/**
 * NEA-2:3 — Channel Connector Model Relationships.
 *
 * Immutable relationship declarations between domain models.
 * Composition metadata only. No runtime graph traversal.
 *
 * Ownership: owned exclusively by NEA-2:3.
 */

import type {
  ChannelConnectorModelKind,
  ChannelConnectorModelRelationship,
} from "./channelConnectorModelTypes.ts";

const relationship = (
  key: string,
  relationshipName: string,
  sourceModelKind: ChannelConnectorModelKind,
  targetModelKind: ChannelConnectorModelKind,
  cardinality: ChannelConnectorModelRelationship["cardinality"],
  required: boolean,
  description: string,
  order: number,
): ChannelConnectorModelRelationship =>
  Object.freeze({
    relationshipId: `NEA-2:3/Relationship/${key}`,
    relationshipName,
    sourceModelKind,
    targetModelKind,
    cardinality,
    required,
    description,
    metadataOnly: true as const,
    immutable: true as const,
    deterministicOrder: order,
  });

/** Canonical immutable model relationship inventory. */
export const ChannelConnectorModelRelationships: readonly ChannelConnectorModelRelationship[] =
  Object.freeze([
    relationship(
      "Definition-Identity",
      "Definition has Identity",
      "ConnectorDefinition",
      "ConnectorIdentity",
      "one-to-one",
      true,
      "Every connector definition declares exactly one identity.",
      1,
    ),
    relationship(
      "Definition-Family",
      "Definition has Family",
      "ConnectorDefinition",
      "ConnectorFamily",
      "one-to-one",
      true,
      "Every connector definition declares exactly one family.",
      2,
    ),
    relationship(
      "Definition-Type",
      "Definition has Type",
      "ConnectorDefinition",
      "ConnectorType",
      "one-to-one",
      true,
      "Every connector definition declares exactly one type.",
      3,
    ),
    relationship(
      "Type-Family",
      "Type belongs to Family",
      "ConnectorType",
      "ConnectorFamily",
      "many-to-one",
      true,
      "Each connector type belongs to exactly one family.",
      4,
    ),
    relationship(
      "Identity-Protocol",
      "Identity uses Protocol",
      "ConnectorIdentity",
      "ConnectorProtocol",
      "one-to-one",
      true,
      "Every identity declares exactly one protocol.",
      5,
    ),
    relationship(
      "Identity-Direction",
      "Identity has Direction",
      "ConnectorIdentity",
      "ConnectorDirection",
      "one-to-one",
      true,
      "Every identity declares exactly one direction.",
      6,
    ),
    relationship(
      "Identity-Status",
      "Identity has Status",
      "ConnectorIdentity",
      "ConnectorStatus",
      "one-to-one",
      true,
      "Every identity declares exactly one status.",
      7,
    ),
    relationship(
      "Definition-Capability",
      "Definition has Capabilities",
      "ConnectorDefinition",
      "ConnectorCapability",
      "one-to-many",
      true,
      "A connector definition declares one or more capabilities.",
      8,
    ),
    relationship(
      "Endpoint-Protocol",
      "Endpoint references Protocol",
      "ConnectorEndpoint",
      "ConnectorProtocol",
      "one-to-one",
      true,
      "Every endpoint references exactly one protocol.",
      9,
    ),
    relationship(
      "Endpoint-Direction",
      "Endpoint references Direction",
      "ConnectorEndpoint",
      "ConnectorDirection",
      "one-to-one",
      true,
      "Every endpoint references exactly one direction.",
      10,
    ),
    relationship(
      "Configuration-Endpoint",
      "Configuration has Endpoint",
      "ConnectorConfiguration",
      "ConnectorEndpoint",
      "one-to-one",
      true,
      "Configuration declares exactly one endpoint description.",
      11,
    ),
    relationship(
      "Configuration-Authentication",
      "Configuration has Authentication",
      "ConnectorConfiguration",
      "ConnectorAuthentication",
      "one-to-one",
      true,
      "Configuration declares exactly one authentication metadata model.",
      12,
    ),
    relationship(
      "Session-Identity",
      "Session references Identity",
      "ConnectorSession",
      "ConnectorIdentity",
      "many-to-one",
      true,
      "Every session references exactly one connector identity.",
      13,
    ),
    relationship(
      "Diagnostics-Health",
      "Diagnostics has Health",
      "ConnectorDiagnostics",
      "ConnectorHealth",
      "one-to-one",
      true,
      "Diagnostics declare exactly one health model.",
      14,
    ),
    relationship(
      "Diagnostics-Event",
      "Diagnostics may include Events",
      "ConnectorDiagnostics",
      "ConnectorEvent",
      "one-to-many",
      false,
      "Diagnostics may reference zero or more event models.",
      15,
    ),
    relationship(
      "Result-Status",
      "Result has Status",
      "ConnectorResult",
      "ConnectorStatus",
      "one-to-one",
      true,
      "Every result declares exactly one status.",
      16,
    ),
    relationship(
      "Result-Diagnostics",
      "Result has Diagnostics",
      "ConnectorResult",
      "ConnectorDiagnostics",
      "one-to-one",
      false,
      "A result may include diagnostics metadata.",
      17,
    ),
    relationship(
      "Summary-Identity",
      "Summary has Identity",
      "ConnectorSummary",
      "ConnectorIdentity",
      "one-to-one",
      true,
      "Every summary declares exactly one identity.",
      18,
    ),
    relationship(
      "Summary-Definition",
      "Summary has Definition",
      "ConnectorSummary",
      "ConnectorDefinition",
      "one-to-one",
      true,
      "Every summary declares exactly one definition.",
      19,
    ),
    relationship(
      "Summary-Result",
      "Summary has Result",
      "ConnectorSummary",
      "ConnectorResult",
      "one-to-one",
      false,
      "A summary may include a result model.",
      20,
    ),
  ]);

/** Canonical immutable relationship catalog. */
export const ChannelConnectorModelRelationshipCatalog = Object.freeze({
  catalogId: "NEA-2:3/ModelRelationshipCatalog",
  sourcePhase: "NEA-2:3" as const,
  relationships: ChannelConnectorModelRelationships,
  relationshipCount: ChannelConnectorModelRelationships.length,
  executesRuntime: false as const,
  metadataOnly: true as const,
  immutable: true as const,
  deterministic: true as const,
});
