/**
 * NEA-1:1 — Executive Gateway Ownership and Boundaries.
 *
 * Ownership, non-ownership, and prohibited-surface declarations.
 * Metadata only — no runtime assignment or enforcement.
 *
 * Ownership: owned exclusively by NEA-1:1.
 */

export const EXECUTIVE_GATEWAY_OWNS = Object.freeze([
  "External interaction intake boundary",
  "External source classification",
  "Channel classification",
  "Gateway envelope contracts",
  "Sender references",
  "Gateway-level context capture",
  "Gateway authentication context",
  "Gateway authorization context",
  "Gateway trust and consent context",
  "Gateway normalization",
  "Gateway-level validation declarations",
  "Routing preparation",
  "Correlation and tracing",
  "Gateway diagnostics",
  "Gateway response contracts",
  "Gateway lifecycle",
  "Gateway policies",
  "Gateway capability declarations",
] as const);

export const EXECUTIVE_GATEWAY_DOES_NOT_OWN = Object.freeze([
  "Business understanding",
  "Semantic interpretation",
  "Knowledge modeling",
  "Business Object creation",
  "Executive reasoning",
  "Executive planning",
  "Executive decisions",
  "Executive orchestration",
  "Visualization",
  "Scene rendering",
  "Internal Assistant conversation architecture",
  "Database persistence",
  "Channel-specific connector implementation",
  "External API implementation",
  "DKL internals",
  "Engine internals",
  "Advisor",
  "Director",
  "EVE",
] as const);

export const EXECUTIVE_GATEWAY_PROHIBITED_SURFACES = Object.freeze([
  "HTTP server implementation",
  "REST route implementation",
  "Webhook implementation",
  "Telegram bot implementation",
  "WhatsApp integration",
  "Slack integration",
  "Teams integration",
  "Email client integration",
  "Voice transcription implementation",
  "MCP server or client implementation",
  "SDK implementation",
  "Database access",
  "Filesystem persistence",
  "Message queue implementation",
  "Event-bus implementation",
  "Authentication execution",
  "Authorization execution",
  "Secret storage",
  "Token validation",
  "AI inference",
  "LLM calls",
  "Prompt execution",
  "Semantic interpretation",
  "Business Object construction",
  "DKL invocation",
  "Engine invocation",
  "Assistant invocation",
  "Advisor invocation",
  "Director invocation",
  "EVE invocation",
  "UI components",
  "React components",
  "Next.js routes",
  "Runtime orchestration",
] as const);

/** Canonical immutable ownership declaration. */
export const ExecutiveGatewayOwnership = Object.freeze({
  ownershipId: "NEA-1:1/ExecutiveGatewayOwnership",
  sourcePhase: "NEA-1:1" as const,
  owns: EXECUTIVE_GATEWAY_OWNS,
  doesNotOwn: EXECUTIVE_GATEWAY_DOES_NOT_OWN,
  ownsCount: EXECUTIVE_GATEWAY_OWNS.length,
  doesNotOwnCount: EXECUTIVE_GATEWAY_DOES_NOT_OWN.length,
  assignsUsers: false as const,
  assignsOrganizations: false as const,
  ownsChannelConnectors: false as const,
  ownsBusinessUnderstanding: false as const,
  ownsInternalAssistantArchitecture: false as const,
  runtimeBehavior: "None" as const,
  metadataOnly: true as const,
  immutable: true as const,
  deterministic: true as const,
});

/** Canonical immutable boundary declarations. */
export const ExecutiveGatewayBoundaries = Object.freeze({
  boundariesId: "NEA-1:1/ExecutiveGatewayBoundaries",
  sourcePhase: "NEA-1:1" as const,
  consumes: Object.freeze([
    "External Channels",
    "External APIs",
    "External Systems",
    "External Users",
    "Approved Agents",
  ] as const),
  provides: Object.freeze([
    "Executive Gateway Foundation",
  ] as const),
  authorizedConsumers: Object.freeze([
    "DKL",
    "Executive Engine",
    "Knowledge Services",
  ] as const),
  architecturalPath: Object.freeze([
    "External Channels / APIs / Systems",
    "NEA — Executive Gateway",
    "Authorized Nexora Consumers (DKL / Engine / Services)",
  ] as const),
  assistantSeparation: Object.freeze({
    internalAssistantBypassesNea: true as const,
    internalAssistantUsesInternalContracts: true as const,
    neaOwnsExternalGatewayBoundaryOnly: true as const,
  }),
  prohibitedSurfaces: EXECUTIVE_GATEWAY_PROHIBITED_SURFACES,
  prohibitedSurfaceCount: EXECUTIVE_GATEWAY_PROHIBITED_SURFACES.length,
  runtimeEnforcement: false as const,
  implementsHttpServer: false as const,
  implementsRestRoutes: false as const,
  implementsWebhooks: false as const,
  implementsTelegramBot: false as const,
  implementsWhatsapp: false as const,
  implementsSlack: false as const,
  implementsTeams: false as const,
  implementsEmailClient: false as const,
  implementsVoiceTranscription: false as const,
  implementsMcp: false as const,
  implementsSdk: false as const,
  accessesDatabase: false as const,
  persistsFilesystem: false as const,
  implementsMessageQueue: false as const,
  implementsEventBus: false as const,
  executesAuthentication: false as const,
  executesAuthorization: false as const,
  storesSecrets: false as const,
  validatesTokens: false as const,
  performsAiInference: false as const,
  callsLlm: false as const,
  executesPrompts: false as const,
  performsSemanticInterpretation: false as const,
  constructsBusinessObjects: false as const,
  invokesDkl: false as const,
  invokesEngine: false as const,
  invokesAssistant: false as const,
  invokesAdvisor: false as const,
  invokesDirector: false as const,
  invokesEve: false as const,
  uiComponents: false as const,
  reactComponents: false as const,
  nextJsRoutes: false as const,
  runtimeOrchestration: false as const,
  importsDeepInternalModules: false as const,
  metadataOnly: true as const,
  immutable: true as const,
  deterministic: true as const,
});
