/**
 * NEA-8:3 — Executive Gateway Suite Model Relationships.
 *
 * Immutable relationship declarations between suite domain models.
 * Composition metadata only. No runtime graph traversal.
 *
 * Ownership: owned exclusively by NEA-8:3.
 */

import type {
  ExecutiveGatewaySuiteModelKind,
  ExecutiveGatewaySuiteModelRelationship,
} from "./executiveGatewaySuiteModelTypes.ts";

const relationship = (
  key: string,
  relationshipName: string,
  sourceModelKind: ExecutiveGatewaySuiteModelKind,
  targetModelKind: ExecutiveGatewaySuiteModelKind,
  cardinality: ExecutiveGatewaySuiteModelRelationship["cardinality"],
  required: boolean,
  description: string,
  order: number,
): ExecutiveGatewaySuiteModelRelationship =>
  Object.freeze({
    relationshipId: `NEA-8:3/Relationship/${key}`,
    relationshipName,
    sourceModelKind,
    targetModelKind,
    cardinality,
    required,
    description,
    metadataOnly: true as const,
    immutable: true as const,
    deterministicOrder: order,
  });

/** Canonical immutable model relationship inventory — exactly twenty. */
export const ExecutiveGatewaySuiteModelRelationships: readonly ExecutiveGatewaySuiteModelRelationship[] =
  Object.freeze([
    relationship(
      "ExecutiveGatewaySuite-SuiteIdentity",
      "Executive Gateway Suite has Suite Identity",
      "ExecutiveGatewaySuite",
      "SuiteIdentity",
      "one-to-one",
      true,
      "Every suite aggregate declares exactly one suite identity.",
      1,
    ),
    relationship(
      "ExecutiveGatewaySuite-SuiteComposition",
      "Executive Gateway Suite has Suite Composition",
      "ExecutiveGatewaySuite",
      "SuiteComposition",
      "one-to-one",
      true,
      "Every suite aggregate declares exactly one suite composition.",
      2,
    ),
    relationship(
      "SuiteComposition-SuiteComponent",
      "Suite Composition has Suite Components",
      "SuiteComposition",
      "SuiteComponent",
      "one-to-many",
      true,
      "Suite composition declares exactly seven suite components.",
      3,
    ),
    relationship(
      "SuiteComponent-SuiteComponentIdentity",
      "Suite Component has Suite Component Identity",
      "SuiteComponent",
      "SuiteComponentIdentity",
      "one-to-one",
      true,
      "Every suite component declares exactly one component identity.",
      4,
    ),
    relationship(
      "SuiteComponent-SuiteDependency",
      "Suite Component has Suite Dependency",
      "SuiteComponent",
      "SuiteDependency",
      "one-to-one",
      true,
      "Every suite component declares exactly one declarative dependency.",
      5,
    ),
    relationship(
      "SuiteComponent-SuitePlatformReference",
      "Suite Component has Suite Platform Reference",
      "SuiteComponent",
      "SuitePlatformReference",
      "one-to-one",
      true,
      "Every suite component preserves exactly one Public Index platform reference.",
      6,
    ),
    relationship(
      "ExecutiveGatewaySuite-SuiteCapability",
      "Executive Gateway Suite has Suite Capabilities",
      "ExecutiveGatewaySuite",
      "SuiteCapability",
      "one-to-many",
      true,
      "Every suite aggregate declares suite capabilities by Registry reference.",
      7,
    ),
    relationship(
      "ExecutiveGatewaySuite-SuiteContract",
      "Executive Gateway Suite has Suite Contracts",
      "ExecutiveGatewaySuite",
      "SuiteContract",
      "one-to-many",
      true,
      "Every suite aggregate declares suite contracts by Registry reference.",
      8,
    ),
    relationship(
      "ExecutiveGatewaySuite-SuiteLifecycle",
      "Executive Gateway Suite has Suite Lifecycle",
      "ExecutiveGatewaySuite",
      "SuiteLifecycle",
      "one-to-one",
      true,
      "Every suite aggregate declares suite lifecycle by Registry reference.",
      9,
    ),
    relationship(
      "ExecutiveGatewaySuite-SuitePolicy",
      "Executive Gateway Suite has Suite Policies",
      "ExecutiveGatewaySuite",
      "SuitePolicy",
      "one-to-many",
      true,
      "Every suite aggregate declares suite policies by Registry reference.",
      10,
    ),
    relationship(
      "ExecutiveGatewaySuite-SuiteInventory",
      "Executive Gateway Suite has Suite Inventory",
      "ExecutiveGatewaySuite",
      "SuiteInventory",
      "one-to-one",
      true,
      "Every suite aggregate declares exactly one suite inventory.",
      11,
    ),
    relationship(
      "ExecutiveGatewaySuite-SuiteMetadata",
      "Executive Gateway Suite has Suite Metadata",
      "ExecutiveGatewaySuite",
      "SuiteMetadata",
      "one-to-one",
      true,
      "Every suite aggregate declares exactly one suite metadata structure.",
      12,
    ),
    relationship(
      "ExecutiveGatewaySuite-SuiteStatus",
      "Executive Gateway Suite has Suite Statuses",
      "ExecutiveGatewaySuite",
      "SuiteStatus",
      "one-to-many",
      true,
      "Every suite aggregate declares suite statuses by Registry reference.",
      13,
    ),
    relationship(
      "ExecutiveGatewaySuite-SuiteVersion",
      "Executive Gateway Suite has Suite Version",
      "ExecutiveGatewaySuite",
      "SuiteVersion",
      "one-to-one",
      true,
      "Every suite aggregate declares exactly one suite version structure.",
      14,
    ),
    relationship(
      "ExecutiveGatewaySuite-SuiteReadiness",
      "Executive Gateway Suite has Suite Readiness",
      "ExecutiveGatewaySuite",
      "SuiteReadiness",
      "one-to-one",
      true,
      "Every suite aggregate declares exactly one suite readiness structure.",
      15,
    ),
    relationship(
      "ExecutiveGatewaySuite-SuitePublicApiInventory",
      "Executive Gateway Suite has Suite Public API Inventory",
      "ExecutiveGatewaySuite",
      "SuitePublicApiInventory",
      "one-to-one",
      true,
      "Every suite aggregate declares public API inventory derived from Registry.",
      16,
    ),
    relationship(
      "ExecutiveGatewaySuite-SuiteValidationTarget",
      "Executive Gateway Suite has Suite Validation Target",
      "ExecutiveGatewaySuite",
      "SuiteValidationTarget",
      "one-to-one",
      true,
      "Every suite aggregate declares a validation target for NEA-8:4.",
      17,
    ),
    relationship(
      "ExecutiveGatewaySuite-SuiteRelationship",
      "Executive Gateway Suite has Suite Relationships",
      "ExecutiveGatewaySuite",
      "SuiteRelationship",
      "one-to-many",
      true,
      "Every suite aggregate declares declarative suite relationships.",
      18,
    ),
    relationship(
      "SuiteSummary-ExecutiveGatewaySuite",
      "Suite Summary summarizes Executive Gateway Suite",
      "SuiteSummary",
      "ExecutiveGatewaySuite",
      "one-to-one",
      true,
      "Suite summary aggregates the Executive Gateway Suite model.",
      19,
    ),
    relationship(
      "SuiteSummary-SuitePublicApiInventory",
      "Suite Summary includes Suite Public API Inventory",
      "SuiteSummary",
      "SuitePublicApiInventory",
      "one-to-one",
      true,
      "Suite summary includes public API inventory totals from Registry.",
      20,
    ),
  ]);

/** Canonical immutable model relationship catalog. */
export const ExecutiveGatewaySuiteModelRelationshipCatalog = Object.freeze({
  catalogId: "NEA-8:3/ModelRelationshipCatalog",
  sourcePhase: "NEA-8:3" as const,
  relationships: ExecutiveGatewaySuiteModelRelationships,
  relationshipCount: ExecutiveGatewaySuiteModelRelationships.length,
  executesRelationships: false as const,
  metadataOnly: true as const,
  immutable: true as const,
  deterministic: true as const,
});
