/**
 * NEA-1:3 — Executive Gateway Model Relationships.
 *
 * Immutable relationship declarations between domain models.
 * Composition metadata only. No runtime graph traversal.
 *
 * Ownership: owned exclusively by NEA-1:3.
 */

import type { ExecutiveGatewayModelRelationship } from "./executiveGatewayModelTypes.ts";

const relationship = (
  key: string,
  relationshipName: string,
  sourceModelKind: ExecutiveGatewayModelRelationship["sourceModelKind"],
  targetModelKind: ExecutiveGatewayModelRelationship["targetModelKind"],
  cardinality: ExecutiveGatewayModelRelationship["cardinality"],
  required: boolean,
  description: string,
  order: number,
): ExecutiveGatewayModelRelationship =>
  Object.freeze({
    relationshipId: `NEA-1:3/Relationship/${key}`,
    relationshipName,
    sourceModelKind,
    targetModelKind,
    cardinality,
    required,
    description,
    metadataOnly: true as const,
    immutable: true as const,
    deterministicOrder: order,
  });

/** Canonical immutable model relationship inventory. */
export const ExecutiveGatewayModelRelationships: readonly ExecutiveGatewayModelRelationship[] =
  Object.freeze([
    relationship(
      "Request-Identity",
      "Request has Identity",
      "GatewayRequest",
      "GatewayIdentity",
      "one-to-one",
      true,
      "Every request declares exactly one gateway identity.",
      1,
    ),
    relationship(
      "Request-Sender",
      "Request has Sender",
      "GatewayRequest",
      "GatewaySender",
      "one-to-one",
      true,
      "Every request declares exactly one sender.",
      2,
    ),
    relationship(
      "Request-Context",
      "Request has Context",
      "GatewayRequest",
      "GatewayContext",
      "one-to-one",
      true,
      "Every request declares exactly one gateway context.",
      3,
    ),
    relationship(
      "Context-Tenant",
      "Context has Tenant",
      "GatewayContext",
      "GatewayTenant",
      "one-to-one",
      true,
      "Context composes exactly one tenant model.",
      4,
    ),
    relationship(
      "Context-Workspace",
      "Context has Workspace",
      "GatewayContext",
      "GatewayWorkspace",
      "one-to-one",
      true,
      "Context composes exactly one workspace model.",
      5,
    ),
    relationship(
      "Request-Session",
      "Request has Session",
      "GatewayRequest",
      "GatewaySession",
      "one-to-one",
      true,
      "Every request declares exactly one session.",
      6,
    ),
    relationship(
      "Request-Conversation",
      "Request has Conversation",
      "GatewayRequest",
      "GatewayConversation",
      "one-to-one",
      true,
      "Every request declares exactly one conversation.",
      7,
    ),
    relationship(
      "Conversation-Session",
      "Conversation references Session",
      "GatewayConversation",
      "GatewaySession",
      "many-to-one",
      true,
      "Conversations reference a session.",
      8,
    ),
    relationship(
      "Request-Payload",
      "Request has Payload",
      "GatewayRequest",
      "GatewayPayload",
      "one-to-one",
      true,
      "Every request declares exactly one payload.",
      9,
    ),
    relationship(
      "Request-Attachments",
      "Request has Attachments",
      "GatewayRequest",
      "GatewayAttachment",
      "one-to-many",
      false,
      "A request may declare zero or more attachments.",
      10,
    ),
    relationship(
      "Request-Authentication",
      "Request has Authentication",
      "GatewayRequest",
      "GatewayAuthentication",
      "one-to-one",
      true,
      "Every request declares authentication metadata.",
      11,
    ),
    relationship(
      "Request-Authorization",
      "Request has Authorization",
      "GatewayRequest",
      "GatewayAuthorization",
      "one-to-one",
      true,
      "Every request declares authorization metadata.",
      12,
    ),
    relationship(
      "Request-Trust",
      "Request has Trust",
      "GatewayRequest",
      "GatewayTrust",
      "one-to-one",
      true,
      "Every request declares trust metadata.",
      13,
    ),
    relationship(
      "Request-Consent",
      "Request has Consent",
      "GatewayRequest",
      "GatewayConsent",
      "one-to-one",
      true,
      "Every request declares consent metadata.",
      14,
    ),
    relationship(
      "Request-Metadata",
      "Request has Metadata",
      "GatewayRequest",
      "GatewayMetadata",
      "one-to-one",
      true,
      "Every request declares shared metadata.",
      15,
    ),
    relationship(
      "Response-Request",
      "Response references Request",
      "GatewayResponse",
      "GatewayRequest",
      "many-to-one",
      true,
      "Every response references a request.",
      16,
    ),
    relationship(
      "Response-ProcessingResult",
      "Response has Processing Result",
      "GatewayResponse",
      "GatewayProcessingResult",
      "one-to-one",
      true,
      "Every response declares exactly one processing result.",
      17,
    ),
    relationship(
      "Response-Routing",
      "Response has Routing",
      "GatewayResponse",
      "GatewayRouting",
      "one-to-one",
      true,
      "Every response declares routing metadata.",
      18,
    ),
    relationship(
      "Response-Validation",
      "Response has Validation",
      "GatewayResponse",
      "GatewayValidation",
      "one-to-one",
      true,
      "Every response declares validation outcome metadata.",
      19,
    ),
    relationship(
      "Response-Diagnostics",
      "Response has Diagnostics",
      "GatewayResponse",
      "GatewayDiagnostic",
      "one-to-many",
      false,
      "A response may declare zero or more diagnostics.",
      20,
    ),
    relationship(
      "Routing-Request",
      "Routing references Request",
      "GatewayRouting",
      "GatewayRequest",
      "many-to-one",
      true,
      "Routing declarations reference a request.",
      21,
    ),
    relationship(
      "ProcessingResult-Request",
      "Processing Result references Request",
      "GatewayProcessingResult",
      "GatewayRequest",
      "many-to-one",
      true,
      "Processing results reference a request.",
      22,
    ),
  ]);

/** Canonical immutable relationship catalog. */
export const ExecutiveGatewayModelRelationshipCatalog = Object.freeze({
  catalogId: "NEA-1:3/ModelRelationshipCatalog",
  sourcePhase: "NEA-1:3" as const,
  relationships: ExecutiveGatewayModelRelationships,
  relationshipCount: ExecutiveGatewayModelRelationships.length,
  executesGraphTraversal: false as const,
  metadataOnly: true as const,
  immutable: true as const,
  deterministic: true as const,
});
