/**
 * NEA-5:3 — Gateway Routing Model Relationships.
 *
 * Immutable relationship declarations between domain models.
 * Composition metadata only. No runtime graph traversal.
 *
 * Ownership: owned exclusively by NEA-5:3.
 */

import type {
  GatewayRoutingModelKind,
  GatewayRoutingModelRelationship,
} from "./gatewayRoutingModelTypes.ts";

const relationship = (
  key: string,
  relationshipName: string,
  sourceModelKind: GatewayRoutingModelKind,
  targetModelKind: GatewayRoutingModelKind,
  cardinality: GatewayRoutingModelRelationship["cardinality"],
  required: boolean,
  description: string,
  order: number,
): GatewayRoutingModelRelationship =>
  Object.freeze({
    relationshipId: `NEA-5:3/Relationship/${key}`,
    relationshipName,
    sourceModelKind,
    targetModelKind,
    cardinality,
    required,
    description,
    metadataOnly: true as const,
    immutable: true as const,
    deterministicOrder: order,
  });

/** Canonical immutable model relationship inventory — exactly twenty. */
export const GatewayRoutingModelRelationships: readonly GatewayRoutingModelRelationship[] =
  Object.freeze([
    relationship(
      "Identity-Definition",
      "Route Identity has Route Definition",
      "RouteIdentity",
      "RouteDefinition",
      "one-to-one",
      true,
      "Every route identity declares exactly one route definition.",
      1,
    ),
    relationship(
      "Definition-Destination",
      "Route Definition has Destination",
      "RouteDefinition",
      "RouteDestination",
      "one-to-one",
      true,
      "Every route definition declares exactly one destination.",
      2,
    ),
    relationship(
      "Definition-Strategy",
      "Route Definition has Strategy",
      "RouteDefinition",
      "RouteStrategy",
      "one-to-one",
      true,
      "Every route definition declares exactly one strategy.",
      3,
    ),
    relationship(
      "Definition-Priority",
      "Route Definition has Priority",
      "RouteDefinition",
      "RoutePriority",
      "one-to-one",
      true,
      "Every route definition declares exactly one priority.",
      4,
    ),
    relationship(
      "Definition-Policy",
      "Route Definition has Policies",
      "RouteDefinition",
      "RoutePolicy",
      "one-to-many",
      true,
      "A route definition declares one or more policies.",
      5,
    ),
    relationship(
      "Definition-Capability",
      "Route Definition has Capabilities",
      "RouteDefinition",
      "RouteCapability",
      "one-to-many",
      true,
      "A route definition declares one or more capabilities.",
      6,
    ),
    relationship(
      "Definition-Lifecycle",
      "Route Definition has Lifecycle",
      "RouteDefinition",
      "RouteLifecycle",
      "one-to-one",
      true,
      "Every route definition declares exactly one lifecycle.",
      7,
    ),
    relationship(
      "Request-Context",
      "Route Request has Context",
      "RouteRequest",
      "RouteContext",
      "one-to-one",
      true,
      "Every route request declares exactly one context.",
      8,
    ),
    relationship(
      "Request-Identity",
      "Route Request has Identity",
      "RouteRequest",
      "RouteIdentity",
      "one-to-one",
      true,
      "Every route request declares exactly one route identity.",
      9,
    ),
    relationship(
      "Request-Resolution",
      "Route Request has Resolution",
      "RouteRequest",
      "RouteResolution",
      "one-to-one",
      true,
      "Every route request declares exactly one resolution.",
      10,
    ),
    relationship(
      "Resolution-Destination",
      "Route Resolution has Destination",
      "RouteResolution",
      "RouteDestination",
      "one-to-one",
      true,
      "Every route resolution declares exactly one destination.",
      11,
    ),
    relationship(
      "Resolution-Decision",
      "Route Resolution has Decision",
      "RouteResolution",
      "RouteDecision",
      "one-to-one",
      true,
      "Every route resolution declares exactly one decision.",
      12,
    ),
    relationship(
      "Response-Result",
      "Route Response has Result",
      "RouteResponse",
      "RouteResult",
      "one-to-one",
      true,
      "Every route response declares exactly one result.",
      13,
    ),
    relationship(
      "Response-Diagnostics",
      "Route Response has Diagnostics",
      "RouteResponse",
      "RouteDiagnostics",
      "one-to-many",
      false,
      "A route response may declare diagnostics.",
      14,
    ),
    relationship(
      "Summary-Response",
      "Route Summary has Response",
      "RouteSummary",
      "RouteResponse",
      "one-to-one",
      true,
      "Every route summary declares exactly one response.",
      15,
    ),
    relationship(
      "Summary-Definition",
      "Route Summary has Definition",
      "RouteSummary",
      "RouteDefinition",
      "one-to-one",
      true,
      "Every route summary declares exactly one definition.",
      16,
    ),
    relationship(
      "Configuration-Strategy",
      "Route Configuration has Strategy",
      "RouteConfiguration",
      "RouteStrategy",
      "one-to-one",
      true,
      "Every route configuration declares exactly one strategy.",
      17,
    ),
    relationship(
      "Reference-Identity",
      "Route Reference has Identity",
      "RouteReference",
      "RouteIdentity",
      "one-to-one",
      true,
      "Every route reference declares exactly one route identity.",
      18,
    ),
    relationship(
      "Metadata-Definition",
      "Route Metadata has Definition",
      "RouteMetadata",
      "RouteDefinition",
      "one-to-one",
      true,
      "Every route metadata declares exactly one definition.",
      19,
    ),
    relationship(
      "Diagnostics-Result",
      "Route Diagnostics belongs to Result",
      "RouteDiagnostics",
      "RouteResult",
      "many-to-one",
      true,
      "Every route diagnostic belongs to exactly one result.",
      20,
    ),
  ]);

/** Canonical immutable relationship catalog. */
export const GatewayRoutingModelRelationshipCatalog = Object.freeze({
  catalogId: "NEA-5:3/ModelRelationshipCatalog",
  sourcePhase: "NEA-5:3" as const,
  relationships: GatewayRoutingModelRelationships,
  relationshipCount: GatewayRoutingModelRelationships.length,
  executesRuntime: false as const,
  metadataOnly: true as const,
  immutable: true as const,
  deterministic: true as const,
});
