/**
 * NEA-7:3 — Intake Orchestration Model Relationships.
 *
 * Immutable relationship declarations between domain models.
 * Composition metadata only. No runtime graph traversal.
 *
 * Ownership: owned exclusively by NEA-7:3.
 */

import type {
  IntakeOrchestrationModelKind,
  IntakeOrchestrationModelRelationship,
} from "./intakeOrchestrationModelTypes.ts";

const relationship = (
  key: string,
  relationshipName: string,
  sourceModelKind: IntakeOrchestrationModelKind,
  targetModelKind: IntakeOrchestrationModelKind,
  cardinality: IntakeOrchestrationModelRelationship["cardinality"],
  required: boolean,
  description: string,
  order: number,
): IntakeOrchestrationModelRelationship =>
  Object.freeze({
    relationshipId: `NEA-7:3/Relationship/${key}`,
    relationshipName,
    sourceModelKind,
    targetModelKind,
    cardinality,
    required,
    description,
    metadataOnly: true as const,
    immutable: true as const,
    deterministicOrder: order,
  });

/** Canonical immutable model relationship inventory — exactly twenty. */
export const IntakeOrchestrationModelRelationships: readonly IntakeOrchestrationModelRelationship[] =
  Object.freeze([
    relationship(
      "ExecutiveIntakePackage-IntakeIdentity",
      "Executive Intake Package has Intake Identity",
      "ExecutiveIntakePackage",
      "IntakeIdentity",
      "one-to-one",
      true,
      "Every executive intake package declares exactly one intake identity.",
      1,
    ),
    relationship(
      "ExecutiveIntakePackage-IntakeSource",
      "Executive Intake Package has Intake Source",
      "ExecutiveIntakePackage",
      "IntakeSource",
      "one-to-one",
      true,
      "Every executive intake package declares exactly one intake source.",
      2,
    ),
    relationship(
      "ExecutiveIntakePackage-IntakeContext",
      "Executive Intake Package has Intake Context",
      "ExecutiveIntakePackage",
      "IntakeContext",
      "one-to-one",
      true,
      "Every executive intake package declares exactly one intake context.",
      3,
    ),
    relationship(
      "ExecutiveIntakePackage-MessageReference",
      "Executive Intake Package has Message Reference",
      "ExecutiveIntakePackage",
      "MessageReference",
      "one-to-one",
      true,
      "Every executive intake package declares exactly one message reference.",
      4,
    ),
    relationship(
      "ExecutiveIntakePackage-SessionReference",
      "Executive Intake Package has Session Reference",
      "ExecutiveIntakePackage",
      "SessionReference",
      "one-to-one",
      true,
      "Every executive intake package declares exactly one session reference.",
      5,
    ),
    relationship(
      "ExecutiveIntakePackage-ConversationReference",
      "Executive Intake Package has Conversation Reference",
      "ExecutiveIntakePackage",
      "ConversationReference",
      "one-to-one",
      true,
      "Every executive intake package declares exactly one conversation reference.",
      6,
    ),
    relationship(
      "ExecutiveIntakePackage-AuthenticationReference",
      "Executive Intake Package has Authentication Reference",
      "ExecutiveIntakePackage",
      "AuthenticationReference",
      "one-to-one",
      true,
      "Every executive intake package declares exactly one authentication reference.",
      7,
    ),
    relationship(
      "ExecutiveIntakePackage-RoutingReference",
      "Executive Intake Package has Routing Reference",
      "ExecutiveIntakePackage",
      "RoutingReference",
      "one-to-one",
      true,
      "Every executive intake package declares exactly one routing reference.",
      8,
    ),
    relationship(
      "ExecutiveIntakePackage-ConnectorReference",
      "Executive Intake Package has Connector Reference",
      "ExecutiveIntakePackage",
      "ConnectorReference",
      "one-to-one",
      true,
      "Every executive intake package declares exactly one connector reference.",
      9,
    ),
    relationship(
      "ExecutiveIntakePackage-WorkspaceReference",
      "Executive Intake Package has Workspace Reference",
      "ExecutiveIntakePackage",
      "WorkspaceReference",
      "one-to-one",
      true,
      "Every executive intake package declares exactly one workspace reference.",
      10,
    ),
    relationship(
      "ExecutiveIntakePackage-TenantReference",
      "Executive Intake Package has Tenant Reference",
      "ExecutiveIntakePackage",
      "TenantReference",
      "one-to-one",
      true,
      "Every executive intake package declares exactly one tenant reference.",
      11,
    ),
    relationship(
      "ExecutiveIntakePackage-CorrelationReference",
      "Executive Intake Package has Correlation Reference",
      "ExecutiveIntakePackage",
      "CorrelationReference",
      "one-to-one",
      true,
      "Every executive intake package declares exactly one correlation reference.",
      12,
    ),
    relationship(
      "ExecutiveIntakePackage-TraceReference",
      "Executive Intake Package has Trace Reference",
      "ExecutiveIntakePackage",
      "TraceReference",
      "one-to-one",
      true,
      "Every executive intake package declares exactly one trace reference.",
      13,
    ),
    relationship(
      "ExecutiveIntakePackage-AttachmentReference",
      "Executive Intake Package has Attachment Reference",
      "ExecutiveIntakePackage",
      "AttachmentReference",
      "one-to-many",
      false,
      "An executive intake package may declare zero or more attachment references.",
      14,
    ),
    relationship(
      "ExecutiveIntakePackage-IntakeMetadata",
      "Executive Intake Package has Intake Metadata",
      "ExecutiveIntakePackage",
      "IntakeMetadata",
      "one-to-one",
      true,
      "Every executive intake package declares exactly one intake metadata structure.",
      15,
    ),
    relationship(
      "ExecutiveIntakePackage-IntakeConfiguration",
      "Executive Intake Package has Intake Configuration",
      "ExecutiveIntakePackage",
      "IntakeConfiguration",
      "one-to-one",
      true,
      "Every executive intake package declares exactly one intake configuration.",
      16,
    ),
    relationship(
      "ExecutiveIntakePackage-IntakeDiagnostics",
      "Executive Intake Package has Intake Diagnostics",
      "ExecutiveIntakePackage",
      "IntakeDiagnostics",
      "one-to-one",
      true,
      "Every executive intake package declares exactly one intake diagnostics structure.",
      17,
    ),
    relationship(
      "ExecutiveIntakePackage-IntakeResult",
      "Executive Intake Package has Intake Result",
      "ExecutiveIntakePackage",
      "IntakeResult",
      "one-to-one",
      true,
      "Every executive intake package declares exactly one intake result.",
      18,
    ),
    relationship(
      "IntakeSummary-ExecutiveIntakePackage",
      "Intake Summary references Executive Intake Package",
      "IntakeSummary",
      "ExecutiveIntakePackage",
      "one-to-one",
      true,
      "Every intake summary references exactly one executive intake package.",
      19,
    ),
    relationship(
      "IntakeSummary-IntakeResult",
      "Intake Summary references Intake Result",
      "IntakeSummary",
      "IntakeResult",
      "one-to-one",
      true,
      "Every intake summary references exactly one intake result.",
      20,
    ),
  ]);

/** Canonical immutable model relationship catalog. */
export const IntakeOrchestrationModelRelationshipCatalog = Object.freeze({
  catalogId: "NEA-7:3/ModelRelationshipCatalog",
  sourcePhase: "NEA-7:3" as const,
  relationships: IntakeOrchestrationModelRelationships,
  relationshipCount: IntakeOrchestrationModelRelationships.length,
  executesRuntime: false as const,
  metadataOnly: true as const,
  immutable: true as const,
  deterministic: true as const,
});
