/**
 * NEA-6:2 — Message Normalization Registry Ownership.
 *
 * Ownership and boundary declarations for the Message Normalization Registry.
 * Metadata only — no runtime assignment.
 *
 * Ownership: owned exclusively by NEA-6:2.
 */

export const MESSAGE_NORMALIZATION_REGISTRY_OWNS = Object.freeze([
  "Message Identity Registry",
  "Payload Registry",
  "Metadata Registry",
  "Mapping Registry",
  "Normalization Policy Registry",
  "Registry Metadata",
  "Status Registry",
  "Registry Collections",
  "Registry Summary",
] as const);

export const MESSAGE_NORMALIZATION_REGISTRY_DOES_NOT_OWN = Object.freeze([
  "Executive Message Contract",
  "Runtime Normalization",
  "Runtime Parsing",
  "AI",
  "Intent Detection",
  "DKL",
  "Executive Engine",
  "Database",
  "Storage",
  "Routing",
  "Security",
  "Connector Runtime",
  "Assistant",
  "Advisor",
  "Director",
  "EVE",
  "Foundation Contracts",
  "Foundation Ownership",
  "Foundation Boundaries",
  "Domain Models",
  "Validation Rules",
] as const);

export const MESSAGE_NORMALIZATION_REGISTRY_PROHIBITED_SURFACES = Object.freeze([
  "Runtime Normalization",
  "Payload Parsing",
  "AI",
  "Intent Recognition",
  "Entity Extraction",
  "Business Understanding",
  "Routing",
  "HTTP",
  "REST",
  "WebSockets",
  "Database",
  "Queue",
  "Event Bus",
  "Authentication",
  "Authorization",
  "Storage",
  "React",
  "Next.js",
  "DKL invocation",
  "Executive Engine invocation",
  "Advisor invocation",
  "Director invocation",
  "EVE invocation",
] as const);

/** Canonical immutable registry ownership declaration. */
export const MessageNormalizationRegistryOwnership = Object.freeze({
  ownershipId: "NEA-6:2/MessageNormalizationRegistryOwnership",
  sourcePhase: "NEA-6:2" as const,
  owns: MESSAGE_NORMALIZATION_REGISTRY_OWNS,
  doesNotOwn: MESSAGE_NORMALIZATION_REGISTRY_DOES_NOT_OWN,
  ownsCount: MESSAGE_NORMALIZATION_REGISTRY_OWNS.length,
  doesNotOwnCount: MESSAGE_NORMALIZATION_REGISTRY_DOES_NOT_OWN.length,
  ownsExecutiveMessageContract: false as const,
  ownsRuntimeNormalization: false as const,
  ownsRuntimeParsing: false as const,
  ownsAi: false as const,
  ownsIntentDetection: false as const,
  ownsDkl: false as const,
  ownsExecutiveEngine: false as const,
  ownsDatabase: false as const,
  ownsStorage: false as const,
  ownsRouting: false as const,
  ownsSecurity: false as const,
  ownsConnectorRuntime: false as const,
  ownsAssistant: false as const,
  ownsAdvisor: false as const,
  ownsDirector: false as const,
  ownsEve: false as const,
  ownsFoundationContracts: false as const,
  ownsDomainModels: false as const,
  ownsValidationRules: false as const,
  runtimeBehavior: "None" as const,
  metadataOnly: true as const,
  immutable: true as const,
  deterministic: true as const,
});

/** Canonical immutable registry boundary declarations. */
export const MessageNormalizationRegistryBoundaries = Object.freeze({
  boundariesId: "NEA-6:2/MessageNormalizationRegistryBoundaries",
  sourcePhase: "NEA-6:2" as const,
  consumes: Object.freeze([
    "NEA-6:1 Message Normalization Foundation",
  ] as const),
  provides: Object.freeze(["Message Normalization Registry"] as const),
  prohibitedSurfaces: MESSAGE_NORMALIZATION_REGISTRY_PROHIBITED_SURFACES,
  prohibitedSurfaceCount:
    MESSAGE_NORMALIZATION_REGISTRY_PROHIBITED_SURFACES.length,
  implementsRuntimeNormalization: false as const,
  parsesPayloads: false as const,
  performsAi: false as const,
  recognizesIntent: false as const,
  extractsEntities: false as const,
  interpretsBusinessMeaning: false as const,
  modifiesUserIntent: false as const,
  implementsRouting: false as const,
  implementsHttp: false as const,
  implementsRest: false as const,
  implementsWebSockets: false as const,
  accessesDatabase: false as const,
  implementsQueue: false as const,
  implementsEventBus: false as const,
  executesAuthentication: false as const,
  executesAuthorization: false as const,
  implementsStorage: false as const,
  invokesDkl: false as const,
  invokesExecutiveEngine: false as const,
  invokesAdvisor: false as const,
  invokesDirector: false as const,
  invokesEve: false as const,
  uiComponents: false as const,
  reactComponents: false as const,
  nextJsRoutes: false as const,
  duplicatesFoundationValues: false as const,
  reconstructsFoundation: false as const,
  runtimeEnforcement: false as const,
  metadataOnly: true as const,
  immutable: true as const,
  deterministic: true as const,
});
