/**
 * NEA-6:3 — Message Normalization Model Relationships.
 *
 * Immutable relationship declarations between domain models.
 * Composition metadata only. No runtime graph traversal.
 *
 * Ownership: owned exclusively by NEA-6:3.
 */

import type {
  MessageNormalizationModelKind,
  MessageNormalizationModelRelationship,
} from "./messageNormalizationModelTypes.ts";

const relationship = (
  key: string,
  relationshipName: string,
  sourceModelKind: MessageNormalizationModelKind,
  targetModelKind: MessageNormalizationModelKind,
  cardinality: MessageNormalizationModelRelationship["cardinality"],
  required: boolean,
  description: string,
  order: number,
): MessageNormalizationModelRelationship =>
  Object.freeze({
    relationshipId: `NEA-6:3/Relationship/${key}`,
    relationshipName,
    sourceModelKind,
    targetModelKind,
    cardinality,
    required,
    description,
    metadataOnly: true as const,
    immutable: true as const,
    deterministicOrder: order,
  });

/** Canonical immutable model relationship inventory — exactly twenty. */
export const MessageNormalizationModelRelationships: readonly MessageNormalizationModelRelationship[] =
  Object.freeze([
    relationship(
      "ExecutiveMessage-MessageIdentity",
      "Executive Message has Message Identity",
      "ExecutiveMessage",
      "MessageIdentity",
      "one-to-one",
      true,
      "Every executive message declares exactly one message identity.",
      1,
    ),
    relationship(
      "ExecutiveMessage-Sender",
      "Executive Message has Sender",
      "ExecutiveMessage",
      "Sender",
      "one-to-one",
      true,
      "Every executive message declares exactly one sender.",
      2,
    ),
    relationship(
      "ExecutiveMessage-Recipient",
      "Executive Message has Recipient",
      "ExecutiveMessage",
      "Recipient",
      "one-to-one",
      true,
      "Every executive message declares exactly one recipient.",
      3,
    ),
    relationship(
      "ExecutiveMessage-Payload",
      "Executive Message has Payload",
      "ExecutiveMessage",
      "Payload",
      "one-to-one",
      true,
      "Every executive message declares exactly one payload.",
      4,
    ),
    relationship(
      "ExecutiveMessage-Metadata",
      "Executive Message has Metadata",
      "ExecutiveMessage",
      "Metadata",
      "one-to-one",
      true,
      "Every executive message declares exactly one metadata structure.",
      5,
    ),
    relationship(
      "ExecutiveMessage-Context",
      "Executive Message has Context",
      "ExecutiveMessage",
      "Context",
      "one-to-one",
      true,
      "Every executive message declares exactly one context.",
      6,
    ),
    relationship(
      "ExecutiveMessage-Attachment",
      "Executive Message has Attachments",
      "ExecutiveMessage",
      "Attachment",
      "one-to-many",
      false,
      "An executive message may declare zero or more attachments.",
      7,
    ),
    relationship(
      "ExecutiveMessage-Correlation",
      "Executive Message has Correlation",
      "ExecutiveMessage",
      "Correlation",
      "one-to-one",
      true,
      "Every executive message declares exactly one correlation.",
      8,
    ),
    relationship(
      "Correlation-Trace",
      "Correlation has Trace",
      "Correlation",
      "Trace",
      "one-to-one",
      true,
      "Every correlation declares exactly one trace.",
      9,
    ),
    relationship(
      "ExecutiveMessage-DeliveryMetadata",
      "Executive Message has Delivery Metadata",
      "ExecutiveMessage",
      "DeliveryMetadata",
      "one-to-one",
      true,
      "Every executive message declares exactly one delivery metadata structure.",
      10,
    ),
    relationship(
      "ExecutiveMessage-SessionReference",
      "Executive Message has Session Reference",
      "ExecutiveMessage",
      "SessionReference",
      "one-to-one",
      true,
      "Every executive message declares exactly one session reference.",
      11,
    ),
    relationship(
      "ExecutiveMessage-ConversationReference",
      "Executive Message has Conversation Reference",
      "ExecutiveMessage",
      "ConversationReference",
      "one-to-one",
      true,
      "Every executive message declares exactly one conversation reference.",
      12,
    ),
    relationship(
      "Context-WorkspaceReference",
      "Context has Workspace Reference",
      "Context",
      "WorkspaceReference",
      "one-to-one",
      true,
      "Every context declares exactly one workspace reference.",
      13,
    ),
    relationship(
      "Context-TenantReference",
      "Context has Tenant Reference",
      "Context",
      "TenantReference",
      "one-to-one",
      true,
      "Every context declares exactly one tenant reference.",
      14,
    ),
    relationship(
      "Context-ChannelReference",
      "Context has Channel Reference",
      "Context",
      "ChannelReference",
      "one-to-one",
      true,
      "Every context declares exactly one channel reference.",
      15,
    ),
    relationship(
      "Context-ConnectorReference",
      "Context has Connector Reference",
      "Context",
      "ConnectorReference",
      "one-to-one",
      true,
      "Every context declares exactly one connector reference.",
      16,
    ),
    relationship(
      "Payload-PayloadType",
      "Payload has Payload Type",
      "Payload",
      "PayloadType",
      "one-to-one",
      true,
      "Every payload declares exactly one payload type.",
      17,
    ),
    relationship(
      "ExecutiveMessage-NormalizationResult",
      "Executive Message has Normalization Result",
      "ExecutiveMessage",
      "NormalizationResult",
      "one-to-one",
      true,
      "Every executive message declares exactly one normalization result.",
      18,
    ),
    relationship(
      "MessageSummary-ExecutiveMessage",
      "Message Summary has Executive Message",
      "MessageSummary",
      "ExecutiveMessage",
      "one-to-one",
      true,
      "Every message summary declares exactly one executive message.",
      19,
    ),
    relationship(
      "MessageSummary-NormalizationResult",
      "Message Summary has Normalization Result",
      "MessageSummary",
      "NormalizationResult",
      "one-to-one",
      true,
      "Every message summary declares exactly one normalization result.",
      20,
    ),
  ]);

/** Canonical immutable relationship catalog. */
export const MessageNormalizationModelRelationshipCatalog = Object.freeze({
  catalogId: "NEA-6:3/ModelRelationshipCatalog",
  sourcePhase: "NEA-6:3" as const,
  relationships: MessageNormalizationModelRelationships,
  relationshipCount: MessageNormalizationModelRelationships.length,
  executesRuntime: false as const,
  metadataOnly: true as const,
  immutable: true as const,
  deterministic: true as const,
});
