/**
 * NEA-4:3 — Security Gateway Model Ownership.
 *
 * Ownership and boundary declarations for the Security Gateway Model.
 * Metadata only — no runtime assignment.
 *
 * Ownership: owned exclusively by NEA-4:3.
 */

export const SECURITY_GATEWAY_MODEL_OWNS = Object.freeze([
  "Security Domain Models",
  "Model Composition",
  "Model Relationships",
  "Model Metadata",
  "Security Identity Model Instances",
  "Security Principal Model Instances",
  "Model Lifecycle",
  "Model Summary",
] as const);

export const SECURITY_GATEWAY_MODEL_DOES_NOT_OWN = Object.freeze([
  "Authentication Execution",
  "Authorization Execution",
  "Permission Evaluation",
  "Trust Evaluation",
  "Consent Verification",
  "Identity Verification",
  "Login or Logout",
  "OAuth, JWT, SAML, OIDC, or MFA Runtime",
  "Encryption",
  "Secret or Key Management",
  "Token Generation or Validation",
  "Persistence",
  "Gateway Routing",
  "DKL",
  "Executive Engine",
  "Assistant",
  "Advisor",
  "Director",
  "EVE",
  "Registry Collections",
  "Foundation Contracts",
] as const);

export const SECURITY_GATEWAY_MODEL_PROHIBITED_SURFACES = Object.freeze([
  "Login or Logout",
  "Authentication Engine",
  "Authorization Engine",
  "Permission Engine",
  "Policy Engine",
  "Trust Evaluation",
  "Consent Enforcement",
  "Identity Verification",
  "OAuth Runtime",
  "JWT Runtime",
  "SAML Runtime",
  "OpenID Connect Runtime",
  "MFA Runtime",
  "Token Generation",
  "Token Validation",
  "Encryption",
  "Hashing Services",
  "Secret Management",
  "Key Management",
  "HTTP or REST",
  "Databases",
  "Queues or Event Bus",
  "Runtime Security Decisions",
  "Gateway Routing",
  "AI or LLM",
  "DKL invocation",
  "Executive Engine invocation",
  "Assistant invocation",
  "React",
  "Next.js",
] as const);

/** Canonical immutable model ownership declaration. */
export const SecurityGatewayModelOwnership = Object.freeze({
  ownershipId: "NEA-4:3/SecurityGatewayModelOwnership",
  sourcePhase: "NEA-4:3" as const,
  owns: SECURITY_GATEWAY_MODEL_OWNS,
  doesNotOwn: SECURITY_GATEWAY_MODEL_DOES_NOT_OWN,
  ownsCount: SECURITY_GATEWAY_MODEL_OWNS.length,
  doesNotOwnCount: SECURITY_GATEWAY_MODEL_DOES_NOT_OWN.length,
  ownsAuthenticationExecution: false as const,
  ownsAuthorizationExecution: false as const,
  ownsPermissionEvaluation: false as const,
  ownsTrustEvaluation: false as const,
  ownsConsentVerification: false as const,
  ownsIdentityVerification: false as const,
  ownsEncryption: false as const,
  ownsRegistryCollections: false as const,
  runtimeBehavior: "None" as const,
  metadataOnly: true as const,
  immutable: true as const,
  deterministic: true as const,
});

/** Canonical immutable model boundary declarations. */
export const SecurityGatewayModelBoundaries = Object.freeze({
  boundariesId: "NEA-4:3/SecurityGatewayModelBoundaries",
  sourcePhase: "NEA-4:3" as const,
  consumes: Object.freeze([
    "NEA-4:2 Security Gateway Registry",
  ] as const),
  provides: Object.freeze(["Security Gateway Model"] as const),
  prohibitedSurfaces: SECURITY_GATEWAY_MODEL_PROHIBITED_SURFACES,
  prohibitedSurfaceCount: SECURITY_GATEWAY_MODEL_PROHIBITED_SURFACES.length,
  implementsLogin: false as const,
  executesAuthentication: false as const,
  executesAuthorization: false as const,
  evaluatesPermissions: false as const,
  evaluatesTrust: false as const,
  enforcesConsent: false as const,
  verifiesIdentity: false as const,
  implementsOAuth: false as const,
  implementsJwt: false as const,
  implementsEncryption: false as const,
  generatesTokens: false as const,
  validatesTokens: false as const,
  managesSecrets: false as const,
  implementsHttp: false as const,
  accessesDatabase: false as const,
  calculatesSecurityDecisions: false as const,
  performsAi: false as const,
  callsLlm: false as const,
  invokesDkl: false as const,
  invokesEngine: false as const,
  invokesAssistant: false as const,
  reactComponents: false as const,
  nextJsRoutes: false as const,
  duplicatesRegistryValues: false as const,
  reconstructsRegistry: false as const,
  runtimeEnforcement: false as const,
  metadataOnly: true as const,
  immutable: true as const,
  deterministic: true as const,
});
