/**
 * NEA-4:3 — Security Gateway Model Relationships.
 *
 * Immutable relationship declarations between domain models.
 * Composition metadata only. No runtime graph traversal.
 *
 * Ownership: owned exclusively by NEA-4:3.
 */

import type {
  SecurityGatewayModelKind,
  SecurityGatewayModelRelationship,
} from "./securityGatewayModelTypes.ts";

const relationship = (
  key: string,
  relationshipName: string,
  sourceModelKind: SecurityGatewayModelKind,
  targetModelKind: SecurityGatewayModelKind,
  cardinality: SecurityGatewayModelRelationship["cardinality"],
  required: boolean,
  description: string,
  order: number,
): SecurityGatewayModelRelationship =>
  Object.freeze({
    relationshipId: `NEA-4:3/Relationship/${key}`,
    relationshipName,
    sourceModelKind,
    targetModelKind,
    cardinality,
    required,
    description,
    metadataOnly: true as const,
    immutable: true as const,
    deterministicOrder: order,
  });

/** Canonical immutable model relationship inventory — exactly twenty-four. */
export const SecurityGatewayModelRelationships: readonly SecurityGatewayModelRelationship[] =
  Object.freeze([
    relationship(
      "Identity-Principal",
      "Security Identity has Security Principal",
      "SecurityIdentity",
      "SecurityPrincipal",
      "one-to-one",
      true,
      "Every security identity declares exactly one security principal.",
      1,
    ),
    relationship(
      "Identity-Classification",
      "Security Identity has Classification",
      "SecurityIdentity",
      "SecurityClassification",
      "one-to-one",
      true,
      "Every security identity declares exactly one classification.",
      2,
    ),
    relationship(
      "Identity-Metadata",
      "Security Identity has Status Metadata",
      "SecurityIdentity",
      "SecurityMetadata",
      "one-to-one",
      true,
      "Every security identity declares status through security metadata.",
      3,
    ),
    relationship(
      "Context-Identity",
      "Security Context has Security Identity",
      "SecurityContext",
      "SecurityIdentity",
      "one-to-one",
      true,
      "Every security context declares exactly one security identity.",
      4,
    ),
    relationship(
      "Context-Authentication",
      "Security Context has Authentication Context",
      "SecurityContext",
      "AuthenticationContext",
      "one-to-one",
      true,
      "Every security context declares exactly one authentication context.",
      5,
    ),
    relationship(
      "Context-Authorization",
      "Security Context has Authorization Context",
      "SecurityContext",
      "AuthorizationContext",
      "one-to-one",
      true,
      "Every security context declares exactly one authorization context.",
      6,
    ),
    relationship(
      "Context-Trust",
      "Security Context has Trust Context",
      "SecurityContext",
      "TrustContext",
      "one-to-one",
      true,
      "Every security context declares exactly one trust context.",
      7,
    ),
    relationship(
      "Context-Consent",
      "Security Context has Consent Context",
      "SecurityContext",
      "ConsentContext",
      "one-to-one",
      true,
      "Every security context declares exactly one consent context.",
      8,
    ),
    relationship(
      "Context-Role",
      "Security Context has Roles",
      "SecurityContext",
      "Role",
      "one-to-many",
      true,
      "A security context declares one or more roles.",
      9,
    ),
    relationship(
      "Context-Permission",
      "Security Context has Permissions",
      "SecurityContext",
      "Permission",
      "one-to-many",
      true,
      "A security context declares one or more permissions.",
      10,
    ),
    relationship(
      "Context-Policy",
      "Security Context has Policies",
      "SecurityContext",
      "SecurityPolicy",
      "one-to-many",
      true,
      "A security context declares one or more security policies.",
      11,
    ),
    relationship(
      "Authorization-Resource",
      "Authorization Context has Resource",
      "AuthorizationContext",
      "SecurityResource",
      "one-to-one",
      true,
      "Every authorization context declares exactly one resource.",
      12,
    ),
    relationship(
      "Authorization-Action",
      "Authorization Context has Action",
      "AuthorizationContext",
      "SecurityAction",
      "one-to-one",
      true,
      "Every authorization context declares exactly one action.",
      13,
    ),
    relationship(
      "Authorization-Role",
      "Authorization Context has Roles",
      "AuthorizationContext",
      "Role",
      "one-to-many",
      false,
      "An authorization context may declare role references.",
      14,
    ),
    relationship(
      "Authorization-Permission",
      "Authorization Context has Permissions",
      "AuthorizationContext",
      "Permission",
      "one-to-many",
      false,
      "An authorization context may declare permission references.",
      15,
    ),
    relationship(
      "Permission-Resource",
      "Permission has Resource",
      "Permission",
      "SecurityResource",
      "one-to-one",
      true,
      "Every permission declares exactly one resource reference.",
      16,
    ),
    relationship(
      "Permission-Action",
      "Permission has Action",
      "Permission",
      "SecurityAction",
      "one-to-one",
      true,
      "Every permission declares exactly one action reference.",
      17,
    ),
    relationship(
      "Permission-Constraint",
      "Permission has Constraints",
      "Permission",
      "SecurityConstraint",
      "one-to-many",
      false,
      "A permission may declare zero or more constraints.",
      18,
    ),
    relationship(
      "Policy-Constraint",
      "Policy has Constraints",
      "SecurityPolicy",
      "SecurityConstraint",
      "one-to-many",
      false,
      "A policy may declare zero or more constraints.",
      19,
    ),
    relationship(
      "Decision-Authorization",
      "Decision Declaration belongs to Authorization Context",
      "SecurityDecisionDeclaration",
      "AuthorizationContext",
      "many-to-one",
      true,
      "Every decision declaration belongs to exactly one authorization context.",
      20,
    ),
    relationship(
      "Result-Decision",
      "Result has Decision Declaration",
      "SecurityResult",
      "SecurityDecisionDeclaration",
      "one-to-one",
      true,
      "Every security result declares exactly one decision declaration.",
      21,
    ),
    relationship(
      "Result-Diagnostic",
      "Result has Diagnostics",
      "SecurityResult",
      "SecurityDiagnostic",
      "one-to-many",
      false,
      "A security result may declare diagnostics.",
      22,
    ),
    relationship(
      "Summary-Context",
      "Summary has Security Context",
      "SecuritySummary",
      "SecurityContext",
      "one-to-one",
      true,
      "Every security summary declares exactly one security context.",
      23,
    ),
    relationship(
      "Summary-Result",
      "Summary has Security Result",
      "SecuritySummary",
      "SecurityResult",
      "one-to-one",
      false,
      "A security summary may include a security result model.",
      24,
    ),
  ]);

/** Canonical immutable relationship catalog. */
export const SecurityGatewayModelRelationshipCatalog = Object.freeze({
  catalogId: "NEA-4:3/ModelRelationshipCatalog",
  sourcePhase: "NEA-4:3" as const,
  relationships: SecurityGatewayModelRelationships,
  relationshipCount: SecurityGatewayModelRelationships.length,
  executesRuntime: false as const,
  metadataOnly: true as const,
  immutable: true as const,
  deterministic: true as const,
});
