/**
 * NEA-3:3 — Session & Conversation Model Relationships.
 *
 * Immutable relationship declarations between domain models.
 * Composition metadata only. No runtime graph traversal.
 *
 * Ownership: owned exclusively by NEA-3:3.
 */

import type {
  SessionConversationModelKind,
  SessionConversationModelRelationship,
} from "./sessionConversationModelTypes.ts";

const relationship = (
  key: string,
  relationshipName: string,
  sourceModelKind: SessionConversationModelKind,
  targetModelKind: SessionConversationModelKind,
  cardinality: SessionConversationModelRelationship["cardinality"],
  required: boolean,
  description: string,
  order: number,
): SessionConversationModelRelationship =>
  Object.freeze({
    relationshipId: `NEA-3:3/Relationship/${key}`,
    relationshipName,
    sourceModelKind,
    targetModelKind,
    cardinality,
    required,
    description,
    metadataOnly: true as const,
    immutable: true as const,
    deterministicOrder: order,
  });

/** Canonical immutable model relationship inventory — exactly twenty. */
export const SessionConversationModelRelationships: readonly SessionConversationModelRelationship[] =
  Object.freeze([
    relationship(
      "Session-SessionIdentity",
      "Session has Session Identity",
      "Session",
      "SessionIdentity",
      "one-to-one",
      true,
      "Every session declares exactly one session identity.",
      1,
    ),
    relationship(
      "Conversation-ConversationIdentity",
      "Conversation has Conversation Identity",
      "Conversation",
      "ConversationIdentity",
      "one-to-one",
      true,
      "Every conversation declares exactly one conversation identity.",
      2,
    ),
    relationship(
      "Conversation-Session",
      "Conversation belongs to Session",
      "Conversation",
      "Session",
      "many-to-one",
      true,
      "Every conversation belongs to exactly one session.",
      3,
    ),
    relationship(
      "Conversation-Participant",
      "Conversation has Participants",
      "Conversation",
      "Participant",
      "one-to-many",
      true,
      "A conversation declares one or more participants.",
      4,
    ),
    relationship(
      "Conversation-Context",
      "Conversation has Context",
      "Conversation",
      "ConversationContext",
      "one-to-one",
      true,
      "Every conversation declares exactly one conversation context.",
      5,
    ),
    relationship(
      "Conversation-ConversationType",
      "Conversation has Conversation Type",
      "Conversation",
      "ConversationType",
      "one-to-one",
      true,
      "Every conversation declares exactly one conversation type.",
      6,
    ),
    relationship(
      "Session-SessionState",
      "Session has Session State",
      "Session",
      "SessionState",
      "one-to-one",
      true,
      "Every session declares exactly one session state.",
      7,
    ),
    relationship(
      "Conversation-ConversationState",
      "Conversation has Conversation State",
      "Conversation",
      "ConversationState",
      "one-to-one",
      true,
      "Every conversation declares exactly one conversation state.",
      8,
    ),
    relationship(
      "Conversation-MessageReference",
      "Conversation has Message References",
      "Conversation",
      "MessageReference",
      "one-to-many",
      false,
      "A conversation may declare zero or more message references.",
      9,
    ),
    relationship(
      "MessageReference-Correlation",
      "Message Reference has Correlation",
      "MessageReference",
      "Correlation",
      "one-to-one",
      true,
      "Every message reference declares exactly one correlation.",
      10,
    ),
    relationship(
      "Correlation-Trace",
      "Correlation has Trace",
      "Correlation",
      "Trace",
      "one-to-one",
      false,
      "A correlation may declare a trace model.",
      11,
    ),
    relationship(
      "Session-SessionMetadata",
      "Session has Session Metadata",
      "Session",
      "SessionMetadata",
      "one-to-one",
      true,
      "Every session declares exactly one session metadata model.",
      12,
    ),
    relationship(
      "Conversation-ConversationMetadata",
      "Conversation has Conversation Metadata",
      "Conversation",
      "ConversationMetadata",
      "one-to-one",
      true,
      "Every conversation declares exactly one conversation metadata model.",
      13,
    ),
    relationship(
      "Configuration-Conversation",
      "Configuration belongs to Conversation",
      "ConversationConfiguration",
      "Conversation",
      "many-to-one",
      true,
      "Every configuration belongs to exactly one conversation.",
      14,
    ),
    relationship(
      "Diagnostics-Conversation",
      "Diagnostics belong to Conversation",
      "ConversationDiagnostics",
      "Conversation",
      "many-to-one",
      true,
      "Every diagnostics model belongs to exactly one conversation.",
      15,
    ),
    relationship(
      "Result-Conversation",
      "Result belongs to Conversation",
      "ConversationResult",
      "Conversation",
      "many-to-one",
      true,
      "Every result belongs to exactly one conversation.",
      16,
    ),
    relationship(
      "Summary-Conversation",
      "Summary has Conversation",
      "ConversationSummary",
      "Conversation",
      "one-to-one",
      true,
      "Every summary declares exactly one conversation.",
      17,
    ),
    relationship(
      "Summary-Session",
      "Summary has Session",
      "ConversationSummary",
      "Session",
      "one-to-one",
      true,
      "Every summary declares exactly one session.",
      18,
    ),
    relationship(
      "Summary-Result",
      "Summary has Result",
      "ConversationSummary",
      "ConversationResult",
      "one-to-one",
      false,
      "A summary may include a conversation result model.",
      19,
    ),
    relationship(
      "Context-Connector",
      "Context references Connector",
      "ConversationContext",
      "ConversationConfiguration",
      "one-to-one",
      true,
      "Conversation context declares a connector dimension through configuration metadata.",
      20,
    ),
  ]);

/** Canonical immutable relationship catalog. */
export const SessionConversationModelRelationshipCatalog = Object.freeze({
  catalogId: "NEA-3:3/ModelRelationshipCatalog",
  sourcePhase: "NEA-3:3" as const,
  relationships: SessionConversationModelRelationships,
  relationshipCount: SessionConversationModelRelationships.length,
  executesRuntime: false as const,
  metadataOnly: true as const,
  immutable: true as const,
  deterministic: true as const,
});
