/** WS-4:4 — Immutable declarative validation rules. */
import { DecisionWorkspaceModel } from "./decisionWorkspaceModel.ts";

const names = Object.freeze([
  "Public Identities Present",
  "Canonical Identifiers Unique",
  "WS-4 Naming Structure",
  "Decision Namespace Prefix",
  "Explicit Versions",
  "Phase Identity Alignment",
  "Identity Immutability",
  "Foundation Vocabulary Registry Coverage",
  "Registry Identity Uniqueness",
  "Registry Deterministic Ordering",
  "Responsibility Duplicate Absence",
  "Capability Duplicate Absence",
  "Decision Type Duplicate Absence",
  "Lifecycle Duplicate Absence",
  "Contract Duplicate Absence",
  "Foundation Reference Preservation",
  "Required Domain Models Present",
  "Model Identity Uniqueness",
  "Registered Vocabulary References",
  "Model Metadata Only",
  "Serialization Independence",
  "Immutable Model Structure",
  "Decision Namespace Membership",
  "Valid Relationship Sources",
  "Valid Relationship Targets",
  "Relationship Identity Uniqueness",
  "Relationship Direction Declared",
  "Relationship Type Declared",
  "Relationship Order Declared",
  "Unknown Model Reference Absence",
  "Circular Ownership Absence",
  "Cross-Boundary Relationship Absence",
  "Workspace Composition Includes Decisions",
  "Decision Composition Metadata Valid",
  "Decision Option Composition Valid",
  "Criteria Composition Valid",
  "Context Composition Valid",
  "Risk Composition Valid",
  "Assumption Composition Valid",
  "Constraint Composition Valid",
  "Confidence Composition Valid",
  "Outcome Composition Valid",
  "Composition Runtime Absence",
  "Metadata Models Complete",
  "Canonical Decision Types Registered",
  "Decision Type Identity Uniqueness",
  "Foundation Decision Type Ordering",
  "Runtime Decision Type Absence",
  "Custom Decision Explicit",
  "Canonical Lifecycle Registered",
  "Lifecycle Identity Uniqueness",
  "Lifecycle Deterministic Ordering",
  "Lifecycle Immutability",
  "Lifecycle Execution Logic Absence",
  "Undeclared Lifecycle Absence",
  "Executive Responsibilities Registered",
  "Responsibility Identity Uniqueness",
  "Responsibility Metadata Only",
  "Responsibility Scope Compliance",
  "Canonical Capabilities Registered",
  "Capability Identity Uniqueness",
  "Capability Execution Absence",
  "Capability Workspace Scope",
  "Planning Scheduling Capability Absence",
  "Canonical Contracts Registered",
  "Contract Identity Uniqueness",
  "Contract Implementation Independence",
  "Service Factory Contract Absence",
  "Foundation Contract Identity References",
  "Decision Execution Absent",
  "Planning Absent",
  "Scheduling Absent",
  "Scenario Execution Absent",
  "Workflow Execution Absent",
  "Runtime Orchestration Absent",
  "AI Reasoning Absent",
  "Persistence Absent",
  "Networking Absent",
  "Rendering Absent",
  "Visualization Absent",
  "Analytics Execution Absent",
  "Notifications Absent",
  "External Integration Absent",
  "Foundation Dependency Allowed",
  "Registry Dependency Allowed",
  "Model Dependency Allowed",
  "Future Phase Dependency Absent",
  "Runtime Dependency Absent",
  "UI Package Absent",
  "Persistence Package Absent",
  "Networking Package Absent",
  "AI Package Absent",
  "Category Ordering Deterministic",
  "Rule Ordering Deterministic",
  "Target Ordering Deterministic",
  "Outcome Ordering Deterministic",
  "Gate Ordering Deterministic",
  "Source Registry Ordering Preserved",
  "Runtime-Independent Ordering",
  "Exported Records Immutable",
  "Exported Collections Readonly",
  "Mutation Function Absent",
  "Setter Absent",
  "Mutable Registry Absent",
  "Runtime State Container Absent",
  "Foundation Ready For Registry",
  "Registry Ready For Model",
  "Model Ready For Validation",
  "Validation Categories Complete",
  "Validation Rules Declared",
  "Validation Gates Pass",
  "Manifest Readiness Declared",
] as const);

export const DecisionWorkspaceValidationRules = Object.freeze(
  names.map((name, index) => Object.freeze({
    id: `WS-4:4/Rule/${String(index + 1).padStart(3, "0")}`,
    name,
    description: `Requires ${name.toLowerCase()} in Decision Workspace architecture metadata.`,
    source: DecisionWorkspaceModel,
    category: "Architectural Integrity",
    expectedOutcome: "Pass",
    severity: "Critical",
    order: index + 1,
    executable: false,
    metadataOnly: true,
    immutable: true,
  })),
);
