/** WS-3:4 — Immutable declarative validation rules. */
import { GoalWorkspaceModel } from "./goalWorkspaceModel.ts";
const names = Object.freeze([
  "Public Identities Present", "Canonical Identifiers Unique", "WS-3 Naming Structure",
  "Goal Namespace Prefix", "Explicit Versions", "Phase Identity Alignment",
  "Identity Immutability", "Foundation Vocabulary Registry Coverage",
  "Registry Identity Uniqueness", "Registry Deterministic Ordering",
  "Responsibility Duplicate Absence", "Capability Duplicate Absence",
  "Goal Type Duplicate Absence", "Lifecycle Duplicate Absence", "Contract Duplicate Absence",
  "Foundation Reference Preservation", "Required Domain Models Present",
  "Model Identity Uniqueness", "Registered Vocabulary References", "Model Metadata Only",
  "Serialization Independence", "Immutable Model Structure", "Goal Namespace Membership",
  "Valid Relationship Sources", "Valid Relationship Targets",
  "Relationship Identity Uniqueness", "Relationship Direction Declared",
  "Relationship Cardinality Valid", "Unknown Model Reference Absence",
  "Circular Ownership Absence", "Cross-Boundary Relationship Absence",
  "Workspace Composition Includes Goals", "Goal Composition Metadata Valid",
  "Ownership Composition Owner Valid", "KPI Composition Mapping Valid",
  "Timeline Composition Model Valid", "Assumption Composition Model Valid",
  "Constraint Composition Model Valid", "Risk Composition Model Valid",
  "Composition Runtime Absence", "Canonical Goal Types Registered",
  "Goal Type Identity Uniqueness", "Foundation Goal Type Ordering",
  "Runtime Goal Type Absence", "Custom Goal Explicit", "Canonical Lifecycle Registered",
  "Lifecycle Identity Uniqueness", "Lifecycle Deterministic Ordering",
  "Lifecycle Immutability", "Lifecycle Execution Logic Absence",
  "Undeclared Lifecycle Absence", "Executive Responsibilities Registered",
  "Responsibility Identity Uniqueness", "Responsibility Metadata Only",
  "Responsibility Scope Compliance", "Canonical Capabilities Registered",
  "Capability Identity Uniqueness", "Capability Execution Absence",
  "Capability Workspace Scope", "Planning Scheduling Task Capability Absence",
  "Canonical Contracts Registered", "Contract Identity Uniqueness",
  "Contract Implementation Independence", "Service Factory Contract Absence",
  "Foundation Contract Identity References", "Goal Execution Absent", "Planning Absent",
  "Scheduling Absent", "Task Management Absent", "Decision Execution Absent",
  "Scenario Simulation Absent", "Runtime Orchestration Absent", "AI Reasoning Absent",
  "Persistence Absent", "Networking Absent", "Rendering Absent", "Visualization Absent",
  "Analytics Execution Absent", "Notifications Absent", "External Integration Absent",
  "Foundation Dependency Allowed", "Registry Dependency Allowed", "Model Dependency Allowed",
  "Future Phase Dependency Absent", "Runtime Dependency Absent", "UI Package Absent",
  "Persistence Package Absent", "Networking Package Absent", "AI Package Absent",
  "Category Ordering Deterministic", "Rule Ordering Deterministic",
  "Target Ordering Deterministic", "Outcome Ordering Deterministic",
  "Gate Ordering Deterministic", "Source Registry Ordering Preserved",
  "Runtime-Independent Ordering", "Exported Records Immutable",
  "Exported Collections Readonly", "Mutation Function Absent", "Setter Absent",
  "Mutable Registry Absent", "Runtime State Container Absent",
  "Foundation Ready For Registry", "Registry Ready For Model",
  "Model Ready For Validation", "Validation Categories Complete",
  "Validation Rules Declared", "Validation Gates Pass", "Manifest Readiness Declared",
] as const);
export const GoalWorkspaceValidationRules = Object.freeze(names.map((name, index) => Object.freeze({
  id: `WS-3:4/Rule/${String(index + 1).padStart(3, "0")}`, name,
  description: `Requires ${name.toLowerCase()} in Goal Workspace architecture metadata.`,
  source: GoalWorkspaceModel, category: "Architectural Integrity",
  expectedOutcome: "Pass", severity: "Critical", order: index + 1,
  executable: false, metadataOnly: true, immutable: true,
})));

