/** WS-6:4 — Exactly 48 immutable declarative validation rules. */
import { ProblemWorkspaceModel } from "./problemWorkspaceModel.ts";

const definitions = Object.freeze([
  ["Foundation Integrity", "Every Foundation contract has a unique identity"],
  ["Foundation Integrity", "No duplicate Foundation contracts exist"],
  ["Capability Integrity", "All Foundation capabilities are declared"],
  ["Responsibility Integrity", "All Foundation responsibilities are declared"],
  ["Lifecycle Integrity", "All Foundation lifecycle stages are declared"],
  ["Boundary Integrity", "All Foundation boundaries are explicit"],
  ["Registry Integrity", "Every registry entry has a unique identifier"],
  ["Registry Integrity", "Registry entries preserve Foundation references"],
  ["Registry Integrity", "No duplicate registry records exist"],
  ["Lifecycle Integrity", "Lifecycle registrations are complete"],
  ["Registry Integrity", "Registry vocabulary is deterministically ordered"],
  ["Registry Integrity", "Registry collections are immutable"],
  ["Model Integrity", "Every model references registered identities"],
  ["Relationship Integrity", "Every relationship has a valid source"],
  ["Relationship Integrity", "Every relationship has a valid target"],
  ["Model Integrity", "No orphan models exist"],
  ["Architecture Integrity", "No circular architectural dependencies exist"],
  ["Model Integrity", "Executive problem representation is complete"],
  ["Model Integrity", "Composition metadata is complete"],
  ["Model Integrity", "Model inventory is internally consistent"],
  ["Identity Integrity", "Canonical identifiers are unique"],
  ["Namespace Integrity", "Namespace follows Nexora standards"],
  ["Identity Integrity", "Version metadata exists"],
  ["Identity Integrity", "Public identities are immutable"],
  ["Dependency Integrity", "Foundation dependency is permitted"],
  ["Dependency Integrity", "Registry dependency is permitted"],
  ["Dependency Integrity", "Model dependency is permitted"],
  ["Dependency Integrity", "No downstream imports exist"],
  ["Dependency Integrity", "No Runtime imports exist"],
  ["Dependency Integrity", "No UI imports exist"],
  ["Dependency Integrity", "No Engine imports exist"],
  ["Dependency Integrity", "No DKL imports exist"],
  ["Dependency Integrity", "No Director imports exist"],
  ["Dependency Integrity", "No EVE imports exist"],
  ["Boundary Integrity", "No execution logic exists"],
  ["Boundary Integrity", "No AI logic exists"],
  ["Boundary Integrity", "No persistence exists"],
  ["Boundary Integrity", "No networking exists"],
  ["Boundary Integrity", "No rendering exists"],
  ["Boundary Integrity", "No workflow execution exists"],
  ["Boundary Integrity", "No services exist"],
  ["Boundary Integrity", "No factories exist"],
  ["Metadata Integrity", "Metadata completeness is declared"],
  ["Export Integrity", "Stable export declarations are present"],
  ["Workspace Integrity", "Workspace identity is canonical"],
  ["Metadata Integrity", "All exported collections are immutable"],
  ["Architecture Integrity", "Relationship ordering is deterministic"],
  ["Workspace Integrity", "ReadyForManifest eligibility is declared"],
] as const);

export const ProblemWorkspaceValidationRules = Object.freeze(
  definitions.map(([category, name], index) => Object.freeze({
    id: `WS-6:4/Rule/${String(index + 1).padStart(2, "0")}`,
    name,
    description: `Requires that ${name.toLowerCase()}.`,
    category,
    source: ProblemWorkspaceModel,
    expectedOutcome: "Pass",
    order: index + 1,
    executable: false,
    metadataOnly: true,
    immutable: true,
  })),
);
