/** WS-5:4 — Immutable declarative validation rules. */
import { ScenarioWorkspaceModel } from "./scenarioWorkspaceModel.ts";

const names = Object.freeze([
  "Public Identities Present",
  "Canonical Identifiers Unique",
  "Scenario Namespace Prefix",
  "Explicit Versions",
  "Exported Identities Immutable",
  "Foundation Vocabulary Registry Coverage",
  "Responsibility Duplicate Absence",
  "Capability Duplicate Absence",
  "Scenario Type Duplicate Absence",
  "Lifecycle Duplicate Absence",
  "Contract Duplicate Absence",
  "Registry Deterministic Ordering",
  "Required Domain Models Present",
  "Valid Relationship Model References",
  "Composition Models Complete",
  "Metadata Models Complete",
  "Model Runtime Implementation Absent",
  "Model Identities Unique",
  "Strategic Scenario Registered",
  "Tactical Scenario Registered",
  "Operational Scenario Registered",
  "Financial Scenario Registered",
  "Investment Scenario Registered",
  "Market Scenario Registered",
  "Growth Scenario Registered",
  "Risk Scenario Registered",
  "Crisis Scenario Registered",
  "Opportunity Scenario Registered",
  "Future State Scenario Registered",
  "Custom Scenario Registered",
  "Draft Lifecycle Registered",
  "UnderReview Lifecycle Registered",
  "UnderAnalysis Lifecycle Registered",
  "Approved Lifecycle Registered",
  "Rejected Lifecycle Registered",
  "Active Lifecycle Registered",
  "Completed Lifecycle Registered",
  "Archived Lifecycle Registered",
  "Scenario Definition Responsibility Registered",
  "Scenario Modeling Responsibility Registered",
  "Scenario Comparison Responsibility Registered",
  "Scenario Evaluation Responsibility Registered",
  "Scenario Prioritization Responsibility Registered",
  "Scenario Review Responsibility Registered",
  "Scenario Governance Responsibility Registered",
  "Scenario Recommendation Responsibility Registered",
  "Scenario Documentation Responsibility Registered",
  "Scenario Selection Responsibility Registered",
  "Define Scenario Capability Registered",
  "Manage Scenario Options Capability Registered",
  "Compare Scenarios Capability Registered",
  "Analyze Assumptions Capability Registered",
  "Analyze Risks Capability Registered",
  "Manage Constraints Capability Registered",
  "Evaluate Outcomes Capability Registered",
  "Assign Scenario Owner Capability Registered",
  "Record Scenario Capability Registered",
  "Review Scenario Capability Registered",
  "Archive Scenario Capability Registered",
  "Track Scenario Confidence Capability Registered",
  "Scenario Workspace Contract Registered",
  "Scenario Object Contract Registered",
  "Scenario Option Contract Registered",
  "Scenario Branch Contract Registered",
  "Scenario Timeline Contract Registered",
  "Scenario Assumption Contract Registered",
  "Scenario Risk Contract Registered",
  "Scenario Constraint Contract Registered",
  "Scenario Outcome Contract Registered",
  "Scenario Confidence Contract Registered",
  "Scenario Recommendation Contract Registered",
  "Scenario Metadata Contract Registered",
  "Scenario Execution Absent",
  "Simulation Runtime Absent",
  "Prediction Engine Absent",
  "Forecast Calculation Absent",
  "Decision Execution Absent",
  "Planning Absent",
  "Scheduling Absent",
  "Runtime Orchestration Absent",
  "AI Reasoning Absent",
  "Persistence Absent",
  "Networking Absent",
  "Rendering Absent",
  "Visualization Absent",
  "Notifications Absent",
  "Foundation Dependency Allowed",
  "Registry Dependency Allowed",
  "Model Dependency Allowed",
  "Future Phase Dependency Absent",
  "Runtime Dependency Absent",
  "Ordering Deterministic",
  "Exported Records Immutable",
  "Exported Collections Readonly",
  "Mutable State Absent",
  "Foundation Ready For Registry",
  "Registry Ready For Model",
  "Model Ready For Validation",
  "Validation Gates Pass",
  "Manifest Readiness Declared",
] as const);

export const ScenarioWorkspaceValidationRules = Object.freeze(
  names.map((name, index) => Object.freeze({
    id: `WS-5:4/Rule/${String(index + 1).padStart(3, "0")}`,
    name,
    description: `Requires ${name.toLowerCase()} in Scenario Workspace architecture metadata.`,
    source: ScenarioWorkspaceModel,
    category: "Architectural Integrity",
    expectedOutcome: "Pass",
    severity: "Critical",
    order: index + 1,
    executable: false,
    metadataOnly: true,
    immutable: true,
  })),
);
