/**
 * WS-1:2 — Declarative lifecycle records. Transitions are never executed.
 */

import { WorkspaceFoundation } from "./workspaceFoundation.ts";
import type { WorkspaceLifecycleRegistryRecord } from "./workspaceRegistryTypes.ts";

export const WorkspaceLifecycleRegistry = Object.freeze([
  Object.freeze({ id: "WS-1:2/Lifecycle/Declared", key: "declared", name: "Declared", description: "Workspace metadata has been declared.", registryCategory: "Lifecycle", sourcePhase: "WS-1:1", source: WorkspaceFoundation.lifecycle[0], allowedArchitecturalTransitions: Object.freeze(["Registered"]), executesTransitions: false, stability: "Stable", version: "1.0.0", ownership: "Workspace", extensionPolicy: "Additive", metadataOnly: true, immutable: true }),
  Object.freeze({ id: "WS-1:2/Lifecycle/Registered", key: "registered", name: "Registered", description: "Workspace metadata has been registered.", registryCategory: "Lifecycle", sourcePhase: "WS-1:1", source: WorkspaceFoundation.lifecycle[1], allowedArchitecturalTransitions: Object.freeze(["Configured"]), executesTransitions: false, stability: "Stable", version: "1.0.0", ownership: "Workspace", extensionPolicy: "Additive", metadataOnly: true, immutable: true }),
  Object.freeze({ id: "WS-1:2/Lifecycle/Configured", key: "configured", name: "Configured", description: "Workspace configuration metadata is available.", registryCategory: "Lifecycle", sourcePhase: "WS-1:1", source: WorkspaceFoundation.lifecycle[2], allowedArchitecturalTransitions: Object.freeze(["Initialized"]), executesTransitions: false, stability: "Stable", version: "1.0.0", ownership: "Workspace", extensionPolicy: "Additive", metadataOnly: true, immutable: true }),
  Object.freeze({ id: "WS-1:2/Lifecycle/Initialized", key: "initialized", name: "Initialized", description: "Workspace initialization readiness is declared.", registryCategory: "Lifecycle", sourcePhase: "WS-1:1", source: WorkspaceFoundation.lifecycle[3], allowedArchitecturalTransitions: Object.freeze(["Active"]), executesTransitions: false, stability: "Stable", version: "1.0.0", ownership: "Workspace", extensionPolicy: "Additive", metadataOnly: true, immutable: true }),
  Object.freeze({ id: "WS-1:2/Lifecycle/Active", key: "active", name: "Active", description: "Workspace active-state metadata is declared.", registryCategory: "Lifecycle", sourcePhase: "WS-1:1", source: WorkspaceFoundation.lifecycle[4], allowedArchitecturalTransitions: Object.freeze(["Suspended", "Archived"]), executesTransitions: false, stability: "Stable", version: "1.0.0", ownership: "Workspace", extensionPolicy: "Additive", metadataOnly: true, immutable: true }),
  Object.freeze({ id: "WS-1:2/Lifecycle/Suspended", key: "suspended", name: "Suspended", description: "Workspace suspension metadata is declared.", registryCategory: "Lifecycle", sourcePhase: "WS-1:1", source: WorkspaceFoundation.lifecycle[5], allowedArchitecturalTransitions: Object.freeze(["Restored", "Archived"]), executesTransitions: false, stability: "Stable", version: "1.0.0", ownership: "Workspace", extensionPolicy: "Additive", metadataOnly: true, immutable: true }),
  Object.freeze({ id: "WS-1:2/Lifecycle/Restored", key: "restored", name: "Restored", description: "Workspace restoration metadata is declared.", registryCategory: "Lifecycle", sourcePhase: "WS-1:1", source: WorkspaceFoundation.lifecycle[6], allowedArchitecturalTransitions: Object.freeze(["Active"]), executesTransitions: false, stability: "Stable", version: "1.0.0", ownership: "Workspace", extensionPolicy: "Additive", metadataOnly: true, immutable: true }),
  Object.freeze({ id: "WS-1:2/Lifecycle/Archived", key: "archived", name: "Archived", description: "Workspace archive metadata is declared.", registryCategory: "Lifecycle", sourcePhase: "WS-1:1", source: WorkspaceFoundation.lifecycle[7], allowedArchitecturalTransitions: Object.freeze(["Restored", "Retired"]), executesTransitions: false, stability: "Stable", version: "1.0.0", ownership: "Workspace", extensionPolicy: "Additive", metadataOnly: true, immutable: true }),
  Object.freeze({ id: "WS-1:2/Lifecycle/Retired", key: "retired", name: "Retired", description: "Workspace retirement metadata is declared.", registryCategory: "Lifecycle", sourcePhase: "WS-1:1", source: WorkspaceFoundation.lifecycle[8], allowedArchitecturalTransitions: Object.freeze([]), executesTransitions: false, stability: "Stable", version: "1.0.0", ownership: "Workspace", extensionPolicy: "Additive", metadataOnly: true, immutable: true }),
] as const satisfies readonly WorkspaceLifecycleRegistryRecord[]);

