/**
 * WS-1:2 — Canonical Workspace type records derived from Foundation categories.
 */

import { WorkspaceFoundation } from "./workspaceFoundation.ts";
import type { WorkspaceTypeRegistryRecord } from "./workspaceRegistryTypes.ts";

export const WorkspaceTypeRegistry = Object.freeze([
  Object.freeze({ id: "WS-1:2/Type/ExecutiveHome", key: "executive-home", name: "Executive Home Workspace", description: "Registers the canonical executive home category.", registryCategory: "WorkspaceType", sourcePhase: "WS-1:1", source: WorkspaceFoundation.categories[0], category: WorkspaceFoundation.categories[0], purpose: "Provide a unified executive orientation surface.", supportedObjectives: Object.freeze(["Executive orientation", "Portfolio awareness"]), lifecycleAvailability: WorkspaceFoundation.lifecycle, customizationPolicy: "Canonical", stability: "Stable", version: "1.0.0", ownership: "Workspace", extensionPolicy: "Additive", metadataOnly: true, immutable: true }),
  Object.freeze({ id: "WS-1:2/Type/Goal", key: "goal", name: "Goal Workspace", description: "Registers the canonical goal category.", registryCategory: "WorkspaceType", sourcePhase: "WS-1:1", source: WorkspaceFoundation.categories[1], category: WorkspaceFoundation.categories[1], purpose: "Organize work around a defined executive goal.", supportedObjectives: Object.freeze(["Goal definition", "Goal oversight"]), lifecycleAvailability: WorkspaceFoundation.lifecycle, customizationPolicy: "Configurable", stability: "Stable", version: "1.0.0", ownership: "Workspace", extensionPolicy: "Additive", metadataOnly: true, immutable: true }),
  Object.freeze({ id: "WS-1:2/Type/Problem", key: "problem", name: "Problem Workspace", description: "Registers the canonical problem category.", registryCategory: "WorkspaceType", sourcePhase: "WS-1:1", source: WorkspaceFoundation.categories[2], category: WorkspaceFoundation.categories[2], purpose: "Frame and examine a bounded management problem.", supportedObjectives: Object.freeze(["Problem framing", "Problem oversight"]), lifecycleAvailability: WorkspaceFoundation.lifecycle, customizationPolicy: "Configurable", stability: "Stable", version: "1.0.0", ownership: "Workspace", extensionPolicy: "Additive", metadataOnly: true, immutable: true }),
  Object.freeze({ id: "WS-1:2/Type/Decision", key: "decision", name: "Decision Workspace", description: "Registers the canonical decision category.", registryCategory: "WorkspaceType", sourcePhase: "WS-1:1", source: WorkspaceFoundation.categories[3], category: WorkspaceFoundation.categories[3], purpose: "Organize context around an executive decision.", supportedObjectives: Object.freeze(["Decision preparation", "Decision traceability"]), lifecycleAvailability: WorkspaceFoundation.lifecycle, customizationPolicy: "Configurable", stability: "Stable", version: "1.0.0", ownership: "Workspace", extensionPolicy: "Additive", metadataOnly: true, immutable: true }),
  Object.freeze({ id: "WS-1:2/Type/Scenario", key: "scenario", name: "Scenario Workspace", description: "Registers the canonical scenario category.", registryCategory: "WorkspaceType", sourcePhase: "WS-1:1", source: WorkspaceFoundation.categories[4], category: WorkspaceFoundation.categories[4], purpose: "Describe a bounded scenario context.", supportedObjectives: Object.freeze(["Scenario comparison", "Scenario oversight"]), lifecycleAvailability: WorkspaceFoundation.lifecycle, customizationPolicy: "Configurable", stability: "Stable", version: "1.0.0", ownership: "Workspace", extensionPolicy: "Additive", metadataOnly: true, immutable: true }),
  Object.freeze({ id: "WS-1:2/Type/Strategy", key: "strategy", name: "Strategy Workspace", description: "Registers the canonical strategy category.", registryCategory: "WorkspaceType", sourcePhase: "WS-1:1", source: WorkspaceFoundation.categories[5], category: WorkspaceFoundation.categories[5], purpose: "Organize strategic objectives and references.", supportedObjectives: Object.freeze(["Strategy definition", "Strategy alignment"]), lifecycleAvailability: WorkspaceFoundation.lifecycle, customizationPolicy: "Configurable", stability: "Stable", version: "1.0.0", ownership: "Workspace", extensionPolicy: "Additive", metadataOnly: true, immutable: true }),
  Object.freeze({ id: "WS-1:2/Type/Risk", key: "risk", name: "Risk Workspace", description: "Registers the canonical risk category.", registryCategory: "WorkspaceType", sourcePhase: "WS-1:1", source: WorkspaceFoundation.categories[6], category: WorkspaceFoundation.categories[6], purpose: "Organize executive risk context.", supportedObjectives: Object.freeze(["Risk awareness", "Risk oversight"]), lifecycleAvailability: WorkspaceFoundation.lifecycle, customizationPolicy: "Configurable", stability: "Stable", version: "1.0.0", ownership: "Workspace", extensionPolicy: "Additive", metadataOnly: true, immutable: true }),
  Object.freeze({ id: "WS-1:2/Type/Organization", key: "organization", name: "Organization Workspace", description: "Registers the canonical organization category.", registryCategory: "WorkspaceType", sourcePhase: "WS-1:1", source: WorkspaceFoundation.categories[7], category: WorkspaceFoundation.categories[7], purpose: "Describe an organizational management context.", supportedObjectives: Object.freeze(["Organization awareness", "Organization oversight"]), lifecycleAvailability: WorkspaceFoundation.lifecycle, customizationPolicy: "Configurable", stability: "Stable", version: "1.0.0", ownership: "Workspace", extensionPolicy: "Additive", metadataOnly: true, immutable: true }),
  Object.freeze({ id: "WS-1:2/Type/Knowledge", key: "knowledge", name: "Knowledge Workspace", description: "Registers the canonical knowledge category.", registryCategory: "WorkspaceType", sourcePhase: "WS-1:1", source: WorkspaceFoundation.categories[8], category: WorkspaceFoundation.categories[8], purpose: "Organize product and executive knowledge references.", supportedObjectives: Object.freeze(["Knowledge organization", "Knowledge access"]), lifecycleAvailability: WorkspaceFoundation.lifecycle, customizationPolicy: "Configurable", stability: "Stable", version: "1.0.0", ownership: "Workspace", extensionPolicy: "Additive", metadataOnly: true, immutable: true }),
  Object.freeze({ id: "WS-1:2/Type/Dashboard", key: "dashboard", name: "Dashboard Workspace", description: "Registers the canonical dashboard category.", registryCategory: "WorkspaceType", sourcePhase: "WS-1:1", source: WorkspaceFoundation.categories[9], category: WorkspaceFoundation.categories[9], purpose: "Compose executive information references.", supportedObjectives: Object.freeze(["Executive monitoring", "Executive review"]), lifecycleAvailability: WorkspaceFoundation.lifecycle, customizationPolicy: "Configurable", stability: "Stable", version: "1.0.0", ownership: "Workspace", extensionPolicy: "Additive", metadataOnly: true, immutable: true }),
  Object.freeze({ id: "WS-1:2/Type/Custom", key: "custom", name: "Custom Workspace", description: "Registers the canonical extensible category.", registryCategory: "WorkspaceType", sourcePhase: "WS-1:1", source: WorkspaceFoundation.categories[10], category: WorkspaceFoundation.categories[10], purpose: "Describe an approved extension of Workspace metadata.", supportedObjectives: Object.freeze(["Approved custom objective"]), lifecycleAvailability: WorkspaceFoundation.lifecycle, customizationPolicy: "Configurable", stability: "Stable", version: "1.0.0", ownership: "Workspace", extensionPolicy: "Additive", metadataOnly: true, immutable: true }),
] as const satisfies readonly WorkspaceTypeRegistryRecord[]);

