import type { ScenarioDomain, ScenarioSeed } from "./decisionAssistantTypes.ts";

/** Static seed templates per domain (not evaluated until run through evaluator). */
export const SCENARIO_DOMAIN_TEMPLATES: Record<ScenarioDomain, ScenarioSeed[]> = {
  business: [
    {
      id: "biz_baseline",
      name: "Baseline operations",
      intent: "Hold current operating posture and monitor leading indicators.",
      delta: {},
      tags: ["baseline", "monitor"],
      applicableWhen: ["low_risk", "steady_state"],
    },
    {
      id: "biz_buffer_inventory",
      name: "Buffer critical inventory",
      intent: "Increase safety stock on constraint SKUs to absorb supplier variance.",
      delta: { inventory: 0.18, cost: 0.06 },
      tags: ["inventory", "supply"],
      applicableWhen: ["supply_pressure", "inventory"],
    },
    {
      id: "biz_restore_throughput",
      name: "Restore flow throughput",
      intent: "Re-sequence fulfillment and unlock bottleneck lanes without capex.",
      delta: { throughput: 0.2, risk: -0.05 },
      tags: ["throughput", "fulfillment"],
      applicableWhen: ["delivery", "flow", "latency"],
    },
    {
      id: "biz_cost_discipline",
      name: "Tighten unit economics",
      intent: "Defer discretionary spend and renegotiate variable cost levers.",
      delta: { cost: -0.12, stability: 0.05 },
      tags: ["cost", "margin"],
      applicableWhen: ["margin_pressure", "low_risk"],
    },
  ],
  politics: [
    {
      id: "pol_baseline",
      name: "Baseline posture",
      intent: "Maintain coalition alignment and document decision rationale.",
      delta: {},
      tags: ["baseline"],
      applicableWhen: ["stable_coalition"],
    },
    {
      id: "pol_contain_escalation",
      name: "Contain escalation",
      intent: "Slow the feedback loop; trade speed for coalition stability.",
      delta: { risk: -0.18, stability: 0.12 },
      tags: ["de_escalate", "coalition"],
      applicableWhen: ["high_risk", "critical_risk", "escalation"],
    },
    {
      id: "pol_signal_clarity",
      name: "Clarify public signal",
      intent: "Reduce ambiguity in messaging to protect negotiating room.",
      delta: { stability: 0.08, throughput: 0.04 },
      tags: ["messaging", "trust"],
      applicableWhen: ["negotiation", "media"],
    },
    {
      id: "pol_reciprocity_window",
      name: "Structured reciprocity",
      intent: "Offer bounded concessions tied to verifiable counter-moves.",
      delta: { risk: -0.08, cost: 0.05 },
      tags: ["bargain", "reciprocity"],
      applicableWhen: ["deal_window"],
    },
  ],
  strategy: [
    {
      id: "strat_baseline",
      name: "Strategic hold",
      intent: "Preserve option value; avoid irreversible commitments this quarter.",
      delta: {},
      tags: ["baseline", "options"],
      applicableWhen: ["uncertainty"],
    },
    {
      id: "strat_defensive_moat",
      name: "Defensive moat",
      intent: "Protect core revenue and raise switching costs for key accounts.",
      delta: { stability: 0.15, cost: 0.04 },
      tags: ["defense", "retention"],
      applicableWhen: ["competitive_pressure", "high_risk"],
    },
    {
      id: "strat_selective_bet",
      name: "Selective acceleration",
      intent: "Fund one bounded initiative with clear kill criteria.",
      delta: { throughput: 0.14, risk: 0.06 },
      tags: ["growth", "bet"],
      applicableWhen: ["low_risk", "optimize"],
    },
    {
      id: "strat_portfolio_rebalance",
      name: "Rebalance portfolio",
      intent: "Shift capacity from tail offerings to highest conviction bets.",
      delta: { cost: -0.08, throughput: 0.1 },
      tags: ["portfolio", "focus"],
      applicableWhen: ["resource_constraint"],
    },
  ],
  generic: [
    {
      id: "gen_baseline",
      name: "Observe and align",
      intent: "Keep stakeholders aligned while information is still incomplete.",
      delta: {},
      tags: ["baseline"],
      applicableWhen: [],
    },
    {
      id: "gen_stabilize",
      name: "Stabilize first",
      intent: "Reduce variance before optimizing; protect downside.",
      delta: { risk: -0.12, stability: 0.14 },
      tags: ["stabilize"],
      applicableWhen: ["high_risk", "critical_risk"],
    },
    {
      id: "gen_prudent_push",
      name: "Prudent push",
      intent: "Increase pace where confidence is adequate and risk is contained.",
      delta: { throughput: 0.12, risk: 0.04 },
      tags: ["accelerate"],
      applicableWhen: ["low_risk", "medium_risk"],
    },
    {
      id: "gen_efficiency_pass",
      name: "Efficiency pass",
      intent: "Remove friction and duplication without changing strategic direction.",
      delta: { cost: -0.1, stability: 0.06 },
      tags: ["efficiency"],
      applicableWhen: ["cost", "process"],
    },
  ],
};
