import type { BusinessProjectConceptDefinition, ConceptAssociation, ConceptFamilyRelevance } from "./businessProjectConceptContract.ts";

const family = (name: string, contextKind: "BUSINESS" | "PROJECT", rank: "PRIMARY" | "ADDITIONAL" = "PRIMARY", aspect: "GENERAL" | "CURRENT_OPERATIONS" | "PLANNED_PROJECT" = "GENERAL"): ConceptFamilyRelevance => Object.freeze({ family: name, contextKind, rank, aspect });
const association = (targetConcept: string, kind: ConceptAssociation["kind"] = "RELEVANT_TO"): ConceptAssociation => Object.freeze({ targetConcept, kind, causal: false });

function concept(input: BusinessProjectConceptDefinition): BusinessProjectConceptDefinition {
  return Object.freeze({ ...input, aliases: Object.freeze([...input.aliases]), contextKinds: Object.freeze([...input.contextKinds]), familyRelevance: Object.freeze([...input.familyRelevance]), safeAssociations: Object.freeze([...input.safeAssociations]), rejectedConclusions: Object.freeze([...input.rejectedConclusions]) });
}

const NO_STATE = Object.freeze(["current state is not established", "no executive object is implied", "no causal conclusion is justified"]);

/** Small BCA knowledge registry. Exact aliases normalize established meanings; they never interpret raw fields. */
export const BUSINESS_PROJECT_CONCEPT_REGISTRY: readonly BusinessProjectConceptDefinition[] = Object.freeze([
  concept({ registryId: "business.backlog", canonicalName: "Backlog", aliases: ["backlog level", "backlog units"], generalMeaning: "Pending work or orders awaiting completion.", contextKinds: ["BUSINESS"], familyRelevance: [family("OPERATIONS", "BUSINESS"), family("PRODUCTION", "BUSINESS", "ADDITIONAL"), family("SUPPLY_CHAIN", "BUSINESS", "ADDITIONAL")], safeAssociations: [association("Delivery"), association("Capacity", "POTENTIALLY_RELATED_TO"), association("Throughput", "POTENTIALLY_RELATED_TO")], rejectedConclusions: NO_STATE }),
  concept({ registryId: "business.gross-margin", canonicalName: "Gross Margin", aliases: ["gross margin percent", "gross margin percentage", "margin"], generalMeaning: "Revenue remaining after direct cost, expressed as value or rate.", contextKinds: ["BUSINESS"], familyRelevance: [family("FINANCE", "BUSINESS")], safeAssociations: [association("Revenue"), association("Cost")], rejectedConclusions: NO_STATE }),
  concept({ registryId: "project.schedule-variance", canonicalName: "Schedule Variance", aliases: [], generalMeaning: "Difference between planned and observed project schedule position.", contextKinds: ["PROJECT"], familyRelevance: [family("SCHEDULE", "PROJECT")], safeAssociations: [association("Schedule"), association("Milestone")], rejectedConclusions: NO_STATE }),
  concept({ registryId: "project.milestone", canonicalName: "Milestone", aliases: ["project milestone"], generalMeaning: "A significant project checkpoint or completion point.", contextKinds: ["PROJECT"], familyRelevance: [family("MILESTONE", "PROJECT"), family("SCHEDULE", "PROJECT", "ADDITIONAL"), family("DELIVERABLE", "PROJECT", "ADDITIONAL")], safeAssociations: [association("Schedule"), association("Deliverable")], rejectedConclusions: NO_STATE }),
  concept({ registryId: "hybrid.cost", canonicalName: "Cost", aliases: ["project cost", "procurement cost"], generalMeaning: "Resources consumed or monetary expenditure associated with work.", contextKinds: ["BUSINESS", "PROJECT", "HYBRID"], familyRelevance: [family("FINANCE", "BUSINESS"), family("OPERATIONS", "BUSINESS", "ADDITIONAL"), family("COST", "PROJECT"), family("PROCUREMENT", "PROJECT", "ADDITIONAL")], safeAssociations: [association("Budget"), association("Procurement")], rejectedConclusions: NO_STATE }),
  concept({ registryId: "hybrid.capacity", canonicalName: "Capacity", aliases: ["available capacity", "capacity availability", "production capacity"], generalMeaning: "The amount of work or output a system or resource can support.", contextKinds: ["BUSINESS", "PROJECT", "HYBRID"], familyRelevance: [family("OPERATIONS", "BUSINESS", "PRIMARY", "CURRENT_OPERATIONS"), family("PRODUCTION", "BUSINESS", "ADDITIONAL", "CURRENT_OPERATIONS"), family("RESOURCE", "PROJECT", "PRIMARY", "PLANNED_PROJECT")], safeAssociations: [association("Backlog", "POTENTIALLY_RELATED_TO"), association("Throughput"), association("Resource Availability")], rejectedConclusions: NO_STATE }),
  concept({ registryId: "business.on-time-delivery", canonicalName: "On-Time Delivery", aliases: ["on-time delivery percentage", "on time delivery", "on time deliveries", "on time delivery percent", "on-time delivery percent"], generalMeaning: "Delivery performance relative to a promised or planned time.", contextKinds: ["BUSINESS"], familyRelevance: [family("OPERATIONS", "BUSINESS"), family("SERVICE", "BUSINESS", "ADDITIONAL")], safeAssociations: [association("Delivery Performance", "MEASURE_OF")], rejectedConclusions: NO_STATE }),
  concept({ registryId: "business.revenue", canonicalName: "Revenue", aliases: ["current revenue"], generalMeaning: "Income generated from business activity.", contextKinds: ["BUSINESS"], familyRelevance: [family("FINANCE", "BUSINESS"), family("SALES", "BUSINESS", "ADDITIONAL")], safeAssociations: [association("Margin")], rejectedConclusions: NO_STATE }),
  concept({ registryId: "business.delivery", canonicalName: "Delivery", aliases: [], generalMeaning: "Completion or fulfillment of an expected output.", contextKinds: ["BUSINESS", "PROJECT", "HYBRID"], familyRelevance: [family("OPERATIONS", "BUSINESS"), family("DELIVERABLE", "PROJECT")], safeAssociations: [association("On-Time Delivery")], rejectedConclusions: NO_STATE }),
  concept({ registryId: "business.delivery-performance", canonicalName: "Delivery Performance", aliases: [], generalMeaning: "Observed delivery results relative to expected fulfillment.", contextKinds: ["BUSINESS"], familyRelevance: [family("OPERATIONS", "BUSINESS"), family("SERVICE", "BUSINESS", "ADDITIONAL")], safeAssociations: [association("On-Time Delivery", "MEASURE_OF")], rejectedConclusions: NO_STATE }),
  concept({ registryId: "business.throughput", canonicalName: "Throughput", aliases: ["throughput units"], generalMeaning: "Rate of completed work or output.", contextKinds: ["BUSINESS"], familyRelevance: [family("OPERATIONS", "BUSINESS")], safeAssociations: [association("Capacity", "POTENTIALLY_RELATED_TO")], rejectedConclusions: NO_STATE }),
  concept({ registryId: "business.supplier-lead-time", canonicalName: "Supplier Lead Time", aliases: [], generalMeaning: "Time required for supplier fulfillment.", contextKinds: ["BUSINESS"], familyRelevance: [family("SUPPLY_CHAIN", "BUSINESS")], safeAssociations: [association("Delivery")], rejectedConclusions: NO_STATE }),
  concept({ registryId: "project.schedule", canonicalName: "Project Schedule", aliases: ["schedule"], generalMeaning: "Planned timing of project work and checkpoints.", contextKinds: ["PROJECT"], familyRelevance: [family("SCHEDULE", "PROJECT")], safeAssociations: [association("Milestone")], rejectedConclusions: NO_STATE }),
  concept({ registryId: "project.schedule-performance", canonicalName: "Schedule Performance", aliases: [], generalMeaning: "Observed project timing relative to the plan.", contextKinds: ["PROJECT"], familyRelevance: [family("SCHEDULE", "PROJECT")], safeAssociations: [association("Schedule Variance", "MEASURE_OF")], rejectedConclusions: NO_STATE }),
  concept({ registryId: "project.budget", canonicalName: "Budget", aliases: [], generalMeaning: "Planned financial envelope for work.", contextKinds: ["BUSINESS", "PROJECT", "HYBRID"], familyRelevance: [family("FINANCE", "BUSINESS"), family("COST", "PROJECT")], safeAssociations: [association("Cost")], rejectedConclusions: NO_STATE }),
  concept({ registryId: "project.procurement", canonicalName: "Procurement", aliases: [], generalMeaning: "Acquisition of goods or services needed for work.", contextKinds: ["PROJECT", "HYBRID"], familyRelevance: [family("PROCUREMENT", "PROJECT")], safeAssociations: [association("Budget")], rejectedConclusions: NO_STATE }),
  concept({ registryId: "project.deliverable", canonicalName: "Deliverable", aliases: [], generalMeaning: "A defined project output.", contextKinds: ["PROJECT"], familyRelevance: [family("DELIVERABLE", "PROJECT"), family("SCOPE", "PROJECT", "ADDITIONAL")], safeAssociations: [association("Milestone")], rejectedConclusions: NO_STATE }),
  concept({ registryId: "project.scope", canonicalName: "Project Scope", aliases: ["scope"], generalMeaning: "The agreed boundary of project work.", contextKinds: ["PROJECT"], familyRelevance: [family("SCOPE", "PROJECT")], safeAssociations: [association("Deliverable")], rejectedConclusions: NO_STATE }),
  concept({ registryId: "project.resource-availability", canonicalName: "Resource Availability", aliases: [], generalMeaning: "Availability of people, equipment, or other resources for planned project work.", contextKinds: ["PROJECT"], familyRelevance: [family("RESOURCE", "PROJECT", "PRIMARY", "PLANNED_PROJECT")], safeAssociations: [association("Schedule", "POTENTIALLY_RELATED_TO")], rejectedConclusions: NO_STATE }),
  concept({ registryId: "project.cost-variance", canonicalName: "Cost Variance", aliases: [], generalMeaning: "Difference between planned and observed project cost position.", contextKinds: ["PROJECT"], familyRelevance: [family("COST", "PROJECT")], safeAssociations: [association("Budget")], rejectedConclusions: NO_STATE }),
  concept({ registryId: "business.quality", canonicalName: "Quality", aliases: ["defect rate", "rework"], generalMeaning: "Conformance of outputs or work to expected requirements.", contextKinds: ["BUSINESS", "PROJECT", "HYBRID"], familyRelevance: [family("QUALITY", "BUSINESS"), family("QUALITY", "PROJECT")], safeAssociations: [], rejectedConclusions: NO_STATE }),
]);

export function normalizeEstablishedConceptMeaning(value: string): string {
  return value.trim().toLowerCase().replace(/%/g, " percent ").replace(/[^a-z0-9]+/g, " ").replace(/\s+/g, " ").trim();
}

export function findBusinessProjectConceptDefinition(establishedMeaning: string): BusinessProjectConceptDefinition | null {
  const normalized = normalizeEstablishedConceptMeaning(establishedMeaning);
  return BUSINESS_PROJECT_CONCEPT_REGISTRY.find((entry) => [entry.canonicalName, ...entry.aliases].some((candidate) => normalizeEstablishedConceptMeaning(candidate) === normalized)) ?? null;
}
