/** ASSISTANT-7:1 — Exactly 16 immutable descriptive planning contracts. */
import type { AssistantExecutiveActionPlanningContractMetadata } from "./assistantExecutiveActionPlanningFoundation.types.ts";

const declarations = Object.freeze([
  {
    name: "Executive Action Planning Contract",
    description:
      "Defines the canonical Executive Action Planning architectural domain.",
    responsibility: "Executive Action Planning",
    inputs: Object.freeze(["Upstream Object Context", "Executive Guidance"]),
    outputs: Object.freeze(["Action Planning Vocabulary"]),
    invariants: Object.freeze([
      "Metadata only",
      "No runtime planning engine",
    ]),
  },
  {
    name: "Action Plan Contract",
    description: "Defines Action Plan identity and structural metadata.",
    responsibility: "Action Plan",
    inputs: Object.freeze(["Action Objective", "Planning Context"]),
    outputs: Object.freeze(["Action Plan Identity"]),
    invariants: Object.freeze(["One canonical Action Plan identity"]),
  },
  {
    name: "Planned Action Contract",
    description: "Defines Planned Action identity within an Action Plan.",
    responsibility: "Planned Action",
    inputs: Object.freeze(["Action Plan Identity"]),
    outputs: Object.freeze(["Planned Action Identity"]),
    invariants: Object.freeze(["Planned Actions belong to an Action Plan"]),
  },
  {
    name: "Action Objective Contract",
    description: "Defines intended executive results for Action Plans.",
    responsibility: "Action Objective",
    inputs: Object.freeze(["Executive Object References"]),
    outputs: Object.freeze(["Action Objective Metadata"]),
    invariants: Object.freeze(["Explicit objective required conceptually"]),
  },
  {
    name: "Action Sequence Contract",
    description: "Defines descriptive ordering of planned actions.",
    responsibility: "Action Sequence",
    inputs: Object.freeze(["Planned Action Identities"]),
    outputs: Object.freeze(["Sequence Metadata"]),
    invariants: Object.freeze(["Ordering is descriptive only"]),
  },
  {
    name: "Action Dependency Contract",
    description: "Defines descriptive relationships between planned actions.",
    responsibility: "Action Dependency",
    inputs: Object.freeze(["Planned Action Identities"]),
    outputs: Object.freeze(["Dependency Metadata"]),
    invariants: Object.freeze(["No dependency resolution at runtime"]),
  },
  {
    name: "Action Ownership Contract",
    description: "Defines immutable owner references without assignment.",
    responsibility: "Action Owner Reference",
    inputs: Object.freeze(["Role", "Team", "Executive Entity References"]),
    outputs: Object.freeze(["Owner Reference Metadata"]),
    invariants: Object.freeze(["No automatic assignment", "No authorization"]),
  },
  {
    name: "Action Timing Contract",
    description: "Defines descriptive Action Time Horizon metadata.",
    responsibility: "Action Time Horizon",
    inputs: Object.freeze(["Planning Context"]),
    outputs: Object.freeze(["Time Horizon Metadata"]),
    invariants: Object.freeze(["No calendars", "No schedulers"]),
  },
  {
    name: "Action Milestone Contract",
    description: "Defines descriptive milestone checkpoint metadata.",
    responsibility: "Action Milestone",
    inputs: Object.freeze(["Action Plan Identity"]),
    outputs: Object.freeze(["Milestone Metadata"]),
    invariants: Object.freeze(["Milestones are non-scheduled"]),
  },
  {
    name: "Action Constraint Contract",
    description: "Defines descriptive plan and action constraint metadata.",
    responsibility: "Action Constraint",
    inputs: Object.freeze(["Policy", "Capacity", "Authority References"]),
    outputs: Object.freeze(["Constraint Metadata"]),
    invariants: Object.freeze(["Constraints remain descriptive only"]),
  },
  {
    name: "Action Outcome Contract",
    description: "Defines intended or expected result metadata.",
    responsibility: "Action Outcome",
    inputs: Object.freeze(["Action Plan", "Planned Action"]),
    outputs: Object.freeze(["Outcome Metadata"]),
    invariants: Object.freeze(["No outcome execution or monitoring"]),
  },
  {
    name: "Action Planning Context Contract",
    description: "Defines surrounding executive and business context metadata.",
    responsibility: "Action Planning Context",
    inputs: Object.freeze([
      "Conversation Context",
      "Workspace Context",
      "Executive Object",
    ]),
    outputs: Object.freeze(["Planning Context Metadata"]),
    invariants: Object.freeze(["Upstream identity preservation"]),
  },
  {
    name: "Action Planning Lifecycle Contract",
    description: "Defines descriptive Action Planning lifecycle states.",
    responsibility: "Action Planning Lifecycle",
    inputs: Object.freeze(["Action Plan Identity"]),
    outputs: Object.freeze(["Lifecycle Metadata"]),
    invariants: Object.freeze(["No automatic lifecycle transitions"]),
  },
  {
    name: "Action Planning Policy Contract",
    description: "Defines immutable Action Planning policy declarations.",
    responsibility: "Action Plan Policy",
    inputs: Object.freeze(["Architectural Standards"]),
    outputs: Object.freeze(["Policy Metadata"]),
    invariants: Object.freeze(["Policies are non-executable"]),
  },
  {
    name: "Action Planning Boundary Contract",
    description: "Defines prohibited Executive Action Planning surfaces.",
    responsibility: "Action Plan Boundary",
    inputs: Object.freeze(["Boundary Declarations"]),
    outputs: Object.freeze(["Boundary Metadata"]),
    invariants: Object.freeze(["No Runtime", "No OPS execution"]),
  },
  {
    name: "Action Planning Capability Contract",
    description: "Defines Action Planning capability declarations.",
    responsibility: "Action Planning Capability",
    inputs: Object.freeze(["Capability Declarations"]),
    outputs: Object.freeze(["Capability Metadata"]),
    invariants: Object.freeze(["Capabilities remain unimplemented"]),
  },
] as const);

export const AssistantExecutiveActionPlanningFoundationContracts:
readonly AssistantExecutiveActionPlanningContractMetadata[] = Object.freeze(
  declarations.map((declaration, index) => Object.freeze({
    id: `ASSISTANT-7:1/Contract/${String(index + 1).padStart(2, "0")}`,
    name: declaration.name,
    description: declaration.description,
    responsibility: declaration.responsibility,
    inputs: declaration.inputs,
    outputs: declaration.outputs,
    invariants: declaration.invariants,
    upstreamReferences: Object.freeze([
      "ASSISTANT-6:9/ObjectContextManagementPublicIndex",
    ]),
    downstreamCompatibility: Object.freeze([
      "ASSISTANT-7:2/ExecutiveActionPlanningRegistry",
    ]),
    version: "1.0.0",
    status: "Declared",
    tags: Object.freeze([
      "assistant",
      "executive-action-planning",
      "contract",
    ]),
    order: index + 1,
    executable: false,
    metadataOnly: true,
    immutable: true,
  })),
);
