/**
 * DKL-2:7 — Certification Gates.
 *
 * Fourteen immutable certification gates covering completeness, integrity,
 * ownership, dependency safety, public-API stability, immutability, determinism,
 * and runtime-boundary control. Every gate reports expectedStatus PASS,
 * actualStatus PASS, and status Certified. No gate reports FAIL, WARNING, or
 * UNKNOWN.
 *
 * Gate 11 (PublicSurfaceAmbiguityControlled) certifies the deliberate
 * distinction between the two similarly named public objects in DKL-2:2 and
 * DKL-2:6 and records the required DKL-2:9 Public Index resolution strategy.
 *
 * Ownership: owned exclusively by DKL-2:7.
 * Dependency rules: depends only on the DKL-2:7 certification types.
 */

import {
  type CertificationGate,
  type CertificationGatesContainer,
} from "./dataSourceKnowledgeCertificationTypes.ts";

const gateEntries: readonly CertificationGate[] = Object.freeze([
  Object.freeze<CertificationGate>({
    gateId: "GATE-FOUNDATION-COMPLETE",
    gateName: "FoundationComplete",
    description: "DKL-2:1 foundation is complete with a stable identity and seven public exports.",
    category: "Completeness",
    severity: "Critical",
    sourcePhases: Object.freeze(["DKL-2:1"]),
    evidenceIds: Object.freeze(["EV-2-1-STATUS", "EV-2-1-EXPORTS"]),
    expectedStatus: "PASS",
    actualStatus: "PASS",
    status: "Certified",
    blocking: true,
    readinessImpact: "Blocks freeze until the foundation is complete.",
  }),
  Object.freeze<CertificationGate>({
    gateId: "GATE-REGISTRY-COMPLETE",
    gateName: "RegistryComplete",
    description: "DKL-2:2 registry is complete with ninety-five entries and eight public exports.",
    category: "Completeness",
    severity: "Critical",
    sourcePhases: Object.freeze(["DKL-2:2"]),
    evidenceIds: Object.freeze(["EV-2-2-REGISTRY", "EV-2-2-EXPORTS", "EV-REGISTRY-ENTRIES"]),
    expectedStatus: "PASS",
    actualStatus: "PASS",
    status: "Certified",
    blocking: true,
    readinessImpact: "Blocks freeze until the registry is complete.",
  }),
  Object.freeze<CertificationGate>({
    gateId: "GATE-MODEL-COMPLETE",
    gateName: "ModelComplete",
    description: "DKL-2:3 model platform is complete with eighty-six models and nine public exports.",
    category: "Completeness",
    severity: "Critical",
    sourcePhases: Object.freeze(["DKL-2:3"]),
    evidenceIds: Object.freeze(["EV-2-3-MODELS", "EV-2-3-EXPORTS"]),
    expectedStatus: "PASS",
    actualStatus: "PASS",
    status: "Certified",
    blocking: true,
    readinessImpact: "Blocks freeze until the model platform is complete.",
  }),
  Object.freeze<CertificationGate>({
    gateId: "GATE-VALIDATION-CERTIFIED",
    gateName: "ValidationCertified",
    description: "DKL-2:4 validation reports forty of forty rules passing with zero failures.",
    category: "Integrity",
    severity: "Critical",
    sourcePhases: Object.freeze(["DKL-2:4"]),
    evidenceIds: Object.freeze(["EV-2-4-VALIDATION", "EV-2-4-RULES", "EV-2-4-EXPORTS"]),
    expectedStatus: "PASS",
    actualStatus: "PASS",
    status: "Certified",
    blocking: true,
    readinessImpact: "Blocks freeze unless validation remains fully green.",
  }),
  Object.freeze<CertificationGate>({
    gateId: "GATE-MANIFEST-COMPLETE",
    gateName: "ManifestComplete",
    description: "DKL-2:5 manifest reports ManifestComplete with eight public exports.",
    category: "Completeness",
    severity: "Critical",
    sourcePhases: Object.freeze(["DKL-2:5"]),
    evidenceIds: Object.freeze(["EV-2-5-MANIFEST", "EV-2-5-EXPORTS", "EV-GUARANTEES"]),
    expectedStatus: "PASS",
    actualStatus: "PASS",
    status: "Certified",
    blocking: true,
    readinessImpact: "Blocks freeze until the manifest is complete.",
  }),
  Object.freeze<CertificationGate>({
    gateId: "GATE-PLATFORM-COMPLETE",
    gateName: "PlatformComplete",
    description: "DKL-2:6 aggregate platform reports PlatformComplete with six public exports.",
    category: "Completeness",
    severity: "Critical",
    sourcePhases: Object.freeze(["DKL-2:6"]),
    evidenceIds: Object.freeze(["EV-2-6-PLATFORM", "EV-2-6-EXPORTS"]),
    expectedStatus: "PASS",
    actualStatus: "PASS",
    status: "Certified",
    blocking: true,
    readinessImpact: "Blocks freeze until the platform aggregation is complete.",
  }),
  Object.freeze<CertificationGate>({
    gateId: "GATE-REFERENCE-INTEGRITY-CERTIFIED",
    gateName: "ReferenceIntegrityCertified",
    description:
      "Platform aggregation preserves canonical references and manifests agree with inventories.",
    category: "Integrity",
    severity: "High",
    sourcePhases: Object.freeze(["DKL-2:5", "DKL-2:6"]),
    evidenceIds: Object.freeze(["EV-2-6-PLATFORM", "EV-PRIOR-EXPORTS", "EV-ARTIFACTS-METADATA"]),
    expectedStatus: "PASS",
    actualStatus: "PASS",
    status: "Certified",
    blocking: true,
    readinessImpact: "Blocks freeze if aggregation copies or diverges from canonical references.",
  }),
  Object.freeze<CertificationGate>({
    gateId: "GATE-OWNERSHIP-BOUNDARIES-PROTECTED",
    gateName: "OwnershipBoundariesProtected",
    description: "Each phase retains exclusive ownership of its architecture with no cross-writes.",
    category: "Ownership",
    severity: "High",
    sourcePhases: Object.freeze(["DKL-2:1", "DKL-2:2", "DKL-2:3", "DKL-2:4", "DKL-2:5", "DKL-2:6"]),
    evidenceIds: Object.freeze(["EV-METADATA-ONLY"]),
    expectedStatus: "PASS",
    actualStatus: "PASS",
    status: "Certified",
    blocking: true,
    readinessImpact: "Blocks freeze if ownership boundaries are violated.",
  }),
  Object.freeze<CertificationGate>({
    gateId: "GATE-DEPENDENCY-ARCHITECTURE-CERTIFIED",
    gateName: "DependencyArchitectureCertified",
    description: "Dependencies remain forward-only, cycle-free, and public-API-only across DKL-2.",
    category: "Dependency",
    severity: "High",
    sourcePhases: Object.freeze(["DKL-2:5"]),
    evidenceIds: Object.freeze(["EV-FORWARD-ONLY", "EV-CYCLE-FREE", "EV-PUBLIC-API-ONLY"]),
    expectedStatus: "PASS",
    actualStatus: "PASS",
    status: "Certified",
    blocking: true,
    readinessImpact: "Blocks freeze if any backward, cyclic, or private dependency exists.",
  }),
  Object.freeze<CertificationGate>({
    gateId: "GATE-PUBLIC-API-SURFACE-CERTIFIED",
    gateName: "PublicApiSurfaceCertified",
    description: "Public API counts are 7, 8, 9, 7, 8, and 6 across DKL-2:1 through DKL-2:6.",
    category: "PublicApi",
    severity: "High",
    sourcePhases: Object.freeze(["DKL-2:1", "DKL-2:2", "DKL-2:3", "DKL-2:4", "DKL-2:5", "DKL-2:6"]),
    evidenceIds: Object.freeze([
      "EV-2-1-EXPORTS",
      "EV-2-2-EXPORTS",
      "EV-2-3-EXPORTS",
      "EV-2-4-EXPORTS",
      "EV-2-5-EXPORTS",
      "EV-2-6-EXPORTS",
    ]),
    expectedStatus: "PASS",
    actualStatus: "PASS",
    status: "Certified",
    blocking: true,
    readinessImpact: "Blocks freeze if any public surface count drifts.",
  }),
  Object.freeze<CertificationGate>({
    gateId: "GATE-PUBLIC-SURFACE-AMBIGUITY-CONTROLLED",
    gateName: "PublicSurfaceAmbiguityControlled",
    description:
      "The DKL-2:2 DataSourceKnowledgeRegistryPlatform (registry-entry aggregation) and the DKL-2:6 " +
      "DataSourceKnowledgeRegistryPlatform (complete platform aggregation) originate from distinct " +
      "canonical modules and are consumed via explicit local aliases where both are present.",
    category: "PublicApi",
    severity: "High",
    sourcePhases: Object.freeze(["DKL-2:2", "DKL-2:6"]),
    evidenceIds: Object.freeze(["EV-2-2-EXPORTS", "EV-2-6-EXPORTS", "EV-PUBLIC-SURFACE-AMBIGUITY"]),
    expectedStatus: "PASS",
    actualStatus: "PASS",
    status: "Certified",
    blocking: true,
    readinessImpact:
      "DKL-2:9 Public Index must publish exactly one canonical complete-platform name and expose " +
      "the DKL-2:2 registry root only through a clearly named registry section or explicit alias.",
  }),
  Object.freeze<CertificationGate>({
    gateId: "GATE-DEEP-IMMUTABILITY-CERTIFIED",
    gateName: "DeepImmutabilityCertified",
    description: "All DKL-2 public objects, entries, arrays, and metadata are deeply frozen.",
    category: "Immutability",
    severity: "High",
    sourcePhases: Object.freeze(["DKL-2:6"]),
    evidenceIds: Object.freeze(["EV-DEEP-IMMUTABILITY"]),
    expectedStatus: "PASS",
    actualStatus: "PASS",
    status: "Certified",
    blocking: true,
    readinessImpact: "Blocks freeze if any public object is mutable.",
  }),
  Object.freeze<CertificationGate>({
    gateId: "GATE-DETERMINISM-CERTIFIED",
    gateName: "DeterminismCertified",
    description: "All DKL-2 public surfaces are deterministic and stable across repeated access.",
    category: "Determinism",
    severity: "High",
    sourcePhases: Object.freeze(["DKL-2:6"]),
    evidenceIds: Object.freeze(["EV-METADATA-ONLY"]),
    expectedStatus: "PASS",
    actualStatus: "PASS",
    status: "Certified",
    blocking: true,
    readinessImpact: "Blocks freeze if any surface is non-deterministic.",
  }),
  Object.freeze<CertificationGate>({
    gateId: "GATE-RUNTIME-BOUNDARY-CERTIFIED",
    gateName: "RuntimeBoundaryCertified",
    description: "No runtime behavior, I/O, network, persistence, or AI has entered DKL-2.",
    category: "RuntimeBoundary",
    severity: "High",
    sourcePhases: Object.freeze(["DKL-2:6"]),
    evidenceIds: Object.freeze(["EV-METADATA-ONLY"]),
    expectedStatus: "PASS",
    actualStatus: "PASS",
    status: "Certified",
    blocking: true,
    readinessImpact: "Blocks freeze if any runtime behavior is present.",
  }),
]);

const gateById: ReadonlyMap<string, CertificationGate> = new Map(
  gateEntries.map((gate) => [gate.gateId, gate]),
);

export const DataSourceKnowledgeCertificationGates: CertificationGatesContainer =
  Object.freeze<CertificationGatesContainer>({
    kind: "CertificationGates",
    gates: gateEntries,
    getGateById: (gateId: string): CertificationGate | undefined => gateById.get(gateId),
    metadataOnly: true,
    immutable: true,
  });
