/**
 * DKL-8:1 — Knowledge Governance Boundaries.
 *
 * Explicit immutable boundaries separating Knowledge Governance from
 * enforcement, persistence, retrieval, Engine, NEA, UI, and related surfaces.
 *
 * Ownership: owned exclusively by DKL-8:1.
 */

export const KNOWLEDGE_GOVERNANCE_PROHIBITED_SURFACES = Object.freeze([
  "Authentication",
  "Authorization runtime",
  "RBAC engine",
  "ABAC engine",
  "Policy evaluation engine",
  "Policy execution",
  "Compliance engine",
  "Audit event storage",
  "Audit event listeners",
  "Legal interpretation",
  "Privacy law interpretation",
  "User management",
  "Identity provider integration",
  "Database schemas",
  "Repository writes",
  "Knowledge search",
  "Knowledge retrieval",
  "Graph traversal",
  "Data ingestion",
  "Parsing",
  "AI inference",
  "LLM calls",
  "Executive reasoning",
  "Workflow automation",
  "Approvals runtime",
  "Notifications",
  "UI components",
  "React components",
  "API routes",
  "HTTP clients",
  "Webhooks",
  "Queues",
  "Schedulers",
  "Caching",
  "Telemetry",
  "NEA channel transport",
  "Telegram integration",
  "WhatsApp integration",
  "Slack integration",
  "Teams integration",
  "Email transport",
  "Voice transport",
  "REST endpoints",
  "MCP transport",
  "SDK transport",
  "Scene rendering",
  "Advisor responses",
] as const);

/** Canonical immutable boundary declarations. */
export const KnowledgeGovernanceBoundaries = Object.freeze({
  boundariesId: "DKL-8:1/KnowledgeGovernanceBoundaries",
  sourcePhase: "DKL-8:1" as const,
  consumes: Object.freeze(["DKL-7 Public Index"] as const),
  provides: Object.freeze(["Knowledge Governance Foundation"] as const),
  prohibitedSurfaces: KNOWLEDGE_GOVERNANCE_PROHIBITED_SURFACES,
  prohibitedSurfaceCount: KNOWLEDGE_GOVERNANCE_PROHIBITED_SURFACES.length,
  runtimeEnforcement: false as const,
  layerSeparation: Object.freeze({
    neaOwnsChannelsAndTransport: true as const,
    dkl6OwnsPersistenceAndRepository: true as const,
    dkl7OwnsKnowledgeServicesAccess: true as const,
    engineOwnsReasoningAndDecisions: true as const,
    advisorSceneOwnPresentation: true as const,
    dkl8OwnsGovernanceSemanticsOnly: true as const,
  }),
  authenticates: false as const,
  authorizes: false as const,
  executesPolicy: false as const,
  evaluatesCompliance: false as const,
  storesAuditEvents: false as const,
  persistsRepositoryRecords: false as const,
  retrievesKnowledge: false as const,
  searchesKnowledge: false as const,
  traversesGraphs: false as const,
  makesExecutiveDecisions: false as const,
  rendersUi: false as const,
  rendersScene: false as const,
  connectsNeaChannels: false as const,
  interpretsLaw: false as const,
  metadataOnly: true as const,
  immutable: true as const,
  deterministic: true as const,
});
