/**
 * DKL-7:7 — Knowledge Services Certification Compatibility.
 *
 * Exactly sixteen immutable Compatible declarations.
 * Runtime authorization remains None.
 *
 * Ownership: owned exclusively by DKL-7:7.
 */

import {
  KnowledgeServicesPlatform,
  KnowledgeServicesPlatformId,
} from "./knowledgeServicesPlatform.ts";
import type { KnowledgeServicesCertificationCompatibilityDeclaration } from "./knowledgeServicesCertificationTypes.ts";

const platform = KnowledgeServicesPlatform;

const compat = (
  key: string,
  subject: string,
  direction: string,
  compatibilityType: string,
  canonicalPath: string,
  ownershipConstraint: string,
  boundaryConstraint: string,
  changePolicy: string,
  evidenceReference: string,
  freezeRelevance: string,
  order: number,
): KnowledgeServicesCertificationCompatibilityDeclaration =>
  Object.freeze({
    compatibilityId: `DKL-7:7/Compatibility/${key}`,
    subject,
    direction,
    compatibilityType,
    status: "Compatible" as const,
    certificationResult: "Pass" as const,
    canonicalPath,
    ownershipConstraint,
    boundaryConstraint,
    changePolicy,
    runtimeAuthorization: "None" as const,
    evidenceReference,
    freezeRelevance,
    deterministicOrder: order,
  });

/** Exactly sixteen Certification compatibility declarations. */
export const KnowledgeServicesCertificationCompatibility: readonly KnowledgeServicesCertificationCompatibilityDeclaration[] =
  Object.freeze([
    compat(
      "Foundation",
      "Foundation certified compatibility",
      "Backward",
      "PhaseCertification",
      `Certification → Platform → … → ${platform.identity.foundationId}`,
      "DKL-7 ownership unchanged",
      "29 prohibited surfaces preserved",
      "AdditiveOnly",
      "KS-CERT-EV-005",
      "Must preserve through Freeze",
      1,
    ),
    compat(
      "Registry",
      "Registry certified compatibility",
      "Backward",
      "PhaseCertification",
      `Certification → Platform → … → ${platform.identity.registryId}`,
      "Registry inventories preserved",
      "Read-only access preserved",
      "AdditiveOnly",
      "KS-CERT-EV-006",
      "Must preserve through Freeze",
      2,
    ),
    compat(
      "Model",
      "Model certified compatibility",
      "Backward",
      "PhaseCertification",
      `Certification → Platform → … → ${platform.identity.modelId}`,
      "Model inventory 79 preserved",
      "No mutation modes",
      "AdditiveOnly",
      "KS-CERT-EV-008",
      "Must preserve through Freeze",
      3,
    ),
    compat(
      "Validation",
      "Validation certified compatibility",
      "Backward",
      "PhaseCertification",
      `Certification → Platform → … → ${platform.identity.validationId}`,
      "Validation Pass state preserved",
      "No runtime validation introduced",
      "AdditiveOnly",
      "KS-CERT-EV-010",
      "Must preserve through Freeze",
      4,
    ),
    compat(
      "Manifest",
      "Manifest certified compatibility",
      "Backward",
      "PhaseCertification",
      `Certification → Platform → ${platform.identity.manifestId}`,
      "Manifest inventory 447 preserved",
      "ManifestComplete preserved",
      "AdditiveOnly",
      "KS-CERT-EV-012",
      "Must preserve through Freeze",
      5,
    ),
    compat(
      "Platform",
      "Platform certified compatibility",
      "Direct",
      "PhaseCertification",
      `Certification → ${KnowledgeServicesPlatformId}`,
      "Platform inventory 527 preserved",
      "PlatformComplete preserved",
      "AdditiveOnly",
      "KS-CERT-EV-014",
      "Must preserve through Freeze",
      6,
    ),
    compat(
      "DKL6PublicIndex",
      "DKL-6 Public Index indirect compatibility",
      "Indirect",
      "UpstreamCompatibility",
      `Certification → Platform → … → ${platform.identity.dkl6PublicIndexId}`,
      "DKL-6 ownership outside DKL-7",
      "No DKL-6 reconstruction",
      "AdditiveOnly",
      "KS-CERT-EV-004",
      "Must preserve through Freeze",
      7,
    ),
    compat(
      "FutureFreeze",
      "Future Freeze compatibility",
      "Forward",
      "FuturePhase",
      "Freeze → Certification → Platform",
      "Freeze consumes Certification only",
      "No Platform bypass",
      "AdditiveOnly",
      "KS-CERT-EV-018",
      "Defines Freeze consumer path",
      8,
    ),
    compat(
      "FuturePublicIndex",
      "Future Public Index compatibility",
      "Forward",
      "FuturePhase",
      "Public Index → Freeze → Certification",
      "Public Index consumes Freeze only",
      "No Certification bypass",
      "AdditiveOnly",
      "KS-CERT-EV-016",
      "Defines Public Index path",
      9,
    ),
    compat(
      "ExecutiveEngine",
      "Executive Engine consumer compatibility",
      "Consumer",
      "FutureConsumer",
      "Executive Engine → Public Index → … → Platform",
      "Engine does not own Knowledge Services",
      "No direct Platform import",
      "AdditiveOnly",
      "KS-CERT-EV-016",
      "Consumer path locked for Freeze",
      10,
    ),
    compat(
      "Advisor",
      "Advisor consumer compatibility",
      "Consumer",
      "FutureConsumer",
      "Advisor → Public Index → … → Platform",
      "Advisor does not own Knowledge Services",
      "No direct Platform import",
      "AdditiveOnly",
      "KS-CERT-EV-016",
      "Consumer path locked for Freeze",
      11,
    ),
    compat(
      "ApprovedInternal",
      "Approved internal consumer compatibility",
      "Consumer",
      "FutureConsumer",
      "Approved internal → Public Index → … → Platform",
      "Internal consumers use Public Index only",
      "Runtime authorization None",
      "AdditiveOnly",
      "KS-CERT-EV-016",
      "Consumer path locked for Freeze",
      12,
    ),
    compat(
      "BackwardDKL71To76",
      "Backward compatibility through DKL-7:1–7:6",
      "Backward",
      "ChainCompatibility",
      "Certification → Platform → Manifest → Validation → Model → Registry → Foundation",
      "No reconstruction of prior phases",
      "Boundaries unchanged",
      "AdditiveOnly",
      "KS-CERT-EV-004",
      "Must preserve through Freeze",
      13,
    ),
    compat(
      "AdditiveExtension",
      "Additive-extension compatibility",
      "Extension",
      "AdditiveCompatibility",
      "Certification additive metadata only",
      "No ownership expansion",
      "No boundary weakening",
      "AdditiveOnly",
      "KS-CERT-EV-015",
      "Guides Freeze change policy",
      14,
    ),
    compat(
      "FreezePreservation",
      "Freeze preservation compatibility",
      "Forward",
      "FreezePreparation",
      "Freeze must preserve Certification Pass state",
      "Certification inventories frozen by reference",
      "No runtime authorization",
      "AdditiveOnly",
      "KS-CERT-EV-018",
      "Required Freeze input",
      15,
    ),
    compat(
      "PublicReleasePreparation",
      "Public release preparation compatibility",
      "Forward",
      "ReleasePreparation",
      "Public Index preparation through Freeze",
      "No Released claim at Certification",
      "No consumer runtime access",
      "AdditiveOnly",
      "KS-CERT-EV-018",
      "Prepares future Public Index",
      16,
    ),
  ]);
