/**
 * DKL-5:7 — Knowledge Validation Certification Gates.
 *
 * Immutable catalog of mandatory certification gates. Metadata only.
 * Evaluation occurs in knowledgeValidationCertification.ts.
 *
 * Ownership: owned exclusively by DKL-5:7.
 */

import type {
  CertificationCategory,
  CertificationGateDefinition,
  CertificationSeverity,
} from "./knowledgeValidationCertificationTypes.ts";

const OWNER = "DKL-5 Knowledge Validation Certification";

export const KNOWLEDGE_VALIDATION_CERTIFICATION_CATEGORIES: readonly CertificationCategory[] =
  Object.freeze([
    "Identity",
    "Foundation",
    "Registry",
    "Model",
    "Validation",
    "Manifest",
    "Platform",
    "Evidence",
    "Explainability",
    "Consumer Readiness",
    "Executive Usability",
    "Ownership",
    "Dependencies",
    "Compatibility",
    "Extension",
    "Immutability",
    "Determinism",
    "Runtime Prohibition",
    "Scoring Prohibition",
    "Trust-Calculation Prohibition",
    "Cleansing Prohibition",
    "Remediation Prohibition",
    "Regression Protection",
    "Freeze Readiness",
  ]);

const gate = (
  id: string,
  name: string,
  description: string,
  category: CertificationCategory,
  severity: CertificationSeverity,
  sourceComponent: string,
  requirement: string,
  evidenceTarget: string,
  expectedCondition: string,
  failureMeaning: string,
): CertificationGateDefinition =>
  Object.freeze({
    id,
    name,
    description,
    category,
    severity,
    sourceComponent,
    requirement,
    evidenceTarget,
    expectedCondition,
    failureMeaning,
    ownership: OWNER,
    mandatory: true as const,
    deterministic: true as const,
    runtimeDataRequired: false as const,
  });

/** Canonical immutable certification gate catalog (85 mandatory gates). */
export const KnowledgeValidationCertificationGates: readonly CertificationGateDefinition[] =
  Object.freeze([
    gate("KV-CERT-001", "Platform identity exists", "Platform identity is declared.", "Identity", "Critical", "DKL-5:6", "Platform identity must exist.", "platform.identity.platformId", "DKL-5:6/KnowledgeValidationPlatform", "Certification cannot proceed without Platform identity."),
    gate("KV-CERT-002", "Platform version exists", "Platform version is declared and stable.", "Identity", "Critical", "DKL-5:6", "Platform version must exist.", "platform.version", "1.0.0", "Version drift blocks freeze stability."),
    gate("KV-CERT-003", "Platform namespace exists", "Platform namespace is declared.", "Identity", "Critical", "DKL-5:6", "Platform namespace must exist.", "platform.namespace", "nexora.dkl.knowledge-validation.platform", "Namespace absence blocks consumer discovery."),
    gate("KV-CERT-004", "Platform status is PlatformComplete", "Platform reports PlatformComplete.", "Platform", "Critical", "DKL-5:6", "Platform must be complete.", "platform.identity.status", "PlatformComplete", "Incomplete Platform blocks Certification."),
    gate("KV-CERT-005", "Platform readiness is ReadyForCertification", "Platform readiness must be ReadyForCertification.", "Platform", "Critical", "DKL-5:6", "Platform must be ready for Certification.", "platform.identity.readiness", "ReadyForCertification", "Premature Certification is forbidden."),
    gate("KV-CERT-006", "Platform validation status is Pass", "Platform validation status is Pass.", "Platform", "Critical", "DKL-5:6", "Platform validation status must be Pass.", "platform.identity.validationStatus", "Pass", "Failed validation status blocks Certification."),
    gate("KV-CERT-007", "All 27 Platform readiness gates pass", "Every Platform readiness gate reports Pass.", "Platform", "Critical", "DKL-5:6", "All Platform readiness gates must pass.", "platform.readiness.gates", "27/27 Pass", "Failed Platform gates invalidate Certification."),
    gate("KV-CERT-008", "Exactly six ordered Platform sections exist", "Platform exposes exactly six sections.", "Platform", "Critical", "DKL-5:6", "Exactly six Platform sections must exist.", "platform.sections", "count=6", "Wrong section count invalidates composition."),
    gate("KV-CERT-009", "Platform section order is correct", "Section order is metadata→foundation→registry→model→validation→manifest.", "Platform", "Critical", "DKL-5:6", "Section order must be deterministic and correct.", "platform.sectionOrder", "metadata→foundation→registry→model→validation→manifest", "Incorrect ordering breaks composition guarantees."),
    gate("KV-CERT-010", "Foundation reference is canonical", "Platform foundation is identity-equal to sections.foundation.", "Foundation", "Critical", "DKL-5:6", "Foundation must be included by canonical reference.", "platform.foundation", "identity-equal reference", "Copied Foundation metadata invalidates Certification."),
    gate("KV-CERT-011", "Registry reference is canonical", "Platform registry is identity-equal to sections.registry.", "Registry", "Critical", "DKL-5:6", "Registry must be included by canonical reference.", "platform.registry", "identity-equal reference", "Copied Registry metadata invalidates Certification."),
    gate("KV-CERT-012", "Model reference is canonical", "Platform model is identity-equal to sections.model.", "Model", "Critical", "DKL-5:6", "Model must be included by canonical reference.", "platform.model", "identity-equal reference", "Copied Model metadata invalidates Certification."),
    gate("KV-CERT-013", "Validation reference is canonical", "Platform validation is identity-equal to sections.validation.", "Validation", "Critical", "DKL-5:6", "Validation must be included by canonical reference.", "platform.validation", "identity-equal reference", "Copied Validation metadata invalidates Certification."),
    gate("KV-CERT-014", "Manifest reference is canonical", "Platform manifest is identity-equal to sections.manifest.", "Manifest", "Critical", "DKL-5:6", "Manifest must be included by canonical reference.", "platform.manifest", "identity-equal reference", "Copied Manifest metadata invalidates Certification."),
    gate("KV-CERT-015", "Exactly five Platform components exist", "Platform component registry has five entries.", "Platform", "Critical", "DKL-5:6", "Exactly five components must exist.", "platform.components.componentCount", "5", "Wrong component count invalidates Platform."),
    gate("KV-CERT-016", "Every component is included by reference", "All components declare includedByReference=true.", "Platform", "Critical", "DKL-5:6", "Every component must be included by reference.", "platform.components.components.includedByReference", "all true", "Copied components invalidate Certification."),
    gate("KV-CERT-017", "No component is re-owned by Platform", "All components declare ownedByPlatform=false.", "Ownership", "Critical", "DKL-5:6", "Platform must not re-own upstream components.", "platform.components.components.ownedByPlatform", "all false", "Re-ownership violates phase boundaries."),
    gate("KV-CERT-018", "Foundation status is FoundationComplete", "Foundation reports FoundationComplete.", "Foundation", "Critical", "DKL-5:1", "Foundation status must be FoundationComplete.", "platform.foundation.identity.status", "FoundationComplete", "Incomplete Foundation blocks Certification."),
    gate("KV-CERT-019", "Foundation readiness is ReadyForRegistry", "Foundation readiness is ReadyForRegistry.", "Foundation", "Critical", "DKL-5:1", "Foundation must be ReadyForRegistry.", "platform.foundation.identity.readiness", "ReadyForRegistry", "Incorrect Foundation readiness blocks Certification."),
    gate("KV-CERT-020", "Registry status is RegistryComplete", "Registry reports RegistryComplete.", "Registry", "Critical", "DKL-5:2", "Registry status must be RegistryComplete.", "platform.registry.identity.status", "RegistryComplete", "Incomplete Registry blocks Certification."),
    gate("KV-CERT-021", "Registry readiness is ReadyForModel", "Registry readiness is ReadyForModel.", "Registry", "Critical", "DKL-5:2", "Registry must be ReadyForModel.", "platform.registry.identity.readiness", "ReadyForModel", "Incorrect Registry readiness blocks Certification."),
    gate("KV-CERT-022", "Model status is ModelComplete", "Model reports ModelComplete.", "Model", "Critical", "DKL-5:3", "Model status must be ModelComplete.", "platform.model.identity.status", "ModelComplete", "Incomplete Model blocks Certification."),
    gate("KV-CERT-023", "Model readiness is ReadyForValidation", "Model readiness is ReadyForValidation.", "Model", "Critical", "DKL-5:3", "Model must be ReadyForValidation.", "platform.model.identity.readiness", "ReadyForValidation", "Incorrect Model readiness blocks Certification."),
    gate("KV-CERT-024", "Validation status is ValidationComplete", "Validation reports ValidationComplete.", "Validation", "Critical", "DKL-5:4", "Validation status must be ValidationComplete.", "platform.validation.identity.status", "ValidationComplete", "Incomplete Validation blocks Certification."),
    gate("KV-CERT-025", "Validation result is Pass", "Validation overall result is Pass.", "Validation", "Critical", "DKL-5:4", "Validation overall result must be Pass.", "platform.validation.result.overallStatus", "Pass", "Failed Validation blocks Certification."),
    gate("KV-CERT-026", "Validation readiness is ReadyForManifest", "Validation readiness is ReadyForManifest.", "Validation", "Critical", "DKL-5:4", "Validation must be ReadyForManifest.", "platform.validation.identity.readiness", "ReadyForManifest", "Incorrect Validation readiness blocks Certification."),
    gate("KV-CERT-027", "Manifest status is ManifestComplete", "Manifest reports ManifestComplete.", "Manifest", "Critical", "DKL-5:5", "Manifest status must be ManifestComplete.", "platform.manifest.identity.status", "ManifestComplete", "Incomplete Manifest blocks Certification."),
    gate("KV-CERT-028", "Manifest readiness is ReadyForPlatform", "Manifest readiness is ReadyForPlatform.", "Manifest", "Critical", "DKL-5:5", "Manifest must be ReadyForPlatform.", "platform.manifest.identity.readiness", "ReadyForPlatform", "Incorrect Manifest readiness blocks Certification."),
    gate("KV-CERT-029", "All 15 Manifest readiness gates pass", "Every Manifest readiness gate reports Pass.", "Manifest", "Critical", "DKL-5:5", "All Manifest readiness gates must pass.", "platform.manifest.manifestReadiness", "15/15 Pass", "Failed Manifest gates invalidate Certification."),
    gate("KV-CERT-030", "All 63 architectural validation rules pass", "Validation pass count is 63.", "Validation", "Critical", "DKL-5:4", "All architectural validation rules must pass.", "platform.validation.result.summary.passCount", "63", "Failed architectural rules block Certification."),
    gate("KV-CERT-031", "Validation fail count is zero", "Validation fail count is 0.", "Validation", "Critical", "DKL-5:4", "Validation fail count must be zero.", "platform.validation.result.summary.failCount", "0", "Any Fail blocks Certification."),
    gate("KV-CERT-032", "Every validation rule has evidence", "Each rule result includes evidence.", "Evidence", "Critical", "DKL-5:4", "Every validation rule must have evidence.", "platform.validation.result.ruleResults.evidence", "63 evidence records", "Missing evidence breaks evidence-oriented guarantees."),
    gate("KV-CERT-033", "Validation evidence is frozen", "Validation result and evidence structures are frozen.", "Evidence", "Critical", "DKL-5:4", "Validation evidence must be frozen.", "platform.validation.result", "Object.isFrozen=true", "Mutable evidence invalidates Certification."),
    gate("KV-CERT-034", "Foundation contains 20 contract kinds", "Foundation contractKinds length is 20.", "Foundation", "High", "DKL-5:1", "Exactly 20 contract kinds must exist.", "platform.foundation.contracts.contractKinds", "20", "Contract count drift breaks freeze stability."),
    gate("KV-CERT-035", "Foundation contains 19 validation targets", "Foundation targetCategories length is 19.", "Foundation", "High", "DKL-5:1", "Exactly 19 validation targets must exist.", "platform.foundation.contracts.targetCategories", "19", "Target count drift breaks freeze stability."),
    gate("KV-CERT-036", "Foundation contains 20 validation dimensions", "Foundation dimensions length is 20.", "Foundation", "High", "DKL-5:1", "Exactly 20 validation dimensions must exist.", "platform.foundation.contracts.dimensions", "20", "Dimension count drift breaks freeze stability."),
    gate("KV-CERT-037", "Foundation contains 20 quality signals", "Foundation qualitySignals length is 20.", "Foundation", "High", "DKL-5:1", "Exactly 20 quality signals must exist.", "platform.foundation.contracts.qualitySignals", "20", "Signal count drift breaks freeze stability."),
    gate("KV-CERT-038", "Foundation contains 11 outcomes", "Foundation outcomes length is 11.", "Foundation", "High", "DKL-5:1", "Exactly 11 outcomes must exist.", "platform.foundation.contracts.outcomes", "11", "Outcome count drift breaks freeze stability."),
    gate("KV-CERT-039", "Foundation contains 6 severities", "Foundation severities length is 6.", "Foundation", "High", "DKL-5:1", "Exactly 6 severities must exist.", "platform.foundation.contracts.severities", "6", "Severity count drift breaks freeze stability."),
    gate("KV-CERT-040", "Registry contains 24 collections", "Registry collection count is 24.", "Registry", "High", "DKL-5:2", "Exactly 24 registry collections must exist.", "platform.registry.summary.registryCategoryCount", "24", "Collection count drift breaks freeze stability."),
    gate("KV-CERT-041", "Registry contains 266 entries", "Registry total entry count is 266.", "Registry", "High", "DKL-5:2", "Exactly 266 registry entries must exist.", "platform.registry.summary.totalEntryCount", "266", "Entry count drift breaks freeze stability."),
    gate("KV-CERT-042", "Model contains 30 canonical models", "Model catalog modelCount is 30.", "Model", "High", "DKL-5:3", "Exactly 30 canonical models must exist.", "platform.model.catalog.modelCount", "30", "Model count drift breaks freeze stability."),
    gate("KV-CERT-043", "Model contains 14 structural relationships", "Model relationship declarationCount is 14.", "Model", "High", "DKL-5:3", "Exactly 14 structural relationships must exist.", "platform.model.relationships.declarationCount", "14", "Relationship count drift breaks freeze stability."),
    gate("KV-CERT-044", "Validation contains 27 categories", "Validation categories length is 27.", "Validation", "High", "DKL-5:4", "Exactly 27 validation categories must exist.", "platform.validation.categories", "27", "Category count drift breaks freeze stability."),
    gate("KV-CERT-045", "Validation contains 63 rules", "Validation rules length is 63.", "Validation", "High", "DKL-5:4", "Exactly 63 validation rules must exist.", "platform.validation.rules", "63", "Rule count drift breaks freeze stability."),
    gate("KV-CERT-046", "Manifest inventories match Platform inventory", "Manifest counts match Platform inventory.", "Manifest", "Critical", "DKL-5:5", "Manifest inventories must match Platform inventory.", "platform.inventory vs platform.manifest.counts", "matched", "Inventory mismatch invalidates Certification."),
    gate("KV-CERT-047", "Public API counts are internally consistent", "Upstream 40 + Platform 8 = 48.", "Platform", "Critical", "DKL-5:6", "Public API counts must be consistent.", "platform.inventory.totalPublicApiCount", "48", "Inconsistent public API counts block Freeze."),
    gate("KV-CERT-048", "Ownership conflicts are absent", "No ownership transfer or re-ownership.", "Ownership", "Critical", "DKL-5:6", "Ownership conflicts must be absent.", "platform.metadata.ownership", "noOwnershipTransfer=true", "Ownership conflicts block Freeze."),
    gate("KV-CERT-049", "Public-entry-point-only dependencies are satisfied", "Dependencies are public-entry-point-only.", "Dependencies", "Critical", "DKL-5:6", "Dependencies must be public-entry-point-only.", "platform.dependencies.publicEntryPointOnly", "true", "Internal imports invalidate Certification."),
    gate("KV-CERT-050", "No direct DKL-4 dependency exists", "Platform declares no direct DKL-4 dependency.", "Dependencies", "Critical", "DKL-5:6", "No direct DKL-4 dependency may exist.", "platform.dependencies.noDirectDkl4Dependency", "true", "Direct DKL-4 dependency violates approved dependency rule."),
    gate("KV-CERT-051", "No future-phase dependency exists", "Platform declares no future-phase dependency.", "Dependencies", "Critical", "DKL-5:6", "No future-phase dependency may exist.", "platform.dependencies.noFuturePhases", "true", "Future-phase dependency violates layering."),
    gate("KV-CERT-052", "No circular dependency exists", "Platform declares no circular dependency.", "Dependencies", "Critical", "DKL-5:6", "No circular dependency may exist.", "platform.dependencies.noCircularDependency", "true", "Circular dependency invalidates Certification."),
    gate("KV-CERT-053", "No external library dependency exists", "Platform declares no external package dependency.", "Dependencies", "Critical", "DKL-5:6", "No external library dependency may exist.", "platform.dependencies.noExternalPackageDependency", "true", "External libraries are forbidden."),
    gate("KV-CERT-054", "Compatibility declarations are complete", "Platform compatibility entries cover required subjects.", "Compatibility", "High", "DKL-5:6", "Compatibility declarations must be complete.", "platform.compatibility.entryCount", ">=20", "Incomplete compatibility blocks Freeze."),
    gate("KV-CERT-055", "Extension declarations are additive and controlled", "Extensions are additive with mutable registration forbidden.", "Extension", "High", "DKL-5:6", "Extensions must be additive and controlled.", "platform.extensions.policy", "additive + mutableRuntimeRegistrationForbidden", "Uncontrolled extensions block Freeze."),
    gate("KV-CERT-056", "Foundation metadata is frozen", "Foundation aggregate is frozen.", "Immutability", "Critical", "DKL-5:1", "Foundation metadata must be frozen.", "platform.foundation", "Object.isFrozen=true", "Mutable Foundation blocks Freeze."),
    gate("KV-CERT-057", "Registry metadata is frozen", "Registry aggregate is frozen.", "Immutability", "Critical", "DKL-5:2", "Registry metadata must be frozen.", "platform.registry", "Object.isFrozen=true", "Mutable Registry blocks Freeze."),
    gate("KV-CERT-058", "Model metadata is frozen", "Model aggregate is frozen.", "Immutability", "Critical", "DKL-5:3", "Model metadata must be frozen.", "platform.model", "Object.isFrozen=true", "Mutable Model blocks Freeze."),
    gate("KV-CERT-059", "Validation metadata is frozen", "Validation aggregate is frozen.", "Immutability", "Critical", "DKL-5:4", "Validation metadata must be frozen.", "platform.validation", "Object.isFrozen=true", "Mutable Validation blocks Freeze."),
    gate("KV-CERT-060", "Manifest metadata is frozen", "Manifest aggregate is frozen.", "Immutability", "Critical", "DKL-5:5", "Manifest metadata must be frozen.", "platform.manifest", "Object.isFrozen=true", "Mutable Manifest blocks Freeze."),
    gate("KV-CERT-061", "Platform metadata is frozen", "Platform aggregate is frozen.", "Immutability", "Critical", "DKL-5:6", "Platform metadata must be frozen.", "platform", "Object.isFrozen=true", "Mutable Platform blocks Freeze."),
    gate("KV-CERT-062", "Certification evaluation is deterministic", "Platform and Certification declare deterministic=true.", "Determinism", "Critical", "DKL-5:6", "Certification evaluation must be deterministic.", "platform.deterministic", "true", "Non-deterministic evaluation blocks Freeze."),
    gate("KV-CERT-063", "Evidence-oriented architecture is preserved", "Evidence contracts and validation evidence exist.", "Evidence", "Critical", "DKL-5:1", "Evidence-oriented architecture must be preserved.", "platform.foundation.contracts.evidenceAndFindings", "present", "Loss of evidence orientation blocks Freeze."),
    gate("KV-CERT-064", "Findings remain explainable and traceable", "Finding contracts declare explainable and traceable.", "Explainability", "Critical", "DKL-5:1", "Findings must remain explainable and traceable.", "platform.foundation.contracts.evidenceAndFindings.notes", "findingsExplainable+findingsTraceable", "Opaque findings block Certification."),
    gate("KV-CERT-065", "Limitations preserve partial usability", "ValidWithLimitations outcome exists.", "Explainability", "High", "DKL-5:1", "Partial usability must be preserved.", "platform.foundation.contracts.outcomeStatuses", "includes ValidWithLimitations", "Loss of partial usability violates product philosophy."),
    gate("KV-CERT-066", "Consumer-readiness declarations exist", "Four consumer suitability states are declared.", "Consumer Readiness", "High", "DKL-5:3", "Consumer-readiness declarations must exist.", "platform.model.catalog.consumerSuitabilityStates", "4 states", "Missing consumer readiness blocks Certification."),
    gate("KV-CERT-067", "Executive-usability declarations distinguish awareness from decision commitment", "Eight executive usability capabilities are declared.", "Executive Usability", "High", "DKL-5:3", "Executive usability must distinguish awareness from decision commitment.", "platform.model.catalog.executiveUsabilityCapabilities", "includes ExecutiveAwareness and DecisionCommitment", "Missing distinction blocks Certification."),
    gate("KV-CERT-068", "Runtime organizational validation is prohibited", "Platform guarantees no runtime organizational validation.", "Runtime Prohibition", "Critical", "DKL-5:6", "Runtime organizational validation must be prohibited.", "platform.metadata.guarantees.noRuntimeOrganizationalValidation", "true", "Runtime validation violates Certification."),
    gate("KV-CERT-069", "Numeric scoring is prohibited", "Platform guarantees no numeric scoring.", "Scoring Prohibition", "Critical", "DKL-5:6", "Numeric scoring must be prohibited.", "platform.metadata.guarantees.noNumericScoring", "true", "Scoring violates Certification."),
    gate("KV-CERT-070", "Trust calculation is prohibited", "Platform guarantees no trust calculation.", "Trust-Calculation Prohibition", "Critical", "DKL-5:6", "Trust calculation must be prohibited.", "platform.metadata.guarantees.noTrustCalculation", "true", "Trust calculation violates Certification."),
    gate("KV-CERT-071", "AI confidence generation is prohibited", "Platform guarantees no AI or semantic inference.", "Runtime Prohibition", "Critical", "DKL-5:6", "AI confidence generation must be prohibited.", "platform.metadata.guarantees.noAiOrSemanticInference", "true", "AI confidence violates Certification."),
    gate("KV-CERT-072", "Broad data cleansing is prohibited", "Platform guarantees no cleansing.", "Cleansing Prohibition", "Critical", "DKL-5:6", "Broad data cleansing must be prohibited.", "platform.metadata.guarantees.noCleansing", "true", "Cleansing violates Certification."),
    gate("KV-CERT-073", "Source-system correction is prohibited", "Boundaries separate from source-system correction.", "Cleansing Prohibition", "Critical", "DKL-5:6", "Source-system correction must be prohibited.", "platform.metadata.boundaries.separateFrom", "includes Source-system correction", "Source correction violates Certification."),
    gate("KV-CERT-074", "Conflict resolution is prohibited", "Boundaries separate from conflict resolution.", "Remediation Prohibition", "Critical", "DKL-5:6", "Conflict resolution must be prohibited.", "platform.metadata.boundaries.separateFrom", "includes Conflict resolution", "Conflict resolution violates Certification."),
    gate("KV-CERT-075", "Ambiguity resolution is prohibited", "Boundaries separate from ambiguity resolution.", "Remediation Prohibition", "Critical", "DKL-5:6", "Ambiguity resolution must be prohibited.", "platform.metadata.boundaries.separateFrom", "includes Ambiguity resolution", "Ambiguity resolution violates Certification."),
    gate("KV-CERT-076", "Automatic remediation is prohibited", "Platform guarantees no remediation.", "Remediation Prohibition", "Critical", "DKL-5:6", "Automatic remediation must be prohibited.", "platform.metadata.guarantees.noRemediation", "true", "Remediation violates Certification."),
    gate("KV-CERT-077", "Persistence and repository behavior are prohibited", "Platform guarantees no persistence.", "Runtime Prohibition", "Critical", "DKL-5:6", "Persistence and repository behavior must be prohibited.", "platform.metadata.guarantees.noPersistence", "true", "Persistence violates Certification."),
    gate("KV-CERT-078", "Search and query execution are prohibited", "Boundaries separate from search and query execution.", "Runtime Prohibition", "Critical", "DKL-5:6", "Search and query execution must be prohibited.", "platform.metadata.boundaries.separateFrom", "includes Search and query execution", "Search/query violates Certification."),
    gate("KV-CERT-079", "Graph traversal is prohibited", "Platform guarantees no graph traversal.", "Runtime Prohibition", "Critical", "DKL-5:6", "Graph traversal must be prohibited.", "platform.metadata.guarantees.noGraphTraversal", "true", "Graph traversal violates Certification."),
    gate("KV-CERT-080", "Executive Engine reasoning is prohibited", "Platform guarantees no Executive Engine behavior.", "Runtime Prohibition", "Critical", "DKL-5:6", "Executive Engine reasoning must be prohibited.", "platform.metadata.guarantees.noExecutiveEngineBehavior", "true", "Engine reasoning violates Certification."),
    gate("KV-CERT-081", "Advisor, Scene, and UI behavior are prohibited", "Boundaries separate from Advisor, Scene, and UI.", "Runtime Prohibition", "Critical", "DKL-5:6", "Advisor, Scene, and UI behavior must be prohibited.", "platform.metadata.boundaries.separateFrom", "includes Advisor/Scene/UI", "Advisor/Scene/UI behavior violates Certification."),
    gate("KV-CERT-082", "Source-code scanning is prohibited", "Platform guarantees no source scanning.", "Runtime Prohibition", "Critical", "DKL-5:6", "Source-code scanning must be prohibited.", "platform.metadata.guarantees.noSourceScanning", "true", "Source scanning violates Certification."),
    gate("KV-CERT-083", "Environment-dependent behavior is prohibited", "Platform guarantees no environment-dependent behavior.", "Determinism", "Critical", "DKL-5:6", "Environment-dependent behavior must be prohibited.", "platform.metadata.guarantees.noEnvironmentDependentBehavior", "true", "Environment dependence violates Certification."),
    gate("KV-CERT-084", "Mutable registration is prohibited", "Extension policy forbids mutable runtime registration.", "Extension", "Critical", "DKL-5:6", "Mutable registration must be prohibited.", "platform.extensions.policy.mutableRuntimeRegistrationForbidden", "true", "Mutable registration violates Certification."),
    gate("KV-CERT-085", "Freeze prerequisites are satisfied", "All mandatory gates and regression checks enable ReadyForFreeze.", "Freeze Readiness", "Critical", "DKL-5:7", "Freeze prerequisites must be satisfied.", "certification.freezeReadiness", "ReadyForFreeze", "Unmet Freeze prerequisites block DKL-5:8."),
  ]);
