/**
 * DKL-7:5 — Knowledge Services Manifest Compatibility.
 *
 * Exactly twelve immutable compatibility declarations.
 * All Compatible. No runtime authorization. No future imports.
 *
 * Ownership: owned exclusively by DKL-7:5.
 */

import { KnowledgeServicesManifestChainIds } from "./knowledgeServicesManifestInventory.ts";
import type { KnowledgeServicesManifestCompatibilityDeclaration } from "./knowledgeServicesManifestTypes.ts";

const compat = (
  key: string,
  subject: string,
  direction: string,
  compatibilityType: string,
  dependencyPath: string,
  ownershipConstraint: string,
  boundaryConstraint: string,
  changePolicy: string,
  evidenceReference: string,
  order: number,
): KnowledgeServicesManifestCompatibilityDeclaration =>
  Object.freeze({
    compatibilityId: `DKL-7:5/Compatibility/${key}`,
    subject,
    direction,
    status: "Compatible" as const,
    compatibilityType,
    dependencyPath,
    ownershipConstraint,
    boundaryConstraint,
    runtimeAuthorization: "None" as const,
    changePolicy,
    evidenceReference,
    deterministicOrder: order,
  });

const ids = KnowledgeServicesManifestChainIds;

/** Exactly twelve Compatible declarations. */
export const KnowledgeServicesManifestCompatibility: readonly KnowledgeServicesManifestCompatibilityDeclaration[] =
  Object.freeze([
    compat(
      "Foundation",
      "DKL-7:1 Foundation compatibility",
      "Backward",
      "PhaseCompatibility",
      `Manifest → Validation → Model → Registry → ${ids.foundationId}`,
      "DKL-7 ownership unchanged",
      "29 prohibited surfaces preserved",
      "AdditiveOnly",
      "DKL-7:4/Validation",
      1,
    ),
    compat(
      "Registry",
      "DKL-7:2 Registry compatibility",
      "Backward",
      "PhaseCompatibility",
      `Manifest → Validation → Model → ${ids.registryId}`,
      "Registry inventories frozen by reference",
      "Read-only service boundaries preserved",
      "AdditiveOnly",
      "DKL-7:4/Validation",
      2,
    ),
    compat(
      "Model",
      "DKL-7:3 Model compatibility",
      "Backward",
      "PhaseCompatibility",
      `Manifest → Validation → ${ids.modelId}`,
      "Model inventories frozen by reference",
      "No mutation modes",
      "AdditiveOnly",
      "DKL-7:4/Validation",
      3,
    ),
    compat(
      "Validation",
      "DKL-7:4 Validation compatibility",
      "Backward",
      "PhaseCompatibility",
      `Manifest → ${ids.validationId}`,
      "Validation guarantees preserved",
      "48 rules remain Pass",
      "AdditiveOnly",
      "DKL-7:4/Validation",
      4,
    ),
    compat(
      "Dkl6PublicIndex",
      "DKL-6 Public Index compatibility",
      "Upstream",
      "UpstreamCompatibility",
      `Foundation → ${ids.dkl6PublicIndexId}`,
      "DKL-6 ownership retained",
      "No direct DKL-6 import by Manifest",
      "PublicIndexOnly",
      "DKL-7:1/Foundation.upstream",
      5,
    ),
    compat(
      "FuturePlatform",
      "Future DKL-7:6 Platform compatibility",
      "Forward",
      "FuturePhaseCompatibility",
      "Platform → Manifest",
      "Platform may consume Manifest only",
      "No Platform runtime in Manifest",
      "ForwardCompatibleDeclaration",
      "DKL-7:5/Dependency/FuturePlatformToManifest",
      6,
    ),
    compat(
      "FutureCertification",
      "Future DKL-7:7 Certification compatibility",
      "Forward",
      "FuturePhaseCompatibility",
      "Certification → Platform → Manifest",
      "No Certification ownership in Manifest",
      "No Certification runtime in Manifest",
      "ForwardCompatibleDeclaration",
      "DKL-7:5/Dependency/FutureCertificationToPlatform",
      7,
    ),
    compat(
      "FutureFreeze",
      "Future DKL-7:8 Freeze compatibility",
      "Forward",
      "FuturePhaseCompatibility",
      "Freeze → Certification → Platform → Manifest",
      "No Freeze ownership in Manifest",
      "No Freeze runtime in Manifest",
      "ForwardCompatibleDeclaration",
      "DKL-7:5/Dependency/FutureFreezeToCertification",
      8,
    ),
    compat(
      "FuturePublicIndex",
      "Future DKL-7:9 Public Index compatibility",
      "Forward",
      "FuturePhaseCompatibility",
      "Public Index → Freeze → … → Manifest",
      "No Public Index ownership in Manifest",
      "No consumer release in Manifest",
      "ForwardCompatibleDeclaration",
      "DKL-7:5/Dependency/FuturePublicIndexToFreeze",
      9,
    ),
    compat(
      "ExecutiveEngineConsumer",
      "Executive Engine consumer compatibility",
      "Consumer",
      "FutureConsumerCompatibility",
      "Executive Engine → future DKL-7 Public Index",
      "Executive Engine not owned by DKL-7",
      "No Engine reasoning in Manifest",
      "ConsumerViaFuturePublicIndexOnly",
      "DKL-7:5/Dependency/FutureExecutiveConsumersToPublicIndex",
      10,
    ),
    compat(
      "AdvisorConsumer",
      "Advisor consumer compatibility",
      "Consumer",
      "FutureConsumerCompatibility",
      "Advisor → future DKL-7 Public Index",
      "Advisor not owned by DKL-7",
      "No Advisor behavior in Manifest",
      "ConsumerViaFuturePublicIndexOnly",
      "DKL-7:5/Compatibility/ExecutiveEngineConsumer",
      11,
    ),
    compat(
      "ApprovedInternalConsumer",
      "Future approved internal consumer compatibility",
      "Consumer",
      "FutureConsumerCompatibility",
      "Approved internal consumer → future DKL-7 Public Index",
      "Consumers not owned by DKL-7",
      "No consumer runtime in Manifest",
      "ConsumerViaFuturePublicIndexOnly",
      "DKL-7:5/Compatibility/AdvisorConsumer",
      12,
    ),
  ]);
