/**
 * DKL-7:7 — Knowledge Services Certification Evidence.
 *
 * Exactly eighteen evidence records and eighteen gate results.
 * One primary evidence record and one result per gate.
 *
 * Ownership: owned exclusively by DKL-7:7.
 */

import { KnowledgeServicesCertificationGates } from "./knowledgeServicesCertificationGates.ts";
import type {
  KnowledgeServicesCertificationEvidence as CertificationEvidenceRecord,
  KnowledgeServicesCertificationGateResultRecord,
} from "./knowledgeServicesCertificationTypes.ts";

const evidence = (
  evidenceId: string,
  gateReference: string,
  evidenceType: string,
  canonicalSubjectReference: string,
  expectedArchitecturalState: string,
  certifiedArchitecturalState: string,
  sourcePhase: string,
  canonicalReferencePath: string,
  order: number,
): CertificationEvidenceRecord =>
  Object.freeze({
    evidenceId,
    gateReference,
    evidenceType,
    canonicalSubjectReference,
    expectedArchitecturalState,
    certifiedArchitecturalState,
    sourcePhase,
    canonicalReferencePath,
    result: "Pass" as const,
    immutabilityStatus: "Immutable" as const,
    deterministicOrder: order,
  });

/** Exactly eighteen immutable evidence records. */
export const KnowledgeServicesCertificationEvidence: readonly CertificationEvidenceRecord[] =
  Object.freeze([
    evidence(
      "KS-CERT-EV-001",
      "KS-CERT-ID-001",
      "CertificationIdentity",
      "DKL-7:7/KnowledgeServicesCertification",
      "Certified identity 1.0.0 Pass",
      "Certified identity 1.0.0 Pass",
      "DKL-7:7",
      "Certification.identity",
      1,
    ),
    evidence(
      "KS-CERT-EV-002",
      "KS-CERT-ID-002",
      "PlatformIdentity",
      "DKL-7:6/KnowledgeServicesPlatform",
      "PlatformComplete ReadyForCertification",
      "PlatformComplete ReadyForCertification",
      "DKL-7:6",
      "Certification.platform.identity",
      2,
    ),
    evidence(
      "KS-CERT-EV-003",
      "KS-CERT-DEP-001",
      "DependencyDeclaration",
      "knowledgeServicesPlatform.ts",
      "Platform-only direct dependency",
      "Platform-only direct dependency",
      "DKL-7:7",
      "Certification.dependencyDeclarations",
      3,
    ),
    evidence(
      "KS-CERT-EV-004",
      "KS-CERT-DEP-002",
      "CanonicalReferencePath",
      "Platform→Manifest→Validation→Model→Registry→Foundation→DKL-6",
      "Chain preserved by reference",
      "Chain preserved by reference",
      "DKL-7:6",
      "Certification.platform.manifest.validation.model.registry.foundation",
      4,
    ),
    evidence(
      "KS-CERT-EV-005",
      "KS-CERT-FND-001",
      "FoundationInventory",
      "Foundation ownership and boundaries",
      "6/24/29/8",
      "6/24/29/8",
      "DKL-7:1",
      "Certification.platform.ownership|boundaries|inventory",
      5,
    ),
    evidence(
      "KS-CERT-EV-006",
      "KS-CERT-REG-001",
      "RegistryInventory",
      "Registry services capabilities contracts",
      "12/12/11/12",
      "12/12/11/12",
      "DKL-7:2",
      "Certification.platform.services|capabilities|contracts",
      6,
    ),
    evidence(
      "KS-CERT-EV-007",
      "KS-CERT-REG-002",
      "RegistryAccessArchitecture",
      "Registry access modes",
      "12/12/10/0",
      "12/12/10/0",
      "DKL-7:2",
      "Certification.platform.inventory",
      7,
    ),
    evidence(
      "KS-CERT-EV-008",
      "KS-CERT-MOD-001",
      "ModelInventory",
      "Model inventory",
      "79",
      "79",
      "DKL-7:3",
      "Certification.platform.model",
      8,
    ),
    evidence(
      "KS-CERT-EV-009",
      "KS-CERT-MOD-002",
      "ModelGuarantees",
      "Model safety guarantees",
      "20 guarantees; immutable; transport/persistence neutral",
      "20 guarantees; immutable; transport/persistence neutral",
      "DKL-7:3",
      "Certification.platform.model.guarantees",
      9,
    ),
    evidence(
      "KS-CERT-EV-010",
      "KS-CERT-VAL-001",
      "ValidationProfile",
      "Validation inventory",
      "15/48/48 Pass",
      "15/48/48 Pass",
      "DKL-7:4",
      "Certification.platform.validation",
      10,
    ),
    evidence(
      "KS-CERT-EV-011",
      "KS-CERT-VAL-002",
      "ValidationGuarantees",
      "Validation guarantees",
      "16 guarantees; Pass; ReadyForManifest",
      "16 guarantees; Pass; ReadyForManifest",
      "DKL-7:4",
      "Certification.platform.validation",
      11,
    ),
    evidence(
      "KS-CERT-EV-012",
      "KS-CERT-MAN-001",
      "ManifestInventory",
      "Manifest inventory",
      "447 ManifestComplete",
      "447 ManifestComplete",
      "DKL-7:5",
      "Certification.platform.manifest.inventory",
      12,
    ),
    evidence(
      "KS-CERT-EV-013",
      "KS-CERT-PLT-001",
      "PlatformArchitecture",
      "Platform architecture inventory",
      "20/6/3/9/12/4",
      "20/6/3/9/12/4",
      "DKL-7:6",
      "Certification.platform.architecture|inventory",
      13,
    ),
    evidence(
      "KS-CERT-EV-014",
      "KS-CERT-PLT-002",
      "PlatformReleasePreparation",
      "Platform inventory and readiness",
      "527 PlatformComplete ReadyForCertification",
      "527 PlatformComplete ReadyForCertification",
      "DKL-7:6",
      "Certification.platform.inventory|status|readiness",
      14,
    ),
    evidence(
      "KS-CERT-EV-015",
      "KS-CERT-OWN-001",
      "OwnershipAndBoundaries",
      "Ownership and boundaries",
      "6/24/29 preserved; no expansion",
      "6/24/29 preserved; no expansion",
      "DKL-7:1",
      "Certification.platform.ownership|boundaries",
      15,
    ),
    evidence(
      "KS-CERT-EV-016",
      "KS-CERT-CMP-001",
      "CompatibilityAndConsumers",
      "Platform compatibility and consumers",
      "14 Compatible; consumer paths safe; runtime=None",
      "14 Compatible; consumer paths safe; runtime=None",
      "DKL-7:6",
      "Certification.platform.compatibility|consumers",
      16,
    ),
    evidence(
      "KS-CERT-EV-017",
      "KS-CERT-RUN-001",
      "RuntimeProhibitions",
      "Platform runtime prohibition flags",
      "runtimeBehavior=false",
      "runtimeBehavior=false",
      "DKL-7:6",
      "Certification.platform.runtimeBehavior",
      17,
    ),
    evidence(
      "KS-CERT-EV-018",
      "KS-CERT-RDY-001",
      "FreezeReadiness",
      "Certification freeze readiness",
      "ReadyForFreeze",
      "ReadyForFreeze",
      "DKL-7:7",
      "Certification.readiness",
      18,
    ),
  ]);

/** Exactly eighteen immutable gate results, one per gate. */
export const KnowledgeServicesCertificationResults: readonly KnowledgeServicesCertificationGateResultRecord[] =
  Object.freeze(
    KnowledgeServicesCertificationGates.map((gateItem, index) => {
      const primaryEvidence = KnowledgeServicesCertificationEvidence[index];
      return Object.freeze({
        resultId: `KS-CERT-RES-${String(index + 1).padStart(3, "0")}`,
        gateId: gateItem.gateId,
        gateGroup: gateItem.group,
        severity: gateItem.severity,
        evidenceReferences: Object.freeze([
          primaryEvidence?.evidenceId ?? gateItem.evidenceReferences[0]!,
        ]),
        outcome: gateItem.result,
        deterministicOrder: index + 1,
      });
    }),
  );
