/**
 * DKL-5:4 — Knowledge Validation Validation Rules.
 *
 * Immutable architectural validation rule catalog for DKL-5:1–5:3.
 * Metadata only — no live organizational knowledge validation.
 *
 * Ownership: owned exclusively by DKL-5:4.
 */

import type {
  KnowledgeValidationValidationCategory,
  KnowledgeValidationValidationRule,
} from "./knowledgeValidationValidationTypes.ts";

const OWNER = "DKL-5 Knowledge Validation Validation";

const rule = (
  id: string,
  name: string,
  category: KnowledgeValidationValidationCategory,
  sourcePhase: string,
  target: string,
  description: string,
  requirement: string,
  expectedCondition: string,
  failureMeaning: string,
): KnowledgeValidationValidationRule =>
  Object.freeze({
    id,
    name,
    description,
    category,
    sourcePhase,
    target,
    severity: "Critical" as const,
    requirement,
    expectedCondition,
    failureMeaning,
    ownership: OWNER,
    deterministic: true as const,
    runtimeDataRequired: false as const,
    mandatory: true as const,
    status: "Active" as const,
  });

/** Ordered immutable category catalog — every category must host ≥1 rule. */
export const KnowledgeValidationValidationCategories: readonly KnowledgeValidationValidationCategory[] =
  Object.freeze([
    "Foundation",
    "Registry",
    "Model",
    "Identity",
    "Target",
    "Dimension",
    "Signal",
    "Trust",
    "Outcome",
    "Severity",
    "Evidence",
    "Finding",
    "Issue",
    "Conflict",
    "Ambiguity",
    "Limitation",
    "ConsumerReadiness",
    "ExecutiveUsability",
    "Provenance",
    "Ownership",
    "Dependency",
    "Compatibility",
    "Extension",
    "Immutability",
    "CrossPhase",
    "Prohibition",
    "Readiness",
  ]);

/** Canonical immutable architectural validation rule catalog. */
export const KnowledgeValidationValidationRules: readonly KnowledgeValidationValidationRule[] =
  Object.freeze([
    rule(
      "KV-VAL-ID-001",
      "FoundationIdentityComplete",
      "Identity",
      "DKL-5:1",
      "KnowledgeValidationFoundation.identity",
      "Foundation identity must declare FoundationComplete and ReadyForRegistry.",
      "Foundation identity status and readiness must match phase contract.",
      "status=FoundationComplete; readiness=ReadyForRegistry; version+namespace present",
      "Foundation identity is incomplete or incorrectly staged.",
    ),
    rule(
      "KV-VAL-ID-002",
      "RegistryIdentityComplete",
      "Identity",
      "DKL-5:2",
      "KnowledgeValidationRegistry.identity",
      "Registry identity must declare RegistryComplete and ReadyForModel.",
      "Registry identity status and readiness must match phase contract.",
      "status=RegistryComplete; readiness=ReadyForModel; version+namespace present",
      "Registry identity is incomplete or incorrectly staged.",
    ),
    rule(
      "KV-VAL-ID-003",
      "ModelIdentityComplete",
      "Identity",
      "DKL-5:3",
      "KnowledgeValidationModel.identity",
      "Model identity must declare ModelComplete and ReadyForValidation.",
      "Model identity status and readiness must match phase contract.",
      "status=ModelComplete; readiness=ReadyForValidation; version+namespace present",
      "Model identity is incomplete or incorrectly staged.",
    ),
    rule(
      "KV-VAL-FND-001",
      "FoundationContractsComplete",
      "Foundation",
      "DKL-5:1",
      "KnowledgeValidationFoundation.contracts",
      "Foundation must expose all required contract kinds and core vocabularies.",
      "All 20 contract kinds and core contract surfaces must exist.",
      "contractKinds=20; trustDeclaration present; evidence/findings/ambiguity surfaces present",
      "Foundation contracts are incomplete.",
    ),
    rule(
      "KV-VAL-FND-002",
      "FoundationLifecycleMetadataOnly",
      "Foundation",
      "DKL-5:1",
      "KnowledgeValidationFoundation.lifecycle",
      "Lifecycle must declare eleven states with metadata-only transitions.",
      "Lifecycle stateCount must be 11 and transitions must not execute.",
      "stateCount=11; transitionExecutionForbidden=true",
      "Foundation lifecycle is incomplete or implies execution.",
    ),
    rule(
      "KV-VAL-FND-003",
      "FoundationBoundariesExcludeRuntime",
      "Foundation",
      "DKL-5:1",
      "KnowledgeValidationFoundation.boundaries",
      "Foundation boundaries must exclude cleansing, scoring, trust calc, AI, runtime validation, persistence, and Engine.",
      "Boundary exclusions must be explicit and true.",
      "dataCleansingExcluded; runtimeValidationExecutionExcluded; aiConfidenceGenerationExcluded; calculatesScores=false; calculatesTrustAutomatically=false; persistenceExcluded; engineReasoningExcluded",
      "Foundation boundaries allow forbidden runtime behavior.",
    ),
    rule(
      "KV-VAL-TGT-001",
      "FoundationTargetsDeclared",
      "Target",
      "DKL-5:1",
      "KnowledgeValidationFoundation.contracts.targetCategories",
      "Foundation must declare all nineteen validation targets.",
      "targetCategories length must equal 19.",
      "targetCategories.length=19",
      "Foundation target vocabulary is incomplete.",
    ),
    rule(
      "KV-VAL-TGT-002",
      "RegistryTargetsRegistered",
      "Target",
      "DKL-5:2",
      "KnowledgeValidationRegistry.collections.validationTargetTypes",
      "Registry must register all nineteen validation targets.",
      "validationTargetTypes length must equal 19.",
      "validationTargetCount=19",
      "Registry target registration is incomplete.",
    ),
    rule(
      "KV-VAL-DIM-001",
      "FoundationDimensionsDeclared",
      "Dimension",
      "DKL-5:1",
      "KnowledgeValidationFoundation.contracts.dimensions",
      "Foundation must declare all twenty validation dimensions.",
      "dimensions length must equal 20.",
      "dimensions.length=20",
      "Foundation dimension vocabulary is incomplete.",
    ),
    rule(
      "KV-VAL-DIM-002",
      "RegistryDimensionsRegistered",
      "Dimension",
      "DKL-5:2",
      "KnowledgeValidationRegistry.collections.validationDimensions",
      "Registry must register all twenty validation dimensions.",
      "validationDimensions length must equal 20.",
      "validationDimensionCount=20",
      "Registry dimension registration is incomplete.",
    ),
    rule(
      "KV-VAL-SIG-001",
      "FoundationSignalsDeclared",
      "Signal",
      "DKL-5:1",
      "KnowledgeValidationFoundation.contracts.qualitySignals",
      "Foundation must declare all twenty quality signals.",
      "qualitySignals length must equal 20.",
      "qualitySignals.length=20",
      "Foundation quality-signal vocabulary is incomplete.",
    ),
    rule(
      "KV-VAL-SIG-002",
      "RegistrySignalsRegistered",
      "Signal",
      "DKL-5:2",
      "KnowledgeValidationRegistry.collections.knowledgeQualitySignals",
      "Registry must register all twenty quality signals.",
      "knowledgeQualitySignals length must equal 20.",
      "qualitySignalCount=20",
      "Registry quality-signal registration is incomplete.",
    ),
    rule(
      "KV-VAL-SIG-003",
      "ModelSignalReferencesRegistry",
      "Signal",
      "DKL-5:3",
      "KnowledgeValidationModel.catalog.byKind.KnowledgeQualitySignal",
      "Quality Signal model must reference registered signals and forbid numeric scoring.",
      "Model must reference knowledgeQualitySignals and declare numericScoreCalculated=false.",
      "registryCategoryReferences includes knowledgeQualitySignals; numericScoreCalculated=false",
      "Quality Signal model is not registry-aligned or implies scoring.",
    ),
    rule(
      "KV-VAL-TRU-001",
      "FoundationTrustDeclarationExists",
      "Trust",
      "DKL-5:1",
      "KnowledgeValidationFoundation.contracts.trustDeclaration",
      "Foundation Trust Declaration contract must exist without trust calculation.",
      "trustDeclaration must exist and noTrustCalculation must be true.",
      "trustDeclaration present; noTrustCalculation=true",
      "Trust Declaration contract is missing or implies calculation.",
    ),
    rule(
      "KV-VAL-TRU-002",
      "RegistryTrustLevelsRegistered",
      "Trust",
      "DKL-5:2",
      "KnowledgeValidationRegistry.collections.trustLevels",
      "Registry must register trust levels.",
      "trustLevels collection must be non-empty and frozen.",
      "trustLevels.length>=1",
      "Registry trust levels are missing.",
    ),
    rule(
      "KV-VAL-TRU-003",
      "ModelTrustEvidenceBasedNoCalculation",
      "Trust",
      "DKL-5:3",
      "KnowledgeValidationModel.catalog.byKind.KnowledgeTrustDeclaration",
      "Trust Declaration model must be evidence-based with trustCalculated and aiConfidenceUsed false.",
      "Evidence fields present; calculation flags false.",
      "evidenceReferences present; trustCalculated=false; aiConfidenceUsed=false",
      "Trust Declaration model implies calculation or lacks evidence fields.",
    ),
    rule(
      "KV-VAL-OUT-001",
      "FoundationOutcomesDeclared",
      "Outcome",
      "DKL-5:1",
      "KnowledgeValidationFoundation.contracts.outcomes",
      "Foundation must declare all eleven outcomes.",
      "outcomes length must equal 11.",
      "outcomes.length=11",
      "Foundation outcomes are incomplete.",
    ),
    rule(
      "KV-VAL-OUT-002",
      "RegistryOutcomesRegistered",
      "Outcome",
      "DKL-5:2",
      "KnowledgeValidationRegistry.collections.validationOutcomes",
      "Registry must register all eleven outcomes.",
      "validationOutcomes length must equal 11.",
      "outcomeCount=11",
      "Registry outcomes are incomplete.",
    ),
    rule(
      "KV-VAL-SEV-001",
      "FoundationSeveritiesDeclared",
      "Severity",
      "DKL-5:1",
      "KnowledgeValidationFoundation.contracts.severities",
      "Foundation must declare all six severity levels.",
      "severities length must equal 6.",
      "severities.length=6",
      "Foundation severities are incomplete.",
    ),
    rule(
      "KV-VAL-SEV-002",
      "RegistrySeveritiesRegistered",
      "Severity",
      "DKL-5:2",
      "KnowledgeValidationRegistry.collections.validationSeverities",
      "Registry must register all six severities.",
      "validationSeverities length must equal 6.",
      "severityCount=6",
      "Registry severities are incomplete.",
    ),
    rule(
      "KV-VAL-EVD-001",
      "FoundationEvidenceContractsExist",
      "Evidence",
      "DKL-5:1",
      "KnowledgeValidationFoundation.contracts.evidenceAndFindings",
      "Foundation evidence contracts must exist with reference-not-copy notes.",
      "evidenceAndFindings surface and evidenceReferencedNotCopied must be true.",
      "validationEvidence present; evidenceReferencedNotCopied=true",
      "Foundation evidence contracts are incomplete.",
    ),
    rule(
      "KV-VAL-EVD-002",
      "RegistryEvidenceTypesRegistered",
      "Evidence",
      "DKL-5:2",
      "KnowledgeValidationRegistry.collections.evidenceTypes",
      "Registry must register evidence types.",
      "evidenceTypes collection must be non-empty.",
      "evidenceTypes.length>=1",
      "Registry evidence types are missing.",
    ),
    rule(
      "KV-VAL-EVD-003",
      "ModelEvidenceUsesReferences",
      "Evidence",
      "DKL-5:3",
      "KnowledgeValidationModel.catalog.byKind.ValidationEvidence",
      "Evidence models must exist and use references rather than payload copies.",
      "ValidationEvidence and EvidenceReference models must exist with reference fields.",
      "ValidationEvidence+EvidenceReference present; sourceReference field present",
      "Evidence models are missing or imply payload copying.",
    ),
    rule(
      "KV-VAL-FNDG-001",
      "FoundationFindingContractExists",
      "Finding",
      "DKL-5:1",
      "KnowledgeValidationFoundation.contracts.evidenceAndFindings.validationFinding",
      "Foundation finding contract must be explainable and traceable.",
      "validationFinding fields and findingsExplainable/findingsTraceable must hold.",
      "validationFinding present; findingsExplainable=true; findingsTraceable=true",
      "Foundation finding contract is incomplete.",
    ),
    rule(
      "KV-VAL-FNDG-002",
      "RegistryFindingsRegistered",
      "Finding",
      "DKL-5:2",
      "KnowledgeValidationRegistry.collections.findingCategories",
      "Registry must register finding categories.",
      "findingCategories must be non-empty.",
      "findingCategories.length>=1",
      "Registry finding categories are missing.",
    ),
    rule(
      "KV-VAL-FNDG-003",
      "ModelFindingNoRemediation",
      "Finding",
      "DKL-5:3",
      "KnowledgeValidationModel.catalog.byKind.ValidationFinding",
      "Finding model must be explainable with remediation absent.",
      "explanation field present; runtimeRemediationImplemented=false.",
      "explanation present; runtimeRemediationImplemented=false",
      "Finding model lacks explainability or implies remediation.",
    ),
    rule(
      "KV-VAL-ISS-001",
      "RegistryIssuesRegistered",
      "Issue",
      "DKL-5:2",
      "KnowledgeValidationRegistry.collections.issueCategories",
      "Registry must register issue categories.",
      "issueCategories must be non-empty.",
      "issueCategories.length>=1",
      "Registry issue categories are missing.",
    ),
    rule(
      "KV-VAL-ISS-002",
      "ModelIssueNoWorkflow",
      "Issue",
      "DKL-5:3",
      "KnowledgeValidationModel.catalog.byKind.ValidationIssue",
      "Issue model must exist without workflow execution fields.",
      "ValidationIssue model present; no executable workflow fields.",
      "ValidationIssue present; all fields executableBehaviorImplied=false",
      "Issue model is missing or implies workflow execution.",
    ),
    rule(
      "KV-VAL-CNF-001",
      "RegistryConflictsRegistered",
      "Conflict",
      "DKL-5:2",
      "KnowledgeValidationRegistry.collections.conflictTypes",
      "Registry must register conflict types.",
      "conflictTypes must be non-empty.",
      "conflictTypes.length>=1",
      "Registry conflict types are missing.",
    ),
    rule(
      "KV-VAL-CNF-002",
      "ModelConflictNoResolution",
      "Conflict",
      "DKL-5:3",
      "KnowledgeValidationModel.catalog.byKind.ValidationConflict",
      "Conflict model must declare resolutionImplemented=false.",
      "resolutionImplemented field kind must be false.",
      "resolutionImplemented=false",
      "Conflict model implies resolution behavior.",
    ),
    rule(
      "KV-VAL-AMB-001",
      "FoundationAmbiguityContractExists",
      "Ambiguity",
      "DKL-5:1",
      "KnowledgeValidationFoundation.contracts.ambiguityAndConflict",
      "Foundation ambiguity/conflict contracts must exist.",
      "ambiguityAndConflict surface must be present.",
      "ambiguityAndConflict present",
      "Foundation ambiguity/conflict contracts are missing.",
    ),
    rule(
      "KV-VAL-AMB-002",
      "RegistryAmbiguityRegistered",
      "Ambiguity",
      "DKL-5:2",
      "KnowledgeValidationRegistry.collections.ambiguityTypes",
      "Registry must register ambiguity types.",
      "ambiguityTypes must be non-empty.",
      "ambiguityTypes.length>=1",
      "Registry ambiguity types are missing.",
    ),
    rule(
      "KV-VAL-AMB-003",
      "ModelAmbiguityNoResolution",
      "Ambiguity",
      "DKL-5:3",
      "KnowledgeValidationModel.catalog.byKind.ValidationAmbiguity",
      "Ambiguity model must declare resolutionImplemented=false.",
      "resolutionImplemented field kind must be false.",
      "resolutionImplemented=false",
      "Ambiguity model implies resolution behavior.",
    ),
    rule(
      "KV-VAL-LIM-001",
      "ModelLimitationPreservesPartialUsability",
      "Limitation",
      "DKL-5:3",
      "KnowledgeValidationModel.catalog.byKind.ValidationLimitation",
      "Limitation model must preserve partial usability.",
      "partialUsabilityPreserved field kind must be true.",
      "partialUsabilityPreserved=true",
      "Limitation model does not preserve partial usability.",
    ),
    rule(
      "KV-VAL-CON-001",
      "ModelConsumerSuitabilityExists",
      "ConsumerReadiness",
      "DKL-5:3",
      "KnowledgeValidationModel.catalog.byKind.ValidationConsumerSuitability",
      "Consumer Suitability model and four readiness states must exist.",
      "Model and ReadyForConsumer/ReadyWithLimitations/Restricted/NotReadyForConsumer states present.",
      "ValidationConsumerSuitability present; four suitability states declared",
      "Consumer Suitability model or states are incomplete.",
    ),
    rule(
      "KV-VAL-EXE-001",
      "ModelExecutiveUsabilityDistinguishesAwareness",
      "ExecutiveUsability",
      "DKL-5:3",
      "KnowledgeValidationModel.catalog.byKind.ValidationExecutiveUsability",
      "Executive Usability must distinguish awareness from decision commitment.",
      "executiveAwareness and decisionCommitment fields plus awarenessVsDecisionDistinction=true.",
      "executiveAwareness+decisionCommitment present; awarenessVsDecisionDistinction=true; executiveEngineReasoningForbidden=true",
      "Executive Usability does not distinguish awareness from high-impact decisions.",
    ),
    rule(
      "KV-VAL-PRV-001",
      "ModelProvenanceForbidsTimestamps",
      "Provenance",
      "DKL-5:3",
      "KnowledgeValidationModel.catalog.byKind.ValidationProvenance",
      "Provenance model must prohibit generated runtime timestamps.",
      "generatedTimestampProhibited field kind must be true.",
      "generatedTimestampProhibited=true",
      "Provenance model allows runtime timestamps.",
    ),
    rule(
      "KV-VAL-OWN-001",
      "FoundationOwnershipExplicit",
      "Ownership",
      "DKL-5:1",
      "KnowledgeValidationFoundation.ownership",
      "Foundation ownership owns and doesNotOwn must be explicit and non-overlapping.",
      "owns and doesNotOwn non-empty with empty intersection.",
      "owns>=1; doesNotOwn>=1; intersection empty",
      "Foundation ownership is incomplete or conflicting.",
    ),
    rule(
      "KV-VAL-OWN-002",
      "RegistryOwnershipExplicit",
      "Ownership",
      "DKL-5:2",
      "KnowledgeValidationRegistry.ownership",
      "Registry ownership must be explicit with no duplicate architectural ownership.",
      "owns/doesNotOwn present; noDuplicateArchitecturalOwnership=true.",
      "owns>=1; doesNotOwn>=1; noDuplicateArchitecturalOwnership=true",
      "Registry ownership is incomplete or duplicated.",
    ),
    rule(
      "KV-VAL-OWN-003",
      "ModelOwnershipExplicit",
      "Ownership",
      "DKL-5:3",
      "KnowledgeValidationModel.ownership",
      "Model ownership must be explicit and exclude Engine/UI ownership.",
      "owns and doesNotOwn present; doesNotOwn includes Executive reasoning and UI.",
      "owns>=1; doesNotOwn includes Executive reasoning and UI",
      "Model ownership is incomplete or claims Engine/UI ownership.",
    ),
    rule(
      "KV-VAL-DEP-001",
      "FoundationDependsOnDkl4PublicIndexOnly",
      "Dependency",
      "DKL-5:1",
      "KnowledgeValidationFoundation.dependencies",
      "Foundation must depend only on knowledgeModelingPublicIndex.ts.",
      "allowed dependency module must be the DKL-4 public index.",
      "allowed[0].module=knowledgeModelingPublicIndex.ts; publicEntryPointOnly=true",
      "Foundation dependency violates approved entry-point rule.",
    ),
    rule(
      "KV-VAL-DEP-002",
      "RegistryDependsOnFoundationOnly",
      "Dependency",
      "DKL-5:2",
      "KnowledgeValidationRegistry.dependencies",
      "Registry must depend only on knowledgeValidationFoundation.ts.",
      "approvedFoundationDependency module must be foundation entry.",
      "module=knowledgeValidationFoundation.ts; noDirectDkl4Dependency=true; noFutureDkl5Dependency=true",
      "Registry dependency violates approved entry-point rule.",
    ),
    rule(
      "KV-VAL-DEP-003",
      "ModelDependsOnFoundationAndRegistryOnly",
      "Dependency",
      "DKL-5:3",
      "KnowledgeValidationModel.dependencies",
      "Model must depend only on Foundation and Registry public entries.",
      "approvedDependencyCount=2; noDirectDkl4Dependency; noFutureDkl5Dependency.",
      "approvedDependencyCount=2; modules=foundation+registry; noDirectDkl4Dependency=true",
      "Model dependency violates approved entry-point rule.",
    ),
    rule(
      "KV-VAL-CMP-001",
      "FoundationCompatibilityPoliciesExist",
      "Compatibility",
      "DKL-5:1",
      "KnowledgeValidationFoundation.contracts.compatibilityPolicies",
      "Foundation must declare compatibility policies.",
      "compatibilityPolicies length must be >=1.",
      "compatibilityPolicies.length>=1",
      "Foundation compatibility policies are missing.",
    ),
    rule(
      "KV-VAL-CMP-002",
      "RegistryCompatibilityPoliciesRegistered",
      "Compatibility",
      "DKL-5:2",
      "KnowledgeValidationRegistry.collections.compatibilityPolicies",
      "Registry must register compatibility policies.",
      "compatibilityPolicies collection must be non-empty.",
      "compatibilityPolicies.length>=1",
      "Registry compatibility policies are missing.",
    ),
    rule(
      "KV-VAL-EXT-001",
      "FoundationExtensionPoliciesExist",
      "Extension",
      "DKL-5:1",
      "KnowledgeValidationFoundation.contracts.extensionPolicies",
      "Foundation must declare extension policies.",
      "extensionPolicies length must be >=1.",
      "extensionPolicies.length>=1",
      "Foundation extension policies are missing.",
    ),
    rule(
      "KV-VAL-EXT-002",
      "RegistryExtensionPoliciesRegistered",
      "Extension",
      "DKL-5:2",
      "KnowledgeValidationRegistry.collections.extensionPolicies",
      "Registry must register extension policies.",
      "extensionPolicies collection must be non-empty.",
      "extensionPolicies.length>=1",
      "Registry extension policies are missing.",
    ),
    rule(
      "KV-VAL-REG-001",
      "RegistryCollectionsComplete",
      "Registry",
      "DKL-5:2",
      "KnowledgeValidationRegistry.collections",
      "Registry must expose exactly twenty-four collections with deterministic totals.",
      "registryCategoryCount=24 and totalEntryCount deterministic.",
      "registryCategoryCount=24; totalEntryCount=266; collections frozen",
      "Registry collections are incomplete or non-deterministic.",
    ),
    rule(
      "KV-VAL-REG-002",
      "RegistryUniqueIdsAndNames",
      "Registry",
      "DKL-5:2",
      "KnowledgeValidationRegistry.collections",
      "Registry IDs must be unique across collections; names unique within each collection.",
      "All IDs unique globally; names unique per collection; ordering deterministic.",
      "unique IDs; unique names within collection; deterministicOrderingGuaranteed=true",
      "Registry identifiers or names collide or ordering is non-deterministic.",
    ),
    rule(
      "KV-VAL-REG-003",
      "RegistryStatusesAndLifecycleRegistered",
      "Registry",
      "DKL-5:2",
      "KnowledgeValidationRegistry.collections",
      "Registry must register statuses and lifecycle states.",
      "validationStatuses length=11; validationLifecycleStates non-empty.",
      "validationStatuses=11; validationLifecycleStates>=1",
      "Registry statuses or lifecycle registration is incomplete.",
    ),
    rule(
      "KV-VAL-REG-004",
      "RegistryForbidsRuntimeValidatorsAndRemediation",
      "Registry",
      "DKL-5:2",
      "KnowledgeValidationRegistry.readiness",
      "Registry readiness must forbid runtime validators, scoring, trust calc, mutation, and remediation.",
      "RuntimeValidationForbidden, Score/TrustCalculationForbidden, RemediationForbidden, mutableRegistrationForbidden.",
      "RuntimeValidationForbidden; ScoreCalculationForbidden; TrustCalculationForbidden; RemediationForbidden; mutableRegistrationForbidden",
      "Registry readiness allows forbidden runtime or mutation behavior.",
    ),
    rule(
      "KV-VAL-MDL-001",
      "ModelCatalogComplete",
      "Model",
      "DKL-5:3",
      "KnowledgeValidationModel.catalog",
      "Model catalog must contain exactly thirty unique ordered canonical models.",
      "modelCount=30; unique IDs; unique names; deterministic ordering.",
      "modelCount=30; unique modelIds; unique modelNames; deterministic order",
      "Model catalog is incomplete or non-deterministic.",
    ),
    rule(
      "KV-VAL-MDL-002",
      "ModelAggregateComplete",
      "Model",
      "DKL-5:3",
      "KnowledgeValidationModel.catalog.byKind.KnowledgeValidation",
      "Knowledge Validation aggregate must contain the complete required field catalog.",
      "Required aggregate fields including target, ruleSet, evidence, trust, result, summary must exist.",
      "complete aggregate field catalog present",
      "Knowledge Validation aggregate field catalog is incomplete.",
    ),
    rule(
      "KV-VAL-MDL-003",
      "ModelTargetRuleCriterionContracts",
      "Model",
      "DKL-5:3",
      "KnowledgeValidationModel.catalog.byKind",
      "Target/Rule/Criterion models must reference registry categories; rule execution absent; comparison descriptive only.",
      "Target/Rule/Criterion models present with required registry refs and executionImplemented=false.",
      "validationTargetTypes/validationRuleCategories/validationDimensions referenced; executionImplemented=false; comparisonModeDeclaration present",
      "Target, Rule, or Criterion model contracts are incomplete.",
    ),
    rule(
      "KV-VAL-MDL-004",
      "ModelResultSummaryAndRelationships",
      "Model",
      "DKL-5:3",
      "KnowledgeValidationModel.catalog+relationships",
      "Result/Summary models and all fourteen structural relationships must exist without graph traversal or factories.",
      "Result/Summary present; 14 relationships; graphTraversalForbidden; factoryForbidden on models.",
      "Result+Summary present; declarationCount=14; graphTraversalForbidden=true; factoryForbidden=true",
      "Result/Summary models or relationships are incomplete.",
    ),
    rule(
      "KV-VAL-MDL-005",
      "ModelResultAllowsImperfectUsability",
      "Model",
      "DKL-5:3",
      "KnowledgeValidationModel.catalog.byKind.ValidationResult",
      "Result model must not classify all imperfect knowledge as unusable; summary counts are declarations only.",
      "nonPerfectKnowledgeAutomaticallyUnusable=false; countsCalculatedInPhase=false.",
      "nonPerfectKnowledgeAutomaticallyUnusable=false; countsCalculatedInPhase=false",
      "Result/Summary imply perfect-only usability or calculated counts.",
    ),
    rule(
      "KV-VAL-XPH-001",
      "CrossPhaseIdentityAndNamespaceCoherence",
      "CrossPhase",
      "DKL-5:1|DKL-5:2|DKL-5:3",
      "phase identities",
      "Phase IDs must be unique; versions explicit; namespaces follow DKL-5 conventions.",
      "Unique phase IDs; version 1.0.0; namespaces under nexora.dkl.knowledge-validation.",
      "unique phase IDs; versions explicit; namespaces coherent",
      "Cross-phase identity or namespace coherence failed.",
    ),
    rule(
      "KV-VAL-XPH-002",
      "CrossPhaseLifecycleAndReadinessProgression",
      "CrossPhase",
      "DKL-5:1|DKL-5:2|DKL-5:3",
      "lifecycle+readiness progression",
      "Lifecycle and readiness must progress FoundationComplete→RegistryComplete→ModelComplete and ReadyForRegistry→ReadyForModel→ReadyForValidation.",
      "Status and readiness progression must be coherent.",
      "FoundationComplete→RegistryComplete→ModelComplete; ReadyForRegistry→ReadyForModel→ReadyForValidation",
      "Lifecycle or readiness progression is incoherent.",
    ),
    rule(
      "KV-VAL-XPH-003",
      "CrossPhaseVocabularyCountsAlign",
      "CrossPhase",
      "DKL-5:1|DKL-5:2|DKL-5:3",
      "Foundation↔Registry↔Model vocabulary",
      "Foundation and Registry vocabulary counts must align; Model references must map to Registry vocabularies.",
      "Target/dimension/signal/outcome/severity counts match; model category refs map to registry collections.",
      "counts align; model registryCategoryReferences map to registry collections",
      "Cross-phase vocabulary alignment failed.",
    ),
    rule(
      "KV-VAL-XPH-004",
      "CrossPhaseNoOwnershipDuplicationOfDkl4OrEngine",
      "CrossPhase",
      "DKL-5:1|DKL-5:2|DKL-5:3",
      "ownership boundaries",
      "No phase may duplicate DKL-4 Knowledge Modeling or Executive Engine ownership.",
      "Guarantees/doesNotOwn must exclude Knowledge Modeling creation and Engine reasoning ownership.",
      "noDuplicateKnowledgeModelingOwnership; doesNotOwn includes Executive reasoning / Engine",
      "Phase ownership duplicates DKL-4 or Engine ownership.",
    ),
    rule(
      "KV-VAL-PRH-001",
      "ArchitecturalProhibitionsDeclared",
      "Prohibition",
      "DKL-5:1|DKL-5:2|DKL-5:3",
      "exported guarantees/boundaries/readiness",
      "Exported architecture must declare prohibitions for ingestion, cleansing, scoring, trust calc, AI, resolution, remediation, persistence, graph, Engine, UI, and mutable plugins.",
      "Foundation/Registry/Model exported metadata must forbid the prohibited behaviors.",
      "prohibitions declared across boundaries, guarantees, readiness, and doesNotOwn",
      "Architectural prohibitions are not declared on exported surfaces.",
    ),
    rule(
      "KV-VAL-IMM-001",
      "PhasesImmutableAndMetadataOnly",
      "Immutability",
      "DKL-5:1|DKL-5:2|DKL-5:3",
      "Foundation+Registry+Model aggregates",
      "Foundation, Registry, and Model must declare metadata-only and immutable with frozen catalogs.",
      "metadataOnly=true; immutable=true across phases; model fields readonly.",
      "metadataOnly=true; immutable=true; fields readonly",
      "Phases are not metadata-only or immutable.",
    ),
    rule(
      "KV-VAL-RDY-001",
      "ArchitectureReadyForManifest",
      "Readiness",
      "DKL-5:1|DKL-5:2|DKL-5:3",
      "phase readiness chain",
      "Prior phases must complete the readiness chain culminating in Model ReadyForValidation so Manifest can proceed.",
      "Foundation ReadyForRegistry; Registry ReadyForModel; Model ReadyForValidation.",
      "ReadyForRegistry + ReadyForModel + ReadyForValidation all true",
      "Architecture is not ready for Manifest.",
    ),
  ]);
