/**
 * DKL-4:2 — Knowledge Modeling Business Object Registry.
 *
 * Stable architectural categories for organizational Business Objects.
 * No business behavior, runtime instances, or persistence schemas.
 *
 * Ownership: owned exclusively by DKL-4:2.
 */

import type { BusinessObjectRegistryEntry } from "./knowledgeModelingRegistryTypes.ts";

const OWNER = "DKL-4 Knowledge Modeling Registry";
const PHASE = "DKL-4:2";

export const KnowledgeModelingBusinessObjectRegistry: readonly BusinessObjectRegistryEntry[] =
  Object.freeze([
    Object.freeze({
      id: "km-bo-customer",
      name: "Customer",
      namespace: "nexora.dkl.knowledge-modeling.registry.business-object.customer",
      description: "Architectural category for a customer business object.",
      category: "BusinessObjectType",
      organizationalCategory: "Customer",
      owner: OWNER,
      sourcePhase: PHASE,
      lifecycleStatus: "Registered",
      stabilityStatus: "Stable",
      compatibilityStatus: "Compatible",
      extensionStatus: "AdditiveAllowed",
      publicVisibility: "Public",
      tags: Object.freeze(["business-object", "commercial", "party"]),
      behaviorImplemented: false,
      runtimeInstanceCreated: false,
      persistenceSchemaAssumed: false,
    }),
    Object.freeze({
      id: "km-bo-employee",
      name: "Employee",
      namespace: "nexora.dkl.knowledge-modeling.registry.business-object.employee",
      description: "Architectural category for an employee business object.",
      category: "BusinessObjectType",
      organizationalCategory: "Employee",
      owner: OWNER,
      sourcePhase: PHASE,
      lifecycleStatus: "Registered",
      stabilityStatus: "Stable",
      compatibilityStatus: "Compatible",
      extensionStatus: "AdditiveAllowed",
      publicVisibility: "Public",
      tags: Object.freeze(["business-object", "people", "workforce"]),
      behaviorImplemented: false,
      runtimeInstanceCreated: false,
      persistenceSchemaAssumed: false,
    }),
    Object.freeze({
      id: "km-bo-product",
      name: "Product",
      namespace: "nexora.dkl.knowledge-modeling.registry.business-object.product",
      description: "Architectural category for a product business object.",
      category: "BusinessObjectType",
      organizationalCategory: "Product",
      owner: OWNER,
      sourcePhase: PHASE,
      lifecycleStatus: "Registered",
      stabilityStatus: "Stable",
      compatibilityStatus: "Compatible",
      extensionStatus: "AdditiveAllowed",
      publicVisibility: "Public",
      tags: Object.freeze(["business-object", "offering"]),
      behaviorImplemented: false,
      runtimeInstanceCreated: false,
      persistenceSchemaAssumed: false,
    }),
    Object.freeze({
      id: "km-bo-service",
      name: "Service",
      namespace: "nexora.dkl.knowledge-modeling.registry.business-object.service",
      description: "Architectural category for a service business object.",
      category: "BusinessObjectType",
      organizationalCategory: "Service",
      owner: OWNER,
      sourcePhase: PHASE,
      lifecycleStatus: "Registered",
      stabilityStatus: "Stable",
      compatibilityStatus: "Compatible",
      extensionStatus: "AdditiveAllowed",
      publicVisibility: "Public",
      tags: Object.freeze(["business-object", "offering"]),
      behaviorImplemented: false,
      runtimeInstanceCreated: false,
      persistenceSchemaAssumed: false,
    }),
    Object.freeze({
      id: "km-bo-supplier",
      name: "Supplier",
      namespace: "nexora.dkl.knowledge-modeling.registry.business-object.supplier",
      description: "Architectural category for a supplier business object.",
      category: "BusinessObjectType",
      organizationalCategory: "Supplier",
      owner: OWNER,
      sourcePhase: PHASE,
      lifecycleStatus: "Registered",
      stabilityStatus: "Stable",
      compatibilityStatus: "Compatible",
      extensionStatus: "AdditiveAllowed",
      publicVisibility: "Public",
      tags: Object.freeze(["business-object", "commercial", "party"]),
      behaviorImplemented: false,
      runtimeInstanceCreated: false,
      persistenceSchemaAssumed: false,
    }),
    Object.freeze({
      id: "km-bo-department",
      name: "Department",
      namespace: "nexora.dkl.knowledge-modeling.registry.business-object.department",
      description: "Architectural category for a department business object.",
      category: "BusinessObjectType",
      organizationalCategory: "Department",
      owner: OWNER,
      sourcePhase: PHASE,
      lifecycleStatus: "Registered",
      stabilityStatus: "Stable",
      compatibilityStatus: "Compatible",
      extensionStatus: "AdditiveAllowed",
      publicVisibility: "Public",
      tags: Object.freeze(["business-object", "organization"]),
      behaviorImplemented: false,
      runtimeInstanceCreated: false,
      persistenceSchemaAssumed: false,
    }),
    Object.freeze({
      id: "km-bo-team",
      name: "Team",
      namespace: "nexora.dkl.knowledge-modeling.registry.business-object.team",
      description: "Architectural category for a team business object.",
      category: "BusinessObjectType",
      organizationalCategory: "Team",
      owner: OWNER,
      sourcePhase: PHASE,
      lifecycleStatus: "Registered",
      stabilityStatus: "Stable",
      compatibilityStatus: "Compatible",
      extensionStatus: "AdditiveAllowed",
      publicVisibility: "Public",
      tags: Object.freeze(["business-object", "organization"]),
      behaviorImplemented: false,
      runtimeInstanceCreated: false,
      persistenceSchemaAssumed: false,
    }),
    Object.freeze({
      id: "km-bo-project",
      name: "Project",
      namespace: "nexora.dkl.knowledge-modeling.registry.business-object.project",
      description: "Architectural category for a project business object.",
      category: "BusinessObjectType",
      organizationalCategory: "Project",
      owner: OWNER,
      sourcePhase: PHASE,
      lifecycleStatus: "Registered",
      stabilityStatus: "Stable",
      compatibilityStatus: "Compatible",
      extensionStatus: "AdditiveAllowed",
      publicVisibility: "Public",
      tags: Object.freeze(["business-object", "work"]),
      behaviorImplemented: false,
      runtimeInstanceCreated: false,
      persistenceSchemaAssumed: false,
    }),
    Object.freeze({
      id: "km-bo-program",
      name: "Program",
      namespace: "nexora.dkl.knowledge-modeling.registry.business-object.program",
      description: "Architectural category for a program business object.",
      category: "BusinessObjectType",
      organizationalCategory: "Program",
      owner: OWNER,
      sourcePhase: PHASE,
      lifecycleStatus: "Registered",
      stabilityStatus: "Stable",
      compatibilityStatus: "Compatible",
      extensionStatus: "AdditiveAllowed",
      publicVisibility: "Public",
      tags: Object.freeze(["business-object", "work"]),
      behaviorImplemented: false,
      runtimeInstanceCreated: false,
      persistenceSchemaAssumed: false,
    }),
    Object.freeze({
      id: "km-bo-contract",
      name: "Contract",
      namespace: "nexora.dkl.knowledge-modeling.registry.business-object.contract",
      description: "Architectural category for a contract business object.",
      category: "BusinessObjectType",
      organizationalCategory: "Contract",
      owner: OWNER,
      sourcePhase: PHASE,
      lifecycleStatus: "Registered",
      stabilityStatus: "Stable",
      compatibilityStatus: "Compatible",
      extensionStatus: "AdditiveAllowed",
      publicVisibility: "Public",
      tags: Object.freeze(["business-object", "commercial", "document"]),
      behaviorImplemented: false,
      runtimeInstanceCreated: false,
      persistenceSchemaAssumed: false,
    }),
    Object.freeze({
      id: "km-bo-order",
      name: "Order",
      namespace: "nexora.dkl.knowledge-modeling.registry.business-object.order",
      description: "Architectural category for an order business object.",
      category: "BusinessObjectType",
      organizationalCategory: "Order",
      owner: OWNER,
      sourcePhase: PHASE,
      lifecycleStatus: "Registered",
      stabilityStatus: "Stable",
      compatibilityStatus: "Compatible",
      extensionStatus: "AdditiveAllowed",
      publicVisibility: "Public",
      tags: Object.freeze(["business-object", "commercial", "transaction"]),
      behaviorImplemented: false,
      runtimeInstanceCreated: false,
      persistenceSchemaAssumed: false,
    }),
    Object.freeze({
      id: "km-bo-invoice",
      name: "Invoice",
      namespace: "nexora.dkl.knowledge-modeling.registry.business-object.invoice",
      description: "Architectural category for an invoice business object.",
      category: "BusinessObjectType",
      organizationalCategory: "Invoice",
      owner: OWNER,
      sourcePhase: PHASE,
      lifecycleStatus: "Registered",
      stabilityStatus: "Stable",
      compatibilityStatus: "Compatible",
      extensionStatus: "AdditiveAllowed",
      publicVisibility: "Public",
      tags: Object.freeze(["business-object", "finance", "transaction"]),
      behaviorImplemented: false,
      runtimeInstanceCreated: false,
      persistenceSchemaAssumed: false,
    }),
    Object.freeze({
      id: "km-bo-payment",
      name: "Payment",
      namespace: "nexora.dkl.knowledge-modeling.registry.business-object.payment",
      description: "Architectural category for a payment business object.",
      category: "BusinessObjectType",
      organizationalCategory: "Payment",
      owner: OWNER,
      sourcePhase: PHASE,
      lifecycleStatus: "Registered",
      stabilityStatus: "Stable",
      compatibilityStatus: "Compatible",
      extensionStatus: "AdditiveAllowed",
      publicVisibility: "Public",
      tags: Object.freeze(["business-object", "finance", "transaction"]),
      behaviorImplemented: false,
      runtimeInstanceCreated: false,
      persistenceSchemaAssumed: false,
    }),
    Object.freeze({
      id: "km-bo-asset",
      name: "Asset",
      namespace: "nexora.dkl.knowledge-modeling.registry.business-object.asset",
      description: "Architectural category for an asset business object.",
      category: "BusinessObjectType",
      organizationalCategory: "Asset",
      owner: OWNER,
      sourcePhase: PHASE,
      lifecycleStatus: "Registered",
      stabilityStatus: "Stable",
      compatibilityStatus: "Compatible",
      extensionStatus: "AdditiveAllowed",
      publicVisibility: "Public",
      tags: Object.freeze(["business-object", "resource"]),
      behaviorImplemented: false,
      runtimeInstanceCreated: false,
      persistenceSchemaAssumed: false,
    }),
    Object.freeze({
      id: "km-bo-facility",
      name: "Facility",
      namespace: "nexora.dkl.knowledge-modeling.registry.business-object.facility",
      description: "Architectural category for a facility business object.",
      category: "BusinessObjectType",
      organizationalCategory: "Facility",
      owner: OWNER,
      sourcePhase: PHASE,
      lifecycleStatus: "Registered",
      stabilityStatus: "Stable",
      compatibilityStatus: "Compatible",
      extensionStatus: "AdditiveAllowed",
      publicVisibility: "Public",
      tags: Object.freeze(["business-object", "resource", "location"]),
      behaviorImplemented: false,
      runtimeInstanceCreated: false,
      persistenceSchemaAssumed: false,
    }),
    Object.freeze({
      id: "km-bo-process",
      name: "Process",
      namespace: "nexora.dkl.knowledge-modeling.registry.business-object.process",
      description: "Architectural category for a process business object.",
      category: "BusinessObjectType",
      organizationalCategory: "Process",
      owner: OWNER,
      sourcePhase: PHASE,
      lifecycleStatus: "Registered",
      stabilityStatus: "Stable",
      compatibilityStatus: "Compatible",
      extensionStatus: "AdditiveAllowed",
      publicVisibility: "Public",
      tags: Object.freeze(["business-object", "operation"]),
      behaviorImplemented: false,
      runtimeInstanceCreated: false,
      persistenceSchemaAssumed: false,
    }),
    Object.freeze({
      id: "km-bo-task",
      name: "Task",
      namespace: "nexora.dkl.knowledge-modeling.registry.business-object.task",
      description: "Architectural category for a task business object.",
      category: "BusinessObjectType",
      organizationalCategory: "Task",
      owner: OWNER,
      sourcePhase: PHASE,
      lifecycleStatus: "Registered",
      stabilityStatus: "Stable",
      compatibilityStatus: "Compatible",
      extensionStatus: "AdditiveAllowed",
      publicVisibility: "Public",
      tags: Object.freeze(["business-object", "work"]),
      behaviorImplemented: false,
      runtimeInstanceCreated: false,
      persistenceSchemaAssumed: false,
    }),
    Object.freeze({
      id: "km-bo-goal",
      name: "Goal",
      namespace: "nexora.dkl.knowledge-modeling.registry.business-object.goal",
      description: "Architectural category for a goal business object.",
      category: "BusinessObjectType",
      organizationalCategory: "Goal",
      owner: OWNER,
      sourcePhase: PHASE,
      lifecycleStatus: "Registered",
      stabilityStatus: "Stable",
      compatibilityStatus: "Compatible",
      extensionStatus: "AdditiveAllowed",
      publicVisibility: "Public",
      tags: Object.freeze(["business-object", "strategy"]),
      behaviorImplemented: false,
      runtimeInstanceCreated: false,
      persistenceSchemaAssumed: false,
    }),
    Object.freeze({
      id: "km-bo-kpi",
      name: "KPI",
      namespace: "nexora.dkl.knowledge-modeling.registry.business-object.kpi",
      description: "Architectural category for a KPI business object.",
      category: "BusinessObjectType",
      organizationalCategory: "KPI",
      owner: OWNER,
      sourcePhase: PHASE,
      lifecycleStatus: "Registered",
      stabilityStatus: "Stable",
      compatibilityStatus: "Compatible",
      extensionStatus: "AdditiveAllowed",
      publicVisibility: "Public",
      tags: Object.freeze(["business-object", "metric", "strategy"]),
      behaviorImplemented: false,
      runtimeInstanceCreated: false,
      persistenceSchemaAssumed: false,
    }),
    Object.freeze({
      id: "km-bo-risk",
      name: "Risk",
      namespace: "nexora.dkl.knowledge-modeling.registry.business-object.risk",
      description: "Architectural category for a risk business object.",
      category: "BusinessObjectType",
      organizationalCategory: "Risk",
      owner: OWNER,
      sourcePhase: PHASE,
      lifecycleStatus: "Registered",
      stabilityStatus: "Stable",
      compatibilityStatus: "Compatible",
      extensionStatus: "AdditiveAllowed",
      publicVisibility: "Public",
      tags: Object.freeze(["business-object", "risk"]),
      behaviorImplemented: false,
      runtimeInstanceCreated: false,
      persistenceSchemaAssumed: false,
    }),
    Object.freeze({
      id: "km-bo-issue",
      name: "Issue",
      namespace: "nexora.dkl.knowledge-modeling.registry.business-object.issue",
      description: "Architectural category for an issue business object.",
      category: "BusinessObjectType",
      organizationalCategory: "Issue",
      owner: OWNER,
      sourcePhase: PHASE,
      lifecycleStatus: "Registered",
      stabilityStatus: "Stable",
      compatibilityStatus: "Compatible",
      extensionStatus: "AdditiveAllowed",
      publicVisibility: "Public",
      tags: Object.freeze(["business-object", "risk", "work"]),
      behaviorImplemented: false,
      runtimeInstanceCreated: false,
      persistenceSchemaAssumed: false,
    }),
    Object.freeze({
      id: "km-bo-opportunity",
      name: "Opportunity",
      namespace: "nexora.dkl.knowledge-modeling.registry.business-object.opportunity",
      description: "Architectural category for an opportunity business object.",
      category: "BusinessObjectType",
      organizationalCategory: "Opportunity",
      owner: OWNER,
      sourcePhase: PHASE,
      lifecycleStatus: "Registered",
      stabilityStatus: "Stable",
      compatibilityStatus: "Compatible",
      extensionStatus: "AdditiveAllowed",
      publicVisibility: "Public",
      tags: Object.freeze(["business-object", "strategy"]),
      behaviorImplemented: false,
      runtimeInstanceCreated: false,
      persistenceSchemaAssumed: false,
    }),
    Object.freeze({
      id: "km-bo-decision",
      name: "Decision",
      namespace: "nexora.dkl.knowledge-modeling.registry.business-object.decision",
      description: "Architectural category for a decision record definition; no decision making.",
      category: "BusinessObjectType",
      organizationalCategory: "Decision",
      owner: OWNER,
      sourcePhase: PHASE,
      lifecycleStatus: "Registered",
      stabilityStatus: "Stable",
      compatibilityStatus: "Restricted",
      extensionStatus: "AdditiveAllowed",
      publicVisibility: "Public",
      tags: Object.freeze(["business-object", "governance"]),
      behaviorImplemented: false,
      runtimeInstanceCreated: false,
      persistenceSchemaAssumed: false,
    }),
    Object.freeze({
      id: "km-bo-event",
      name: "Event",
      namespace: "nexora.dkl.knowledge-modeling.registry.business-object.event",
      description: "Architectural category for an event business object.",
      category: "BusinessObjectType",
      organizationalCategory: "Event",
      owner: OWNER,
      sourcePhase: PHASE,
      lifecycleStatus: "Registered",
      stabilityStatus: "Stable",
      compatibilityStatus: "Compatible",
      extensionStatus: "AdditiveAllowed",
      publicVisibility: "Public",
      tags: Object.freeze(["business-object", "temporal"]),
      behaviorImplemented: false,
      runtimeInstanceCreated: false,
      persistenceSchemaAssumed: false,
    }),
    Object.freeze({
      id: "km-bo-document",
      name: "Document",
      namespace: "nexora.dkl.knowledge-modeling.registry.business-object.document",
      description: "Architectural category for a document business object.",
      category: "BusinessObjectType",
      organizationalCategory: "Document",
      owner: OWNER,
      sourcePhase: PHASE,
      lifecycleStatus: "Registered",
      stabilityStatus: "Stable",
      compatibilityStatus: "Compatible",
      extensionStatus: "AdditiveAllowed",
      publicVisibility: "Public",
      tags: Object.freeze(["business-object", "content"]),
      behaviorImplemented: false,
      runtimeInstanceCreated: false,
      persistenceSchemaAssumed: false,
    }),
    Object.freeze({
      id: "km-bo-communication",
      name: "Communication",
      namespace: "nexora.dkl.knowledge-modeling.registry.business-object.communication",
      description: "Architectural category for a communication business object.",
      category: "BusinessObjectType",
      organizationalCategory: "Communication",
      owner: OWNER,
      sourcePhase: PHASE,
      lifecycleStatus: "Registered",
      stabilityStatus: "Stable",
      compatibilityStatus: "Compatible",
      extensionStatus: "AdditiveAllowed",
      publicVisibility: "Public",
      tags: Object.freeze(["business-object", "content", "interaction"]),
      behaviorImplemented: false,
      runtimeInstanceCreated: false,
      persistenceSchemaAssumed: false,
    }),
  ]);
