/**
 * DKL-7:6 — Knowledge Services Platform Compatibility.
 *
 * Exactly fourteen immutable Compatible declarations.
 * No runtime authorization. No future imports.
 *
 * Ownership: owned exclusively by DKL-7:6.
 */

import { KnowledgeServicesPlatformChainIds } from "./knowledgeServicesPlatformArchitecture.ts";
import type { KnowledgeServicesPlatformCompatibilityDeclaration } from "./knowledgeServicesPlatformTypes.ts";

const compat = (
  key: string,
  subject: string,
  direction: string,
  compatibilityType: string,
  canonicalPath: string,
  ownershipConstraint: string,
  boundaryConstraint: string,
  changePolicy: string,
  evidenceReference: string,
  order: number,
): KnowledgeServicesPlatformCompatibilityDeclaration =>
  Object.freeze({
    compatibilityId: `DKL-7:6/Compatibility/${key}`,
    subject,
    direction,
    compatibilityType,
    status: "Compatible" as const,
    canonicalPath,
    ownershipConstraint,
    boundaryConstraint,
    changePolicy,
    runtimeAuthorization: "None" as const,
    evidenceReference,
    deterministicOrder: order,
  });

const ids = KnowledgeServicesPlatformChainIds;

/** Exactly fourteen Compatible declarations. */
export const KnowledgeServicesPlatformCompatibility: readonly KnowledgeServicesPlatformCompatibilityDeclaration[] =
  Object.freeze([
    compat(
      "Foundation",
      "Foundation compatibility",
      "Backward",
      "PhaseCompatibility",
      `Platform → Manifest → … → ${ids.foundationId}`,
      "DKL-7 ownership unchanged",
      "29 prohibited surfaces preserved",
      "AdditiveOnly",
      "DKL-7:5/Manifest",
      1,
    ),
    compat(
      "Registry",
      "Registry compatibility",
      "Backward",
      "PhaseCompatibility",
      `Platform → Manifest → … → ${ids.registryId}`,
      "Registry inventories frozen by reference",
      "Read-only boundaries preserved",
      "AdditiveOnly",
      "DKL-7:5/Manifest",
      2,
    ),
    compat(
      "Model",
      "Model compatibility",
      "Backward",
      "PhaseCompatibility",
      `Platform → Manifest → … → ${ids.modelId}`,
      "Model inventory 79 preserved",
      "No mutation modes",
      "AdditiveOnly",
      "DKL-7:5/Manifest",
      3,
    ),
    compat(
      "Validation",
      "Validation compatibility",
      "Backward",
      "PhaseCompatibility",
      `Platform → Manifest → ${ids.validationId}`,
      "48 Validation rules remain Pass",
      "No runtime validation",
      "AdditiveOnly",
      "DKL-7:5/Manifest",
      4,
    ),
    compat(
      "Manifest",
      "Manifest compatibility",
      "Backward",
      "PhaseCompatibility",
      `Platform → ${ids.manifestId}`,
      "Manifest inventory 447 preserved",
      "No Manifest reconstruction",
      "AdditiveOnly",
      "DKL-7:5/Manifest",
      5,
    ),
    compat(
      "Dkl6PublicIndex",
      "DKL-6 Public Index compatibility",
      "Upstream",
      "UpstreamCompatibility",
      `Foundation → ${ids.dkl6PublicIndexId}`,
      "DKL-6 ownership retained",
      "No direct DKL-6 import by Platform",
      "PublicIndexOnly",
      "DKL-7:5/Manifest.identity.dkl6PublicIndexId",
      6,
    ),
    compat(
      "FutureCertification",
      "Future Certification compatibility",
      "Forward",
      "FuturePhaseCompatibility",
      "Certification → Platform",
      "Certification may consume Platform",
      "No Certification runtime in Platform",
      "ForwardCompatibleDeclaration",
      "DKL-7:6/Dependency/CertificationToPlatform",
      7,
    ),
    compat(
      "FutureFreeze",
      "Future Freeze compatibility",
      "Forward",
      "FuturePhaseCompatibility",
      "Freeze → Certification → Platform",
      "Freeze consumes Certification only",
      "No Freeze direct Platform import",
      "ForwardCompatibleDeclaration",
      "DKL-7:6/Dependency/FreezeToCertification",
      8,
    ),
    compat(
      "FuturePublicIndex",
      "Future Public Index compatibility",
      "Forward",
      "FuturePhaseCompatibility",
      "Public Index → Freeze → … → Platform",
      "Public Index consumes Freeze only",
      "No consumer release in Platform",
      "ForwardCompatibleDeclaration",
      "DKL-7:6/Dependency/PublicIndexToFreeze",
      9,
    ),
    compat(
      "ExecutiveEngineConsumer",
      "Executive Engine consumer compatibility",
      "Consumer",
      "FutureConsumerCompatibility",
      "Executive Engine → future Public Index",
      "Executive Engine not owned by DKL-7",
      "No Engine reasoning in Platform",
      "ConsumerViaFuturePublicIndexOnly",
      "DKL-7:6/Dependency/ExecutiveEngineToPublicIndex",
      10,
    ),
    compat(
      "AdvisorConsumer",
      "Advisor consumer compatibility",
      "Consumer",
      "FutureConsumerCompatibility",
      "Advisor → future Public Index",
      "Advisor not owned by DKL-7",
      "No Advisor behavior in Platform",
      "ConsumerViaFuturePublicIndexOnly",
      "DKL-7:6/Dependency/AdvisorToPublicIndex",
      11,
    ),
    compat(
      "ApprovedInternalConsumer",
      "Future approved internal consumer compatibility",
      "Consumer",
      "FutureConsumerCompatibility",
      "Approved internal consumer → future Public Index",
      "Consumers not owned by DKL-7",
      "No consumer runtime in Platform",
      "ConsumerViaFuturePublicIndexOnly",
      "DKL-7:6/Dependency/ApprovedInternalConsumerToPublicIndex",
      12,
    ),
    compat(
      "BackwardThroughManifest",
      "Backward compatibility with DKL-7:1 through DKL-7:5",
      "Backward",
      "MultiPhaseCompatibility",
      "Platform → Manifest → Validation → Model → Registry → Foundation",
      "No ownership transfer across phases",
      "All prior inventories preserved",
      "AdditiveOnly",
      "DKL-7:5/Manifest",
      13,
    ),
    compat(
      "AdditiveExtension",
      "Additive extension compatibility",
      "Forward",
      "ExtensionCompatibility",
      "Future Certification and later phases",
      "Additive declarations only",
      "No weakening of prohibitions",
      "AdditiveOnly",
      "DKL-7:6/Guarantees",
      14,
    ),
  ]);
