/**
 * DKL-4:2 — Knowledge Modeling Relationship Registry.
 *
 * Canonical relationship category registrations. These entries describe
 * relationship architecture only; they do not execute graph behavior.
 *
 * Ownership: owned exclusively by DKL-4:2.
 */

import type { RelationshipRegistryEntry } from "./knowledgeModelingRegistryTypes.ts";

const OWNER = "DKL-4 Knowledge Modeling Registry";
const PHASE = "DKL-4:2";
const ANY_BUSINESS_OBJECT = Object.freeze(["BusinessObjectType", "EntityType"]);
const PARTY_OR_ORG = Object.freeze(["Customer", "Employee", "Supplier", "Department", "Team"]);
const WORK_OBJECTS = Object.freeze(["Project", "Program", "Process", "Task", "Goal", "KPI"]);
const COMMERCIAL_OBJECTS = Object.freeze([
  "Customer",
  "Supplier",
  "Product",
  "Service",
  "Contract",
  "Order",
  "Invoice",
  "Payment",
]);

export const KnowledgeModelingRelationshipRegistry: readonly RelationshipRegistryEntry[] =
  Object.freeze([
    Object.freeze({
      id: "km-rel-owns",
      name: "owns",
      namespace: "nexora.dkl.knowledge-modeling.registry.relationship.owns",
      description: "Ownership relationship category between source and target concepts.",
      category: "RelationshipType",
      relationshipCategory: "Ownership",
      direction: "SourceToTarget",
      sourceCompatibility: PARTY_OR_ORG,
      targetCompatibility: ANY_BUSINESS_OBJECT,
      cardinality: "OneToMany",
      owner: OWNER,
      sourcePhase: PHASE,
      lifecycleStatus: "Registered",
      stabilityStatus: "Stable",
      compatibilityStatus: "Compatible",
      extensionStatus: "AdditiveAllowed",
      publicVisibility: "Public",
      tags: Object.freeze(["relationship", "ownership"]),
      graphBehaviorEnforced: false,
    }),
    Object.freeze({
      id: "km-rel-belongs-to",
      name: "belongsTo",
      namespace: "nexora.dkl.knowledge-modeling.registry.relationship.belongs-to",
      description: "Belonging relationship category from object to owning context.",
      category: "RelationshipType",
      relationshipCategory: "Ownership",
      direction: "SourceToTarget",
      sourceCompatibility: ANY_BUSINESS_OBJECT,
      targetCompatibility: PARTY_OR_ORG,
      cardinality: "ManyToOne",
      owner: OWNER,
      sourcePhase: PHASE,
      lifecycleStatus: "Registered",
      stabilityStatus: "Stable",
      compatibilityStatus: "Compatible",
      extensionStatus: "AdditiveAllowed",
      publicVisibility: "Public",
      tags: Object.freeze(["relationship", "ownership"]),
      graphBehaviorEnforced: false,
    }),
    Object.freeze({
      id: "km-rel-contains",
      name: "contains",
      namespace: "nexora.dkl.knowledge-modeling.registry.relationship.contains",
      description: "Containment relationship category for part-whole modeling.",
      category: "RelationshipType",
      relationshipCategory: "Containment",
      direction: "SourceToTarget",
      sourceCompatibility: ANY_BUSINESS_OBJECT,
      targetCompatibility: ANY_BUSINESS_OBJECT,
      cardinality: "OneToMany",
      owner: OWNER,
      sourcePhase: PHASE,
      lifecycleStatus: "Registered",
      stabilityStatus: "Stable",
      compatibilityStatus: "Compatible",
      extensionStatus: "AdditiveAllowed",
      publicVisibility: "Public",
      tags: Object.freeze(["relationship", "containment"]),
      graphBehaviorEnforced: false,
    }),
    Object.freeze({
      id: "km-rel-references",
      name: "references",
      namespace: "nexora.dkl.knowledge-modeling.registry.relationship.references",
      description: "Reference relationship category between modeled concepts.",
      category: "RelationshipType",
      relationshipCategory: "Reference",
      direction: "SourceToTarget",
      sourceCompatibility: ANY_BUSINESS_OBJECT,
      targetCompatibility: ANY_BUSINESS_OBJECT,
      cardinality: "ManyToMany",
      owner: OWNER,
      sourcePhase: PHASE,
      lifecycleStatus: "Registered",
      stabilityStatus: "Stable",
      compatibilityStatus: "Compatible",
      extensionStatus: "AdditiveAllowed",
      publicVisibility: "Public",
      tags: Object.freeze(["relationship", "reference"]),
      graphBehaviorEnforced: false,
    }),
    Object.freeze({
      id: "km-rel-depends-on",
      name: "dependsOn",
      namespace: "nexora.dkl.knowledge-modeling.registry.relationship.depends-on",
      description: "Dependency relationship category between modeled concepts.",
      category: "RelationshipType",
      relationshipCategory: "Dependency",
      direction: "SourceToTarget",
      sourceCompatibility: ANY_BUSINESS_OBJECT,
      targetCompatibility: ANY_BUSINESS_OBJECT,
      cardinality: "ManyToMany",
      owner: OWNER,
      sourcePhase: PHASE,
      lifecycleStatus: "Registered",
      stabilityStatus: "Stable",
      compatibilityStatus: "Compatible",
      extensionStatus: "AdditiveAllowed",
      publicVisibility: "Public",
      tags: Object.freeze(["relationship", "dependency"]),
      graphBehaviorEnforced: false,
    }),
    Object.freeze({
      id: "km-rel-relates-to",
      name: "relatesTo",
      namespace: "nexora.dkl.knowledge-modeling.registry.relationship.relates-to",
      description: "Generic relation category for declared association metadata.",
      category: "RelationshipType",
      relationshipCategory: "Association",
      direction: "Bidirectional",
      sourceCompatibility: ANY_BUSINESS_OBJECT,
      targetCompatibility: ANY_BUSINESS_OBJECT,
      cardinality: "ManyToMany",
      owner: OWNER,
      sourcePhase: PHASE,
      lifecycleStatus: "Registered",
      stabilityStatus: "Stable",
      compatibilityStatus: "Compatible",
      extensionStatus: "AdditiveAllowed",
      publicVisibility: "Public",
      tags: Object.freeze(["relationship", "association"]),
      graphBehaviorEnforced: false,
    }),
    Object.freeze({
      id: "km-rel-reports-to",
      name: "reportsTo",
      namespace: "nexora.dkl.knowledge-modeling.registry.relationship.reports-to",
      description: "Reporting relationship category for organizational models.",
      category: "RelationshipType",
      relationshipCategory: "Organizational",
      direction: "SourceToTarget",
      sourceCompatibility: Object.freeze(["Employee", "Team", "Department"]),
      targetCompatibility: Object.freeze(["Employee", "Team", "Department"]),
      cardinality: "ManyToOne",
      owner: OWNER,
      sourcePhase: PHASE,
      lifecycleStatus: "Registered",
      stabilityStatus: "Stable",
      compatibilityStatus: "Compatible",
      extensionStatus: "AdditiveAllowed",
      publicVisibility: "Public",
      tags: Object.freeze(["relationship", "organizational"]),
      graphBehaviorEnforced: false,
    }),
    Object.freeze({
      id: "km-rel-participates-in",
      name: "participatesIn",
      namespace: "nexora.dkl.knowledge-modeling.registry.relationship.participates-in",
      description: "Participation relationship category for people, teams, and work objects.",
      category: "RelationshipType",
      relationshipCategory: "Participation",
      direction: "SourceToTarget",
      sourceCompatibility: PARTY_OR_ORG,
      targetCompatibility: WORK_OBJECTS,
      cardinality: "ManyToMany",
      owner: OWNER,
      sourcePhase: PHASE,
      lifecycleStatus: "Registered",
      stabilityStatus: "Stable",
      compatibilityStatus: "Compatible",
      extensionStatus: "AdditiveAllowed",
      publicVisibility: "Public",
      tags: Object.freeze(["relationship", "participation"]),
      graphBehaviorEnforced: false,
    }),
    Object.freeze({
      id: "km-rel-responsible-for",
      name: "responsibleFor",
      namespace: "nexora.dkl.knowledge-modeling.registry.relationship.responsible-for",
      description: "Responsibility relationship category for ownership of work or outcomes.",
      category: "RelationshipType",
      relationshipCategory: "Responsibility",
      direction: "SourceToTarget",
      sourceCompatibility: PARTY_OR_ORG,
      targetCompatibility: WORK_OBJECTS,
      cardinality: "ManyToMany",
      owner: OWNER,
      sourcePhase: PHASE,
      lifecycleStatus: "Registered",
      stabilityStatus: "Stable",
      compatibilityStatus: "Compatible",
      extensionStatus: "AdditiveAllowed",
      publicVisibility: "Public",
      tags: Object.freeze(["relationship", "responsibility"]),
      graphBehaviorEnforced: false,
    }),
    Object.freeze({
      id: "km-rel-created-by",
      name: "createdBy",
      namespace: "nexora.dkl.knowledge-modeling.registry.relationship.created-by",
      description: "Creation provenance relationship category.",
      category: "RelationshipType",
      relationshipCategory: "Provenance",
      direction: "SourceToTarget",
      sourceCompatibility: ANY_BUSINESS_OBJECT,
      targetCompatibility: PARTY_OR_ORG,
      cardinality: "ManyToOne",
      owner: OWNER,
      sourcePhase: PHASE,
      lifecycleStatus: "Registered",
      stabilityStatus: "Stable",
      compatibilityStatus: "Compatible",
      extensionStatus: "AdditiveAllowed",
      publicVisibility: "Public",
      tags: Object.freeze(["relationship", "provenance"]),
      graphBehaviorEnforced: false,
    }),
    Object.freeze({
      id: "km-rel-assigned-to",
      name: "assignedTo",
      namespace: "nexora.dkl.knowledge-modeling.registry.relationship.assigned-to",
      description: "Assignment relationship category for work and responsibility metadata.",
      category: "RelationshipType",
      relationshipCategory: "Assignment",
      direction: "SourceToTarget",
      sourceCompatibility: Object.freeze(["Task", "Issue", "Risk", "Project"]),
      targetCompatibility: PARTY_OR_ORG,
      cardinality: "ManyToMany",
      owner: OWNER,
      sourcePhase: PHASE,
      lifecycleStatus: "Registered",
      stabilityStatus: "Stable",
      compatibilityStatus: "Compatible",
      extensionStatus: "AdditiveAllowed",
      publicVisibility: "Public",
      tags: Object.freeze(["relationship", "assignment"]),
      graphBehaviorEnforced: false,
    }),
    Object.freeze({
      id: "km-rel-supplies",
      name: "supplies",
      namespace: "nexora.dkl.knowledge-modeling.registry.relationship.supplies",
      description: "Supply relationship category for supplier and offering metadata.",
      category: "RelationshipType",
      relationshipCategory: "Commercial",
      direction: "SourceToTarget",
      sourceCompatibility: Object.freeze(["Supplier"]),
      targetCompatibility: Object.freeze(["Product", "Service", "Asset"]),
      cardinality: "ManyToMany",
      owner: OWNER,
      sourcePhase: PHASE,
      lifecycleStatus: "Registered",
      stabilityStatus: "Stable",
      compatibilityStatus: "Compatible",
      extensionStatus: "AdditiveAllowed",
      publicVisibility: "Public",
      tags: Object.freeze(["relationship", "commercial"]),
      graphBehaviorEnforced: false,
    }),
    Object.freeze({
      id: "km-rel-purchases",
      name: "purchases",
      namespace: "nexora.dkl.knowledge-modeling.registry.relationship.purchases",
      description: "Purchase relationship category for commercial metadata.",
      category: "RelationshipType",
      relationshipCategory: "Commercial",
      direction: "SourceToTarget",
      sourceCompatibility: Object.freeze(["Customer", "Department", "Team"]),
      targetCompatibility: COMMERCIAL_OBJECTS,
      cardinality: "ManyToMany",
      owner: OWNER,
      sourcePhase: PHASE,
      lifecycleStatus: "Registered",
      stabilityStatus: "Stable",
      compatibilityStatus: "Compatible",
      extensionStatus: "AdditiveAllowed",
      publicVisibility: "Public",
      tags: Object.freeze(["relationship", "commercial"]),
      graphBehaviorEnforced: false,
    }),
    Object.freeze({
      id: "km-rel-produces",
      name: "produces",
      namespace: "nexora.dkl.knowledge-modeling.registry.relationship.produces",
      description: "Production relationship category for outputs and producing concepts.",
      category: "RelationshipType",
      relationshipCategory: "Production",
      direction: "SourceToTarget",
      sourceCompatibility: Object.freeze(["Process", "Team", "Department", "Project"]),
      targetCompatibility: Object.freeze(["Product", "Service", "Document", "Event"]),
      cardinality: "ManyToMany",
      owner: OWNER,
      sourcePhase: PHASE,
      lifecycleStatus: "Registered",
      stabilityStatus: "Stable",
      compatibilityStatus: "Compatible",
      extensionStatus: "AdditiveAllowed",
      publicVisibility: "Public",
      tags: Object.freeze(["relationship", "production"]),
      graphBehaviorEnforced: false,
    }),
    Object.freeze({
      id: "km-rel-affects",
      name: "affects",
      namespace: "nexora.dkl.knowledge-modeling.registry.relationship.affects",
      description: "Influence relationship category for risk, issue, and opportunity metadata.",
      category: "RelationshipType",
      relationshipCategory: "Impact",
      direction: "SourceToTarget",
      sourceCompatibility: Object.freeze(["Risk", "Issue", "Opportunity", "Decision", "Event"]),
      targetCompatibility: ANY_BUSINESS_OBJECT,
      cardinality: "ManyToMany",
      owner: OWNER,
      sourcePhase: PHASE,
      lifecycleStatus: "Registered",
      stabilityStatus: "Stable",
      compatibilityStatus: "Compatible",
      extensionStatus: "AdditiveAllowed",
      publicVisibility: "Public",
      tags: Object.freeze(["relationship", "impact"]),
      graphBehaviorEnforced: false,
    }),
    Object.freeze({
      id: "km-rel-supports",
      name: "supports",
      namespace: "nexora.dkl.knowledge-modeling.registry.relationship.supports",
      description: "Support relationship category between modeled concepts.",
      category: "RelationshipType",
      relationshipCategory: "Support",
      direction: "SourceToTarget",
      sourceCompatibility: ANY_BUSINESS_OBJECT,
      targetCompatibility: ANY_BUSINESS_OBJECT,
      cardinality: "ManyToMany",
      owner: OWNER,
      sourcePhase: PHASE,
      lifecycleStatus: "Registered",
      stabilityStatus: "Stable",
      compatibilityStatus: "Compatible",
      extensionStatus: "AdditiveAllowed",
      publicVisibility: "Public",
      tags: Object.freeze(["relationship", "support"]),
      graphBehaviorEnforced: false,
    }),
    Object.freeze({
      id: "km-rel-blocks",
      name: "blocks",
      namespace: "nexora.dkl.knowledge-modeling.registry.relationship.blocks",
      description: "Blocking relationship category for impediment metadata.",
      category: "RelationshipType",
      relationshipCategory: "Blocking",
      direction: "SourceToTarget",
      sourceCompatibility: Object.freeze(["Risk", "Issue", "Task", "Process"]),
      targetCompatibility: WORK_OBJECTS,
      cardinality: "ManyToMany",
      owner: OWNER,
      sourcePhase: PHASE,
      lifecycleStatus: "Registered",
      stabilityStatus: "Stable",
      compatibilityStatus: "Compatible",
      extensionStatus: "AdditiveAllowed",
      publicVisibility: "Public",
      tags: Object.freeze(["relationship", "blocking"]),
      graphBehaviorEnforced: false,
    }),
    Object.freeze({
      id: "km-rel-precedes",
      name: "precedes",
      namespace: "nexora.dkl.knowledge-modeling.registry.relationship.precedes",
      description: "Ordering relationship category for temporal or sequence metadata.",
      category: "RelationshipType",
      relationshipCategory: "TemporalOrdering",
      direction: "SourceToTarget",
      sourceCompatibility: Object.freeze(["Task", "Event", "Process", "Project"]),
      targetCompatibility: Object.freeze(["Task", "Event", "Process", "Project"]),
      cardinality: "ManyToMany",
      owner: OWNER,
      sourcePhase: PHASE,
      lifecycleStatus: "Registered",
      stabilityStatus: "Stable",
      compatibilityStatus: "Compatible",
      extensionStatus: "AdditiveAllowed",
      publicVisibility: "Public",
      tags: Object.freeze(["relationship", "ordering"]),
      graphBehaviorEnforced: false,
    }),
    Object.freeze({
      id: "km-rel-follows",
      name: "follows",
      namespace: "nexora.dkl.knowledge-modeling.registry.relationship.follows",
      description: "Reverse ordering relationship category for sequence metadata.",
      category: "RelationshipType",
      relationshipCategory: "TemporalOrdering",
      direction: "SourceToTarget",
      sourceCompatibility: Object.freeze(["Task", "Event", "Process", "Project"]),
      targetCompatibility: Object.freeze(["Task", "Event", "Process", "Project"]),
      cardinality: "ManyToMany",
      owner: OWNER,
      sourcePhase: PHASE,
      lifecycleStatus: "Registered",
      stabilityStatus: "Stable",
      compatibilityStatus: "Compatible",
      extensionStatus: "AdditiveAllowed",
      publicVisibility: "Public",
      tags: Object.freeze(["relationship", "ordering"]),
      graphBehaviorEnforced: false,
    }),
    Object.freeze({
      id: "km-rel-associated-with",
      name: "associatedWith",
      namespace: "nexora.dkl.knowledge-modeling.registry.relationship.associated-with",
      description: "Bidirectional association relationship category.",
      category: "RelationshipType",
      relationshipCategory: "Association",
      direction: "Bidirectional",
      sourceCompatibility: ANY_BUSINESS_OBJECT,
      targetCompatibility: ANY_BUSINESS_OBJECT,
      cardinality: "ManyToMany",
      owner: OWNER,
      sourcePhase: PHASE,
      lifecycleStatus: "Registered",
      stabilityStatus: "Stable",
      compatibilityStatus: "Compatible",
      extensionStatus: "AdditiveAllowed",
      publicVisibility: "Public",
      tags: Object.freeze(["relationship", "association"]),
      graphBehaviorEnforced: false,
    }),
  ]);
