/**
 * DKL-4:7 — Knowledge Modeling Certification Gates.
 *
 * Immutable catalog of mandatory certification gates. Metadata only.
 * Evaluation occurs in knowledgeModelingCertification.ts.
 *
 * Ownership: owned exclusively by DKL-4:7.
 */

import type {
  CertificationCategory,
  CertificationGateDefinition,
  CertificationSeverity,
} from "./knowledgeModelingCertificationTypes.ts";

const OWNER = "DKL-4 Knowledge Modeling Certification";

export const KNOWLEDGE_MODELING_CERTIFICATION_CATEGORIES: readonly CertificationCategory[] =
  Object.freeze([
    "Identity",
    "Foundation",
    "Registry",
    "Model",
    "Validation",
    "Manifest",
    "Platform",
    "Ownership",
    "Dependencies",
    "Compatibility",
    "Extension",
    "Immutability",
    "Determinism",
    "Runtime Prohibition",
    "Regression Protection",
    "Freeze Readiness",
  ]);

const gate = (
  id: string,
  name: string,
  description: string,
  category: CertificationCategory,
  severity: CertificationSeverity,
  source: string,
  requirement: string,
  evidenceTarget: string,
  expectedCondition: string,
  failureMeaning: string,
): CertificationGateDefinition =>
  Object.freeze({
    id,
    name,
    description,
    category,
    severity,
    source,
    requirement,
    evidenceTarget,
    expectedCondition,
    failureMeaning,
    ownership: OWNER,
    deterministic: true as const,
    mandatory: true as const,
  });

/** Canonical immutable certification gate catalog. */
export const KnowledgeModelingCertificationGates: readonly CertificationGateDefinition[] =
  Object.freeze([
    gate(
      "KM-CERT-001",
      "Platform identity exists",
      "Platform identity id is declared and non-empty.",
      "Identity",
      "Critical",
      "DKL-4:6",
      "Platform identity must exist.",
      "platform.identity.id",
      "DKL-4:6/KnowledgeModelingPlatform",
      "Certification cannot proceed without Platform identity.",
    ),
    gate(
      "KM-CERT-002",
      "Platform version exists",
      "Platform version is declared and stable.",
      "Identity",
      "Critical",
      "DKL-4:6",
      "Platform version must exist.",
      "platform.version",
      "1.0.0",
      "Version drift blocks freeze stability.",
    ),
    gate(
      "KM-CERT-003",
      "Platform namespace exists",
      "Platform namespace is declared.",
      "Identity",
      "Critical",
      "DKL-4:6",
      "Platform namespace must exist.",
      "platform.namespace",
      "nexora.dkl.knowledge-modeling.platform",
      "Namespace absence blocks consumer discovery.",
    ),
    gate(
      "KM-CERT-004",
      "Platform status is PlatformComplete",
      "Platform reports PlatformComplete.",
      "Platform",
      "Critical",
      "DKL-4:6",
      "Platform must be complete.",
      "platform.identity.status",
      "PlatformComplete",
      "Incomplete Platform blocks Certification.",
    ),
    gate(
      "KM-CERT-005",
      "Platform readiness is ReadyForCertification",
      "Platform readiness must be ReadyForCertification.",
      "Platform",
      "Critical",
      "DKL-4:6",
      "Platform must be ready for Certification.",
      "platform.identity.readiness",
      "ReadyForCertification",
      "Premature Certification is forbidden.",
    ),
    gate(
      "KM-CERT-006",
      "All 16 Platform readiness gates pass",
      "Every Platform readiness gate reports Pass.",
      "Platform",
      "Critical",
      "DKL-4:6",
      "All Platform readiness gates must pass.",
      "platform.readiness.gates",
      "16/16 Pass",
      "Failed Platform gates invalidate Certification.",
    ),
    gate(
      "KM-CERT-007",
      "Foundation reference is canonical",
      "Platform foundation section is identity-equal to sections.foundation.",
      "Foundation",
      "Critical",
      "DKL-4:6",
      "Foundation must be included by canonical reference.",
      "platform.foundation",
      "identity-equal reference",
      "Copied Foundation metadata invalidates Certification.",
    ),
    gate(
      "KM-CERT-008",
      "Registry reference is canonical",
      "Platform registry section is identity-equal to sections.registry.",
      "Registry",
      "Critical",
      "DKL-4:6",
      "Registry must be included by canonical reference.",
      "platform.registry",
      "identity-equal reference",
      "Copied Registry metadata invalidates Certification.",
    ),
    gate(
      "KM-CERT-009",
      "Model reference is canonical",
      "Platform model section is identity-equal to sections.model.",
      "Model",
      "Critical",
      "DKL-4:6",
      "Model must be included by canonical reference.",
      "platform.model",
      "identity-equal reference",
      "Copied Model metadata invalidates Certification.",
    ),
    gate(
      "KM-CERT-010",
      "Validation reference is canonical",
      "Platform validation section is identity-equal to sections.validation.",
      "Validation",
      "Critical",
      "DKL-4:6",
      "Validation must be included by canonical reference.",
      "platform.validation",
      "identity-equal reference",
      "Copied Validation metadata invalidates Certification.",
    ),
    gate(
      "KM-CERT-011",
      "Manifest reference is canonical",
      "Platform manifest section is identity-equal to sections.manifest.",
      "Manifest",
      "Critical",
      "DKL-4:6",
      "Manifest must be included by canonical reference.",
      "platform.manifest",
      "identity-equal reference",
      "Copied Manifest metadata invalidates Certification.",
    ),
    gate(
      "KM-CERT-012",
      "Six Platform sections exist",
      "Platform exposes exactly six primary sections.",
      "Platform",
      "Critical",
      "DKL-4:6",
      "Six sections must exist.",
      "platform.sections",
      "count=6",
      "Missing sections break Platform composition.",
    ),
    gate(
      "KM-CERT-013",
      "Platform section order is correct",
      "Section order is metadata→foundation→registry→model→validation→manifest.",
      "Platform",
      "Critical",
      "DKL-4:6",
      "Section order must be deterministic.",
      "platform.sectionOrder",
      "metadata→foundation→registry→model→validation→manifest",
      "Section order drift breaks consumer contracts.",
    ),
    gate(
      "KM-CERT-014",
      "Five upstream components included by reference",
      "All five upstream components are includedByReference.",
      "Platform",
      "Critical",
      "DKL-4:6",
      "Components must be by-reference only.",
      "platform.components.components",
      "5 components; includedByReference=true",
      "Re-owned components violate architecture boundaries.",
    ),
    gate(
      "KM-CERT-015",
      "No Platform component is re-owned",
      "Every component has ownedByPlatform=false.",
      "Ownership",
      "Critical",
      "DKL-4:6",
      "Platform must not re-own upstream components.",
      "platform.components.components",
      "ownedByPlatform=false",
      "Ownership duplication blocks Freeze.",
    ),
    gate(
      "KM-CERT-016",
      "Validation status is ValidationComplete",
      "Validation phase reports ValidationComplete.",
      "Validation",
      "Critical",
      "DKL-4:4",
      "Validation must be complete.",
      "platform.validation.identity.status",
      "ValidationComplete",
      "Incomplete Validation blocks Certification.",
    ),
    gate(
      "KM-CERT-017",
      "Validation overall result is Pass",
      "Validation report status is Validated with zero failures.",
      "Validation",
      "Critical",
      "DKL-4:4",
      "Validation must pass architecturally.",
      "platform.validation.report.status",
      "Validated",
      "Failed Validation invalidates Platform.",
    ),
    gate(
      "KM-CERT-018",
      "All validation rules pass",
      "Validation report failCount is zero.",
      "Validation",
      "Critical",
      "DKL-4:4",
      "All validation rules must pass.",
      "platform.validation.report.failCount",
      "0",
      "Failed rules indicate architectural defects.",
    ),
    gate(
      "KM-CERT-019",
      "Manifest status is ManifestComplete",
      "Manifest reports ManifestComplete.",
      "Manifest",
      "Critical",
      "DKL-4:5",
      "Manifest must be complete.",
      "platform.manifest.identity.status",
      "ManifestComplete",
      "Incomplete Manifest blocks Certification.",
    ),
    gate(
      "KM-CERT-020",
      "Manifest readiness is ReadyForPlatform",
      "Manifest readiness is ReadyForPlatform.",
      "Manifest",
      "Critical",
      "DKL-4:5",
      "Manifest must be ready for Platform.",
      "platform.manifest.identity.readiness",
      "ReadyForPlatform",
      "Manifest readiness regression blocks Platform.",
    ),
    gate(
      "KM-CERT-021",
      "Foundation status/readiness progression",
      "Foundation is FoundationComplete and ReadyForRegistry.",
      "Foundation",
      "Critical",
      "DKL-4:1",
      "Foundation lifecycle progression must be correct.",
      "platform.foundation.identity",
      "FoundationComplete/ReadyForRegistry",
      "Foundation regression blocks downstream phases.",
    ),
    gate(
      "KM-CERT-022",
      "Registry status/readiness progression",
      "Registry is RegistryComplete and ReadyForModel.",
      "Registry",
      "Critical",
      "DKL-4:2",
      "Registry lifecycle progression must be correct.",
      "platform.registry.identity",
      "RegistryComplete/ReadyForModel",
      "Registry regression blocks Model.",
    ),
    gate(
      "KM-CERT-023",
      "Model status/readiness progression",
      "Model is ModelComplete and ReadyForValidation.",
      "Model",
      "Critical",
      "DKL-4:3",
      "Model lifecycle progression must be correct.",
      "platform.model.identity",
      "ModelComplete/ReadyForValidation",
      "Model regression blocks Validation.",
    ),
    gate(
      "KM-CERT-024",
      "Validation status/readiness progression",
      "Validation is ValidationComplete and ReadyForManifest.",
      "Validation",
      "Critical",
      "DKL-4:4",
      "Validation lifecycle progression must be correct.",
      "platform.validation.identity",
      "ValidationComplete/ReadyForManifest",
      "Validation regression blocks Manifest.",
    ),
    gate(
      "KM-CERT-025",
      "Manifest status/readiness progression",
      "Manifest is ManifestComplete and ReadyForPlatform.",
      "Manifest",
      "Critical",
      "DKL-4:5",
      "Manifest lifecycle progression must be correct.",
      "platform.manifest.identity",
      "ManifestComplete/ReadyForPlatform",
      "Manifest regression blocks Platform.",
    ),
    gate(
      "KM-CERT-026",
      "Platform status/readiness progression",
      "Platform is PlatformComplete and ReadyForCertification.",
      "Platform",
      "Critical",
      "DKL-4:6",
      "Platform lifecycle progression must be correct.",
      "platform.identity",
      "PlatformComplete/ReadyForCertification",
      "Platform regression blocks Certification.",
    ),
    gate(
      "KM-CERT-027",
      "Public API surfaces are explicit",
      "Platform declares 48 total public APIs across phases.",
      "Platform",
      "High",
      "DKL-4:6",
      "Public API counts must be explicit.",
      "platform.summary.totalPublicApiCount",
      "48",
      "Implicit APIs break consumer contracts.",
    ),
    gate(
      "KM-CERT-028",
      "Ownership conflicts are absent",
      "No duplicate architectural ownership and no component re-ownership.",
      "Ownership",
      "Critical",
      "DKL-4:6",
      "Ownership must be conflict-free.",
      "platform.metadata.ownership",
      "noDuplicatedOwnership=true",
      "Ownership conflicts block Freeze.",
    ),
    gate(
      "KM-CERT-029",
      "Dependency ordering is correct",
      "Dependencies follow Foundation→Registry→Model→Validation→Manifest.",
      "Dependencies",
      "Critical",
      "DKL-4:6",
      "Dependency order must be correct.",
      "platform.dependencies.orderedAs",
      "Foundation→Registry→Model→Validation→Manifest",
      "Dependency order violations break composition.",
    ),
    gate(
      "KM-CERT-030",
      "Public-entry-point-only dependency policy",
      "Platform dependencies are public entry points only.",
      "Dependencies",
      "Critical",
      "DKL-4:6",
      "Only canonical entry points may be consumed.",
      "platform.dependencies.publicEntryPointOnly",
      "true",
      "Internal imports violate dependency policy.",
    ),
    gate(
      "KM-CERT-031",
      "No direct DKL-3 dependency",
      "Platform declares no direct DKL-3 dependency.",
      "Dependencies",
      "Critical",
      "DKL-4:6",
      "DKL-3 must be upstream-reference only.",
      "platform.dependencies.noDirectDkl3Dependency",
      "true",
      "Direct DKL-3 imports violate layering.",
    ),
    gate(
      "KM-CERT-032",
      "No Engine dependency",
      "Platform declares no Engine dependency.",
      "Dependencies",
      "Critical",
      "DKL-4:6",
      "Engine must not be a dependency.",
      "platform.dependencies.noEngineDependency",
      "true",
      "Engine coupling violates metadata-only architecture.",
    ),
    gate(
      "KM-CERT-033",
      "No persistence dependency",
      "Platform declares no persistence dependency.",
      "Dependencies",
      "Critical",
      "DKL-4:6",
      "Persistence must not be a dependency.",
      "platform.dependencies.noPersistenceDependency",
      "true",
      "Persistence coupling violates architecture.",
    ),
    gate(
      "KM-CERT-034",
      "No external library dependency",
      "Platform declares no external package dependency.",
      "Dependencies",
      "Critical",
      "DKL-4:6",
      "External packages must not be dependencies.",
      "platform.dependencies.noExternalPackageDependency",
      "true",
      "External dependencies break determinism guarantees.",
    ),
    gate(
      "KM-CERT-035",
      "Compatibility declarations are complete",
      "Platform compatibility catalog has required entries.",
      "Compatibility",
      "High",
      "DKL-4:6",
      "Compatibility declarations must be complete.",
      "platform.compatibility.entryCount",
      ">=10",
      "Incomplete compatibility blocks consumer safety.",
    ),
    gate(
      "KM-CERT-036",
      "Extension declarations are additive and controlled",
      "Extensions are additive with mutable registration forbidden.",
      "Extension",
      "High",
      "DKL-4:6",
      "Extensions must be controlled.",
      "platform.extensions",
      "additiveOnly=true; mutableRegistrationForbidden=true",
      "Uncontrolled extensions break stability.",
    ),
    gate(
      "KM-CERT-037",
      "Exported Platform metadata is frozen",
      "Platform aggregate and metadata are frozen.",
      "Immutability",
      "Critical",
      "DKL-4:6",
      "Platform metadata must be frozen.",
      "platform",
      "Object.isFrozen(platform)=true",
      "Mutable Platform metadata invalidates Certification.",
    ),
    gate(
      "KM-CERT-038",
      "Platform component metadata is frozen",
      "Component registry and entries are frozen.",
      "Immutability",
      "Critical",
      "DKL-4:6",
      "Component metadata must be frozen.",
      "platform.components",
      "frozen components and entries",
      "Mutable components enable drift.",
    ),
    gate(
      "KM-CERT-039",
      "Readiness metadata is frozen",
      "Platform readiness gates are frozen.",
      "Immutability",
      "Critical",
      "DKL-4:6",
      "Readiness metadata must be frozen.",
      "platform.readiness",
      "frozen readiness and gates",
      "Mutable readiness enables false Certification.",
    ),
    gate(
      "KM-CERT-040",
      "Certification evaluation is deterministic",
      "Platform and Certification declare deterministic metadata.",
      "Determinism",
      "Critical",
      "DKL-4:7",
      "Evaluation must be deterministic.",
      "platform.deterministic",
      "true",
      "Non-deterministic Certification is invalid.",
    ),
    gate(
      "KM-CERT-041",
      "No runtime Knowledge Object creation",
      "Model guarantees forbid object factories.",
      "Runtime Prohibition",
      "Critical",
      "DKL-4:3",
      "Runtime KO creation must be forbidden.",
      "platform.model.guarantees.noObjectFactories",
      "true",
      "Runtime KO creation violates architecture.",
    ),
    gate(
      "KM-CERT-042",
      "No runtime Business Object creation",
      "Platform ownership excludes runtime Business Objects.",
      "Runtime Prohibition",
      "Critical",
      "DKL-4:6",
      "Runtime BO creation must be forbidden.",
      "platform.metadata.ownership.doesNotOwn",
      "includes Runtime Business Objects",
      "Runtime BO creation violates architecture.",
    ),
    gate(
      "KM-CERT-043",
      "No entity-resolution behavior",
      "Platform ownership excludes entity resolution.",
      "Runtime Prohibition",
      "Critical",
      "DKL-4:6",
      "Entity resolution must be forbidden.",
      "platform.metadata.ownership.doesNotOwn",
      "includes Entity resolution",
      "Entity resolution is out of scope.",
    ),
    gate(
      "KM-CERT-044",
      "No semantic-inference behavior",
      "Platform ownership excludes semantic inference.",
      "Runtime Prohibition",
      "Critical",
      "DKL-4:6",
      "Semantic inference must be forbidden.",
      "platform.metadata.ownership.doesNotOwn",
      "includes Semantic inference",
      "Inference violates metadata-only architecture.",
    ),
    gate(
      "KM-CERT-045",
      "No graph construction or traversal",
      "Model guarantees forbid graph operations.",
      "Runtime Prohibition",
      "Critical",
      "DKL-4:3",
      "Graph operations must be forbidden.",
      "platform.model.guarantees.noGraphOperations",
      "true",
      "Graph behavior violates architecture.",
    ),
    gate(
      "KM-CERT-046",
      "No repository or query behavior",
      "Platform ownership excludes queries and persistence.",
      "Runtime Prohibition",
      "Critical",
      "DKL-4:6",
      "Repository/query behavior must be forbidden.",
      "platform.metadata.ownership.doesNotOwn",
      "includes Queries and Persistence",
      "Repository behavior is out of scope.",
    ),
    gate(
      "KM-CERT-047",
      "No mutable registration",
      "Extensions forbid mutable registration.",
      "Runtime Prohibition",
      "Critical",
      "DKL-4:6",
      "Mutable registration must be forbidden.",
      "platform.extensions.mutableRegistrationForbidden",
      "true",
      "Mutable registration enables architecture drift.",
    ),
    gate(
      "KM-CERT-048",
      "No source-code scanning",
      "Platform guarantees forbid source inspection.",
      "Runtime Prohibition",
      "Critical",
      "DKL-4:6",
      "Source scanning must be forbidden.",
      "platform.metadata.guarantees.noSourceInspection",
      "true",
      "Source scanning violates metadata-only Certification.",
    ),
    gate(
      "KM-CERT-049",
      "No environment-dependent behavior",
      "Platform guarantees forbid environment-dependent behavior.",
      "Runtime Prohibition",
      "Critical",
      "DKL-4:6",
      "Environment dependence must be forbidden.",
      "platform.metadata.guarantees.noEnvironmentDependentBehavior",
      "true",
      "Environment dependence breaks determinism.",
    ),
    gate(
      "KM-CERT-050",
      "Freeze prerequisites are satisfied",
      "All Certification prerequisites for Freeze are met.",
      "Freeze Readiness",
      "Critical",
      "DKL-4:7",
      "Freeze prerequisites must be satisfied.",
      "certification.readiness",
      "ReadyForFreeze",
      "Freeze cannot proceed until prerequisites pass.",
    ),
  ]);
