/**
 * DKL-6:8 — Knowledge Repository Freeze Registry.
 *
 * Declares freeze scope, frozen components, and canonical count preservation.
 * Metadata only. No runtime behavior.
 *
 * Ownership: owned exclusively by DKL-6:8.
 */

import {
  KnowledgeRepositoryFoundationId,
  KnowledgeRepositoryFoundationVersion,
  KnowledgeRepositoryFoundationStatus,
  KnowledgeRepositoryFoundationNamespace,
} from "./knowledgeRepositoryFoundation.ts";
import {
  KnowledgeRepositoryRegistryId,
  KnowledgeRepositoryRegistryVersion,
  KnowledgeRepositoryRegistryStatus,
  KnowledgeRepositoryRegistryNamespace,
} from "./knowledgeRepositoryRegistry.ts";
import {
  KnowledgeRepositoryModelId,
  KnowledgeRepositoryModelVersion,
  KnowledgeRepositoryModelStatus,
  KnowledgeRepositoryModelNamespace,
} from "./knowledgeRepositoryModel.ts";
import {
  KnowledgeRepositoryValidationId,
  KnowledgeRepositoryValidationVersion,
  KnowledgeRepositoryValidationStatus,
  KnowledgeRepositoryValidationNamespace,
} from "./knowledgeRepositoryValidation.ts";
import {
  KnowledgeRepositoryManifestId,
  KnowledgeRepositoryManifestVersion,
  KnowledgeRepositoryManifestStatus,
  KnowledgeRepositoryManifestNamespace,
} from "./knowledgeRepositoryManifest.ts";
import {
  KnowledgeRepositoryPlatformId,
  KnowledgeRepositoryPlatformVersion,
  KnowledgeRepositoryPlatformStatus,
  KnowledgeRepositoryPlatformNamespace,
} from "./knowledgeRepositoryPlatform.ts";
import {
  KnowledgeRepositoryCertificationId,
  KnowledgeRepositoryCertificationVersion,
  KnowledgeRepositoryCertificationStatus,
  KnowledgeRepositoryCertificationNamespace,
} from "./knowledgeRepositoryCertification.ts";
import type {
  KnowledgeRepositoryFreezeScope,
  KnowledgeRepositoryFrozenComponent,
} from "./knowledgeRepositoryFreezeTypes.ts";

export const KnowledgeRepositoryFreezeScopeEntries: readonly KnowledgeRepositoryFreezeScope[] =
  Object.freeze([
    Object.freeze({
      id: "DKL-6:8/Scope/Foundation",
      name: "foundation" as const,
      sourceIdentity: KnowledgeRepositoryFoundationId,
      sourceVersion: KnowledgeRepositoryFoundationVersion,
      sourceStatus: KnowledgeRepositoryFoundationStatus,
      order: 1,
      included: true as const,
      certified: true as const,
      frozen: true as const,
      stable: true as const,
      owner: "DKL-6" as const,
      runtimeBehavior: "None" as const,
    }),
    Object.freeze({
      id: "DKL-6:8/Scope/Registry",
      name: "registry" as const,
      sourceIdentity: KnowledgeRepositoryRegistryId,
      sourceVersion: KnowledgeRepositoryRegistryVersion,
      sourceStatus: KnowledgeRepositoryRegistryStatus,
      order: 2,
      included: true as const,
      certified: true as const,
      frozen: true as const,
      stable: true as const,
      owner: "DKL-6" as const,
      runtimeBehavior: "None" as const,
    }),
    Object.freeze({
      id: "DKL-6:8/Scope/Model",
      name: "model" as const,
      sourceIdentity: KnowledgeRepositoryModelId,
      sourceVersion: KnowledgeRepositoryModelVersion,
      sourceStatus: KnowledgeRepositoryModelStatus,
      order: 3,
      included: true as const,
      certified: true as const,
      frozen: true as const,
      stable: true as const,
      owner: "DKL-6" as const,
      runtimeBehavior: "None" as const,
    }),
    Object.freeze({
      id: "DKL-6:8/Scope/Validation",
      name: "validation" as const,
      sourceIdentity: KnowledgeRepositoryValidationId,
      sourceVersion: KnowledgeRepositoryValidationVersion,
      sourceStatus: KnowledgeRepositoryValidationStatus,
      order: 4,
      included: true as const,
      certified: true as const,
      frozen: true as const,
      stable: true as const,
      owner: "DKL-6" as const,
      runtimeBehavior: "None" as const,
    }),
    Object.freeze({
      id: "DKL-6:8/Scope/Manifest",
      name: "manifest" as const,
      sourceIdentity: KnowledgeRepositoryManifestId,
      sourceVersion: KnowledgeRepositoryManifestVersion,
      sourceStatus: KnowledgeRepositoryManifestStatus,
      order: 5,
      included: true as const,
      certified: true as const,
      frozen: true as const,
      stable: true as const,
      owner: "DKL-6" as const,
      runtimeBehavior: "None" as const,
    }),
    Object.freeze({
      id: "DKL-6:8/Scope/Platform",
      name: "platform" as const,
      sourceIdentity: KnowledgeRepositoryPlatformId,
      sourceVersion: KnowledgeRepositoryPlatformVersion,
      sourceStatus: KnowledgeRepositoryPlatformStatus,
      order: 6,
      included: true as const,
      certified: true as const,
      frozen: true as const,
      stable: true as const,
      owner: "DKL-6" as const,
      runtimeBehavior: "None" as const,
    }),
    Object.freeze({
      id: "DKL-6:8/Scope/Certification",
      name: "certification" as const,
      sourceIdentity: KnowledgeRepositoryCertificationId,
      sourceVersion: KnowledgeRepositoryCertificationVersion,
      sourceStatus: KnowledgeRepositoryCertificationStatus,
      order: 7,
      included: true as const,
      certified: true as const,
      frozen: true as const,
      stable: true as const,
      owner: "DKL-6" as const,
      runtimeBehavior: "None" as const,
    }),
    Object.freeze({
      id: "DKL-6:8/Scope/Freeze",
      name: "freeze" as const,
      sourceIdentity: "DKL-6:8/KnowledgeRepositoryFreeze",
      sourceVersion: "1.0.0",
      sourceStatus: "Frozen",
      order: 8,
      included: true as const,
      certified: true as const,
      frozen: true as const,
      stable: true as const,
      owner: "DKL-6" as const,
      runtimeBehavior: "None" as const,
    }),
  ]);

export const KnowledgeRepositoryFrozenComponents: readonly KnowledgeRepositoryFrozenComponent[] =
  Object.freeze([
    Object.freeze({
      id: "DKL-6:8/Component/KnowledgeRepositoryFoundation",
      name: "KnowledgeRepositoryFoundation",
      sourceIdentity: KnowledgeRepositoryFoundationId,
      sourceVersion: KnowledgeRepositoryFoundationVersion,
      namespace: KnowledgeRepositoryFoundationNamespace,
      sourceStatus: KnowledgeRepositoryFoundationStatus,
      certificationStatus: "Certified" as const,
      freezeStatus: "Frozen" as const,
      stability: "Stable" as const,
      owner: "DKL-6" as const,
      runtimeBehavior: "None" as const,
    }),
    Object.freeze({
      id: "DKL-6:8/Component/KnowledgeRepositoryRegistry",
      name: "KnowledgeRepositoryRegistry",
      sourceIdentity: KnowledgeRepositoryRegistryId,
      sourceVersion: KnowledgeRepositoryRegistryVersion,
      namespace: KnowledgeRepositoryRegistryNamespace,
      sourceStatus: KnowledgeRepositoryRegistryStatus,
      certificationStatus: "Certified" as const,
      freezeStatus: "Frozen" as const,
      stability: "Stable" as const,
      owner: "DKL-6" as const,
      runtimeBehavior: "None" as const,
    }),
    Object.freeze({
      id: "DKL-6:8/Component/KnowledgeRepositoryModel",
      name: "KnowledgeRepositoryModel",
      sourceIdentity: KnowledgeRepositoryModelId,
      sourceVersion: KnowledgeRepositoryModelVersion,
      namespace: KnowledgeRepositoryModelNamespace,
      sourceStatus: KnowledgeRepositoryModelStatus,
      certificationStatus: "Certified" as const,
      freezeStatus: "Frozen" as const,
      stability: "Stable" as const,
      owner: "DKL-6" as const,
      runtimeBehavior: "None" as const,
    }),
    Object.freeze({
      id: "DKL-6:8/Component/KnowledgeRepositoryValidation",
      name: "KnowledgeRepositoryValidation",
      sourceIdentity: KnowledgeRepositoryValidationId,
      sourceVersion: KnowledgeRepositoryValidationVersion,
      namespace: KnowledgeRepositoryValidationNamespace,
      sourceStatus: KnowledgeRepositoryValidationStatus,
      certificationStatus: "Certified" as const,
      freezeStatus: "Frozen" as const,
      stability: "Stable" as const,
      owner: "DKL-6" as const,
      runtimeBehavior: "None" as const,
    }),
    Object.freeze({
      id: "DKL-6:8/Component/KnowledgeRepositoryManifest",
      name: "KnowledgeRepositoryManifest",
      sourceIdentity: KnowledgeRepositoryManifestId,
      sourceVersion: KnowledgeRepositoryManifestVersion,
      namespace: KnowledgeRepositoryManifestNamespace,
      sourceStatus: KnowledgeRepositoryManifestStatus,
      certificationStatus: "Certified" as const,
      freezeStatus: "Frozen" as const,
      stability: "Stable" as const,
      owner: "DKL-6" as const,
      runtimeBehavior: "None" as const,
    }),
    Object.freeze({
      id: "DKL-6:8/Component/KnowledgeRepositoryPlatform",
      name: "KnowledgeRepositoryPlatform",
      sourceIdentity: KnowledgeRepositoryPlatformId,
      sourceVersion: KnowledgeRepositoryPlatformVersion,
      namespace: KnowledgeRepositoryPlatformNamespace,
      sourceStatus: KnowledgeRepositoryPlatformStatus,
      certificationStatus: "Certified" as const,
      freezeStatus: "Frozen" as const,
      stability: "Stable" as const,
      owner: "DKL-6" as const,
      runtimeBehavior: "None" as const,
    }),
    Object.freeze({
      id: "DKL-6:8/Component/KnowledgeRepositoryCertification",
      name: "KnowledgeRepositoryCertification",
      sourceIdentity: KnowledgeRepositoryCertificationId,
      sourceVersion: KnowledgeRepositoryCertificationVersion,
      namespace: KnowledgeRepositoryCertificationNamespace,
      sourceStatus: KnowledgeRepositoryCertificationStatus,
      certificationStatus: "Certified" as const,
      freezeStatus: "Frozen" as const,
      stability: "Stable" as const,
      owner: "DKL-6" as const,
      runtimeBehavior: "None" as const,
    }),
    Object.freeze({
      id: "DKL-6:8/Component/KnowledgeRepositoryFreeze",
      name: "KnowledgeRepositoryFreeze",
      sourceIdentity: "DKL-6:8/KnowledgeRepositoryFreeze",
      sourceVersion: "1.0.0",
      namespace: "nexora.dkl.repository.freeze",
      sourceStatus: "Frozen",
      certificationStatus: "Certified" as const,
      freezeStatus: "Frozen" as const,
      stability: "Stable" as const,
      owner: "DKL-6" as const,
      runtimeBehavior: "None" as const,
    }),
  ]);

/**
 * Canonical counts preserved from certified public summaries.
 * Derived by reference at aggregate composition time — values here document
 * the locked baseline for regression locks and gates.
 */
export const KnowledgeRepositoryFreezeCanonicalCountBaseline = Object.freeze({
  foundation: Object.freeze({
    capabilities: 9,
    contracts: 8,
    lifecycleStates: 7,
    policies: 6,
    publicApis: 6,
  }),
  registry: Object.freeze({
    entries: 103,
    groups: 16,
    publicApis: 8,
  }),
  model: Object.freeze({
    models: 52,
    relationships: 13,
    registryTraceabilityGroups: 14,
    publicApis: 8,
  }),
  validation: Object.freeze({
    categories: 10,
    rules: 40,
    passedRules: 40,
    failedRules: 0,
    gates: 10,
    passedGates: 10,
    failedGates: 0,
    publicApis: 8,
  }),
  manifest: Object.freeze({
    sections: 5,
    components: 5,
    dependencies: 11,
    boundaries: 18,
    compatibilityDeclarations: 12,
    guarantees: 16,
    completenessGates: 12,
    publicApisThroughManifest: 38,
  }),
  platform: Object.freeze({
    sections: 6,
    components: 6,
    dependencies: 15,
    compatibilityDeclarations: 14,
    boundaries: 18,
    guarantees: 18,
    readinessGates: 14,
    publicApisThroughPlatform: 46,
  }),
  certification: Object.freeze({
    scopeEntries: 7,
    criteria: 18,
    evidenceEntries: 16,
    compatibilityCertifications: 14,
    regressionProtections: 12,
    boundaryCertifications: 18,
    guarantees: 20,
    certificationGates: 15,
    publicApisThroughCertification: 54,
  }),
});
