/**
 * DKL-4:2 — Knowledge Modeling Registry Catalog.
 *
 * Immutable registrations for Foundation-declared Knowledge Modeling concepts.
 * Architecture definitions only — no object construction or runtime registry.
 *
 * Ownership: owned exclusively by DKL-4:2.
 */

import { KnowledgeModelingFoundation } from "./knowledgeModelingFoundation.ts";
import type { KnowledgeModelingRegistryEntry } from "./knowledgeModelingRegistryTypes.ts";

const OWNER = "DKL-4 Knowledge Modeling Registry";
const PHASE = "DKL-4:2";
const VISIBILITY = "Public" as const;
const LIFECYCLE = "Registered" as const;
const STABILITY = "Stable" as const;
const COMPATIBLE = "Compatible" as const;
const ADDITIVE = "AdditiveAllowed" as const;
const CLOSED = "Closed" as const;
const RESTRICTED = "Restricted" as const;
const FORBIDDEN = "Forbidden" as const;

export const KnowledgeModelingKnowledgeModelTypeRegistry: readonly KnowledgeModelingRegistryEntry[] =
  Object.freeze([
    Object.freeze({
      id: "km-reg-knowledge-model-type-canonical",
      name: "CanonicalKnowledgeModel",
      namespace: "nexora.dkl.knowledge-modeling.registry.knowledge-model.canonical",
      description: "Canonical immutable organizational knowledge model definition.",
      category: "KnowledgeModelType",
      owner: OWNER,
      sourcePhase: PHASE,
      lifecycleStatus: LIFECYCLE,
      stabilityStatus: STABILITY,
      compatibilityStatus: COMPATIBLE,
      extensionStatus: ADDITIVE,
      publicVisibility: VISIBILITY,
      tags: Object.freeze(["knowledge-model", "canonical", "metadata-only"]),
    }),
  ]);

export const KnowledgeModelingKnowledgeObjectTypeRegistry: readonly KnowledgeModelingRegistryEntry[] =
  Object.freeze([
    Object.freeze({
      id: "km-reg-knowledge-object-type-knowledge-model",
      name: "KnowledgeModel",
      namespace: "nexora.dkl.knowledge-modeling.registry.object.knowledge-model",
      description: "Registered Knowledge Model object type from DKL-4:1 contracts.",
      category: "KnowledgeObjectType",
      owner: OWNER,
      sourcePhase: PHASE,
      lifecycleStatus: LIFECYCLE,
      stabilityStatus: STABILITY,
      compatibilityStatus: COMPATIBLE,
      extensionStatus: ADDITIVE,
      publicVisibility: VISIBILITY,
      tags: Object.freeze(["knowledge-object", "model"]),
    }),
    Object.freeze({
      id: "km-reg-knowledge-object-type-knowledge-object",
      name: "KnowledgeObject",
      namespace: "nexora.dkl.knowledge-modeling.registry.object.knowledge-object",
      description: "Registered generic Knowledge Object type from DKL-4:1 contracts.",
      category: "KnowledgeObjectType",
      owner: OWNER,
      sourcePhase: PHASE,
      lifecycleStatus: LIFECYCLE,
      stabilityStatus: STABILITY,
      compatibilityStatus: COMPATIBLE,
      extensionStatus: ADDITIVE,
      publicVisibility: VISIBILITY,
      tags: Object.freeze(["knowledge-object"]),
    }),
    Object.freeze({
      id: "km-reg-knowledge-object-type-business-object",
      name: "BusinessObject",
      namespace: "nexora.dkl.knowledge-modeling.registry.object.business-object",
      description: "Registered Business Object definition type from DKL-4:1 contracts.",
      category: "KnowledgeObjectType",
      owner: OWNER,
      sourcePhase: PHASE,
      lifecycleStatus: LIFECYCLE,
      stabilityStatus: STABILITY,
      compatibilityStatus: COMPATIBLE,
      extensionStatus: ADDITIVE,
      publicVisibility: VISIBILITY,
      tags: Object.freeze(["knowledge-object", "business-object"]),
    }),
    Object.freeze({
      id: "km-reg-knowledge-object-type-entity",
      name: "Entity",
      namespace: "nexora.dkl.knowledge-modeling.registry.object.entity",
      description: "Registered Entity definition type from DKL-4:1 contracts.",
      category: "KnowledgeObjectType",
      owner: OWNER,
      sourcePhase: PHASE,
      lifecycleStatus: LIFECYCLE,
      stabilityStatus: STABILITY,
      compatibilityStatus: COMPATIBLE,
      extensionStatus: ADDITIVE,
      publicVisibility: VISIBILITY,
      tags: Object.freeze(["knowledge-object", "entity"]),
    }),
    Object.freeze({
      id: "km-reg-knowledge-object-type-relationship",
      name: "Relationship",
      namespace: "nexora.dkl.knowledge-modeling.registry.object.relationship",
      description: "Registered Relationship definition type from DKL-4:1 contracts.",
      category: "KnowledgeObjectType",
      owner: OWNER,
      sourcePhase: PHASE,
      lifecycleStatus: LIFECYCLE,
      stabilityStatus: STABILITY,
      compatibilityStatus: COMPATIBLE,
      extensionStatus: ADDITIVE,
      publicVisibility: VISIBILITY,
      tags: Object.freeze(["knowledge-object", "relationship"]),
    }),
    Object.freeze({
      id: "km-reg-knowledge-object-type-identity-node",
      name: "IdentityNode",
      namespace: "nexora.dkl.knowledge-modeling.registry.object.identity-node",
      description: "Registered Identity Node type from DKL-4:1 contracts.",
      category: "KnowledgeObjectType",
      owner: OWNER,
      sourcePhase: PHASE,
      lifecycleStatus: LIFECYCLE,
      stabilityStatus: STABILITY,
      compatibilityStatus: COMPATIBLE,
      extensionStatus: ADDITIVE,
      publicVisibility: VISIBILITY,
      tags: Object.freeze(["knowledge-object", "identity"]),
    }),
    Object.freeze({
      id: "km-reg-knowledge-object-type-metadata-descriptor",
      name: "MetadataDescriptor",
      namespace: "nexora.dkl.knowledge-modeling.registry.object.metadata-descriptor",
      description: "Registered Metadata Descriptor type from DKL-4:1 contracts.",
      category: "KnowledgeObjectType",
      owner: OWNER,
      sourcePhase: PHASE,
      lifecycleStatus: LIFECYCLE,
      stabilityStatus: STABILITY,
      compatibilityStatus: COMPATIBLE,
      extensionStatus: ADDITIVE,
      publicVisibility: VISIBILITY,
      tags: Object.freeze(["knowledge-object", "metadata"]),
    }),
    Object.freeze({
      id: "km-reg-knowledge-object-type-hierarchy-node",
      name: "HierarchyNode",
      namespace: "nexora.dkl.knowledge-modeling.registry.object.hierarchy-node",
      description: "Registered Hierarchy Node type from DKL-4:1 contracts.",
      category: "KnowledgeObjectType",
      owner: OWNER,
      sourcePhase: PHASE,
      lifecycleStatus: LIFECYCLE,
      stabilityStatus: STABILITY,
      compatibilityStatus: COMPATIBLE,
      extensionStatus: ADDITIVE,
      publicVisibility: VISIBILITY,
      tags: Object.freeze(["knowledge-object", "hierarchy"]),
    }),
    Object.freeze({
      id: "km-reg-knowledge-object-type-composition-node",
      name: "CompositionNode",
      namespace: "nexora.dkl.knowledge-modeling.registry.object.composition-node",
      description: "Registered Composition Node type from DKL-4:1 contracts.",
      category: "KnowledgeObjectType",
      owner: OWNER,
      sourcePhase: PHASE,
      lifecycleStatus: LIFECYCLE,
      stabilityStatus: STABILITY,
      compatibilityStatus: COMPATIBLE,
      extensionStatus: ADDITIVE,
      publicVisibility: VISIBILITY,
      tags: Object.freeze(["knowledge-object", "composition"]),
    }),
    Object.freeze({
      id: "km-reg-knowledge-object-type-reference-link",
      name: "ReferenceLink",
      namespace: "nexora.dkl.knowledge-modeling.registry.object.reference-link",
      description: "Registered Reference Link type from DKL-4:1 contracts.",
      category: "KnowledgeObjectType",
      owner: OWNER,
      sourcePhase: PHASE,
      lifecycleStatus: LIFECYCLE,
      stabilityStatus: STABILITY,
      compatibilityStatus: COMPATIBLE,
      extensionStatus: ADDITIVE,
      publicVisibility: VISIBILITY,
      tags: Object.freeze(["knowledge-object", "reference"]),
    }),
    Object.freeze({
      id: "km-reg-knowledge-object-type-semantic-structure",
      name: "SemanticStructure",
      namespace: "nexora.dkl.knowledge-modeling.registry.object.semantic-structure",
      description: "Registered Semantic Structure type from DKL-4:1 contracts.",
      category: "KnowledgeObjectType",
      owner: OWNER,
      sourcePhase: PHASE,
      lifecycleStatus: LIFECYCLE,
      stabilityStatus: STABILITY,
      compatibilityStatus: COMPATIBLE,
      extensionStatus: ADDITIVE,
      publicVisibility: VISIBILITY,
      tags: Object.freeze(["knowledge-object", "semantic-structure"]),
    }),
  ]);

export const KnowledgeModelingEntityTypeRegistry: readonly KnowledgeModelingRegistryEntry[] =
  Object.freeze([
    Object.freeze({
      id: "km-reg-entity-type-named",
      name: "NamedEntity",
      namespace: "nexora.dkl.knowledge-modeling.registry.entity.named",
      description: "Registered named entity definition type.",
      category: "EntityType",
      owner: OWNER,
      sourcePhase: PHASE,
      lifecycleStatus: LIFECYCLE,
      stabilityStatus: STABILITY,
      compatibilityStatus: COMPATIBLE,
      extensionStatus: ADDITIVE,
      publicVisibility: VISIBILITY,
      tags: Object.freeze(["entity", "named"]),
    }),
    Object.freeze({
      id: "km-reg-entity-type-typed",
      name: "TypedEntity",
      namespace: "nexora.dkl.knowledge-modeling.registry.entity.typed",
      description: "Registered typed entity definition type.",
      category: "EntityType",
      owner: OWNER,
      sourcePhase: PHASE,
      lifecycleStatus: LIFECYCLE,
      stabilityStatus: STABILITY,
      compatibilityStatus: COMPATIBLE,
      extensionStatus: ADDITIVE,
      publicVisibility: VISIBILITY,
      tags: Object.freeze(["entity", "typed"]),
    }),
    Object.freeze({
      id: "km-reg-entity-type-composite",
      name: "CompositeEntity",
      namespace: "nexora.dkl.knowledge-modeling.registry.entity.composite",
      description: "Registered composite entity definition type.",
      category: "EntityType",
      owner: OWNER,
      sourcePhase: PHASE,
      lifecycleStatus: LIFECYCLE,
      stabilityStatus: STABILITY,
      compatibilityStatus: COMPATIBLE,
      extensionStatus: ADDITIVE,
      publicVisibility: VISIBILITY,
      tags: Object.freeze(["entity", "composite"]),
    }),
    Object.freeze({
      id: "km-reg-entity-type-reference",
      name: "ReferenceEntity",
      namespace: "nexora.dkl.knowledge-modeling.registry.entity.reference",
      description: "Registered reference entity definition type.",
      category: "EntityType",
      owner: OWNER,
      sourcePhase: PHASE,
      lifecycleStatus: LIFECYCLE,
      stabilityStatus: STABILITY,
      compatibilityStatus: COMPATIBLE,
      extensionStatus: ADDITIVE,
      publicVisibility: VISIBILITY,
      tags: Object.freeze(["entity", "reference"]),
    }),
    Object.freeze({
      id: "km-reg-entity-type-abstract",
      name: "AbstractEntity",
      namespace: "nexora.dkl.knowledge-modeling.registry.entity.abstract",
      description: "Registered abstract entity definition type.",
      category: "EntityType",
      owner: OWNER,
      sourcePhase: PHASE,
      lifecycleStatus: LIFECYCLE,
      stabilityStatus: STABILITY,
      compatibilityStatus: COMPATIBLE,
      extensionStatus: ADDITIVE,
      publicVisibility: VISIBILITY,
      tags: Object.freeze(["entity", "abstract"]),
    }),
  ]);

export const KnowledgeModelingIdentityTypeRegistry: readonly KnowledgeModelingRegistryEntry[] =
  Object.freeze([
    Object.freeze({
      id: "km-reg-identity-type-platform",
      name: "PlatformIdentity",
      namespace: "nexora.dkl.knowledge-modeling.registry.identity.platform",
      description: "Registered platform-scoped knowledge identity.",
      category: "IdentityType",
      owner: OWNER,
      sourcePhase: PHASE,
      lifecycleStatus: LIFECYCLE,
      stabilityStatus: STABILITY,
      compatibilityStatus: COMPATIBLE,
      extensionStatus: CLOSED,
      publicVisibility: VISIBILITY,
      tags: Object.freeze(["identity", "platform"]),
    }),
    Object.freeze({
      id: "km-reg-identity-type-model",
      name: "ModelIdentity",
      namespace: "nexora.dkl.knowledge-modeling.registry.identity.model",
      description: "Registered model-scoped knowledge identity.",
      category: "IdentityType",
      owner: OWNER,
      sourcePhase: PHASE,
      lifecycleStatus: LIFECYCLE,
      stabilityStatus: STABILITY,
      compatibilityStatus: COMPATIBLE,
      extensionStatus: CLOSED,
      publicVisibility: VISIBILITY,
      tags: Object.freeze(["identity", "model"]),
    }),
    Object.freeze({
      id: "km-reg-identity-type-object",
      name: "ObjectIdentity",
      namespace: "nexora.dkl.knowledge-modeling.registry.identity.object",
      description: "Registered object-scoped knowledge identity.",
      category: "IdentityType",
      owner: OWNER,
      sourcePhase: PHASE,
      lifecycleStatus: LIFECYCLE,
      stabilityStatus: STABILITY,
      compatibilityStatus: COMPATIBLE,
      extensionStatus: CLOSED,
      publicVisibility: VISIBILITY,
      tags: Object.freeze(["identity", "object"]),
    }),
    Object.freeze({
      id: "km-reg-identity-type-entity",
      name: "EntityIdentity",
      namespace: "nexora.dkl.knowledge-modeling.registry.identity.entity",
      description: "Registered entity-scoped knowledge identity.",
      category: "IdentityType",
      owner: OWNER,
      sourcePhase: PHASE,
      lifecycleStatus: LIFECYCLE,
      stabilityStatus: STABILITY,
      compatibilityStatus: COMPATIBLE,
      extensionStatus: CLOSED,
      publicVisibility: VISIBILITY,
      tags: Object.freeze(["identity", "entity"]),
    }),
    Object.freeze({
      id: "km-reg-identity-type-relationship",
      name: "RelationshipIdentity",
      namespace: "nexora.dkl.knowledge-modeling.registry.identity.relationship",
      description: "Registered relationship-scoped knowledge identity.",
      category: "IdentityType",
      owner: OWNER,
      sourcePhase: PHASE,
      lifecycleStatus: LIFECYCLE,
      stabilityStatus: STABILITY,
      compatibilityStatus: COMPATIBLE,
      extensionStatus: CLOSED,
      publicVisibility: VISIBILITY,
      tags: Object.freeze(["identity", "relationship"]),
    }),
    Object.freeze({
      id: "km-reg-identity-type-reference",
      name: "ReferenceIdentity",
      namespace: "nexora.dkl.knowledge-modeling.registry.identity.reference",
      description: "Registered reference-scoped knowledge identity.",
      category: "IdentityType",
      owner: OWNER,
      sourcePhase: PHASE,
      lifecycleStatus: LIFECYCLE,
      stabilityStatus: STABILITY,
      compatibilityStatus: COMPATIBLE,
      extensionStatus: CLOSED,
      publicVisibility: VISIBILITY,
      tags: Object.freeze(["identity", "reference"]),
    }),
  ]);

export const KnowledgeModelingMetadataTypeRegistry: readonly KnowledgeModelingRegistryEntry[] =
  Object.freeze([
    Object.freeze({
      id: "km-reg-metadata-type-descriptive",
      name: "DescriptiveMetadata",
      namespace: "nexora.dkl.knowledge-modeling.registry.metadata.descriptive",
      description: "Registered descriptive knowledge metadata type.",
      category: "MetadataType",
      owner: OWNER,
      sourcePhase: PHASE,
      lifecycleStatus: LIFECYCLE,
      stabilityStatus: STABILITY,
      compatibilityStatus: COMPATIBLE,
      extensionStatus: ADDITIVE,
      publicVisibility: VISIBILITY,
      tags: Object.freeze(["metadata", "descriptive"]),
    }),
    Object.freeze({
      id: "km-reg-metadata-type-structural",
      name: "StructuralMetadata",
      namespace: "nexora.dkl.knowledge-modeling.registry.metadata.structural",
      description: "Registered structural knowledge metadata type.",
      category: "MetadataType",
      owner: OWNER,
      sourcePhase: PHASE,
      lifecycleStatus: LIFECYCLE,
      stabilityStatus: STABILITY,
      compatibilityStatus: COMPATIBLE,
      extensionStatus: ADDITIVE,
      publicVisibility: VISIBILITY,
      tags: Object.freeze(["metadata", "structural"]),
    }),
    Object.freeze({
      id: "km-reg-metadata-type-provenance",
      name: "ProvenanceMetadata",
      namespace: "nexora.dkl.knowledge-modeling.registry.metadata.provenance",
      description: "Registered provenance knowledge metadata type.",
      category: "MetadataType",
      owner: OWNER,
      sourcePhase: PHASE,
      lifecycleStatus: LIFECYCLE,
      stabilityStatus: STABILITY,
      compatibilityStatus: COMPATIBLE,
      extensionStatus: ADDITIVE,
      publicVisibility: VISIBILITY,
      tags: Object.freeze(["metadata", "provenance"]),
    }),
    Object.freeze({
      id: "km-reg-metadata-type-semantic",
      name: "SemanticMetadata",
      namespace: "nexora.dkl.knowledge-modeling.registry.metadata.semantic",
      description: "Registered semantic knowledge metadata type.",
      category: "MetadataType",
      owner: OWNER,
      sourcePhase: PHASE,
      lifecycleStatus: LIFECYCLE,
      stabilityStatus: STABILITY,
      compatibilityStatus: COMPATIBLE,
      extensionStatus: ADDITIVE,
      publicVisibility: VISIBILITY,
      tags: Object.freeze(["metadata", "semantic"]),
    }),
    Object.freeze({
      id: "km-reg-metadata-type-lifecycle",
      name: "LifecycleMetadata",
      namespace: "nexora.dkl.knowledge-modeling.registry.metadata.lifecycle",
      description: "Registered lifecycle knowledge metadata type.",
      category: "MetadataType",
      owner: OWNER,
      sourcePhase: PHASE,
      lifecycleStatus: LIFECYCLE,
      stabilityStatus: STABILITY,
      compatibilityStatus: COMPATIBLE,
      extensionStatus: ADDITIVE,
      publicVisibility: VISIBILITY,
      tags: Object.freeze(["metadata", "lifecycle"]),
    }),
    Object.freeze({
      id: "km-reg-metadata-type-compatibility",
      name: "CompatibilityMetadata",
      namespace: "nexora.dkl.knowledge-modeling.registry.metadata.compatibility",
      description: "Registered compatibility knowledge metadata type.",
      category: "MetadataType",
      owner: OWNER,
      sourcePhase: PHASE,
      lifecycleStatus: LIFECYCLE,
      stabilityStatus: STABILITY,
      compatibilityStatus: COMPATIBLE,
      extensionStatus: ADDITIVE,
      publicVisibility: VISIBILITY,
      tags: Object.freeze(["metadata", "compatibility"]),
    }),
  ]);

export const KnowledgeModelingHierarchyTypeRegistry: readonly KnowledgeModelingRegistryEntry[] =
  Object.freeze([
    Object.freeze({
      id: "km-reg-hierarchy-type-taxonomy",
      name: "TaxonomyHierarchy",
      namespace: "nexora.dkl.knowledge-modeling.registry.hierarchy.taxonomy",
      description: "Registered taxonomy hierarchy definition type.",
      category: "HierarchyType",
      owner: OWNER,
      sourcePhase: PHASE,
      lifecycleStatus: LIFECYCLE,
      stabilityStatus: STABILITY,
      compatibilityStatus: COMPATIBLE,
      extensionStatus: ADDITIVE,
      publicVisibility: VISIBILITY,
      tags: Object.freeze(["hierarchy", "taxonomy"]),
    }),
    Object.freeze({
      id: "km-reg-hierarchy-type-part-whole",
      name: "PartWholeHierarchy",
      namespace: "nexora.dkl.knowledge-modeling.registry.hierarchy.part-whole",
      description: "Registered part-whole hierarchy definition type.",
      category: "HierarchyType",
      owner: OWNER,
      sourcePhase: PHASE,
      lifecycleStatus: LIFECYCLE,
      stabilityStatus: STABILITY,
      compatibilityStatus: COMPATIBLE,
      extensionStatus: ADDITIVE,
      publicVisibility: VISIBILITY,
      tags: Object.freeze(["hierarchy", "part-whole"]),
    }),
    Object.freeze({
      id: "km-reg-hierarchy-type-organizational",
      name: "OrganizationalHierarchy",
      namespace: "nexora.dkl.knowledge-modeling.registry.hierarchy.organizational",
      description: "Registered organizational hierarchy definition type.",
      category: "HierarchyType",
      owner: OWNER,
      sourcePhase: PHASE,
      lifecycleStatus: LIFECYCLE,
      stabilityStatus: STABILITY,
      compatibilityStatus: COMPATIBLE,
      extensionStatus: ADDITIVE,
      publicVisibility: VISIBILITY,
      tags: Object.freeze(["hierarchy", "organizational"]),
    }),
    Object.freeze({
      id: "km-reg-hierarchy-type-classification",
      name: "ClassificationHierarchy",
      namespace: "nexora.dkl.knowledge-modeling.registry.hierarchy.classification",
      description: "Registered classification hierarchy definition type.",
      category: "HierarchyType",
      owner: OWNER,
      sourcePhase: PHASE,
      lifecycleStatus: LIFECYCLE,
      stabilityStatus: STABILITY,
      compatibilityStatus: COMPATIBLE,
      extensionStatus: ADDITIVE,
      publicVisibility: VISIBILITY,
      tags: Object.freeze(["hierarchy", "classification"]),
    }),
    Object.freeze({
      id: "km-reg-hierarchy-type-containment",
      name: "ContainmentHierarchy",
      namespace: "nexora.dkl.knowledge-modeling.registry.hierarchy.containment",
      description: "Registered containment hierarchy definition type.",
      category: "HierarchyType",
      owner: OWNER,
      sourcePhase: PHASE,
      lifecycleStatus: LIFECYCLE,
      stabilityStatus: STABILITY,
      compatibilityStatus: COMPATIBLE,
      extensionStatus: ADDITIVE,
      publicVisibility: VISIBILITY,
      tags: Object.freeze(["hierarchy", "containment"]),
    }),
  ]);

export const KnowledgeModelingCompositionTypeRegistry: readonly KnowledgeModelingRegistryEntry[] =
  Object.freeze([
    Object.freeze({
      id: "km-reg-composition-type-aggregate",
      name: "AggregateComposition",
      namespace: "nexora.dkl.knowledge-modeling.registry.composition.aggregate",
      description: "Registered aggregate composition definition type.",
      category: "CompositionType",
      owner: OWNER,
      sourcePhase: PHASE,
      lifecycleStatus: LIFECYCLE,
      stabilityStatus: STABILITY,
      compatibilityStatus: COMPATIBLE,
      extensionStatus: ADDITIVE,
      publicVisibility: VISIBILITY,
      tags: Object.freeze(["composition", "aggregate"]),
    }),
    Object.freeze({
      id: "km-reg-composition-type-composite",
      name: "CompositeComposition",
      namespace: "nexora.dkl.knowledge-modeling.registry.composition.composite",
      description: "Registered composite composition definition type.",
      category: "CompositionType",
      owner: OWNER,
      sourcePhase: PHASE,
      lifecycleStatus: LIFECYCLE,
      stabilityStatus: STABILITY,
      compatibilityStatus: COMPATIBLE,
      extensionStatus: ADDITIVE,
      publicVisibility: VISIBILITY,
      tags: Object.freeze(["composition", "composite"]),
    }),
    Object.freeze({
      id: "km-reg-composition-type-collection",
      name: "CollectionComposition",
      namespace: "nexora.dkl.knowledge-modeling.registry.composition.collection",
      description: "Registered collection composition definition type.",
      category: "CompositionType",
      owner: OWNER,
      sourcePhase: PHASE,
      lifecycleStatus: LIFECYCLE,
      stabilityStatus: STABILITY,
      compatibilityStatus: COMPATIBLE,
      extensionStatus: ADDITIVE,
      publicVisibility: VISIBILITY,
      tags: Object.freeze(["composition", "collection"]),
    }),
    Object.freeze({
      id: "km-reg-composition-type-bundle",
      name: "BundleComposition",
      namespace: "nexora.dkl.knowledge-modeling.registry.composition.bundle",
      description: "Registered bundle composition definition type.",
      category: "CompositionType",
      owner: OWNER,
      sourcePhase: PHASE,
      lifecycleStatus: LIFECYCLE,
      stabilityStatus: STABILITY,
      compatibilityStatus: COMPATIBLE,
      extensionStatus: ADDITIVE,
      publicVisibility: VISIBILITY,
      tags: Object.freeze(["composition", "bundle"]),
    }),
    Object.freeze({
      id: "km-reg-composition-type-view",
      name: "ViewComposition",
      namespace: "nexora.dkl.knowledge-modeling.registry.composition.view",
      description: "Registered view composition definition type.",
      category: "CompositionType",
      owner: OWNER,
      sourcePhase: PHASE,
      lifecycleStatus: LIFECYCLE,
      stabilityStatus: STABILITY,
      compatibilityStatus: COMPATIBLE,
      extensionStatus: ADDITIVE,
      publicVisibility: VISIBILITY,
      tags: Object.freeze(["composition", "view"]),
    }),
  ]);

export const KnowledgeModelingReferenceTypeRegistry: readonly KnowledgeModelingRegistryEntry[] =
  Object.freeze([
    Object.freeze({
      id: "km-reg-reference-type-upstream-understanding",
      name: "UpstreamUnderstandingReference",
      namespace: "nexora.dkl.knowledge-modeling.registry.reference.upstream-understanding",
      description: "Registered reference to DKL-3 understanding metadata.",
      category: "ReferenceType",
      owner: OWNER,
      sourcePhase: PHASE,
      lifecycleStatus: LIFECYCLE,
      stabilityStatus: STABILITY,
      compatibilityStatus: COMPATIBLE,
      extensionStatus: CLOSED,
      publicVisibility: VISIBILITY,
      tags: Object.freeze(["reference", "dkl-3"]),
    }),
    Object.freeze({
      id: "km-reg-reference-type-cross-model",
      name: "CrossModelReference",
      namespace: "nexora.dkl.knowledge-modeling.registry.reference.cross-model",
      description: "Registered cross-model reference definition type.",
      category: "ReferenceType",
      owner: OWNER,
      sourcePhase: PHASE,
      lifecycleStatus: LIFECYCLE,
      stabilityStatus: STABILITY,
      compatibilityStatus: COMPATIBLE,
      extensionStatus: ADDITIVE,
      publicVisibility: VISIBILITY,
      tags: Object.freeze(["reference", "cross-model"]),
    }),
    Object.freeze({
      id: "km-reg-reference-type-external-registry",
      name: "ExternalRegistryReference",
      namespace: "nexora.dkl.knowledge-modeling.registry.reference.external-registry",
      description: "Registered external registry reference definition type.",
      category: "ReferenceType",
      owner: OWNER,
      sourcePhase: PHASE,
      lifecycleStatus: LIFECYCLE,
      stabilityStatus: STABILITY,
      compatibilityStatus: RESTRICTED,
      extensionStatus: ADDITIVE,
      publicVisibility: VISIBILITY,
      tags: Object.freeze(["reference", "external-registry"]),
    }),
    Object.freeze({
      id: "km-reg-reference-type-identity-alias",
      name: "IdentityAliasReference",
      namespace: "nexora.dkl.knowledge-modeling.registry.reference.identity-alias",
      description: "Registered identity alias reference definition type.",
      category: "ReferenceType",
      owner: OWNER,
      sourcePhase: PHASE,
      lifecycleStatus: LIFECYCLE,
      stabilityStatus: STABILITY,
      compatibilityStatus: COMPATIBLE,
      extensionStatus: CLOSED,
      publicVisibility: VISIBILITY,
      tags: Object.freeze(["reference", "identity-alias"]),
    }),
    Object.freeze({
      id: "km-reg-reference-type-semantic-equivalence",
      name: "SemanticEquivalenceReference",
      namespace: "nexora.dkl.knowledge-modeling.registry.reference.semantic-equivalence",
      description: "Registered semantic equivalence reference definition type.",
      category: "ReferenceType",
      owner: OWNER,
      sourcePhase: PHASE,
      lifecycleStatus: LIFECYCLE,
      stabilityStatus: STABILITY,
      compatibilityStatus: COMPATIBLE,
      extensionStatus: ADDITIVE,
      publicVisibility: VISIBILITY,
      tags: Object.freeze(["reference", "semantic-equivalence"]),
    }),
  ]);

export const KnowledgeModelingSemanticStructureTypeRegistry: readonly KnowledgeModelingRegistryEntry[] =
  Object.freeze([
    Object.freeze({
      id: "km-reg-semantic-structure-type-system",
      name: "TypeSystem",
      namespace: "nexora.dkl.knowledge-modeling.registry.semantic-structure.type-system",
      description: "Registered semantic type-system contract.",
      category: "SemanticStructureType",
      owner: OWNER,
      sourcePhase: PHASE,
      lifecycleStatus: LIFECYCLE,
      stabilityStatus: STABILITY,
      compatibilityStatus: COMPATIBLE,
      extensionStatus: ADDITIVE,
      publicVisibility: VISIBILITY,
      tags: Object.freeze(["semantic-structure", "type-system"]),
    }),
    Object.freeze({
      id: "km-reg-semantic-structure-role-system",
      name: "RoleSystem",
      namespace: "nexora.dkl.knowledge-modeling.registry.semantic-structure.role-system",
      description: "Registered semantic role-system contract.",
      category: "SemanticStructureType",
      owner: OWNER,
      sourcePhase: PHASE,
      lifecycleStatus: LIFECYCLE,
      stabilityStatus: STABILITY,
      compatibilityStatus: COMPATIBLE,
      extensionStatus: ADDITIVE,
      publicVisibility: VISIBILITY,
      tags: Object.freeze(["semantic-structure", "role-system"]),
    }),
    Object.freeze({
      id: "km-reg-semantic-structure-constraint-system",
      name: "ConstraintSystem",
      namespace: "nexora.dkl.knowledge-modeling.registry.semantic-structure.constraint-system",
      description: "Registered semantic constraint-system contract.",
      category: "SemanticStructureType",
      owner: OWNER,
      sourcePhase: PHASE,
      lifecycleStatus: LIFECYCLE,
      stabilityStatus: STABILITY,
      compatibilityStatus: COMPATIBLE,
      extensionStatus: ADDITIVE,
      publicVisibility: VISIBILITY,
      tags: Object.freeze(["semantic-structure", "constraint-system"]),
    }),
    Object.freeze({
      id: "km-reg-semantic-structure-hierarchy-system",
      name: "HierarchySystem",
      namespace: "nexora.dkl.knowledge-modeling.registry.semantic-structure.hierarchy-system",
      description: "Registered semantic hierarchy-system contract.",
      category: "SemanticStructureType",
      owner: OWNER,
      sourcePhase: PHASE,
      lifecycleStatus: LIFECYCLE,
      stabilityStatus: STABILITY,
      compatibilityStatus: COMPATIBLE,
      extensionStatus: ADDITIVE,
      publicVisibility: VISIBILITY,
      tags: Object.freeze(["semantic-structure", "hierarchy-system"]),
    }),
    Object.freeze({
      id: "km-reg-semantic-structure-composition-system",
      name: "CompositionSystem",
      namespace: "nexora.dkl.knowledge-modeling.registry.semantic-structure.composition-system",
      description: "Registered semantic composition-system contract.",
      category: "SemanticStructureType",
      owner: OWNER,
      sourcePhase: PHASE,
      lifecycleStatus: LIFECYCLE,
      stabilityStatus: STABILITY,
      compatibilityStatus: COMPATIBLE,
      extensionStatus: ADDITIVE,
      publicVisibility: VISIBILITY,
      tags: Object.freeze(["semantic-structure", "composition-system"]),
    }),
    Object.freeze({
      id: "km-reg-semantic-structure-reference-system",
      name: "ReferenceSystem",
      namespace: "nexora.dkl.knowledge-modeling.registry.semantic-structure.reference-system",
      description: "Registered semantic reference-system contract.",
      category: "SemanticStructureType",
      owner: OWNER,
      sourcePhase: PHASE,
      lifecycleStatus: LIFECYCLE,
      stabilityStatus: STABILITY,
      compatibilityStatus: COMPATIBLE,
      extensionStatus: ADDITIVE,
      publicVisibility: VISIBILITY,
      tags: Object.freeze(["semantic-structure", "reference-system"]),
    }),
  ]);

export const KnowledgeModelingLifecycleStateRegistry: readonly KnowledgeModelingRegistryEntry[] =
  Object.freeze(
    KnowledgeModelingFoundation.lifecycle.states.map((state) =>
      Object.freeze({
        id: `km-reg-lifecycle-state-${state.toLowerCase()}`,
        name: state,
        namespace: `nexora.dkl.knowledge-modeling.registry.lifecycle.${state.toLowerCase()}`,
        description: `Registered Knowledge Modeling lifecycle state: ${state}.`,
        category: "LifecycleState" as const,
        owner: OWNER,
        sourcePhase: PHASE,
        lifecycleStatus: LIFECYCLE,
        stabilityStatus: STABILITY,
        compatibilityStatus: COMPATIBLE,
        extensionStatus: CLOSED,
        publicVisibility: VISIBILITY,
        tags: Object.freeze(["lifecycle", state]),
      }),
    ),
  );

export const KnowledgeModelingOwnershipDeclarationRegistry: readonly KnowledgeModelingRegistryEntry[] =
  Object.freeze([
    Object.freeze({
      id: "km-reg-ownership-declaration-owns-vocabulary-registration",
      name: "OwnsVocabularyRegistration",
      namespace: "nexora.dkl.knowledge-modeling.registry.ownership.vocabulary",
      description: "DKL-4:2 owns registration of Knowledge Modeling vocabulary.",
      category: "OwnershipDeclaration",
      owner: OWNER,
      sourcePhase: PHASE,
      lifecycleStatus: LIFECYCLE,
      stabilityStatus: STABILITY,
      compatibilityStatus: COMPATIBLE,
      extensionStatus: CLOSED,
      publicVisibility: VISIBILITY,
      tags: Object.freeze(["ownership", "owns"]),
    }),
    Object.freeze({
      id: "km-reg-ownership-declaration-does-not-own-runtime-creation",
      name: "DoesNotOwnRuntimeCreation",
      namespace: "nexora.dkl.knowledge-modeling.registry.ownership.runtime-creation",
      description: "DKL-4:2 does not own runtime object or relationship creation.",
      category: "OwnershipDeclaration",
      owner: OWNER,
      sourcePhase: PHASE,
      lifecycleStatus: LIFECYCLE,
      stabilityStatus: STABILITY,
      compatibilityStatus: FORBIDDEN,
      extensionStatus: CLOSED,
      publicVisibility: VISIBILITY,
      tags: Object.freeze(["ownership", "does-not-own"]),
    }),
  ]);

export const KnowledgeModelingBoundaryDeclarationRegistry: readonly KnowledgeModelingRegistryEntry[] =
  Object.freeze([
    Object.freeze({
      id: "km-reg-boundary-declaration-metadata-only",
      name: "MetadataOnlyBoundary",
      namespace: "nexora.dkl.knowledge-modeling.registry.boundary.metadata-only",
      description: "Registry entries are metadata only and never runtime objects.",
      category: "BoundaryDeclaration",
      owner: OWNER,
      sourcePhase: PHASE,
      lifecycleStatus: LIFECYCLE,
      stabilityStatus: STABILITY,
      compatibilityStatus: COMPATIBLE,
      extensionStatus: CLOSED,
      publicVisibility: VISIBILITY,
      tags: Object.freeze(["boundary", "metadata-only"]),
    }),
    Object.freeze({
      id: "km-reg-boundary-declaration-no-graph-execution",
      name: "NoGraphExecutionBoundary",
      namespace: "nexora.dkl.knowledge-modeling.registry.boundary.no-graph-execution",
      description: "Registry relationships do not enforce graph behavior or traversal.",
      category: "BoundaryDeclaration",
      owner: OWNER,
      sourcePhase: PHASE,
      lifecycleStatus: LIFECYCLE,
      stabilityStatus: STABILITY,
      compatibilityStatus: FORBIDDEN,
      extensionStatus: CLOSED,
      publicVisibility: VISIBILITY,
      tags: Object.freeze(["boundary", "graph-execution-forbidden"]),
    }),
  ]);

export const KnowledgeModelingExtensionPolicyRegistry: readonly KnowledgeModelingRegistryEntry[] =
  Object.freeze(
    KnowledgeModelingFoundation.contracts.extensionPolicies.map((policy) =>
      Object.freeze({
        id: `km-reg-extension-policy-${policy.policyId.toLowerCase()}`,
        name: policy.name,
        namespace: `nexora.dkl.knowledge-modeling.registry.extension.${policy.policyId.toLowerCase()}`,
        description: policy.description,
        category: "ExtensionPolicy" as const,
        owner: OWNER,
        sourcePhase: PHASE,
        lifecycleStatus: LIFECYCLE,
        stabilityStatus: STABILITY,
        compatibilityStatus: policy.status === "Forbidden" ? FORBIDDEN : COMPATIBLE,
        extensionStatus: policy.status === "MigrationRequired" ? "MigrationRequired" as const : ADDITIVE,
        publicVisibility: VISIBILITY,
        tags: Object.freeze(["extension-policy", policy.status]),
      }),
    ),
  );

export const KnowledgeModelingCompatibilityPolicyRegistry: readonly KnowledgeModelingRegistryEntry[] =
  Object.freeze(
    KnowledgeModelingFoundation.contracts.compatibilityPolicies.map((policy) =>
      Object.freeze({
        id: `km-reg-compatibility-policy-${policy.policyId.toLowerCase()}`,
        name: policy.name,
        namespace: `nexora.dkl.knowledge-modeling.registry.compatibility.${policy.policyId.toLowerCase()}`,
        description: policy.description,
        category: "CompatibilityPolicy" as const,
        owner: OWNER,
        sourcePhase: PHASE,
        lifecycleStatus: LIFECYCLE,
        stabilityStatus: STABILITY,
        compatibilityStatus: policy.status,
        extensionStatus: CLOSED,
        publicVisibility: VISIBILITY,
        tags: Object.freeze(["compatibility-policy", policy.status]),
      }),
    ),
  );

export const KnowledgeModelingDependencyDeclarationRegistry: readonly KnowledgeModelingRegistryEntry[] =
  Object.freeze([
    Object.freeze({
      id: "km-reg-dependency-declaration-dkl41-foundation",
      name: "KnowledgeModelingFoundationDependency",
      namespace: "nexora.dkl.knowledge-modeling.registry.dependency.foundation",
      description: "DKL-4:2 depends only on the DKL-4:1 public foundation aggregate.",
      category: "DependencyDeclaration",
      owner: OWNER,
      sourcePhase: PHASE,
      lifecycleStatus: LIFECYCLE,
      stabilityStatus: STABILITY,
      compatibilityStatus: COMPATIBLE,
      extensionStatus: CLOSED,
      publicVisibility: VISIBILITY,
      tags: Object.freeze(["dependency", "dkl-4:1"]),
    }),
  ]);

export const KnowledgeModelingPublicFoundationApiRegistry: readonly KnowledgeModelingRegistryEntry[] =
  Object.freeze([
    Object.freeze({
      id: "km-reg-public-api-foundation",
      name: "KnowledgeModelingFoundation",
      namespace: "nexora.dkl.knowledge-modeling.registry.public-api.foundation",
      description: "Registered public aggregate API from DKL-4:1.",
      category: "PublicFoundationApi",
      owner: OWNER,
      sourcePhase: PHASE,
      lifecycleStatus: LIFECYCLE,
      stabilityStatus: STABILITY,
      compatibilityStatus: COMPATIBLE,
      extensionStatus: CLOSED,
      publicVisibility: VISIBILITY,
      tags: Object.freeze(["public-api", "aggregate"]),
    }),
    Object.freeze({
      id: "km-reg-public-api-version",
      name: "KnowledgeModelingFoundationVersion",
      namespace: "nexora.dkl.knowledge-modeling.registry.public-api.version",
      description: "Registered public version API from DKL-4:1.",
      category: "PublicFoundationApi",
      owner: OWNER,
      sourcePhase: PHASE,
      lifecycleStatus: LIFECYCLE,
      stabilityStatus: STABILITY,
      compatibilityStatus: COMPATIBLE,
      extensionStatus: CLOSED,
      publicVisibility: VISIBILITY,
      tags: Object.freeze(["public-api", "version"]),
    }),
    Object.freeze({
      id: "km-reg-public-api-identity",
      name: "KnowledgeModelingFoundationIdentity",
      namespace: "nexora.dkl.knowledge-modeling.registry.public-api.identity",
      description: "Registered public identity API from DKL-4:1.",
      category: "PublicFoundationApi",
      owner: OWNER,
      sourcePhase: PHASE,
      lifecycleStatus: LIFECYCLE,
      stabilityStatus: STABILITY,
      compatibilityStatus: COMPATIBLE,
      extensionStatus: CLOSED,
      publicVisibility: VISIBILITY,
      tags: Object.freeze(["public-api", "identity"]),
    }),
    Object.freeze({
      id: "km-reg-public-api-contracts",
      name: "KnowledgeModelingContracts",
      namespace: "nexora.dkl.knowledge-modeling.registry.public-api.contracts",
      description: "Registered public contracts API from DKL-4:1.",
      category: "PublicFoundationApi",
      owner: OWNER,
      sourcePhase: PHASE,
      lifecycleStatus: LIFECYCLE,
      stabilityStatus: STABILITY,
      compatibilityStatus: COMPATIBLE,
      extensionStatus: CLOSED,
      publicVisibility: VISIBILITY,
      tags: Object.freeze(["public-api", "contracts"]),
    }),
    Object.freeze({
      id: "km-reg-public-api-ownership",
      name: "KnowledgeModelingOwnership",
      namespace: "nexora.dkl.knowledge-modeling.registry.public-api.ownership",
      description: "Registered public ownership API from DKL-4:1.",
      category: "PublicFoundationApi",
      owner: OWNER,
      sourcePhase: PHASE,
      lifecycleStatus: LIFECYCLE,
      stabilityStatus: STABILITY,
      compatibilityStatus: COMPATIBLE,
      extensionStatus: CLOSED,
      publicVisibility: VISIBILITY,
      tags: Object.freeze(["public-api", "ownership"]),
    }),
    Object.freeze({
      id: "km-reg-public-api-boundaries",
      name: "KnowledgeModelingBoundaries",
      namespace: "nexora.dkl.knowledge-modeling.registry.public-api.boundaries",
      description: "Registered public boundaries API from DKL-4:1.",
      category: "PublicFoundationApi",
      owner: OWNER,
      sourcePhase: PHASE,
      lifecycleStatus: LIFECYCLE,
      stabilityStatus: STABILITY,
      compatibilityStatus: COMPATIBLE,
      extensionStatus: CLOSED,
      publicVisibility: VISIBILITY,
      tags: Object.freeze(["public-api", "boundaries"]),
    }),
    Object.freeze({
      id: "km-reg-public-api-lifecycle",
      name: "KnowledgeModelingLifecycle",
      namespace: "nexora.dkl.knowledge-modeling.registry.public-api.lifecycle",
      description: "Registered public lifecycle API from DKL-4:1.",
      category: "PublicFoundationApi",
      owner: OWNER,
      sourcePhase: PHASE,
      lifecycleStatus: LIFECYCLE,
      stabilityStatus: STABILITY,
      compatibilityStatus: COMPATIBLE,
      extensionStatus: CLOSED,
      publicVisibility: VISIBILITY,
      tags: Object.freeze(["public-api", "lifecycle"]),
    }),
    Object.freeze({
      id: "km-reg-public-api-dependencies",
      name: "KnowledgeModelingDependencies",
      namespace: "nexora.dkl.knowledge-modeling.registry.public-api.dependencies",
      description: "Registered public dependencies API from DKL-4:1.",
      category: "PublicFoundationApi",
      owner: OWNER,
      sourcePhase: PHASE,
      lifecycleStatus: LIFECYCLE,
      stabilityStatus: STABILITY,
      compatibilityStatus: COMPATIBLE,
      extensionStatus: CLOSED,
      publicVisibility: VISIBILITY,
      tags: Object.freeze(["public-api", "dependencies"]),
    }),
  ]);
