/**
 * DKL-7:8 — Knowledge Services Freeze Compatibility.
 *
 * Exactly eighteen immutable Compatible + Frozen declarations.
 * Runtime authorization remains None.
 *
 * Ownership: owned exclusively by DKL-7:8.
 */

import { KnowledgeServicesFreezeChainIds } from "./knowledgeServicesFreezeRegistry.ts";
import type { KnowledgeServicesFreezeCompatibilityDeclaration } from "./knowledgeServicesFreezeTypes.ts";

const ids = KnowledgeServicesFreezeChainIds;

const compat = (
  key: string,
  subject: string,
  direction: string,
  compatibilityType: string,
  canonicalPath: string,
  protectedLockReferences: readonly string[],
  ownershipConstraint: string,
  boundaryConstraint: string,
  changePolicy: KnowledgeServicesFreezeCompatibilityDeclaration["changePolicy"],
  publicIndexRelevance: string,
  order: number,
): KnowledgeServicesFreezeCompatibilityDeclaration =>
  Object.freeze({
    compatibilityId: `DKL-7:8/Compatibility/${key}`,
    subject,
    direction,
    compatibilityType,
    status: "Compatible" as const,
    freezeStatus: "Frozen" as const,
    runtimeAuthorization: "None" as const,
    canonicalPath,
    protectedLockReferences: Object.freeze([...protectedLockReferences]),
    ownershipConstraint,
    boundaryConstraint,
    changePolicy,
    publicIndexRelevance,
    deterministicOrder: order,
  });

/** Exactly eighteen Freeze compatibility declarations. */
export const KnowledgeServicesFreezeCompatibility: readonly KnowledgeServicesFreezeCompatibilityDeclaration[] =
  Object.freeze([
    compat(
      "Foundation",
      "Foundation frozen compatibility",
      "Backward",
      "PhaseFreeze",
      `Freeze → … → ${ids.foundationId}`,
      Object.freeze(["LOCK-KS-OWNERSHIP", "LOCK-KS-BOUNDARY"]),
      "DKL-7 ownership unchanged",
      "29 prohibited surfaces preserved",
      "Forbidden",
      "RequiredPublicIndexUpstream",
      1,
    ),
    compat(
      "Registry",
      "Registry frozen compatibility",
      "Backward",
      "PhaseFreeze",
      `Freeze → … → ${ids.registryId}`,
      Object.freeze([
        "LOCK-KS-SERVICE-INVENTORY",
        "LOCK-KS-CAPABILITY-INVENTORY",
        "LOCK-KS-CONTRACT-INVENTORY",
      ]),
      "Registry inventories frozen",
      "Read-only boundaries preserved",
      "Forbidden",
      "RequiredPublicIndexUpstream",
      2,
    ),
    compat(
      "Model",
      "Model frozen compatibility",
      "Backward",
      "PhaseFreeze",
      `Freeze → … → ${ids.modelId}`,
      Object.freeze(["LOCK-KS-MODEL-INVENTORY"]),
      "Model inventory 79 frozen",
      "No mutation modes",
      "Forbidden",
      "RequiredPublicIndexUpstream",
      3,
    ),
    compat(
      "Validation",
      "Validation frozen compatibility",
      "Backward",
      "PhaseFreeze",
      `Freeze → … → ${ids.validationId}`,
      Object.freeze(["LOCK-KS-VALIDATION-STATE"]),
      "Validation Pass state frozen",
      "No runtime validation",
      "Forbidden",
      "RequiredPublicIndexUpstream",
      4,
    ),
    compat(
      "Manifest",
      "Manifest frozen compatibility",
      "Backward",
      "PhaseFreeze",
      `Freeze → … → ${ids.manifestId}`,
      Object.freeze(["LOCK-KS-CERTIFICATION-BASELINE"]),
      "Manifest inventory 447 frozen",
      "ManifestComplete preserved",
      "Forbidden",
      "RequiredPublicIndexUpstream",
      5,
    ),
    compat(
      "Platform",
      "Platform frozen compatibility",
      "Backward",
      "PhaseFreeze",
      `Freeze → Certification → ${ids.platformId}`,
      Object.freeze(["LOCK-KS-CERTIFICATION-BASELINE"]),
      "Platform inventory 527 frozen",
      "PlatformComplete preserved",
      "Forbidden",
      "RequiredPublicIndexUpstream",
      6,
    ),
    compat(
      "Certification",
      "Certification frozen compatibility",
      "Direct",
      "PhaseFreeze",
      `Freeze → ${ids.certificationId}`,
      Object.freeze(["LOCK-KS-CERTIFICATION-BASELINE"]),
      "Certification inventory 137 frozen",
      "Certified Pass preserved",
      "Forbidden",
      "RequiredPublicIndexUpstream",
      7,
    ),
    compat(
      "DKL6PublicIndex",
      "DKL-6 indirect compatibility",
      "Indirect",
      "UpstreamCompatibility",
      `Freeze → … → ${ids.dkl6PublicIndexId}`,
      Object.freeze(["LOCK-KS-DEPENDENCY-CHAIN"]),
      "DKL-6 ownership outside DKL-7",
      "No DKL-6 reconstruction",
      "Forbidden",
      "RequiredPublicIndexUpstream",
      8,
    ),
    compat(
      "FreezeSelfConsistency",
      "Freeze self-consistency compatibility",
      "Internal",
      "SelfConsistency",
      "Freeze identity and registry",
      Object.freeze(["LOCK-KS-PUBLIC-API"]),
      "Freeze owns freeze metadata only",
      "No recursive self-embedding",
      "Forbidden",
      "DirectPublicIndexInput",
      9,
    ),
    compat(
      "FuturePublicIndex",
      "Future Public Index compatibility",
      "Forward",
      "FuturePhase",
      "Public Index → Freeze → Certification → …",
      Object.freeze(["LOCK-KS-DEPENDENCY-CHAIN", "LOCK-KS-PUBLIC-API"]),
      "Public Index consumes Freeze only",
      "No Certification bypass",
      "AdditiveOnly",
      "DefinesPublicIndexInput",
      10,
    ),
    compat(
      "ExecutiveEngine",
      "Executive Engine future-consumer compatibility",
      "Consumer",
      "FutureConsumer",
      "Executive Engine → Public Index → Freeze → …",
      Object.freeze(["LOCK-KS-COMPATIBILITY"]),
      "Engine does not own Knowledge Services",
      "No direct Freeze import",
      "AdditiveOnly",
      "ConsumerPathForPublicIndex",
      11,
    ),
    compat(
      "Advisor",
      "Advisor future-consumer compatibility",
      "Consumer",
      "FutureConsumer",
      "Advisor → Public Index → Freeze → …",
      Object.freeze(["LOCK-KS-COMPATIBILITY"]),
      "Advisor does not own Knowledge Services",
      "No direct Freeze import",
      "AdditiveOnly",
      "ConsumerPathForPublicIndex",
      12,
    ),
    compat(
      "ApprovedInternal",
      "Approved internal future-consumer compatibility",
      "Consumer",
      "FutureConsumer",
      "Approved internal → Public Index → Freeze → …",
      Object.freeze(["LOCK-KS-COMPATIBILITY"]),
      "Internal consumers use Public Index only",
      "Runtime authorization None",
      "AdditiveOnly",
      "ConsumerPathForPublicIndex",
      13,
    ),
    compat(
      "BackwardDKL71To77",
      "Backward compatibility through DKL-7:1–7:7",
      "Backward",
      "ChainCompatibility",
      "Freeze → Certification → Platform → … → Foundation",
      Object.freeze(["LOCK-KS-DEPENDENCY-CHAIN"]),
      "No reconstruction of prior phases",
      "Boundaries unchanged",
      "Forbidden",
      "RequiredPublicIndexUpstream",
      14,
    ),
    compat(
      "AdditiveExtension",
      "Additive extension compatibility",
      "Extension",
      "AdditiveCompatibility",
      "Controlled additive Freeze extensions",
      Object.freeze(["LOCK-KS-PUBLIC-API"]),
      "Ownership preserved",
      "Boundaries preserved",
      "AdditiveOnly",
      "GuidesPublicIndexChangePolicy",
      15,
    ),
    compat(
      "VersionedReCertification",
      "Versioned re-certification compatibility",
      "Versioning",
      "VersionedCompatibility",
      "Breaking changes require re-certify and re-freeze",
      Object.freeze(["LOCK-KS-CERTIFICATION-BASELINE"]),
      "Ownership preserved across versions",
      "Boundaries preserved across versions",
      "VersionedReCertificationRequired",
      "GuidesPublicIndexVersioning",
      16,
    ),
    compat(
      "PublicApiPreservation",
      "Public API preservation compatibility",
      "Surface",
      "ApiCompatibility",
      "Freeze public API identities",
      Object.freeze(["LOCK-KS-PUBLIC-API"]),
      "API ownership remains DKL-7",
      "No runtime service APIs",
      "Forbidden",
      "RequiredPublicIndexSurfaceInput",
      17,
    ),
    compat(
      "StableReleasePreparation",
      "Stable release preparation compatibility",
      "Forward",
      "ReleasePreparation",
      "Public Index preparation through Freeze",
      Object.freeze(["LOCK-KS-RUNTIME-PROHIBITION"]),
      "No Released claim at Freeze",
      "No consumer runtime access",
      "AdditiveOnly",
      "PreparesPublicIndex",
      18,
    ),
  ]);
