/**
 * DKL-7:1 — Knowledge Services Boundaries.
 *
 * Explicit immutable boundary declarations separating Knowledge Services from
 * runtime execution, repositories, databases, networking, AI, Engine, Advisor,
 * Scene, UI, and other prohibited surfaces.
 *
 * Ownership: owned exclusively by DKL-7:1.
 */

export const KNOWLEDGE_SERVICES_PROHIBITED_SURFACES = Object.freeze([
  "Runtime execution",
  "Repository implementation",
  "SQL",
  "NoSQL",
  "Vector databases",
  "Graph databases",
  "Caching implementation",
  "API implementation",
  "REST endpoints",
  "HTTP clients",
  "Authentication",
  "Authorization",
  "External connectors",
  "Business logic",
  "Executive reasoning",
  "Planning",
  "Decision generation",
  "Scene generation",
  "Visualization",
  "UI",
  "Logging",
  "Telemetry",
  "Reflection",
  "Dynamic loading",
  "Dependency injection",
  "Threading",
  "Queues",
  "Background jobs",
  "Network communication",
] as const);

/** Canonical immutable boundary declarations. */
export const KnowledgeServicesBoundaries = Object.freeze({
  boundariesId: "DKL-7:1/KnowledgeServicesBoundaries",
  sourcePhase: "DKL-7:1" as const,
  consumes: Object.freeze(["DKL-6 Public Index"] as const),
  provides: Object.freeze(["Knowledge Services Foundation"] as const),
  prohibitedSurfaces: KNOWLEDGE_SERVICES_PROHIBITED_SURFACES,
  prohibitedSurfaceCount: KNOWLEDGE_SERVICES_PROHIBITED_SURFACES.length,
  readOnlyAccessLayer: true,
  createsKnowledge: false,
  modifiesKnowledge: false,
  performsExecutiveReasoning: false,
  consumesDkl6PublicIndex: true,
  runtimeExecution: false,
  repositoryImplementation: false,
  implementsSql: false,
  implementsNoSql: false,
  implementsVectorDatabases: false,
  implementsGraphDatabases: false,
  cachingImplementation: false,
  apiImplementation: false,
  restEndpoints: false,
  httpClients: false,
  authentication: false,
  authorization: false,
  externalConnectors: false,
  businessLogic: false,
  planning: false,
  decisionGeneration: false,
  sceneGeneration: false,
  visualization: false,
  rendersUi: false,
  logging: false,
  telemetry: false,
  reflection: false,
  dynamicLoading: false,
  dependencyInjection: false,
  threading: false,
  queues: false,
  backgroundJobs: false,
  networkCommunication: false,
  narratesAdvisor: false,
  executesEngineReasoning: false,
  createsBusinessObjects: false,
  performsAiReasoning: false,
  architecturalPosition: Object.freeze({
    upstream: Object.freeze([
      "DKL-6 Knowledge Repository (Public Index only)",
      "DKL-5 Knowledge Validation (via DKL-6)",
      "DKL-4 Knowledge Modeling (via DKL-6)",
    ]),
    platform: "DKL-7 Knowledge Services",
    downstream: Object.freeze([
      "DKL-7 Registry",
      "DKL-7 Model",
      "DKL-7 Validation",
      "DKL-7 Manifest",
      "Executive Engine (restricted consumer)",
      "Advisor (restricted consumer)",
      "Future internal platform services",
    ]),
  }),
  metadataOnly: true,
  knowledgeServicesArchitectureOnly: true,
  serviceImplementationExcluded: true,
  repositoryImplementationExcluded: true,
  runtimeBehaviorExcluded: true,
  immutable: true,
  deterministic: true,
});
