/** EX-3:5 Manifest capabilities (descriptive metadata only). */

import type { ExecutiveTimelineExperienceManifestCapability } from "./executiveTimelineExperienceManifestTypes.ts";

export const ExecutiveTimelineExperienceManifestCapabilities = Object.freeze([
  Object.freeze({
    capabilityId: "EX-3:5/Capability/TimelineNavigation",
    name: "TimelineNavigation",
    order: 1,
    statement: "Describes Timeline navigation metadata for Platform consumers.",
    descriptiveOnly: true,
    executable: false,
    metadataOnly: true,
    immutable: true,
  }),
  Object.freeze({
    capabilityId: "EX-3:5/Capability/TimelinePositioning",
    name: "TimelinePositioning",
    order: 2,
    statement: "Describes Timeline positioning metadata without runtime engines.",
    descriptiveOnly: true,
    executable: false,
    metadataOnly: true,
    immutable: true,
  }),
  Object.freeze({
    capabilityId: "EX-3:5/Capability/TimelinePlaybackMetadata",
    name: "TimelinePlaybackMetadata",
    order: 3,
    statement: "Publishes playback-related metadata without playback execution.",
    descriptiveOnly: true,
    executable: false,
    metadataOnly: true,
    immutable: true,
  }),
  Object.freeze({
    capabilityId: "EX-3:5/Capability/TimelineHistoryMetadata",
    name: "TimelineHistoryMetadata",
    order: 4,
    statement: "Publishes history metadata derived from the Timeline Model.",
    descriptiveOnly: true,
    executable: false,
    metadataOnly: true,
    immutable: true,
  }),
  Object.freeze({
    capabilityId: "EX-3:5/Capability/TimelineSnapshotMetadata",
    name: "TimelineSnapshotMetadata",
    order: 5,
    statement: "Publishes snapshot metadata without persistence or capture runtime.",
    descriptiveOnly: true,
    executable: false,
    metadataOnly: true,
    immutable: true,
  }),
  Object.freeze({
    capabilityId: "EX-3:5/Capability/TimelineContextMetadata",
    name: "TimelineContextMetadata",
    order: 6,
    statement: "Publishes context metadata for Timeline Experience consumers.",
    descriptiveOnly: true,
    executable: false,
    metadataOnly: true,
    immutable: true,
  }),
  Object.freeze({
    capabilityId: "EX-3:5/Capability/TimelineSynchronizationMetadata",
    name: "TimelineSynchronizationMetadata",
    order: 7,
    statement:
      "Publishes synchronization metadata without Stage or Journal sync runtime.",
    descriptiveOnly: true,
    executable: false,
    metadataOnly: true,
    immutable: true,
  }),
  Object.freeze({
    capabilityId: "EX-3:5/Capability/TimelineMarkerMetadata",
    name: "TimelineMarkerMetadata",
    order: 8,
    statement: "Publishes marker metadata from Registry and Model catalogues.",
    descriptiveOnly: true,
    executable: false,
    metadataOnly: true,
    immutable: true,
  }),
  Object.freeze({
    capabilityId: "EX-3:5/Capability/TimelineEventMetadata",
    name: "TimelineEventMetadata",
    order: 9,
    statement: "Publishes event metadata without event processing runtime.",
    descriptiveOnly: true,
    executable: false,
    metadataOnly: true,
    immutable: true,
  }),
  Object.freeze({
    capabilityId: "EX-3:5/Capability/TimelineCursorMetadata",
    name: "TimelineCursorMetadata",
    order: 10,
    statement: "Publishes cursor metadata without interactive cursor engines.",
    descriptiveOnly: true,
    executable: false,
    metadataOnly: true,
    immutable: true,
  }),
  Object.freeze({
    capabilityId: "EX-3:5/Capability/TimelineViewportMetadata",
    name: "TimelineViewportMetadata",
    order: 11,
    statement: "Publishes viewport metadata without rendering surfaces.",
    descriptiveOnly: true,
    executable: false,
    metadataOnly: true,
    immutable: true,
  }),
  Object.freeze({
    capabilityId: "EX-3:5/Capability/TimelineRelationshipMetadata",
    name: "TimelineRelationshipMetadata",
    order: 12,
    statement: "Publishes Model relationship metadata for structural consumers.",
    descriptiveOnly: true,
    executable: false,
    metadataOnly: true,
    immutable: true,
  }),
  Object.freeze({
    capabilityId: "EX-3:5/Capability/TimelineSchemaMetadata",
    name: "TimelineSchemaMetadata",
    order: 13,
    statement: "Publishes Model schema metadata without schema engines.",
    descriptiveOnly: true,
    executable: false,
    metadataOnly: true,
    immutable: true,
  }),
  Object.freeze({
    capabilityId: "EX-3:5/Capability/TimelineValidationMetadata",
    name: "TimelineValidationMetadata",
    order: 14,
    statement:
      "Publishes Validation categories and rules as descriptive metadata only.",
    descriptiveOnly: true,
    executable: false,
    metadataOnly: true,
    immutable: true,
  }),
  Object.freeze({
    capabilityId: "EX-3:5/Capability/TimelineAggregatePublication",
    name: "TimelineAggregatePublication",
    order: 15,
    statement:
      "Publishes the consolidated Timeline Experience aggregate for Platform.",
    descriptiveOnly: true,
    executable: false,
    metadataOnly: true,
    immutable: true,
  }),
  Object.freeze({
    capabilityId: "EX-3:5/Capability/TimelineConsumerPublication",
    name: "TimelineConsumerPublication",
    order: 16,
    statement:
      "Publishes consumer-facing Manifest metadata without Platform implementation.",
    descriptiveOnly: true,
    executable: false,
    metadataOnly: true,
    immutable: true,
  }),
] as const satisfies readonly ExecutiveTimelineExperienceManifestCapability[]);

export const ExecutiveTimelineExperienceManifestCapabilityCount = 16 as const;
