import assert from "node:assert/strict"; import test from "node:test";
import { createExecutiveMemoryLocalStorageProvider, type ExecutiveMemoryKeyValueStorage } from "./executiveMemoryLocalStorageProvider.ts";
import { createExecutiveMemoryStore } from "./executiveMemoryStore.ts"; import { createExecutiveMemoryRepository } from "./executiveMemoryRepository.ts";
import { initializeExecutiveMemoryStorageEngine, resetExecutiveMemoryStorageEngineForTests, createExecutiveMemory, getExecutiveMemoryById, updateExecutiveMemory, archiveExecutiveMemory } from "./executiveMemoryStorageEngine.ts";
import { registerExecutiveMemoryProvider, resetExecutiveMemoryPlatformForTests } from "./executiveMemoryPlatform.ts";
import { createCanonicalDurableExecutiveMemory, retrieveRelevantDurableExecutiveMemory, buildDurableExecutiveAdvisorMemoryContext, supersedeDurableExecutiveMemory, DURABLE_EXECUTIVE_MEMORY_BOUNDARY } from "./durableExecutiveMemory.ts";

class FakeStorage implements ExecutiveMemoryKeyValueStorage { data = new Map<string, string>(); getItem(k: string) { return this.data.get(k) ?? null; } setItem(k: string, v: string) { this.data.set(k, v); } removeItem(k: string) { this.data.delete(k); } }
const input = (id: string, kind: "decision" | "outcome" | "learning" = "decision") => ({ id, workspaceId: "w", kind, title: id, summary: `Summary ${id}`, narrative: `Narrative ${id}`, status: "active", source: "canonical-decision-runtime", owner: "manager", confidence: .9, createdAt: "2026-08-15T00:00:00Z", updatedAt: "2026-08-15T00:00:00Z", subjectReferences: [{ type: "decision" as const, targetId: "decision-a", label: "Decision A" }], provenance: ["event:approved"], ...(kind === "decision" ? { decision: { decisionId: "decision-a", rationale: "Capacity is required", status: "approved" as const } } : {}), ...(kind === "outcome" ? { outcome: { outcomeId: "outcome-a", description: "Capacity increased", achieved: true, measuredAt: "2026-09-01" } } : {}), ...(kind === "learning" ? { lesson: { lessonId: "lesson-a", summary: "Engage procurement earlier", context: "Execution review" } } : {}) });
test.beforeEach(() => { resetExecutiveMemoryPlatformForTests(); resetExecutiveMemoryStorageEngineForTests(); registerExecutiveMemoryProvider({ providerId: "durable-executive-memory", label: "Durable Executive Memory", version: "1.0.0", supportedCategories: ["goal", "problem", "risk_reference", "scenario", "decision", "decision_rationale", "execution", "outcome", "learning", "business_context"] }, "2026-08-15T00:00:00Z"); });

test("DM boundary separates durable history from session/current Runtime", () => assert.deepEqual(DURABLE_EXECUTIVE_MEMORY_BOUNDARY, { storesConversationTranscript: false, storesSessionContext: false, ownsCurrentExecutionTruth: false, proactiveMonitoring: false, externalIntegrations: false, persistenceAuthority: "APP-4/ExecutiveMemoryStorageEngine", retrievalAuthority: "APP-4/ExecutiveMemoryRetrieval", advisorRole: "historical-context-only" }));
test("canonical record includes identity, references, time, source, confidence, status, and provenance", () => { const record = createCanonicalDurableExecutiveMemory(input("memory-a")); assert.equal(record.id, "memory-a"); assert.equal(record.references[0]?.targetId, "decision-a"); assert.equal(record.header.sourceModule, "canonical-decision-runtime"); assert.equal(record.confidence?.score, .9); assert.equal(record.metadata.customMetadata.status, "active"); assert.equal(record.metadata.customMetadata.provenance, "event:approved"); assert.equal(record.decision?.rationale, "Capacity is required"); assert.ok(Object.isFrozen(record)); });
test("conversation transcripts cannot be persisted without explicit subject/provenance", () => assert.throws(() => createCanonicalDurableExecutiveMemory({ ...input("chat"), subjectReferences: [], provenance: [] }), /provenance-and-subject-required/));
test("durable provider survives provider recreation/application restart", () => { const storage = new FakeStorage(); const first = createExecutiveMemoryRepository(createExecutiveMemoryStore(createExecutiveMemoryLocalStorageProvider(storage))); first.createExecutiveMemory(createCanonicalDurableExecutiveMemory(input("persisted")), input("x").createdAt); const provider = createExecutiveMemoryLocalStorageProvider(storage); provider.initialize(); const second = createExecutiveMemoryRepository(createExecutiveMemoryStore(provider)); assert.equal(second.getExecutiveMemoryById("persisted")?.record.header.summary, "Summary persisted"); });
test("durable provider supports update and archive lifecycle", () => { const storage = new FakeStorage(); const provider = createExecutiveMemoryLocalStorageProvider(storage); provider.initialize(); const repo = createExecutiveMemoryRepository(createExecutiveMemoryStore(provider)); repo.createExecutiveMemory(createCanonicalDurableExecutiveMemory(input("lifecycle")), "2026-08-15"); assert.equal(repo.updateExecutiveMemory("lifecycle", { header: { summary: "Updated" } }, "2026-08-16").data?.storageRevision, 2); assert.equal(repo.archiveExecutiveMemory("lifecycle", "2026-08-17").data?.lifecycle, "archived"); });
test("canonical engine retrieval returns bounded relevant Decision→Outcome→Learning chain", () => { resetExecutiveMemoryStorageEngineForTests(); initializeExecutiveMemoryStorageEngine("2026-08-15"); for (const [id, kind] of [["decision-memory", "decision"], ["outcome-memory", "outcome"], ["learning-memory", "learning"]] as const) createExecutiveMemory(createCanonicalDurableExecutiveMemory(input(id, kind))); createExecutiveMemory(createCanonicalDurableExecutiveMemory({ ...input("unrelated"), subjectReferences: [{ type: "goal", targetId: "goal-other", label: "Other" }] })); const found = retrieveRelevantDurableExecutiveMemory({ workspaceId: "w", currentSubjectId: "decision-a", limit: 3 }); assert.deepEqual(found.map((x) => x.record.id).sort(), ["decision-memory", "learning-memory", "outcome-memory"]); });
test("workspace isolation and archived exclusion are mandatory", () => { resetExecutiveMemoryStorageEngineForTests(); initializeExecutiveMemoryStorageEngine("2026-08-15"); createExecutiveMemory(createCanonicalDurableExecutiveMemory(input("active"))); createExecutiveMemory(createCanonicalDurableExecutiveMemory({ ...input("other"), workspaceId: "other" })); createExecutiveMemory(createCanonicalDurableExecutiveMemory(input("archived"))); archiveExecutiveMemory("archived", "2026-08-16"); assert.deepEqual(retrieveRelevantDurableExecutiveMemory({ workspaceId: "w", currentSubjectId: "decision-a" }).map((x) => x.record.id), ["active"]); });
test("Advisor context distinguishes current facts and cited historical memory", () => { resetExecutiveMemoryStorageEngineForTests(); initializeExecutiveMemoryStorageEngine("2026-08-15"); createExecutiveMemory(createCanonicalDurableExecutiveMemory(input("history"))); const context = buildDurableExecutiveAdvisorMemoryContext({ workspaceId: "w", currentSubjectId: "decision-a", currentFacts: ["Execution is currently blocked"] }); assert.equal(context.boundary, "current-facts-override-history"); assert.deepEqual(context.currentFacts, ["Execution is currently blocked"]); assert.equal(context.historicalMemories[0]?.memoryId, "history"); assert.deepEqual(context.historicalMemories[0]?.provenance, ["event:approved"]); });
test("conflicting active historical records remain separate evidence, never current truth", () => { resetExecutiveMemoryStorageEngineForTests(); initializeExecutiveMemoryStorageEngine("2026-08-15"); createExecutiveMemory(createCanonicalDurableExecutiveMemory(input("v1"))); createExecutiveMemory(createCanonicalDurableExecutiveMemory({ ...input("v2"), summary: "Conflicting historical account", confidence: .5 })); const context = buildDurableExecutiveAdvisorMemoryContext({ workspaceId: "w", currentSubjectId: "decision-a", currentFacts: ["Canonical Runtime says completed"] }); assert.equal(context.historicalMemories.length, 2); assert.equal(context.conflicts[0]?.reason, "conflicting-historical-accounts"); assert.equal(context.currentFacts[0], "Canonical Runtime says completed"); });
test("supersede preserves replacement and archives obsolete provenance", () => { initializeExecutiveMemoryStorageEngine("2026-08-15"); createExecutiveMemory(createCanonicalDurableExecutiveMemory(input("old"))); const result = supersedeDurableExecutiveMemory({ obsoleteId: "old", replacement: { ...input("new"), provenance: ["supersedes:old"] }, timestamp: "2026-08-16" }); assert.equal(result.success, true); assert.equal(getExecutiveMemoryById("old")?.lifecycle, "archived"); assert.equal(getExecutiveMemoryById("old")?.record.metadata.customMetadata.supersededBy, "new"); assert.equal(getExecutiveMemoryById("new")?.lifecycle, "active"); });
test("engine create/update/archive chain remains canonical", () => { resetExecutiveMemoryStorageEngineForTests(); initializeExecutiveMemoryStorageEngine("2026-08-15"); assert.equal(createExecutiveMemory(createCanonicalDurableExecutiveMemory(input("chain"))).success, true); assert.equal(updateExecutiveMemory("chain", { body: { narrative: "Outcome observed" } }, "2026-08-16").success, true); assert.equal(getExecutiveMemoryById("chain")?.record.body.narrative, "Outcome observed"); assert.equal(archiveExecutiveMemory("chain", "2026-08-17").success, true); });
