/**
 * EIL-1:1 — Executive Integration Boundaries.
 *
 * Explicit immutable boundaries separating coordination metadata from
 * reasoning, transport, persistence, UI, and runtime execution surfaces.
 *
 * Ownership: owned exclusively by EIL-1:1.
 */

export const EXECUTIVE_INTEGRATION_PROHIBITED_SURFACES = Object.freeze([
  "AI",
  "Reasoning",
  "Executive Decision",
  "Planning",
  "Knowledge Modeling",
  "Business Objects",
  "Database",
  "Persistence",
  "Caching",
  "Authentication",
  "Authorization",
  "REST",
  "HTTP",
  "GraphQL",
  "WebSocket",
  "Queue",
  "Message Bus",
  "SDK",
  "MCP",
  "Telegram",
  "Slack",
  "Teams",
  "WhatsApp",
  "Voice",
  "Email",
  "Transport protocols",
  "UI",
  "React",
  "Next.js",
  "Advisor",
  "Scene",
  "Director",
  "EVE",
  "Execution logic",
  "Runtime orchestration",
  "Internal BUS phase imports",
  "Internal OPS phase imports",
  "Internal ENG phase imports",
  "Internal DKL phase imports",
  "Adapters",
  "Factories",
  "Dependency injection",
  "Network calls",
  "Storage writes",
  "Business logic",
] as const);

/** Canonical immutable Executive Integration boundary declarations. */
export const ExecutiveIntegrationBoundaries = Object.freeze({
  boundariesId: "EIL-1:1/ExecutiveIntegrationBoundaries",
  sourcePhase: "EIL-1:1" as const,
  consumes: Object.freeze([
    "BUS Public Index",
    "OPS Public Index",
    "ENG Public Index",
    "DKL Public Index",
  ] as const),
  provides: Object.freeze([
    "Executive Integration Foundation",
  ] as const),
  prohibitedSurfaces: EXECUTIVE_INTEGRATION_PROHIBITED_SURFACES,
  prohibitedSurfaceCount: EXECUTIVE_INTEGRATION_PROHIBITED_SURFACES.length,
  dependencyRules: Object.freeze([
    "PublicIndexOnly",
    "CertifiedPlatformsOnly",
    "NoInternalPhaseImport",
    "NoReconstruction",
    "NoCircularPlatformOwnership",
  ] as const),
  extensionPolicy: Object.freeze([
    "AdditivePublicIndexOnly",
    "NoInternalPhaseImport",
    "NoRuntimeIntroduction",
    "NoBusinessReasoning",
  ] as const),
  runtimeEnforcement: false as const,
  layerSeparation: Object.freeze({
    eilOwnsCoordinationMetadataOnly: true as const,
    busOwnsBusinessIntelligenceInternals: true as const,
    opsOwnsOperationsInternals: true as const,
    engOwnsEngineReasoningAndDecisions: true as const,
    dklOwnsKnowledgeInternals: true as const,
    neaOwnsChannelsAndTransport: true as const,
    advisorSceneOwnPresentation: true as const,
  }),
  performsAi: false as const,
  performsReasoning: false as const,
  performsExecutiveDecision: false as const,
  performsPlanning: false as const,
  modelsKnowledge: false as const,
  constructsBusinessObjects: false as const,
  accessesDatabase: false as const,
  persists: false as const,
  caches: false as const,
  authenticates: false as const,
  authorizes: false as const,
  implementsRest: false as const,
  implementsHttp: false as const,
  implementsGraphql: false as const,
  implementsWebsocket: false as const,
  implementsQueue: false as const,
  implementsMessageBus: false as const,
  shipsSdk: false as const,
  implementsMcp: false as const,
  connectsTelegram: false as const,
  connectsSlack: false as const,
  connectsTeams: false as const,
  connectsWhatsapp: false as const,
  connectsVoice: false as const,
  connectsEmail: false as const,
  implementsTransport: false as const,
  uiBehavior: false as const,
  reactBehavior: false as const,
  nextJsBehavior: false as const,
  advisorBehavior: false as const,
  sceneBehavior: false as const,
  directorBehavior: false as const,
  eveBehavior: false as const,
  executionLogic: false as const,
  runtimeOrchestration: false as const,
  importsInternalPhases: false as const,
  metadataOnly: true as const,
  immutable: true as const,
  deterministic: true as const,
});
