/**
 * EIL-1:3 — Integration Relationship Models.
 *
 * Canonical descriptive relationships between domain models.
 * Metadata only — no relationship resolution or execution.
 *
 * Ownership: owned exclusively by EIL-1:3.
 */

import { IntegrationRegistryIdentity } from "./integrationRegistry.ts";
import type {
  IntegrationRegistryReference,
  IntegrationRelationshipModel,
  IntegrationRelationshipType,
} from "./integrationModelTypes.ts";

const registryRef = (
  collection: IntegrationRegistryReference["collection"],
  entryKey: string,
): IntegrationRegistryReference =>
  Object.freeze({
    registryId: IntegrationRegistryIdentity.canonicalId,
    registryNamespace: IntegrationRegistryIdentity.namespace,
    entryPoint: "integrationRegistry.ts" as const,
    collection,
    entryKey,
    preservesCanonicalReference: true as const,
    duplicatesRegistryValue: false as const,
    metadataOnly: true as const,
    immutable: true as const,
  });

const relationship = (
  key: string,
  relationshipType: IntegrationRelationshipType,
  canonicalName: string,
  description: string,
  sourceModelKey: string,
  targetModelKey: string,
  collection: IntegrationRegistryReference["collection"],
  entryKey: string,
  ordinal: number,
  tags: readonly string[],
): IntegrationRelationshipModel =>
  Object.freeze({
    relationshipId: `EIL-1:3/Relationship/${key}` as const,
    relationshipType,
    canonicalKey: key,
    canonicalName,
    description,
    sourceModelKey,
    targetModelKey,
    sourceRegistryReference: registryRef(collection, entryKey),
    ownership: "EIL-1:3" as const,
    lifecycle: "Verified" as const,
    version: "1.0.0" as const,
    ordinal,
    tags: Object.freeze([...tags]),
    resolvesRuntime: false as const,
    metadataOnly: true as const,
    immutable: true as const,
  });

/**
 * Required architectural relationships plus supporting relationship vocabulary.
 * Descriptive metadata only.
 */
export const IntegrationRelationshipModels: readonly IntegrationRelationshipModel[] =
  Object.freeze([
    relationship(
      "PlatformMappedToContract",
      "mappedTo",
      "Platform → Contract",
      "Platform model maps to contract model metadata.",
      "IntegrationPlatform",
      "IntegrationContract",
      "contracts",
      "PlatformContract",
      1,
      Object.freeze(["required", "platform", "contract"]),
    ),
    relationship(
      "PlatformMappedToCapability",
      "mappedTo",
      "Platform → Capability",
      "Platform model maps to capability model metadata.",
      "IntegrationPlatform",
      "IntegrationCapability",
      "capabilities",
      "PlatformIntegration",
      2,
      Object.freeze(["required", "platform", "capability"]),
    ),
    relationship(
      "PlatformMappedToResponsibility",
      "mappedTo",
      "Platform → Responsibility",
      "Platform model maps to responsibility model metadata.",
      "IntegrationPlatform",
      "IntegrationResponsibility",
      "responsibilities",
      "PreservePlatformBoundaries",
      3,
      Object.freeze(["required", "platform", "responsibility"]),
    ),
    relationship(
      "ParticipantReferencesContract",
      "references",
      "Participant → Contract",
      "Participant references contract model metadata.",
      "IntegrationParticipant",
      "IntegrationContract",
      "contracts",
      "ConsumerContract",
      4,
      Object.freeze(["required", "participant", "contract"]),
    ),
    relationship(
      "ParticipantReferencesCapability",
      "references",
      "Participant → Capability",
      "Participant references capability model metadata.",
      "IntegrationParticipant",
      "IntegrationCapability",
      "capabilities",
      "Interoperability",
      5,
      Object.freeze(["required", "participant", "capability"]),
    ),
    relationship(
      "ParticipantParticipatesInLifecycle",
      "participatesIn",
      "Participant → Lifecycle",
      "Participant participates in lifecycle model metadata.",
      "IntegrationParticipant",
      "IntegrationLifecycle",
      "lifecycleCoverage",
      "Verified",
      6,
      Object.freeze(["required", "participant", "lifecycle"]),
    ),
    relationship(
      "DomainComposedOfTopology",
      "composedOf",
      "Domain → Topology",
      "Domain is composed of topology model metadata.",
      "IntegrationDomain",
      "IntegrationTopology",
      "categories",
      "Coordination",
      7,
      Object.freeze(["required", "domain", "topology"]),
    ),
    relationship(
      "DomainOwnsBoundary",
      "owns",
      "Domain → Boundary",
      "Domain owns boundary model metadata.",
      "IntegrationDomain",
      "IntegrationBoundary",
      "categories",
      "Ownership",
      8,
      Object.freeze(["required", "domain", "boundary"]),
    ),
    relationship(
      "DomainDependsOnDependency",
      "dependsOn",
      "Domain → Dependency",
      "Domain depends on dependency-direction model metadata.",
      "IntegrationDomain",
      "IntegrationDependency",
      "categories",
      "Compatibility",
      9,
      Object.freeze(["required", "domain", "dependency"]),
    ),
    relationship(
      "DomainCompatibleWithCompatibility",
      "compatibleWith",
      "Domain → Compatibility",
      "Domain declares compatibility model metadata.",
      "IntegrationDomain",
      "IntegrationCompatibility",
      "categories",
      "Compatibility",
      10,
      Object.freeze(["required", "domain", "compatibility"]),
    ),
    relationship(
      "ModelExtendsRegistry",
      "extends",
      "Model extends Registry",
      "Integration Model extends Registry collections without duplication.",
      "IntegrationModel",
      "IntegrationDomain",
      "collections",
      "collections",
      11,
      Object.freeze(["structural", "extends"]),
    ),
    relationship(
      "PlatformProducesExchange",
      "produces",
      "Platform produces Exchange",
      "Platform produces exchange metadata without runtime emission.",
      "IntegrationPlatform",
      "IntegrationExchange",
      "contracts",
      "ProducerContract",
      12,
      Object.freeze(["producer"]),
    ),
    relationship(
      "PlatformConsumesExchange",
      "consumes",
      "Platform consumes Exchange",
      "Platform consumes exchange metadata without runtime dispatch.",
      "IntegrationPlatform",
      "IntegrationExchange",
      "contracts",
      "ConsumerContract",
      13,
      Object.freeze(["consumer"]),
    ),
    relationship(
      "DomainCoordinatesRoute",
      "coordinates",
      "Domain coordinates Route",
      "Domain coordinates route metadata without networking.",
      "IntegrationDomain",
      "IntegrationRoute",
      "categories",
      "Routing",
      14,
      Object.freeze(["coordination", "routing"]),
    ),
    relationship(
      "ParticipantBelongsToDomain",
      "belongsTo",
      "Participant belongs to Domain",
      "Participant belongs to the integration domain model.",
      "IntegrationParticipant",
      "IntegrationDomain",
      "categories",
      "IntegrationType",
      15,
      Object.freeze(["membership"]),
    ),
    relationship(
      "OwnershipOwnsBoundary",
      "owns",
      "Ownership owns Boundary",
      "Ownership model owns boundary declarations.",
      "IntegrationOwnership",
      "IntegrationBoundary",
      "categories",
      "Ownership",
      16,
      Object.freeze(["ownership"]),
    ),
  ]);
