/**
 * EIL-2:4 — Integration Connector Validation Rules.
 *
 * Canonical declarative validation rules for connector architecture metadata.
 * Descriptive only. No rule execution. No validation engine.
 *
 * Ownership: owned exclusively by EIL-2:4.
 */

import {
  IntegrationConnectorModelIdentity,
  IntegrationConnectorModelPlatform,
} from "./integrationConnectorModel.ts";
import type {
  IntegrationConnectorModelReference,
  IntegrationConnectorValidationCategoryId,
  IntegrationConnectorValidationExpectedOutcome,
  IntegrationConnectorValidationRule,
  IntegrationConnectorValidationSeverity,
} from "./integrationConnectorValidationTypes.ts";

const model = IntegrationConnectorModelPlatform;

const modelRef = (sourcePath: string): IntegrationConnectorModelReference =>
  Object.freeze({
    modelId: IntegrationConnectorModelIdentity.canonicalId,
    modelNamespace: IntegrationConnectorModelIdentity.namespace,
    entryPoint: "integrationConnectorModel.ts" as const,
    sourcePath,
    preservesCanonicalReference: true as const,
    duplicatesModelValue: false as const,
    metadataOnly: true as const,
    immutable: true as const,
  });

const rule = (
  key: string,
  canonicalName: string,
  category: IntegrationConnectorValidationCategoryId,
  description: string,
  severity: IntegrationConnectorValidationSeverity,
  expectedOutcome: IntegrationConnectorValidationExpectedOutcome,
  sourcePath: string,
  ordinal: number,
  tags: readonly string[],
): IntegrationConnectorValidationRule =>
  Object.freeze({
    ruleId: `EIL-2:4/Rule/${key}` as const,
    canonicalKey: key,
    canonicalName,
    category,
    description,
    severity,
    expectedOutcome,
    sourceReference: modelRef(sourcePath),
    ownership: "EIL-2:4" as const,
    ordinal,
    tags: Object.freeze([...tags]),
    executesValidation: false as const,
    metadataOnly: true as const,
    immutable: true as const,
  });

/**
 * Canonical declarative validation rules.
 * Counts and references are derived from Model aggregate metadata.
 */
export const IntegrationConnectorValidationRules: readonly IntegrationConnectorValidationRule[] =
  Object.freeze([
    rule(
      "CanonicalIdentityExists",
      "Canonical identity exists",
      "Identity",
      "Canonical Integration Connector Model identity must exist.",
      "Error",
      "Present",
      "identity",
      1,
      Object.freeze(["identity"]),
    ),
    rule(
      "NamespaceValid",
      "Namespace valid",
      "Namespace",
      "Connector model namespace must equal nexora.eil.integration-connector.model.",
      "Error",
      "Valid",
      "identity.namespace",
      2,
      Object.freeze(["namespace"]),
    ),
    rule(
      "VersionValid",
      "Version valid",
      "Identity",
      "Connector model version must equal 1.0.0.",
      "Error",
      "Valid",
      "identity.version",
      3,
      Object.freeze(["version"]),
    ),
    rule(
      "RegistryComplete",
      "Registry complete",
      "Registry",
      `Registry reference must remain complete via Model (${model.sources.registryId}).`,
      "Error",
      "Complete",
      "sources.registryId",
      4,
      Object.freeze(["registry"]),
    ),
    rule(
      "DomainModelsComplete",
      "Domain models complete",
      "DomainModel",
      `Exactly ${model.domains.length} connector domain models must be declared.`,
      "Error",
      "Complete",
      "domains",
      5,
      Object.freeze(["domain-model"]),
    ),
    rule(
      "EndpointModelsComplete",
      "Endpoint models complete",
      "EndpointModel",
      `Exactly ${model.endpoints.length} endpoint models must be declared.`,
      "Error",
      "Complete",
      "endpoints",
      6,
      Object.freeze(["endpoint-model"]),
    ),
    rule(
      "ProtocolModelsComplete",
      "Protocol models complete",
      "ProtocolModel",
      `Exactly ${model.protocols.length} protocol models must be declared.`,
      "Error",
      "Complete",
      "protocols",
      7,
      Object.freeze(["protocol-model"]),
    ),
    rule(
      "RelationshipsComplete",
      "Relationships complete",
      "Relationship",
      `Exactly ${model.relationships.length} relationship models must be declared.`,
      "Error",
      "Complete",
      "relationships",
      8,
      Object.freeze(["relationship"]),
    ),
    rule(
      "DependencyDirectionPreserved",
      "Dependency direction preserved",
      "Dependency",
      "Model must consume only the Registry aggregate entry point.",
      "Error",
      "Valid",
      "dependency",
      9,
      Object.freeze(["dependency"]),
    ),
    rule(
      "CompatibilityComplete",
      "Compatibility complete",
      "Compatibility",
      "Compatibility domain and relationship metadata must remain declared.",
      "Error",
      "Complete",
      "domains",
      10,
      Object.freeze(["compatibility"]),
    ),
    rule(
      "LifecycleComplete",
      "Lifecycle complete",
      "Lifecycle",
      "Lifecycle domain mapping metadata must remain declared.",
      "Error",
      "Complete",
      "domains",
      11,
      Object.freeze(["lifecycle"]),
    ),
    rule(
      "InventoryDerived",
      "Inventory derived",
      "Inventory",
      "Model inventory counts must be derived from canonical collections.",
      "Error",
      "Derived",
      "inventory",
      12,
      Object.freeze(["inventory"]),
    ),
    rule(
      "ImmutableMetadata",
      "Immutable metadata",
      "Immutability",
      "Connector model collections must declare immutability.",
      "Error",
      "Immutable",
      "collections",
      13,
      Object.freeze(["immutability"]),
    ),
    rule(
      "DeterministicOrdering",
      "Deterministic ordering",
      "Determinism",
      "Connector model ordinals must remain deterministic.",
      "Error",
      "Deterministic",
      "collections",
      14,
      Object.freeze(["determinism"]),
    ),
    rule(
      "AggregateExportsCorrect",
      "Aggregate exports correct",
      "Export",
      "Model aggregate must expose exactly eight public exports.",
      "Error",
      "Complete",
      "sectionOrder",
      15,
      Object.freeze(["export"]),
    ),
    rule(
      "ProhibitedImportsAbsent",
      "Prohibited imports absent",
      "Dependency",
      "Model must not import Foundation, Registry internals, EIL-1, or later phases.",
      "Error",
      "Absent",
      "dependency",
      16,
      Object.freeze(["imports"]),
    ),
    rule(
      "MetadataOnlyArchitecture",
      "Metadata-only architecture",
      "Architecture",
      "Connector model must declare metadataOnly architecture.",
      "Error",
      "Present",
      "metadataOnly",
      17,
      Object.freeze(["architecture"]),
    ),
    rule(
      "RuntimeAbsent",
      "Runtime absent",
      "Architecture",
      "Connector runtime behavior must be absent.",
      "Error",
      "Absent",
      "connectorRuntime",
      18,
      Object.freeze(["runtime"]),
    ),
    rule(
      "NetworkingAbsent",
      "Networking absent",
      "Architecture",
      "Networking behavior must be absent.",
      "Error",
      "Absent",
      "networkingBehavior",
      19,
      Object.freeze(["networking"]),
    ),
    rule(
      "AuthenticationAbsent",
      "Authentication absent",
      "Architecture",
      "Authentication and authorization logic must be absent.",
      "Error",
      "Absent",
      "authenticationLogic",
      20,
      Object.freeze(["authentication"]),
    ),
    rule(
      "ProtocolExecutionAbsent",
      "Protocol execution absent",
      "ProtocolModel",
      "Protocol execution must be absent.",
      "Error",
      "Absent",
      "protocolExecution",
      21,
      Object.freeze(["protocol"]),
    ),
    rule(
      "EndpointExecutionAbsent",
      "Endpoint execution absent",
      "EndpointModel",
      "Endpoint communication must be absent.",
      "Error",
      "Absent",
      "endpointCommunication",
      22,
      Object.freeze(["endpoint"]),
    ),
    rule(
      "SdkRuntimeAbsent",
      "SDK runtime absent",
      "Architecture",
      "SDK runtime behavior must be absent.",
      "Warning",
      "Absent",
      "boundaries",
      23,
      Object.freeze(["sdk"]),
    ),
    rule(
      "AiAbsent",
      "AI absent",
      "Architecture",
      "AI and LLM behavior must be absent.",
      "Error",
      "Absent",
      "aiBehavior",
      24,
      Object.freeze(["ai"]),
    ),
    rule(
      "UiAbsent",
      "UI absent",
      "Architecture",
      "UI and React behavior must be absent.",
      "Error",
      "Absent",
      "uiBehavior",
      25,
      Object.freeze(["ui"]),
    ),
    rule(
      "ReadinessDeclared",
      "Readiness declared",
      "Readiness",
      "Model readiness must declare ReadyForValidation for Validation consumption.",
      "Error",
      "Present",
      "readiness",
      26,
      Object.freeze(["readiness"]),
    ),
  ]);
