/**
 * EIL-3:4 — Integration Routing Validation Rules.
 *
 * Canonical declarative validation rules for routing architecture metadata.
 * Descriptive only. No rule execution. No validation engine.
 *
 * Ownership: owned exclusively by EIL-3:4.
 */

import {
  IntegrationRoutingModelIdentity,
  IntegrationRoutingModelPlatform,
} from "./integrationRoutingModel.ts";
import type {
  RoutingModelReference,
  RoutingValidationCategoryId,
  RoutingValidationExpectedOutcome,
  RoutingValidationRule,
  RoutingValidationSeverity,
} from "./integrationRoutingValidationTypes.ts";

const model = IntegrationRoutingModelPlatform;

const modelRef = (sourcePath: string): RoutingModelReference =>
  Object.freeze({
    modelId: IntegrationRoutingModelIdentity.canonicalId,
    modelNamespace: IntegrationRoutingModelIdentity.namespace,
    entryPoint: "integrationRoutingModel.ts" as const,
    sourcePath,
    preservesCanonicalReference: true as const,
    duplicatesModelValue: false as const,
    metadataOnly: true as const,
    immutable: true as const,
  });

const rule = (
  key: string,
  canonicalName: string,
  category: RoutingValidationCategoryId,
  description: string,
  severity: RoutingValidationSeverity,
  expectedOutcome: RoutingValidationExpectedOutcome,
  sourcePath: string,
  ordinal: number,
  tags: readonly string[],
): RoutingValidationRule =>
  Object.freeze({
    ruleId: `EIL-3:4/Rule/${key}` as const,
    canonicalKey: key,
    canonicalName,
    category,
    description,
    severity,
    expectedOutcome,
    sourceReference: modelRef(sourcePath),
    ownership: "EIL-3:4" as const,
    ordinal,
    tags: Object.freeze([...tags]),
    executesValidation: false as const,
    metadataOnly: true as const,
    immutable: true as const,
  });

/**
 * Exactly twenty-six declarative validation rules.
 * Counts and references are derived from Model aggregate metadata.
 */
export const IntegrationRoutingValidationRules: readonly RoutingValidationRule[] =
  Object.freeze([
    rule(
      "IdentityIntegrity",
      "Identity Integrity",
      "Identity",
      "Canonical Integration Routing Model identity must exist.",
      "Error",
      "Present",
      "identity",
      1,
      Object.freeze(["identity"]),
    ),
    rule(
      "NamespaceIntegrity",
      "Namespace Integrity",
      "Namespace",
      "Routing model namespace must equal nexora.eil.integration-routing.model.",
      "Error",
      "Valid",
      "identity.namespace",
      2,
      Object.freeze(["namespace"]),
    ),
    rule(
      "VersionIntegrity",
      "Version Integrity",
      "Identity",
      "Routing model version must equal 1.0.0.",
      "Error",
      "Valid",
      "identity.version",
      3,
      Object.freeze(["version"]),
    ),
    rule(
      "RegistryReferenceIntegrity",
      "Registry Reference Integrity",
      "Registry",
      `Registry reference must remain complete via Model (${model.sources.registryId}).`,
      "Error",
      "Complete",
      "sources.registryId",
      4,
      Object.freeze(["registry"]),
    ),
    rule(
      "DomainModelCompleteness",
      "Domain Model Completeness",
      "DomainModel",
      `Exactly ${model.domains.length} routing domain models must be declared.`,
      "Error",
      "Complete",
      "domains",
      5,
      Object.freeze(["domain-model"]),
    ),
    rule(
      "RelationshipCompleteness",
      "Relationship Completeness",
      "Relationship",
      `Exactly ${model.relationships.length} relationship models must be declared.`,
      "Error",
      "Complete",
      "relationships",
      6,
      Object.freeze(["relationship"]),
    ),
    rule(
      "TopologyCompleteness",
      "Topology Completeness",
      "Topology",
      `Exactly ${model.topologies.length} topology models must be declared.`,
      "Error",
      "Complete",
      "topologies",
      7,
      Object.freeze(["topology"]),
    ),
    rule(
      "LifecycleCompleteness",
      "Lifecycle Completeness",
      "Lifecycle",
      `Exactly ${model.lifecycles.length} lifecycle mappings must be declared.`,
      "Error",
      "Complete",
      "lifecycles",
      8,
      Object.freeze(["lifecycle"]),
    ),
    rule(
      "DependencyDirection",
      "Dependency Direction",
      "Dependency",
      "Model must consume only the Registry aggregate entry point.",
      "Error",
      "Valid",
      "dependency",
      9,
      Object.freeze(["dependency"]),
    ),
    rule(
      "CompatibilityIntegrity",
      "Compatibility Integrity",
      "Compatibility",
      "Compatibility declarations must remain declared without runtime validation.",
      "Error",
      "Complete",
      "compatibility",
      10,
      Object.freeze(["compatibility"]),
    ),
    rule(
      "OwnershipIntegrity",
      "Ownership Integrity",
      "Architecture",
      "Model ownership boundaries must remain declared.",
      "Error",
      "Complete",
      "boundaries",
      11,
      Object.freeze(["ownership"]),
    ),
    rule(
      "BoundaryIntegrity",
      "Boundary Integrity",
      "Architecture",
      "Architectural boundary metadata must remain declared.",
      "Error",
      "Complete",
      "boundaries",
      12,
      Object.freeze(["boundary"]),
    ),
    rule(
      "InventoryIntegrity",
      "Inventory Integrity",
      "Inventory",
      "Model inventory counts must be derived from canonical collections.",
      "Error",
      "Derived",
      "inventory",
      13,
      Object.freeze(["inventory"]),
    ),
    rule(
      "CollectionIntegrity",
      "Collection Integrity",
      "Inventory",
      "Model collections must remain complete and frozen.",
      "Error",
      "Complete",
      "collections",
      14,
      Object.freeze(["collection"]),
    ),
    rule(
      "ExportIntegrity",
      "Export Integrity",
      "Export",
      "Model aggregate must expose exactly eight public exports.",
      "Error",
      "Complete",
      "sectionOrder",
      15,
      Object.freeze(["export"]),
    ),
    rule(
      "Immutability",
      "Immutability",
      "Immutability",
      "Routing model collections must declare immutability.",
      "Error",
      "Immutable",
      "collections",
      16,
      Object.freeze(["immutability"]),
    ),
    rule(
      "DeterministicOrdering",
      "Deterministic Ordering",
      "Determinism",
      "Routing model ordinals must remain deterministic.",
      "Error",
      "Deterministic",
      "collections",
      17,
      Object.freeze(["determinism"]),
    ),
    rule(
      "CanonicalInventoryRule",
      "Canonical Inventory Rule",
      "Inventory",
      "Inventory values must be dynamically derived from collection lengths.",
      "Error",
      "Derived",
      "inventory.countsDerivedFromCollections",
      18,
      Object.freeze(["canonical-inventory"]),
    ),
    rule(
      "MetadataOnlyCompliance",
      "Metadata-only Compliance",
      "Architecture",
      "Routing model must declare metadataOnly architecture.",
      "Error",
      "Present",
      "metadataOnly",
      19,
      Object.freeze(["architecture"]),
    ),
    rule(
      "RuntimeSurfaceProhibition",
      "Runtime Surface Prohibition",
      "Architecture",
      "Routing engine and runtime surfaces must be absent.",
      "Error",
      "Absent",
      "routingEngine",
      20,
      Object.freeze(["runtime"]),
    ),
    rule(
      "ArchitecturalConsistency",
      "Architectural Consistency",
      "Architecture",
      "Routing model architectural consistency metadata must remain declared.",
      "Error",
      "Valid",
      "boundaries",
      21,
      Object.freeze(["consistency"]),
    ),
    rule(
      "ReadinessIntegrity",
      "Readiness Integrity",
      "Readiness",
      "Model readiness must declare ReadyForValidation for Validation consumption.",
      "Error",
      "Present",
      "readiness",
      22,
      Object.freeze(["readiness"]),
    ),
    rule(
      "SummaryIntegrity",
      "Summary Integrity",
      "Documentation",
      "Model summary metadata must remain complete and frozen.",
      "Error",
      "Complete",
      "summary",
      23,
      Object.freeze(["summary"]),
    ),
    rule(
      "PlatformAggregateIntegrity",
      "Platform Aggregate Integrity",
      "Export",
      "Model platform aggregate must preserve ordered sections.",
      "Error",
      "Complete",
      "sectionOrder",
      24,
      Object.freeze(["platform"]),
    ),
    rule(
      "SourceReferenceIntegrity",
      "Source Reference Integrity",
      "Registry",
      "Model source references must preserve Registry aggregate identity.",
      "Error",
      "Valid",
      "sources",
      25,
      Object.freeze(["source-reference"]),
    ),
    rule(
      "DocumentationIntegrity",
      "Documentation Integrity",
      "Documentation",
      "Validation documentation metadata must remain declaratively complete.",
      "Warning",
      "Complete",
      "identity.description",
      26,
      Object.freeze(["documentation"]),
    ),
  ]);
