/**
 * EIL-1:4 — Integration Validation Rules.
 *
 * Canonical declarative validation rules for Integration architecture metadata.
 * Descriptive only. No rule execution. No validation engine.
 *
 * Ownership: owned exclusively by EIL-1:4.
 */

import {
  IntegrationModelIdentity,
  IntegrationModelPlatform,
} from "./integrationModel.ts";
import type {
  IntegrationModelReference,
  IntegrationValidationCategoryId,
  IntegrationValidationExpectedOutcome,
  IntegrationValidationRule,
  IntegrationValidationSeverity,
} from "./integrationValidationTypes.ts";

const model = IntegrationModelPlatform;

const modelRef = (sourcePath: string): IntegrationModelReference =>
  Object.freeze({
    modelId: IntegrationModelIdentity.canonicalId,
    modelNamespace: IntegrationModelIdentity.namespace,
    entryPoint: "integrationModel.ts" as const,
    sourcePath,
    preservesCanonicalReference: true as const,
    duplicatesModelValue: false as const,
    metadataOnly: true as const,
    immutable: true as const,
  });

const rule = (
  key: string,
  canonicalName: string,
  category: IntegrationValidationCategoryId,
  description: string,
  severity: IntegrationValidationSeverity,
  expectedOutcome: IntegrationValidationExpectedOutcome,
  sourcePath: string,
  ordinal: number,
  tags: readonly string[],
): IntegrationValidationRule =>
  Object.freeze({
    ruleId: `EIL-1:4/Rule/${key}` as const,
    canonicalKey: key,
    canonicalName,
    category,
    description,
    severity,
    expectedOutcome,
    sourceReference: modelRef(sourcePath),
    ownership: "EIL-1:4" as const,
    ordinal,
    tags: Object.freeze([...tags]),
    executesValidation: false as const,
    metadataOnly: true as const,
    immutable: true as const,
  });

/**
 * Canonical declarative validation rules.
 * Counts and references are derived from Model aggregate metadata.
 */
export const IntegrationValidationRules: readonly IntegrationValidationRule[] =
  Object.freeze([
    rule(
      "CanonicalIdentityExists",
      "Canonical identity exists",
      "Identity",
      "Canonical Integration Model identity must exist.",
      "Error",
      "Present",
      "identity",
      1,
      Object.freeze(["identity"]),
    ),
    rule(
      "NamespaceIsValid",
      "Namespace is valid",
      "Namespace",
      "Model namespace must equal nexora.eil.integration.model.",
      "Error",
      "Valid",
      "identity/namespace",
      2,
      Object.freeze(["namespace"]),
    ),
    rule(
      "VersionIsValid",
      "Version is valid",
      "Identity",
      "Model version must equal 1.0.0.",
      "Error",
      "Valid",
      "identity/version",
      3,
      Object.freeze(["version"]),
    ),
    rule(
      "RegistryDependencyOnly",
      "Registry dependency only",
      "Dependency",
      "Model must declare Registry as sole upstream dependency.",
      "Error",
      "Valid",
      "dependency",
      4,
      Object.freeze(["dependency"]),
    ),
    rule(
      "AggregateImportOnly",
      "Aggregate import only",
      "Dependency",
      "Validation must consume only the Model aggregate entry point.",
      "Error",
      "Valid",
      "dependency/entryPoint",
      5,
      Object.freeze(["dependency", "import"]),
    ),
    rule(
      "MetadataOnlyArchitecture",
      "Metadata-only architecture",
      "Immutability",
      "Architecture must remain metadata-only across Foundation, Registry, and Model.",
      "Error",
      "Present",
      "metadataOnly",
      6,
      Object.freeze(["metadata-only"]),
    ),
    rule(
      "ImmutableExports",
      "Immutable exports",
      "Immutability",
      "All Model public exports must be deeply immutable.",
      "Error",
      "Immutable",
      "collections",
      7,
      Object.freeze(["immutability", "export"]),
    ),
    rule(
      "UniqueIds",
      "Unique IDs",
      "Determinism",
      "All model IDs must be unique within each collection.",
      "Error",
      "Unique",
      "domains",
      8,
      Object.freeze(["uniqueness"]),
    ),
    rule(
      "UniqueKeys",
      "Unique keys",
      "Determinism",
      "All model keys must be unique within each collection.",
      "Error",
      "Unique",
      "domains",
      9,
      Object.freeze(["uniqueness"]),
    ),
    rule(
      "DeterministicOrdering",
      "Deterministic ordering",
      "Determinism",
      "All collections must use explicit ascending ordinals.",
      "Error",
      "Deterministic",
      "collections",
      10,
      Object.freeze(["ordering"]),
    ),
    rule(
      "RequiredContractsPresent",
      "Required contracts present",
      "Contract",
      "Contract integrity must remain represented in Model mappings.",
      "Error",
      "Complete",
      "domains/IntegrationContract",
      11,
      Object.freeze(["contract"]),
    ),
    rule(
      "RequiredCapabilitiesPresent",
      "Required capabilities present",
      "Capability",
      "Capability coverage must remain represented in Model mappings.",
      "Error",
      "Complete",
      "domains/IntegrationCapability",
      12,
      Object.freeze(["capability"]),
    ),
    rule(
      "RequiredResponsibilitiesPresent",
      "Required responsibilities present",
      "Responsibility",
      "Responsibility coverage must remain represented in Model mappings.",
      "Error",
      "Complete",
      "domains/IntegrationResponsibility",
      13,
      Object.freeze(["responsibility"]),
    ),
    rule(
      "LifecycleComplete",
      "Lifecycle complete",
      "Lifecycle",
      `Lifecycle mappings must cover all ${model.lifecycle.length} Foundation states.`,
      "Error",
      "Complete",
      "lifecycle",
      14,
      Object.freeze(["lifecycle"]),
    ),
    rule(
      "TopologyComplete",
      "Topology complete",
      "Topology",
      `Topology models must declare all ${model.topology.length} architectural node kinds.`,
      "Error",
      "Complete",
      "topology",
      15,
      Object.freeze(["topology"]),
    ),
    rule(
      "InventoryDerivedDynamically",
      "Inventory derived dynamically",
      "Inventory",
      "Inventory counts must be derived from canonical collections.",
      "Error",
      "Derived",
      "inventory",
      16,
      Object.freeze(["inventory"]),
    ),
    rule(
      "ProhibitedImportsAbsent",
      "Prohibited imports absent",
      "Dependency",
      "Model and Validation must not import prohibited internals or later phases.",
      "Error",
      "Absent",
      "dependency",
      17,
      Object.freeze(["import"]),
    ),
    rule(
      "RuntimeAbsent",
      "Runtime absent",
      "Boundary",
      "Runtime behavior must remain absent from Integration metadata phases.",
      "Error",
      "Absent",
      "runtimeBehavior",
      18,
      Object.freeze(["runtime"]),
    ),
    rule(
      "NetworkingAbsent",
      "Networking absent",
      "Boundary",
      "Networking behavior must remain absent.",
      "Error",
      "Absent",
      "networkingBehavior",
      19,
      Object.freeze(["networking"]),
    ),
    rule(
      "PersistenceAbsent",
      "Persistence absent",
      "Boundary",
      "Persistence behavior must remain absent.",
      "Error",
      "Absent",
      "persistenceBehavior",
      20,
      Object.freeze(["persistence"]),
    ),
    rule(
      "ServicesAbsent",
      "Services absent",
      "Boundary",
      "Service implementations must remain absent.",
      "Error",
      "Absent",
      "boundaries",
      21,
      Object.freeze(["services"]),
    ),
    rule(
      "ConnectorsAbsent",
      "Connectors absent",
      "Boundary",
      "Connectors and adapters must remain absent.",
      "Error",
      "Absent",
      "connectorBehavior",
      22,
      Object.freeze(["connectors"]),
    ),
    rule(
      "AiAbsent",
      "AI absent",
      "Boundary",
      "AI and LLM behavior must remain absent.",
      "Error",
      "Absent",
      "aiBehavior",
      23,
      Object.freeze(["ai"]),
    ),
    rule(
      "UiAbsent",
      "UI absent",
      "Boundary",
      "UI and visualization behavior must remain absent.",
      "Error",
      "Absent",
      "uiBehavior",
      24,
      Object.freeze(["ui"]),
    ),
    rule(
      "ModelCompleteness",
      "Model completeness",
      "Model",
      `Domain model count must equal ${model.domains.length}.`,
      "Error",
      "Complete",
      "domains",
      25,
      Object.freeze(["model"]),
    ),
    rule(
      "RegistryCompleteness",
      "Registry completeness",
      "Registry",
      "Model must preserve Registry aggregate reference integrity.",
      "Error",
      "Complete",
      "registryIdentity",
      26,
      Object.freeze(["registry"]),
    ),
    rule(
      "CompatibilityDeclarations",
      "Compatibility declarations",
      "Compatibility",
      "Compatibility mappings must remain declared in Model relationships.",
      "Warning",
      "Present",
      "relationships",
      27,
      Object.freeze(["compatibility"]),
    ),
    rule(
      "BoundaryPreservation",
      "Boundary preservation",
      "Boundary",
      "Architectural boundaries must remain declared and non-executable.",
      "Error",
      "Present",
      "boundaries",
      28,
      Object.freeze(["boundary"]),
    ),
    rule(
      "ExportIntegrity",
      "Export integrity",
      "Export",
      "Model aggregate must expose exactly eight public exports.",
      "Error",
      "Valid",
      "summary",
      29,
      Object.freeze(["export"]),
    ),
    rule(
      "RelationshipCoverage",
      "Relationship coverage",
      "Model",
      `Required relationship count must be at least ten; Model declares ${model.relationships.length}.`,
      "Error",
      "Complete",
      "relationships",
      30,
      Object.freeze(["relationship"]),
    ),
  ]);
