import assert from "node:assert/strict";
import test from "node:test";
import { evaluateNxa5ExecutiveJudgment, verifyNexoraNxa5, type Nxa5JudgmentCandidate } from "./nexoraNxa5ExecutiveJudgment.ts";
import type { ExecutiveCollectionComparisonResult, ExecutiveComparisonCriterion } from "./nexoraNcaPost4CollectionComparison.ts";
import type { ExecutiveSituation } from "./nexoraNxa3ExecutiveSituation.ts";
import type { ExecutiveAttentionIntelligence } from "./managerObjectAttentionTypes.ts";

const candidates: readonly Nxa5JudgmentCandidate[] = [
  { id: "capacity", label: "Capacity Gap", kind: "problem", goalAlignment: "DIRECT", materiality: "HIGH", urgency: "MODERATE", riskExposure: "MODERATE", evidenceStrength: "MODERATE", consequence: "Delivery commitment may remain unsupported.", uncertainties: ["Capacity adequacy under expected workload is not yet verified."], constraints: [], feasible: true, reversibility: "REVERSIBLE", gains: ["reduces the most Decision-relevant uncertainty"], sacrifices: ["Margin analysis starts one step later."], learningValue: "HIGH", managerPreference: false, timeSensitive: false },
  { id: "margin", label: "Margin Pressure", kind: "problem", goalAlignment: "RELATED", materiality: "HIGH", urgency: "LOW", riskExposure: "HIGH", evidenceStrength: "MODERATE", consequence: "Financial exposure may continue.", uncertainties: ["Comparable impact is not quantified."], constraints: [], feasible: true, reversibility: "PARTIAL", gains: ["improves cash and margin understanding"], sacrifices: ["Delivery uncertainty remains unresolved."], learningValue: "MODERATE", managerPreference: false, timeSensitive: false },
];
const situation = { identity: "NXA:3/ExecutiveContextSituationalAwareness", composedAtTurn: 3, goal: { title: "Improve Delivery", target: "96%", currentReality: "91%", gap: "5 points", status: "AT_RISK" }, focus: { subjectId: "problems", label: "Problems", kind: "collection", collectionKind: "problem", collectionMemberIds: ["capacity", "margin"], comparisonIds: ["capacity", "margin"], relatedSubjects: ["Capacity Gap"] }, investigation: { subjectId: null, evidence: [], claims: [], causalStatus: "UNCONFIRMED" }, advisory: { recommendation: null, reason: null, status: "NONE" }, decision: { subjectId: null, state: "not-started", confirmationPending: false }, execution: { subjectId: null, state: "NOT_STARTED", blocker: null }, outcome: { state: "NOT_OBSERVED", baseline: null, observed: null, goalImpact: null }, conversation: { referent: "Problems", recentNeed: "ADVISE", pendingQuestion: null, latestManagerAssertion: null }, change: { kind: "NONE", summary: null, affectsGoalOrRecommendation: false }, strongestUnresolvedIssue: "Capacity adequacy is unknown.", conflicts: [] } as ExecutiveSituation;
const attention = { attentionState: "ATTENTION", interventionAssessment: { need: "INTERVENTION_RECOMMENDED" } } as unknown as ExecutiveAttentionIntelligence;
const comparison = (criterion: ExecutiveComparisonCriterion = "INVESTIGATION_PRIORITY", evidenceState: ExecutiveCollectionComparisonResult["evidenceState"] = "INSUFFICIENT"): ExecutiveCollectionComparisonResult => ({ candidateSet: { source: "ACTIVE_COLLECTION", collectionKind: "problem", candidateIds: ["capacity", "margin"], candidates: [{ id: "capacity", label: "Capacity Gap", kind: "problem" }, { id: "margin", label: "Margin Pressure", kind: "problem" }], requestedRelation: "PRIORITIZE", criterion, confidence: "HIGH", resolvedFromTurn: 2 }, mode: "PRIORITIZE", criterion, evidenceState, preferredCandidateId: null, ordering: [], reasons: [], uncertainty: [], advisoryCompatible: false, advisoryEligible: false, primaryOwner: "COLLECTION_COMPARISON", commitsDecision: false, startsExecution: false, businessMutations: [], response: null });
const judge = (overrides: Record<string, unknown> = {}) => evaluateNxa5ExecutiveJudgment({ situation, attention, comparison: comparison(), candidates, judgmentType: "INVESTIGATION_PRIORITY", ...overrides });

test("boundary composes existing authorities without score or mutation", () => { assert.deepEqual(verifyNexoraNxa5(), { ok: true }); const r = judge(); assert.equal(r.numericalScore, null); assert.equal(r.commitsDecision, false); assert.equal(r.startsExecution, false); assert.equal(r.writesStage, false); });
test("problem priority prefers reversible Goal-relevant learning and distinguishes magnitude", () => { const r = judge(); assert.equal(r.preferredCandidateId, "capacity"); assert.equal(r.recommendationType, "INVESTIGATE"); assert.match(r.managerMessage, /Goal relevance|learning value|reversibility/i); assert.doesNotMatch(r.managerMessage, /definitely|is the cause/i); });
test("unsupported overall importance refuses a fake magnitude and offers an explicit-criterion continuation", () => { const r = judge({ comparison: comparison("OVERALL_SIGNIFICANCE"), criterion: "OVERALL_SIGNIFICANCE" }); assert.equal(r.preferredCandidateId, null); assert.equal(r.comparability, "INSUFFICIENT"); assert.match(r.managerMessage, /overall-significance basis/i); assert.match(r.managerMessage, /another explicit criterion/i); assert.doesNotMatch(r.managerMessage, /more useful first investigation/i); });
test("requested risk criterion uses risk evidence instead of default Goal fit", () => { const r = judge({ comparison: comparison("RISK", "SUFFICIENT"), criterion: "RISK", judgmentType: "RISK_PRIORITY" }); assert.equal(r.preferredCandidateId, "margin"); assert.match(r.managerMessage, /risk exposure/i); });
test("reversibility protects against premature irreversible action", () => { const irreversible = { ...candidates[0]!, reversibility: "IRREVERSIBLE" as const, evidenceStrength: "WEAK" as const }; const r = judge({ comparison: comparison("REVERSIBILITY", "SUFFICIENT"), criterion: "REVERSIBILITY", candidates: [irreversible, candidates[1]] }); assert.equal(r.preferredCandidateId, "margin"); assert.notEqual(r.preferredCandidateId, irreversible.id); });
test("weak evidence changes recommendation from action to investigation", () => { const r = judge({ candidates: [{ ...candidates[0]!, evidenceStrength: "WEAK" }, candidates[1]] }); assert.equal(r.recommendationType, "INVESTIGATE"); assert.equal(r.recommendationStrength, "TENTATIVE"); });
test("strong supported reversible recommendation can act without endless analysis", () => { const r = judge({ judgmentType: "ACTION_RECOMMENDATION", comparison: comparison("INVESTIGATION_PRIORITY", "SUFFICIENT"), candidates: [{ ...candidates[0]!, evidenceStrength: "STRONG", uncertainties: [] }, candidates[1]] }); assert.equal(r.recommendationType, "ACT"); assert.equal(r.recommendationStrength, "STRONG"); });
test("decision readiness distinguishes NOT_READY, READY_WITH_KNOWN_UNCERTAINTY, and READY", () => { const base = { situation, attention, comparison: comparison(), candidates, judgmentType: "DECISION_READINESS" as const }; const notReady = evaluateNxa5ExecutiveJudgment({ ...base, decision: { criticalEvidenceMissing: ["supplier capacity"], materialUncertainty: [], remainingUncertainty: [], downsideUnderstood: false, feasible: true, additionalLearningValue: "HIGH" } }); const qualified = evaluateNxa5ExecutiveJudgment({ ...base, decision: { criticalEvidenceMissing: [], materialUncertainty: [], remainingUncertainty: ["timing may vary"], downsideUnderstood: true, feasible: true, additionalLearningValue: "LOW" } }); const ready = evaluateNxa5ExecutiveJudgment({ ...base, decision: { criticalEvidenceMissing: [], materialUncertainty: [], remainingUncertainty: [], downsideUnderstood: true, feasible: true, additionalLearningValue: "LOW" } }); assert.deepEqual([notReady.decisionReadiness, qualified.decisionReadiness, ready.decisionReadiness], ["NOT_READY", "READY_WITH_KNOWN_UNCERTAINTY", "READY"]); assert.match(qualified.managerMessage, /enough to make the Decision/i); });
test("specific change condition makes recommendation falsifiable", () => { const r = judge(); assert.match(r.changeConditions.join(" "), /Capacity adequacy/i); assert.doesNotMatch(r.changeConditions.join(" "), /^new information$/i); });
test("new contradictory evidence revises recommendation without defending stale advice", () => { const previous = judge(); const revisedCandidates = [{ ...candidates[0]!, goalAlignment: "NONE" as const, learningValue: "LOW" as const, evidenceStrength: "STRONG" as const, uncertainties: [] }, { ...candidates[1]!, goalAlignment: "DIRECT" as const, learningValue: "HIGH" as const }]; const revised = judge({ candidates: revisedCandidates, previous }); assert.equal(revised.preferredCandidateId, "margin"); assert.equal(revised.changedFromPrevious, true); });
test("manager preference influences judgment without becoming evidence", () => { const r = judge({ candidates: [candidates[0], { ...candidates[1]!, managerPreference: true }], criterion: "UNSPECIFIED", comparison: comparison("UNSPECIFIED", "SUFFICIENT") }); assert.equal(r.preferredCandidateId, "margin"); assert.doesNotMatch(r.evidence.join(" "), /manager preference/i); });
test("genuine tie produces conditional judgment and no fake winner", () => { const tied = [{ ...candidates[0]!, id: "a", label: "A", goalAlignment: "DIRECT" as const }, { ...candidates[0]!, id: "b", label: "B", goalAlignment: "DIRECT" as const }]; const cmp = { ...comparison("GOAL_IMPACT", "SUFFICIENT"), candidateSet: { ...comparison().candidateSet, candidateIds: ["a", "b"], candidates: [{ id: "a", label: "A", kind: "scenario" }, { id: "b", label: "B", kind: "scenario" }] } }; const r = judge({ candidates: tied, comparison: cmp, criterion: "GOAL_IMPACT", judgmentType: "SCENARIO" }); assert.equal(r.preferredCandidateId, null); assert.match(r.managerMessage, /Neither clearly dominates/i); });
test("candidate set integrity excludes unrelated high-attention candidate", () => { const unrelated = { ...candidates[0]!, id: "unrelated", label: "Unrelated Risk", riskExposure: "CRITICAL" as const }; const r = judge({ candidates: [...candidates, unrelated] }); assert.deepEqual(r.candidateIds, ["capacity", "margin"]); });
test("priority is deterministic and stable under irrelevant context changes", () => { const first = judge(); const changedSituation = { ...situation, focus: { ...situation.focus, label: "Unrelated navigation" } }; const second = judge({ situation: changedSituation, previous: first }); assert.equal(second.preferredCandidateId, first.preferredCandidateId); assert.equal(second.changedFromPrevious, false); });
test("generic judgment types share one architecture", () => { for (const judgmentType of ["RISK_PRIORITY", "OPPORTUNITY_PRIORITY", "SCENARIO", "EXECUTION_PRIORITY", "LEARNING_PRIORITY"] as const) { const r = judge({ judgmentType, comparison: comparison(judgmentType === "RISK_PRIORITY" ? "RISK" : judgmentType === "LEARNING_PRIORITY" ? "INVESTIGATION_PRIORITY" : "GOAL_IMPACT", "SUFFICIENT") }); assert.equal(r.identity, "NXA:5/ExecutiveJudgmentPrioritizationRecommendationQuality"); } });

test("unknown Goal context never invents Goal relevance", () => {
  const noGoal = { ...situation, goal: null } as ExecutiveSituation;
  const unknownGoalCandidates = candidates.map((candidate) => ({ ...candidate, goalAlignment: "UNKNOWN" as const }));
  const result = judge({ situation: noGoal, candidates: unknownGoalCandidates });
  assert.doesNotMatch(result.managerMessage, /Goal relevance|aligned to the Goal/i);
  assert.match(result.managerMessage, /investigat|learning|reversib/i);
});

test("missing Goal context produces Goal-specific insufficiency and a safe continuation", () => {
  const noGoal = { ...situation, goal: null } as ExecutiveSituation;
  const unknownGoalCandidates = candidates.map((candidate) => ({ ...candidate, goalAlignment: "UNKNOWN" as const }));
  const result = judge({
    situation: noGoal,
    candidates: unknownGoalCandidates,
    comparison: comparison("GOAL_IMPACT"),
    criterion: "GOAL_IMPACT",
    judgmentType: "ATTENTION",
  });
  assert.equal(result.preferredCandidateId, null);
  assert.match(result.managerMessage, /authoritative active Goal/i);
  assert.match(result.managerMessage, /another explicit criterion/i);
});
