/**
 * NEX-3:3 — Sixteen immutable Features & Modules domain models.
 */

import { FeaturesModulesRegistry } from "./featuresModulesRegistry.ts";

const Registry = FeaturesModulesRegistry;

export const FeaturesModulesModels = Object.freeze([
  Object.freeze({ identifier: "NEX-3:3/Model/ProductFeatureVision", canonicalName: "Product Feature Vision Model", description: "Structural representation of product feature vision metadata.", category: "ProductFeatureVision", status: "Modeled", version: "1.0.0", owner: "Nexora Product", tags: Object.freeze(["model", "vision"]), relationships: Object.freeze(["NEX-3:3/Relationship/VisionGuidesPrinciples"]), registryEntries: Registry.registries.productFeatureVision, metadataOnly: true, immutable: true }),
  Object.freeze({ identifier: "NEX-3:3/Model/FeaturePrinciple", canonicalName: "Feature Principle Model", description: "Structural representation of feature principle metadata.", category: "FeaturePrinciple", status: "Modeled", version: "1.0.0", owner: "Nexora Product", tags: Object.freeze(["model", "principle"]), relationships: Object.freeze(["NEX-3:3/Relationship/PrinciplesDefineFamilies"]), registryEntries: Registry.registries.featurePrinciples, metadataOnly: true, immutable: true }),
  Object.freeze({ identifier: "NEX-3:3/Model/FeatureCategory", canonicalName: "Feature Category Model", description: "Structural representation of feature classification metadata.", category: "FeatureCategory", status: "Modeled", version: "1.0.0", owner: "Nexora Product", tags: Object.freeze(["model", "feature-category"]), relationships: Object.freeze(["NEX-3:3/Relationship/CategoriesOrganizeFamilies"]), registryEntries: Registry.registries.featureCategories, metadataOnly: true, immutable: true }),
  Object.freeze({ identifier: "NEX-3:3/Model/FeatureFamily", canonicalName: "Feature Family Model", description: "Structural representation of related feature groupings.", category: "FeatureFamily", status: "Modeled", version: "1.0.0", owner: "Nexora Product", tags: Object.freeze(["model", "feature-family"]), relationships: Object.freeze(["NEX-3:3/Relationship/FamiliesContainFeatures"]), registryEntries: Registry.registries.featureFamilies, metadataOnly: true, immutable: true }),
  Object.freeze({ identifier: "NEX-3:3/Model/ProductModule", canonicalName: "Product Module Model", description: "Structural representation of bounded product modules.", category: "ProductModule", status: "Modeled", version: "1.0.0", owner: "Nexora Product", tags: Object.freeze(["model", "module"]), relationships: Object.freeze(["NEX-3:3/Relationship/ModulesExposeCapabilities"]), registryEntries: Registry.registries.productModules, metadataOnly: true, immutable: true }),
  Object.freeze({ identifier: "NEX-3:3/Model/ModuleCategory", canonicalName: "Module Category Model", description: "Structural representation of module classification metadata.", category: "ModuleCategory", status: "Modeled", version: "1.0.0", owner: "Nexora Product", tags: Object.freeze(["model", "module-category"]), relationships: Object.freeze(["NEX-3:3/Relationship/ModuleCategoriesOrganizeModules"]), registryEntries: Registry.registries.moduleCategories, metadataOnly: true, immutable: true }),
  Object.freeze({ identifier: "NEX-3:3/Model/CapabilityGroup", canonicalName: "Capability Group Model", description: "Structural representation of capability group metadata.", category: "CapabilityGroup", status: "Modeled", version: "1.0.0", owner: "Nexora Product", tags: Object.freeze(["model", "capability-group"]), relationships: Object.freeze(["NEX-3:3/Relationship/GroupsContainCapabilities"]), registryEntries: Registry.registries.capabilityGroups, metadataOnly: true, immutable: true }),
  Object.freeze({ identifier: "NEX-3:3/Model/ProductCapability", canonicalName: "Product Capability Model", description: "Structural representation of product capability metadata.", category: "ProductCapability", status: "Modeled", version: "1.0.0", owner: "Nexora Product", tags: Object.freeze(["model", "capability"]), relationships: Object.freeze(["NEX-3:3/Relationship/ModulesExposeCapabilities"]), registryEntries: Registry.registries.productCapabilities, metadataOnly: true, immutable: true }),
  Object.freeze({ identifier: "NEX-3:3/Model/FeatureBoundary", canonicalName: "Feature Boundary Model", description: "Structural representation of feature ownership limits.", category: "FeatureBoundary", status: "Modeled", version: "1.0.0", owner: "Nexora Product", tags: Object.freeze(["model", "feature-boundary"]), relationships: Object.freeze([]), registryEntries: Registry.registries.featureBoundaries, metadataOnly: true, immutable: true }),
  Object.freeze({ identifier: "NEX-3:3/Model/ModuleBoundary", canonicalName: "Module Boundary Model", description: "Structural representation of module responsibility limits.", category: "ModuleBoundary", status: "Modeled", version: "1.0.0", owner: "Nexora Product", tags: Object.freeze(["model", "module-boundary"]), relationships: Object.freeze([]), registryEntries: Registry.registries.moduleBoundaries, metadataOnly: true, immutable: true }),
  Object.freeze({ identifier: "NEX-3:3/Model/FeatureDependency", canonicalName: "Feature Dependency Model", description: "Structural representation of feature metadata references.", category: "FeatureDependency", status: "Modeled", version: "1.0.0", owner: "Nexora Product", tags: Object.freeze(["model", "feature-dependency"]), relationships: Object.freeze(["NEX-3:3/Relationship/FeatureDependenciesReferenceFeatures"]), registryEntries: Registry.registries.featureDependencies, metadataOnly: true, immutable: true }),
  Object.freeze({ identifier: "NEX-3:3/Model/ModuleDependency", canonicalName: "Module Dependency Model", description: "Structural representation of module metadata references.", category: "ModuleDependency", status: "Modeled", version: "1.0.0", owner: "Nexora Product", tags: Object.freeze(["model", "module-dependency"]), relationships: Object.freeze(["NEX-3:3/Relationship/ModuleDependenciesReferenceModules"]), registryEntries: Registry.registries.moduleDependencies, metadataOnly: true, immutable: true }),
  Object.freeze({ identifier: "NEX-3:3/Model/FeatureLifecycle", canonicalName: "Feature Lifecycle Model", description: "Structural representation of feature lifecycle metadata.", category: "FeatureLifecycle", status: "Modeled", version: "1.0.0", owner: "Nexora Product", tags: Object.freeze(["model", "feature-lifecycle"]), relationships: Object.freeze(["NEX-3:3/Relationship/FeatureLifecycleGovernsFeatures"]), registryEntries: Registry.registries.featureLifecycle, metadataOnly: true, immutable: true }),
  Object.freeze({ identifier: "NEX-3:3/Model/ModuleLifecycle", canonicalName: "Module Lifecycle Model", description: "Structural representation of module lifecycle metadata.", category: "ModuleLifecycle", status: "Modeled", version: "1.0.0", owner: "Nexora Product", tags: Object.freeze(["model", "module-lifecycle"]), relationships: Object.freeze(["NEX-3:3/Relationship/ModuleLifecycleGovernsModules"]), registryEntries: Registry.registries.moduleLifecycle, metadataOnly: true, immutable: true }),
  Object.freeze({ identifier: "NEX-3:3/Model/ProductComposition", canonicalName: "Product Composition Model", description: "Structural representation of canonical product composition.", category: "ProductComposition", status: "Modeled", version: "1.0.0", owner: "Nexora Product", tags: Object.freeze(["model", "composition"]), relationships: Object.freeze(["NEX-3:3/Relationship/CompositionContainsModules"]), registryEntries: Registry.registries.productComposition, metadataOnly: true, immutable: true }),
  Object.freeze({ identifier: "NEX-3:3/Model/FeaturesModulesGovernance", canonicalName: "Features & Modules Governance Model", description: "Structural representation of composition ownership and stewardship.", category: "FeaturesModulesGovernance", status: "Modeled", version: "1.0.0", owner: "Nexora Product", tags: Object.freeze(["model", "governance"]), relationships: Object.freeze(["NEX-3:3/Relationship/GovernanceOverseesComposition"]), registryEntries: Registry.registries.featuresModulesGovernance, metadataOnly: true, immutable: true }),
] as const);
