/**
 * NPA v3 — Nexora Architecture Development Standards (NADS).
 *
 * Permanent, dependency-free architectural governance metadata.
 */

export const NexoraArchitectureDevelopmentStandards = Object.freeze({
  identity: Object.freeze({
    id: "NPA-V3/NADS",
    name: "Nexora Architecture Development Standards",
    acronym: "NADS",
    standardVersion: "3.0.0",
    status: "Official",
    effective: "Immediately",
    scope: "AllFutureNexoraDevelopment",
    purpose: "Separate Technical Architecture from Product Reference Architecture.",
    permanentGovernanceRule: true,
    metadataOnly: true,
    immutable: true,
  }),
  architectureFamilies: Object.freeze({
    technical: Object.freeze({
      id: "NPA-T",
      name: "Technical Architecture",
      purpose: "Develop executable software architecture.",
      category: "Runtime",
      appliesTo: Object.freeze([
        "Engine",
        "DKL",
        "Director",
        "EVE",
        "NEA",
        "OPS",
        "EIL",
        "SDK",
        "Runtime",
        "Integration Runtime",
        "Executive Assistant",
        "Workspace Runtime",
        "Pipeline Runtime",
      ]),
      lifecycle: Object.freeze([
        "Foundation",
        "Registry",
        "Model",
        "Validation",
        "Manifest",
        "Platform",
        "Certification",
        "Freeze",
        "Public Index",
      ]),
      lifecyclePolicy: Object.freeze({
        exactPhaseCount: 9,
        mandatory: true,
        alternativesPermitted: false,
        immutable: true,
      }),
      produces: Object.freeze([
        "Executable Architecture",
        "Runtime Metadata",
        "Runtime Contracts",
        "Platform Metadata",
        "Stable Public APIs",
        "Integration Contracts",
        "Runtime References",
        "Canonical Architecture",
      ]),
      prohibitedOutputs: Object.freeze([
        "Product Documentation",
        "Marketing",
        "Pricing",
        "Business Plans",
        "Product Guides",
      ]),
      immutable: true,
    }),
    reference: Object.freeze({
      id: "NPA-R",
      name: "Product Reference Architecture",
      purpose: "Describe the Nexora product and define product knowledge.",
      category: "Product Knowledge",
      appliesTo: Object.freeze([
        "Vision",
        "Product Strategy",
        "Product Roadmap",
        "Features",
        "User Journey",
        "Business Model",
        "Pricing",
        "Licensing",
        "Documentation",
        "Executive Guide",
        "Release Notes",
        "Marketing",
        "Competitive Analysis",
      ]),
      lifecycle: Object.freeze([
        "Foundation",
        "Reference Model",
        "Publication",
        "Release",
        "Public Reference",
      ]),
      lifecyclePolicy: Object.freeze({
        phaseCount: 5,
        lightweight: true,
        technicalLifecyclePermitted: false,
        exceptionAuthority: "Architecture Governance",
        explicitApprovalRequiredForTechnicalLifecycle: true,
        immutable: true,
      }),
      produces: Object.freeze([
        "Product Knowledge",
        "Product Reference",
        "Product Documentation",
        "Product Definitions",
        "Executive References",
        "Product Publications",
      ]),
      prohibitedOutputs: Object.freeze([
        "Runtime Metadata",
        "Runtime",
        "APIs",
        "Executable Architecture",
        "Runtime Contracts",
        "Engines",
        "Services",
        "Integration",
        "AI Execution",
      ]),
      executesSoftware: false,
      immutable: true,
    }),
  }),
  dependencyRules: Object.freeze({
    technicalMayReferenceProductReference: true,
    productReferenceMayDescribeTechnicalArchitecture: true,
    productReferenceMayExecuteRuntime: false,
    runtimeMayDependOnProductReferenceImplementation: false,
    conceptualAlignmentPermitted: true,
    implementationCouplingPermitted: false,
    immutable: true,
  }),
  governance: Object.freeze({
    technicalDecisionStandard: "NPA-T",
    referenceDecisionStandard: "NPA-R",
    classificationRequiredBeforeDevelopment: true,
    simultaneousFamilyMembershipPermitted: false,
    architectureFamiliesMayBeMixed: false,
    independentEvolutionRequired: true,
    conceptualAlignmentRequired: true,
    immutable: true,
  }),
  existingClassification: Object.freeze({
    technicalDomains: Object.freeze([
      "Engine",
      "DKL",
      "Director",
      "EVE",
      "NEA",
      "OPS",
      "EIL",
      "SDK",
      "Runtime",
    ]),
    productReferenceDomains: Object.freeze([
      "NEX",
      "Vision",
      "Product Strategy",
      "Roadmap",
      "Features",
      "User Journey",
      "Business Model",
      "Pricing",
      "Documentation",
      "Executive Guide",
      "Marketing",
    ]),
    mutuallyExclusive: true,
    immutable: true,
  }),
  futureDevelopmentPolicy: Object.freeze({
    effective: "Immediately",
    runtimeDevelopmentPriority: "NPA-T",
    productKnowledgeDevelopmentPriority: "NPA-R",
    evolveIndependently: true,
    remainConceptuallyAligned: true,
    immutable: true,
  }),
  officialDeclaration: Object.freeze({
    architectureStandardCount: 2,
    standards: Object.freeze(["NPA-T", "NPA-R"]),
    technicalArchitectureClassification: "Runtime",
    productReferenceArchitectureClassification: "Product Knowledge",
    permanent: true,
    official: true,
    immutable: true,
  }),
  runtimeExecution: false,
  businessLogic: false,
  apiImplementation: false,
  serviceImplementation: false,
  artificialIntelligenceExecution: false,
  persistence: false,
  networking: false,
  rendering: false,
  integrations: false,
  metadataOnly: true,
  immutable: true,
} as const);

export default NexoraArchitectureDevelopmentStandards;
