/**
 * NEX-1:7 — Immutable declarative Certification criteria.
 */

import { ProductVisionStrategyPlatform } from "./productVisionStrategyPlatform.ts";

export const ProductVisionStrategyCertificationCriteria = Object.freeze([
  Object.freeze({ id: "NEX-1:7/Criterion/CanonicalIdentity", name: "Canonical Identity Verified", description: "Platform canonical identity metadata is declared complete.", category: "Identity", declaredResult: "Verified", platformReference: ProductVisionStrategyPlatform.identity.id, executesCertification: false, metadataOnly: true, immutable: true }),
  Object.freeze({ id: "NEX-1:7/Criterion/PlatformInventory", name: "Platform Inventory Verified", description: "Platform inventory metadata is declared complete.", category: "Inventory", declaredResult: "Verified", platformReference: ProductVisionStrategyPlatform.inventory.id, executesCertification: false, metadataOnly: true, immutable: true }),
  Object.freeze({ id: "NEX-1:7/Criterion/ManifestTraceability", name: "Manifest Traceability Verified", description: "Platform dependency metadata traces to the canonical Manifest.", category: "Traceability", declaredResult: "Verified", platformReference: ProductVisionStrategyPlatform.dependency.upstreamId, executesCertification: false, metadataOnly: true, immutable: true }),
  Object.freeze({ id: "NEX-1:7/Criterion/RegistryTraceability", name: "Registry Traceability Verified", description: "Registry inventory traceability is represented through Platform metadata.", category: "Traceability", declaredResult: "Verified", platformReference: ProductVisionStrategyPlatform.inventory.id, executesCertification: false, metadataOnly: true, immutable: true }),
  Object.freeze({ id: "NEX-1:7/Criterion/ModelTraceability", name: "Model Traceability Verified", description: "Model inventory traceability is represented through Platform metadata.", category: "Traceability", declaredResult: "Verified", platformReference: ProductVisionStrategyPlatform.inventory.id, executesCertification: false, metadataOnly: true, immutable: true }),
  Object.freeze({ id: "NEX-1:7/Criterion/ValidationTraceability", name: "Validation Traceability Verified", description: "Validation inventory traceability is represented through Platform metadata.", category: "Traceability", declaredResult: "Verified", platformReference: ProductVisionStrategyPlatform.inventory.id, executesCertification: false, metadataOnly: true, immutable: true }),
  Object.freeze({ id: "NEX-1:7/Criterion/MetadataIntegrity", name: "Metadata Integrity Verified", description: "Platform metadata integrity declarations are present.", category: "Integrity", declaredResult: "Verified", platformReference: ProductVisionStrategyPlatform.metadata.id, executesCertification: false, metadataOnly: true, immutable: true }),
  Object.freeze({ id: "NEX-1:7/Criterion/PublicationIntegrity", name: "Publication Integrity Verified", description: "Platform publication metadata is declared non-executable.", category: "Publication", declaredResult: "Verified", platformReference: ProductVisionStrategyPlatform.publication.id, executesCertification: false, metadataOnly: true, immutable: true }),
  Object.freeze({ id: "NEX-1:7/Criterion/DependencyIntegrity", name: "Dependency Integrity Verified", description: "Platform declares Manifest as its sole dependency.", category: "Dependency", declaredResult: "Verified", platformReference: ProductVisionStrategyPlatform.dependency.id, executesCertification: false, metadataOnly: true, immutable: true }),
  Object.freeze({ id: "NEX-1:7/Criterion/Compatibility", name: "Compatibility Verified", description: "All required compatibility declarations are present.", category: "Compatibility", declaredResult: "Verified", platformReference: ProductVisionStrategyPlatform.compatibility.id, executesCertification: false, metadataOnly: true, immutable: true }),
  Object.freeze({ id: "NEX-1:7/Criterion/CapabilityCompleteness", name: "Capability Completeness Verified", description: "All declared Platform publication capabilities are represented.", category: "Capability", declaredResult: "Verified", platformReference: ProductVisionStrategyPlatform.inventory.id, executesCertification: false, metadataOnly: true, immutable: true }),
  Object.freeze({ id: "NEX-1:7/Criterion/GuaranteeCompleteness", name: "Guarantee Completeness Verified", description: "All required Platform guarantees are represented.", category: "Guarantee", declaredResult: "Verified", platformReference: ProductVisionStrategyPlatform.inventory.id, executesCertification: false, metadataOnly: true, immutable: true }),
  Object.freeze({ id: "NEX-1:7/Criterion/PublicApiRegistry", name: "Public API Registry Verified", description: "The metadata-only Platform public API Registry is represented.", category: "Publication", declaredResult: "Verified", platformReference: ProductVisionStrategyPlatform.identity.id, executesCertification: false, metadataOnly: true, immutable: true }),
  Object.freeze({ id: "NEX-1:7/Criterion/MetadataOnlyArchitecture", name: "Metadata-Only Architecture Verified", description: "The Platform declares no runtime or executable architecture.", category: "Architecture", declaredResult: "Verified", platformReference: ProductVisionStrategyPlatform.metadata.id, executesCertification: false, metadataOnly: true, immutable: true }),
  Object.freeze({ id: "NEX-1:7/Criterion/VersionConsistency", name: "Version Consistency Verified", description: "Platform and Manifest version metadata are declared consistently.", category: "Versioning", declaredResult: "Verified", platformReference: ProductVisionStrategyPlatform.versioning.id, executesCertification: false, metadataOnly: true, immutable: true }),
  Object.freeze({ id: "NEX-1:7/Criterion/PlatformCompleteness", name: "Platform Completeness Verified", description: "All sixteen required Platform sections are represented.", category: "Completeness", declaredResult: "Verified", platformReference: ProductVisionStrategyPlatform.composition.id, executesCertification: false, metadataOnly: true, immutable: true }),
] as const);
