/**
 * NEX-1:4 — Declarative validation rule metadata.
 *
 * These records describe requirements; they do not evaluate them.
 */

import { ProductVisionStrategyModel } from "./productVisionStrategyModel.ts";

export const ProductVisionStrategyValidationRules = Object.freeze([
  Object.freeze({ identifier: "NEX-1:4/Rule/VisionExists", canonicalName: "Vision shall exist", requirement: "Vision shall exist.", category: "Completeness", domain: "Vision", severity: "Error", modelReference: ProductVisionStrategyModel.groups.identity[0].identifier, executesValidation: false, metadataOnly: true, immutable: true }),
  Object.freeze({ identifier: "NEX-1:4/Rule/MissionExists", canonicalName: "Mission shall exist", requirement: "Mission shall exist.", category: "Completeness", domain: "Mission", severity: "Error", modelReference: ProductVisionStrategyModel.groups.identity[1].identifier, executesValidation: false, metadataOnly: true, immutable: true }),
  Object.freeze({ identifier: "NEX-1:4/Rule/MissionReferencesVision", canonicalName: "Mission vision reference", requirement: "Every Mission references one Vision.", category: "Reference", domain: "Mission", severity: "Error", modelReference: ProductVisionStrategyModel.groups.identity[1].identifier, executesValidation: false, metadataOnly: true, immutable: true }),
  Object.freeze({ identifier: "NEX-1:4/Rule/GoalReferencesMission", canonicalName: "Goal mission reference", requirement: "Every Goal references one Mission.", category: "Reference", domain: "ProductGoal", severity: "Error", modelReference: ProductVisionStrategyModel.groups.outcomes[1].identifier, executesValidation: false, metadataOnly: true, immutable: true }),
  Object.freeze({ identifier: "NEX-1:4/Rule/ObjectiveReferencesGoal", canonicalName: "Objective goal reference", requirement: "Every Strategic Objective references at least one Goal.", category: "Reference", domain: "StrategicObjective", severity: "Error", modelReference: ProductVisionStrategyModel.groups.outcomes[2].identifier, executesValidation: false, metadataOnly: true, immutable: true }),
  Object.freeze({ identifier: "NEX-1:4/Rule/MetricReferencesObjective", canonicalName: "Metric objective reference", requirement: "Every Success Metric references one Strategic Objective.", category: "Reference", domain: "SuccessMetric", severity: "Error", modelReference: ProductVisionStrategyModel.groups.outcomes[3].identifier, executesValidation: false, metadataOnly: true, immutable: true }),
  Object.freeze({ identifier: "NEX-1:4/Rule/CapabilityThemeMembership", canonicalName: "Capability theme membership", requirement: "Every Capability belongs to one Strategic Theme.", category: "Relationship", domain: "ProductCapability", severity: "Error", modelReference: ProductVisionStrategyModel.groups.evolution[2].identifier, executesValidation: false, metadataOnly: true, immutable: true }),
  Object.freeze({ identifier: "NEX-1:4/Rule/UniqueTargetUser", canonicalName: "Unique target users", requirement: "Every Target User is uniquely identified.", category: "Uniqueness", domain: "TargetUser", severity: "Error", modelReference: ProductVisionStrategyModel.groups.audiences[0].identifier, executesValidation: false, metadataOnly: true, immutable: true }),
  Object.freeze({ identifier: "NEX-1:4/Rule/UniqueStakeholder", canonicalName: "Unique stakeholders", requirement: "Every Stakeholder is uniquely identified.", category: "Uniqueness", domain: "Stakeholder", severity: "Error", modelReference: ProductVisionStrategyModel.groups.audiences[1].identifier, executesValidation: false, metadataOnly: true, immutable: true }),
  Object.freeze({ identifier: "NEX-1:4/Rule/UniqueValue", canonicalName: "Unique product values", requirement: "Every Product Value is unique.", category: "Uniqueness", domain: "ProductValue", severity: "Error", modelReference: ProductVisionStrategyModel.groups.outcomes[0].identifier, executesValidation: false, metadataOnly: true, immutable: true }),
  Object.freeze({ identifier: "NEX-1:4/Rule/UniquePrinciple", canonicalName: "Unique product principles", requirement: "Every Product Principle is unique.", category: "Uniqueness", domain: "ProductPrinciple", severity: "Error", modelReference: ProductVisionStrategyModel.groups.identity[2].identifier, executesValidation: false, metadataOnly: true, immutable: true }),
  Object.freeze({ identifier: "NEX-1:4/Rule/ConstraintIdentifier", canonicalName: "Constraint identifier", requirement: "Every Constraint has an identifier.", category: "Identity", domain: "ProductConstraint", severity: "Error", modelReference: ProductVisionStrategyModel.groups.boundaries[2].identifier, executesValidation: false, metadataOnly: true, immutable: true }),
  Object.freeze({ identifier: "NEX-1:4/Rule/AssumptionIdentifier", canonicalName: "Assumption identifier", requirement: "Every Assumption has an identifier.", category: "Identity", domain: "ProductAssumption", severity: "Error", modelReference: ProductVisionStrategyModel.groups.boundaries[3].identifier, executesValidation: false, metadataOnly: true, immutable: true }),
  Object.freeze({ identifier: "NEX-1:4/Rule/AcyclicRelationships", canonicalName: "Acyclic strategic relationships", requirement: "No circular strategic relationships are permitted.", category: "Relationship", domain: "StrategicTheme", severity: "Error", modelReference: ProductVisionStrategyModel.groups.evolution[1].identifier, executesValidation: false, metadataOnly: true, immutable: true }),
  Object.freeze({ identifier: "NEX-1:4/Rule/NoDuplicateIdentifiers", canonicalName: "No duplicate identifiers", requirement: "No duplicate identifiers are permitted.", category: "Uniqueness", domain: "ProductScope", severity: "Error", modelReference: ProductVisionStrategyModel.groups.boundaries[0].identifier, executesValidation: false, metadataOnly: true, immutable: true }),
  Object.freeze({ identifier: "NEX-1:4/Rule/NoDuplicateNames", canonicalName: "No duplicate canonical names", requirement: "No duplicate canonical names are permitted.", category: "Uniqueness", domain: "ProductBoundary", severity: "Error", modelReference: ProductVisionStrategyModel.groups.boundaries[1].identifier, executesValidation: false, metadataOnly: true, immutable: true }),
  Object.freeze({ identifier: "NEX-1:4/Rule/ImmutableMetadata", canonicalName: "Immutable metadata", requirement: "All metadata shall be immutable.", category: "Integrity", domain: "ProductLifecycle", severity: "Error", modelReference: ProductVisionStrategyModel.groups.evolution[0].identifier, executesValidation: false, metadataOnly: true, immutable: true }),
  Object.freeze({ identifier: "NEX-1:4/Rule/InventoryConsistency", canonicalName: "Model inventory consistency", requirement: "Model inventory shall be internally consistent.", category: "Consistency", domain: "ModelInventory", severity: "Error", modelReference: ProductVisionStrategyModel.inventory.identifier, executesValidation: false, metadataOnly: true, immutable: true }),
  Object.freeze({ identifier: "NEX-1:4/Rule/PublicApiConsistency", canonicalName: "Public API Registry consistency", requirement: "Public API Registry shall be internally consistent.", category: "Consistency", domain: "PublicApiRegistry", severity: "Error", modelReference: ProductVisionStrategyModel.identity.id, executesValidation: false, metadataOnly: true, immutable: true }),
  Object.freeze({ identifier: "NEX-1:4/Rule/CanonicalIdentity", canonicalName: "Canonical identity validity", requirement: "Canonical identity shall be valid.", category: "Identity", domain: "CanonicalIdentity", severity: "Error", modelReference: ProductVisionStrategyModel.identity.id, executesValidation: false, metadataOnly: true, immutable: true }),
] as const);
