/**
 * NEX-2:7 — Immutable declarative Certification criteria.
 */

import { ProductRoadmapPlatform } from "./productRoadmapPlatform.ts";

export const ProductRoadmapCertificationCriteria = Object.freeze([
  Object.freeze({ id: "NEX-2:7/Criterion/CanonicalIdentity", name: "Canonical Identity Verified", description: "Platform canonical identity metadata is complete.", category: "Identity", sourceSubject: ProductRoadmapPlatform.certificationSeedMetadata.criteriaSubjects[0], declaredResult: "Verified", executesCertification: false, metadataOnly: true, immutable: true }),
  Object.freeze({ id: "NEX-2:7/Criterion/PlatformInventory", name: "Platform Inventory Verified", description: "Platform inventory metadata is complete and upstream-derived.", category: "Inventory", sourceSubject: ProductRoadmapPlatform.certificationSeedMetadata.criteriaSubjects[1], declaredResult: "Verified", executesCertification: false, metadataOnly: true, immutable: true }),
  Object.freeze({ id: "NEX-2:7/Criterion/ManifestTraceability", name: "Manifest Traceability Verified", description: "Platform metadata traces to the canonical Manifest.", category: "Traceability", sourceSubject: ProductRoadmapPlatform.certificationSeedMetadata.criteriaSubjects[2], declaredResult: "Verified", executesCertification: false, metadataOnly: true, immutable: true }),
  Object.freeze({ id: "NEX-2:7/Criterion/RegistryTraceability", name: "Registry Traceability Verified", description: "Registry inventory remains traceable through Platform metadata.", category: "Traceability", sourceSubject: ProductRoadmapPlatform.certificationSeedMetadata.criteriaSubjects[3], declaredResult: "Verified", executesCertification: false, metadataOnly: true, immutable: true }),
  Object.freeze({ id: "NEX-2:7/Criterion/ModelTraceability", name: "Model Traceability Verified", description: "Model inventory remains traceable through Platform metadata.", category: "Traceability", sourceSubject: ProductRoadmapPlatform.certificationSeedMetadata.criteriaSubjects[4], declaredResult: "Verified", executesCertification: false, metadataOnly: true, immutable: true }),
  Object.freeze({ id: "NEX-2:7/Criterion/ValidationTraceability", name: "Validation Traceability Verified", description: "Validation inventory remains traceable through Platform metadata.", category: "Traceability", sourceSubject: ProductRoadmapPlatform.certificationSeedMetadata.criteriaSubjects[5], declaredResult: "Verified", executesCertification: false, metadataOnly: true, immutable: true }),
  Object.freeze({ id: "NEX-2:7/Criterion/MetadataIntegrity", name: "Metadata Integrity Verified", description: "Platform metadata integrity declarations are complete.", category: "Integrity", sourceSubject: ProductRoadmapPlatform.certificationSeedMetadata.criteriaSubjects[6], declaredResult: "Verified", executesCertification: false, metadataOnly: true, immutable: true }),
  Object.freeze({ id: "NEX-2:7/Criterion/PublicationIntegrity", name: "Publication Integrity Verified", description: "Platform publication metadata is non-executable.", category: "Publication", sourceSubject: ProductRoadmapPlatform.certificationSeedMetadata.criteriaSubjects[7], declaredResult: "Verified", executesCertification: false, metadataOnly: true, immutable: true }),
  Object.freeze({ id: "NEX-2:7/Criterion/DependencyIntegrity", name: "Dependency Integrity Verified", description: "Platform declares Manifest as its sole dependency.", category: "Dependency", sourceSubject: ProductRoadmapPlatform.certificationSeedMetadata.criteriaSubjects[8], declaredResult: "Verified", executesCertification: false, metadataOnly: true, immutable: true }),
  Object.freeze({ id: "NEX-2:7/Criterion/Compatibility", name: "Compatibility Verified", description: "All required compatibility declarations are present.", category: "Compatibility", sourceSubject: ProductRoadmapPlatform.certificationSeedMetadata.criteriaSubjects[9], declaredResult: "Verified", executesCertification: false, metadataOnly: true, immutable: true }),
  Object.freeze({ id: "NEX-2:7/Criterion/CapabilityCompleteness", name: "Capability Completeness Verified", description: "All required Platform capabilities are represented.", category: "Capability", sourceSubject: ProductRoadmapPlatform.certificationSeedMetadata.criteriaSubjects[10], declaredResult: "Verified", executesCertification: false, metadataOnly: true, immutable: true }),
  Object.freeze({ id: "NEX-2:7/Criterion/GuaranteeCompleteness", name: "Guarantee Completeness Verified", description: "All required Platform guarantees are represented.", category: "Guarantee", sourceSubject: ProductRoadmapPlatform.certificationSeedMetadata.criteriaSubjects[11], declaredResult: "Verified", executesCertification: false, metadataOnly: true, immutable: true }),
  Object.freeze({ id: "NEX-2:7/Criterion/PublicApiRegistry", name: "Public API Registry Verified", description: "The Platform public API Registry is complete.", category: "Publication", sourceSubject: ProductRoadmapPlatform.certificationSeedMetadata.criteriaSubjects[12], declaredResult: "Verified", executesCertification: false, metadataOnly: true, immutable: true }),
  Object.freeze({ id: "NEX-2:7/Criterion/MetadataOnlyArchitecture", name: "Metadata-Only Architecture Verified", description: "The Platform implements no roadmap runtime.", category: "Architecture", sourceSubject: ProductRoadmapPlatform.certificationSeedMetadata.criteriaSubjects[13], declaredResult: "Verified", executesCertification: false, metadataOnly: true, immutable: true }),
  Object.freeze({ id: "NEX-2:7/Criterion/VersionConsistency", name: "Version Consistency Verified", description: "Platform and Manifest versions are consistently declared.", category: "Versioning", sourceSubject: ProductRoadmapPlatform.certificationSeedMetadata.criteriaSubjects[14], declaredResult: "Verified", executesCertification: false, metadataOnly: true, immutable: true }),
  Object.freeze({ id: "NEX-2:7/Criterion/PlatformCompleteness", name: "Platform Completeness Verified", description: "All sixteen Platform sections are represented.", category: "Completeness", sourceSubject: ProductRoadmapPlatform.certificationSeedMetadata.criteriaSubjects[15], declaredResult: "Verified", executesCertification: false, metadataOnly: true, immutable: true }),
] as const);
