/**
 * NEX-1:3 — Metadata-only Model relationships and validation declarations.
 */

import { ProductVisionStrategyRegistry } from "./productVisionStrategyRegistry.ts";

export const ProductVisionStrategyModelRelationships = Object.freeze([
  Object.freeze({ identifier: "NEX-1:3/Relationship/VisionContainsMission", sourceModel: "NEX-1:3/Model/ProductVision", relationship: "contains", targetModel: "NEX-1:3/Model/ProductMission", description: "Vision contains Mission product-reference metadata.", runtimeExecution: false, metadataOnly: true, immutable: true }),
  Object.freeze({ identifier: "NEX-1:3/Relationship/MissionDrivesGoals", sourceModel: "NEX-1:3/Model/ProductMission", relationship: "drives", targetModel: "NEX-1:3/Model/ProductGoal", description: "Mission drives Goal metadata.", runtimeExecution: false, metadataOnly: true, immutable: true }),
  Object.freeze({ identifier: "NEX-1:3/Relationship/GoalsSupportObjectives", sourceModel: "NEX-1:3/Model/ProductGoal", relationship: "support", targetModel: "NEX-1:3/Model/StrategicObjective", description: "Goals support Strategic Objective metadata.", runtimeExecution: false, metadataOnly: true, immutable: true }),
  Object.freeze({ identifier: "NEX-1:3/Relationship/ObjectivesMeasuredByMetrics", sourceModel: "NEX-1:3/Model/StrategicObjective", relationship: "measuredBy", targetModel: "NEX-1:3/Model/SuccessMetric", description: "Strategic Objectives are measured by Success Metric metadata.", runtimeExecution: false, metadataOnly: true, immutable: true }),
  Object.freeze({ identifier: "NEX-1:3/Relationship/ThemesOrganizeCapabilities", sourceModel: "NEX-1:3/Model/StrategicTheme", relationship: "organize", targetModel: "NEX-1:3/Model/ProductCapability", description: "Strategic Themes organize Product Capability metadata.", runtimeExecution: false, metadataOnly: true, immutable: true }),
  Object.freeze({ identifier: "NEX-1:3/Relationship/CapabilitiesEnableGoals", sourceModel: "NEX-1:3/Model/ProductCapability", relationship: "enable", targetModel: "NEX-1:3/Model/ProductGoal", description: "Product Capabilities enable Goal metadata.", runtimeExecution: false, metadataOnly: true, immutable: true }),
  Object.freeze({ identifier: "NEX-1:3/Relationship/ConstraintsLimitCapabilities", sourceModel: "NEX-1:3/Model/ProductConstraint", relationship: "limit", targetModel: "NEX-1:3/Model/ProductCapability", description: "Constraints limit Product Capability metadata.", runtimeExecution: false, metadataOnly: true, immutable: true }),
  Object.freeze({ identifier: "NEX-1:3/Relationship/AssumptionsInfluenceStrategy", sourceModel: "NEX-1:3/Model/ProductAssumption", relationship: "influence", targetModel: "NEX-1:3/Model/StrategicTheme", description: "Assumptions influence Strategy metadata.", runtimeExecution: false, metadataOnly: true, immutable: true }),
  Object.freeze({ identifier: "NEX-1:3/Relationship/LifecycleGovernsEvolution", sourceModel: "NEX-1:3/Model/ProductLifecycle", relationship: "governs", targetModel: "NEX-1:3/ProductEvolution", description: "Lifecycle governs Product Evolution metadata.", runtimeExecution: false, metadataOnly: true, immutable: true }),
  Object.freeze({ identifier: "NEX-1:3/Relationship/PrinciplesGuideStrategy", sourceModel: "NEX-1:3/Model/ProductPrinciple", relationship: "guide", targetModel: "NEX-1:3/Model/StrategicTheme", description: "Principles guide Strategy metadata.", runtimeExecution: false, metadataOnly: true, immutable: true }),
  Object.freeze({ identifier: "NEX-1:3/Relationship/ValuesGuideStrategy", sourceModel: "NEX-1:3/Model/ProductValue", relationship: "guide", targetModel: "NEX-1:3/Model/StrategicTheme", description: "Values guide Strategy metadata.", runtimeExecution: false, metadataOnly: true, immutable: true }),
  Object.freeze({ identifier: "NEX-1:3/Relationship/BoundariesLimitScope", sourceModel: "NEX-1:3/Model/ProductBoundary", relationship: "limit", targetModel: "NEX-1:3/Model/ProductScope", description: "Boundaries limit Scope metadata.", runtimeExecution: false, metadataOnly: true, immutable: true }),
  Object.freeze({ identifier: "NEX-1:3/Relationship/UsersInformStrategy", sourceModel: "NEX-1:3/Model/TargetUser", relationship: "inform", targetModel: "NEX-1:3/Model/StrategicTheme", description: "Target Users inform Strategy metadata.", runtimeExecution: false, metadataOnly: true, immutable: true }),
  Object.freeze({ identifier: "NEX-1:3/Relationship/StakeholdersInformStrategy", sourceModel: "NEX-1:3/Model/Stakeholder", relationship: "inform", targetModel: "NEX-1:3/Model/StrategicTheme", description: "Stakeholders inform Strategy metadata.", runtimeExecution: false, metadataOnly: true, immutable: true }),
] as const);

export const ProductVisionStrategyModelValidationMetadata = Object.freeze([
  Object.freeze({ identifier: "NEX-1:3/ValidationDeclaration/1", requirement: "Every model shall have a unique identifier.", sourceRegistry: ProductVisionStrategyRegistry.identity.id, executesValidation: false, metadataOnly: true, immutable: true }),
  Object.freeze({ identifier: "NEX-1:3/ValidationDeclaration/2", requirement: "Every model shall have a canonical name.", sourceRegistry: ProductVisionStrategyRegistry.identity.id, executesValidation: false, metadataOnly: true, immutable: true }),
  Object.freeze({ identifier: "NEX-1:3/ValidationDeclaration/3", requirement: "Every Goal shall reference one Mission.", sourceRegistry: ProductVisionStrategyRegistry.identity.id, executesValidation: false, metadataOnly: true, immutable: true }),
  Object.freeze({ identifier: "NEX-1:3/ValidationDeclaration/4", requirement: "Every Mission shall reference one Vision.", sourceRegistry: ProductVisionStrategyRegistry.identity.id, executesValidation: false, metadataOnly: true, immutable: true }),
  Object.freeze({ identifier: "NEX-1:3/ValidationDeclaration/5", requirement: "Every Strategic Objective shall reference at least one Goal.", sourceRegistry: ProductVisionStrategyRegistry.identity.id, executesValidation: false, metadataOnly: true, immutable: true }),
  Object.freeze({ identifier: "NEX-1:3/ValidationDeclaration/6", requirement: "Every Capability shall belong to one Strategic Theme.", sourceRegistry: ProductVisionStrategyRegistry.identity.id, executesValidation: false, metadataOnly: true, immutable: true }),
  Object.freeze({ identifier: "NEX-1:3/ValidationDeclaration/7", requirement: "Every Success Metric shall measure one Strategic Objective.", sourceRegistry: ProductVisionStrategyRegistry.identity.id, executesValidation: false, metadataOnly: true, immutable: true }),
  Object.freeze({ identifier: "NEX-1:3/ValidationDeclaration/8", requirement: "No circular model relationships are permitted.", sourceRegistry: ProductVisionStrategyRegistry.identity.id, executesValidation: false, metadataOnly: true, immutable: true }),
  Object.freeze({ identifier: "NEX-1:3/ValidationDeclaration/9", requirement: "Models shall be immutable.", sourceRegistry: ProductVisionStrategyRegistry.identity.id, executesValidation: false, metadataOnly: true, immutable: true }),
] as const);
