/**
 * NEX-2:3 — Sixteen immutable Product Roadmap domain models.
 */

import { ProductRoadmapRegistry } from "./productRoadmapRegistry.ts";

const Registry = ProductRoadmapRegistry;

export const ProductRoadmapModels = Object.freeze([
  Object.freeze({ identifier: "NEX-2:3/Model/RoadmapVision", canonicalName: "Roadmap Vision Model", description: "Structural representation of roadmap vision metadata.", category: "RoadmapVision", status: "Modeled", version: "1.0.0", owner: "Nexora Product", tags: Object.freeze(["model", "vision"]), relationships: Object.freeze(["NEX-2:3/Relationship/VisionContainsMission"]), registryEntries: Registry.registries.roadmapVision, metadataOnly: true, immutable: true }),
  Object.freeze({ identifier: "NEX-2:3/Model/RoadmapMission", canonicalName: "Roadmap Mission Model", description: "Structural representation of roadmap mission metadata.", category: "RoadmapMission", status: "Modeled", version: "1.0.0", owner: "Nexora Product", tags: Object.freeze(["model", "mission"]), relationships: Object.freeze(["NEX-2:3/Relationship/MissionDrivesInitiatives"]), registryEntries: Registry.registries.roadmapMission, metadataOnly: true, immutable: true }),
  Object.freeze({ identifier: "NEX-2:3/Model/RoadmapPrinciple", canonicalName: "Roadmap Principle Model", description: "Structural representation of roadmap principles.", category: "RoadmapPrinciple", status: "Modeled", version: "1.0.0", owner: "Nexora Product", tags: Object.freeze(["model", "principles"]), relationships: Object.freeze(["NEX-2:3/Relationship/PrinciplesGuideRoadmap"]), registryEntries: Registry.registries.roadmapPrinciples, metadataOnly: true, immutable: true }),
  Object.freeze({ identifier: "NEX-2:3/Model/ProductEvolution", canonicalName: "Product Evolution Model", description: "Structural representation of product evolution strategy.", category: "ProductEvolution", status: "Modeled", version: "1.0.0", owner: "Nexora Product", tags: Object.freeze(["model", "evolution"]), relationships: Object.freeze(["NEX-2:3/Relationship/ReleaseSupportsEvolution"]), registryEntries: Registry.registries.productEvolution, metadataOnly: true, immutable: true }),
  Object.freeze({ identifier: "NEX-2:3/Model/RoadmapHorizon", canonicalName: "Roadmap Horizon Model", description: "Structural representation of roadmap planning horizons.", category: "RoadmapHorizon", status: "Modeled", version: "1.0.0", owner: "Nexora Product", tags: Object.freeze(["model", "horizons"]), relationships: Object.freeze(["NEX-2:3/Relationship/HorizonsFramePlanning"]), registryEntries: Registry.registries.roadmapHorizons, metadataOnly: true, immutable: true }),
  Object.freeze({ identifier: "NEX-2:3/Model/ReleaseStrategy", canonicalName: "Release Strategy Model", description: "Structural representation of release strategy metadata.", category: "ReleaseStrategy", status: "Modeled", version: "1.0.0", owner: "Nexora Product", tags: Object.freeze(["model", "release-strategy"]), relationships: Object.freeze(["NEX-2:3/Relationship/ReleaseSupportsEvolution"]), registryEntries: Registry.registries.releaseStrategy, metadataOnly: true, immutable: true }),
  Object.freeze({ identifier: "NEX-2:3/Model/ProductMilestone", canonicalName: "Product Milestone Model", description: "Structural representation of significant product evolution milestones.", category: "ProductMilestone", status: "Modeled", version: "1.0.0", owner: "Nexora Product", tags: Object.freeze(["model", "milestones"]), relationships: Object.freeze(["NEX-2:3/Relationship/MilestonesBelongToRelease"]), registryEntries: Registry.registries.productMilestones, metadataOnly: true, immutable: true }),
  Object.freeze({ identifier: "NEX-2:3/Model/StrategicInitiative", canonicalName: "Strategic Initiative Model", description: "Structural representation of strategic roadmap initiatives.", category: "StrategicInitiative", status: "Modeled", version: "1.0.0", owner: "Nexora Product", tags: Object.freeze(["model", "initiatives"]), relationships: Object.freeze(["NEX-2:3/Relationship/InitiativesProduceMilestones"]), registryEntries: Registry.registries.strategicInitiatives, metadataOnly: true, immutable: true }),
  Object.freeze({ identifier: "NEX-2:3/Model/ProductTheme", canonicalName: "Product Theme Model", description: "Structural representation of themes organizing roadmap direction.", category: "ProductTheme", status: "Modeled", version: "1.0.0", owner: "Nexora Product", tags: Object.freeze(["model", "themes"]), relationships: Object.freeze(["NEX-2:3/Relationship/ThemesOrganizePriorities"]), registryEntries: Registry.registries.productThemes, metadataOnly: true, immutable: true }),
  Object.freeze({ identifier: "NEX-2:3/Model/ProductPriority", canonicalName: "Product Priority Model", description: "Structural representation of roadmap priority metadata.", category: "ProductPriority", status: "Modeled", version: "1.0.0", owner: "Nexora Product", tags: Object.freeze(["model", "priorities"]), relationships: Object.freeze(["NEX-2:3/Relationship/PrioritiesInfluenceOutcomes"]), registryEntries: Registry.registries.productPriorities, metadataOnly: true, immutable: true }),
  Object.freeze({ identifier: "NEX-2:3/Model/ProductOutcome", canonicalName: "Product Outcome Model", description: "Structural representation of intended roadmap outcomes.", category: "ProductOutcome", status: "Modeled", version: "1.0.0", owner: "Nexora Product", tags: Object.freeze(["model", "outcomes"]), relationships: Object.freeze(["NEX-2:3/Relationship/OutcomesMeasuredByCriteria"]), registryEntries: Registry.registries.productOutcomes, metadataOnly: true, immutable: true }),
  Object.freeze({ identifier: "NEX-2:3/Model/SuccessCriteria", canonicalName: "Success Criteria Model", description: "Structural representation of roadmap success criteria.", category: "SuccessCriteria", status: "Modeled", version: "1.0.0", owner: "Nexora Product", tags: Object.freeze(["model", "success-criteria"]), relationships: Object.freeze(["NEX-2:3/Relationship/OutcomesMeasuredByCriteria"]), registryEntries: Registry.registries.successCriteria, metadataOnly: true, immutable: true }),
  Object.freeze({ identifier: "NEX-2:3/Model/PlanningAssumption", canonicalName: "Planning Assumption Model", description: "Structural representation of explicit roadmap planning assumptions.", category: "PlanningAssumption", status: "Modeled", version: "1.0.0", owner: "Nexora Product", tags: Object.freeze(["model", "assumptions"]), relationships: Object.freeze(["NEX-2:3/Relationship/AssumptionsInfluencePlanning"]), registryEntries: Registry.registries.planningAssumptions, metadataOnly: true, immutable: true }),
  Object.freeze({ identifier: "NEX-2:3/Model/PlanningConstraint", canonicalName: "Planning Constraint Model", description: "Structural representation of immutable roadmap planning constraints.", category: "PlanningConstraint", status: "Modeled", version: "1.0.0", owner: "Nexora Product", tags: Object.freeze(["model", "constraints"]), relationships: Object.freeze(["NEX-2:3/Relationship/ConstraintsRestrictPlanning"]), registryEntries: Registry.registries.planningConstraints, metadataOnly: true, immutable: true }),
  Object.freeze({ identifier: "NEX-2:3/Model/RoadmapLifecycle", canonicalName: "Roadmap Lifecycle Model", description: "Structural representation of roadmap lifecycle stages.", category: "RoadmapLifecycle", status: "Modeled", version: "1.0.0", owner: "Nexora Product", tags: Object.freeze(["model", "lifecycle"]), relationships: Object.freeze(["NEX-2:3/Relationship/LifecycleGovernsEvolution"]), registryEntries: Registry.registries.roadmapLifecycle, metadataOnly: true, immutable: true }),
  Object.freeze({ identifier: "NEX-2:3/Model/RoadmapGovernance", canonicalName: "Roadmap Governance Model", description: "Structural representation of roadmap ownership and stewardship.", category: "RoadmapGovernance", status: "Modeled", version: "1.0.0", owner: "Nexora Product", tags: Object.freeze(["model", "governance"]), relationships: Object.freeze(["NEX-2:3/Relationship/GovernanceOverseesLifecycle"]), registryEntries: Registry.registries.roadmapGovernance, metadataOnly: true, immutable: true }),
] as const);
