/**
 * NEX-1:4 — Sixteen immutable domain validation groups.
 */

import { ProductVisionStrategyModel } from "./productVisionStrategyModel.ts";

export const ProductVisionStrategyValidationGroups = Object.freeze([
  Object.freeze({ identifier: "NEX-1:4/Group/Vision", canonicalName: "Vision Validation", domain: "Vision", modelReference: ProductVisionStrategyModel.groups.identity[0].identifier, ruleReferences: Object.freeze(["NEX-1:4/Rule/VisionExists"]), metadataOnly: true, immutable: true }),
  Object.freeze({ identifier: "NEX-1:4/Group/Mission", canonicalName: "Mission Validation", domain: "Mission", modelReference: ProductVisionStrategyModel.groups.identity[1].identifier, ruleReferences: Object.freeze(["NEX-1:4/Rule/MissionExists", "NEX-1:4/Rule/MissionReferencesVision"]), metadataOnly: true, immutable: true }),
  Object.freeze({ identifier: "NEX-1:4/Group/ProductPrinciple", canonicalName: "Product Principle Validation", domain: "ProductPrinciple", modelReference: ProductVisionStrategyModel.groups.identity[2].identifier, ruleReferences: Object.freeze(["NEX-1:4/Rule/UniquePrinciple"]), metadataOnly: true, immutable: true }),
  Object.freeze({ identifier: "NEX-1:4/Group/ProductValue", canonicalName: "Product Value Validation", domain: "ProductValue", modelReference: ProductVisionStrategyModel.groups.outcomes[0].identifier, ruleReferences: Object.freeze(["NEX-1:4/Rule/UniqueValue"]), metadataOnly: true, immutable: true }),
  Object.freeze({ identifier: "NEX-1:4/Group/ProductGoal", canonicalName: "Product Goal Validation", domain: "ProductGoal", modelReference: ProductVisionStrategyModel.groups.outcomes[1].identifier, ruleReferences: Object.freeze(["NEX-1:4/Rule/GoalReferencesMission"]), metadataOnly: true, immutable: true }),
  Object.freeze({ identifier: "NEX-1:4/Group/StrategicObjective", canonicalName: "Strategic Objective Validation", domain: "StrategicObjective", modelReference: ProductVisionStrategyModel.groups.outcomes[2].identifier, ruleReferences: Object.freeze(["NEX-1:4/Rule/ObjectiveReferencesGoal"]), metadataOnly: true, immutable: true }),
  Object.freeze({ identifier: "NEX-1:4/Group/ProductScope", canonicalName: "Product Scope Validation", domain: "ProductScope", modelReference: ProductVisionStrategyModel.groups.boundaries[0].identifier, ruleReferences: Object.freeze(["NEX-1:4/Rule/NoDuplicateIdentifiers"]), metadataOnly: true, immutable: true }),
  Object.freeze({ identifier: "NEX-1:4/Group/ProductBoundary", canonicalName: "Product Boundary Validation", domain: "ProductBoundary", modelReference: ProductVisionStrategyModel.groups.boundaries[1].identifier, ruleReferences: Object.freeze(["NEX-1:4/Rule/NoDuplicateNames"]), metadataOnly: true, immutable: true }),
  Object.freeze({ identifier: "NEX-1:4/Group/TargetUser", canonicalName: "Target User Validation", domain: "TargetUser", modelReference: ProductVisionStrategyModel.groups.audiences[0].identifier, ruleReferences: Object.freeze(["NEX-1:4/Rule/UniqueTargetUser"]), metadataOnly: true, immutable: true }),
  Object.freeze({ identifier: "NEX-1:4/Group/Stakeholder", canonicalName: "Stakeholder Validation", domain: "Stakeholder", modelReference: ProductVisionStrategyModel.groups.audiences[1].identifier, ruleReferences: Object.freeze(["NEX-1:4/Rule/UniqueStakeholder"]), metadataOnly: true, immutable: true }),
  Object.freeze({ identifier: "NEX-1:4/Group/SuccessMetric", canonicalName: "Success Metric Validation", domain: "SuccessMetric", modelReference: ProductVisionStrategyModel.groups.outcomes[3].identifier, ruleReferences: Object.freeze(["NEX-1:4/Rule/MetricReferencesObjective"]), metadataOnly: true, immutable: true }),
  Object.freeze({ identifier: "NEX-1:4/Group/ProductLifecycle", canonicalName: "Product Lifecycle Validation", domain: "ProductLifecycle", modelReference: ProductVisionStrategyModel.groups.evolution[0].identifier, ruleReferences: Object.freeze(["NEX-1:4/Rule/ImmutableMetadata"]), metadataOnly: true, immutable: true }),
  Object.freeze({ identifier: "NEX-1:4/Group/StrategicTheme", canonicalName: "Strategic Theme Validation", domain: "StrategicTheme", modelReference: ProductVisionStrategyModel.groups.evolution[1].identifier, ruleReferences: Object.freeze(["NEX-1:4/Rule/AcyclicRelationships"]), metadataOnly: true, immutable: true }),
  Object.freeze({ identifier: "NEX-1:4/Group/ProductCapability", canonicalName: "Product Capability Validation", domain: "ProductCapability", modelReference: ProductVisionStrategyModel.groups.evolution[2].identifier, ruleReferences: Object.freeze(["NEX-1:4/Rule/CapabilityThemeMembership"]), metadataOnly: true, immutable: true }),
  Object.freeze({ identifier: "NEX-1:4/Group/ProductConstraint", canonicalName: "Product Constraint Validation", domain: "ProductConstraint", modelReference: ProductVisionStrategyModel.groups.boundaries[2].identifier, ruleReferences: Object.freeze(["NEX-1:4/Rule/ConstraintIdentifier"]), metadataOnly: true, immutable: true }),
  Object.freeze({ identifier: "NEX-1:4/Group/ProductAssumption", canonicalName: "Product Assumption Validation", domain: "ProductAssumption", modelReference: ProductVisionStrategyModel.groups.boundaries[3].identifier, ruleReferences: Object.freeze(["NEX-1:4/Rule/AssumptionIdentifier"]), metadataOnly: true, immutable: true }),
] as const);
