/**
 * NEX-4:3 — Sixteen immutable User Journey & Experience models.
 */

import { UserJourneyExperienceRegistry } from "./userJourneyExperienceRegistry.ts";

const Registry = UserJourneyExperienceRegistry;

export const UserJourneyExperienceModels = Object.freeze([
  Object.freeze({ identifier: "NEX-4:3/Model/UserJourneyVision", canonicalName: "User Journey Vision Model", description: "Structural representation of user journey vision metadata.", category: "UserJourneyVision", status: "Modeled", version: "1.0.0", owner: "Nexora Product", tags: Object.freeze(["model", "vision"]), relationships: Object.freeze(["NEX-4:3/Relationship/VisionGuidesPrinciples"]), registryEntries: Registry.registries.userJourneyVision, metadataOnly: true, immutable: true }),
  Object.freeze({ identifier: "NEX-4:3/Model/ExperiencePrinciple", canonicalName: "Experience Principle Model", description: "Structural representation of experience principle metadata.", category: "ExperiencePrinciple", status: "Modeled", version: "1.0.0", owner: "Nexora Product", tags: Object.freeze(["model", "principle"]), relationships: Object.freeze(["NEX-4:3/Relationship/PrinciplesDefineStages"]), registryEntries: Registry.registries.experiencePrinciples, metadataOnly: true, immutable: true }),
  Object.freeze({ identifier: "NEX-4:3/Model/UserPersona", canonicalName: "User Persona Model", description: "Structural representation of intended user perspectives.", category: "UserPersona", status: "Modeled", version: "1.0.0", owner: "Nexora Product", tags: Object.freeze(["model", "persona"]), relationships: Object.freeze(["NEX-4:3/Relationship/PersonasFollowJourneys"]), registryEntries: Registry.registries.userPersonas, metadataOnly: true, immutable: true }),
  Object.freeze({ identifier: "NEX-4:3/Model/ExecutiveGoal", canonicalName: "Executive Goal Model", description: "Structural representation of executive outcome metadata.", category: "ExecutiveGoal", status: "Modeled", version: "1.0.0", owner: "Nexora Product", tags: Object.freeze(["model", "goal"]), relationships: Object.freeze([]), registryEntries: Registry.registries.executiveGoals, metadataOnly: true, immutable: true }),
  Object.freeze({ identifier: "NEX-4:3/Model/JourneyStage", canonicalName: "Journey Stage Model", description: "Structural representation of user journey stages.", category: "JourneyStage", status: "Modeled", version: "1.0.0", owner: "Nexora Product", tags: Object.freeze(["model", "journey-stage"]), relationships: Object.freeze(["NEX-4:3/Relationship/StagesContainTouchpoints"]), registryEntries: Registry.registries.journeyStages, metadataOnly: true, immutable: true }),
  Object.freeze({ identifier: "NEX-4:3/Model/ExperienceTouchpoint", canonicalName: "Experience Touchpoint Model", description: "Structural representation of conceptual experience touchpoints.", category: "ExperienceTouchpoint", status: "Modeled", version: "1.0.0", owner: "Nexora Product", tags: Object.freeze(["model", "touchpoint"]), relationships: Object.freeze([]), registryEntries: Registry.registries.experienceTouchpoints, metadataOnly: true, immutable: true }),
  Object.freeze({ identifier: "NEX-4:3/Model/OnboardingExperience", canonicalName: "Onboarding Experience Model", description: "Structural representation of onboarding experience metadata.", category: "OnboardingExperience", status: "Modeled", version: "1.0.0", owner: "Nexora Product", tags: Object.freeze(["model", "onboarding"]), relationships: Object.freeze(["NEX-4:3/Relationship/OnboardingLeadsToWorkspace"]), registryEntries: Registry.registries.onboardingExperience, metadataOnly: true, immutable: true }),
  Object.freeze({ identifier: "NEX-4:3/Model/WorkspaceEntry", canonicalName: "Workspace Entry Model", description: "Structural representation of workspace entry experience metadata.", category: "WorkspaceEntry", status: "Modeled", version: "1.0.0", owner: "Nexora Product", tags: Object.freeze(["model", "workspace"]), relationships: Object.freeze(["NEX-4:3/Relationship/WorkspaceEnablesData"]), registryEntries: Registry.registries.workspaceEntry, metadataOnly: true, immutable: true }),
  Object.freeze({ identifier: "NEX-4:3/Model/DataConnectionExperience", canonicalName: "Data Connection Experience Model", description: "Structural representation of data connection experience metadata.", category: "DataConnectionExperience", status: "Modeled", version: "1.0.0", owner: "Nexora Product", tags: Object.freeze(["model", "data-connection"]), relationships: Object.freeze(["NEX-4:3/Relationship/DataEnablesAdvisor"]), registryEntries: Registry.registries.dataConnectionExperience, metadataOnly: true, immutable: true }),
  Object.freeze({ identifier: "NEX-4:3/Model/AdvisorInteraction", canonicalName: "Advisor Interaction Model", description: "Structural representation of advisor interaction metadata.", category: "AdvisorInteraction", status: "Modeled", version: "1.0.0", owner: "Nexora Product", tags: Object.freeze(["model", "advisor"]), relationships: Object.freeze(["NEX-4:3/Relationship/AdvisorSupportsDecision"]), registryEntries: Registry.registries.advisorInteraction, metadataOnly: true, immutable: true }),
  Object.freeze({ identifier: "NEX-4:3/Model/DecisionExperience", canonicalName: "Decision Experience Model", description: "Structural representation of executive decision experience metadata.", category: "DecisionExperience", status: "Modeled", version: "1.0.0", owner: "Nexora Product", tags: Object.freeze(["model", "decision"]), relationships: Object.freeze(["NEX-4:3/Relationship/DecisionContributesTimeline"]), registryEntries: Registry.registries.decisionExperience, metadataOnly: true, immutable: true }),
  Object.freeze({ identifier: "NEX-4:3/Model/TimelineExperience", canonicalName: "Timeline Experience Model", description: "Structural representation of timeline experience metadata.", category: "TimelineExperience", status: "Modeled", version: "1.0.0", owner: "Nexora Product", tags: Object.freeze(["model", "timeline"]), relationships: Object.freeze([]), registryEntries: Registry.registries.timelineExperience, metadataOnly: true, immutable: true }),
  Object.freeze({ identifier: "NEX-4:3/Model/ExperienceLifecycle", canonicalName: "Experience Lifecycle Model", description: "Structural representation of experience lifecycle metadata.", category: "ExperienceLifecycle", status: "Modeled", version: "1.0.0", owner: "Nexora Product", tags: Object.freeze(["model", "lifecycle"]), relationships: Object.freeze(["NEX-4:3/Relationship/LifecycleGovernsJourney"]), registryEntries: Registry.registries.experienceLifecycle, metadataOnly: true, immutable: true }),
  Object.freeze({ identifier: "NEX-4:3/Model/ExperienceBoundary", canonicalName: "Experience Boundary Model", description: "Structural representation of conceptual experience limits.", category: "ExperienceBoundary", status: "Modeled", version: "1.0.0", owner: "Nexora Product", tags: Object.freeze(["model", "boundary"]), relationships: Object.freeze([]), registryEntries: Registry.registries.experienceBoundaries, metadataOnly: true, immutable: true }),
  Object.freeze({ identifier: "NEX-4:3/Model/ExperienceGovernance", canonicalName: "Experience Governance Model", description: "Structural representation of experience ownership and stewardship.", category: "ExperienceGovernance", status: "Modeled", version: "1.0.0", owner: "Nexora Product", tags: Object.freeze(["model", "governance"]), relationships: Object.freeze(["NEX-4:3/Relationship/GovernanceOverseesLifecycle"]), registryEntries: Registry.registries.experienceGovernance, metadataOnly: true, immutable: true }),
  Object.freeze({ identifier: "NEX-4:3/Model/ExperienceSuccessCriteria", canonicalName: "Experience Success Criteria Model", description: "Structural representation of experience success metadata.", category: "ExperienceSuccessCriteria", status: "Modeled", version: "1.0.0", owner: "Nexora Product", tags: Object.freeze(["model", "success"]), relationships: Object.freeze([]), registryEntries: Registry.registries.experienceSuccessCriteria, metadataOnly: true, immutable: true }),
] as const);
