export const NEXORA_CONVERSATION_OBJECTIVES = Object.freeze([
  "UNDERSTAND_SUBJECT",
  "UNDERSTAND_RELATIONSHIP",
  "INVESTIGATE_SUBJECT",
  "COMPARE_SUBJECTS",
  "UNDERSTAND_STAGE",
  "LEARN_CAPABILITY",
  "RESOLVE_UNCERTAINTY",
] as const);

export type NexoraConversationObjective =
  (typeof NEXORA_CONVERSATION_OBJECTIVES)[number];

export const NEXORA_CONVERSATION_THREAD_STATUSES = Object.freeze([
  "ACTIVE",
  "SUFFICIENTLY_COVERED",
  "WAITING_FOR_MANAGER",
  "SUPERSEDED",
] as const);

export type NexoraConversationThreadStatus =
  (typeof NEXORA_CONVERSATION_THREAD_STATUSES)[number];

export const NEXORA_CONVERSATION_THREAD_REASONS = Object.freeze([
  "TURN_POLICY_STANDS",
  "EXPLICIT_MANAGER_INTENT",
  "EXPLICIT_REPEAT_REQUESTED",
  "GENUINE_AMBIGUITY",
  "MULTIPLE_RELEVANT_PURPOSES_ALREADY_COVERED",
  "THREAD_SUFFICIENTLY_COVERED",
  "PENDING_OFFER_STILL_VALID",
  "SUBJECT_SUPERSEDED",
  "NEED_DIFFERENT_STRATEGY",
] as const);

export type NexoraConversationThreadReason =
  (typeof NEXORA_CONVERSATION_THREAD_REASONS)[number];
