export {
  ExecutiveReportingPlatform,
  ExecutiveReportingPlatformDescription,
  ExecutiveReportingPlatformFoundation,
  ExecutiveReportingPlatformId,
  ExecutiveReportingPlatformMetadata,
  ExecutiveReportingPlatformName,
  ExecutiveReportingPlatformNamespace,
  ExecutiveReportingPlatformVersion,
  buildExecutiveReportingPlatform,
  getExecutiveReportingPlatform,
  getExecutiveReportingPlatformDependencies,
  getExecutiveReportingPlatformMetadata,
  getExecutiveReportingPlatformPublicApi,
  getExecutiveReportingPlatformSummary,
} from "./executiveReportingPlatform.ts";
