import type {
  RevenueDriver,
  RevenueForecast,
  RevenueMetric,
  RevenueOpportunity,
  RevenueRisk,
  RevenueSource,
  RevenueStream,
  RevenueSummary,
  RevenueTarget,
} from "./executiveRevenueContracts.ts";
import {
  ExecutiveRevenueContractNamespace,
  ExecutiveRevenueContractVersion,
} from "./executiveRevenueContracts.ts";

export const ExecutiveRevenueRegistryId = "executive-revenue-registry" as const;

export const ExecutiveRevenueRegistryVersion = "1.0.0" as const;

export const ExecutiveRevenueRegistryNamespace = `${ExecutiveRevenueContractNamespace}.registry` as const;

export const ExecutiveRevenueRegistryDescription =
  "Canonical metadata-only registry layer for executive revenue intelligence." as const;

export const ExecutiveRevenueSourceRegistry: readonly RevenueSource[] = Object.freeze([
  Object.freeze({
    id: "revenue-source-product",
    code: "REV-SRC-PRODUCT",
    name: "Product Revenue",
    description: "Revenue originating from product sales.",
    category: "Product",
    owner: "Revenue Operations",
    status: "Active",
    tags: Object.freeze(["product", "core", "direct"]),
    metadataOnly: true,
    immutable: true,
  }),
  Object.freeze({
    id: "revenue-source-service",
    code: "REV-SRC-SERVICE",
    name: "Service Revenue",
    description: "Revenue originating from service delivery.",
    category: "Service",
    owner: "Services Leadership",
    status: "Active",
    tags: Object.freeze(["service", "delivery"]),
    metadataOnly: true,
    immutable: true,
  }),
  Object.freeze({
    id: "revenue-source-subscription",
    code: "REV-SRC-SUBSCRIPTION",
    name: "Subscription Revenue",
    description: "Revenue originating from subscription offerings.",
    category: "Subscription",
    owner: "Recurring Revenue Office",
    status: "Active",
    tags: Object.freeze(["subscription", "recurring"]),
    metadataOnly: true,
    immutable: true,
  }),
  Object.freeze({
    id: "revenue-source-consulting",
    code: "REV-SRC-CONSULTING",
    name: "Consulting Revenue",
    description: "Revenue originating from consulting engagements.",
    category: "Consulting",
    owner: "Consulting Practice",
    status: "Active",
    tags: Object.freeze(["consulting", "advisory"]),
    metadataOnly: true,
    immutable: true,
  }),
  Object.freeze({
    id: "revenue-source-partnership",
    code: "REV-SRC-PARTNERSHIP",
    name: "Partnership Revenue",
    description: "Revenue originating from partnerships and alliances.",
    category: "Partnership",
    owner: "Strategic Partnerships",
    status: "Active",
    tags: Object.freeze(["partner", "alliance"]),
    metadataOnly: true,
    immutable: true,
  }),
] as const);

export const ExecutiveRevenueStreamRegistry: readonly RevenueStream[] = Object.freeze([
  Object.freeze({
    streamId: "revenue-stream-product-recurring",
    sourceId: "revenue-source-product",
    streamType: "Recurring",
    businessUnit: "Core Products",
    product: "Platform Suite",
    customerSegment: "Enterprise",
    market: "North America",
    currency: "USD",
    status: "Active",
    metadataOnly: true,
    immutable: true,
  }),
  Object.freeze({
    streamId: "revenue-stream-service-projects",
    sourceId: "revenue-source-service",
    streamType: "NonRecurring",
    businessUnit: "Professional Services",
    product: "Implementation Services",
    customerSegment: "MidMarket",
    market: "Global",
    currency: "USD",
    status: "Active",
    metadataOnly: true,
    immutable: true,
  }),
  Object.freeze({
    streamId: "revenue-stream-subscription-annual",
    sourceId: "revenue-source-subscription",
    streamType: "Recurring",
    businessUnit: "Recurring Revenue",
    product: "Annual Subscription",
    customerSegment: "Enterprise",
    market: "EMEA",
    currency: "EUR",
    status: "Active",
    metadataOnly: true,
    immutable: true,
  }),
  Object.freeze({
    streamId: "revenue-stream-consulting-advisory",
    sourceId: "revenue-source-consulting",
    streamType: "Hybrid",
    businessUnit: "Advisory",
    product: "Executive Advisory",
    customerSegment: "Strategic Accounts",
    market: "North America",
    currency: "USD",
    status: "Active",
    metadataOnly: true,
    immutable: true,
  }),
  Object.freeze({
    streamId: "revenue-stream-partner-referral",
    sourceId: "revenue-source-partnership",
    streamType: "NonRecurring",
    businessUnit: "Partnerships",
    product: "Referral Revenue",
    customerSegment: "Channel",
    market: "APAC",
    currency: "USD",
    status: "Active",
    metadataOnly: true,
    immutable: true,
  }),
] as const);

export const ExecutiveRevenueMetricRegistry: readonly RevenueMetric[] = Object.freeze([
  Object.freeze({
    metricId: "revenue-metric-total-revenue",
    metricType: "TotalRevenue",
    name: "Total Revenue",
    description: "Executive total revenue metadata indicator.",
    owner: "Finance Leadership",
    status: "Active",
    tags: Object.freeze(["total", "executive"]),
    metadataOnly: true,
    immutable: true,
  }),
  Object.freeze({
    metricId: "revenue-metric-recurring-revenue",
    metricType: "RecurringRevenue",
    name: "Recurring Revenue",
    description: "Executive recurring revenue metadata indicator.",
    owner: "Revenue Operations",
    status: "Active",
    tags: Object.freeze(["recurring", "subscription"]),
    metadataOnly: true,
    immutable: true,
  }),
  Object.freeze({
    metricId: "revenue-metric-revenue-growth",
    metricType: "RevenueGrowth",
    name: "Revenue Growth",
    description: "Executive revenue growth metadata indicator.",
    owner: "Strategy Office",
    status: "Active",
    tags: Object.freeze(["growth", "trend"]),
    metadataOnly: true,
    immutable: true,
  }),
  Object.freeze({
    metricId: "revenue-metric-arpc",
    metricType: "AverageRevenuePerCustomer",
    name: "Average Revenue Per Customer",
    description: "Executive average revenue per customer metadata indicator.",
    owner: "Commercial Analytics",
    status: "Active",
    tags: Object.freeze(["customer", "yield"]),
    metadataOnly: true,
    immutable: true,
  }),
  Object.freeze({
    metricId: "revenue-metric-expansion-revenue",
    metricType: "ExpansionRevenue",
    name: "Expansion Revenue",
    description: "Executive expansion revenue metadata indicator.",
    owner: "Customer Growth",
    status: "Active",
    tags: Object.freeze(["expansion", "upsell"]),
    metadataOnly: true,
    immutable: true,
  }),
  Object.freeze({
    metricId: "revenue-metric-churn-revenue",
    metricType: "ChurnRevenue",
    name: "Churn Revenue",
    description: "Executive churn revenue metadata indicator.",
    owner: "Customer Success",
    status: "Active",
    tags: Object.freeze(["churn", "retention"]),
    metadataOnly: true,
    immutable: true,
  }),
  Object.freeze({
    metricId: "revenue-metric-forecasted-revenue",
    metricType: "AnnualRevenue",
    name: "Forecasted Revenue",
    description: "Executive forecasted revenue metadata indicator.",
    owner: "Planning Office",
    status: "Draft",
    tags: Object.freeze(["forecast", "planning"]),
    metadataOnly: true,
    immutable: true,
  }),
  Object.freeze({
    metricId: "revenue-metric-target-achievement",
    metricType: "NetRevenue",
    name: "Target Achievement",
    description: "Executive target achievement metadata indicator.",
    owner: "Finance Leadership",
    status: "Active",
    tags: Object.freeze(["target", "achievement"]),
    metadataOnly: true,
    immutable: true,
  }),
] as const);

export const ExecutiveRevenueDriverRegistry: readonly RevenueDriver[] = Object.freeze([
  Object.freeze({
    driverId: "revenue-driver-pricing",
    driverType: "Pricing",
    name: "Pricing",
    description: "Pricing influence on revenue performance.",
    owner: "Pricing Office",
    status: "Active",
    tags: Object.freeze(["pricing"]),
    metadataOnly: true,
    immutable: true,
  }),
  Object.freeze({
    driverId: "revenue-driver-acquisition",
    driverType: "CustomerAcquisition",
    name: "Customer Acquisition",
    description: "Acquisition influence on revenue performance.",
    owner: "Growth Marketing",
    status: "Active",
    tags: Object.freeze(["acquisition"]),
    metadataOnly: true,
    immutable: true,
  }),
  Object.freeze({
    driverId: "revenue-driver-retention",
    driverType: "Retention",
    name: "Retention",
    description: "Retention influence on revenue performance.",
    owner: "Customer Success",
    status: "Active",
    tags: Object.freeze(["retention"]),
    metadataOnly: true,
    immutable: true,
  }),
  Object.freeze({
    driverId: "revenue-driver-upsell",
    driverType: "Upsell",
    name: "Upsell",
    description: "Upsell influence on revenue performance.",
    owner: "Account Management",
    status: "Active",
    tags: Object.freeze(["upsell"]),
    metadataOnly: true,
    immutable: true,
  }),
  Object.freeze({
    driverId: "revenue-driver-crosssell",
    driverType: "CrossSell",
    name: "Cross-sell",
    description: "Cross-sell influence on revenue performance.",
    owner: "Commercial Strategy",
    status: "Active",
    tags: Object.freeze(["cross-sell"]),
    metadataOnly: true,
    immutable: true,
  }),
  Object.freeze({
    driverId: "revenue-driver-market-expansion",
    driverType: "MarketExpansion",
    name: "Market Expansion",
    description: "Market expansion influence on revenue performance.",
    owner: "Market Development",
    status: "Active",
    tags: Object.freeze(["market", "expansion"]),
    metadataOnly: true,
    immutable: true,
  }),
  Object.freeze({
    driverId: "revenue-driver-sales-capacity",
    driverType: "SalesCapacity",
    name: "Sales Capacity",
    description: "Sales capacity influence on revenue performance.",
    owner: "Sales Leadership",
    status: "Active",
    tags: Object.freeze(["capacity", "sales"]),
    metadataOnly: true,
    immutable: true,
  }),
  Object.freeze({
    driverId: "revenue-driver-product-mix",
    driverType: "ProductMix",
    name: "Product Mix",
    description: "Product mix influence on revenue performance.",
    owner: "Portfolio Strategy",
    status: "Active",
    tags: Object.freeze(["product-mix"]),
    metadataOnly: true,
    immutable: true,
  }),
] as const);

export const ExecutiveRevenueOpportunityRegistry: readonly RevenueOpportunity[] = Object.freeze([
  Object.freeze({
    opportunityId: "revenue-opportunity-enterprise-expansion",
    title: "Enterprise Expansion Motion",
    category: "Expansion",
    expectedImpact: "Strategic",
    confidence: "High",
    priority: "Strategic",
    owner: "Growth Office",
    status: "Active",
    metadataOnly: true,
    immutable: true,
  }),
  Object.freeze({
    opportunityId: "revenue-opportunity-pricing-optimization",
    title: "Pricing Optimization",
    category: "Pricing",
    expectedImpact: "High",
    confidence: "Medium",
    priority: "High",
    owner: "Pricing Office",
    status: "Draft",
    metadataOnly: true,
    immutable: true,
  }),
] as const);

export const ExecutiveRevenueRiskRegistry: readonly RevenueRisk[] = Object.freeze([
  Object.freeze({
    riskId: "revenue-risk-churn-acceleration",
    title: "Churn Acceleration",
    severity: "High",
    likelihood: "Medium",
    impactCategory: "CustomerChurn",
    owner: "Customer Success",
    mitigationReference: "retain-key-accounts",
    metadataOnly: true,
    immutable: true,
  }),
  Object.freeze({
    riskId: "revenue-risk-margin-pressure",
    title: "Margin Pressure",
    severity: "Medium",
    likelihood: "Medium",
    impactCategory: "MarginPressure",
    owner: "Finance Leadership",
    mitigationReference: "pricing-review",
    metadataOnly: true,
    immutable: true,
  }),
] as const);

export const ExecutiveRevenueForecastRegistry: readonly RevenueForecast[] = Object.freeze([
  Object.freeze({
    forecastId: "revenue-forecast-quarterly-baseline",
    forecastType: "Quarterly",
    period: "FY2026-Q3",
    baseline: 100,
    projectedRevenue: 112,
    confidence: "Medium",
    assumptions: Object.freeze(["pricing-stable", "retention-stable"]),
    status: "Draft",
    metadataOnly: true,
    immutable: true,
  }),
  Object.freeze({
    forecastId: "revenue-forecast-rolling-growth",
    forecastType: "Rolling",
    period: "FY2026-R12",
    baseline: 120,
    projectedRevenue: 130,
    confidence: "High",
    assumptions: Object.freeze(["expansion-motion", "sales-capacity"]),
    status: "Active",
    metadataOnly: true,
    immutable: true,
  }),
] as const);

export const ExecutiveRevenueTargetRegistry: readonly RevenueTarget[] = Object.freeze([
  Object.freeze({
    targetId: "revenue-target-fy2026-q3",
    period: "FY2026-Q3",
    targetRevenue: 115,
    actualRevenue: 109,
    variance: -6,
    status: "Active",
    metadataOnly: true,
    immutable: true,
  }),
  Object.freeze({
    targetId: "revenue-target-fy2026-annual",
    period: "FY2026",
    targetRevenue: 480,
    actualRevenue: 0,
    variance: 0,
    status: "Draft",
    metadataOnly: true,
    immutable: true,
  }),
] as const);

export const ExecutiveRevenueSummaryRegistry: readonly RevenueSummary[] = Object.freeze([
  Object.freeze({
    summaryId: "revenue-summary-fy2026-q2",
    reportingPeriod: "FY2026-Q2",
    totalRevenue: 108,
    growthRate: 12,
    targetAchievement: 94,
    forecastAccuracy: 91,
    overallStatus: "OnTrack",
    metadataOnly: true,
    immutable: true,
  }),
  Object.freeze({
    summaryId: "revenue-summary-fy2026-q3",
    reportingPeriod: "FY2026-Q3",
    totalRevenue: 109,
    growthRate: 10,
    targetAchievement: 95,
    forecastAccuracy: 89,
    overallStatus: "Watch",
    metadataOnly: true,
    immutable: true,
  }),
] as const);

export const ExecutiveRevenueRegistry = Object.freeze({
  registryId: ExecutiveRevenueRegistryId,
  registryVersion: ExecutiveRevenueRegistryVersion,
  registryNamespace: ExecutiveRevenueRegistryNamespace,
  registryDescription: ExecutiveRevenueRegistryDescription,
  sources: ExecutiveRevenueSourceRegistry,
  streams: ExecutiveRevenueStreamRegistry,
  metrics: ExecutiveRevenueMetricRegistry,
  drivers: ExecutiveRevenueDriverRegistry,
  opportunities: ExecutiveRevenueOpportunityRegistry,
  risks: ExecutiveRevenueRiskRegistry,
  forecasts: ExecutiveRevenueForecastRegistry,
  targets: ExecutiveRevenueTargetRegistry,
  summaries: ExecutiveRevenueSummaryRegistry,
  metadataOnly: true,
  immutable: true,
});
