import {
  ExecutiveRevenueContractNamespace,
  ExecutiveRevenueContractRegistry,
  ExecutiveRevenueContractTypes,
  ExecutiveRevenueContractVersion,
  ExecutiveRevenueContracts,
  ExecutiveRevenuePlatformDescription,
  ExecutiveRevenuePlatformName,
  RevenueForecastTypes,
  RevenueMetricTypes,
  RevenueOpportunityPriorities,
  RevenueRiskSeverities,
  RevenueSourceCategories,
  RevenueStatuses,
} from "./executiveRevenueContracts.ts";
import {
  ExecutiveRevenueDriverRegistry,
  ExecutiveRevenueForecastRegistry,
  ExecutiveRevenueMetricRegistry,
  ExecutiveRevenueOpportunityRegistry,
  ExecutiveRevenueRegistry,
  ExecutiveRevenueRegistryDescription,
  ExecutiveRevenueRegistryId,
  ExecutiveRevenueRegistryNamespace,
  ExecutiveRevenueRegistryVersion,
  ExecutiveRevenueRiskRegistry,
  ExecutiveRevenueSourceRegistry,
  ExecutiveRevenueStreamRegistry,
  ExecutiveRevenueSummaryRegistry,
  ExecutiveRevenueTargetRegistry,
} from "./executiveRevenueRegistry.ts";
import {
  ExecutiveRevenueModel,
  ExecutiveRevenueModelDependencyGraph,
  ExecutiveRevenueModelDescription,
  ExecutiveRevenueModelFoundation,
  ExecutiveRevenueModelId,
  ExecutiveRevenueModelNamespace,
  ExecutiveRevenueModelRelationships,
  ExecutiveRevenueModelVersion,
} from "./executiveRevenueModel.ts";
import {
  ExecutiveRevenueValidationChecklist,
  ExecutiveRevenueValidationDescription,
  ExecutiveRevenueValidationFoundation,
  ExecutiveRevenueValidationId,
  ExecutiveRevenueValidationMatrix,
  ExecutiveRevenueValidationNamespace,
  ExecutiveRevenueValidationResult,
  ExecutiveRevenueValidationRules,
  ExecutiveRevenueValidationVersion,
} from "./executiveRevenueValidation.ts";
import {
  ExecutiveRevenueManifest,
  ExecutiveRevenueManifestCompatibility,
  ExecutiveRevenueManifestDependencies,
  ExecutiveRevenueManifestDescription,
  ExecutiveRevenueManifestFoundation,
  ExecutiveRevenueManifestId,
  ExecutiveRevenueManifestNamespace,
  ExecutiveRevenueManifestPublicSurface,
  ExecutiveRevenueManifestVersion,
} from "./executiveRevenueManifest.ts";
import {
  ExecutiveRevenuePlatformDependencies,
  ExecutiveRevenuePlatformFoundation,
  ExecutiveRevenuePlatformId,
  ExecutiveRevenuePlatformNamespace,
  ExecutiveRevenuePlatformPublicApi,
  ExecutiveRevenuePlatformVersion,
} from "./executiveRevenuePlatform.ts";
import {
  ExecutiveRevenueCertificationDescription,
  ExecutiveRevenueCertificationChecklist,
  ExecutiveRevenueCertificationFoundation,
  ExecutiveRevenueCertificationGates,
  ExecutiveRevenueCertificationId,
  ExecutiveRevenueCertificationNamespace,
  ExecutiveRevenueCertificationResult,
  ExecutiveRevenueCertificationVersion,
} from "./executiveRevenueCertification.ts";
import {
  ExecutiveRevenueFreezeCompatibility,
  ExecutiveRevenueFreezeDependencies,
  ExecutiveRevenueFreezeDescription,
  ExecutiveRevenueFreezeFoundation,
  ExecutiveRevenueFreezeId,
  ExecutiveRevenueFreezeNamespace,
  ExecutiveRevenueFreezePublicApi,
  ExecutiveRevenueFreezeResult,
  ExecutiveRevenueFreezeVersion,
} from "./executiveRevenueFreeze.ts";

export const ExecutiveRevenuePublicIndexId = "executive-revenue-public-index" as const;

export const ExecutiveRevenuePublicIndexVersion = "1.0.0" as const;

export const ExecutiveRevenuePublicIndexNamespace =
  `${ExecutiveRevenueContractNamespace}.public-index` as const;

export const ExecutiveRevenuePublicIndexDescription =
  "Final canonical metadata-only public index for the Executive Revenue Intelligence Platform." as const;

export const ExecutiveRevenuePublicIndexStatus = Object.freeze({
  certified: ExecutiveRevenueFreezeResult.certified,
  frozen: ExecutiveRevenueFreezeResult.frozen,
  released: ExecutiveRevenueFreezeResult.released,
  metadataOnly: true,
  publicApiStable: ExecutiveRevenueFreezeResult.publicApiStable,
  immutable: true,
} as const);

export const ExecutiveRevenueIntelligencePublicFoundation = Object.freeze({
  contracts: Object.freeze({
    ExecutiveRevenueContractNamespace,
    ExecutiveRevenueContractRegistry,
    ExecutiveRevenueContractTypes,
    ExecutiveRevenueContractVersion,
    ExecutiveRevenueContracts,
    ExecutiveRevenuePlatformDescription,
    ExecutiveRevenuePlatformName,
    RevenueForecastTypes,
    RevenueMetricTypes,
    RevenueOpportunityPriorities,
    RevenueRiskSeverities,
    RevenueSourceCategories,
    RevenueStatuses,
    metadataOnly: true,
    immutable: true,
  }),
  registry: Object.freeze({
    ExecutiveRevenueDriverRegistry,
    ExecutiveRevenueForecastRegistry,
    ExecutiveRevenueMetricRegistry,
    ExecutiveRevenueOpportunityRegistry,
    ExecutiveRevenueRegistry,
    ExecutiveRevenueRegistryDescription,
    ExecutiveRevenueRegistryId,
    ExecutiveRevenueRegistryNamespace,
    ExecutiveRevenueRegistryVersion,
    ExecutiveRevenueRiskRegistry,
    ExecutiveRevenueSourceRegistry,
    ExecutiveRevenueStreamRegistry,
    ExecutiveRevenueSummaryRegistry,
    ExecutiveRevenueTargetRegistry,
    metadataOnly: true,
    immutable: true,
  }),
  model: Object.freeze({
    ExecutiveRevenueModel,
    ExecutiveRevenueModelDependencyGraph,
    ExecutiveRevenueModelDescription,
    ExecutiveRevenueModelFoundation,
    ExecutiveRevenueModelId,
    ExecutiveRevenueModelNamespace,
    ExecutiveRevenueModelRelationships,
    ExecutiveRevenueModelVersion,
    metadataOnly: true,
    immutable: true,
  }),
  validation: Object.freeze({
    ExecutiveRevenueValidationChecklist,
    ExecutiveRevenueValidationDescription,
    ExecutiveRevenueValidationFoundation,
    ExecutiveRevenueValidationId,
    ExecutiveRevenueValidationMatrix,
    ExecutiveRevenueValidationNamespace,
    ExecutiveRevenueValidationResult,
    ExecutiveRevenueValidationRules,
    ExecutiveRevenueValidationVersion,
    metadataOnly: true,
    immutable: true,
  }),
  manifest: Object.freeze({
    ExecutiveRevenueManifest,
    ExecutiveRevenueManifestCompatibility,
    ExecutiveRevenueManifestDependencies,
    ExecutiveRevenueManifestDescription,
    ExecutiveRevenueManifestFoundation,
    ExecutiveRevenueManifestId,
    ExecutiveRevenueManifestNamespace,
    ExecutiveRevenueManifestPublicSurface,
    ExecutiveRevenueManifestVersion,
    metadataOnly: true,
    immutable: true,
  }),
  platform: Object.freeze({
    ExecutiveRevenuePlatformDependencies,
    ExecutiveRevenuePlatformFoundation,
    ExecutiveRevenuePlatformId,
    ExecutiveRevenuePlatformNamespace,
    ExecutiveRevenuePlatformPublicApi,
    ExecutiveRevenuePlatformVersion,
    ExecutiveRevenuePlatformDescription,
    metadataOnly: true,
    immutable: true,
  }),
  certification: Object.freeze({
    ExecutiveRevenueCertificationDescription,
    ExecutiveRevenueCertificationChecklist,
    ExecutiveRevenueCertificationFoundation,
    ExecutiveRevenueCertificationGates,
    ExecutiveRevenueCertificationId,
    ExecutiveRevenueCertificationNamespace,
    ExecutiveRevenueCertificationResult,
    ExecutiveRevenueCertificationVersion,
    metadataOnly: true,
    immutable: true,
  }),
  freeze: Object.freeze({
    ExecutiveRevenueFreezeCompatibility,
    ExecutiveRevenueFreezeDependencies,
    ExecutiveRevenueFreezeDescription,
    ExecutiveRevenueFreezeFoundation,
    ExecutiveRevenueFreezeId,
    ExecutiveRevenueFreezeNamespace,
    ExecutiveRevenueFreezePublicApi,
    ExecutiveRevenueFreezeResult,
    ExecutiveRevenueFreezeVersion,
    metadataOnly: true,
    immutable: true,
  }),
  publicIndex: Object.freeze({
    ExecutiveRevenuePublicIndexId,
    ExecutiveRevenuePublicIndexVersion,
    ExecutiveRevenuePublicIndexNamespace,
    ExecutiveRevenuePublicIndexDescription,
    ExecutiveRevenuePublicIndexStatus,
    metadataOnly: true,
    immutable: true,
  }),
  metadataOnly: true,
  immutable: true,
});
