import type {
  ExecutiveKpiConsumerEntry,
  ExecutiveKpiIntegrationCategory,
  ExecutiveKpiIntegrationDependency,
  ExecutiveKpiIntegrationLifecycleState,
  ExecutiveKpiIntegrationPhase,
  ExecutiveKpiIntegrationRegistry,
} from "./executiveKpiIntegrationTypes.ts";

export const EXECUTIVE_KPI_INTEGRATION_CATEGORIES: readonly ExecutiveKpiIntegrationCategory[] = Object.freeze([
  "Foundation",
  "Definition",
  "Source Mapping",
  "Targeting",
  "Governance",
  "Scorecard",
  "Insight Metadata",
  "Strategic Alignment",
  "Business Impact",
  "Reporting",
  "Compatibility",
  "Public API",
  "Consumer Contract",
] as const);

export const EXECUTIVE_KPI_INTEGRATION_LIFECYCLE_STATES: readonly ExecutiveKpiIntegrationLifecycleState[] = Object.freeze([
  "Draft",
  "Candidate",
  "Approved",
  "Active",
  "Deprecated",
  "Archived",
  "Frozen",
] as const);

export const EXECUTIVE_KPI_INTEGRATION_PHASES: readonly ExecutiveKpiIntegrationPhase[] = Object.freeze([
  Object.freeze({
    integrationId: "bus-1-foundation-integration",
    platformName: "Executive KPI Platform",
    phaseId: "BUS-1",
    phaseName: "Executive KPI Platform Foundation",
    phaseStatus: "Certified",
    phaseDependencyIds: Object.freeze([] as const),
    requiredPublicApis: Object.freeze([] as const),
    providedPublicApis: Object.freeze(["getExecutiveKpiPlatform", "getExecutiveKpiPlatformManifest", "validateExecutiveKpiPlatform"] as const),
    compatibilityStatus: "Compatible",
    consumerLayer: "BUS",
    integrationCategory: "Foundation",
    lifecycleState: "Active",
    metadata: Object.freeze({ metadataId: "bus-1-integration-metadata", metadataOnly: true, immutable: true }),
    metadataOnly: true,
    immutable: true,
  }),
  Object.freeze({
    integrationId: "bus-2-definition-integration",
    platformName: "Executive KPI Definition Platform",
    phaseId: "BUS-2",
    phaseName: "Executive KPI Definition Platform",
    phaseStatus: "Certified",
    phaseDependencyIds: Object.freeze(["BUS-1"] as const),
    requiredPublicApis: Object.freeze(["getExecutiveKpiPlatform"] as const),
    providedPublicApis: Object.freeze(["getExecutiveKpiDefinitionPlatform", "listExecutiveKpiDefinitions", "validateExecutiveKpiDefinitions"] as const),
    compatibilityStatus: "Compatible",
    consumerLayer: "BUS",
    integrationCategory: "Definition",
    lifecycleState: "Active",
    metadata: Object.freeze({ metadataId: "bus-2-integration-metadata", metadataOnly: true, immutable: true }),
    metadataOnly: true,
    immutable: true,
  }),
  Object.freeze({
    integrationId: "bus-3-source-mapping-integration",
    platformName: "Executive KPI Source Mapping Platform",
    phaseId: "BUS-3",
    phaseName: "Executive KPI Source Mapping Platform",
    phaseStatus: "Certified",
    phaseDependencyIds: Object.freeze(["BUS-1", "BUS-2"] as const),
    requiredPublicApis: Object.freeze(["getExecutiveKpiPlatform", "getExecutiveKpiDefinitionPlatform"] as const),
    providedPublicApis: Object.freeze(["getExecutiveKpiSourceMappingPlatform", "listExecutiveKpiSourceMappings", "validateExecutiveKpiSourceMappings"] as const),
    compatibilityStatus: "Compatible",
    consumerLayer: "BUS",
    integrationCategory: "Source Mapping",
    lifecycleState: "Active",
    metadata: Object.freeze({ metadataId: "bus-3-integration-metadata", metadataOnly: true, immutable: true }),
    metadataOnly: true,
    immutable: true,
  }),
  Object.freeze({
    integrationId: "bus-4-targeting-integration",
    platformName: "Executive KPI Target and Threshold Platform",
    phaseId: "BUS-4",
    phaseName: "Executive KPI Target and Threshold Platform",
    phaseStatus: "Certified",
    phaseDependencyIds: Object.freeze(["BUS-1", "BUS-2", "BUS-3"] as const),
    requiredPublicApis: Object.freeze(["getExecutiveKpiDefinitionPlatform", "getExecutiveKpiSourceMappingPlatform"] as const),
    providedPublicApis: Object.freeze(["getExecutiveKpiTargetPlatform", "listExecutiveKpiTargets", "validateExecutiveKpiTargets"] as const),
    compatibilityStatus: "Compatible",
    consumerLayer: "BUS",
    integrationCategory: "Targeting",
    lifecycleState: "Active",
    metadata: Object.freeze({ metadataId: "bus-4-integration-metadata", metadataOnly: true, immutable: true }),
    metadataOnly: true,
    immutable: true,
  }),
  Object.freeze({
    integrationId: "bus-5-governance-integration",
    platformName: "Executive KPI Governance Platform",
    phaseId: "BUS-5",
    phaseName: "Executive KPI Governance Platform",
    phaseStatus: "Certified",
    phaseDependencyIds: Object.freeze(["BUS-1", "BUS-2", "BUS-3", "BUS-4"] as const),
    requiredPublicApis: Object.freeze(["getExecutiveKpiDefinitionPlatform", "getExecutiveKpiTargetPlatform"] as const),
    providedPublicApis: Object.freeze(["getExecutiveKpiGovernancePlatform", "listExecutiveKpiGovernance", "validateExecutiveKpiGovernance"] as const),
    compatibilityStatus: "Compatible",
    consumerLayer: "BUS",
    integrationCategory: "Governance",
    lifecycleState: "Active",
    metadata: Object.freeze({ metadataId: "bus-5-integration-metadata", metadataOnly: true, immutable: true }),
    metadataOnly: true,
    immutable: true,
  }),
  Object.freeze({
    integrationId: "bus-6-scorecard-integration",
    platformName: "Executive KPI Scorecard Platform",
    phaseId: "BUS-6",
    phaseName: "Executive KPI Scorecard Platform",
    phaseStatus: "Certified",
    phaseDependencyIds: Object.freeze(["BUS-1", "BUS-2", "BUS-3", "BUS-4", "BUS-5"] as const),
    requiredPublicApis: Object.freeze(["getExecutiveKpiDefinitionPlatform", "getExecutiveKpiGovernancePlatform"] as const),
    providedPublicApis: Object.freeze(["getExecutiveKpiScorecardPlatform", "listExecutiveKpiScorecards", "validateExecutiveKpiScorecards"] as const),
    compatibilityStatus: "Compatible",
    consumerLayer: "BUS",
    integrationCategory: "Scorecard",
    lifecycleState: "Active",
    metadata: Object.freeze({ metadataId: "bus-6-integration-metadata", metadataOnly: true, immutable: true }),
    metadataOnly: true,
    immutable: true,
  }),
  Object.freeze({
    integrationId: "bus-7-insight-integration",
    platformName: "Executive KPI Insight Metadata Platform",
    phaseId: "BUS-7",
    phaseName: "Executive KPI Insight Metadata Platform",
    phaseStatus: "Certified",
    phaseDependencyIds: Object.freeze(["BUS-1", "BUS-2", "BUS-3", "BUS-4", "BUS-5", "BUS-6"] as const),
    requiredPublicApis: Object.freeze(["getExecutiveKpiScorecardPlatform"] as const),
    providedPublicApis: Object.freeze(["getExecutiveKpiInsightPlatform", "listExecutiveKpiInsights", "validateExecutiveKpiInsights"] as const),
    compatibilityStatus: "Compatible",
    consumerLayer: "BUS",
    integrationCategory: "Insight Metadata",
    lifecycleState: "Active",
    metadata: Object.freeze({ metadataId: "bus-7-integration-metadata", metadataOnly: true, immutable: true }),
    metadataOnly: true,
    immutable: true,
  }),
  Object.freeze({
    integrationId: "bus-8-strategic-alignment-integration",
    platformName: "Executive KPI Strategic Alignment Platform",
    phaseId: "BUS-8",
    phaseName: "Executive KPI Strategic Alignment Platform",
    phaseStatus: "Certified",
    phaseDependencyIds: Object.freeze(["BUS-1", "BUS-2", "BUS-3", "BUS-4", "BUS-5", "BUS-6", "BUS-7"] as const),
    requiredPublicApis: Object.freeze(["getExecutiveKpiInsightPlatform"] as const),
    providedPublicApis: Object.freeze(["getExecutiveKpiStrategicAlignmentPlatform", "listExecutiveKpiStrategicAlignments", "validateExecutiveKpiStrategicAlignments"] as const),
    compatibilityStatus: "Compatible",
    consumerLayer: "BUS",
    integrationCategory: "Strategic Alignment",
    lifecycleState: "Active",
    metadata: Object.freeze({ metadataId: "bus-8-integration-metadata", metadataOnly: true, immutable: true }),
    metadataOnly: true,
    immutable: true,
  }),
  Object.freeze({
    integrationId: "bus-9-business-impact-integration",
    platformName: "Executive KPI Business Impact Metadata Platform",
    phaseId: "BUS-9",
    phaseName: "Executive KPI Business Impact Metadata Platform",
    phaseStatus: "Certified",
    phaseDependencyIds: Object.freeze(["BUS-1", "BUS-2", "BUS-3", "BUS-4", "BUS-5", "BUS-6", "BUS-7", "BUS-8"] as const),
    requiredPublicApis: Object.freeze(["getExecutiveKpiStrategicAlignmentPlatform"] as const),
    providedPublicApis: Object.freeze(["getExecutiveKpiBusinessImpactPlatform", "listExecutiveKpiBusinessImpacts", "validateExecutiveKpiBusinessImpacts"] as const),
    compatibilityStatus: "Compatible",
    consumerLayer: "BUS",
    integrationCategory: "Business Impact",
    lifecycleState: "Active",
    metadata: Object.freeze({ metadataId: "bus-9-integration-metadata", metadataOnly: true, immutable: true }),
    metadataOnly: true,
    immutable: true,
  }),
  Object.freeze({
    integrationId: "bus-10-reporting-integration",
    platformName: "Executive KPI Reporting Metadata Platform",
    phaseId: "BUS-10",
    phaseName: "Executive KPI Reporting Metadata Platform",
    phaseStatus: "Certified",
    phaseDependencyIds: Object.freeze(["BUS-1", "BUS-2", "BUS-3", "BUS-4", "BUS-5", "BUS-6", "BUS-7", "BUS-8", "BUS-9"] as const),
    requiredPublicApis: Object.freeze(["getExecutiveKpiBusinessImpactPlatform"] as const),
    providedPublicApis: Object.freeze(["getExecutiveKpiReportingPlatform", "listExecutiveKpiReports", "validateExecutiveKpiReporting"] as const),
    compatibilityStatus: "Compatible",
    consumerLayer: "BUS",
    integrationCategory: "Reporting",
    lifecycleState: "Active",
    metadata: Object.freeze({ metadataId: "bus-10-integration-metadata", metadataOnly: true, immutable: true }),
    metadataOnly: true,
    immutable: true,
  }),
] as const);

export const EXECUTIVE_KPI_INTEGRATION_DEPENDENCIES: readonly ExecutiveKpiIntegrationDependency[] = Object.freeze(
  EXECUTIVE_KPI_INTEGRATION_PHASES.map((phase) =>
    Object.freeze({
      dependencyId: `${phase.phaseId.toLowerCase()}-dependency-map`,
      phaseId: phase.phaseId,
      dependsOnPhaseIds: phase.phaseDependencyIds,
      dependencyType: "Public API",
      metadataOnly: true,
    })
  )
);

export const EXECUTIVE_KPI_CONSUMER_REGISTRY: readonly ExecutiveKpiConsumerEntry[] = Object.freeze([
  Object.freeze({ consumerId: "executive-dashboard", consumerName: "Executive Dashboard", consumerLayer: "APP", consumptionBoundary: "Public API Only", metadataOnly: true, immutable: true }),
  Object.freeze({ consumerId: "executive-advisor", consumerName: "Executive Advisor", consumerLayer: "ASS", consumptionBoundary: "Public API Only", metadataOnly: true, immutable: true }),
  Object.freeze({ consumerId: "scenario-platform", consumerName: "Scenario Platform", consumerLayer: "STE", consumptionBoundary: "Public API Only", metadataOnly: true, immutable: true }),
  Object.freeze({ consumerId: "reporting-platform", consumerName: "Reporting Platform", consumerLayer: "APP", consumptionBoundary: "Public API Only", metadataOnly: true, immutable: true }),
  Object.freeze({ consumerId: "business-intelligence-platform", consumerName: "Business Intelligence Platform", consumerLayer: "BUS", consumptionBoundary: "Public API Only", metadataOnly: true, immutable: true }),
  Object.freeze({ consumerId: "operations-platform", consumerName: "Operations Platform", consumerLayer: "OPS", consumptionBoundary: "Public API Only", metadataOnly: true, immutable: true }),
  Object.freeze({ consumerId: "founder-advisor", consumerName: "Founder Advisor", consumerLayer: "ASS", consumptionBoundary: "Public API Only", metadataOnly: true, immutable: true }),
  Object.freeze({ consumerId: "growth-advisor", consumerName: "Growth Advisor", consumerLayer: "ASS", consumptionBoundary: "Public API Only", metadataOnly: true, immutable: true }),
  Object.freeze({ consumerId: "future-external-consumers", consumerName: "Future External Consumers", consumerLayer: "EXT", consumptionBoundary: "Public API Only", metadataOnly: true, immutable: true }),
] as const);

export const EXECUTIVE_KPI_INTEGRATION_PUBLIC_APIS: readonly string[] = Object.freeze([
  "ExecutiveKpiIntegrationPlatform",
  "getExecutiveKpiIntegrationPlatform",
  "getExecutiveKpiIntegrationManifest",
  "validateExecutiveKpiIntegration",
  "listExecutiveKpiIntegrationPhases",
  "listExecutiveKpiIntegrationDependencies",
  "listExecutiveKpiCompatibilityMatrix",
  "listExecutiveKpiConsumerRegistry",
  "listExecutiveKpiIntegrationLifecycleStates",
] as const);

export const EXECUTIVE_KPI_INTEGRATION_REGISTRY: ExecutiveKpiIntegrationRegistry = Object.freeze({
  platformId: "BUS-11",
  platformName: "Executive KPI Integration Platform",
  version: "1.0.0",
  integratedPhaseIds: Object.freeze(["BUS-1", "BUS-2", "BUS-3", "BUS-4", "BUS-5", "BUS-6", "BUS-7", "BUS-8", "BUS-9", "BUS-10"] as const),
  phases: EXECUTIVE_KPI_INTEGRATION_PHASES,
  dependencies: EXECUTIVE_KPI_INTEGRATION_DEPENDENCIES,
  categories: EXECUTIVE_KPI_INTEGRATION_CATEGORIES,
  consumers: EXECUTIVE_KPI_CONSUMER_REGISTRY,
  lifecycleStates: EXECUTIVE_KPI_INTEGRATION_LIFECYCLE_STATES,
  publicApis: EXECUTIVE_KPI_INTEGRATION_PUBLIC_APIS,
  metadataOnly: true,
  immutable: true,
});

export function listExecutiveKpiIntegrationPhases(): readonly ExecutiveKpiIntegrationPhase[] {
  return EXECUTIVE_KPI_INTEGRATION_PHASES;
}

export function listExecutiveKpiIntegrationDependencies(): readonly ExecutiveKpiIntegrationDependency[] {
  return EXECUTIVE_KPI_INTEGRATION_DEPENDENCIES;
}

export function listExecutiveKpiConsumerRegistry(): readonly ExecutiveKpiConsumerEntry[] {
  return EXECUTIVE_KPI_CONSUMER_REGISTRY;
}

export function listExecutiveKpiIntegrationLifecycleStates(): readonly ExecutiveKpiIntegrationLifecycleState[] {
  return EXECUTIVE_KPI_INTEGRATION_LIFECYCLE_STATES;
}
