import type {
  FinanceModelRelationship,
  FinanceRelationshipRegistry as FinanceRelationshipRegistryContract,
} from "./financeModelTypes.ts";

const FINANCE_MODEL_RELATIONSHIPS: readonly FinanceModelRelationship[] = Object.freeze([
  Object.freeze({
    relationshipId: "finance-relationship-revenue-profit",
    source: "Revenue",
    target: "Profit",
    relationshipType: "contributesTo",
    description: "Revenue contributes to Profit.",
    metadataOnly: true,
    immutable: true,
  }),
  Object.freeze({
    relationshipId: "finance-relationship-expense-profit",
    source: "Expense",
    target: "Profit",
    relationshipType: "reduces",
    description: "Expense reduces Profit.",
    metadataOnly: true,
    immutable: true,
  }),
  Object.freeze({
    relationshipId: "finance-relationship-cost-expense",
    source: "Cost",
    target: "Expense",
    relationshipType: "belongsTo",
    description: "Cost belongs to Expense.",
    metadataOnly: true,
    immutable: true,
  }),
  Object.freeze({
    relationshipId: "finance-relationship-budget-expense",
    source: "Budget",
    target: "Expense",
    relationshipType: "governs",
    description: "Budget governs Expense.",
    metadataOnly: true,
    immutable: true,
  }),
  Object.freeze({
    relationshipId: "finance-relationship-forecast-revenue",
    source: "Forecast",
    target: "Revenue",
    relationshipType: "predicts",
    description: "Forecast predicts Revenue.",
    metadataOnly: true,
    immutable: true,
  }),
  Object.freeze({
    relationshipId: "finance-relationship-invoice-payment",
    source: "Invoice",
    target: "Payment",
    relationshipType: "requests",
    description: "Invoice requests Payment.",
    metadataOnly: true,
    immutable: true,
  }),
  Object.freeze({
    relationshipId: "finance-relationship-payment-cashflow",
    source: "Payment",
    target: "CashFlow",
    relationshipType: "affects",
    description: "Payment affects CashFlow.",
    metadataOnly: true,
    immutable: true,
  }),
  Object.freeze({
    relationshipId: "finance-relationship-cashflow-payment",
    source: "CashFlow",
    target: "Payment",
    relationshipType: "summarizes",
    description: "CashFlow summarizes Payments.",
    metadataOnly: true,
    immutable: true,
  }),
  Object.freeze({
    relationshipId: "finance-relationship-asset-financialposition",
    source: "Asset",
    target: "FinancialPosition",
    relationshipType: "belongsTo",
    description: "Asset belongs to FinancialPosition.",
    metadataOnly: true,
    immutable: true,
  }),
  Object.freeze({
    relationshipId: "finance-relationship-liability-financialposition",
    source: "Liability",
    target: "FinancialPosition",
    relationshipType: "belongsTo",
    description: "Liability belongs to FinancialPosition.",
    metadataOnly: true,
    immutable: true,
  }),
  Object.freeze({
    relationshipId: "finance-relationship-equity-financialposition",
    source: "Equity",
    target: "FinancialPosition",
    relationshipType: "belongsTo",
    description: "Equity belongs to FinancialPosition.",
    metadataOnly: true,
    immutable: true,
  }),
  Object.freeze({
    relationshipId: "finance-relationship-statement-revenue",
    source: "FinancialStatement",
    target: "Revenue",
    relationshipType: "summarizes",
    description: "FinancialStatement summarizes Revenue.",
    metadataOnly: true,
    immutable: true,
  }),
  Object.freeze({
    relationshipId: "finance-relationship-statement-expense",
    source: "FinancialStatement",
    target: "Expense",
    relationshipType: "summarizes",
    description: "FinancialStatement summarizes Expense.",
    metadataOnly: true,
    immutable: true,
  }),
  Object.freeze({
    relationshipId: "finance-relationship-statement-asset",
    source: "FinancialStatement",
    target: "Asset",
    relationshipType: "summarizes",
    description: "FinancialStatement summarizes Asset.",
    metadataOnly: true,
    immutable: true,
  }),
  Object.freeze({
    relationshipId: "finance-relationship-statement-liability",
    source: "FinancialStatement",
    target: "Liability",
    relationshipType: "summarizes",
    description: "FinancialStatement summarizes Liability.",
    metadataOnly: true,
    immutable: true,
  }),
  Object.freeze({
    relationshipId: "finance-relationship-statement-equity",
    source: "FinancialStatement",
    target: "Equity",
    relationshipType: "summarizes",
    description: "FinancialStatement summarizes Equity.",
    metadataOnly: true,
    immutable: true,
  }),
  Object.freeze({
    relationshipId: "finance-relationship-period-statement",
    source: "FinancialPeriod",
    target: "FinancialStatement",
    relationshipType: "scopes",
    description: "FinancialPeriod scopes FinancialStatement.",
    metadataOnly: true,
    immutable: true,
  }),
] as const);

export const FinanceRelationshipRegistry: FinanceRelationshipRegistryContract = Object.freeze({
  registryId: "finance-relationship-registry",
  version: "1.0.0",
  relationships: FINANCE_MODEL_RELATIONSHIPS,
  metadataOnly: true,
  immutable: true,
});

export function getFinanceRelationships(): FinanceRelationshipRegistryContract {
  return FinanceRelationshipRegistry;
}
