import type { DependencyPublicSurfaceEntry } from "./dependencyManifestTypes.ts";

export const DependencyPlatformPublicSurface = Object.freeze([
  Object.freeze({
    exportName: "ExecutiveDependencyIntelligenceFoundation",
    phaseId: "OPS-7:1",
    exportKind: "Object",
    stability: "Stable",
    metadataOnly: true,
  } as const satisfies DependencyPublicSurfaceEntry),
  Object.freeze({
    exportName: "getExecutiveDependencyFoundation",
    phaseId: "OPS-7:1",
    exportKind: "Function",
    stability: "Stable",
    metadataOnly: true,
  } as const satisfies DependencyPublicSurfaceEntry),
  Object.freeze({
    exportName: "getExecutiveDependencyMetadata",
    phaseId: "OPS-7:1",
    exportKind: "Function",
    stability: "Stable",
    metadataOnly: true,
  } as const satisfies DependencyPublicSurfaceEntry),
  Object.freeze({
    exportName: "ExecutiveDependencyRegistry",
    phaseId: "OPS-7:2",
    exportKind: "Object",
    stability: "Stable",
    metadataOnly: true,
  } as const satisfies DependencyPublicSurfaceEntry),
  Object.freeze({
    exportName: "getDependencyEntityRegistry",
    phaseId: "OPS-7:2",
    exportKind: "Function",
    stability: "Stable",
    metadataOnly: true,
  } as const satisfies DependencyPublicSurfaceEntry),
  Object.freeze({
    exportName: "getDependencyRelationshipRegistry",
    phaseId: "OPS-7:2",
    exportKind: "Function",
    stability: "Stable",
    metadataOnly: true,
  } as const satisfies DependencyPublicSurfaceEntry),
  Object.freeze({
    exportName: "getDependencyLifecycleRegistry",
    phaseId: "OPS-7:2",
    exportKind: "Function",
    stability: "Stable",
    metadataOnly: true,
  } as const satisfies DependencyPublicSurfaceEntry),
  Object.freeze({
    exportName: "ExecutiveDependencyModel",
    phaseId: "OPS-7:3",
    exportKind: "Object",
    stability: "Stable",
    metadataOnly: true,
  } as const satisfies DependencyPublicSurfaceEntry),
  Object.freeze({
    exportName: "getExecutiveDependencyModel",
    phaseId: "OPS-7:3",
    exportKind: "Function",
    stability: "Stable",
    metadataOnly: true,
  } as const satisfies DependencyPublicSurfaceEntry),
  Object.freeze({
    exportName: "getDependencyGraphModel",
    phaseId: "OPS-7:3",
    exportKind: "Function",
    stability: "Stable",
    metadataOnly: true,
  } as const satisfies DependencyPublicSurfaceEntry),
  Object.freeze({
    exportName: "getDependencyImpactModel",
    phaseId: "OPS-7:3",
    exportKind: "Function",
    stability: "Stable",
    metadataOnly: true,
  } as const satisfies DependencyPublicSurfaceEntry),
  Object.freeze({
    exportName: "validateDependencyFoundation",
    phaseId: "OPS-7:4",
    exportKind: "Function",
    stability: "Stable",
    metadataOnly: true,
  } as const satisfies DependencyPublicSurfaceEntry),
  Object.freeze({
    exportName: "validateDependencyRegistry",
    phaseId: "OPS-7:4",
    exportKind: "Function",
    stability: "Stable",
    metadataOnly: true,
  } as const satisfies DependencyPublicSurfaceEntry),
  Object.freeze({
    exportName: "validateDependencyModel",
    phaseId: "OPS-7:4",
    exportKind: "Function",
    stability: "Stable",
    metadataOnly: true,
  } as const satisfies DependencyPublicSurfaceEntry),
  Object.freeze({
    exportName: "validateDependencyPlatform",
    phaseId: "OPS-7:4",
    exportKind: "Function",
    stability: "Stable",
    metadataOnly: true,
  } as const satisfies DependencyPublicSurfaceEntry),
  Object.freeze({
    exportName: "validateExecutiveDependencyPlatform",
    phaseId: "OPS-7:4",
    exportKind: "Function",
    stability: "Stable",
    metadataOnly: true,
  } as const satisfies DependencyPublicSurfaceEntry),
] as const);

export const DependencyPlatformPublicSurfaceMetadata = Object.freeze({
  publicSurfaceId: "ops.executive-dependency.platform-public-surface",
  publicSurfaceVersion: "1.0.0",
  exportCount: DependencyPlatformPublicSurface.length,
  metadataOnly: true,
  immutable: true,
} as const);
