export const ExecutiveSchedulingPlatformCompatibility = Object.freeze({
  internal: Object.freeze([
    Object.freeze({
      target: "OPS-6:1",
      compatibilityStatus: "Compatible",
      dependencyStatus: "Satisfied",
      publicApiCompatibility: "Stable",
      certificationCompatibility: "Ready",
      manifestCompatibility: "Complete",
      metadataOnly: true,
    }),
    Object.freeze({
      target: "OPS-6:2",
      compatibilityStatus: "Compatible",
      dependencyStatus: "Satisfied",
      publicApiCompatibility: "Stable",
      certificationCompatibility: "Ready",
      manifestCompatibility: "Complete",
      metadataOnly: true,
    }),
    Object.freeze({
      target: "OPS-6:3",
      compatibilityStatus: "Compatible",
      dependencyStatus: "Satisfied",
      publicApiCompatibility: "Stable",
      certificationCompatibility: "Ready",
      manifestCompatibility: "Complete",
      metadataOnly: true,
    }),
    Object.freeze({
      target: "OPS-6:4",
      compatibilityStatus: "Compatible",
      dependencyStatus: "Satisfied",
      publicApiCompatibility: "Stable",
      certificationCompatibility: "Ready",
      manifestCompatibility: "Complete",
      metadataOnly: true,
    }),
    Object.freeze({
      target: "OPS-6:5",
      compatibilityStatus: "Compatible",
      dependencyStatus: "Satisfied",
      publicApiCompatibility: "Stable",
      certificationCompatibility: "Ready",
      manifestCompatibility: "Complete",
      metadataOnly: true,
    }),
    Object.freeze({
      target: "OPS-6:6",
      compatibilityStatus: "Compatible",
      dependencyStatus: "Satisfied",
      publicApiCompatibility: "Stable",
      certificationCompatibility: "Ready",
      manifestCompatibility: "Complete",
      metadataOnly: true,
    }),
  ] as const),
  crossPlatform: Object.freeze([
    Object.freeze({
      target: "OPS-2 Task Platform",
      compatibilityStatus: "Compatible",
      dependencyStatus: "Satisfied",
      publicApiCompatibility: "Stable",
      certificationCompatibility: "Ready",
      manifestCompatibility: "Complete",
      metadataOnly: true,
    }),
    Object.freeze({
      target: "OPS-3 Workflow Platform",
      compatibilityStatus: "Compatible",
      dependencyStatus: "Satisfied",
      publicApiCompatibility: "Stable",
      certificationCompatibility: "Ready",
      manifestCompatibility: "Complete",
      metadataOnly: true,
    }),
    Object.freeze({
      target: "OPS-4 Project Platform",
      compatibilityStatus: "Compatible",
      dependencyStatus: "Satisfied",
      publicApiCompatibility: "Stable",
      certificationCompatibility: "Ready",
      manifestCompatibility: "Complete",
      metadataOnly: true,
    }),
    Object.freeze({
      target: "OPS-5 Resource Platform",
      compatibilityStatus: "Compatible",
      dependencyStatus: "Satisfied",
      publicApiCompatibility: "Stable",
      certificationCompatibility: "Ready",
      manifestCompatibility: "Complete",
      metadataOnly: true,
    }),
  ] as const),
  metadataOnly: true,
  immutable: true,
  deterministic: true,
} as const);
