import { ResourcePlatformMetadata } from "./resourceMetadata.ts";

export interface ResourceCapabilityRegistryEntry {
  readonly id: string;
  readonly name: string;
  readonly description: string;
  readonly domainId: string;
  readonly phaseId: string;
  readonly releaseState: "Draft";
  readonly runtimeBehavior: false;
  readonly metadataOnly: true;
}

export const ResourceCapabilityRegistry = Object.freeze([
  Object.freeze({
    id: "cap-human-resources",
    name: "Human Resources",
    description: "Descriptive registry entry for human resource intelligence.",
    domainId: "human-resources",
    phaseId: "OPS-5:2",
    releaseState: "Draft",
    runtimeBehavior: false,
    metadataOnly: true,
  }),
  Object.freeze({
    id: "cap-team-resources",
    name: "Team Resources",
    description: "Descriptive registry entry for team resource intelligence.",
    domainId: "team-resources",
    phaseId: "OPS-5:2",
    releaseState: "Draft",
    runtimeBehavior: false,
    metadataOnly: true,
  }),
  Object.freeze({
    id: "cap-ai-agent-resources",
    name: "AI Agent Resources",
    description: "Descriptive registry entry for AI agent resource intelligence.",
    domainId: "ai-agent-resources",
    phaseId: "OPS-5:2",
    releaseState: "Draft",
    runtimeBehavior: false,
    metadataOnly: true,
  }),
  Object.freeze({
    id: "cap-software-resources",
    name: "Software Resources",
    description: "Descriptive registry entry for software resource intelligence.",
    domainId: "software-resources",
    phaseId: "OPS-5:2",
    releaseState: "Draft",
    runtimeBehavior: false,
    metadataOnly: true,
  }),
  Object.freeze({
    id: "cap-hardware-resources",
    name: "Hardware Resources",
    description: "Descriptive registry entry for hardware resource intelligence.",
    domainId: "hardware-resources",
    phaseId: "OPS-5:2",
    releaseState: "Draft",
    runtimeBehavior: false,
    metadataOnly: true,
  }),
  Object.freeze({
    id: "cap-equipment-resources",
    name: "Equipment Resources",
    description: "Descriptive registry entry for equipment resource intelligence.",
    domainId: "equipment-resources",
    phaseId: "OPS-5:2",
    releaseState: "Draft",
    runtimeBehavior: false,
    metadataOnly: true,
  }),
  Object.freeze({
    id: "cap-financial-resources",
    name: "Financial Resources",
    description: "Descriptive registry entry for financial resource intelligence.",
    domainId: "financial-resources",
    phaseId: "OPS-5:2",
    releaseState: "Draft",
    runtimeBehavior: false,
    metadataOnly: true,
  }),
  Object.freeze({
    id: "cap-facility-resources",
    name: "Facility Resources",
    description: "Descriptive registry entry for facility resource intelligence.",
    domainId: "facility-resources",
    phaseId: "OPS-5:2",
    releaseState: "Draft",
    runtimeBehavior: false,
    metadataOnly: true,
  }),
  Object.freeze({
    id: "cap-vendor-resources",
    name: "Vendor Resources",
    description: "Descriptive registry entry for vendor resource intelligence.",
    domainId: "vendor-resources",
    phaseId: "OPS-5:2",
    releaseState: "Draft",
    runtimeBehavior: false,
    metadataOnly: true,
  }),
  Object.freeze({
    id: "cap-cloud-resources",
    name: "Cloud Resources",
    description: "Descriptive registry entry for cloud resource intelligence.",
    domainId: "cloud-resources",
    phaseId: "OPS-5:2",
    releaseState: "Draft",
    runtimeBehavior: false,
    metadataOnly: true,
  }),
  Object.freeze({
    id: "cap-database-resources",
    name: "Database Resources",
    description: "Descriptive registry entry for database resource intelligence.",
    domainId: "database-resources",
    phaseId: "OPS-5:2",
    releaseState: "Draft",
    runtimeBehavior: false,
    metadataOnly: true,
  }),
  Object.freeze({
    id: "cap-api-resources",
    name: "API Resources",
    description: "Descriptive registry entry for API resource intelligence.",
    domainId: "api-resources",
    phaseId: "OPS-5:2",
    releaseState: "Draft",
    runtimeBehavior: false,
    metadataOnly: true,
  }),
  Object.freeze({
    id: "cap-time-resources",
    name: "Time Resources",
    description: "Descriptive registry entry for time resource intelligence.",
    domainId: "time-resources",
    phaseId: "OPS-5:2",
    releaseState: "Draft",
    runtimeBehavior: false,
    metadataOnly: true,
  }),
  Object.freeze({
    id: "cap-material-resources",
    name: "Material Resources",
    description: "Descriptive registry entry for material resource intelligence.",
    domainId: "material-resources",
    phaseId: "OPS-5:2",
    releaseState: "Draft",
    runtimeBehavior: false,
    metadataOnly: true,
  }),
  Object.freeze({
    id: "cap-inventory-resources",
    name: "Inventory Resources",
    description: "Descriptive registry entry for inventory resource intelligence.",
    domainId: "inventory-resources",
    phaseId: "OPS-5:2",
    releaseState: "Draft",
    runtimeBehavior: false,
    metadataOnly: true,
  }),
  Object.freeze({
    id: "cap-future-resource-extensions",
    name: "Future Resource Extensions",
    description: "Descriptive registry entry for future resource intelligence extensions.",
    domainId: "future-resource-extensions",
    phaseId: "OPS-5:2",
    releaseState: "Draft",
    runtimeBehavior: false,
    metadataOnly: true,
  }),
] as const satisfies readonly ResourceCapabilityRegistryEntry[]);

export const ResourceCapabilityRegistryMetadata = Object.freeze({
  registryId: "ops.resource-intelligence.capability-registry",
  registryVersion: ResourcePlatformMetadata.compatibilityVersion,
  platformId: ResourcePlatformMetadata.platformId,
  capabilityCount: ResourceCapabilityRegistry.length,
  metadataOnly: true,
  immutable: true,
} as const);

