import { ResourceIntelligenceIdentity } from "./resourceIntelligenceIdentity.ts";

export const ResourceIntelligenceRegistry = Object.freeze({
  platformIdentity: ResourceIntelligenceIdentity,
  supportedResourceCategories: Object.freeze([
    "Human",
    "Team",
    "Department",
    "AI Agent",
    "Software",
    "Hardware",
    "Equipment",
    "Vehicle",
    "Budget",
    "Financial Account",
    "Facility",
    "Workspace",
    "License",
    "Vendor",
    "Service",
    "Cloud Resource",
    "Database",
    "API",
    "Time",
    "Material",
    "Inventory",
  ]),
  platformScope:
    "Defines canonical metadata contracts for organizational resources required by projects, workflows, and tasks.",
  architecturalLevel: ResourceIntelligenceIdentity.platformArchitecturalLevel,
  consumedPlatforms: Object.freeze([
    "OPS-1 Executive Operations Public Platform",
    "OPS-2 Executive Task Intelligence Public Platform",
    "OPS-3 Executive Workflow Intelligence Public Platform",
    "OPS-4 Executive Project Execution Public Platform",
  ]),
  publicApiSurface: Object.freeze([
    "ExecutiveResourceIntelligenceFoundation",
    "buildResourceIntelligenceManifest",
    "validateResourceIntelligenceFoundation",
  ]),
  version: ResourceIntelligenceIdentity.platformVersion,
  namespace: ResourceIntelligenceIdentity.platformNamespace,
  description: ResourceIntelligenceIdentity.platformDescription,
  releaseStage: ResourceIntelligenceIdentity.releaseStage,
  status: ResourceIntelligenceIdentity.platformStatus,
  taskIntelligenceDependency: Object.freeze({
    dependencyId: "ops-2-public-index",
    dependencyName: "Executive Task Intelligence Public Index",
    dependencyPhase: "OPS-2:9",
    dependencyVersion: "1.0.0",
    metadataOnly: true,
  }),
  workflowIntelligenceDependency: Object.freeze({
    dependencyId: "ops-3-public-index",
    dependencyName: "Executive Workflow Intelligence Public Index",
    dependencyPhase: "OPS-3:9",
    dependencyVersion: "1.0.0",
    metadataOnly: true,
  }),
  projectExecutionDependency: Object.freeze({
    dependencyId: "ops-4-public-index",
    dependencyName: "Executive Project Execution Public Index",
    dependencyPhase: "OPS-4:9",
    dependencyVersion: "1.0.0",
    metadataOnly: true,
  }),
  registeredPhases: Object.freeze([
    Object.freeze({
      phaseId: "OPS-5:1",
      phaseName: "Resource Intelligence Foundation",
      phaseVersion: "1.0.0",
      phaseStatus: "Foundation",
      metadataOnly: true,
      deterministic: true,
    }),
  ]),
  metadataOnly: true,
  immutable: true,
  deterministic: true,
} as const);

