import { SchedulingIntelligenceIdentity } from "./schedulingIntelligenceIdentity.ts";

export const SchedulingIntelligenceRegistry = Object.freeze({
  platformIdentity: SchedulingIntelligenceIdentity,
  supportedSchedulingDomains: Object.freeze([
    "Schedules",
    "Timelines",
    "Execution Windows",
    "Calendars",
    "Milestones",
    "Temporal Dependencies",
    "Sequences",
    "Constraints",
  ]),
  schedulingCapabilityCategories: Object.freeze([
    "Executive Scheduling",
    "Project Scheduling",
    "Workflow Scheduling",
    "Task Scheduling",
    "Resource-Aware Scheduling",
    "Milestone Scheduling",
    "Calendar Coordination",
    "Dependency Coordination",
  ]),
  scheduleMetadata: Object.freeze([
    "schedule-identity",
    "schedule-category",
    "schedule-status",
  ]),
  timelineMetadata: Object.freeze([
    "timeline-type",
    "timeline-sequence",
    "timeline-milestones",
  ]),
  calendarMetadata: Object.freeze([
    "calendar-type",
    "calendar-exceptions",
    "calendar-coordination",
  ]),
  executionWindowMetadata: Object.freeze([
    "window-boundaries",
    "window-availability",
    "window-readiness",
  ]),
  milestoneTimingMetadata: Object.freeze([
    "milestone-timing",
    "milestone-dependencies",
    "milestone-readiness",
  ]),
  dependencyTimingMetadata: Object.freeze([
    "dependency-ordering",
    "dependency-offsets",
    "dependency-constraints",
  ]),
  sequencingMetadata: Object.freeze([
    "sequence-order",
    "sequence-gates",
    "sequence-handoffs",
  ]),
  platformScope:
    "Defines canonical metadata contracts for describing how projects, workflows, tasks, and resources are organized in time.",
  architecturalLevel: SchedulingIntelligenceIdentity.platformArchitecturalLevel,
  consumedPlatforms: Object.freeze([
    "OPS-1 Executive Operations Public Platform",
    "OPS-2 Executive Task Intelligence Public Platform",
    "OPS-3 Executive Workflow Intelligence Public Platform",
    "OPS-4 Executive Project Execution Public Platform",
    "OPS-5 Executive Resource Intelligence Public Platform",
  ]),
  publicApiSurface: Object.freeze([
    "ExecutiveSchedulingIntelligenceFoundation",
    "buildSchedulingIntelligenceManifest",
    "validateSchedulingIntelligenceFoundation",
  ]),
  compatibilityMetadata: Object.freeze([
    "ops-2-task-compatible",
    "ops-3-workflow-compatible",
    "ops-4-project-compatible",
    "ops-5-resource-compatible",
  ]),
  version: SchedulingIntelligenceIdentity.platformVersion,
  namespace: SchedulingIntelligenceIdentity.platformNamespace,
  description: SchedulingIntelligenceIdentity.platformDescription,
  releaseStage: SchedulingIntelligenceIdentity.releaseStage,
  status: SchedulingIntelligenceIdentity.platformStatus,
  taskIntelligenceDependency: Object.freeze({
    dependencyId: "ops-2-public-index",
    dependencyName: "Executive Task Intelligence Public Index",
    dependencyPhase: "OPS-2:9",
    dependencyVersion: "1.0.0",
    metadataOnly: true,
  }),
  workflowIntelligenceDependency: Object.freeze({
    dependencyId: "ops-3-public-index",
    dependencyName: "Executive Workflow Intelligence Public Index",
    dependencyPhase: "OPS-3:9",
    dependencyVersion: "1.0.0",
    metadataOnly: true,
  }),
  projectExecutionDependency: Object.freeze({
    dependencyId: "ops-4-public-index",
    dependencyName: "Executive Project Execution Public Index",
    dependencyPhase: "OPS-4:9",
    dependencyVersion: "1.0.0",
    metadataOnly: true,
  }),
  resourceIntelligenceDependency: Object.freeze({
    dependencyId: "ops-5-public-index",
    dependencyName: "Executive Resource Intelligence Public Index",
    dependencyPhase: "OPS-5:9",
    dependencyVersion: "1.0.0",
    metadataOnly: true,
  }),
  registeredPhases: Object.freeze([
    Object.freeze({
      phaseId: "OPS-6:1",
      phaseName: "Scheduling Intelligence Foundation",
      phaseVersion: "1.0.0",
      phaseStatus: "Foundation",
      metadataOnly: true,
      deterministic: true,
    }),
  ]),
  metadataOnly: true,
  immutable: true,
  deterministic: true,
} as const);
