import type { TaskPlatformCertificationEntry } from "./taskPlatformCertificationTypes.ts";

export const TaskPlatformCertificationRegistry = Object.freeze([
  Object.freeze({
    certificationId: "ops-2-foundation-certification",
    certificationVersion: "1.0.0",
    certificationDateMetadata: "logical-2026-07-07",
    certificationScope: "Foundation",
    certificationStatus: "PASS",
    category: "Foundation",
    level: "Phase",
    metadataOnly: true,
  } as const satisfies TaskPlatformCertificationEntry),
  Object.freeze({
    certificationId: "ops-2-registry-metadata-certification",
    certificationVersion: "1.0.0",
    certificationDateMetadata: "logical-2026-07-07",
    certificationScope: "Registry & Metadata",
    certificationStatus: "PASS",
    category: "RegistryMetadata",
    level: "Phase",
    metadataOnly: true,
  } as const satisfies TaskPlatformCertificationEntry),
  Object.freeze({
    certificationId: "ops-2-model-certification",
    certificationVersion: "1.0.0",
    certificationDateMetadata: "logical-2026-07-07",
    certificationScope: "Model",
    certificationStatus: "PASS",
    category: "Model",
    level: "Phase",
    metadataOnly: true,
  } as const satisfies TaskPlatformCertificationEntry),
  Object.freeze({
    certificationId: "ops-2-validation-certification",
    certificationVersion: "1.0.0",
    certificationDateMetadata: "logical-2026-07-07",
    certificationScope: "Validation",
    certificationStatus: "PASS",
    category: "Validation",
    level: "Phase",
    metadataOnly: true,
  } as const satisfies TaskPlatformCertificationEntry),
  Object.freeze({
    certificationId: "ops-2-manifest-certification",
    certificationVersion: "1.0.0",
    certificationDateMetadata: "logical-2026-07-07",
    certificationScope: "Manifest",
    certificationStatus: "PASS",
    category: "Manifest",
    level: "Phase",
    metadataOnly: true,
  } as const satisfies TaskPlatformCertificationEntry),
  Object.freeze({
    certificationId: "ops-2-platform-index-certification",
    certificationVersion: "1.0.0",
    certificationDateMetadata: "logical-2026-07-07",
    certificationScope: "Platform Index",
    certificationStatus: "PASS",
    category: "PlatformIndex",
    level: "Platform",
    metadataOnly: true,
  } as const satisfies TaskPlatformCertificationEntry),
] as const);

export const TaskPlatformCertificationRegistryMetadata = Object.freeze({
  certificationRegistryId: "ops.task.platform-certification-registry",
  certificationRegistryVersion: "1.0.0",
  certificationScope: "OPS-2 Platform",
  certificationStatus: "PASS",
  entryCount: TaskPlatformCertificationRegistry.length,
  metadataOnly: true,
  immutable: true,
} as const);
