/**
 * APP-3:8 — Executive Intent dependency canonical examples.
 */
export const INTENT_DEPENDENCY_CANONICAL_EXAMPLES = Object.freeze([
    Object.freeze({
        exampleId: "launch-depends-prototype",
        label: "Launch product depends on prototype",
        dependentText: "Launch product innovation program next year.",
        prerequisiteText: "Modernize cloud platform technology across the enterprise.",
        languageCode: "en",
        expectedDependency: true,
        expectedCategories: Object.freeze(["technology", "direct"]),
        expectedMinimumStrength: "critical",
        readOnly: true,
    }),
    Object.freeze({
        exampleId: "hiring-before-expansion",
        label: "Hiring before expansion",
        dependentText: "Expand market share by 15% this year.",
        prerequisiteText: "Hire 50 engineers for the project by Q3.",
        languageCode: "en",
        expectedDependency: true,
        expectedCategories: Object.freeze(["enabling"]),
        expectedMinimumStrength: "strong",
        readOnly: true,
    }),
    Object.freeze({
        exampleId: "funding-before-acquisition",
        label: "Funding before acquisition",
        dependentText: "Acquire competitor company next year.",
        prerequisiteText: "Improve cash flow by 12% next year.",
        languageCode: "en",
        expectedDependency: true,
        expectedCategories: Object.freeze(["strategic"]),
        expectedMinimumStrength: "moderate",
        readOnly: true,
    }),
    Object.freeze({
        exampleId: "compliance-before-release",
        label: "Compliance before release",
        dependentText: "Launch product innovation program next year.",
        prerequisiteText: "Ensure compliance with GDPR regulation by 2026.",
        languageCode: "en",
        expectedDependency: true,
        expectedCategories: Object.freeze(["compliance"]),
        expectedMinimumStrength: "strong",
        readOnly: true,
    }),
    Object.freeze({
        exampleId: "technology-before-deployment",
        label: "Technology migration before deployment",
        dependentText: "Expand market share by 15% this year.",
        prerequisiteText: "Modernize cloud platform technology across the enterprise.",
        languageCode: "en",
        expectedDependency: true,
        expectedCategories: Object.freeze(["technology"]),
        expectedMinimumStrength: "strong",
        readOnly: true,
    }),
    Object.freeze({
        exampleId: "independent-objectives",
        label: "Independent objectives",
        dependentText: "Increase company profit by 20% next year.",
        prerequisiteText: "Improve operational efficiency by 10% in the department.",
        languageCode: "en",
        expectedDependency: false,
        expectedCategories: Object.freeze([]),
        expectedMinimumStrength: "none",
        readOnly: true,
    }),
    Object.freeze({
        exampleId: "circular-dependency",
        label: "Circular dependency",
        dependentText: "Launch product innovation program next year.",
        prerequisiteText: "Ensure compliance with GDPR regulation by 2026.",
        languageCode: "en",
        expectedDependency: true,
        expectedCategories: Object.freeze(["compliance", "technology", "indirect"]),
        expectedMinimumStrength: "moderate",
        readOnly: true,
    }),
    Object.freeze({
        exampleId: "shared-prerequisite",
        label: "Shared prerequisite",
        dependentText: "Reduce operating cost by 8% next year.",
        prerequisiteText: "Increase company profit by 20% next year.",
        languageCode: "en",
        expectedDependency: true,
        expectedCategories: Object.freeze(["shared_prerequisite"]),
        expectedMinimumStrength: "weak",
        readOnly: true,
    }),
    Object.freeze({
        exampleId: "blocked-dependency",
        label: "Blocked dependency",
        dependentText: "Expand market share by 15% this year.",
        prerequisiteText: "Mitigate supply chain risk exposure without increasing cost.",
        languageCode: "en",
        expectedDependency: true,
        expectedCategories: Object.freeze(["operational", "technology", "enabling"]),
        expectedMinimumStrength: "moderate",
        readOnly: true,
    }),
    Object.freeze({
        exampleId: "unknown-dependency",
        label: "Unknown dependency",
        dependentText: "Increase by 20%",
        prerequisiteText: "Improve operational efficiency by 10% in the department.",
        languageCode: "en",
        expectedDependency: true,
        expectedCategories: Object.freeze(["unknown"]),
        expectedMinimumStrength: "unknown",
        readOnly: true,
    }),
]);
export function getIntentDependencyCanonicalExample(exampleId) {
    return INTENT_DEPENDENCY_CANONICAL_EXAMPLES.find((entry) => entry.exampleId === exampleId) ?? null;
}
export const ExecutiveIntentDependencyExamples = Object.freeze({
    canonical: INTENT_DEPENDENCY_CANONICAL_EXAMPLES,
    getIntentDependencyCanonicalExample,
});
