/**
 * APP-3:6 — Executive Intent classification canonical examples.
 */
export const INTENT_CLASSIFICATION_CANONICAL_EXAMPLES = Object.freeze([
    Object.freeze({
        exampleId: "increase-profit",
        label: "Increase Profit",
        semanticExampleId: "increase-profit",
        customText: null,
        languageCode: "en",
        expectedPrimaryClass: "financial",
        expectedSecondaryClasses: Object.freeze([]),
        expectedMultiClass: false,
        readOnly: true,
    }),
    Object.freeze({
        exampleId: "reduce-cost",
        label: "Reduce Cost",
        semanticExampleId: "reduce-costs",
        customText: null,
        languageCode: "en",
        expectedPrimaryClass: "financial",
        expectedSecondaryClasses: Object.freeze([]),
        expectedMultiClass: false,
        readOnly: true,
    }),
    Object.freeze({
        exampleId: "expand-market",
        label: "Expand Market",
        semanticExampleId: "expand-new-market",
        customText: null,
        languageCode: "en",
        expectedPrimaryClass: "growth",
        expectedSecondaryClasses: Object.freeze(["strategic"]),
        expectedMultiClass: true,
        readOnly: true,
    }),
    Object.freeze({
        exampleId: "digital-transformation",
        label: "Digital Transformation",
        semanticExampleId: "modernize-technology",
        customText: null,
        languageCode: "en",
        expectedPrimaryClass: "transformation",
        expectedSecondaryClasses: Object.freeze(["technology"]),
        expectedMultiClass: true,
        readOnly: true,
    }),
    Object.freeze({
        exampleId: "compliance-initiative",
        label: "Compliance Initiative",
        semanticExampleId: null,
        customText: "Ensure regulatory compliance by Q4 without increasing cost.",
        languageCode: "en",
        expectedPrimaryClass: "compliance",
        expectedSecondaryClasses: Object.freeze(["financial"]),
        expectedMultiClass: true,
        readOnly: true,
    }),
    Object.freeze({
        exampleId: "customer-experience",
        label: "Customer Experience",
        semanticExampleId: "improve-customer-satisfaction",
        customText: null,
        languageCode: "en",
        expectedPrimaryClass: "customer",
        expectedSecondaryClasses: Object.freeze([]),
        expectedMultiClass: false,
        readOnly: true,
    }),
    Object.freeze({
        exampleId: "operational-efficiency",
        label: "Operational Efficiency",
        semanticExampleId: null,
        customText: "Improve operational efficiency by 15% this year.",
        languageCode: "en",
        expectedPrimaryClass: "operational",
        expectedSecondaryClasses: Object.freeze([]),
        expectedMultiClass: false,
        readOnly: true,
    }),
    Object.freeze({
        exampleId: "risk-reduction",
        label: "Risk Reduction",
        semanticExampleId: "reduce-operational-risk",
        customText: null,
        languageCode: "en",
        expectedPrimaryClass: "risk",
        expectedSecondaryClasses: Object.freeze([]),
        expectedMultiClass: false,
        readOnly: true,
    }),
    Object.freeze({
        exampleId: "innovation-program",
        label: "Innovation Program",
        semanticExampleId: null,
        customText: "Launch product innovation program next year.",
        languageCode: "en",
        expectedPrimaryClass: "innovation",
        expectedSecondaryClasses: Object.freeze([]),
        expectedMultiClass: false,
        readOnly: true,
    }),
    Object.freeze({
        exampleId: "hiring-initiative",
        label: "Hiring Initiative",
        semanticExampleId: "hire-engineers",
        customText: null,
        languageCode: "en",
        expectedPrimaryClass: "people",
        expectedSecondaryClasses: Object.freeze(["resource"]),
        expectedMultiClass: true,
        readOnly: true,
    }),
    Object.freeze({
        exampleId: "multiple-classifications",
        label: "Multiple classifications",
        semanticExampleId: "multiple-goals",
        customText: null,
        languageCode: "en",
        expectedPrimaryClass: "financial",
        expectedSecondaryClasses: Object.freeze([]),
        expectedMultiClass: true,
        readOnly: true,
    }),
    Object.freeze({
        exampleId: "unknown-classification",
        label: "Unknown classification",
        semanticExampleId: "incomplete-objective",
        customText: null,
        languageCode: "en",
        expectedPrimaryClass: "custom",
        expectedSecondaryClasses: Object.freeze([]),
        expectedMultiClass: false,
        readOnly: true,
    }),
]);
export function getIntentClassificationCanonicalExample(exampleId) {
    return (INTENT_CLASSIFICATION_CANONICAL_EXAMPLES.find((entry) => entry.exampleId === exampleId) ?? null);
}
export const ExecutiveIntentClassificationExamples = Object.freeze({
    canonical: INTENT_CLASSIFICATION_CANONICAL_EXAMPLES,
    getIntentClassificationCanonicalExample,
});
