/**
 * DTH:1 — Director boundary for Decision Theatre foundation.
 * DTH:5 implements Scene Intent and Scene Script as a projection, not a second Director.
 */

export const NEXORA_DECISION_THEATRE_DIRECTOR_BOUNDARY = Object.freeze({
  identity: "DTH:1/DirectorBoundary" as const,
  sceneIntentImplemented: true as const,
  sceneScriptImplemented: true as const,
  objectInvestigationImplemented: true as const,
  decisionComparisonImplemented: true as const,
  decisionCommitmentImplemented: true as const,
  executionReadinessImplemented: true as const,
  liveExecutionImplemented: true as const,
  outcomeObservationImplemented: true as const,
  learningReassessmentImplemented: true as const,
  may: Object.freeze([
    "Read authoritative executive context",
    "Read existing Stage scene state",
    "Compose a deterministic presentation projection",
    "Preserve focus, selection, visibility and semantic relations",
    "Produce Advisor-readable presentation context",
    "Report why an existing element is visible when that reason is supported",
    "Project registered Iconic Objects from authoritative sources when the owner is visible",
    "Select supported visual grammar directives from authoritative Theatre state",
    "Project supported Stage atmosphere from whole-scene authority",
    "Project Scene Intent from already-resolved canonical meaning",
    "Compose a renderer-neutral Scene Script from existing participants",
    "Project a read-only Object Investigation context from the current Scene and selected object",
    "Project a read-only Decision Comparison from authoritative comparison membership",
    "Project a read-only Decision review from comparison and existing Decision authority",
    "Project a read-only Execution readiness view from a committed Decision and existing Execution authority",
    "Project a read-only live Execution Theatre from an already-started canonical Execution",
    "Project a read-only Outcome observation view from existing Outcome capture or explicit observations",
    "Project a read-only Learning and Reassessment view from an existing Outcome observation",
  ] as const),
  mayNot: Object.freeze([
    "Create business facts",
    "Confirm causes",
    "Rank options without comparable evidence",
    "Create or approve Decisions",
    "Start Executions",
    "Complete, pause, cancel, or restart Executions",
    "Fabricate progress, owners, deadlines, blockers, or Outcomes",
    "Generate Outcomes or Learning",
    "Treat Execution completed as Outcome success",
    "Infer that Execution caused an observed change",
    "Close a Decision or start Learning because an Outcome was observed",
    "Persist session Outcome as durable Learning",
    "Create a Decision, Scenario, or Goal from Learning",
    "Mutate canonical Objects for presentation convenience",
    "Use color, size, movement or placement to invent unsupported meaning",
    "Treat raw CSS as semantic authority",
    "Derive atmosphere from a single Object color, count, or focus",
    "Re-parse raw manager text when canonical meaning already exists",
    "Select War Room Atmosphere from Scene Intent",
    "Upgrade Iconic Objects into Executive Objects",
    "Display unknown or missing Iconic values as zero",
    "Replace a canonical Executive Object with an Iconic Object",
    "Implement NexoSelect, NexoCompare, NexoTime, Cards, or Charts",
  ] as const),
  businessMutationAllowed: false as const,
} as const);
