import {
  ExecutiveConfidenceLevels,
  ExecutiveEvidenceCategories,
  ExecutiveInferenceTypes,
  ExecutiveReasoningDomains,
  ExecutiveReasoningLifecycle,
  ExecutiveReasoningPipelineContracts,
  ExecutiveReasoningPipelineFoundation,
} from "./executiveReasoningPipelineFoundation.ts";
import type {
  ExecutiveReasoningValidationDomain,
  ExecutiveReasoningValidationRule,
} from "./executiveReasoningValidationTypes.ts";

const rule = (
  key: string,
  name: string,
  description: string,
  domain: ExecutiveReasoningValidationRule["domain"],
  expectedCondition: string,
  actualMetadataResult: string,
  severity: ExecutiveReasoningValidationRule["severity"] = "Error",
) => Object.freeze({
  id: `eng-6-validation-foundation-${key}`,
  name,
  description,
  domain,
  severity,
  status: "PASS",
  expectedCondition,
  actualMetadataResult,
  owner: "ENG-6",
  targetPhase: "ENG-6:1",
  metadataOnly: true,
  immutable: true,
  deterministic: true,
  runtimeFree: true,
  aiFree: true,
} as const satisfies ExecutiveReasoningValidationRule);

export const ExecutiveReasoningFoundationValidationRules = Object.freeze([
  rule(
    "foundation-exists",
    "Foundation Exists",
    "ENG-6:1 foundation aggregate is published.",
    "Foundation",
    "platformId=ENG-6:1",
    `platformId=${ExecutiveReasoningPipelineFoundation.platformId}`,
    "Critical",
  ),
  rule(
    "contracts-exist",
    "Required Contracts Exist",
    "ENG-6:1 publishes the six executive reasoning contracts.",
    "Foundation",
    "contracts=6",
    `contracts=${ExecutiveReasoningPipelineContracts.length}`,
  ),
  rule(
    "domains-exist",
    "Required Domains Exist",
    "ENG-6:1 publishes the twelve reasoning domains.",
    "Foundation",
    "domains=12",
    `domains=${ExecutiveReasoningDomains.length}`,
  ),
  rule(
    "lifecycle-exists",
    "Lifecycle Definition Exists",
    "ENG-6:1 publishes the nine reasoning lifecycle stages.",
    "Lifecycle",
    "lifecycle=9",
    `lifecycle=${ExecutiveReasoningLifecycle.length}`,
  ),
  rule(
    "lifecycle-unique",
    "Lifecycle Stages Unique",
    "Lifecycle stage identifiers are unique.",
    "Lifecycle",
    "uniqueIds=9",
    `uniqueIds=${new Set(ExecutiveReasoningLifecycle.map(({ id }) => id)).size}`,
  ),
  rule(
    "evidence-categories-exist",
    "Evidence Categories Exist",
    "ENG-6:1 publishes the ten evidence categories.",
    "Foundation",
    "evidence=10",
    `evidence=${ExecutiveEvidenceCategories.length}`,
  ),
  rule(
    "confidence-levels-exist",
    "Confidence Levels Exist",
    "ENG-6:1 publishes the seven confidence classifications.",
    "Foundation",
    "confidence=7",
    `confidence=${ExecutiveConfidenceLevels.length}`,
  ),
  rule(
    "inference-types-exist",
    "Inference Types Exist",
    "ENG-6:1 publishes the eight inference classifications.",
    "Foundation",
    "inference=8",
    `inference=${ExecutiveInferenceTypes.length}`,
  ),
  rule(
    "metadata-complete",
    "Foundation Metadata Complete",
    "Foundation declares metadata-only, runtime-free, and AI-free status.",
    "Metadata",
    "metadataOnly+runtimeFree+aiFree",
    `metadataOnly=${String(ExecutiveReasoningPipelineFoundation.metadataOnly)};runtimeFree=${String(ExecutiveReasoningPipelineFoundation.runtimeFree)};aiFree=${String(ExecutiveReasoningPipelineFoundation.aiFree)}`,
  ),
  rule(
    "namespace-integrity",
    "Foundation Namespace Integrity",
    "Foundation namespace remains under the reasoning foundation namespace.",
    "Namespace",
    "nexora.engine.executive.reasoning.foundation",
    ExecutiveReasoningPipelineFoundation.namespace,
  ),
] as const);

export const ExecutiveReasoningFoundationValidation = Object.freeze({
  id: "eng-6-validation-group-foundation",
  name: "Foundation",
  description: "Architectural validation of ENG-6:1 Foundation public metadata.",
  rules: ExecutiveReasoningFoundationValidationRules,
  status: "PASS",
  owner: "ENG-6",
  metadataOnly: true,
  immutable: true,
  deterministic: true,
} as const satisfies ExecutiveReasoningValidationDomain);
