export const ExecutiveContextAssemblyMetadata = Object.freeze({
  platformId: "ENG-4:1",
  name: "Executive Context Assembly Foundation",
  version: "1.0.0",
  phase: "ENG-4:1",
  namespace: "nexora.engine.executive.context-assembly.foundation",
  description: "Canonical metadata-only foundation defining architectural contracts for Executive Context Assembly.",
  owner: "ENG-4",
  layer: "ExecutiveEngine",
  module: "ContextAssemblyFoundation",
  status: Object.freeze({
    foundation: "Foundation",
    metadataOnly: "MetadataOnly",
    runtimeFree: "RuntimeFree",
    immutable: "Immutable",
    deterministic: "Deterministic",
  } as const),
  publicDependencies: Object.freeze([
    Object.freeze({ phase: "ENG-1", publicIndex: "executiveEnginePublicIndex.ts", consumption: "PublicIndexOnly" } as const),
    Object.freeze({ phase: "ENG-2", publicIndex: "executiveRequestIntentPublicIndex.ts", consumption: "PublicIndexOnly" } as const),
    Object.freeze({ phase: "ENG-3", publicIndex: "executiveIntentResolutionPublicIndex.ts", consumption: "PublicIndexOnly" } as const),
  ]),
  nextPhase: "ENG-4:2",
  visibility: "Public",
  releaseStatus: "Draft",
  stability: "Foundation",
  certification: "Uncertified",
  metadataOnly: true,
  immutable: true,
  deterministic: true,
} as const);
