import { ExecutivePlanningLifecycle } from "./executivePlanningIndex.ts";
import type {
  ExecutivePlanningModelLifecycleStage,
  ExecutivePlanningStepModelDescriptor,
} from "./executivePlanningModelTypes.ts";

const lifecycleStages = Object.freeze(
  ExecutivePlanningLifecycle.map(({ name }) => name) as ExecutivePlanningModelLifecycleStage[],
);

const stepModel = (
  key: string,
  name: string,
  description: string,
  planningRole: string,
  metadataInputs: readonly string[],
  metadataOutputs: readonly string[],
  dependencyCompatibility: readonly string[],
  parallelCompatibility: string,
  retryCompatibility: string,
  compatibleStepRegistryId: string,
) => Object.freeze({
  id: `eng-5-model-step-${key}`,
  name,
  description,
  category: "Step",
  owner: "ENG-5",
  version: "1.0.0",
  status: "Active",
  planningRole,
  metadataInputs: Object.freeze([...metadataInputs]),
  metadataOutputs: Object.freeze([...metadataOutputs]),
  dependencyCompatibility: Object.freeze([...dependencyCompatibility]),
  parallelCompatibility,
  retryCompatibility,
  compatibleStepRegistryId,
  supportedLifecycleStages: lifecycleStages,
  metadataOnly: true,
  runtimeFree: true,
  public: true,
} as const satisfies ExecutivePlanningStepModelDescriptor);

export const ExecutivePlanningStepModels = Object.freeze([
  stepModel(
    "input",
    "InputStep",
    "Model for input-acquisition planning steps as metadata only.",
    "Acquire approved planning input references",
    Object.freeze(["request-intent-public-surface", "context-assembly-public-surface"]),
    Object.freeze(["acquired-input-metadata"]),
    Object.freeze(["eng-5-dep-type-data", "eng-5-dep-type-context"]),
    "ParallelEligible",
    "RetryMetadataDisallowed",
    "eng-5-step-type-input-acquisition",
  ),
  stepModel(
    "context",
    "ContextStep",
    "Model for context-preparation planning steps as metadata only.",
    "Prepare executive-context references for planning",
    Object.freeze(["acquired-input-metadata", "executive-context-public-surface"]),
    Object.freeze(["prepared-context-metadata"]),
    Object.freeze(["eng-5-dep-type-context", "eng-5-dep-type-sequential"]),
    "ParallelEligible",
    "RetryMetadataAllowed",
    "eng-5-step-type-context-preparation",
  ),
  stepModel(
    "analysis",
    "AnalysisStep",
    "Model for analysis planning steps as metadata only.",
    "Describe analysis planning without performing analysis",
    Object.freeze(["prepared-context-metadata"]),
    Object.freeze(["analysis-step-metadata"]),
    Object.freeze(["eng-5-dep-type-data", "eng-5-dep-type-sequential"]),
    "ParallelEligible",
    "RetryMetadataAllowed",
    "eng-5-step-type-analysis",
  ),
  stepModel(
    "comparison",
    "ComparisonStep",
    "Model for comparison planning steps as metadata only.",
    "Describe comparison planning without computing comparisons",
    Object.freeze(["analysis-step-metadata"]),
    Object.freeze(["comparison-step-metadata"]),
    Object.freeze(["eng-5-dep-type-sequential", "eng-5-dep-type-data"]),
    "ParallelEligible",
    "RetryMetadataAllowed",
    "eng-5-step-type-comparison",
  ),
  stepModel(
    "validation",
    "ValidationStep",
    "Model for validation planning steps as metadata only.",
    "Describe validation planning without executing validators",
    Object.freeze(["comparison-step-metadata", "analysis-step-metadata"]),
    Object.freeze(["validation-step-metadata"]),
    Object.freeze(["eng-5-dep-type-validation", "eng-5-dep-type-sequential"]),
    "SequentialOnly",
    "RetryMetadataAllowed",
    "eng-5-step-type-validation",
  ),
  stepModel(
    "decision",
    "DecisionStep",
    "Model for decision-evaluation planning steps as metadata only.",
    "Describe decision-evaluation planning without making decisions",
    Object.freeze(["validation-step-metadata"]),
    Object.freeze(["decision-evaluation-metadata"]),
    Object.freeze(["eng-5-dep-type-decision", "eng-5-dep-type-validation"]),
    "SequentialOnly",
    "RetryMetadataAllowed",
    "eng-5-step-type-decision-evaluation",
  ),
  stepModel(
    "recommendation",
    "RecommendationStep",
    "Model for recommendation-preparation planning steps as metadata only.",
    "Describe recommendation preparation without Advisor generation",
    Object.freeze(["decision-evaluation-metadata"]),
    Object.freeze(["recommendation-preparation-metadata"]),
    Object.freeze(["eng-5-dep-type-decision", "eng-5-dep-type-output"]),
    "ParallelEligible",
    "RetryMetadataAllowed",
    "eng-5-step-type-recommendation-preparation",
  ),
  stepModel(
    "execution-preparation",
    "ExecutionPreparationStep",
    "Model for execution-preparation planning steps as metadata only.",
    "Describe execution preparation for OPS without invoking OPS",
    Object.freeze(["recommendation-preparation-metadata", "decision-evaluation-metadata"]),
    Object.freeze(["execution-preparation-metadata"]),
    Object.freeze(["eng-5-dep-type-sequential", "eng-5-dep-type-resource"]),
    "SequentialOnly",
    "RetryMetadataAllowed",
    "eng-5-step-type-execution-preparation",
  ),
  stepModel(
    "monitoring-preparation",
    "MonitoringPreparationStep",
    "Model for monitoring-preparation planning steps as metadata only.",
    "Describe monitoring preparation without monitoring runtime",
    Object.freeze(["execution-preparation-metadata"]),
    Object.freeze(["monitoring-preparation-metadata"]),
    Object.freeze(["eng-5-dep-type-sequential", "eng-5-dep-type-temporal"]),
    "ParallelEligible",
    "RetryMetadataAllowed",
    "eng-5-step-type-monitoring-preparation",
  ),
  stepModel(
    "output-assembly",
    "OutputAssemblyStep",
    "Model for output-assembly planning steps as metadata only.",
    "Describe output assembly without persistence or UI delivery",
    Object.freeze(["monitoring-preparation-metadata", "execution-preparation-metadata"]),
    Object.freeze(["assembled-planning-output-metadata"]),
    Object.freeze(["eng-5-dep-type-output", "eng-5-dep-type-sequential"]),
    "SequentialOnly",
    "RetryMetadataDisallowed",
    "eng-5-step-type-output-assembly",
  ),
] as const);

const stepIndex = Object.freeze(
  Object.fromEntries(ExecutivePlanningStepModels.map((model) => [model.id, model])) as Readonly<
    Record<string, ExecutivePlanningStepModelDescriptor | undefined>
  >,
);

export const getExecutivePlanningStepModels = () => ExecutivePlanningStepModels;
export const getExecutivePlanningStepModel = (
  id: string,
): ExecutivePlanningStepModelDescriptor | undefined => stepIndex[id];
