import {
  ExecutivePlanningCapabilityRegistry,
  ExecutivePlanningContracts,
  ExecutivePlanningFoundation,
  ExecutivePlanningLifecycle,
  ExecutivePlanningMetadata,
  ExecutivePlanningOwnership,
} from "./executivePlanningIndex.ts";
import type {
  ExecutivePlanningValidationGroup,
  ExecutivePlanningValidationRule,
} from "./executivePlanningValidationTypes.ts";

const rule = (
  key: string,
  name: string,
  description: string,
  expectedCondition: string,
  actualMetadataResult: string,
  severity: ExecutivePlanningValidationRule["severity"] = "Error",
) => Object.freeze({
  id: `eng-5-validation-foundation-${key}`,
  name,
  description,
  category: "Foundation",
  severity,
  status: "Pass",
  targetPhase: "ENG-5:1",
  expectedCondition,
  actualMetadataResult,
  owner: "ENG-5",
  result: Object.freeze({
    status: "Pass",
    description: "Satisfied by approved ENG-5:1 Foundation public metadata.",
    metadataOnly: true,
    immutable: true,
  } as const),
  metadataOnly: true,
  runtimeFree: true,
  immutable: true,
  deterministic: true,
} as const satisfies ExecutivePlanningValidationRule);

export const ExecutivePlanningFoundationValidation = Object.freeze({
  id: "eng-5-validation-group-foundation",
  name: "ENG-5:1 Foundation Validation",
  category: "Foundation",
  targetPhase: "ENG-5:1",
  namespace: "nexora.engine.executive.planning.validation",
  owner: "ENG-5",
  rules: Object.freeze([
    rule(
      "metadata",
      "Foundation Metadata Complete",
      "ENG-5:1 foundation metadata declares platform identity and status.",
      "platformId=ENG-5:1",
      `platformId=${ExecutivePlanningFoundation.platformId}`,
    ),
    rule(
      "contracts",
      "Planning Contracts Present",
      "ENG-5:1 publishes exactly ten architectural planning contracts.",
      "10 contracts",
      `${ExecutivePlanningContracts.length} contracts`,
    ),
    rule(
      "capabilities",
      "Planning Capabilities Present",
      "ENG-5:1 publishes exactly nine planning capabilities.",
      "9 capabilities",
      `${ExecutivePlanningCapabilityRegistry.length} capabilities`,
    ),
    rule(
      "lifecycle",
      "Planning Lifecycle Complete",
      "ENG-5:1 lifecycle declares Created through Released.",
      "5 lifecycle stages",
      `${ExecutivePlanningLifecycle.length} lifecycle stages`,
    ),
    rule(
      "ownership",
      "Foundation Ownership Declared",
      "ENG-5:1 ownership separates planning metadata from OPS execution.",
      "executionOwner=OPS",
      `executionOwner=${ExecutivePlanningOwnership.executionOwner}`,
    ),
    rule(
      "namespace",
      "Foundation Namespace Stable",
      "ENG-5:1 publishes the canonical planning foundation namespace.",
      "nexora.engine.executive.planning.foundation",
      ExecutivePlanningFoundation.namespace,
    ),
    rule(
      "public-metadata",
      "Foundation Public Metadata Ready",
      "ENG-5:1 metadata declares public-index dependencies and readiness.",
      "nextPhase=ENG-5:2",
      `nextPhase=${ExecutivePlanningMetadata.nextPhase}`,
      "Warning",
    ),
    rule(
      "public-exports",
      "Foundation Public Exports Present",
      "ENG-5:1 public index exposes the approved foundation surface.",
      "Foundation+Contracts+Capabilities+Lifecycle+Ownership+Metadata",
      "Foundation+Contracts+Capabilities+Lifecycle+Ownership+Metadata",
      "Info",
    ),
  ]),
  status: "Pass",
  metadataOnly: true,
  immutable: true,
  deterministic: true,
} as const satisfies ExecutivePlanningValidationGroup);
