import {
  ExecutiveOrchestrationCapabilityContract,
  ExecutiveOrchestrationFoundation,
} from "./executiveOrchestrationFoundation.ts";
import type {
  ExecutiveOrchestrationCapabilityEntry,
  ExecutiveOrchestrationCapabilityId,
  ExecutiveOrchestrationComponentId,
  ExecutiveOrchestrationCoordinationTargetId,
  ExecutiveOrchestrationDependencyId,
  ExecutiveOrchestrationExecutionMode,
  ExecutiveOrchestrationLifecycleStageId,
} from "./executiveOrchestrationRegistryTypes.ts";

const capability = (
  capabilityId: ExecutiveOrchestrationCapabilityId,
  name: string,
  description: string,
  ownerComponentId: ExecutiveOrchestrationComponentId,
  supportedTargetIds: readonly ExecutiveOrchestrationCoordinationTargetId[],
  supportedExecutionModes: readonly ExecutiveOrchestrationExecutionMode[],
  requiredDependencyIds: readonly ExecutiveOrchestrationDependencyId[],
  lifecycleStageIds: readonly ExecutiveOrchestrationLifecycleStageId[],
) => Object.freeze({
  id: `eng-8-cap-${capabilityId}` as const,
  capabilityId,
  name,
  description,
  kind: "Capability",
  ownerComponentId,
  supportedTargetIds: Object.freeze([...supportedTargetIds]),
  supportedExecutionModes: Object.freeze([...supportedExecutionModes]),
  requiredDependencyIds: Object.freeze([...requiredDependencyIds]),
  lifecycleStageIds: Object.freeze([...lifecycleStageIds]),
  metadataOnly: true,
  runtimeFree: true,
  immutable: true,
  status: "Registered",
} as const satisfies ExecutiveOrchestrationCapabilityEntry);

/**
 * Canonical capability registry aligned with ENG-8:1 capabilities.
 */
export const ExecutiveOrchestrationCapabilityRegistry = Object.freeze([
  capability(
    "sequential-orchestration",
    "Sequential Orchestration",
    "Registers sequential orchestration capability metadata without executing sequences.",
    "execution-sequence-coordinator",
    Object.freeze([
      "executive-request",
      "intent-resolution",
      "context-assembly",
      "planning",
      "reasoning",
      "decision",
    ] as const),
    Object.freeze(["Sequential"] as const),
    Object.freeze([
      "eng-2-public-api",
      "eng-3-public-api",
      "eng-4-public-api",
      "eng-5-public-api",
      "eng-6-public-api",
      "eng-7-public-api",
    ] as const),
    Object.freeze(["PreparePipeline", "CoordinateExecution"] as const),
  ),
  capability(
    "parallel-orchestration",
    "Parallel Orchestration",
    "Registers parallel orchestration capability metadata without executing parallel work.",
    "parallel-coordination-descriptor",
    Object.freeze(["bus-platforms", "ops-platforms"] as const),
    Object.freeze(["Parallel"] as const),
    Object.freeze(["bus-public-apis", "ops-public-apis"] as const),
    Object.freeze(["CoordinateExecution"] as const),
  ),
  capability(
    "dependency-resolution",
    "Dependency Resolution",
    "Registers dependency-resolution capability metadata without resolving runtime dependencies.",
    "dependency-coordinator",
    Object.freeze([
      "executive-request",
      "intent-resolution",
      "context-assembly",
      "planning",
      "reasoning",
      "decision",
      "bus-platforms",
      "ops-platforms",
    ] as const),
    Object.freeze(["Sequential", "Conditional"] as const),
    Object.freeze([
      "eng-1-public-api",
      "eng-2-public-api",
      "eng-3-public-api",
      "eng-4-public-api",
      "eng-5-public-api",
      "eng-6-public-api",
      "eng-7-public-api",
      "bus-public-apis",
      "ops-public-apis",
    ] as const),
    Object.freeze(["ResolveDependencies"] as const),
  ),
  capability(
    "result-aggregation",
    "Result Aggregation",
    "Registers result-aggregation capability metadata without aggregating runtime results.",
    "result-aggregator",
    Object.freeze(["decision", "bus-platforms", "ops-platforms", "advisor"] as const),
    Object.freeze(["Aggregated", "Synchronized"] as const),
    Object.freeze([
      "eng-7-public-api",
      "bus-public-apis",
      "ops-public-apis",
      "advisor-public-apis",
    ] as const),
    Object.freeze(["AggregateResults"] as const),
  ),
  capability(
    "failure-propagation",
    "Failure Propagation",
    "Registers failure-propagation capability metadata without propagating runtime failures.",
    "failure-routing-coordinator",
    Object.freeze([
      "executive-request",
      "intent-resolution",
      "context-assembly",
      "planning",
      "reasoning",
      "decision",
      "advisor",
    ] as const),
    Object.freeze(["Conditional", "Handoff"] as const),
    Object.freeze([
      "eng-2-public-api",
      "eng-3-public-api",
      "eng-4-public-api",
      "eng-5-public-api",
      "eng-6-public-api",
      "eng-7-public-api",
      "advisor-public-apis",
    ] as const),
    Object.freeze(["CoordinateExecution", "AggregateResults", "PrepareResponse"] as const),
  ),
  capability(
    "completion-synchronization",
    "Completion Synchronization",
    "Registers completion-synchronization capability metadata without synchronizing runtime completion.",
    "completion-coordinator",
    Object.freeze(["decision", "advisor"] as const),
    Object.freeze(["Synchronized", "Handoff"] as const),
    Object.freeze(["eng-7-public-api", "advisor-public-apis"] as const),
    Object.freeze(["AggregateResults", "PrepareResponse", "Complete"] as const),
  ),
  capability(
    "advisor-routing",
    "Advisor Routing",
    "Registers advisor-routing capability metadata without routing Advisor runtime messages.",
    "advisor-handoff-coordinator",
    Object.freeze(["advisor", "decision"] as const),
    Object.freeze(["Handoff"] as const),
    Object.freeze(["eng-7-public-api", "advisor-public-apis"] as const),
    Object.freeze(["PrepareResponse", "Complete"] as const),
  ),
  capability(
    "pipeline-coordination",
    "Pipeline Coordination",
    "Registers pipeline-coordination capability metadata without coordinating runtime pipelines.",
    "pipeline-orchestrator",
    Object.freeze([
      "executive-request",
      "intent-resolution",
      "context-assembly",
      "planning",
      "reasoning",
      "decision",
    ] as const),
    Object.freeze(["Sequential", "Synchronized"] as const),
    Object.freeze([
      "eng-1-public-api",
      "eng-2-public-api",
      "eng-3-public-api",
      "eng-4-public-api",
      "eng-5-public-api",
      "eng-6-public-api",
      "eng-7-public-api",
    ] as const),
    Object.freeze([
      "Idle",
      "ReceiveRequest",
      "PreparePipeline",
      "CoordinateExecution",
      "Complete",
    ] as const),
  ),
] as const);

export const ExecutiveOrchestrationCapabilityRegistryFoundationAlignment = Object.freeze({
  foundationId: ExecutiveOrchestrationFoundation.id,
  foundationCapabilityCount: ExecutiveOrchestrationCapabilityContract.capabilities.length,
  registeredCapabilityCount: 8,
  metadataOnly: true,
  immutable: true,
} as const);
