import type { ExecutiveDecisionPlatformComponent } from "./executiveDecisionPlatformTypes.ts";

const component = (
  id: ExecutiveDecisionPlatformComponent["id"],
  name: string,
  description: string,
  owningPhase: ExecutiveDecisionPlatformComponent["owningPhase"],
  publicSourceModule: string,
  dependencyPosition: number,
  requiredPredecessors: readonly ExecutiveDecisionPlatformComponent["id"][],
  permittedSuccessors: readonly ExecutiveDecisionPlatformComponent["id"][] | readonly ["platform"],
  fileCount: number,
  publicExportCount: number,
  artifactCount: number,
  readinessContribution: string,
) => Object.freeze({
  id,
  name,
  description,
  owningPhase,
  publicSourceModule,
  version: "1.0.0",
  status: "Complete",
  dependencyPosition,
  requiredPredecessors,
  permittedSuccessors,
  fileCount,
  publicExportCount,
  artifactCount,
  metadataOnly: true,
  immutable: true,
  runtimeBehavior: "None",
  readinessContribution,
} as const satisfies ExecutiveDecisionPlatformComponent);

/**
 * Canonical platform-component registry.
 * Counts are declared metadata — not derived from filesystem inspection.
 */
export const ExecutiveDecisionPlatformComponentRegistry = Object.freeze([
  component(
    "foundation",
    "Foundation",
    "ENG-7:1 executive decision foundation public architecture.",
    "ENG-7:1",
    "executiveDecisionPublicApi.ts",
    1,
    Object.freeze([] as const),
    Object.freeze(["registry"] as const),
    7,
    6,
    6,
    "FoundationReady",
  ),
  component(
    "registry",
    "Registry",
    "ENG-7:2 executive decision registry public architecture.",
    "ENG-7:2",
    "executiveDecisionRegistryPlatform.ts",
    2,
    Object.freeze(["foundation"] as const),
    Object.freeze(["model"] as const),
    8,
    7,
    7,
    "RegistryReady",
  ),
  component(
    "model",
    "Model",
    "ENG-7:3 executive decision model public architecture.",
    "ENG-7:3",
    "executiveDecisionModelPlatform.ts",
    3,
    Object.freeze(["foundation", "registry"] as const),
    Object.freeze(["validation"] as const),
    9,
    8,
    10,
    "ModelReady",
  ),
  component(
    "validation",
    "Validation",
    "ENG-7:4 executive decision validation public architecture.",
    "ENG-7:4",
    "executiveDecisionValidationPlatform.ts",
    4,
    Object.freeze(["foundation", "registry", "model"] as const),
    Object.freeze(["manifest"] as const),
    8,
    6,
    32,
    "ValidationCertified",
  ),
  component(
    "manifest",
    "Manifest",
    "ENG-7:5 executive decision manifest public architecture.",
    "ENG-7:5",
    "executiveDecisionManifestPlatform.ts",
    5,
    Object.freeze(["foundation", "registry", "model", "validation"] as const),
    Object.freeze(["platform"] as const),
    8,
    7,
    9,
    "ManifestComplete",
  ),
] as const);

export const ExecutiveDecisionPlatformComponentTotals = Object.freeze({
  completedPhases: 5,
  representedFiles: 40,
  approvedPublicExports: 34,
  metadataOnly: true,
  immutable: true,
} as const);
