const edge = (
  key: string,
  source: string,
  target: string,
  publicIndex: string,
) => Object.freeze({
  id: `eng-6-manifest-dependency-${key}`,
  source,
  target,
  direction: "ForwardOnly" as const,
  consumption: "PublicIndexOnly" as const,
  publicIndex,
  reverseDependency: false,
  circularDependency: false,
  metadataOnly: true,
  immutable: true,
  deterministic: true,
} as const);

export const ExecutiveReasoningDependencyMap = Object.freeze({
  id: "eng-6-dependency-map",
  name: "Executive Reasoning Dependency Map",
  description:
    "Immutable architectural dependency graph for the Executive Reasoning Pipeline. Metadata only.",
  phase: "ENG-6:5",
  owner: "ENG-6",
  chain: Object.freeze([
    "ENG-1",
    "ENG-2",
    "ENG-3",
    "ENG-4",
    "ENG-5",
    "ENG-6:1",
    "ENG-6:2",
    "ENG-6:3",
    "ENG-6:4",
  ] as const),
  edges: Object.freeze([
    edge("eng-2-on-1", "ENG-2", "ENG-1", "executiveEnginePublicIndex.ts"),
    edge("eng-3-on-2", "ENG-3", "ENG-2", "executiveRequestIntentPublicIndex.ts"),
    edge("eng-4-on-3", "ENG-4", "ENG-3", "executiveIntentResolutionPublicIndex.ts"),
    edge("eng-5-on-4", "ENG-5", "ENG-4", "executiveContextAssemblyPublicIndex.ts"),
    edge("eng-6-1-on-5", "ENG-6:1", "ENG-5", "executivePlanningPublicIndex.ts"),
    edge("eng-6-2-on-6-1", "ENG-6:2", "ENG-6:1", "executiveReasoningPipelineFoundation.ts"),
    edge("eng-6-3-on-6-2", "ENG-6:3", "ENG-6:2", "executiveReasoningRegistryIndex.ts"),
    edge("eng-6-4-on-6-3", "ENG-6:4", "ENG-6:3", "executiveReasoningModelIndex.ts"),
    edge("eng-6-5-on-6-4", "ENG-6:5", "ENG-6:4", "executiveReasoningValidationPlatform.ts"),
  ] as const),
  allowedDependencies: Object.freeze([
    "ENG-1",
    "ENG-2",
    "ENG-3",
    "ENG-4",
    "ENG-5",
    "ENG-6:1",
    "ENG-6:2",
    "ENG-6:3",
    "ENG-6:4",
  ] as const),
  rejectedDependencies: Object.freeze([
    "BUS",
    "OPS",
    "Advisor",
    "Scene",
    "Director",
    "UI",
    "Integration",
    "Persistence",
    "Runtime",
  ] as const),
  policy: Object.freeze({
    consumption: "PublicIndexOnly",
    reverseDependencies: "Prohibited",
    circularDependencies: "Prohibited",
    runtimeInvocation: "Prohibited",
  } as const),
  edgeCount: 9,
  metadataOnly: true,
  immutable: true,
  deterministic: true,
  runtimeFree: true,
  aiFree: true,
} as const);
