import {
  ExecutivePlanTypeRegistry,
  ExecutivePlanningDependencyRegistry,
  ExecutivePlanningGraphEdgeRegistry,
  ExecutivePlanningGraphNodeRegistry,
  ExecutivePlanningParallelModeRegistry,
  ExecutivePlanningPriorityRegistry,
  ExecutivePlanningRegistryPlatform,
  ExecutivePlanningRetryStrategyRegistry,
  ExecutivePlanningStepRegistry,
  getExecutivePlanningRegistryEntryById,
  getExecutivePlanningRegistryInventory,
  getExecutivePlanTypeById,
} from "./executivePlanningRegistryIndex.ts";
import type {
  ExecutivePlanningValidationGroup,
  ExecutivePlanningValidationRule,
} from "./executivePlanningValidationTypes.ts";

const inventory = getExecutivePlanningRegistryInventory();

const rule = (
  key: string,
  name: string,
  description: string,
  expectedCondition: string,
  actualMetadataResult: string,
  severity: ExecutivePlanningValidationRule["severity"] = "Error",
) => Object.freeze({
  id: `eng-5-validation-registry-${key}`,
  name,
  description,
  category: "Registry",
  severity,
  status: "Pass",
  targetPhase: "ENG-5:2",
  expectedCondition,
  actualMetadataResult,
  owner: "ENG-5",
  result: Object.freeze({
    status: "Pass",
    description: "Satisfied by approved ENG-5:2 Registry public metadata.",
    metadataOnly: true,
    immutable: true,
  } as const),
  metadataOnly: true,
  runtimeFree: true,
  immutable: true,
  deterministic: true,
} as const satisfies ExecutivePlanningValidationRule);

const allRegistryIds = Object.freeze([
  ...ExecutivePlanTypeRegistry.map(({ id }) => id),
  ...ExecutivePlanningStepRegistry.map(({ id }) => id),
  ...ExecutivePlanningDependencyRegistry.map(({ id }) => id),
  ...ExecutivePlanningGraphNodeRegistry.map(({ id }) => id),
  ...ExecutivePlanningGraphEdgeRegistry.map(({ id }) => id),
  ...ExecutivePlanningPriorityRegistry.map(({ id }) => id),
  ...ExecutivePlanningParallelModeRegistry.map(({ id }) => id),
  ...ExecutivePlanningRetryStrategyRegistry.map(({ id }) => id),
]);

export const ExecutivePlanningRegistryValidation = Object.freeze({
  id: "eng-5-validation-group-registry",
  name: "ENG-5:2 Registry Validation",
  category: "Registry",
  targetPhase: "ENG-5:2",
  namespace: "nexora.engine.executive.planning.validation",
  owner: "ENG-5",
  rules: Object.freeze([
    rule(
      "counts",
      "Registry Counts Complete",
      "ENG-5:2 publishes the required registry group counts totaling 56 entries.",
      "total=56",
      `total=${inventory.totalRegistryEntryCount}`,
      "Critical",
    ),
    rule(
      "ids-present",
      "Registry Identifiers Present",
      "Every registry entry declares a stable identifier.",
      "all ids non-empty",
      `idCount=${allRegistryIds.length}`,
    ),
    rule(
      "ids-unique",
      "Registry Identifiers Unique",
      "All ENG-5:2 registry identifiers are globally unique.",
      "uniqueIds=56",
      `uniqueIds=${new Set(allRegistryIds).size}`,
      "Critical",
    ),
    rule(
      "ownership",
      "Registry Ownership Protected",
      "Registry platform ownership remains ENG-5.",
      "ownership=ENG-5",
      `ownership=${inventory.ownership}`,
    ),
    rule(
      "metadata",
      "Registry Metadata Complete",
      "Registry platform metadata declares ENG-5:2 identity and readiness.",
      "platformId=ENG-5:2",
      `platformId=${ExecutivePlanningRegistryPlatform.metadata.platformId}`,
    ),
    rule(
      "lookup-helpers",
      "Registry Lookup Helpers Deterministic",
      "Approved registry lookup helpers return registry entries or undefined.",
      "known id resolves",
      `resolved=${String(Boolean(getExecutivePlanTypeById("eng-5-plan-type-analysis")))}`,
    ),
    rule(
      "inventory",
      "Registry Inventory Accurate",
      "Inventory helper counts match published registry collections.",
      "planTypes=8;steps=10;deps=9",
      `planTypes=${inventory.planTypeCount};steps=${inventory.stepTypeCount};deps=${inventory.dependencyTypeCount}`,
    ),
    rule(
      "platform-metadata",
      "Registry Platform Metadata Frozen",
      "Registry platform declares metadata-only and runtime-free status.",
      "metadataOnly=true;runtimeFree=true",
      `metadataOnly=${String(ExecutivePlanningRegistryPlatform.metadataOnly)};runtimeFree=${String(ExecutivePlanningRegistryPlatform.runtimeFree)}`,
    ),
    rule(
      "unknown-lookup",
      "Unknown Registry Lookup Undefined",
      "Unknown registry identifiers resolve to undefined.",
      "undefined",
      `result=${String(getExecutivePlanningRegistryEntryById("missing"))}`,
      "Warning",
    ),
    rule(
      "execution-isolation",
      "Registry Execution Isolation",
      "Registry inventory keeps OPS as execution owner.",
      "executionOwner=OPS",
      `executionOwner=${inventory.executionOwner}`,
      "Info",
    ),
  ]),
  status: "Pass",
  metadataOnly: true,
  immutable: true,
  deterministic: true,
} as const satisfies ExecutivePlanningValidationGroup);
