import type { ExecutivePlanningManifestDependencyEntry } from "./executivePlanningManifestTypes.ts";

const dependency = (
  key: string,
  source: string,
  target: string,
  dependencyType: string,
  compatibility: ExecutivePlanningManifestDependencyEntry["compatibility"],
  requiredPublicSurface: string,
) => Object.freeze({
  id: `eng-5-manifest-dependency-${key}`,
  source,
  target,
  dependencyType,
  direction: "ForwardOnly",
  compatibility,
  requiredPublicSurface,
  metadataOnly: true,
  runtimeFree: true,
} as const satisfies ExecutivePlanningManifestDependencyEntry);

export const ExecutivePlanningDependencyManifest = Object.freeze([
  dependency(
    "eng-1",
    "ENG-5",
    "ENG-1",
    "PublicIndexCompatibility",
    "PublicIndexCompatible",
    "executiveEnginePublicIndex.ts",
  ),
  dependency(
    "eng-2",
    "ENG-5",
    "ENG-2",
    "PublicIndexCompatibility",
    "PublicIndexCompatible",
    "executiveRequestIntentPublicIndex.ts",
  ),
  dependency(
    "eng-3",
    "ENG-5",
    "ENG-3",
    "PublicIndexCompatibility",
    "PublicIndexCompatible",
    "executiveIntentResolutionPublicIndex.ts",
  ),
  dependency(
    "eng-4",
    "ENG-5",
    "ENG-4",
    "PublicIndexCompatibility",
    "PublicIndexCompatible",
    "executiveContextAssemblyPublicIndex.ts",
  ),
  dependency(
    "eng-5-1",
    "ENG-5:5",
    "ENG-5:1",
    "InternalPhaseDependency",
    "PublicIndexCompatible",
    "executivePlanningIndex.ts",
  ),
  dependency(
    "eng-5-2",
    "ENG-5:5",
    "ENG-5:2",
    "InternalPhaseDependency",
    "PublicIndexCompatible",
    "executivePlanningRegistryIndex.ts",
  ),
  dependency(
    "eng-5-3",
    "ENG-5:5",
    "ENG-5:3",
    "InternalPhaseDependency",
    "PublicIndexCompatible",
    "executivePlanningModelIndex.ts",
  ),
  dependency(
    "eng-5-4",
    "ENG-5:5",
    "ENG-5:4",
    "InternalPhaseDependency",
    "PublicIndexCompatible",
    "executivePlanningValidationIndex.ts",
  ),
  dependency(
    "ops-execution-contracts",
    "ENG-5",
    "OPS",
    "ExecutionBoundaryCompatibility",
    "BoundaryDeclared",
    "OPS public execution contracts",
  ),
] as const);
