import type { ExecutivePlanningCertificationGate } from "./executivePlanningCertificationTypes.ts";

const gate = (
  key: string,
  title: string,
  description: string,
  certificationPurpose: string,
  category: ExecutivePlanningCertificationGate["category"],
  severity: ExecutivePlanningCertificationGate["severity"] = "Critical",
) => Object.freeze({
  id: `eng-5-cert-gate-${key}`,
  title,
  description,
  certificationPurpose,
  category,
  severity,
  status: "Passed",
  expectedStatus: "Passed",
  readinessTarget: "ReadyForFreeze",
  owner: "ENG-5",
  metadataOnly: true,
  runtimeFree: true,
  immutable: true,
  deterministic: true,
} as const satisfies ExecutivePlanningCertificationGate);

export const ExecutivePlanningCertificationGates = Object.freeze([
  gate(
    "foundation",
    "Foundation Certification",
    "Certifies that ENG-5:1 Foundation is complete and metadata-only.",
    "Confirm foundation contracts, capabilities, lifecycle, ownership, and metadata.",
    "Foundation",
  ),
  gate(
    "registry",
    "Registry Certification",
    "Certifies that ENG-5:2 Registry Platform is complete and inventory-stable.",
    "Confirm planning taxonomy registries and lookup surfaces.",
    "Registry",
  ),
  gate(
    "model",
    "Model Certification",
    "Certifies that ENG-5:3 Model Platform is complete and registry-aligned.",
    "Confirm planning model definitions without plan creation or mutation.",
    "Model",
  ),
  gate(
    "validation",
    "Validation Certification",
    "Certifies that ENG-5:4 Validation Platform has passed architectural validation.",
    "Confirm validation groups and rule inventory remain passed.",
    "Validation",
  ),
  gate(
    "manifest",
    "Manifest Certification",
    "Certifies that ENG-5:5 Manifest Platform consolidates prior phases correctly.",
    "Confirm component, dependency, ownership, compatibility, and release inventories.",
    "Manifest",
  ),
  gate(
    "platform",
    "Platform Certification",
    "Certifies that ENG-5:6 Platform aggregation is complete and ready for certification.",
    "Confirm foundation through manifest aggregation into one platform surface.",
    "Platform",
  ),
  gate(
    "ownership",
    "Ownership Certification",
    "Certifies that ENG-5 ownership boundaries and OPS execution ownership are preserved.",
    "Confirm planning owns metadata only and OPS remains execution owner.",
    "Ownership",
  ),
  gate(
    "dependency",
    "Dependency Certification",
    "Certifies that dependencies remain public-index only and forward-only.",
    "Confirm approved public-index dependency boundaries without resolution runtime.",
    "Dependency",
  ),
  gate(
    "compatibility",
    "Compatibility Certification",
    "Certifies compatibility with ENG-1 through ENG-4 and OPS execution boundaries.",
    "Confirm public-index and OPS boundary compatibility declarations.",
    "Compatibility",
  ),
  gate(
    "public-api",
    "Public API Certification",
    "Certifies that approved public APIs remain explicit, stable, and non-wildarded.",
    "Confirm public indices expose approved exports only.",
    "PublicApi",
  ),
  gate(
    "metadata-immutability",
    "Metadata Immutability Certification",
    "Certifies that published certification and prior-phase metadata remain immutable.",
    "Confirm Object.freeze immutability guarantees across ENG-5:1 through ENG-5:6.",
    "Metadata",
  ),
  gate(
    "runtime-free",
    "Runtime-Free Certification",
    "Certifies that no planning, scheduling, or OPS runtime behavior was introduced.",
    "Confirm runtime-free declarations across the Executive Planning architecture.",
    "Runtime",
  ),
  gate(
    "deterministic-behavior",
    "Deterministic Behavior Certification",
    "Certifies that public helpers remain deterministic and side-effect free.",
    "Confirm deterministic helper guarantees for certification and prior platforms.",
    "Determinism",
  ),
  gate(
    "architectural-integrity",
    "Architectural Integrity Certification",
    "Certifies end-to-end architectural integrity from foundation through platform.",
    "Confirm phase inventory integrity and public-surface-only composition.",
    "Integrity",
  ),
  gate(
    "release-readiness",
    "Release Readiness Certification",
    "Certifies that the Executive Planning Platform is ready for ENG-5:8 Freeze.",
    "Confirm Certified status and ReadyForFreeze readiness.",
    "Readiness",
  ),
] as const);
