import type {
  ExecutiveReasoningCertificationGate,
} from "./executiveReasoningCertificationTypes.ts";

const gate = (
  gateNumber: number,
  key: string,
  title: string,
  description: string,
  certificationPurpose: string,
  category: ExecutiveReasoningCertificationGate["category"],
  certifiedPhase: string,
  severity: ExecutiveReasoningCertificationGate["severity"] = "Critical",
) => Object.freeze({
  id: `eng-6-cert-gate-${key}`,
  gateNumber,
  title,
  description,
  certificationPurpose,
  category,
  severity,
  status: "PASS",
  expectedStatus: "PASS",
  certifiedPhase,
  owner: "ENG-6",
  metadataOnly: true,
  runtimeFree: true,
  immutable: true,
  deterministic: true,
  aiFree: true,
} as const satisfies ExecutiveReasoningCertificationGate);

export const ExecutiveReasoningCertificationGates = Object.freeze([
  gate(
    1,
    "foundation",
    "Foundation Certification",
    "Certifies ENG-6:1 Foundation contracts, domains, lifecycle, evidence, and confidence metadata.",
    "Confirm foundation public surface is complete, immutable, and metadata-only.",
    "Foundation",
    "ENG-6:1",
  ),
  gate(
    2,
    "registry",
    "Registry Certification",
    "Certifies ENG-6:2 Registry components, capabilities, and lifecycle inventories.",
    "Confirm registry inventories remain unique, complete, and ownership-safe.",
    "Registry",
    "ENG-6:2",
  ),
  gate(
    3,
    "model",
    "Model Certification",
    "Certifies ENG-6:3 Model definitions and structural relationship metadata.",
    "Confirm models, versions, owners, and relationship targets exist as metadata.",
    "Model",
    "ENG-6:3",
  ),
  gate(
    4,
    "validation",
    "Validation Certification",
    "Certifies ENG-6:4 Validation domains and rules declared PASS.",
    "Confirm validation runner metadata aggregates to PASS without runtime validation.",
    "Validation",
    "ENG-6:4",
  ),
  gate(
    5,
    "manifest",
    "Manifest Certification",
    "Certifies ENG-6:5 Manifest sections, dependency map, ownership, and public API inventory.",
    "Confirm manifest aggregates ENG-6:1 through ENG-6:4 without modification.",
    "Manifest",
    "ENG-6:5",
  ),
  gate(
    6,
    "platform",
    "Platform Certification",
    "Certifies ENG-6:6 Platform aggregation of foundation through manifest.",
    "Confirm platform sections, registry, summary, and readiness are READY.",
    "Platform",
    "ENG-6:6",
  ),
  gate(
    7,
    "ownership",
    "Ownership Certification",
    "Certifies single ownership, ownership completeness, and ownership consistency.",
    "Confirm every artifact has exactly one ENG-6 owner with no duplicate ownership.",
    "Ownership",
    "ENG-6:1–ENG-6:6",
  ),
  gate(
    8,
    "dependency",
    "Dependency Certification",
    "Certifies allowed Engine dependencies and rejected external/runtime dependencies.",
    "Confirm only ENG-1 through ENG-6:6 public surfaces are declared as dependencies.",
    "Dependency",
    "ENG-6:1–ENG-6:6",
  ),
  gate(
    9,
    "public-api",
    "Public API Certification",
    "Certifies approved exports only, immutable exports, and no internal leakage.",
    "Confirm public surfaces expose approved APIs without internal export leakage.",
    "PublicApi",
    "ENG-6:1–ENG-6:6",
  ),
  gate(
    10,
    "compatibility",
    "Compatibility Certification",
    "Certifies backward, namespace, model, registry, and public API compatibility.",
    "Confirm compatibility metadata remains Compatible/Stable/ForwardCompatible.",
    "Compatibility",
    "ENG-6:5–ENG-6:6",
  ),
  gate(
    11,
    "immutability",
    "Immutability Certification",
    "Certifies frozen metadata, deterministic metadata, and runtime-free declarations.",
    "Confirm Object.freeze and runtime-free declarations across ENG-6:1 through ENG-6:6.",
    "Immutability",
    "ENG-6:1–ENG-6:6",
  ),
  gate(
    12,
    "release-readiness",
    "Release Readiness Certification",
    "Declares CERTIFIED status and ReadyForFreeze readiness for ENG-6:8 Freeze.",
    "Confirm certification status CERTIFIED and release readiness ReadyForFreeze.",
    "ReleaseReadiness",
    "ENG-6:7",
  ),
] as const);

export const ExecutiveReasoningCertificationAllowedDependencies = Object.freeze([
  "ENG-1",
  "ENG-2",
  "ENG-3",
  "ENG-4",
  "ENG-5",
  "ENG-6:1",
  "ENG-6:2",
  "ENG-6:3",
  "ENG-6:4",
  "ENG-6:5",
  "ENG-6:6",
] as const);

export const ExecutiveReasoningCertificationRejectedDependencies = Object.freeze([
  "BUS",
  "OPS",
  "Advisor",
  "Scene",
  "Director",
  "Runtime",
  "Integration",
  "Persistence",
] as const);

export const ExecutiveReasoningCertificationRegistry = Object.freeze({
  certificationId: "ENG-6:7",
  version: "1.0.0",
  namespace: "nexora.engine.executive.reasoning.certification",
  name: "Executive Reasoning Certification Registry",
  description:
    "Immutable certification registry for architectural verification of ENG-6:1 through ENG-6:6.",
  certificationStatus: "CERTIFIED",
  certifiedPhases: Object.freeze([
    "ENG-6:1",
    "ENG-6:2",
    "ENG-6:3",
    "ENG-6:4",
    "ENG-6:5",
    "ENG-6:6",
  ] as const),
  totalGates: 12,
  gates: ExecutiveReasoningCertificationGates,
  gateCount: ExecutiveReasoningCertificationGates.length,
  certificationDatePlaceholder: "CERTIFICATION_DATE_UNSET",
  releaseTarget: "ENG-6:8",
  releaseReadiness: "ReadyForFreeze",
  allowedDependencies: ExecutiveReasoningCertificationAllowedDependencies,
  rejectedDependencies: ExecutiveReasoningCertificationRejectedDependencies,
  owner: "ENG-6",
  metadataOnly: true,
  immutable: true,
  deterministic: true,
  runtimeFree: true,
  aiFree: true,
} as const);

const gateIndex = Object.freeze(
  Object.fromEntries(
    ExecutiveReasoningCertificationGates.map((entry) => [entry.id, entry]),
  ) as Readonly<Record<string, ExecutiveReasoningCertificationGate | undefined>>,
);

export const getExecutiveReasoningCertificationGateById = (
  id: string,
): ExecutiveReasoningCertificationGate | undefined => gateIndex[id];
