import {
  ExecutiveOrchestrationFoundation,
} from "./executiveOrchestrationFoundation.ts";
import type {
  ExecutiveOrchestrationComponentEntry,
  ExecutiveOrchestrationComponentId,
  ExecutiveOrchestrationExecutionMode,
  ExecutiveOrchestrationCapabilityId,
  ExecutiveOrchestrationCoordinationTargetId,
  ExecutiveOrchestrationDependencyId,
  ExecutiveOrchestrationLifecycleStageId,
  ExecutiveOrchestrationResponsibilityId,
  ExecutiveOrchestrationResponsibilityOwnership,
  ExecutiveOrchestrationResponsibilityEntry,
} from "./executiveOrchestrationRegistryTypes.ts";

const ownership = (
  responsibilityId: ExecutiveOrchestrationResponsibilityId,
  role: ExecutiveOrchestrationResponsibilityOwnership["role"],
) => Object.freeze({
  responsibilityId,
  role,
  metadataOnly: true,
  immutable: true,
} as const satisfies ExecutiveOrchestrationResponsibilityOwnership);

const component = (
  componentId: ExecutiveOrchestrationComponentId,
  name: string,
  description: string,
  ownedResponsibilities: readonly ExecutiveOrchestrationResponsibilityOwnership[],
  coordinationTargets: readonly ExecutiveOrchestrationCoordinationTargetId[],
  supportedCapabilities: readonly ExecutiveOrchestrationCapabilityId[],
  executionModes: readonly ExecutiveOrchestrationExecutionMode[],
  lifecycleParticipation: readonly ExecutiveOrchestrationLifecycleStageId[],
  dependencyIds: readonly ExecutiveOrchestrationDependencyId[],
) => Object.freeze({
  id: `eng-8-comp-${componentId}` as const,
  componentId,
  name,
  description,
  kind: "Component",
  ownedResponsibilities: Object.freeze([...ownedResponsibilities]),
  coordinationTargets: Object.freeze([...coordinationTargets]),
  supportedCapabilities: Object.freeze([...supportedCapabilities]),
  executionModes: Object.freeze([...executionModes]),
  lifecycleParticipation: Object.freeze([...lifecycleParticipation]),
  dependencyIds: Object.freeze([...dependencyIds]),
  status: "Registered",
  metadataOnly: true,
  runtimeFree: true,
  immutable: true,
} as const satisfies ExecutiveOrchestrationComponentEntry);

/**
 * Canonical orchestration component registry for ENG-8:2.
 * Consumes ENG-8:1 foundation as the sole foundation dependency.
 */
export const ExecutiveOrchestrationComponentRegistry = Object.freeze([
  component(
    "pipeline-orchestrator",
    "Pipeline Orchestrator",
    "Primary owner of pipeline orchestration architecture metadata.",
    Object.freeze([ownership("pipeline-orchestration", "PrimaryOwner")]),
    Object.freeze([
      "executive-request",
      "intent-resolution",
      "context-assembly",
      "planning",
      "reasoning",
      "decision",
    ] as const),
    Object.freeze(["pipeline-coordination", "sequential-orchestration"] as const),
    Object.freeze(["Sequential", "Synchronized"] as const),
    Object.freeze([
      "Idle",
      "ReceiveRequest",
      "PreparePipeline",
      "CoordinateExecution",
      "Complete",
    ] as const),
    Object.freeze([
      "eng-1-public-api",
      "eng-2-public-api",
      "eng-3-public-api",
      "eng-4-public-api",
      "eng-5-public-api",
      "eng-6-public-api",
      "eng-7-public-api",
    ] as const),
  ),
  component(
    "engine-coordinator",
    "Engine Coordinator",
    "Primary owner of component coordination and engine synchronization metadata.",
    Object.freeze([
      ownership("component-coordination", "PrimaryOwner"),
      ownership("engine-synchronization", "PrimaryOwner"),
    ]),
    Object.freeze([
      "executive-request",
      "intent-resolution",
      "context-assembly",
      "planning",
      "reasoning",
      "decision",
    ] as const),
    Object.freeze(["pipeline-coordination", "completion-synchronization"] as const),
    Object.freeze(["Sequential", "Synchronized"] as const),
    Object.freeze([
      "PreparePipeline",
      "ResolveDependencies",
      "CoordinateExecution",
      "Complete",
    ] as const),
    Object.freeze([
      "eng-1-public-api",
      "eng-2-public-api",
      "eng-3-public-api",
      "eng-4-public-api",
      "eng-5-public-api",
      "eng-6-public-api",
      "eng-7-public-api",
    ] as const),
  ),
  component(
    "dependency-coordinator",
    "Dependency Coordinator",
    "Primary owner of dependency-coordination architecture metadata.",
    Object.freeze([ownership("dependency-coordination", "PrimaryOwner")]),
    Object.freeze([
      "executive-request",
      "intent-resolution",
      "context-assembly",
      "planning",
      "reasoning",
      "decision",
      "bus-platforms",
      "ops-platforms",
    ] as const),
    Object.freeze(["dependency-resolution"] as const),
    Object.freeze(["Sequential", "Conditional"] as const),
    Object.freeze(["ResolveDependencies", "CoordinateExecution"] as const),
    Object.freeze([
      "eng-1-public-api",
      "eng-2-public-api",
      "eng-3-public-api",
      "eng-4-public-api",
      "eng-5-public-api",
      "eng-6-public-api",
      "eng-7-public-api",
      "bus-public-apis",
      "ops-public-apis",
    ] as const),
  ),
  component(
    "execution-sequence-coordinator",
    "Execution Sequence Coordinator",
    "Primary owner of execution-ordering and sequential-execution declarations.",
    Object.freeze([
      ownership("execution-ordering", "PrimaryOwner"),
      ownership("sequential-execution-declaration", "PrimaryOwner"),
    ]),
    Object.freeze([
      "executive-request",
      "intent-resolution",
      "context-assembly",
      "planning",
      "reasoning",
      "decision",
    ] as const),
    Object.freeze(["sequential-orchestration", "pipeline-coordination"] as const),
    Object.freeze(["Sequential"] as const),
    Object.freeze(["PreparePipeline", "CoordinateExecution"] as const),
    Object.freeze([
      "eng-2-public-api",
      "eng-3-public-api",
      "eng-4-public-api",
      "eng-5-public-api",
      "eng-6-public-api",
      "eng-7-public-api",
    ] as const),
  ),
  component(
    "parallel-coordination-descriptor",
    "Parallel Coordination Descriptor",
    "Primary owner of parallel-execution declaration metadata.",
    Object.freeze([ownership("parallel-execution-declaration", "PrimaryOwner")]),
    Object.freeze(["bus-platforms", "ops-platforms"] as const),
    Object.freeze(["parallel-orchestration"] as const),
    Object.freeze(["Parallel"] as const),
    Object.freeze(["CoordinateExecution"] as const),
    Object.freeze(["bus-public-apis", "ops-public-apis"] as const),
  ),
  component(
    "context-propagation-coordinator",
    "Context Propagation Coordinator",
    "Primary owner of context-propagation architecture metadata.",
    Object.freeze([ownership("context-propagation", "PrimaryOwner")]),
    Object.freeze([
      "context-assembly",
      "planning",
      "reasoning",
      "decision",
    ] as const),
    Object.freeze(["pipeline-coordination"] as const),
    Object.freeze(["Sequential", "Synchronized"] as const),
    Object.freeze(["PreparePipeline", "CoordinateExecution"] as const),
    Object.freeze(["eng-4-public-api", "eng-5-public-api", "eng-6-public-api", "eng-7-public-api"] as const),
  ),
  component(
    "result-aggregator",
    "Result Aggregator",
    "Primary owner of result-aggregation architecture metadata.",
    Object.freeze([ownership("result-aggregation", "PrimaryOwner")]),
    Object.freeze(["decision", "bus-platforms", "ops-platforms", "advisor"] as const),
    Object.freeze(["result-aggregation"] as const),
    Object.freeze(["Aggregated", "Synchronized"] as const),
    Object.freeze(["AggregateResults", "PrepareResponse"] as const),
    Object.freeze([
      "eng-7-public-api",
      "bus-public-apis",
      "ops-public-apis",
      "advisor-public-apis",
    ] as const),
  ),
  component(
    "completion-coordinator",
    "Completion Coordinator",
    "Primary owner of completion-routing architecture metadata.",
    Object.freeze([ownership("completion-routing", "PrimaryOwner")]),
    Object.freeze(["decision", "advisor"] as const),
    Object.freeze(["completion-synchronization"] as const),
    Object.freeze(["Synchronized", "Handoff"] as const),
    Object.freeze(["AggregateResults", "PrepareResponse", "Complete"] as const),
    Object.freeze(["eng-7-public-api", "advisor-public-apis"] as const),
  ),
  component(
    "failure-routing-coordinator",
    "Failure Routing Coordinator",
    "Primary owner of failure-routing architecture metadata.",
    Object.freeze([ownership("failure-routing", "PrimaryOwner")]),
    Object.freeze([
      "executive-request",
      "intent-resolution",
      "context-assembly",
      "planning",
      "reasoning",
      "decision",
      "advisor",
    ] as const),
    Object.freeze(["failure-propagation"] as const),
    Object.freeze(["Conditional", "Handoff"] as const),
    Object.freeze([
      "CoordinateExecution",
      "AggregateResults",
      "PrepareResponse",
      "Complete",
    ] as const),
    Object.freeze([
      "eng-2-public-api",
      "eng-3-public-api",
      "eng-4-public-api",
      "eng-5-public-api",
      "eng-6-public-api",
      "eng-7-public-api",
      "advisor-public-apis",
    ] as const),
  ),
  component(
    "advisor-handoff-coordinator",
    "Advisor Handoff Coordinator",
    "Primary owner of advisor-handoff architecture metadata.",
    Object.freeze([ownership("advisor-handoff", "PrimaryOwner")]),
    Object.freeze(["advisor", "decision"] as const),
    Object.freeze(["advisor-routing"] as const),
    Object.freeze(["Handoff"] as const),
    Object.freeze(["PrepareResponse", "Complete"] as const),
    Object.freeze(["eng-7-public-api", "advisor-public-apis"] as const),
  ),
  component(
    "bus-coordination-gateway",
    "BUS Coordination Gateway",
    "Supporting gateway for BUS public-API coordination references.",
    Object.freeze([
      ownership("component-coordination", "SupportingParticipant"),
      ownership("dependency-coordination", "SupportingParticipant"),
    ]),
    Object.freeze(["bus-platforms", "decision"] as const),
    Object.freeze(["parallel-orchestration", "dependency-resolution"] as const),
    Object.freeze(["Parallel", "Conditional"] as const),
    Object.freeze(["ResolveDependencies", "CoordinateExecution"] as const),
    Object.freeze(["eng-7-public-api", "bus-public-apis"] as const),
  ),
  component(
    "ops-coordination-gateway",
    "OPS Coordination Gateway",
    "Supporting gateway for OPS public-API coordination references.",
    Object.freeze([
      ownership("component-coordination", "SupportingParticipant"),
      ownership("dependency-coordination", "SupportingParticipant"),
    ]),
    Object.freeze(["ops-platforms", "decision"] as const),
    Object.freeze(["parallel-orchestration", "dependency-resolution"] as const),
    Object.freeze(["Parallel", "Conditional"] as const),
    Object.freeze(["ResolveDependencies", "CoordinateExecution"] as const),
    Object.freeze(["eng-7-public-api", "ops-public-apis"] as const),
  ),
] as const);

const responsibilityEntry = (
  responsibilityId: ExecutiveOrchestrationResponsibilityId,
  name: string,
  primaryOwnerComponentId: ExecutiveOrchestrationComponentId,
  supportingComponentIds: readonly ExecutiveOrchestrationComponentId[] = Object.freeze([]),
) => Object.freeze({
  id: `eng-8-resp-${responsibilityId}` as const,
  responsibilityId,
  name,
  primaryOwnerComponentId,
  supportingComponentIds: Object.freeze([...supportingComponentIds]),
  kind: "Responsibility",
  status: "Registered",
  metadataOnly: true,
  runtimeFree: true,
  immutable: true,
} as const satisfies ExecutiveOrchestrationResponsibilityEntry);

/**
 * Declared responsibility ownership registry aligned with ENG-8:1 responsibilities.
 */
export const ExecutiveOrchestrationResponsibilityRegistry = Object.freeze([
  responsibilityEntry("pipeline-orchestration", "Pipeline orchestration", "pipeline-orchestrator"),
  responsibilityEntry("execution-ordering", "Execution ordering", "execution-sequence-coordinator"),
  responsibilityEntry(
    "component-coordination",
    "Component coordination",
    "engine-coordinator",
    Object.freeze(["bus-coordination-gateway", "ops-coordination-gateway"] as const),
  ),
  responsibilityEntry("context-propagation", "Context propagation", "context-propagation-coordinator"),
  responsibilityEntry(
    "dependency-coordination",
    "Dependency coordination",
    "dependency-coordinator",
    Object.freeze(["bus-coordination-gateway", "ops-coordination-gateway"] as const),
  ),
  responsibilityEntry(
    "parallel-execution-declaration",
    "Parallel execution declaration",
    "parallel-coordination-descriptor",
  ),
  responsibilityEntry(
    "sequential-execution-declaration",
    "Sequential execution declaration",
    "execution-sequence-coordinator",
  ),
  responsibilityEntry("result-aggregation", "Result aggregation", "result-aggregator"),
  responsibilityEntry("completion-routing", "Completion routing", "completion-coordinator"),
  responsibilityEntry("failure-routing", "Failure routing", "failure-routing-coordinator"),
  responsibilityEntry("advisor-handoff", "Advisor handoff", "advisor-handoff-coordinator"),
  responsibilityEntry("engine-synchronization", "Engine synchronization", "engine-coordinator"),
] as const);

export const ExecutiveOrchestrationComponentRegistryFoundationId =
  ExecutiveOrchestrationFoundation.id;
