import type {
  ExecutiveDecisionCertificationCategory,
  ExecutiveDecisionCertificationGate,
  ExecutiveDecisionCertificationGateId,
  ExecutiveDecisionCertificationSeverity,
} from "./executiveDecisionCertificationTypes.ts";

const gate = (
  id: ExecutiveDecisionCertificationGateId,
  name: string,
  description: string,
  category: ExecutiveDecisionCertificationCategory,
  severity: ExecutiveDecisionCertificationSeverity,
  validatedPhases: readonly string[],
  evidenceReferences: readonly string[],
  expectedState: string,
  actualDeclaredState: string,
  blocking: boolean,
) => Object.freeze({
  id,
  name,
  description,
  category,
  severity,
  validatedPhases,
  evidenceReferences,
  expectedState,
  actualDeclaredState,
  status: "PASS",
  blocking,
  metadataOnly: true,
  immutable: true,
  runtimeBehavior: "None",
} as const satisfies ExecutiveDecisionCertificationGate);

/**
 * Canonical ENG-7:7 certification-gate registry.
 * All gate results are declared metadata only; no gate executes.
 */
export const ExecutiveDecisionCertificationGateRegistry = Object.freeze([
  gate(
    "FoundationIntegrity",
    "Foundation Integrity",
    "Certifies ENG-7:1 foundation public architecture integrity.",
    "Foundation",
    "Critical",
    Object.freeze(["ENG-7:1"] as const),
    Object.freeze(["executiveDecisionPublicApi.ts"] as const),
    "FoundationComplete",
    "FoundationComplete",
    true,
  ),
  gate(
    "RegistryIntegrity",
    "Registry Integrity",
    "Certifies ENG-7:2 registry public architecture integrity.",
    "Registry",
    "Critical",
    Object.freeze(["ENG-7:2"] as const),
    Object.freeze(["executiveDecisionRegistryPlatform.ts"] as const),
    "RegistryComplete",
    "RegistryComplete",
    true,
  ),
  gate(
    "ModelIntegrity",
    "Model Integrity",
    "Certifies ENG-7:3 model public architecture integrity.",
    "Model",
    "Critical",
    Object.freeze(["ENG-7:3"] as const),
    Object.freeze(["executiveDecisionModelPlatform.ts"] as const),
    "ModelComplete",
    "ModelComplete",
    true,
  ),
  gate(
    "ValidationIntegrity",
    "Validation Integrity",
    "Certifies ENG-7:4 validation rules and declared PASS state.",
    "Validation",
    "Critical",
    Object.freeze(["ENG-7:4"] as const),
    Object.freeze(["executiveDecisionValidationPlatform.ts"] as const),
    "ValidationCertified",
    "ValidationCertified",
    true,
  ),
  gate(
    "ManifestIntegrity",
    "Manifest Integrity",
    "Certifies ENG-7:5 manifest completeness and inventory stability.",
    "Manifest",
    "Critical",
    Object.freeze(["ENG-7:5"] as const),
    Object.freeze(["executiveDecisionManifestPlatform.ts"] as const),
    "ManifestComplete",
    "ManifestComplete",
    true,
  ),
  gate(
    "PlatformIntegrity",
    "Platform Integrity",
    "Certifies ENG-7:6 platform assembly and component registry integrity.",
    "Platform",
    "Critical",
    Object.freeze(["ENG-7:6"] as const),
    Object.freeze(["executiveDecisionPlatform.ts"] as const),
    "PlatformAssembled",
    "PlatformAssembled",
    true,
  ),
  gate(
    "OwnershipIntegrity",
    "Ownership Integrity",
    "Certifies ENG-7 ownership boundaries remain isolated and unduplicated.",
    "Ownership",
    "High",
    Object.freeze(["ENG-7:1", "ENG-7:2", "ENG-7:3", "ENG-7:4", "ENG-7:5", "ENG-7:6"] as const),
    Object.freeze(["ownership-summary"] as const),
    "OwnershipProtected",
    "OwnershipProtected",
    true,
  ),
  gate(
    "DependencyIntegrity",
    "Dependency Integrity",
    "Certifies public-API-only forward dependencies across ENG-7 phases.",
    "Dependency",
    "High",
    Object.freeze(["ENG-7:1", "ENG-7:2", "ENG-7:3", "ENG-7:4", "ENG-7:5", "ENG-7:6"] as const),
    Object.freeze(["dependency-summary"] as const),
    "DependencySafe",
    "DependencySafe",
    true,
  ),
  gate(
    "PublicApiIntegrity",
    "Public API Integrity",
    "Certifies approved public export surfaces remain stable and isolated.",
    "PublicApi",
    "High",
    Object.freeze(["ENG-7:1", "ENG-7:2", "ENG-7:3", "ENG-7:4", "ENG-7:5", "ENG-7:6"] as const),
    Object.freeze(["public-api-policy"] as const),
    "PublicApiStable",
    "PublicApiStable",
    true,
  ),
  gate(
    "ImmutabilityIntegrity",
    "Immutability Integrity",
    "Certifies deep freeze and immutability declarations across certified surfaces.",
    "Immutability",
    "High",
    Object.freeze(["ENG-7:1", "ENG-7:2", "ENG-7:3", "ENG-7:4", "ENG-7:5", "ENG-7:6"] as const),
    Object.freeze(["immutability-declaration"] as const),
    "DeeplyFrozen",
    "DeeplyFrozen",
    true,
  ),
  gate(
    "MetadataOnlyIntegrity",
    "Metadata Only Integrity",
    "Certifies architecture remains metadata-only with no behavioral surfaces.",
    "MetadataOnly",
    "Critical",
    Object.freeze(["ENG-7:1", "ENG-7:2", "ENG-7:3", "ENG-7:4", "ENG-7:5", "ENG-7:6"] as const),
    Object.freeze(["architecture-mode"] as const),
    "MetadataOnly",
    "MetadataOnly",
    true,
  ),
  gate(
    "RuntimeFreeIntegrity",
    "Runtime Free Integrity",
    "Certifies zero runtime behavior entries across certified phases.",
    "RuntimeFree",
    "Critical",
    Object.freeze(["ENG-7:1", "ENG-7:2", "ENG-7:3", "ENG-7:4", "ENG-7:5", "ENG-7:6"] as const),
    Object.freeze(["runtime-behavior"] as const),
    "RuntimeFree",
    "RuntimeFree",
    true,
  ),
  gate(
    "AntiDuplicationIntegrity",
    "Anti-Duplication Integrity",
    "Certifies prior phase ownership is consumed without redefinition.",
    "AntiDuplication",
    "High",
    Object.freeze(["ENG-7:1", "ENG-7:2", "ENG-7:3", "ENG-7:4", "ENG-7:5", "ENG-7:6"] as const),
    Object.freeze(["anti-duplication-policy"] as const),
    "AntiDuplicationCompliant",
    "AntiDuplicationCompliant",
    true,
  ),
  gate(
    "CompatibilityIntegrity",
    "Compatibility Integrity",
    "Certifies declared ENG-7 compatibility relationships and cross-platform refs.",
    "Compatibility",
    "Medium",
    Object.freeze(["ENG-7:1", "ENG-7:2", "ENG-7:3", "ENG-7:4", "ENG-7:5", "ENG-7:6"] as const),
    Object.freeze(["compatibility-declarations"] as const),
    "CompatibilityCertified",
    "CompatibilityCertified",
    true,
  ),
  gate(
    "FreezeReadiness",
    "Freeze Readiness",
    "Certifies ENG-7 architecture is ready for ENG-7:8 freeze.",
    "FreezeReadiness",
    "Critical",
    Object.freeze(["ENG-7:1", "ENG-7:2", "ENG-7:3", "ENG-7:4", "ENG-7:5", "ENG-7:6", "ENG-7:7"] as const),
    Object.freeze(["certification-readiness"] as const),
    "ReadyForDecisionFreeze",
    "ReadyForDecisionFreeze",
    true,
  ),
] as const);

export const ExecutiveDecisionCertificationGateTotals = Object.freeze({
  gateCount: 15,
  passedGateCount: 15,
  failedGateCount: 0,
  blockingGateCount: 15,
} as const);

const gateIndex = Object.freeze(
  Object.fromEntries(
    ExecutiveDecisionCertificationGateRegistry.map((entry) => [entry.id, entry]),
  ) as Readonly<Record<string, ExecutiveDecisionCertificationGate | undefined>>,
);

export const getExecutiveDecisionCertificationGateById = (
  id: string,
): ExecutiveDecisionCertificationGate | undefined => gateIndex[id];
