import { ExecutiveDecisionCapabilityRegistry, ExecutiveDecisionDependencyMap, ExecutiveDecisionOwnershipMap, getExecutiveDecisionFoundation, getExecutiveDecisionMetadata } from "./executiveDecisionPublicApi.ts";
import type { ExecutiveDecisionValidationRule } from "./executiveDecisionValidationTypes.ts";

const rule = (
  key: string,
  name: string,
  category: ExecutiveDecisionValidationRule["category"],
  description: string,
  validatedArtifact: string,
  expectedState: string,
  actualMetadataResult: string,
  targetPhase: ExecutiveDecisionValidationRule["targetPhase"] = "ENG-7:1",
  severity: ExecutiveDecisionValidationRule["severity"] = "Error",
) => Object.freeze({
  id: `eng-7-validation-${key}`,
  name,
  category,
  severity,
  description,
  validatedArtifact,
  expectedState,
  actualMetadataResult,
  status: "PASS",
  owner: "ENG-7",
  targetPhase,
  metadataOnly: true,
  immutable: true,
  deterministic: true,
  runtimeFree: true,
  aiFree: true,
} as const satisfies ExecutiveDecisionValidationRule);

const foundation = getExecutiveDecisionFoundation();
const metadata = getExecutiveDecisionMetadata();

export const ExecutiveDecisionFoundationValidationRules = Object.freeze([
  rule(
    "foundation-immutable",
    "Immutable Foundation",
    "Foundation",
    "ENG-7:1 foundation is published as immutable metadata.",
    "ExecutiveDecisionFoundation",
    "immutable=true",
    `immutable=${foundation.immutable}`,
    "ENG-7:1",
    "Critical",
  ),
  rule(
    "foundation-ownership-integrity",
    "Foundation Ownership Integrity",
    "Foundation",
    "Foundation ownership map is bound to ENG-7.",
    "ExecutiveDecisionOwnershipMap",
    "owner=ENG-7",
    `owner=${ExecutiveDecisionOwnershipMap.owner}`,
  ),
  rule(
    "foundation-dependency-integrity",
    "Foundation Dependency Integrity",
    "Foundation",
    "Foundation dependency map declares allowed incoming ENG-1 through ENG-6.",
    "ExecutiveDecisionDependencyMap",
    "incoming=6",
    `incoming=${ExecutiveDecisionDependencyMap.incoming.length}`,
  ),
  rule(
    "foundation-capability-ownership",
    "Capability Ownership",
    "Foundation",
    "Foundation capability registry is owned by ENG-7 and complete.",
    "ExecutiveDecisionCapabilityRegistry",
    "capabilities=8",
    `capabilities=${ExecutiveDecisionCapabilityRegistry.length}`,
  ),
  rule(
    "public-api-foundation-export",
    "Public API Foundation Export",
    "Public API",
    "Public API publishes ExecutiveDecisionFoundation.",
    "executiveDecisionPublicApi.ts",
    "foundationId=ENG-7:1",
    `foundationId=${foundation.id}`,
  ),
  rule(
    "public-api-capability-export",
    "Public API Capability Export",
    "Public API",
    "Public API publishes ExecutiveDecisionCapabilityRegistry.",
    "executiveDecisionPublicApi.ts",
    "capabilityExport=present",
    `capabilityCount=${ExecutiveDecisionCapabilityRegistry.length}`,
  ),
  rule(
    "public-api-ownership-export",
    "Public API Ownership Export",
    "Public API",
    "Public API publishes ExecutiveDecisionOwnershipMap.",
    "executiveDecisionPublicApi.ts",
    "ownershipExport=present",
    `owner=${ExecutiveDecisionOwnershipMap.owner}`,
  ),
  rule(
    "public-api-helpers",
    "Public API Helper Completeness",
    "Public API",
    "Public API helpers return foundation and metadata.",
    "getExecutiveDecisionFoundation|getExecutiveDecisionMetadata",
    "helpers=deterministic",
    `platformId=${metadata.platformId};next=${metadata.nextPhase}`,
  ),
] as const);

export const ExecutiveDecisionFoundationValidation = Object.freeze({
  id: "eng-7-validation-group-foundation",
  name: "Foundation",
  description: "Architectural validation of ENG-7:1 Foundation public metadata.",
  rules: ExecutiveDecisionFoundationValidationRules,
  status: "PASS",
  owner: "ENG-7",
  metadataOnly: true,
  immutable: true,
  deterministic: true,
} as const);
