import { ExecutiveDecisionCertificationCompatibility } from "./executiveDecisionCertificationCompatibility.ts";
import {
  ExecutiveDecisionCertificationEvidence,
  ExecutiveDecisionCertificationInventory,
  ExecutiveDecisionCertificationPhaseEvidence,
} from "./executiveDecisionCertificationEvidence.ts";
import {
  ExecutiveDecisionCertificationGateRegistry,
  ExecutiveDecisionCertificationGateTotals,
} from "./executiveDecisionCertificationGateRegistry.ts";
import type {
  ExecutiveDecisionCertificationMetadata as ExecutiveDecisionCertificationMetadataDescriptor,
  ExecutiveDecisionCertificationReadiness as ExecutiveDecisionCertificationReadinessDescriptor,
} from "./executiveDecisionCertificationTypes.ts";

export const ExecutiveDecisionCertificationMetadata = Object.freeze({
  id: "ENG-7:7",
  name: "Executive Decision Certification Platform",
  namespace: "Nexora.Engine.ExecutiveDecision.Certification",
  version: "1.0.0",
  status: "Certified",
  architectureMode: "MetadataOnly",
  immutability: "DeeplyFrozen",
  runtimeBehavior: "None",
  owner: "ENG-7",
  previousPhase: "ENG-7:6",
  nextPhase: "ENG-7:8",
  validationStatus: "ValidationCertified",
  manifestStatus: "ManifestComplete",
  platformStatus: "PlatformAssembled",
  certificationStatus: "Certified",
  readiness: "ReadyForDecisionFreeze",
  metadataOnly: true,
  immutable: true,
  deterministic: true,
  runtimeFree: true,
} as const satisfies ExecutiveDecisionCertificationMetadataDescriptor);

export const ExecutiveDecisionCertificationReadiness = Object.freeze({
  foundationCertified: true,
  registryCertified: true,
  modelCertified: true,
  validationCertified: true,
  manifestCertified: true,
  platformCertified: true,
  ownershipCertified: true,
  dependencyCertified: true,
  publicApiCertified: true,
  immutabilityCertified: true,
  metadataOnlyCertified: true,
  runtimeFreeCertified: true,
  antiDuplicationCertified: true,
  compatibilityCertified: true,
  regressionCertified: true,
  allGatesPassing: true,
  certificationComplete: true,
  readyForFreeze: true,
  readyForPublicIndex: false,
  released: false,
  metadataOnly: true,
  immutable: true,
} as const satisfies ExecutiveDecisionCertificationReadinessDescriptor);

export const ExecutiveDecisionCertificationBlockers = Object.freeze({
  failedGates: 0,
  validationFailures: 0,
  ownershipConflicts: 0,
  dependencyViolations: 0,
  publicApiLeaks: 0,
  immutabilityViolations: 0,
  runtimeBehaviorViolations: 0,
  antiDuplicationViolations: 0,
  compatibilityFailures: 0,
  regressionFailures: 0,
  metadataOnly: true,
  immutable: true,
} as const);

const section = (
  id: string,
  name: string,
  description: string,
  order: number,
  payload: object,
) => Object.freeze({
  id,
  name,
  description,
  order,
  payload,
  metadataOnly: true,
  immutable: true,
} as const);

/**
 * Canonical immutable certification manifest with 13 ordered sections.
 */
export const ExecutiveDecisionCertificationManifest = Object.freeze({
  metadata: ExecutiveDecisionCertificationMetadata,
  sections: Object.freeze([
    section(
      "foundation",
      "Foundation",
      "Certified ENG-7:1 foundation evidence.",
      1,
      ExecutiveDecisionCertificationPhaseEvidence[0],
    ),
    section(
      "registry",
      "Registry",
      "Certified ENG-7:2 registry evidence.",
      2,
      ExecutiveDecisionCertificationPhaseEvidence[1],
    ),
    section(
      "model",
      "Model",
      "Certified ENG-7:3 model evidence.",
      3,
      ExecutiveDecisionCertificationPhaseEvidence[2],
    ),
    section(
      "validation",
      "Validation",
      "Certified ENG-7:4 validation evidence.",
      4,
      ExecutiveDecisionCertificationPhaseEvidence[3],
    ),
    section(
      "manifest",
      "Manifest",
      "Certified ENG-7:5 manifest evidence.",
      5,
      ExecutiveDecisionCertificationPhaseEvidence[4],
    ),
    section(
      "platform",
      "Platform",
      "Certified ENG-7:6 platform evidence.",
      6,
      ExecutiveDecisionCertificationPhaseEvidence[5],
    ),
    section(
      "ownership",
      "Ownership",
      "Certified ownership integrity declarations.",
      7,
      Object.freeze({ status: "OwnershipCertified", conflicts: 0 } as const),
    ),
    section(
      "dependencies",
      "Dependencies",
      "Certified forward-only dependency integrity.",
      8,
      Object.freeze({ status: "DependencyCertified", violations: 0 } as const),
    ),
    section(
      "publicApi",
      "Public API",
      "Certified public API isolation and stability.",
      9,
      Object.freeze({ status: "PublicApiCertified", leaks: 0 } as const),
    ),
    section(
      "compatibility",
      "Compatibility",
      "Certified compatibility relationships.",
      10,
      ExecutiveDecisionCertificationCompatibility.relationships,
    ),
    section(
      "regression",
      "Regression",
      "Certified regression protection declarations.",
      11,
      ExecutiveDecisionCertificationCompatibility.regressions,
    ),
    section(
      "readiness",
      "Readiness",
      "Certified freeze-readiness declarations.",
      12,
      ExecutiveDecisionCertificationReadiness,
    ),
    section(
      "certification",
      "Certification",
      "Final certification gate registry and inventory.",
      13,
      Object.freeze({
        gates: ExecutiveDecisionCertificationGateRegistry,
        gateTotals: ExecutiveDecisionCertificationGateTotals,
        inventory: ExecutiveDecisionCertificationInventory,
        evidence: ExecutiveDecisionCertificationEvidence,
        blockers: ExecutiveDecisionCertificationBlockers,
        finalState: "Certified",
      } as const),
    ),
  ] as const),
  gateRegistry: ExecutiveDecisionCertificationGateRegistry,
  phaseEvidence: ExecutiveDecisionCertificationPhaseEvidence,
  inventory: ExecutiveDecisionCertificationInventory,
  compatibilityDeclarations: ExecutiveDecisionCertificationCompatibility.relationships,
  regressionDeclarations: ExecutiveDecisionCertificationCompatibility.regressions,
  blockerInventory: ExecutiveDecisionCertificationBlockers,
  readiness: ExecutiveDecisionCertificationReadiness,
  finalCertificationState: "Certified",
  sectionCount: 13,
  metadataOnly: true,
  immutable: true,
  deeplyFrozen: true,
} as const);
