/** NOL-4:7 — canonical trust gate for validated Director Runtime evidence. */
import {
  assertNexoraDirectorRuntimeValidationInvariants,
  nexoraObjectDirectorRuntimeValidationIntegrityEngineIdentity,
  nexoraObjectDirectorRuntimeValidationIntegrityEngineVersion,
  nexoraObjectDirectorRuntimeValidationIntegritySchemaVersion,
  type NexoraDirectorRuntimeValidationDomain,
  type NexoraDirectorRuntimeValidationProfile,
  type NexoraDirectorRuntimeValidationReport,
} from "./nexoraObjectDirectorRuntimeValidationIntegrityEngine.ts";

export * from "./nexoraObjectDirectorRuntimeValidationIntegrityEngine.ts";

export const nexoraObjectDirectorRuntimeCertificationIdentity = "NOL-4:7/NexoraObjectDirectorRuntimeCertification" as const;
export const nexoraObjectDirectorRuntimeCertificationVersion = "1.0.0" as const;
export const nexoraObjectDirectorRuntimeCertificationSchemaVersion = "1.0.0" as const;

export type NexoraDirectorRuntimeCertificationProfile = "Development" | "Testing" | "Production" | "Platform" | "Release";
export type NexoraDirectorRuntimeCertificationStatus = "NotCertified" | "Pending" | "Certified" | "Suspended" | "Expired" | "Revoked";
export type NexoraDirectorRuntimeCertificationCompatibility = "Compatible" | "Degraded" | "Incompatible" | "Unknown";
export type NexoraDirectorRuntimeCertificationProjectionType = "Consumer" | "Platform" | "Release" | "Diagnostics";
export interface NexoraDirectorRuntimeCertificationPolicy { readonly policyId: string; readonly profile: NexoraDirectorRuntimeCertificationProfile; readonly requiredValidationProfiles: readonly NexoraDirectorRuntimeValidationProfile[]; readonly requiredReadiness: NexoraDirectorRuntimeValidationReport["releaseReadiness"]; readonly minimumIntegrityScore: number; readonly maximumWarningCount?: number; readonly requireZeroBlockingErrors: boolean; readonly requireRendererIndependence: boolean; readonly requireDeepImmutability: boolean; readonly requireDeterminism: boolean; readonly requireSerialization: boolean; readonly requireCompleteIdentityChain: boolean; readonly requireCompleteRevisionChain: boolean; readonly requireRequiredCapabilities: boolean; readonly requireHealthyOrDegradedRuntime: boolean; readonly requiredDomains: readonly NexoraDirectorRuntimeValidationDomain[]; }
export interface NexoraDirectorRuntimeCertificationContext { readonly source: "Validation" | "Platform" | "Release" | "System"; readonly correlationId?: string; readonly causationId?: string; readonly occurredAt?: string; readonly allowWarnings?: boolean; readonly requireExactEngineVersion?: boolean; readonly requireExactSchemaVersion?: boolean; }
export interface NexoraDirectorRuntimeCertificationRequest { readonly requestId: string; readonly certificationId?: string; readonly profile: NexoraDirectorRuntimeCertificationProfile; readonly validationReport: NexoraDirectorRuntimeValidationReport; readonly policy?: NexoraDirectorRuntimeCertificationPolicy; readonly certifiedBy: string; readonly reason?: string; readonly expiresAt?: string; readonly previousCertification?: NexoraDirectorRuntimeCertificationReport; readonly context?: NexoraDirectorRuntimeCertificationContext; }
export interface NexoraDirectorRuntimeCertificationStamp { readonly certificationId: string; readonly profile: NexoraDirectorRuntimeCertificationProfile; readonly status: NexoraDirectorRuntimeCertificationStatus; readonly validationReportId: string; readonly validationRequestId: string; readonly validationProfile: NexoraDirectorRuntimeValidationProfile; readonly validationReadiness: NexoraDirectorRuntimeValidationReport["releaseReadiness"]; readonly integrityScore: number; readonly certifiedBy: string; readonly certifiedAt?: string; readonly expiresAt?: string; readonly engineIdentity: string; readonly engineVersion: string; readonly schemaVersion: string; readonly compatibility: NexoraDirectorRuntimeCertificationCompatibility; readonly trustLevel: NexoraDirectorRuntimeCertificationProfile; }
export interface NexoraDirectorRuntimeCertificationHistoryEntry { readonly historyId: string; readonly certificationId: string; readonly previousStatus: NexoraDirectorRuntimeCertificationStatus; readonly nextStatus: NexoraDirectorRuntimeCertificationStatus; readonly profile: NexoraDirectorRuntimeCertificationProfile; readonly validationReportId?: string; readonly integrityScore?: number; readonly reason: string; readonly actor: string; readonly occurredAt: string; readonly correlationId?: string; readonly causationId?: string; }
export interface NexoraDirectorRuntimeCertificationRequirementResult { readonly requirementId: string; readonly name: string; readonly passed: boolean; readonly mandatory: boolean; readonly message: string; readonly details?: Readonly<Record<string, unknown>>; }
export type NexoraDirectorRuntimeCertificationWarningCode = "RUNTIME_CERT_WARNING_LIMIT_NEAR" | "RUNTIME_CERT_SCORE_NEAR_THRESHOLD" | "RUNTIME_CERT_DEGRADED_RUNTIME_ACCEPTED" | "RUNTIME_CERT_OPTIONAL_CAPABILITY_UNAVAILABLE" | "RUNTIME_CERT_NEAR_EXPIRY" | "RUNTIME_CERT_RECERTIFICATION_RECOMMENDED" | "RUNTIME_CERT_COMPATIBILITY_DEGRADED" | "RUNTIME_CERT_SUSPENDED";
export interface NexoraDirectorRuntimeCertificationWarning { readonly code: NexoraDirectorRuntimeCertificationWarningCode; readonly message: string; readonly requirementId?: string; readonly validationReportId?: string; readonly details?: Readonly<Record<string, unknown>>; }
export type NexoraDirectorRuntimeCertificationErrorCode = "RUNTIME_CERT_INVALID_REQUEST" | "RUNTIME_CERT_INVALID_PROFILE" | "RUNTIME_CERT_INVALID_POLICY" | "RUNTIME_CERT_VALIDATION_REPORT_INVALID" | "RUNTIME_CERT_VALIDATION_PROFILE_INSUFFICIENT" | "RUNTIME_CERT_RELEASE_READINESS_INSUFFICIENT" | "RUNTIME_CERT_INTEGRITY_SCORE_TOO_LOW" | "RUNTIME_CERT_BLOCKING_VALIDATION_ERROR" | "RUNTIME_CERT_REQUIRED_DOMAIN_MISSING" | "RUNTIME_CERT_RENDERER_INDEPENDENCE_FAILED" | "RUNTIME_CERT_IMMUTABILITY_FAILED" | "RUNTIME_CERT_DETERMINISM_FAILED" | "RUNTIME_CERT_SERIALIZATION_FAILED" | "RUNTIME_CERT_IDENTITY_CHAIN_FAILED" | "RUNTIME_CERT_REVISION_CHAIN_FAILED" | "RUNTIME_CERT_REQUIRED_CAPABILITY_UNAVAILABLE" | "RUNTIME_CERT_RUNTIME_HEALTH_UNACCEPTABLE" | "RUNTIME_CERT_ADAPTER_ASSIGNMENT_INVALID" | "RUNTIME_CERT_CRITICAL_REPAIR_UNRESOLVED" | "RUNTIME_CERT_COMPATIBILITY_FAILED" | "RUNTIME_CERT_INVALID_LIFECYCLE" | "RUNTIME_CERT_ALREADY_SUSPENDED" | "RUNTIME_CERT_ALREADY_EXPIRED" | "RUNTIME_CERT_ALREADY_REVOKED" | "RUNTIME_CERT_REVOKED_TERMINAL" | "RUNTIME_CERT_NEW_VALIDATION_REQUIRED" | "RUNTIME_CERT_DUPLICATE_REQUEST_ID" | "RUNTIME_CERT_DUPLICATE_CERTIFICATION_ID" | "RUNTIME_CERT_HISTORY_INVALID" | "RUNTIME_CERT_INVARIANT_VIOLATION" | "RUNTIME_CERT_UNSUPPORTED_VERSION";
export interface NexoraDirectorRuntimeCertificationError { readonly code: NexoraDirectorRuntimeCertificationErrorCode; readonly message: string; readonly requestId?: string; readonly certificationId?: string; readonly validationReportId?: string; readonly requirementId?: string; readonly details?: Readonly<Record<string, unknown>>; }
export interface NexoraDirectorRuntimeCertificationEvaluation { readonly accepted: boolean; readonly compatibility: NexoraDirectorRuntimeCertificationCompatibility; readonly requirements: readonly NexoraDirectorRuntimeCertificationRequirementResult[]; readonly warnings: readonly NexoraDirectorRuntimeCertificationWarning[]; readonly errors: readonly NexoraDirectorRuntimeCertificationError[]; }
export interface NexoraDirectorRuntimeCertificationReport { readonly reportId: string; readonly requestId: string; readonly certificationId: string; readonly accepted: boolean; readonly profile: NexoraDirectorRuntimeCertificationProfile; readonly status: NexoraDirectorRuntimeCertificationStatus; readonly stamp?: NexoraDirectorRuntimeCertificationStamp; readonly validationReport: NexoraDirectorRuntimeValidationReport; readonly policy: NexoraDirectorRuntimeCertificationPolicy; readonly passedRequirements: readonly NexoraDirectorRuntimeCertificationRequirementResult[]; readonly warnings: readonly NexoraDirectorRuntimeCertificationWarning[]; readonly errors: readonly NexoraDirectorRuntimeCertificationError[]; readonly history: readonly NexoraDirectorRuntimeCertificationHistoryEntry[]; readonly createdAt: string; }
export interface NexoraDirectorRuntimeCertificationDifference { readonly profileChanged: boolean; readonly statusChanged: boolean; readonly scoreChange: number; readonly readinessChanged: boolean; readonly validationReportChanged: boolean; readonly engineVersionChanged: boolean; readonly schemaVersionChanged: boolean; readonly compatibilityChanged: boolean; readonly historyLengthChange: number; readonly addedWarningCodes: readonly string[]; readonly removedWarningCodes: readonly string[]; readonly addedErrorCodes: readonly string[]; readonly removedErrorCodes: readonly string[]; }
export interface NexoraDirectorRuntimeCertificationBatchRequest { readonly requests: readonly NexoraDirectorRuntimeCertificationRequest[]; readonly mode: "Atomic" | "BestEffort"; }
export interface NexoraDirectorRuntimeCertificationBatchResult { readonly accepted: boolean; readonly mode: "Atomic" | "BestEffort"; readonly reports: readonly NexoraDirectorRuntimeCertificationReport[]; readonly certifiedRequestIds: readonly string[]; readonly rejectedRequestIds: readonly string[]; }
export type NexoraDirectorRuntimeCertificationEventType = "CertificationPending" | "CertificationAccepted" | "CertificationRejected" | "CertificationSuspended" | "CertificationRestored" | "CertificationExpired" | "CertificationRevoked" | "RecertificationAccepted" | "RecertificationRejected";
export interface NexoraDirectorRuntimeCertificationEvent { readonly eventId: string; readonly certificationId: string; readonly requestId?: string; readonly profile: NexoraDirectorRuntimeCertificationProfile; readonly type: NexoraDirectorRuntimeCertificationEventType; readonly occurredAt: string; readonly validationReportId?: string; readonly correlationId?: string; readonly causationId?: string; readonly payload: Readonly<Record<string, unknown>>; }
export interface NexoraDirectorRuntimeCertificationDependencies { readonly now: () => string; readonly createCertificationId: () => string; readonly createReportId: () => string; readonly createHistoryId: () => string; readonly createRequirementId: (name: string) => string; readonly createEventId: () => string; }
export interface NexoraDirectorRuntimeCertificationValidationResult { readonly valid: boolean; readonly errors: readonly NexoraDirectorRuntimeCertificationError[]; }

export class NexoraObjectDirectorRuntimeCertificationException extends Error { constructor(message: string) { super(message); this.name = "NexoraObjectDirectorRuntimeCertificationException"; } }

const PROFILES = Object.freeze(["Development", "Testing", "Production", "Platform", "Release"] as const);
const STATUSES = Object.freeze(["NotCertified", "Pending", "Certified", "Suspended", "Expired", "Revoked"] as const);
const VALIDATION_PROFILES = Object.freeze(["Minimal", "Standard", "Strict", "Certification"] as const);
const READINESS = Object.freeze(["NotReady", "DevelopmentReady", "TestingReady", "ProductionReady", "PlatformReady", "CertificationReady"] as const);
const ALL_DOMAINS = Object.freeze(["Identity", "AdapterFoundation", "CommandExecution", "RuntimeState", "StateSynchronization", "Events", "Feedback", "Acknowledgments", "Capabilities", "AdapterRegistry", "Assignments", "Routing", "FailoverMigration", "Lifecycle", "Revisions", "Health", "Diagnostics", "Snapshots", "Serialization", "Compatibility", "Immutability", "Determinism", "RendererIndependence", "PublicSurface", "Composite"] as const satisfies readonly NexoraDirectorRuntimeValidationDomain[]);
const DEFAULTS: NexoraDirectorRuntimeCertificationDependencies = Object.freeze({ now: () => "1970-01-01T00:00:00.000Z", createCertificationId: () => "runtime-certification", createReportId: () => "runtime-certification-report", createHistoryId: () => "runtime-certification-history", createRequirementId: (name: string) => `runtime-certification:${name}`, createEventId: () => "runtime-certification-event" });
const TRANSITIONS: Readonly<Record<NexoraDirectorRuntimeCertificationStatus, readonly NexoraDirectorRuntimeCertificationStatus[]>> = Object.freeze({ NotCertified: Object.freeze(["Pending"] as const), Pending: Object.freeze(["Certified", "NotCertified"] as const), Certified: Object.freeze(["Suspended", "Expired", "Revoked"] as const), Suspended: Object.freeze(["Certified", "Expired", "Revoked"] as const), Expired: Object.freeze(["Pending"] as const), Revoked: Object.freeze([] as const) });

function freeze<T>(value: T, seen = new Set<object>()): T { if (value === null || typeof value !== "object" || seen.has(value as object)) return value; seen.add(value as object); Object.values(value as Record<string, unknown>).forEach((child) => freeze(child, seen)); return Object.isFrozen(value) ? value : Object.freeze(value); }
function compact<T extends Record<string, unknown>>(value: T): T { return Object.fromEntries(Object.entries(value).filter(([, child]) => child !== undefined)) as T; }
function rec(value: unknown): value is Record<string, unknown> { return value !== null && typeof value === "object" && !Array.isArray(value); }
function deeplyFrozen(value: unknown, seen = new Set<object>()): boolean { if (value === null || typeof value !== "object" || seen.has(value as object)) return true; if (!Object.isFrozen(value)) return false; seen.add(value as object); return Object.values(value as Record<string, unknown>).every((child) => deeplyFrozen(child, seen)); }
function unsafe(value: unknown, seen = new Set<object>()): boolean { if (typeof value === "function" || value instanceof Promise) return true; if (value === null || typeof value !== "object" || seen.has(value as object)) return false; seen.add(value as object); const name = (value as { constructor?: { name?: string } }).constructor?.name; if (name && !["Object", "Array"].includes(name)) return true; return Object.entries(value as Record<string, unknown>).some(([key, child]) => /^(callback|handler|connection|plugin|instance|renderer|mesh|scene|camera|material|geometry|dom|canvas|eventBus)$/i.test(key) || unsafe(child, seen)); }
function err(code: NexoraDirectorRuntimeCertificationErrorCode, message: string, extra: Partial<NexoraDirectorRuntimeCertificationError> = {}): NexoraDirectorRuntimeCertificationError { return freeze({ code, message, ...extra }); }
function valid(errors: readonly NexoraDirectorRuntimeCertificationError[]): NexoraDirectorRuntimeCertificationValidationResult { return freeze({ valid: errors.length === 0, errors }); }
function history(certificationId: string, profile: NexoraDirectorRuntimeCertificationProfile, previousStatus: NexoraDirectorRuntimeCertificationStatus, nextStatus: NexoraDirectorRuntimeCertificationStatus, reason: string, actor: string, report: NexoraDirectorRuntimeValidationReport | undefined, context: NexoraDirectorRuntimeCertificationContext | undefined, dependencies: NexoraDirectorRuntimeCertificationDependencies): NexoraDirectorRuntimeCertificationHistoryEntry { return freeze(compact({ historyId: dependencies.createHistoryId(), certificationId, previousStatus, nextStatus, profile, validationReportId: report?.reportId, integrityScore: report?.integrityScore, reason, actor, occurredAt: context?.occurredAt ?? dependencies.now(), correlationId: context?.correlationId, causationId: context?.causationId })); }
function requirement(name: string, passed: boolean, mandatory: boolean, message: string, dependencies: NexoraDirectorRuntimeCertificationDependencies, details?: Readonly<Record<string, unknown>>): NexoraDirectorRuntimeCertificationRequirementResult { return freeze(compact({ requirementId: dependencies.createRequirementId(name), name, passed, mandatory, message, details })); }
function domainPassed(report: NexoraDirectorRuntimeValidationReport, target: NexoraDirectorRuntimeValidationDomain): boolean { return report.result.checkedDomains.includes(target) && !report.result.errors.some((item) => item.domain === target) && report.result.passedChecks.filter((item) => item.domain === target).every((item) => item.passed); }
function readinessAtLeast(actual: NexoraDirectorRuntimeValidationReport["releaseReadiness"], required: NexoraDirectorRuntimeValidationReport["releaseReadiness"]): boolean { return READINESS.indexOf(actual) >= READINESS.indexOf(required); }
function unique(values: readonly string[]): readonly string[] { return freeze([...new Set(values)].sort()); }
function transitionAllowed(previous: NexoraDirectorRuntimeCertificationStatus, next: NexoraDirectorRuntimeCertificationStatus): boolean { return TRANSITIONS[previous].includes(next); }

export function createDefaultNexoraDirectorRuntimeCertificationPolicy(profile: NexoraDirectorRuntimeCertificationProfile): NexoraDirectorRuntimeCertificationPolicy {
  const settings: Record<NexoraDirectorRuntimeCertificationProfile, { score: number; readiness: NexoraDirectorRuntimeValidationReport["releaseReadiness"]; validations: readonly NexoraDirectorRuntimeValidationProfile[]; domains: readonly NexoraDirectorRuntimeValidationDomain[] }> = {
    Development: { score: 60, readiness: "DevelopmentReady", validations: VALIDATION_PROFILES, domains: ["Identity", "RendererIndependence"] },
    Testing: { score: 75, readiness: "TestingReady", validations: ["Standard", "Strict", "Certification"], domains: ["CommandExecution", "RuntimeState", "Feedback", "AdapterRegistry", "Serialization", "Determinism"] },
    Production: { score: 85, readiness: "ProductionReady", validations: ["Strict", "Certification"], domains: ["CommandExecution", "RuntimeState", "StateSynchronization", "Feedback", "Capabilities", "Assignments", "Health"] },
    Platform: { score: 90, readiness: "PlatformReady", validations: ["Certification"], domains: ["Identity", "Lifecycle", "Revisions", "Health", "Assignments", "Immutability", "Determinism", "RendererIndependence", "PublicSurface"] },
    Release: { score: 95, readiness: "CertificationReady", validations: ["Certification"], domains: ALL_DOMAINS },
  };
  const selected = settings[profile];
  return freeze(compact({ policyId: `NOL-4:7/default/${profile}`, profile, requiredValidationProfiles: selected.validations, requiredReadiness: selected.readiness, minimumIntegrityScore: selected.score, maximumWarningCount: profile === "Release" ? 0 : undefined, requireZeroBlockingErrors: profile !== "Development", requireRendererIndependence: true, requireDeepImmutability: ["Platform", "Release"].includes(profile), requireDeterminism: ["Testing", "Platform", "Release"].includes(profile), requireSerialization: ["Testing", "Release"].includes(profile), requireCompleteIdentityChain: ["Platform", "Release"].includes(profile), requireCompleteRevisionChain: ["Platform", "Release"].includes(profile), requireRequiredCapabilities: ["Production", "Platform", "Release"].includes(profile), requireHealthyOrDegradedRuntime: ["Production", "Platform", "Release"].includes(profile), requiredDomains: selected.domains }));
}

export function evaluateNexoraDirectorRuntimeCertificationCompatibility(report: NexoraDirectorRuntimeValidationReport, context: NexoraDirectorRuntimeCertificationContext = { source: "Validation" }): NexoraDirectorRuntimeCertificationCompatibility { if (report.result.validatorIdentity !== nexoraObjectDirectorRuntimeValidationIntegrityEngineIdentity || report.result.errors.some((item) => ["RUNTIME_VALIDATION_UNSUPPORTED_VERSION", "RUNTIME_VALIDATION_PUBLIC_SURFACE_INVALID"].includes(item.code))) return "Incompatible"; if (report.result.errors.some((item) => item.code === "RUNTIME_VALIDATION_VERSION_MISMATCH") || report.result.warnings.some((item) => item.code === "RUNTIME_VALIDATION_DEGRADED_ADAPTER_ACTIVE")) return "Degraded"; if ((context.requireExactEngineVersion && nexoraObjectDirectorRuntimeValidationIntegrityEngineVersion !== "1.0.0") || (context.requireExactSchemaVersion && nexoraObjectDirectorRuntimeValidationIntegritySchemaVersion !== "1.0.0")) return "Incompatible"; return report.reportId ? "Compatible" : "Unknown"; }

export function validateNexoraDirectorRuntimeCertificationPolicy(policy: unknown): NexoraDirectorRuntimeCertificationValidationResult { const errors: NexoraDirectorRuntimeCertificationError[] = []; if (!rec(policy) || typeof policy.policyId !== "string" || !policy.policyId || !PROFILES.includes(policy.profile as NexoraDirectorRuntimeCertificationProfile)) return valid([err("RUNTIME_CERT_INVALID_POLICY", "Certification policy identity or profile is invalid")]); if (typeof policy.minimumIntegrityScore !== "number" || policy.minimumIntegrityScore < 0 || policy.minimumIntegrityScore > 100) errors.push(err("RUNTIME_CERT_INVALID_POLICY", "Integrity threshold must be between zero and one hundred")); if (!Array.isArray(policy.requiredValidationProfiles) || !policy.requiredValidationProfiles.length || policy.requiredValidationProfiles.some((item) => !VALIDATION_PROFILES.includes(item))) errors.push(err("RUNTIME_CERT_INVALID_POLICY", "Required validation profiles are invalid")); if (!READINESS.includes(policy.requiredReadiness as typeof READINESS[number])) errors.push(err("RUNTIME_CERT_INVALID_POLICY", "Required readiness is invalid")); if (!Array.isArray(policy.requiredDomains) || !policy.requiredDomains.length || policy.requiredDomains.some((item) => !ALL_DOMAINS.includes(item))) errors.push(err("RUNTIME_CERT_INVALID_POLICY", "Required validation domains are invalid")); if (!deeplyFrozen(policy)) errors.push(err("RUNTIME_CERT_INVALID_POLICY", "Certification policy must be deeply immutable")); return valid(errors); }
export function validateNexoraDirectorRuntimeCertificationRequest(request: unknown): NexoraDirectorRuntimeCertificationValidationResult { const errors: NexoraDirectorRuntimeCertificationError[] = []; if (!rec(request) || typeof request.requestId !== "string" || !request.requestId || !PROFILES.includes(request.profile as NexoraDirectorRuntimeCertificationProfile) || typeof request.certifiedBy !== "string" || !request.certifiedBy || !rec(request.validationReport)) return valid([err("RUNTIME_CERT_INVALID_REQUEST", "Certification request is invalid")]); try { assertNexoraDirectorRuntimeValidationInvariants(request.validationReport as unknown as NexoraDirectorRuntimeValidationReport); } catch { errors.push(err("RUNTIME_CERT_VALIDATION_REPORT_INVALID", "Validation report invariants failed", { requestId: request.requestId })); } if (request.policy && (validateNexoraDirectorRuntimeCertificationPolicy(request.policy).errors.length || !rec(request.policy) || request.policy.profile !== request.profile)) errors.push(err("RUNTIME_CERT_INVALID_POLICY", "Explicit certification policy is invalid or targets a different profile", { requestId: request.requestId })); if (request.expiresAt !== undefined && (typeof request.expiresAt !== "string" || Number.isNaN(Date.parse(request.expiresAt)))) errors.push(err("RUNTIME_CERT_INVALID_REQUEST", "Certification expiration must be an ISO timestamp", { requestId: request.requestId })); return valid(errors); }

export function evaluateNexoraDirectorRuntimeCertificationPolicy(report: NexoraDirectorRuntimeValidationReport, policy: NexoraDirectorRuntimeCertificationPolicy, context: NexoraDirectorRuntimeCertificationContext = { source: "Validation" }, dependencies: NexoraDirectorRuntimeCertificationDependencies = DEFAULTS): NexoraDirectorRuntimeCertificationEvaluation {
  const compatibility = evaluateNexoraDirectorRuntimeCertificationCompatibility(report, context), blocking = report.result.errors.length === 0, domains = policy.requiredDomains.every((item) => report.result.checkedDomains.includes(item));
  const renderer = domainPassed(report, "RendererIndependence"), immutable = domainPassed(report, "Immutability"), deterministic = domainPassed(report, "Determinism"), serialization = domainPassed(report, "Serialization"), identity = domainPassed(report, "Identity"), revision = domainPassed(report, "Revisions"), capabilities = domainPassed(report, "Capabilities"), health = domainPassed(report, "Health"), assignments = domainPassed(report, "Assignments"), failover = domainPassed(report, "FailoverMigration");
  const criticalRepair = report.result.repairSuggestions.some((item) => item.priority >= 90), warningsAllowed = context.allowWarnings !== false || report.result.warnings.length === 0;
  const definitions: readonly [string, boolean, boolean, NexoraDirectorRuntimeCertificationErrorCode][] = [
    ["ValidationReportIdentity", report.result.validatorIdentity === nexoraObjectDirectorRuntimeValidationIntegrityEngineIdentity && report.valid, true, "RUNTIME_CERT_VALIDATION_REPORT_INVALID"],
    ["ValidationProfile", policy.requiredValidationProfiles.includes(report.profile), true, "RUNTIME_CERT_VALIDATION_PROFILE_INSUFFICIENT"],
    ["ReleaseReadiness", readinessAtLeast(report.releaseReadiness, policy.requiredReadiness), true, "RUNTIME_CERT_RELEASE_READINESS_INSUFFICIENT"],
    ["IntegrityScore", report.integrityScore >= policy.minimumIntegrityScore, true, "RUNTIME_CERT_INTEGRITY_SCORE_TOO_LOW"],
    ["BlockingErrors", !policy.requireZeroBlockingErrors || blocking, policy.requireZeroBlockingErrors, "RUNTIME_CERT_BLOCKING_VALIDATION_ERROR"],
    ["WarningLimit", (policy.maximumWarningCount === undefined || report.result.warnings.length <= policy.maximumWarningCount) && warningsAllowed, policy.maximumWarningCount !== undefined || !warningsAllowed, "RUNTIME_CERT_BLOCKING_VALIDATION_ERROR"],
    ["RequiredDomains", domains, true, "RUNTIME_CERT_REQUIRED_DOMAIN_MISSING"],
    ["RendererIndependence", !policy.requireRendererIndependence || renderer, policy.requireRendererIndependence, "RUNTIME_CERT_RENDERER_INDEPENDENCE_FAILED"],
    ["DeepImmutability", !policy.requireDeepImmutability || immutable, policy.requireDeepImmutability, "RUNTIME_CERT_IMMUTABILITY_FAILED"],
    ["Determinism", !policy.requireDeterminism || deterministic, policy.requireDeterminism, "RUNTIME_CERT_DETERMINISM_FAILED"],
    ["Serialization", !policy.requireSerialization || serialization, policy.requireSerialization, "RUNTIME_CERT_SERIALIZATION_FAILED"],
    ["IdentityChain", !policy.requireCompleteIdentityChain || identity, policy.requireCompleteIdentityChain, "RUNTIME_CERT_IDENTITY_CHAIN_FAILED"],
    ["RevisionChain", !policy.requireCompleteRevisionChain || revision, policy.requireCompleteRevisionChain, "RUNTIME_CERT_REVISION_CHAIN_FAILED"],
    ["RequiredCapabilities", !policy.requireRequiredCapabilities || capabilities, policy.requireRequiredCapabilities, "RUNTIME_CERT_REQUIRED_CAPABILITY_UNAVAILABLE"],
    ["RuntimeHealth", !policy.requireHealthyOrDegradedRuntime || health, policy.requireHealthyOrDegradedRuntime, "RUNTIME_CERT_RUNTIME_HEALTH_UNACCEPTABLE"],
    ["AdapterAssignments", !["Production", "Platform", "Release"].includes(policy.profile) || assignments, ["Production", "Platform", "Release"].includes(policy.profile), "RUNTIME_CERT_ADAPTER_ASSIGNMENT_INVALID"],
    ["RecommendationOnlyFailover", policy.profile === "Development" || failover, policy.profile !== "Development", "RUNTIME_CERT_BLOCKING_VALIDATION_ERROR"],
    ["Compatibility", compatibility === "Compatible" || (policy.profile !== "Release" && compatibility === "Degraded"), true, "RUNTIME_CERT_COMPATIBILITY_FAILED"],
    ["CriticalRepairs", policy.profile !== "Release" || !criticalRepair, policy.profile === "Release", "RUNTIME_CERT_CRITICAL_REPAIR_UNRESOLVED"],
    ["ProfileTrust", report.valid && (policy.profile !== "Release" || report.releaseReadiness === "CertificationReady"), true, "RUNTIME_CERT_RELEASE_READINESS_INSUFFICIENT"],
  ];
  const requirements = definitions.map(([name, passed, mandatory]) => requirement(name, passed, mandatory, passed ? `${name} evidence accepted` : `${name} evidence rejected`, dependencies));
  const errors = definitions.flatMap(([name, passed, mandatory, code], index) => !passed && mandatory ? [err(code, `${name} requirement failed`, { requirementId: requirements[index]?.requirementId, validationReportId: report.reportId })] : []);
  const warnings: NexoraDirectorRuntimeCertificationWarning[] = [];
  if (report.integrityScore >= policy.minimumIntegrityScore && report.integrityScore < policy.minimumIntegrityScore + 3) warnings.push(freeze({ code: "RUNTIME_CERT_SCORE_NEAR_THRESHOLD", message: "Integrity score is near the certification threshold", validationReportId: report.reportId }));
  if (compatibility === "Degraded") warnings.push(freeze({ code: "RUNTIME_CERT_COMPATIBILITY_DEGRADED", message: "Degraded compatibility evidence was accepted", validationReportId: report.reportId }));
  return freeze({ accepted: errors.length === 0, compatibility, requirements, warnings, errors });
}

function policyFor(request: NexoraDirectorRuntimeCertificationRequest): NexoraDirectorRuntimeCertificationPolicy { return request.policy ?? createDefaultNexoraDirectorRuntimeCertificationPolicy(request.profile); }
function stampFor(request: NexoraDirectorRuntimeCertificationRequest, certificationId: string, compatibility: NexoraDirectorRuntimeCertificationCompatibility, status: NexoraDirectorRuntimeCertificationStatus, dependencies: NexoraDirectorRuntimeCertificationDependencies): NexoraDirectorRuntimeCertificationStamp { return freeze(compact({ certificationId, profile: request.profile, status, validationReportId: request.validationReport.reportId, validationRequestId: request.validationReport.requestId, validationProfile: request.validationReport.profile, validationReadiness: request.validationReport.releaseReadiness, integrityScore: request.validationReport.integrityScore, certifiedBy: request.certifiedBy, certifiedAt: dependencies.now(), expiresAt: request.expiresAt, engineIdentity: nexoraObjectDirectorRuntimeValidationIntegrityEngineIdentity, engineVersion: nexoraObjectDirectorRuntimeValidationIntegrityEngineVersion, schemaVersion: nexoraObjectDirectorRuntimeValidationIntegritySchemaVersion, compatibility, trustLevel: request.profile })); }

export function createPendingNexoraDirectorRuntimeCertification(request: NexoraDirectorRuntimeCertificationRequest, dependencies: NexoraDirectorRuntimeCertificationDependencies = DEFAULTS): NexoraDirectorRuntimeCertificationReport { const policy = policyFor(request), certificationId = request.certificationId ?? dependencies.createCertificationId(), requestValidation = validateNexoraDirectorRuntimeCertificationRequest(request), policyValidation = validateNexoraDirectorRuntimeCertificationPolicy(policy), errors = freeze([...requestValidation.errors, ...policyValidation.errors]); const pending = history(certificationId, request.profile, "NotCertified", errors.length ? "NotCertified" : "Pending", request.reason ?? "Certification requested", request.certifiedBy, request.validationReport, request.context, dependencies); return freeze({ reportId: dependencies.createReportId(), requestId: request.requestId, certificationId, accepted: false, profile: request.profile, status: errors.length ? "NotCertified" : "Pending", validationReport: request.validationReport, policy, passedRequirements: [], warnings: [], errors, history: [pending], createdAt: dependencies.now() }); }

export function certifyNexoraDirectorRuntime(request: NexoraDirectorRuntimeCertificationRequest, dependencies: NexoraDirectorRuntimeCertificationDependencies = DEFAULTS): NexoraDirectorRuntimeCertificationReport { const pending = createPendingNexoraDirectorRuntimeCertification(request, dependencies); if (pending.errors.length) return pending; const evaluation = evaluateNexoraDirectorRuntimeCertificationPolicy(request.validationReport, pending.policy, request.context, dependencies), status = evaluation.accepted ? "Certified" : "NotCertified", finalHistory = history(pending.certificationId, request.profile, "Pending", status, request.reason ?? (evaluation.accepted ? "Certification accepted" : "Certification rejected"), request.certifiedBy, request.validationReport, request.context, dependencies); const report: NexoraDirectorRuntimeCertificationReport = freeze({ ...pending, accepted: evaluation.accepted, status, ...(evaluation.accepted ? { stamp: stampFor(request, pending.certificationId, evaluation.compatibility, "Certified", dependencies) } : {}), passedRequirements: evaluation.requirements, warnings: evaluation.warnings, errors: evaluation.errors, history: [...pending.history, finalHistory] }); assertNexoraDirectorRuntimeCertificationInvariants(report); return report; }

function lifecycleFailure(report: NexoraDirectorRuntimeCertificationReport, code: NexoraDirectorRuntimeCertificationErrorCode, message: string): NexoraDirectorRuntimeCertificationReport { return freeze({ ...report, errors: [...report.errors, err(code, message, { certificationId: report.certificationId })] }); }
function lifecycleReport(report: NexoraDirectorRuntimeCertificationReport, nextStatus: NexoraDirectorRuntimeCertificationStatus, reason: string, actor: string, dependencies: NexoraDirectorRuntimeCertificationDependencies): NexoraDirectorRuntimeCertificationReport { if (!transitionAllowed(report.status, nextStatus)) return lifecycleFailure(report, report.status === "Revoked" ? "RUNTIME_CERT_REVOKED_TERMINAL" : "RUNTIME_CERT_INVALID_LIFECYCLE", `${report.status} cannot transition to ${nextStatus}`); const nextHistory = history(report.certificationId, report.profile, report.status, nextStatus, reason, actor, report.validationReport, undefined, dependencies); return freeze({ ...report, reportId: dependencies.createReportId(), accepted: nextStatus === "Certified", status: nextStatus, ...(report.stamp ? { stamp: freeze({ ...report.stamp, status: nextStatus }) } : {}), history: [...report.history, nextHistory], createdAt: dependencies.now() }); }

export function recertifyNexoraDirectorRuntime(previous: NexoraDirectorRuntimeCertificationReport, request: NexoraDirectorRuntimeCertificationRequest, dependencies: NexoraDirectorRuntimeCertificationDependencies = DEFAULTS): NexoraDirectorRuntimeCertificationReport { if (previous.status === "Revoked") return lifecycleFailure(previous, "RUNTIME_CERT_REVOKED_TERMINAL", "Revoked certification cannot be recertified"); if (previous.validationReport.reportId === request.validationReport.reportId) return lifecycleFailure(previous, "RUNTIME_CERT_NEW_VALIDATION_REQUIRED", "Recertification requires a new validation report"); if (!["Expired", "Suspended"].includes(previous.status)) return lifecycleFailure(previous, "RUNTIME_CERT_INVALID_LIFECYCLE", "Only Expired or Suspended certification may be recertified in place"); const evaluated = certifyNexoraDirectorRuntime(freeze({ ...request, certificationId: previous.certificationId, previousCertification: previous }), dependencies); if (!evaluated.accepted) return freeze({ ...evaluated, history: [...previous.history, ...evaluated.history] }); const firstPrevious: NexoraDirectorRuntimeCertificationStatus = previous.status === "Expired" ? "Expired" : "Suspended"; const entries = previous.status === "Expired" ? [history(previous.certificationId, request.profile, firstPrevious, "Pending", "Recertification pending", request.certifiedBy, request.validationReport, request.context, dependencies), history(previous.certificationId, request.profile, "Pending", "Certified", "Recertification accepted", request.certifiedBy, request.validationReport, request.context, dependencies)] : [history(previous.certificationId, request.profile, "Suspended", "Certified", "Recertification accepted", request.certifiedBy, request.validationReport, request.context, dependencies)]; return freeze({ ...evaluated, history: [...previous.history, ...entries] }); }
export function suspendNexoraDirectorRuntimeCertification(report: NexoraDirectorRuntimeCertificationReport, reason: string, actor: string, dependencies: NexoraDirectorRuntimeCertificationDependencies = DEFAULTS): NexoraDirectorRuntimeCertificationReport { if (report.status === "Suspended") return lifecycleFailure(report, "RUNTIME_CERT_ALREADY_SUSPENDED", "Certification is already suspended"); return lifecycleReport(report, "Suspended", reason, actor, dependencies); }
export function restoreNexoraDirectorRuntimeCertification(previous: NexoraDirectorRuntimeCertificationReport, request: NexoraDirectorRuntimeCertificationRequest, dependencies: NexoraDirectorRuntimeCertificationDependencies = DEFAULTS): NexoraDirectorRuntimeCertificationReport { if (previous.status !== "Suspended") return lifecycleFailure(previous, previous.status === "Revoked" ? "RUNTIME_CERT_REVOKED_TERMINAL" : "RUNTIME_CERT_INVALID_LIFECYCLE", "Only Suspended certification may be restored"); return recertifyNexoraDirectorRuntime(previous, request, dependencies); }
export function expireNexoraDirectorRuntimeCertification(report: NexoraDirectorRuntimeCertificationReport, reason: string, actor: string, dependencies: NexoraDirectorRuntimeCertificationDependencies = DEFAULTS): NexoraDirectorRuntimeCertificationReport { if (report.status === "Expired") return lifecycleFailure(report, "RUNTIME_CERT_ALREADY_EXPIRED", "Certification is already expired"); return lifecycleReport(report, "Expired", reason, actor, dependencies); }
export function isNexoraDirectorRuntimeCertificationExpired(report: NexoraDirectorRuntimeCertificationReport, now: string): boolean { return report.status === "Expired" || Boolean(report.stamp?.expiresAt && Date.parse(report.stamp.expiresAt) <= Date.parse(now)); }
export function revokeNexoraDirectorRuntimeCertification(report: NexoraDirectorRuntimeCertificationReport, reason: string, actor: string, dependencies: NexoraDirectorRuntimeCertificationDependencies = DEFAULTS): NexoraDirectorRuntimeCertificationReport { if (report.status === "Revoked") return lifecycleFailure(report, "RUNTIME_CERT_ALREADY_REVOKED", "Certification is already revoked"); return lifecycleReport(report, "Revoked", reason, actor, dependencies); }

export function compareNexoraDirectorRuntimeCertifications(previous: NexoraDirectorRuntimeCertificationReport, next: NexoraDirectorRuntimeCertificationReport): NexoraDirectorRuntimeCertificationDifference { const difference = (left: readonly string[], right: readonly string[]) => ({ added: unique(right.filter((item) => !left.includes(item))), removed: unique(left.filter((item) => !right.includes(item))) }), warnings = difference(previous.warnings.map((item) => item.code), next.warnings.map((item) => item.code)), errors = difference(previous.errors.map((item) => item.code), next.errors.map((item) => item.code)); return freeze({ profileChanged: previous.profile !== next.profile, statusChanged: previous.status !== next.status, scoreChange: next.validationReport.integrityScore - previous.validationReport.integrityScore, readinessChanged: previous.validationReport.releaseReadiness !== next.validationReport.releaseReadiness, validationReportChanged: previous.validationReport.reportId !== next.validationReport.reportId, engineVersionChanged: previous.stamp?.engineVersion !== next.stamp?.engineVersion, schemaVersionChanged: previous.stamp?.schemaVersion !== next.stamp?.schemaVersion, compatibilityChanged: previous.stamp?.compatibility !== next.stamp?.compatibility, historyLengthChange: next.history.length - previous.history.length, addedWarningCodes: warnings.added, removedWarningCodes: warnings.removed, addedErrorCodes: errors.added, removedErrorCodes: errors.removed }); }
export function projectNexoraDirectorRuntimeCertification(report: NexoraDirectorRuntimeCertificationReport, type: NexoraDirectorRuntimeCertificationProjectionType): Readonly<Record<string, unknown>> | undefined { const consumer = { certificationId: report.certificationId, profile: report.profile, status: report.status, trustLevel: report.stamp?.trustLevel, score: report.validationReport.integrityScore, readiness: report.validationReport.releaseReadiness, expiresAt: report.stamp?.expiresAt, compatibility: report.stamp?.compatibility ?? "Unknown" }; if (type === "Consumer") return freeze(consumer); if (type === "Platform") return freeze({ ...consumer, requiredDomains: report.policy.requiredDomains, engineVersion: report.stamp?.engineVersion, schemaVersion: report.stamp?.schemaVersion, policyId: report.policy.policyId, validationReportId: report.validationReport.reportId, createdAt: report.createdAt, historyLength: report.history.length }); if (type === "Release") return report.accepted && report.status === "Certified" && report.profile === "Release" && report.validationReport.releaseReadiness === "CertificationReady" && report.stamp?.compatibility === "Compatible" ? freeze({ released: true, profile: "Release", readiness: "CertificationReady", compatibility: "Compatible", stamp: report.stamp, certificationId: report.certificationId }) : undefined; return freeze({ warnings: report.warnings, errors: report.errors, requirements: report.passedRequirements, history: report.history, policy: report.policy }); }

export function certifyNexoraDirectorRuntimeBatch(batch: NexoraDirectorRuntimeCertificationBatchRequest, dependencies: NexoraDirectorRuntimeCertificationDependencies = DEFAULTS): NexoraDirectorRuntimeCertificationBatchResult { const requestIds = batch.requests.map((item) => item.requestId), certificationIds = batch.requests.flatMap((item) => item.certificationId ? [item.certificationId] : []), duplicateRequests = requestIds.filter((item, index) => requestIds.indexOf(item) !== index), duplicateCertifications = certificationIds.filter((item, index) => certificationIds.indexOf(item) !== index); if (duplicateRequests.length || duplicateCertifications.length) return freeze({ accepted: false, mode: batch.mode, reports: [], certifiedRequestIds: [], rejectedRequestIds: unique(duplicateRequests.length ? duplicateRequests : batch.requests.filter((item) => item.certificationId && duplicateCertifications.includes(item.certificationId)).map((item) => item.requestId)) }); const reports = batch.requests.map((item) => certifyNexoraDirectorRuntime(item, dependencies)), rejectedRequestIds = reports.filter((item) => !item.accepted).map((item) => item.requestId), atomicRejected = batch.mode === "Atomic" && rejectedRequestIds.length > 0; return freeze({ accepted: rejectedRequestIds.length === 0, mode: batch.mode, reports, certifiedRequestIds: atomicRejected ? [] : reports.filter((item) => item.accepted).map((item) => item.requestId), rejectedRequestIds }); }
export function createNexoraDirectorRuntimeCertificationEvent(report: NexoraDirectorRuntimeCertificationReport, type: NexoraDirectorRuntimeCertificationEventType, context: NexoraDirectorRuntimeCertificationContext, dependencies: NexoraDirectorRuntimeCertificationDependencies = DEFAULTS): NexoraDirectorRuntimeCertificationEvent { return freeze({ eventId: dependencies.createEventId(), certificationId: report.certificationId, requestId: report.requestId, profile: report.profile, type, occurredAt: context.occurredAt ?? dependencies.now(), validationReportId: report.validationReport.reportId, correlationId: context.correlationId, causationId: context.causationId, payload: freeze({ status: report.status, accepted: report.accepted }) }); }

export function validateNexoraDirectorRuntimeCertificationStamp(stamp: unknown, report?: NexoraDirectorRuntimeValidationReport): NexoraDirectorRuntimeCertificationValidationResult { const errors: NexoraDirectorRuntimeCertificationError[] = []; if (!rec(stamp) || typeof stamp.certificationId !== "string" || !stamp.certificationId || !PROFILES.includes(stamp.profile as NexoraDirectorRuntimeCertificationProfile) || !STATUSES.includes(stamp.status as NexoraDirectorRuntimeCertificationStatus)) return valid([err("RUNTIME_CERT_INVARIANT_VIOLATION", "Certification stamp is invalid")]); if (stamp.status === "Certified" && typeof stamp.certifiedAt !== "string") errors.push(err("RUNTIME_CERT_INVARIANT_VIOLATION", "Certified stamp requires certifiedAt")); if (stamp.engineIdentity !== nexoraObjectDirectorRuntimeValidationIntegrityEngineIdentity || stamp.engineVersion !== nexoraObjectDirectorRuntimeValidationIntegrityEngineVersion || stamp.schemaVersion !== nexoraObjectDirectorRuntimeValidationIntegritySchemaVersion || !["Compatible", "Degraded", "Incompatible", "Unknown"].includes(String(stamp.compatibility)) || stamp.trustLevel !== stamp.profile) errors.push(err("RUNTIME_CERT_COMPATIBILITY_FAILED", "Certification stamp compatibility evidence is invalid")); if (report && (stamp.validationReportId !== report.reportId || stamp.validationRequestId !== report.requestId || stamp.validationProfile !== report.profile || stamp.integrityScore !== report.integrityScore || stamp.validationReadiness !== report.releaseReadiness)) errors.push(err("RUNTIME_CERT_VALIDATION_REPORT_INVALID", "Stamp does not match validation report evidence")); if (stamp.profile === "Release" && (stamp.validationReadiness !== "CertificationReady" || stamp.compatibility !== "Compatible")) errors.push(err("RUNTIME_CERT_RELEASE_READINESS_INSUFFICIENT", "Release stamp evidence is insufficient")); if (!deeplyFrozen(stamp) || unsafe(stamp)) errors.push(err("RUNTIME_CERT_INVARIANT_VIOLATION", "Certification stamp must be safe and deeply immutable")); return valid(errors); }
export function validateNexoraDirectorRuntimeCertificationHistory(entries: readonly NexoraDirectorRuntimeCertificationHistoryEntry[]): NexoraDirectorRuntimeCertificationValidationResult { const errors: NexoraDirectorRuntimeCertificationError[] = []; if (!deeplyFrozen(entries)) errors.push(err("RUNTIME_CERT_HISTORY_INVALID", "Certification history must be deeply immutable")); entries.forEach((entry, index) => { if (!entry.historyId || !entry.certificationId || !entry.reason || !entry.actor || !transitionAllowed(entry.previousStatus, entry.nextStatus)) errors.push(err("RUNTIME_CERT_HISTORY_INVALID", "Certification history contains an invalid transition")); if (index > 0 && entries[index - 1]!.occurredAt > entry.occurredAt) errors.push(err("RUNTIME_CERT_HISTORY_INVALID", "Certification history must be chronological")); }); return valid(errors); }
export function validateNexoraDirectorRuntimeCertificationReport(report: unknown): NexoraDirectorRuntimeCertificationValidationResult { const errors: NexoraDirectorRuntimeCertificationError[] = []; if (!rec(report) || typeof report.reportId !== "string" || !report.reportId || typeof report.requestId !== "string" || !report.requestId || typeof report.certificationId !== "string" || !report.certificationId || !Array.isArray(report.history) || !PROFILES.includes(report.profile as NexoraDirectorRuntimeCertificationProfile) || !STATUSES.includes(report.status as NexoraDirectorRuntimeCertificationStatus)) return valid([err("RUNTIME_CERT_INVARIANT_VIOLATION", "Certification report is invalid")]); const typed = report as unknown as NexoraDirectorRuntimeCertificationReport; try { assertNexoraDirectorRuntimeValidationInvariants(typed.validationReport); } catch { errors.push(err("RUNTIME_CERT_VALIDATION_REPORT_INVALID", "Embedded validation report invariants failed")); } if (!validateNexoraDirectorRuntimeCertificationPolicy(typed.policy).valid || typed.policy.profile !== typed.profile) errors.push(err("RUNTIME_CERT_INVALID_POLICY", "Certification report policy is invalid")); if (typed.status === "Certified" && (!typed.accepted || !typed.stamp)) errors.push(err("RUNTIME_CERT_INVARIANT_VIOLATION", "Certified report requires accepted evaluation and stamp")); if (!typed.accepted && typed.stamp?.status === "Certified") errors.push(err("RUNTIME_CERT_INVARIANT_VIOLATION", "Rejected report cannot contain an active Certified stamp")); if (typed.stamp) { errors.push(...validateNexoraDirectorRuntimeCertificationStamp(typed.stamp, typed.validationReport).errors); if (typed.stamp.status !== typed.status || typed.stamp.certificationId !== typed.certificationId || typed.stamp.profile !== typed.profile) errors.push(err("RUNTIME_CERT_INVARIANT_VIOLATION", "Stamp and report lifecycle evidence differ")); } errors.push(...validateNexoraDirectorRuntimeCertificationHistory(typed.history).errors); if (typed.history.at(-1)?.nextStatus !== typed.status) errors.push(err("RUNTIME_CERT_HISTORY_INVALID", "History does not resolve to the report status")); if (!deeplyFrozen(typed) || unsafe(typed)) errors.push(err("RUNTIME_CERT_INVARIANT_VIOLATION", "Certification report must be safe and deeply immutable")); return valid(errors); }
export function assertNexoraDirectorRuntimeCertificationInvariants(report: NexoraDirectorRuntimeCertificationReport): void { if (!validateNexoraDirectorRuntimeCertificationReport(report).valid) throw new NexoraObjectDirectorRuntimeCertificationException("Director Runtime certification invariants failed"); }

type SerializedKind = "Stamp" | "Report";
function serialize(kind: SerializedKind, payload: unknown): string { if (!deeplyFrozen(payload) || unsafe(payload)) throw new NexoraObjectDirectorRuntimeCertificationException("Unsafe certification artifact"); return JSON.stringify({ identity: nexoraObjectDirectorRuntimeCertificationIdentity, schemaVersion: nexoraObjectDirectorRuntimeCertificationSchemaVersion, kind, payload }); }
function deserialize<T>(json: string, kind: SerializedKind): T { const envelope: unknown = JSON.parse(json); if (!rec(envelope) || envelope.identity !== nexoraObjectDirectorRuntimeCertificationIdentity || envelope.schemaVersion !== nexoraObjectDirectorRuntimeCertificationSchemaVersion || envelope.kind !== kind || unsafe(envelope.payload)) throw new NexoraObjectDirectorRuntimeCertificationException("Unsupported certification schema"); return freeze(envelope.payload as T); }
export const serializeNexoraDirectorRuntimeCertificationStamp = (stamp: NexoraDirectorRuntimeCertificationStamp): string => serialize("Stamp", stamp);
export const deserializeNexoraDirectorRuntimeCertificationStamp = (json: string): NexoraDirectorRuntimeCertificationStamp => { const stamp = deserialize<NexoraDirectorRuntimeCertificationStamp>(json, "Stamp"); if (!validateNexoraDirectorRuntimeCertificationStamp(stamp).valid) throw new NexoraObjectDirectorRuntimeCertificationException("Invalid serialized certification stamp"); return stamp; };
export const serializeNexoraDirectorRuntimeCertificationReport = (report: NexoraDirectorRuntimeCertificationReport): string => serialize("Report", report);
export const deserializeNexoraDirectorRuntimeCertificationReport = (json: string): NexoraDirectorRuntimeCertificationReport => { const report = deserialize<NexoraDirectorRuntimeCertificationReport>(json, "Report"); if (!validateNexoraDirectorRuntimeCertificationReport(report).valid) throw new NexoraObjectDirectorRuntimeCertificationException("Invalid serialized certification report"); return report; };
