import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { describe, it } from "node:test";
import {
  assertNexoraDirectorRuntimeFreezeInvariants,
  certifyNexoraDirectorRuntime,
  compareNexoraDirectorRuntimeFreezes,
  createNexoraDirectorRuntimeFreeze,
  createPendingNexoraDirectorRuntimeCertification,
  deserializeNexoraDirectorRuntimeFreezeArtifact,
  deserializeNexoraDirectorRuntimeFreezeManifest,
  evaluateNexoraDirectorRuntimeFreezeCompatibility,
  expireNexoraDirectorRuntimeCertification,
  getNexoraDirectorRuntimeConsumerMetadata,
  getNexoraDirectorRuntimeFreezeManifest,
  getNexoraDirectorRuntimePublicApiRegistry,
  getNexoraDirectorRuntimePublicIdentityRegistry,
  getNexoraDirectorRuntimePublicTypeRegistry,
  getNexoraDirectorRuntimeReleaseInformation,
  nexoraDirectorRuntimeConsumerMetadata,
  nexoraDirectorRuntimeFreezeCompatibility,
  nexoraDirectorRuntimeFreezeStatus,
  nexoraDirectorRuntimeReleaseInformation,
  nexoraObjectDirectorRuntimeFreezeIdentity,
  projectNexoraDirectorRuntimeFreeze,
  revokeNexoraDirectorRuntimeCertification,
  serializeNexoraDirectorRuntimeFreezeArtifact,
  serializeNexoraDirectorRuntimeFreezeManifest,
  suspendNexoraDirectorRuntimeCertification,
  validateNexoraDirectorRuntimeCertificationLock,
  validateNexoraDirectorRuntimeDependencyLock,
  validateNexoraDirectorRuntimeFreezeArtifact,
  validateNexoraDirectorRuntimeFreezeManifest,
  validateNexoraDirectorRuntimeFreezeRequest,
  validateNexoraDirectorRuntimePublicApiRegistry,
  validateNexoraDirectorRuntimePublicIdentityRegistry,
  validateNexoraDirectorRuntimePublicTypeRegistry,
  validateNexoraDirectorRuntimeSchemaLock,
  validateNexoraDirectorRuntimeVersionLock,
  verifyNexoraDirectorRuntimeFreeze,
  type NexoraDirectorRuntimeCertificationDependencies,
  type NexoraDirectorRuntimeCertificationProfile,
  type NexoraDirectorRuntimeCertificationReport,
  type NexoraDirectorRuntimeFreezeArtifact,
  type NexoraDirectorRuntimeFreezeDependencies,
  type NexoraDirectorRuntimeFreezeRequest,
  type NexoraDirectorRuntimeValidationDomain,
  type NexoraDirectorRuntimeValidationProfile,
  type NexoraDirectorRuntimeValidationReport,
} from "./nexoraObjectDirectorRuntimeFreeze.ts";

function freeze<T>(value: T, seen = new Set<object>()): T { if (value === null || typeof value !== "object" || seen.has(value as object)) return value; seen.add(value as object); Object.values(value as Record<string, unknown>).forEach((child) => freeze(child, seen)); return Object.freeze(value); }
function immutable(value: unknown, seen = new Set<object>()): boolean { if (value === null || typeof value !== "object" || seen.has(value as object)) return true; if (!Object.isFrozen(value)) return false; seen.add(value as object); return Object.values(value as Record<string, unknown>).every((child) => immutable(child, seen)); }
const domains = ["Identity", "AdapterFoundation", "CommandExecution", "RuntimeState", "StateSynchronization", "Events", "Feedback", "Acknowledgments", "Capabilities", "AdapterRegistry", "Assignments", "Routing", "FailoverMigration", "Lifecycle", "Revisions", "Health", "Diagnostics", "Snapshots", "Serialization", "Compatibility", "Immutability", "Determinism", "RendererIndependence", "PublicSurface", "Composite"] as const satisfies readonly NexoraDirectorRuntimeValidationDomain[];
const certDeps: NexoraDirectorRuntimeCertificationDependencies = freeze({ now: () => "2035-01-01T00:00:00.000Z", createCertificationId: () => "cert-release", createReportId: () => "cert-report-release", createHistoryId: () => "cert-history", createRequirementId: (name: string) => `requirement:${name}`, createEventId: () => "cert-event" });
const freezeDeps: NexoraDirectorRuntimeFreezeDependencies = freeze({ now: () => "2035-02-01T00:00:00.000Z", createFreezeId: () => "freeze-1", createLock: (version: string) => `lock:${version}` });
let sequence = 0;

function validationReport(profile: NexoraDirectorRuntimeValidationProfile = "Certification", score = 95, readiness: NexoraDirectorRuntimeValidationReport["releaseReadiness"] = "CertificationReady"): NexoraDirectorRuntimeValidationReport { sequence += 1; const result = freeze({ valid: true, profile, score, checkedDomains: domains, passedChecks: domains.map((domain, index) => freeze({ checkId: `check:${index}`, domain, name: domain, passed: true, weight: 1, message: "passed" })), warnings: [], errors: [], repairSuggestions: [], metrics: freeze({ totalChecks: domains.length, passedChecks: domains.length, warningCount: 0, errorCount: 0, repairSuggestionCount: 0, validatedRuntimeObjectCount: 0, validatedCommandCount: 0, validatedEventCount: 0, validatedFeedbackCount: 0, validatedAdapterCount: 0, validatedAssignmentCount: 0, driftCount: 0, conflictCount: 0 }), validatorIdentity: "NOL-4:6/NexoraObjectDirectorRuntimeValidationIntegrityEngine", createdAt: "2035-01-01T00:00:00.000Z" }); return freeze({ reportId: `validation-${sequence}`, requestId: `validation-request-${sequence}`, profile, valid: true, integrityScore: score, result, releaseReadiness: readiness, createdAt: "2035-01-01T00:00:00.000Z" }); }
function certification(profile: NexoraDirectorRuntimeCertificationProfile = "Release"): NexoraDirectorRuntimeCertificationReport { const validationProfile: NexoraDirectorRuntimeValidationProfile = profile === "Release" || profile === "Platform" ? "Certification" : profile === "Production" ? "Strict" : profile === "Testing" ? "Standard" : "Minimal"; const score = profile === "Release" ? 95 : profile === "Platform" ? 90 : profile === "Production" ? 85 : profile === "Testing" ? 75 : 60, readiness = profile === "Release" ? "CertificationReady" : profile === "Platform" ? "PlatformReady" : profile === "Production" ? "ProductionReady" : profile === "Testing" ? "TestingReady" : "DevelopmentReady"; return certifyNexoraDirectorRuntime(freeze({ requestId: `certify-${sequence + 1}`, profile, validationReport: validationReport(validationProfile, score, readiness), certifiedBy: "release-authority", expiresAt: "2036-01-01T00:00:00.000Z", context: freeze({ source: "Release" as const, occurredAt: "2035-01-01T00:00:00.000Z" }) }), certDeps); }
function request(report = certification("Release"), extra: Partial<NexoraDirectorRuntimeFreezeRequest> = {}): NexoraDirectorRuntimeFreezeRequest { return freeze({ freezeId: "freeze-1", certificationReport: report, releaseVersion: "1.0.0", compatibility: "BackwardCompatible" as const, generatedAt: "2035-02-01T00:00:00.000Z", ...extra }); }
function artifact(input = request()): NexoraDirectorRuntimeFreezeArtifact { const result = createNexoraDirectorRuntimeFreeze(input, freezeDeps); assert.equal("manifest" in result, true, JSON.stringify("errors" in result ? result.errors : [])); return result as NexoraDirectorRuntimeFreezeArtifact; }
function cloneCertification(report: NexoraDirectorRuntimeCertificationReport, changes: Record<string, unknown>): NexoraDirectorRuntimeCertificationReport { return freeze({ ...report, ...changes }) as NexoraDirectorRuntimeCertificationReport; }
function variant(base: NexoraDirectorRuntimeFreezeArtifact, changes: Partial<NexoraDirectorRuntimeFreezeArtifact>): NexoraDirectorRuntimeFreezeArtifact { const merged = { ...base, ...changes }; const publicSurface = freeze({ ...base.publicSurface, manifest: merged.manifest, apis: merged.publicApiRegistry, types: merged.publicTypeRegistry, identities: merged.publicIdentityRegistry }); return freeze({ ...merged, publicSurface }); }
const source = readFileSync(new URL("./nexoraObjectDirectorRuntimeFreeze.ts", import.meta.url), "utf8");

describe("NOL-4:8 Director Runtime Freeze", () => {
  it("1-3. exposes the exact identity through only NOL-4:7", () => { assert.equal(nexoraObjectDirectorRuntimeFreezeIdentity, "NOL-4:8/NexoraObjectDirectorRuntimeFreeze"); const imports = [...source.matchAll(/^import[^;]+from\s+["']([^"']+)["']/gm)].map((match) => match[1]); assert.deepEqual(imports, ["./nexoraObjectDirectorRuntimeCertification.ts"]); assert.doesNotMatch(source, /import[^;]+(?:ValidationIntegrity|CapabilityAdapter|EventFeedback|StateSynchronization|CommandExecution|AdapterFoundation)/); });
  it("4-13. only active, compatible, CertificationReady Release evidence can freeze", () => { assert.equal("manifest" in createNexoraDirectorRuntimeFreeze(request(), freezeDeps), true); const nonRelease = createNexoraDirectorRuntimeFreeze(request(certification("Development")), freezeDeps); assert.equal("errors" in nonRelease && nonRelease.errors.some((item) => item.code === "RUNTIME_FREEZE_CERTIFICATION_NOT_RELEASE"), true); const release = certification("Release"), pending = createPendingNexoraDirectorRuntimeCertification(freeze({ requestId: "pending", profile: "Release" as const, validationReport: validationReport(), certifiedBy: "authority" }), certDeps), suspended = suspendNexoraDirectorRuntimeCertification(release, "hold", "authority", certDeps), expired = expireNexoraDirectorRuntimeCertification(release, "expired", "authority", certDeps), revoked = revokeNexoraDirectorRuntimeCertification(release, "revoked", "authority", certDeps), rejected = certifyNexoraDirectorRuntime(freeze({ requestId: "reject", profile: "Release" as const, validationReport: validationReport("Certification", 40, "NotReady"), certifiedBy: "authority" }), certDeps); for (const report of [pending, suspended, expired, revoked, rejected]) assert.equal("errors" in createNexoraDirectorRuntimeFreeze(request(report), freezeDeps), true); const notReadyValidation = freeze({ ...release.validationReport, releaseReadiness: "PlatformReady" as const }), notReadyStamp = freeze({ ...release.stamp!, validationReadiness: "PlatformReady" as const }), notReady = cloneCertification(release, { validationReport: notReadyValidation, stamp: notReadyStamp }); assert.equal(validateNexoraDirectorRuntimeFreezeRequest(request(notReady)).errors.some((item) => item.code === "RUNTIME_FREEZE_CERTIFICATION_NOT_READY"), true); const degraded = cloneCertification(release, { stamp: freeze({ ...release.stamp!, compatibility: "Degraded" as const }) }); assert.equal(validateNexoraDirectorRuntimeFreezeRequest(request(degraded)).errors.some((item) => item.code === "RUNTIME_FREEZE_COMPATIBILITY_INVALID"), true); const lowValidation = freeze({ ...release.validationReport, integrityScore: 90, result: freeze({ ...release.validationReport.result, score: 90 }) }), low = cloneCertification(release, { validationReport: lowValidation, stamp: freeze({ ...release.stamp!, integrityScore: 90 }) }); assert.equal(validateNexoraDirectorRuntimeFreezeRequest(request(low)).valid, false); });
  it("14-33. artifact, locks, registries, status, and certification evidence are exact and immutable", () => { const release = certification("Release"), frozen = artifact(request(release)); for (const value of [frozen, frozen.manifest, frozen.certificationLock, frozen.dependencyLock, frozen.versionLock, frozen.schemaLock, frozen.publicApiRegistry, frozen.publicTypeRegistry, frozen.publicIdentityRegistry, frozen.publicSurface]) assert.equal(immutable(value), true); assert.deepEqual(nexoraDirectorRuntimeFreezeStatus, { released: true, certified: true, frozen: true, stable: true, readyForConsumer: true, label: "Released · Certified · Frozen · Stable · ReadyForConsumer" }); assert.equal(nexoraDirectorRuntimeFreezeCompatibility, "BackwardCompatible"); assert.equal(frozen.dependencyLock.dependencyCount, 1); assert.equal(frozen.dependencyLock.soleDependency, "NOL-4:7"); assert.equal(immutable(frozen.dependencyLock.forbiddenDirectDependencies), true); assert.equal(frozen.certificationLock.certificationId, release.certificationId); assert.equal(frozen.certificationLock.validationReportId, release.validationReport.reportId); assert.equal(frozen.certificationLock.integrityScore, release.validationReport.integrityScore); assert.equal(frozen.certificationLock.releaseReadiness, release.validationReport.releaseReadiness); });
  it("34-44. public registries and equal Freeze inputs are unique, counted, ordered, deterministic, and non-mutating", () => { const input = request(), before = JSON.stringify(input.certificationReport), left = artifact(input), right = artifact(input); const apiIdentities = left.publicApiRegistry.entries.map((entry) => entry.identity), exports = left.publicApiRegistry.entries.map((entry) => entry.exportName), types = left.publicTypeRegistry.entries.map((entry) => entry.typeName), identities = left.publicIdentityRegistry.identities; assert.equal(new Set(apiIdentities).size, apiIdentities.length); assert.equal(new Set(exports).size, exports.length); assert.equal(new Set(types).size, types.length); assert.equal(new Set(identities).size, identities.length); assert.equal(left.publicApiRegistry.count, left.publicApiRegistry.entries.length); assert.equal(left.publicTypeRegistry.count, left.publicTypeRegistry.entries.length); assert.equal(left.publicIdentityRegistry.count, identities.length); assert.equal(left.manifest.publicApiCount, left.publicApiRegistry.count); assert.equal(left.manifest.publicTypeCount, left.publicTypeRegistry.count); assert.equal(left.manifest.publicIdentityCount, left.publicIdentityRegistry.count); assert.deepEqual(exports, [...exports].sort()); assert.deepEqual(left, right); assert.equal(JSON.stringify(input.certificationReport), before); });
  it("45-55. consumer guarantees and all four immutable projections expose only locked evidence", () => { const frozen = artifact(); assert.deepEqual(frozen.consumerMetadata, nexoraDirectorRuntimeConsumerMetadata); assert.equal(frozen.consumerMetadata.readiness, "ReadyForConsumer"); assert.equal(frozen.consumerMetadata.apiStability, "StableAPI"); assert.equal(frozen.consumerMetadata.dependencyPolicy, "FreezeOnlyDependency"); assert.equal(frozen.consumerMetadata.consumerEntryPolicy, "SoleConsumerEntryPoint"); assert.equal(nexoraDirectorRuntimeReleaseInformation.nextConsumerEntry, "NOL-4:9/PublicIndex"); const consumer = projectNexoraDirectorRuntimeFreeze(frozen, "Consumer"), platform = projectNexoraDirectorRuntimeFreeze(frozen, "Platform"), release = projectNexoraDirectorRuntimeFreeze(frozen, "Release"), diagnostics = projectNexoraDirectorRuntimeFreeze(frozen, "Diagnostics"); assert.equal(consumer.readiness, "ReadyForConsumer"); assert.ok(platform.dependencyLock); assert.ok(release.certificationLock); assert.ok(diagnostics.publicApiRegistry); for (const projection of [consumer, platform, release, diagnostics]) assert.equal(immutable(projection), true); });
  it("56-63. verification detects each corrupted component and mutable output", () => { const frozen = artifact(); assert.equal(verifyNexoraDirectorRuntimeFreeze(frozen).valid, true); const badManifest = freeze({ ...frozen.manifest, identity: "wrong" }), badCertification = freeze({ ...frozen.certificationLock, integrityScore: 1 }), badDependency = freeze({ ...frozen.dependencyLock, dependencyCount: 2 as 1 }), badVersion = freeze({ ...frozen.versionLock, freezeVersion: "2.0.0" }), badSchema = freeze({ ...frozen.schemaLock, freezeSchemaVersion: "2.0.0" }), badRegistry = freeze({ ...frozen.publicApiRegistry, count: frozen.publicApiRegistry.count + 1 }); assert.equal(verifyNexoraDirectorRuntimeFreeze(variant(frozen, { manifest: badManifest })).manifestValid, false); assert.equal(verifyNexoraDirectorRuntimeFreeze(variant(frozen, { certificationLock: badCertification })).certificationValid, false); assert.equal(verifyNexoraDirectorRuntimeFreeze(variant(frozen, { dependencyLock: badDependency })).dependencyLockValid, false); assert.equal(verifyNexoraDirectorRuntimeFreeze(variant(frozen, { versionLock: badVersion })).versionLockValid, false); assert.equal(verifyNexoraDirectorRuntimeFreeze(variant(frozen, { schemaLock: badSchema })).schemaLockValid, false); assert.equal(verifyNexoraDirectorRuntimeFreeze(variant(frozen, { publicApiRegistry: badRegistry })).registryValid, false); assert.equal(verifyNexoraDirectorRuntimeFreeze({ ...frozen }).valid, false); });
  it("64-79. comparison and compatibility classify additions, removals, locks, and missing evidence", () => { const base = artifact(), versioned = variant(base, { manifest: freeze({ ...base.manifest, releaseVersion: "1.1.0" }) }), schema = variant(base, { manifest: freeze({ ...base.manifest, schemaVersion: "1.1.0" }) }), certificationChanged = variant(base, { certificationLock: freeze({ ...base.certificationLock, certificationId: "cert-2" }) }), compatibilityChanged = variant(base, { manifest: freeze({ ...base.manifest, compatibility: "ForwardCompatible" as const }) }); assert.equal(compareNexoraDirectorRuntimeFreezes(base, versioned).versionChanged, true); assert.equal(compareNexoraDirectorRuntimeFreezes(base, schema).schemaChanged, true); assert.equal(compareNexoraDirectorRuntimeFreezes(base, certificationChanged).certificationChanged, true); assert.equal(compareNexoraDirectorRuntimeFreezes(base, compatibilityChanged).compatibilityChanged, true); const extraEntry = freeze({ ...base.publicApiRegistry.entries[0]!, identity: "extra", exportName: "extraApi" }), addedRegistry = freeze({ ...base.publicApiRegistry, entries: [...base.publicApiRegistry.entries, extraEntry], count: base.publicApiRegistry.count + 1 }), added = variant(base, { publicApiRegistry: addedRegistry, manifest: freeze({ ...base.manifest, publicApiCount: addedRegistry.count }) }); const removedEntries = base.publicApiRegistry.entries.slice(1), removedRegistry = freeze({ ...base.publicApiRegistry, entries: removedEntries, count: removedEntries.length }), removed = variant(base, { publicApiRegistry: removedRegistry, manifest: freeze({ ...base.manifest, publicApiCount: removedRegistry.count }) }), changedDependency = variant(base, { dependencyLock: freeze({ ...base.dependencyLock, soleDependency: "NOL-4:6" as "NOL-4:7" }) }); assert.equal(compareNexoraDirectorRuntimeFreezes(base, added).addedApiExports.includes("extraApi"), true); assert.equal(compareNexoraDirectorRuntimeFreezes(base, removed).removedApiExports.length, 1); assert.equal(compareNexoraDirectorRuntimeFreezes(base, removed).breaking, true); assert.equal(compareNexoraDirectorRuntimeFreezes(base, changedDependency).breaking, true); assert.equal(evaluateNexoraDirectorRuntimeFreezeCompatibility(base, removed), "Breaking"); assert.equal(evaluateNexoraDirectorRuntimeFreezeCompatibility(base, added), "ForwardCompatible"); assert.equal(evaluateNexoraDirectorRuntimeFreezeCompatibility(base, base), "BackwardCompatible"); assert.equal(evaluateNexoraDirectorRuntimeFreezeCompatibility(), "Unknown"); assert.equal("errors" in createNexoraDirectorRuntimeFreeze(request(undefined, { compatibility: "Breaking" }), freezeDeps), true); assert.deepEqual(compareNexoraDirectorRuntimeFreezes(base, base), compareNexoraDirectorRuntimeFreezes(base, base)); });
  it("80-93. getters and validators reject duplicate, mismatched, mutable, and resource-bearing locks", () => { const frozen = artifact(); for (const value of [getNexoraDirectorRuntimePublicApiRegistry(frozen), getNexoraDirectorRuntimePublicTypeRegistry(frozen), getNexoraDirectorRuntimePublicIdentityRegistry(frozen), getNexoraDirectorRuntimeFreezeManifest(frozen), getNexoraDirectorRuntimeReleaseInformation(), getNexoraDirectorRuntimeConsumerMetadata()]) assert.equal(immutable(value), true); const firstApi = frozen.publicApiRegistry.entries[0]!, secondApi = frozen.publicApiRegistry.entries[1]!, duplicateIdentity = freeze({ ...frozen.publicApiRegistry, entries: [firstApi, freeze({ ...secondApi, identity: firstApi.identity })], count: 2 }), duplicateExport = freeze({ ...frozen.publicApiRegistry, entries: [firstApi, freeze({ ...secondApi, exportName: firstApi.exportName })], count: 2 }), firstType = frozen.publicTypeRegistry.entries[0]!, duplicateType = freeze({ ...frozen.publicTypeRegistry, entries: [firstType, firstType], count: 2 }), identity = frozen.publicIdentityRegistry.identities[0]!, duplicatePublicIdentity = freeze({ ...frozen.publicIdentityRegistry, identities: [identity, identity], count: 2 }); assert.equal(validateNexoraDirectorRuntimePublicApiRegistry(duplicateIdentity).errors[0]?.code, "RUNTIME_FREEZE_DUPLICATE_API_IDENTITY"); assert.equal(validateNexoraDirectorRuntimePublicApiRegistry(duplicateExport).errors[0]?.code, "RUNTIME_FREEZE_DUPLICATE_EXPORT_NAME"); assert.equal(validateNexoraDirectorRuntimePublicTypeRegistry(duplicateType).errors[0]?.code, "RUNTIME_FREEZE_DUPLICATE_TYPE_NAME"); assert.equal(validateNexoraDirectorRuntimePublicIdentityRegistry(duplicatePublicIdentity).errors[0]?.code, "RUNTIME_FREEZE_DUPLICATE_PUBLIC_IDENTITY"); assert.equal(validateNexoraDirectorRuntimeDependencyLock(freeze({ ...frozen.dependencyLock, dependencyCount: 2 })).valid, false); assert.equal(validateNexoraDirectorRuntimeDependencyLock(freeze({ ...frozen.dependencyLock, soleDependency: "NOL-4:6" })).valid, false); assert.equal(validateNexoraDirectorRuntimeSchemaLock(freeze({ ...frozen.schemaLock, freezeSchemaVersion: "2.0.0" })).valid, false); assert.equal(validateNexoraDirectorRuntimeVersionLock(frozen.versionLock).valid, true); assert.equal(validateNexoraDirectorRuntimeCertificationLock(frozen.certificationLock).valid, true); assert.equal(validateNexoraDirectorRuntimeFreezeManifest(frozen.manifest).valid, true); class Mesh {} assert.equal(validateNexoraDirectorRuntimeFreezeRequest(request(undefined, { metadata: freeze({ resource: new Mesh() }) })).valid, false); assert.equal(validateNexoraDirectorRuntimeFreezeRequest(request(undefined, { metadata: freeze({ callback: () => true }) })).valid, false); class AdapterConnection {} assert.equal(validateNexoraDirectorRuntimeFreezeRequest(request(undefined, { metadata: freeze({ resource: new AdapterConnection() }) })).valid, false); });
  it("94-98. versioned serialization round-trips semantically and rejects unsupported envelopes", () => { const frozen = artifact(), artifactJson = serializeNexoraDirectorRuntimeFreezeArtifact(frozen), manifestJson = serializeNexoraDirectorRuntimeFreezeManifest(frozen.manifest), restored = deserializeNexoraDirectorRuntimeFreezeArtifact(artifactJson), restoredManifest = deserializeNexoraDirectorRuntimeFreezeManifest(manifestJson); assert.deepEqual(restored, frozen); assert.deepEqual(restoredManifest, frozen.manifest); assert.equal(serializeNexoraDirectorRuntimeFreezeArtifact(restored), artifactJson); assert.equal(immutable(restored), true); const envelope = JSON.parse(artifactJson); envelope.schemaVersion = "2.0.0"; assert.throws(() => deserializeNexoraDirectorRuntimeFreezeArtifact(JSON.stringify(envelope)), /Unsupported/); assert.doesNotMatch(artifactJson, /"(?:callback|connection|renderer|function|mesh|scene|adapterInstance)"\s*:/i); });
  it("99-108. Freeze repeats and executes nothing and mutates no upstream input", () => { const input = request(), before = JSON.stringify(input.certificationReport); createNexoraDirectorRuntimeFreeze(input, freezeDeps); assert.equal(JSON.stringify(input.certificationReport), before); assert.doesNotMatch(source, /\b(?:executeRuntimeCommand|synchronizeRuntimeState|dispatchEvent|acknowledgeRuntimeFeedback|instantiateAdapter|routeRuntimeCommand|executeFailover|executeMigration|performRecovery|persistRuntime|certifyNexoraDirectorRuntime|validateNexoraDirectorRuntime)\s*\(/); assert.doesNotMatch(source, /from\s+["'][^"']*(?:react|next|three|webgl|webgpu|workspace|advisor|timeline|scenario|database|plugin|event-bus)/i); assert.equal(validateNexoraDirectorRuntimeFreezeArtifact(artifact()).valid, true); assert.doesNotThrow(() => assertNexoraDirectorRuntimeFreezeInvariants(artifact())); });
});
