import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { describe, it } from "node:test";
import { fileURLToPath } from "node:url";
import { createDirectorRuntimeAdapterContext, directorRuntimeAdapterFoundationSchemaVersion, type NexoraDirectorRuntimeCapabilities } from "./nexoraObjectDirectorRuntimeAdapterFoundation.ts";
import type { NexoraDirectorRuntimeExecutionCommand } from "./nexoraObjectDirectorRuntimeCommandExecutionModel.ts";
import { createNexoraDirectorRuntimeState } from "./nexoraObjectDirectorRuntimeStateSynchronizationEngine.ts";
import {
  applyNexoraDirectorRuntimeCapabilityAdapterCoordination, assertNexoraDirectorRuntimeCapabilityAdapterInvariants,
  calculateNexoraDirectorRuntimeAdapterCapabilityScore, compareNexoraDirectorRuntimeCapabilityAdapterSnapshots,
  coordinateNexoraDirectorRuntimeCapabilityAdapterBatch, createNexoraDirectorRuntimeAdapterRegistry,
  createNexoraDirectorRuntimeCapabilityAdapterSnapshot, deriveNexoraDirectorRuntimeCapabilityRequirements,
  deserializeNexoraDirectorRuntimeAdapterDescriptor, deserializeNexoraDirectorRuntimeAdapterRegistry,
  deserializeNexoraDirectorRuntimeCapabilityAdapterCoordinationPlan,
  deserializeNexoraDirectorRuntimeCapabilityAdapterCoordinationState,
  deserializeNexoraDirectorRuntimeCapabilityAdapterRecord, deserializeNexoraDirectorRuntimeCapabilityAdapterSnapshot,
  deserializeNexoraDirectorRuntimeCapabilityRequirementSet, detectNexoraDirectorRuntimeAdapterCapabilityChanges,
  detectNexoraDirectorRuntimeAdapterConflicts, evaluateNexoraDirectorRuntimeCapabilityAdapterCoordination,
  findNexoraDirectorRuntimeAdapter, listNexoraDirectorRuntimeAdapters,
  matchNexoraDirectorRuntimeAdapterCapabilities,
  nexoraObjectDirectorRuntimeCapabilityAdapterCoordinationEngineIdentity,
  nexoraObjectDirectorRuntimeCapabilityAdapterCoordinationEngineVersion,
  nexoraObjectDirectorRuntimeCapabilityAdapterCoordinationSchemaVersion,
  planNexoraDirectorRuntimeAdapterFailover, planNexoraDirectorRuntimeAdapterRecovery,
  planNexoraDirectorRuntimeCapabilityMigration, planNexoraDirectorRuntimeDegradedMode,
  projectNexoraDirectorRuntimeCapabilityAdapterHistory, reconcileNexoraDirectorRuntimeAdapterRegistry,
  registerNexoraDirectorRuntimeAdapter, removeNexoraDirectorRuntimeAdapter,
  resolveNexoraDirectorRuntimeAdapterAffinity, resolveNexoraDirectorRuntimeAdapterHealthCoordination,
  routeNexoraDirectorRuntimeCommandsToAdapters, selectNexoraDirectorRuntimeAdapters,
  serializeNexoraDirectorRuntimeAdapterDescriptor, serializeNexoraDirectorRuntimeAdapterRegistry,
  serializeNexoraDirectorRuntimeCapabilityAdapterCoordinationPlan,
  serializeNexoraDirectorRuntimeCapabilityAdapterCoordinationState,
  serializeNexoraDirectorRuntimeCapabilityAdapterRecord, serializeNexoraDirectorRuntimeCapabilityAdapterSnapshot,
  serializeNexoraDirectorRuntimeCapabilityRequirementSet,
  simulateNexoraDirectorRuntimeCapabilityAdapterSequence, transitionNexoraDirectorRuntimeAdapterLifecycle,
  updateNexoraDirectorRuntimeAdapter, validateNexoraDirectorRuntimeAdapterAssignments,
  validateNexoraDirectorRuntimeAdapterCapabilityDescriptor, validateNexoraDirectorRuntimeAdapterDescriptor,
  validateNexoraDirectorRuntimeAdapterExclusivity, validateNexoraDirectorRuntimeAdapterRegistry,
  validateNexoraDirectorRuntimeCapabilityAdapterCoordinationPlan,
  validateNexoraDirectorRuntimeCapabilityAdapterCoordinationRequest,
  validateNexoraDirectorRuntimeCapabilityAdapterCoordinationResult,
  validateNexoraDirectorRuntimeCapabilityAdapterCoordinationState,
  validateNexoraDirectorRuntimeCapabilityRequirementSet,
  type NexoraDirectorRuntimeAdapterAssignment, type NexoraDirectorRuntimeAdapterDescriptor,
  type NexoraDirectorRuntimeCapabilityAdapterCoordinationRequest,
  type NexoraDirectorRuntimeCapabilityAdapterDependencies,
  type NexoraDirectorRuntimeCapabilityRequirementSet,
} from "./nexoraObjectDirectorRuntimeCapabilityAdapterCoordinationEngine.ts";

const __dirname = dirname(fileURLToPath(import.meta.url));
const source = readFileSync(join(__dirname, "nexoraObjectDirectorRuntimeCapabilityAdapterCoordinationEngine.ts"), "utf8");
function freeze<T>(value: T, seen = new Set<object>()): T { if (value === null || typeof value !== "object" || seen.has(value as object)) return value; seen.add(value as object); Object.values(value as Record<string, unknown>).forEach((x) => freeze(x, seen)); return Object.freeze(value); }
function isFrozen(value: unknown, seen = new Set<object>()): boolean { if (value === null || typeof value !== "object" || seen.has(value as object)) return true; if (!Object.isFrozen(value)) return false; seen.add(value as object); return Object.values(value as Record<string, unknown>).every((x) => isFrozen(x, seen)); }
const capabilities: NexoraDirectorRuntimeCapabilities = { cameraIntents: true, focus: true, interaction: true, animationHints: true, attention: true, labels: true, indicators: true, relationships: true, clustering: true, timelineReplay: true, operationOverlays: true, themeSwitching: true, reducedMotion: true, diagnostics: true };
const deps: NexoraDirectorRuntimeCapabilityAdapterDependencies = freeze({ now: () => "2026-08-05T01:00:00.000Z", createRegistryId: () => "registry-fixed", createStateId: () => "state-fixed", createAssignmentId: (id, role) => `${id}:${role}`, createConflictId: (ids, type) => `${type}:${[...ids].sort().join(":")}`, createMigrationId: (from, to) => `migration:${from ?? "none"}:${to}`, createEventId: () => "event-fixed", createSnapshotId: () => "snapshot-fixed" });
function context() { return createDirectorRuntimeAdapterContext({ runtimeId: "runtime-1", adapterVersion: "1.0.0", engineVersion: "1.0.0", runtimeState: "Ready", capabilities, compatibility: { compatible: true, adapterVersion: "1.0.0", engineVersion: "1.0.0", schemaVersion: directorRuntimeAdapterFoundationSchemaVersion, warnings: [] }, timestamp: "2026-08-05T00:00:00.000Z", diagnosticsEnabled: true, reducedMotion: false, metadata: {} }); }
function capability(name: "SceneObjects" | "CameraIntent" | "Labels" | "Indicators" | "Diagnostics", support: "Partial" | "Supported" | "Preferred" = "Supported") { return freeze({ capability: name, support, version: "1.0.0", requiredDependencies: [], incompatibleCapabilities: [], limits: {}, metadata: {} }); }
function adapter(id = "primary", overrides: Partial<NexoraDirectorRuntimeAdapterDescriptor> = {}): NexoraDirectorRuntimeAdapterDescriptor { return freeze({ adapterId: id, adapterType: "PrimaryRenderer", adapterVersion: "1.0.0", schemaVersion: "1.0.0", lifecycleState: "Ready", health: "Healthy", priority: 10, weight: 10, exclusive: true, capabilities: [capability("SceneObjects"), capability("CameraIntent"), capability("Labels"), capability("Indicators")], compatibility: "Compatible", registeredAt: "2026-08-05T00:00:00.000Z", updatedAt: "2026-08-05T00:00:00.000Z", metadata: {}, ...overrides }); }
function command(id: string, runtimeCommandType: string, order: number): NexoraDirectorRuntimeExecutionCommand { return freeze({ commandId: id, runtimeCommandType: runtimeCommandType as NexoraDirectorRuntimeExecutionCommand["runtimeCommandType"], revision: 0, order, priority: 0, dependencies: [], retryCount: 0, timeout: 0, metadata: {} }); }
function registry(...adapters: NexoraDirectorRuntimeAdapterDescriptor[]) { let value = createNexoraDirectorRuntimeAdapterRegistry("2026-08-05T00:00:00.000Z", deps); for (const item of adapters) value = registerNexoraDirectorRuntimeAdapter(value, item); return value; }
function request(adapterRegistry = registry(adapter()), overrides: Partial<NexoraDirectorRuntimeCapabilityAdapterCoordinationRequest> = {}): NexoraDirectorRuntimeCapabilityAdapterCoordinationRequest { const ctx = context(); return freeze({ requestId: "request-1", runtimeContext: ctx, runtimeState: createNexoraDirectorRuntimeState(ctx), adapterRegistry, runtimeCommands: [command("create", "CreateRuntimeObject", 0), command("camera", "UpdateCameraIntent", 1)], mode: "Atomic", expectedRegistryRevision: adapterRegistry.revision, context: { source: "RuntimeAdapter", occurredAt: "2026-08-05T01:00:00.000Z", correlationId: "correlation", causationId: "causation", preferSingleAdapter: true, allowSplitExecution: true, allowDegradedMode: true, allowFailover: true, allowMigration: true }, ...overrides }); }

describe("NOL-4:5 Runtime Capability & Adapter Coordination Engine", () => {
  it("1-4. identity, imports, default registry, and immutability are exact", () => { assert.equal(nexoraObjectDirectorRuntimeCapabilityAdapterCoordinationEngineIdentity, "NOL-4:5/NexoraObjectDirectorRuntimeCapabilityAdapterCoordinationEngine"); assert.equal(nexoraObjectDirectorRuntimeCapabilityAdapterCoordinationEngineVersion, "1.0.0"); assert.equal(nexoraObjectDirectorRuntimeCapabilityAdapterCoordinationSchemaVersion, "1.0.0"); const imports = [...source.matchAll(/^import[\s\S]*?from\s+"([^"]+)";/gm)].map((x) => x[1]); assert.deepEqual(imports, ["./nexoraObjectDirectorRuntimeAdapterFoundation.ts", "./nexoraObjectDirectorRuntimeCommandExecutionModel.ts", "./nexoraObjectDirectorRuntimeStateSynchronizationEngine.ts", "./nexoraObjectDirectorRuntimeEventFeedbackCoordinationEngine.ts"]); const empty = createNexoraDirectorRuntimeAdapterRegistry("2026-08-05T00:00:00.000Z", deps); assert.equal(empty.revision, 0); assert.equal(isFrozen(empty), true); });
  it("5-13. registration, update, removal, revisions, and lifecycle are enforced", () => { const first = registry(adapter()); assert.equal(first.revision, 1); assert.equal(findNexoraDirectorRuntimeAdapter(first, "primary")?.adapterId, "primary"); assert.equal(listNexoraDirectorRuntimeAdapters(first).length, 1); assert.throws(() => registerNexoraDirectorRuntimeAdapter(first, adapter()), /Duplicate/); const degraded = adapter("primary", { lifecycleState: "Degraded", health: "Degraded", updatedAt: "2026-08-05T00:01:00.000Z" }); const updated = updateNexoraDirectorRuntimeAdapter(first, degraded); assert.equal(updated.revision, 2); assert.equal(updateNexoraDirectorRuntimeAdapter(updated, degraded), updated); const stopped = updateNexoraDirectorRuntimeAdapter(updated, adapter("primary", { lifecycleState: "Stopped", health: "Unavailable", updatedAt: "2026-08-05T00:02:00.000Z" })); const removed = removeNexoraDirectorRuntimeAdapter(stopped, "primary", "2026-08-05T00:03:00.000Z"); assert.equal(findNexoraDirectorRuntimeAdapter(removed, "primary")?.lifecycleState, "Removed"); assert.throws(() => updateNexoraDirectorRuntimeAdapter(removed, adapter()), /cannot return/); assert.equal(transitionNexoraDirectorRuntimeAdapterLifecycle("Registered", "Initializing"), "Initializing"); assert.throws(() => transitionNexoraDirectorRuntimeAdapterLifecycle("Registered", "Ready"), /Illegal/); });
  it("14-18. descriptor validation checks numbers, uniqueness, dependencies, cycles, incompatibility", () => { assert.equal(validateNexoraDirectorRuntimeAdapterDescriptor(adapter()).valid, true); assert.equal(validateNexoraDirectorRuntimeAdapterDescriptor(adapter("bad", { priority: -1 })).valid, false); assert.equal(validateNexoraDirectorRuntimeAdapterDescriptor(adapter("bad", { weight: -1 })).valid, false); assert.equal(validateNexoraDirectorRuntimeAdapterDescriptor(adapter("bad", { capabilities: [capability("SceneObjects"), capability("SceneObjects")] })).valid, false); assert.equal(validateNexoraDirectorRuntimeAdapterCapabilityDescriptor({ ...capability("SceneObjects"), requiredDependencies: ["SceneObjects"] }).valid, false); assert.equal(validateNexoraDirectorRuntimeAdapterDescriptor(adapter("bad", { capabilities: [{ ...capability("SceneObjects"), requiredDependencies: ["CameraIntent"] }] })).valid, false); });
  it("19-23. deterministic requirement derivation preserves semantics", () => { const commands = [command("create", "CreateRuntimeObject", 0), command("camera", "UpdateCameraIntent", 1), command("labels", "UpdateLabels", 2), command("indicators", "UpdateIndicators", 3)]; const derived = deriveNexoraDirectorRuntimeCapabilityRequirements({ requirementSetId: "requirements", runtimeCommands: commands }); assert.deepEqual(derived, deriveNexoraDirectorRuntimeCapabilityRequirements({ requirementSetId: "requirements", runtimeCommands: commands })); assert.deepEqual(derived.requirements.map((x) => x.capability), ["CameraIntent", "Indicators", "Labels", "SceneObjects"]); const explicit = deriveNexoraDirectorRuntimeCapabilityRequirements({ requirementSetId: "explicit", explicitRequirements: [{ capability: "Diagnostics", importance: "Optional", minimumSupport: "Partial", allowDegraded: true, constraints: {} }] }); assert.equal(explicit.requirements[0]?.importance, "Optional"); });
  it("24-35. matching, scoring, health, compatibility, stable selection, and fallback order are deterministic", () => { const commands = [command("create", "CreateRuntimeObject", 0)]; const requirements = deriveNexoraDirectorRuntimeCapabilityRequirements({ requirementSetId: "r", runtimeCommands: commands }); const full = matchNexoraDirectorRuntimeAdapterCapabilities(adapter(), requirements); assert.equal(full.compatibility, "Full"); const partialAdapter = adapter("partial", { capabilities: [capability("SceneObjects", "Partial")], health: "Degraded", lifecycleState: "Degraded" }); const allowPartial: NexoraDirectorRuntimeCapabilityRequirementSet = freeze({ requirementSetId: "p", requirements: [{ capability: "SceneObjects", importance: "Required", minimumSupport: "Supported", allowDegraded: true, constraints: {} }] }); assert.equal(matchNexoraDirectorRuntimeAdapterCapabilities(partialAdapter, allowPartial).compatibility, "Degraded"); assert.equal(matchNexoraDirectorRuntimeAdapterCapabilities(adapter("missing", { capabilities: [] }), requirements).compatibility, "Insufficient"); assert.ok(full.score >= 0 && full.score <= 100); assert.equal(full.score, calculateNexoraDirectorRuntimeAdapterCapabilityScore(adapter(), { ...full, score: undefined as never })); const selection = selectNexoraDirectorRuntimeAdapters(registry(partialAdapter, adapter("healthy"), adapter("other", { priority: 5 })), requirements, "healthy"); assert.equal(selection.primaryAdapterId, "healthy"); assert.deepEqual(selection.fallbackAdapterIds, ["other"]); assert.deepEqual(selection, selectNexoraDirectorRuntimeAdapters(registry(partialAdapter, adapter("healthy"), adapter("other", { priority: 5 })), requirements, "healthy")); });
  it("36-47. assignments, routing, exclusivity, conflict, and affinity remain semantic", () => { const reg = registry(adapter("primary"), adapter("fallback", { priority: 5 })); const req = request(reg); const plan = evaluateNexoraDirectorRuntimeCapabilityAdapterCoordination(req, deps); assert.equal(plan.assignments.find((x) => x.role === "Fallback")?.active, false); assert.equal(plan.routes.length, 2); assert.deepEqual(plan.routes.map((x) => x.commandId), ["create", "camera"]); assert.equal(plan.routes.every((x) => x.primaryAdapterId === "primary"), true); assert.equal(validateNexoraDirectorRuntimeAdapterAssignments(plan.assignments, reg, req.runtimeCommands).valid, true); const duplicate: NexoraDirectorRuntimeAdapterAssignment = freeze({ ...plan.assignments[0]!, assignmentId: "second", adapterId: "fallback" }); assert.equal(validateNexoraDirectorRuntimeAdapterExclusivity([plan.assignments[0]!, duplicate]).valid, false); assert.equal(detectNexoraDirectorRuntimeAdapterConflicts([plan.assignments[0]!, duplicate], reg, deps).some((x) => x.type === "DuplicatePrimary"), true); assert.equal(resolveNexoraDirectorRuntimeAdapterAffinity({ preferredAdapterId: "primary", strength: "Required", reason: "stable" }, reg, ["primary", "fallback"]), "primary"); const removed = registry(adapter("removed", { lifecycleState: "Removed", health: "Unavailable" })); assert.throws(() => resolveNexoraDirectorRuntimeAdapterAffinity({ preferredAdapterId: "removed", strength: "Required", reason: "bad" }, removed, ["removed"]), /Required/); });
  it("48-60. degraded, failover, migration, recovery, and health plans never execute", () => { const requirements: NexoraDirectorRuntimeCapabilityRequirementSet = freeze({ requirementSetId: "r", requirements: [{ capability: "SceneObjects", importance: "Required", minimumSupport: "Supported", allowDegraded: false, constraints: {} }, { capability: "Diagnostics", importance: "Optional", minimumSupport: "Supported", allowDegraded: true, constraints: {} }] }); const reg = registry(adapter("primary"), adapter("fallback", { priority: 5 })); const selection = selectNexoraDirectorRuntimeAdapters(reg, requirements); const routes = routeNexoraDirectorRuntimeCommandsToAdapters([command("create", "CreateRuntimeObject", 0)], selection, reg, requirements); const degraded = planNexoraDirectorRuntimeDegradedMode(requirements, selection, routes); assert.equal(degraded.disabledCapabilities.includes("SceneObjects"), false); assert.equal(degraded.enabled, true); const failedReg = registry(adapter("primary", { lifecycleState: "Unavailable", health: "Unavailable" }), adapter("fallback", { priority: 5 })); const failedSelection = selectNexoraDirectorRuntimeAdapters(failedReg, requirements); const failover = planNexoraDirectorRuntimeAdapterFailover("primary", failedSelection, failedReg, routes, createNexoraDirectorRuntimeState(context())); assert.equal(failover.required, true); assert.equal(failover.replacementAdapterId, "fallback"); assert.deepEqual(failover.preserveRuntimeObjectIds, []); const migration = planNexoraDirectorRuntimeCapabilityMigration("primary", "fallback", ["SceneObjects"], ["operation-command"], "Failover", failedReg, deps); assert.equal(migration.preserveRuntimeState, true); assert.deepEqual(migration.commandIds, ["operation-command"]); assert.equal(migration.requiresCheckpoint, true); assert.equal(planNexoraDirectorRuntimeAdapterRecovery("primary", "fallback", reg).replaceCurrentPrimary, false); assert.equal(resolveNexoraDirectorRuntimeAdapterHealthCoordination(adapter(), "primary").retainPrimary, true); });
  it("61-65. capability changes detect additions, removals, upgrades, downgrades, dependencies", () => { const before = registry(adapter("a", { capabilities: [capability("SceneObjects")] })); const after = registry(adapter("a", { capabilities: [capability("SceneObjects", "Preferred"), capability("CameraIntent")] })); const changes = detectNexoraDirectorRuntimeAdapterCapabilityChanges(before, after); assert.equal(changes.some((x) => x.change === "Added"), true); assert.equal(changes.some((x) => x.change === "Upgraded"), true); assert.equal(detectNexoraDirectorRuntimeAdapterCapabilityChanges(after, before).some((x) => x.change === "Removed"), true); assert.equal(detectNexoraDirectorRuntimeAdapterCapabilityChanges(after, before).some((x) => x.change === "Downgraded"), true); const reconciled = reconcileNexoraDirectorRuntimeAdapterRegistry(before, after.adapters); assert.equal(reconciled.updatedAdapterIds.includes("a"), true); });
  it("66-75. evaluation preserves input and enforces simulation, revisions, Atomic, BestEffort", () => { const input = request(), before = JSON.stringify(input); const applied = applyNexoraDirectorRuntimeCapabilityAdapterCoordination(input, deps); assert.equal(JSON.stringify(input), before); assert.equal(applied.nextState.revision, 1); assert.equal(applied.events[0]?.correlationId, "correlation"); assert.equal(applied.events[0]?.causationId, "causation"); assert.equal(applied.record.revisionBefore, 0); assert.equal(applied.record.revisionAfter, 1); const simulation = applyNexoraDirectorRuntimeCapabilityAdapterCoordination(request(input.adapterRegistry, { mode: "Simulation" }), deps); assert.equal(simulation.nextState.revision, 0); const conflict = applyNexoraDirectorRuntimeCapabilityAdapterCoordination(request(input.adapterRegistry, { expectedCoordinationRevision: 9 }), deps); assert.equal(conflict.accepted, false); assert.equal(conflict.nextState.revision, 0); const registryConflict = applyNexoraDirectorRuntimeCapabilityAdapterCoordination(request(input.adapterRegistry, { expectedRegistryRevision: 9 }), deps); assert.equal(registryConflict.accepted, false); const empty = request(createNexoraDirectorRuntimeAdapterRegistry("2026-08-05T00:00:00.000Z", deps)); const atomic = applyNexoraDirectorRuntimeCapabilityAdapterCoordination(empty, deps); assert.equal(atomic.accepted, false); const best = applyNexoraDirectorRuntimeCapabilityAdapterCoordination(freeze({ ...empty, mode: "BestEffort" as const }), deps); assert.equal(best.accepted, true); assert.equal(best.plan.routes.every((x) => x.routeState === "Blocked"), true); });
  it("76-82. batches, sequences, events, records, and histories are deterministic", () => { const valid = request(), invalid = request(valid.adapterRegistry, { requestId: "bad", expectedRegistryRevision: 99 }); assert.throws(() => coordinateNexoraDirectorRuntimeCapabilityAdapterBatch({ requests: [valid, valid], mode: "Atomic" }, deps), /Duplicate/); const atomic = coordinateNexoraDirectorRuntimeCapabilityAdapterBatch({ requests: [valid, invalid], mode: "Atomic" }, deps); assert.equal(atomic.finalState.revision, 0); assert.deepEqual(atomic.acceptedRequestIds, []); const best = coordinateNexoraDirectorRuntimeCapabilityAdapterBatch({ requests: [valid, invalid], mode: "BestEffort" }, deps); assert.equal(best.finalState.revision, 1); const sequence = simulateNexoraDirectorRuntimeCapabilityAdapterSequence([valid, invalid], false, deps); assert.deepEqual(sequence.plans.map((x) => x.requestId), ["request-1", "bad"]); assert.equal(sequence.firstFailureRequestId, "bad"); const record = applyNexoraDirectorRuntimeCapabilityAdapterCoordination(valid, deps).record; assert.deepEqual(projectNexoraDirectorRuntimeCapabilityAdapterHistory([record]), [record]); });
  it("83-89. snapshot comparison detects registry, adapter, primary, and assignment changes", () => { const empty = createNexoraDirectorRuntimeAdapterRegistry("2026-08-05T00:00:00.000Z", deps), full = registry(adapter()); const result = applyNexoraDirectorRuntimeCapabilityAdapterCoordination(request(full), deps); const leftState = freeze({ ...result.previousState, registryRevision: 0 }); const left = createNexoraDirectorRuntimeCapabilityAdapterSnapshot(empty, leftState, [], deps); const right = createNexoraDirectorRuntimeCapabilityAdapterSnapshot(full, result.nextState, result.plan.assignments, deps); const cmp = compareNexoraDirectorRuntimeCapabilityAdapterSnapshots(left, right); assert.equal(cmp.registryRevisionChanged, true); assert.deepEqual(cmp.addedAdapterIds, ["primary"]); assert.equal(cmp.primaryChanged, true); assert.equal(cmp.assignmentsChanged, true); });
  it("90-96. assignment and artifact validation rejects unsupported ownership and instances", () => { const reg = registry(adapter()); const badFallback: NexoraDirectorRuntimeAdapterAssignment = freeze({ assignmentId: "f", adapterId: "primary", role: "Fallback", capabilities: [], commandIds: [], priority: 1, active: true, degraded: false, reasons: [] }); assert.equal(validateNexoraDirectorRuntimeAdapterAssignments([badFallback], reg).valid, false); const observer = freeze({ ...badFallback, role: "Observer" as const, active: false, commandIds: ["x"] }); assert.equal(validateNexoraDirectorRuntimeAdapterAssignments([observer], reg).valid, false); class Adapter {} assert.equal(validateNexoraDirectorRuntimeAdapterDescriptor({ ...adapter(), metadata: { instance: new Adapter() } }).valid, false); const applied = applyNexoraDirectorRuntimeCapabilityAdapterCoordination(request(reg), deps); assert.equal(validateNexoraDirectorRuntimeAdapterRegistry(reg).valid, true); assert.equal(validateNexoraDirectorRuntimeCapabilityRequirementSet(applied.plan.requirements).valid, true); assert.equal(validateNexoraDirectorRuntimeCapabilityAdapterCoordinationState(applied.nextState).valid, true); assert.equal(validateNexoraDirectorRuntimeCapabilityAdapterCoordinationRequest(request(reg)).valid, true); assert.equal(validateNexoraDirectorRuntimeCapabilityAdapterCoordinationPlan(applied.plan).valid, true); assert.equal(validateNexoraDirectorRuntimeCapabilityAdapterCoordinationResult(applied).valid, true); assert.doesNotThrow(() => assertNexoraDirectorRuntimeCapabilityAdapterInvariants(applied)); assert.equal(isFrozen(applied), true); });
  it("97-106. serialization round-trips and no adapter execution or lower-layer mutation exists", () => { const descriptor = adapter(), reg = registry(descriptor), applied = applyNexoraDirectorRuntimeCapabilityAdapterCoordination(request(reg), deps), snapshot = createNexoraDirectorRuntimeCapabilityAdapterSnapshot(reg, applied.nextState, applied.plan.assignments, deps); assert.deepEqual(deserializeNexoraDirectorRuntimeAdapterDescriptor(serializeNexoraDirectorRuntimeAdapterDescriptor(descriptor)), descriptor); assert.deepEqual(deserializeNexoraDirectorRuntimeAdapterRegistry(serializeNexoraDirectorRuntimeAdapterRegistry(reg)), reg); assert.deepEqual(deserializeNexoraDirectorRuntimeCapabilityRequirementSet(serializeNexoraDirectorRuntimeCapabilityRequirementSet(applied.plan.requirements)), applied.plan.requirements); assert.deepEqual(deserializeNexoraDirectorRuntimeCapabilityAdapterCoordinationState(serializeNexoraDirectorRuntimeCapabilityAdapterCoordinationState(applied.nextState)), applied.nextState); assert.deepEqual(deserializeNexoraDirectorRuntimeCapabilityAdapterCoordinationPlan(serializeNexoraDirectorRuntimeCapabilityAdapterCoordinationPlan(applied.plan)), applied.plan); assert.deepEqual(deserializeNexoraDirectorRuntimeCapabilityAdapterRecord(serializeNexoraDirectorRuntimeCapabilityAdapterRecord(applied.record)), applied.record); assert.deepEqual(deserializeNexoraDirectorRuntimeCapabilityAdapterSnapshot(serializeNexoraDirectorRuntimeCapabilityAdapterSnapshot(snapshot)), snapshot); const envelope = JSON.parse(serializeNexoraDirectorRuntimeAdapterRegistry(reg)); envelope.schemaVersion = "2.0.0"; assert.throws(() => deserializeNexoraDirectorRuntimeAdapterRegistry(JSON.stringify(envelope)), /Unsupported/); assert.doesNotMatch(source, /\b(?:new\s+Adapter|loadPlugin|connect\s*\(|dispatch\s*\(|execute\s*\(|setTimeout|setInterval)\b/); assert.doesNotMatch(source, /from\s+["'](?:react|three|@react-three|[^"']*(?:webgl|webgpu|nol\/director|nol\/material))/i); });
});
