import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { describe, it } from "node:test";
import {
  assertNexoraDirectorRuntimeCertificationInvariants,
  certifyNexoraDirectorRuntime,
  certifyNexoraDirectorRuntimeBatch,
  compareNexoraDirectorRuntimeCertifications,
  createDefaultNexoraDirectorRuntimeCertificationPolicy,
  createNexoraDirectorRuntimeCertificationEvent,
  createPendingNexoraDirectorRuntimeCertification,
  deserializeNexoraDirectorRuntimeCertificationReport,
  deserializeNexoraDirectorRuntimeCertificationStamp,
  evaluateNexoraDirectorRuntimeCertificationCompatibility,
  evaluateNexoraDirectorRuntimeCertificationPolicy,
  expireNexoraDirectorRuntimeCertification,
  isNexoraDirectorRuntimeCertificationExpired,
  nexoraObjectDirectorRuntimeCertificationIdentity,
  projectNexoraDirectorRuntimeCertification,
  recertifyNexoraDirectorRuntime,
  restoreNexoraDirectorRuntimeCertification,
  revokeNexoraDirectorRuntimeCertification,
  serializeNexoraDirectorRuntimeCertificationReport,
  serializeNexoraDirectorRuntimeCertificationStamp,
  suspendNexoraDirectorRuntimeCertification,
  validateNexoraDirectorRuntimeCertificationHistory,
  validateNexoraDirectorRuntimeCertificationPolicy,
  validateNexoraDirectorRuntimeCertificationReport,
  validateNexoraDirectorRuntimeCertificationRequest,
  validateNexoraDirectorRuntimeCertificationStamp,
  type NexoraDirectorRuntimeCertificationDependencies,
  type NexoraDirectorRuntimeCertificationProfile,
  type NexoraDirectorRuntimeCertificationRequest,
} from "./nexoraObjectDirectorRuntimeCertification.ts";
import {
  nexoraObjectDirectorRuntimeValidationIntegrityEngineIdentity,
  type NexoraDirectorRuntimeValidationDomain,
  type NexoraDirectorRuntimeValidationError,
  type NexoraDirectorRuntimeValidationProfile,
  type NexoraDirectorRuntimeValidationReport,
} from "./nexoraObjectDirectorRuntimeValidationIntegrityEngine.ts";

function freeze<T>(value: T, seen = new Set<object>()): T { if (value === null || typeof value !== "object" || seen.has(value as object)) return value; seen.add(value as object); Object.values(value as Record<string, unknown>).forEach((child) => freeze(child, seen)); return Object.freeze(value); }
function frozen(value: unknown, seen = new Set<object>()): boolean { if (value === null || typeof value !== "object" || seen.has(value as object)) return true; if (!Object.isFrozen(value)) return false; seen.add(value as object); return Object.values(value as Record<string, unknown>).every((child) => frozen(child, seen)); }

const domains = ["Identity", "AdapterFoundation", "CommandExecution", "RuntimeState", "StateSynchronization", "Events", "Feedback", "Acknowledgments", "Capabilities", "AdapterRegistry", "Assignments", "Routing", "FailoverMigration", "Lifecycle", "Revisions", "Health", "Diagnostics", "Snapshots", "Serialization", "Compatibility", "Immutability", "Determinism", "RendererIndependence", "PublicSurface", "Composite"] as const satisfies readonly NexoraDirectorRuntimeValidationDomain[];
const thresholds: Record<NexoraDirectorRuntimeCertificationProfile, { validation: NexoraDirectorRuntimeValidationProfile; score: number; readiness: NexoraDirectorRuntimeValidationReport["releaseReadiness"] }> = { Development: { validation: "Minimal", score: 60, readiness: "DevelopmentReady" }, Testing: { validation: "Standard", score: 75, readiness: "TestingReady" }, Production: { validation: "Strict", score: 85, readiness: "ProductionReady" }, Platform: { validation: "Certification", score: 90, readiness: "PlatformReady" }, Release: { validation: "Certification", score: 95, readiness: "CertificationReady" } };
const deps: NexoraDirectorRuntimeCertificationDependencies = freeze({ now: () => "2035-01-01T00:00:00.000Z", createCertificationId: () => "cert-1", createReportId: () => "cert-report-1", createHistoryId: () => "history-1", createRequirementId: (name: string) => `req:${name}`, createEventId: () => "event-1" });
let validationSequence = 0;

function validation(profile: NexoraDirectorRuntimeCertificationProfile = "Release", overrides: Partial<NexoraDirectorRuntimeValidationReport> & { failedDomain?: NexoraDirectorRuntimeValidationDomain; errors?: readonly NexoraDirectorRuntimeValidationError[]; warnings?: readonly { code: "RUNTIME_VALIDATION_DEGRADED_ADAPTER_ACTIVE"; message: string; domain: NexoraDirectorRuntimeValidationDomain }[]; repairPriority?: number; validatorIdentity?: string } = {}): NexoraDirectorRuntimeValidationReport {
  const defaults = thresholds[profile], errors = overrides.errors ?? [], warnings = overrides.warnings ?? [], checkedDomains = overrides.result?.checkedDomains ?? domains, failedDomain = overrides.failedDomain;
  validationSequence += 1;
  const result = freeze({ valid: errors.length === 0, profile: overrides.profile ?? defaults.validation, score: overrides.integrityScore ?? defaults.score, checkedDomains, passedChecks: checkedDomains.map((domain, index) => freeze({ checkId: `check:${index}`, domain, name: domain, passed: domain !== failedDomain, weight: 1, message: domain === failedDomain ? "failed" : "passed" })), warnings, errors, repairSuggestions: overrides.repairPriority === undefined ? [] : [freeze({ suggestionId: "repair-1", type: "CorrectIdentity" as const, priority: overrides.repairPriority, domain: "Identity" as const, message: "review", automatic: false as const })], metrics: freeze({ totalChecks: checkedDomains.length, passedChecks: checkedDomains.length - (failedDomain ? 1 : 0), warningCount: warnings.length, errorCount: errors.length, repairSuggestionCount: overrides.repairPriority === undefined ? 0 : 1, validatedRuntimeObjectCount: 0, validatedCommandCount: 0, validatedEventCount: 0, validatedFeedbackCount: 0, validatedAdapterCount: 0, validatedAssignmentCount: 0, driftCount: 0, conflictCount: 0 }), validatorIdentity: overrides.validatorIdentity ?? nexoraObjectDirectorRuntimeValidationIntegrityEngineIdentity, createdAt: "2035-01-01T00:00:00.000Z", ...overrides.result });
  return freeze({ reportId: overrides.reportId ?? `validation-${validationSequence}`, requestId: overrides.requestId ?? `validation-request-${validationSequence}`, profile: overrides.profile ?? defaults.validation, valid: overrides.valid ?? result.valid, integrityScore: overrides.integrityScore ?? defaults.score, result, releaseReadiness: overrides.releaseReadiness ?? defaults.readiness, createdAt: "2035-01-01T00:00:00.000Z" });
}
function request(profile: NexoraDirectorRuntimeCertificationProfile = "Release", report = validation(profile), extra: Partial<NexoraDirectorRuntimeCertificationRequest> = {}): NexoraDirectorRuntimeCertificationRequest { return freeze({ requestId: `request-${profile}-${report.reportId}`, profile, validationReport: report, certifiedBy: "platform-authority", expiresAt: "2036-01-01T00:00:00.000Z", context: freeze({ source: profile === "Release" ? "Release" as const : "Validation" as const, correlationId: "correlation-1", causationId: "causation-1", occurredAt: "2035-01-01T00:00:00.000Z" }), ...extra }); }
const source = readFileSync(new URL("./nexoraObjectDirectorRuntimeCertification.ts", import.meta.url), "utf8");

describe("NOL-4:7 Director Runtime Certification", () => {
  it("1-3. exposes exact identity through the sole NOL-4:6 production dependency", () => { assert.equal(nexoraObjectDirectorRuntimeCertificationIdentity, "NOL-4:7/NexoraObjectDirectorRuntimeCertification"); const imports = [...source.matchAll(/from\s+["']([^"']+)["']/g)].map((match) => match[1]); assert.deepEqual([...new Set(imports)], ["./nexoraObjectDirectorRuntimeValidationIntegrityEngine.ts"]); assert.doesNotMatch(source, /from\s+["'][^"']*(?:AdapterFoundation|CommandExecution|StateSynchronization|EventFeedback|CapabilityAdapter)/); });
  it("4-14. default policies and non-bypassable profile thresholds are deterministic", () => { for (const profile of Object.keys(thresholds) as NexoraDirectorRuntimeCertificationProfile[]) { const left = createDefaultNexoraDirectorRuntimeCertificationPolicy(profile), right = createDefaultNexoraDirectorRuntimeCertificationPolicy(profile); assert.deepEqual(left, right); assert.equal(left.minimumIntegrityScore, thresholds[profile].score); const low = validation(profile, { integrityScore: thresholds[profile].score - 1 }); assert.equal(certifyNexoraDirectorRuntime(request(profile, low), deps).accepted, false); } const release = createDefaultNexoraDirectorRuntimeCertificationPolicy("Release"); const lowered = freeze({ ...release, minimumIntegrityScore: 1 }); const insufficient = validation("Release", { releaseReadiness: "PlatformReady" }); assert.equal(certifyNexoraDirectorRuntime(request("Release", insufficient, { policy: lowered }), deps).accepted, false); });
  it("15-19. valid evidence certifies every trust profile", () => { for (const profile of Object.keys(thresholds) as NexoraDirectorRuntimeCertificationProfile[]) { const report = certifyNexoraDirectorRuntime(request(profile), deps); assert.equal(report.accepted, true, profile); assert.equal(report.status, "Certified"); assert.equal(frozen(report), true); } });
  it("20-37. policy evaluation rejects each unsafe NOL-4:6 evidence condition", () => { const invalidError = freeze({ code: "RUNTIME_VALIDATION_INVALID_COMMAND" as const, domain: "CommandExecution" as const, message: "invalid" }); const cases: readonly [NexoraDirectorRuntimeCertificationProfile, NexoraDirectorRuntimeValidationReport, string][] = [
    ["Development", validation("Development", { valid: false, errors: [invalidError] }), "RUNTIME_CERT_VALIDATION_REPORT_INVALID"],
    ["Testing", validation("Testing", { profile: "Minimal" }), "RUNTIME_CERT_VALIDATION_PROFILE_INSUFFICIENT"],
    ["Production", validation("Production", { releaseReadiness: "TestingReady" }), "RUNTIME_CERT_RELEASE_READINESS_INSUFFICIENT"],
    ["Production", validation("Production", { integrityScore: 84 }), "RUNTIME_CERT_INTEGRITY_SCORE_TOO_LOW"],
    ["Production", validation("Production", { errors: [invalidError] }), "RUNTIME_CERT_BLOCKING_VALIDATION_ERROR"],
    ["Testing", validation("Testing", { result: { checkedDomains: domains.filter((item) => item !== "Serialization") } as never }), "RUNTIME_CERT_REQUIRED_DOMAIN_MISSING"],
    ["Release", validation("Release", { failedDomain: "RendererIndependence" }), "RUNTIME_CERT_RENDERER_INDEPENDENCE_FAILED"],
    ["Release", validation("Release", { failedDomain: "Immutability" }), "RUNTIME_CERT_IMMUTABILITY_FAILED"],
    ["Release", validation("Release", { failedDomain: "Determinism" }), "RUNTIME_CERT_DETERMINISM_FAILED"],
    ["Release", validation("Release", { failedDomain: "Serialization" }), "RUNTIME_CERT_SERIALIZATION_FAILED"],
    ["Release", validation("Release", { failedDomain: "Identity" }), "RUNTIME_CERT_IDENTITY_CHAIN_FAILED"],
    ["Release", validation("Release", { failedDomain: "Revisions" }), "RUNTIME_CERT_REVISION_CHAIN_FAILED"],
    ["Production", validation("Production", { failedDomain: "Capabilities" }), "RUNTIME_CERT_REQUIRED_CAPABILITY_UNAVAILABLE"],
    ["Production", validation("Production", { failedDomain: "Health" }), "RUNTIME_CERT_RUNTIME_HEALTH_UNACCEPTABLE"],
    ["Production", validation("Production", { failedDomain: "Assignments" }), "RUNTIME_CERT_ADAPTER_ASSIGNMENT_INVALID"],
    ["Release", validation("Release", { repairPriority: 100 }), "RUNTIME_CERT_CRITICAL_REPAIR_UNRESOLVED"],
  ]; for (const [profile, evidence, code] of cases) assert.equal(certifyNexoraDirectorRuntime(request(profile, evidence), deps).errors.some((item) => item.code === code), true, code); const degraded = validation("Release", { warnings: [freeze({ code: "RUNTIME_VALIDATION_DEGRADED_ADAPTER_ACTIVE", message: "degraded", domain: "AdapterRegistry" })] }); assert.equal(evaluateNexoraDirectorRuntimeCertificationCompatibility(degraded), "Degraded"); assert.equal(certifyNexoraDirectorRuntime(request("Release", degraded), deps).accepted, false); const productionDegraded = certifyNexoraDirectorRuntime(request("Production", validation("Production", { warnings: [freeze({ code: "RUNTIME_VALIDATION_DEGRADED_ADAPTER_ACTIVE", message: "degraded", domain: "Health" })] })), deps); assert.equal(productionDegraded.accepted, true); });
  it("38-47. pending, accepted, and rejected reports preserve exact evidence immutably", () => { const input = request("Release"), before = JSON.stringify(input.validationReport), pending = createPendingNexoraDirectorRuntimeCertification(input, deps), certified = certifyNexoraDirectorRuntime(input, deps); assert.equal(pending.status, "Pending"); assert.equal(pending.stamp, undefined); assert.deepEqual(pending.history.map((entry) => [entry.previousStatus, entry.nextStatus]), [["NotCertified", "Pending"]]); assert.equal(certified.status, "Certified"); assert.equal(certified.stamp?.validationReportId, input.validationReport.reportId); assert.equal(certified.stamp?.integrityScore, input.validationReport.integrityScore); assert.equal(certified.stamp?.validationReadiness, input.validationReport.releaseReadiness); assert.equal(frozen(certified.stamp), true); const rejected = certifyNexoraDirectorRuntime(request("Release", validation("Release", { integrityScore: 1 })), deps); assert.equal(rejected.status, "NotCertified"); assert.equal(rejected.stamp, undefined); assert.equal(JSON.stringify(input.validationReport), before); });
  it("48-68. recertification, suspension, restoration, expiration, revocation, and history obey lifecycle", () => { const certified = certifyNexoraDirectorRuntime(request("Release"), deps); assert.equal(recertifyNexoraDirectorRuntime(certified, request("Release", certified.validationReport), deps).errors.at(-1)?.code, "RUNTIME_CERT_NEW_VALIDATION_REQUIRED"); const suspended = suspendNexoraDirectorRuntimeCertification(certified, "policy hold", "authority", deps); assert.equal(suspended.status, "Suspended"); assert.equal(projectNexoraDirectorRuntimeCertification(suspended, "Release"), undefined); assert.equal(suspendNexoraDirectorRuntimeCertification(suspended, "again", "authority", deps).errors.at(-1)?.code, "RUNTIME_CERT_ALREADY_SUSPENDED"); const replacement = request("Release", validation("Release")); const restored = restoreNexoraDirectorRuntimeCertification(suspended, replacement, deps); assert.equal(restored.status, "Certified"); assert.notEqual(restored.stamp, certified.stamp); assert.equal(restored.history.length, suspended.history.length + 1); const expired = expireNexoraDirectorRuntimeCertification(certified, "expired", "authority", deps); assert.equal(expired.status, "Expired"); assert.equal(expired.history.length, certified.history.length + 1); assert.equal(isNexoraDirectorRuntimeCertificationExpired(certified, "2037-01-01T00:00:00.000Z"), true); const recertified = recertifyNexoraDirectorRuntime(expired, replacement, deps); assert.equal(recertified.status, "Certified"); assert.equal(recertified.history.length, expired.history.length + 2); const revoked = revokeNexoraDirectorRuntimeCertification(certified, "manual platform revocation", "authority", deps); assert.equal(revoked.status, "Revoked"); assert.equal(revoked.history.length, certified.history.length + 1); assert.equal(revoked.stamp?.status, "Revoked"); assert.equal(revokeNexoraDirectorRuntimeCertification(revoked, "again", "authority", deps).errors.at(-1)?.code, "RUNTIME_CERT_ALREADY_REVOKED"); assert.equal(restoreNexoraDirectorRuntimeCertification(revoked, replacement, deps).errors.at(-1)?.code, "RUNTIME_CERT_REVOKED_TERMINAL"); assert.equal(recertifyNexoraDirectorRuntime(revoked, replacement, deps).errors.at(-1)?.code, "RUNTIME_CERT_REVOKED_TERMINAL"); assert.equal(validateNexoraDirectorRuntimeCertificationHistory(restored.history).valid, true); const invalidHistory = freeze([{ ...certified.history[0]!, previousStatus: "Revoked" as const, nextStatus: "Certified" as const }]); assert.equal(validateNexoraDirectorRuntimeCertificationHistory(invalidHistory).valid, false); assert.equal(frozen(certified.history), true); });
  it("69-79. comparisons and safe projections expose deterministic trust evidence", () => { const development = certifyNexoraDirectorRuntime(request("Development"), deps), release = certifyNexoraDirectorRuntime(request("Release"), deps), suspended = suspendNexoraDirectorRuntimeCertification(release, "hold", "authority", deps), difference = compareNexoraDirectorRuntimeCertifications(development, suspended); assert.equal(difference.profileChanged, true); assert.equal(difference.statusChanged, true); assert.notEqual(difference.scoreChange, 0); assert.equal(difference.readinessChanged, true); assert.equal(difference.validationReportChanged, true); assert.equal(difference.addedWarningCodes.length >= 0, true); assert.equal(difference.addedErrorCodes.length >= 0, true); const consumer = projectNexoraDirectorRuntimeCertification(release, "Consumer")!; assert.equal(consumer.certificationId, release.certificationId); const platform = projectNexoraDirectorRuntimeCertification(release, "Platform")!; assert.equal(platform.policyId, release.policy.policyId); assert.equal(projectNexoraDirectorRuntimeCertification(development, "Release"), undefined); assert.equal(frozen(projectNexoraDirectorRuntimeCertification(release, "Release")), true); assert.equal(Array.isArray(projectNexoraDirectorRuntimeCertification(release, "Diagnostics")!.requirements), true); });
  it("80-88. compatibility, batches, and local events preserve deterministic order and causation", () => { const supported = validation("Release"); assert.equal(evaluateNexoraDirectorRuntimeCertificationCompatibility(supported), "Compatible"); assert.equal(evaluateNexoraDirectorRuntimeCertificationCompatibility(validation("Release", { warnings: [freeze({ code: "RUNTIME_VALIDATION_DEGRADED_ADAPTER_ACTIVE", message: "degraded", domain: "Health" })] })), "Degraded"); assert.equal(evaluateNexoraDirectorRuntimeCertificationCompatibility(validation("Release", { validatorIdentity: "unknown" })), "Incompatible"); const good = request("Release"), bad = request("Release", validation("Release", { integrityScore: 1 })); const atomic = certifyNexoraDirectorRuntimeBatch({ requests: [good, bad], mode: "Atomic" }, deps); assert.deepEqual(atomic.certifiedRequestIds, []); const best = certifyNexoraDirectorRuntimeBatch({ requests: [good, bad], mode: "BestEffort" }, deps); assert.deepEqual(best.certifiedRequestIds, [good.requestId]); assert.deepEqual(best.reports.map((report) => report.requestId), [good.requestId, bad.requestId]); assert.equal(certifyNexoraDirectorRuntimeBatch({ requests: [good, good], mode: "Atomic" }, deps).accepted, false); const sameCertification = [request("Development", validation("Development"), { certificationId: "same" }), request("Testing", validation("Testing"), { certificationId: "same" })]; assert.equal(certifyNexoraDirectorRuntimeBatch({ requests: sameCertification, mode: "BestEffort" }, deps).accepted, false); const report = certifyNexoraDirectorRuntime(good, deps), event = createNexoraDirectorRuntimeCertificationEvent(report, "CertificationAccepted", good.context!, deps); assert.equal(event.correlationId, "correlation-1"); assert.equal(event.causationId, "causation-1"); assert.equal(frozen(event), true); });
  it("89-97. validators and invariants reject corrupt policies, stamps, reports, histories, and resources", () => { const policy = createDefaultNexoraDirectorRuntimeCertificationPolicy("Release"); assert.equal(validateNexoraDirectorRuntimeCertificationPolicy(freeze({ ...policy, minimumIntegrityScore: -1 })).valid, false); assert.equal(validateNexoraDirectorRuntimeCertificationPolicy(freeze({ ...policy, requiredDomains: [] })).valid, false); const cert = certifyNexoraDirectorRuntime(request("Release"), deps); assert.equal(validateNexoraDirectorRuntimeCertificationRequest(request("Release")).valid, true); assert.equal(validateNexoraDirectorRuntimeCertificationStamp(freeze({ ...cert.stamp!, validationReportId: "wrong" }), cert.validationReport).valid, false); assert.equal(validateNexoraDirectorRuntimeCertificationStamp(freeze({ ...cert.stamp!, validationReadiness: "PlatformReady" }), cert.validationReport).valid, false); assert.equal(validateNexoraDirectorRuntimeCertificationReport(freeze({ ...cert, stamp: undefined })).valid, false); assert.equal(validateNexoraDirectorRuntimeCertificationReport(freeze({ ...cert, accepted: false })).valid, false); assert.equal(validateNexoraDirectorRuntimeCertificationHistory([...cert.history]).valid, false); class Mesh {} assert.equal(validateNexoraDirectorRuntimeCertificationReport(freeze({ ...cert, warnings: [freeze({ ...cert.warnings[0], details: new Mesh() })] }) as never).valid, false); assert.doesNotThrow(() => assertNexoraDirectorRuntimeCertificationInvariants(cert)); assert.equal(frozen(cert.policy) && frozen(cert.history) && frozen(cert.stamp), true); });
  it("98-101. versioned stamp and report serialization is reversible and resource-safe", () => { const report = certifyNexoraDirectorRuntime(request("Release"), deps), stampJson = serializeNexoraDirectorRuntimeCertificationStamp(report.stamp!), reportJson = serializeNexoraDirectorRuntimeCertificationReport(report), stamp = deserializeNexoraDirectorRuntimeCertificationStamp(stampJson), restored = deserializeNexoraDirectorRuntimeCertificationReport(reportJson); assert.deepEqual(stamp, report.stamp); assert.deepEqual(restored, report); assert.equal(serializeNexoraDirectorRuntimeCertificationReport(restored), reportJson); const envelope = JSON.parse(reportJson); envelope.schemaVersion = "2.0.0"; assert.throws(() => deserializeNexoraDirectorRuntimeCertificationReport(JSON.stringify(envelope)), /Unsupported/); assert.doesNotMatch(reportJson, /"(?:callback|connection|renderer|function)"\s*:/i); });
  it("102-110. certification executes nothing, mutates no validation input, and remains framework independent", () => { const input = request("Release"), before = JSON.stringify(input.validationReport); certifyNexoraDirectorRuntime(input, deps); assert.equal(JSON.stringify(input.validationReport), before); assert.doesNotMatch(source, /\b(?:executeRuntimeCommand|retryRuntimeCommand|cancelRuntimeCommand|applyRuntimeRollback|synchronizeRuntimeState|dispatchEvent|acknowledgeRuntimeFeedback|routeRuntimeCommand|activateFallback|executeFailover|executeMigration|persistCertification)\s*\(/); assert.doesNotMatch(source, /from\s+["'][^"']*(?:react|next|three|webgl|webgpu|workspace|advisor|timeline|scenario|database|plugin|event-bus)/i); assert.equal(source.includes("assertNexoraDirectorRuntimeValidationInvariants"), true); assert.equal(source.includes("calculateNexoraDirectorRuntimeIntegrityScore"), false); assert.equal(source.includes("validateExecutionQueue"), false); });
  it("canonical evaluation is deterministic and immutable", () => { const evidence = validation("Release"), policy = createDefaultNexoraDirectorRuntimeCertificationPolicy("Release"), first = evaluateNexoraDirectorRuntimeCertificationPolicy(evidence, policy, { source: "Release" }, deps), second = evaluateNexoraDirectorRuntimeCertificationPolicy(evidence, policy, { source: "Release" }, deps); assert.deepEqual(first, second); assert.equal(first.requirements.length, 20); assert.equal(frozen(first), true); });
});
