/** NOL-4:4 — semantic runtime event and feedback coordination. */
import { validateDirectorRuntimeAdapter, type NexoraDirectorRuntimeAdapterContext, type NexoraDirectorRuntimeRequestMode } from "./nexoraObjectDirectorRuntimeAdapterFoundation.ts";
import { validateExecutionReport, type NexoraDirectorRuntimeExecutionReport } from "./nexoraObjectDirectorRuntimeCommandExecutionModel.ts";
import { validateNexoraDirectorRuntimeState, validateNexoraDirectorRuntimeStateSynchronizationResult, type NexoraDirectorRuntimeState, type NexoraDirectorRuntimeStateSynchronizationResult } from "./nexoraObjectDirectorRuntimeStateSynchronizationEngine.ts";

export * from "./nexoraObjectDirectorRuntimeStateSynchronizationEngine.ts";

export const nexoraObjectDirectorRuntimeEventFeedbackCoordinationEngineIdentity = "NOL-4:4/NexoraObjectDirectorRuntimeEventFeedbackCoordinationEngine" as const;
export const nexoraObjectDirectorRuntimeEventFeedbackCoordinationEngineVersion = "1.0.0" as const;
export const nexoraObjectDirectorRuntimeEventFeedbackCoordinationSchemaVersion = "1.0.0" as const;

export type NexoraDirectorRuntimeEventType = "RuntimeInitialized" | "RuntimeReady" | "RuntimeBusy" | "RuntimePaused" | "RuntimeStopped" | "RuntimeFailed" | "CommandQueued" | "CommandStarted" | "CommandCompleted" | "CommandFailed" | "CommandCancelled" | "CommandRetried" | "CommandRolledBack" | "RuntimeStateChanged" | "RuntimeObjectCreated" | "RuntimeObjectUpdated" | "RuntimeObjectReused" | "RuntimeObjectShown" | "RuntimeObjectHidden" | "RuntimeObjectDetached" | "RuntimeObjectRemoved" | "RuntimeObjectFailed" | "RuntimeFocusChanged" | "RuntimeCameraChanged" | "RuntimeAttentionChanged" | "RuntimeHealthChanged" | "RuntimeDriftDetected" | "RuntimeCapabilityDegraded" | "RuntimeDiagnostic";
export type NexoraDirectorRuntimeEventSource = "RuntimeAdapter" | "ExecutionModel" | "StateSynchronization" | "DirectorRuntime" | "RendererAdapter" | "Diagnostics" | "System";
export interface NexoraDirectorRuntimeEvent { readonly eventId: string; readonly eventType: NexoraDirectorRuntimeEventType; readonly runtimeId: string; readonly runtimeRevision: number; readonly objectId?: string; readonly runtimeObjectId?: string; readonly commandId?: string; readonly executionId?: string; readonly synchronizationId?: string; readonly source: NexoraDirectorRuntimeEventSource; readonly priority: number; readonly occurredAt: string; readonly correlationId?: string; readonly causationId?: string; readonly payload: Readonly<Record<string, unknown>>; }
export type NexoraDirectorRuntimeFeedbackType = "Accepted" | "Applied" | "Completed" | "Rejected" | "Failed" | "Cancelled" | "TimedOut" | "Skipped" | "Retried" | "RolledBack" | "Degraded" | "Unsupported" | "Acknowledged" | "Diagnostic";
export type NexoraDirectorRuntimeFeedbackSeverity = "Info" | "Notice" | "Warning" | "Error" | "Critical";
export type NexoraDirectorRuntimeFeedbackSource = "DirectorRuntime" | "RendererAdapter" | "ExecutionModel" | "StateSynchronization" | "Diagnostics" | "System";
export interface NexoraDirectorRuntimeFeedback { readonly feedbackId: string; readonly feedbackType: NexoraDirectorRuntimeFeedbackType; readonly severity: NexoraDirectorRuntimeFeedbackSeverity; readonly runtimeId: string; readonly runtimeRevision: number; readonly objectId?: string; readonly runtimeObjectId?: string; readonly commandId?: string; readonly executionId?: string; readonly synchronizationId?: string; readonly source: NexoraDirectorRuntimeFeedbackSource; readonly message: string; readonly retryable: boolean; readonly recoverable: boolean; readonly requiresAcknowledgment: boolean; readonly occurredAt: string; readonly correlationId?: string; readonly causationId?: string; readonly payload: Readonly<Record<string, unknown>>; }
export type NexoraDirectorRuntimeFeedbackClassification = "Success" | "TransientFailure" | "PermanentFailure" | "PartialSuccess" | "CapabilityDegradation" | "SynchronizationDrift" | "UserAcknowledgmentRequired" | "DiagnosticOnly";
export type NexoraDirectorRuntimeFeedbackAcknowledgmentState = "NotRequired" | "Pending" | "Acknowledged" | "Dismissed" | "Expired";
export interface NexoraDirectorRuntimeFeedbackAcknowledgment { readonly feedbackId: string; readonly state: NexoraDirectorRuntimeFeedbackAcknowledgmentState; readonly acknowledgedBy?: string; readonly acknowledgedAt?: string; readonly reason?: string; }
export interface NexoraDirectorRuntimeEventFeedbackContext { readonly runtimeContext: NexoraDirectorRuntimeAdapterContext; readonly runtimeState: NexoraDirectorRuntimeState; readonly executionReport?: NexoraDirectorRuntimeExecutionReport; readonly synchronizationResult?: NexoraDirectorRuntimeStateSynchronizationResult; readonly previousCoordinationState?: NexoraDirectorRuntimeEventFeedbackState; readonly source: "RuntimeAdapter" | "DirectorRuntime" | "RendererAdapter" | "Diagnostics" | "System"; readonly mode: NexoraDirectorRuntimeRequestMode; readonly occurredAt?: string; readonly deduplicationWindowMs?: number; readonly staleEventToleranceMs?: number; readonly strictCorrelation?: boolean; }
export interface NexoraDirectorRuntimeEventFeedbackState { readonly stateId: string; readonly runtimeId: string; readonly revision: number; readonly status: "Idle" | "Coordinating" | "Ready" | "Completed" | "PartiallyCompleted" | "Failed"; readonly pendingEventIds: readonly string[]; readonly processedEventIds: readonly string[]; readonly suppressedEventIds: readonly string[]; readonly pendingFeedbackIds: readonly string[]; readonly acknowledgedFeedbackIds: readonly string[]; readonly activeCorrelationIds: readonly string[]; readonly updatedAt: string; }
export interface NexoraDirectorRuntimeStaleEvent { readonly eventId: string; readonly reason: "OlderRuntimeRevision" | "OlderExecution" | "OlderSynchronization" | "ExpiredTimestamp" | "SupersededByRollback" | "ObjectAlreadyRemoved"; readonly recoverable: boolean; }
export interface NexoraDirectorRuntimeFeedbackConflict { readonly conflictId: string; readonly feedbackIds: readonly string[]; readonly type: "SuccessAndFailure" | "CompletedAndCancelled" | "AppliedAndRolledBack" | "RevisionMismatch" | "AcknowledgmentConflict" | "CapabilityConflict"; readonly recoverable: boolean; readonly message: string; }
export type NexoraDirectorRuntimeFeedbackActionType = "NoAction" | "Acknowledge" | "RetryCommand" | "CancelCommand" | "PlanRollback" | "RequestResynchronization" | "DegradeRuntimeHealth" | "MarkRuntimeUnavailable" | "PreservePreviousState" | "EmitDiagnostic" | "EscalateToSystem";
export interface NexoraDirectorRuntimeFeedbackAction { readonly actionId: string; readonly feedbackId: string; readonly type: NexoraDirectorRuntimeFeedbackActionType; readonly priority: number; readonly objectId?: string; readonly runtimeObjectId?: string; readonly commandId?: string; readonly executionId?: string; readonly synchronizationId?: string; readonly target: "RuntimeAdapter" | "ExecutionModel" | "StateSynchronization" | "Diagnostics" | "System" | "User"; readonly reversible: boolean; readonly payload: Readonly<Record<string, unknown>>; }
export interface NexoraDirectorRuntimeCorrelationGroup { readonly correlationId: string; readonly eventIds: readonly string[]; readonly feedbackIds: readonly string[]; readonly commandIds: readonly string[]; readonly executionIds: readonly string[]; readonly synchronizationIds: readonly string[]; readonly objectIds: readonly string[]; }
export interface NexoraDirectorRuntimeEventQueue { readonly events: readonly NexoraDirectorRuntimeEvent[]; }
export interface NexoraDirectorRuntimeFeedbackQueue { readonly feedback: readonly NexoraDirectorRuntimeFeedback[]; }
export interface NexoraDirectorRuntimeEventFeedbackRequest { readonly requestId: string; readonly events: readonly NexoraDirectorRuntimeEvent[]; readonly feedback: readonly NexoraDirectorRuntimeFeedback[]; readonly acknowledgments?: readonly NexoraDirectorRuntimeFeedbackAcknowledgment[]; readonly context: NexoraDirectorRuntimeEventFeedbackContext; readonly expectedCoordinationRevision?: number; }
export type NexoraDirectorRuntimeEventFeedbackWarningCode = "RUNTIME_FEEDBACK_DUPLICATE_EVENT_SUPPRESSED" | "RUNTIME_FEEDBACK_DUPLICATE_FEEDBACK_SUPPRESSED" | "RUNTIME_FEEDBACK_STALE_EVENT_IGNORED" | "RUNTIME_FEEDBACK_PARTIAL_COORDINATION" | "RUNTIME_FEEDBACK_RETRY_RECOMMENDED" | "RUNTIME_FEEDBACK_RESYNCHRONIZATION_RECOMMENDED" | "RUNTIME_FEEDBACK_ACKNOWLEDGMENT_REQUIRED" | "RUNTIME_FEEDBACK_CAPABILITY_DEGRADED" | "RUNTIME_FEEDBACK_NO_ACTION_REQUIRED";
export interface NexoraDirectorRuntimeEventFeedbackWarning { readonly code: NexoraDirectorRuntimeEventFeedbackWarningCode; readonly message: string; readonly requestId?: string; readonly eventId?: string; readonly feedbackId?: string; readonly commandId?: string; readonly objectId?: string; readonly details?: Readonly<Record<string, unknown>>; }
export type NexoraDirectorRuntimeEventFeedbackErrorCode = "RUNTIME_FEEDBACK_INVALID_REQUEST" | "RUNTIME_FEEDBACK_RUNTIME_ID_MISMATCH" | "RUNTIME_FEEDBACK_INVALID_EVENT" | "RUNTIME_FEEDBACK_INVALID_FEEDBACK" | "RUNTIME_FEEDBACK_DUPLICATE_EVENT_ID" | "RUNTIME_FEEDBACK_DUPLICATE_FEEDBACK_ID" | "RUNTIME_FEEDBACK_DUPLICATE_REQUEST_ID" | "RUNTIME_FEEDBACK_INVALID_TIMESTAMP" | "RUNTIME_FEEDBACK_INVALID_PRIORITY" | "RUNTIME_FEEDBACK_INVALID_REVISION" | "RUNTIME_FEEDBACK_MISSING_COMMAND_REFERENCE" | "RUNTIME_FEEDBACK_MISSING_EXECUTION_REFERENCE" | "RUNTIME_FEEDBACK_MISSING_SYNCHRONIZATION_REFERENCE" | "RUNTIME_FEEDBACK_CORRELATION_CONFLICT" | "RUNTIME_FEEDBACK_UNRESOLVED_CONFLICT" | "RUNTIME_FEEDBACK_INVALID_ACKNOWLEDGMENT" | "RUNTIME_FEEDBACK_DUPLICATE_ACKNOWLEDGMENT" | "RUNTIME_FEEDBACK_COORDINATION_REVISION_CONFLICT" | "RUNTIME_FEEDBACK_ATOMIC_REJECTED" | "RUNTIME_FEEDBACK_ACTION_INVALID" | "RUNTIME_FEEDBACK_RENDERER_OBJECT_FORBIDDEN" | "RUNTIME_FEEDBACK_INVARIANT_VIOLATION" | "RUNTIME_FEEDBACK_UNSUPPORTED_VERSION";
export interface NexoraDirectorRuntimeEventFeedbackError { readonly code: NexoraDirectorRuntimeEventFeedbackErrorCode; readonly message: string; readonly requestId?: string; readonly eventId?: string; readonly feedbackId?: string; readonly actionId?: string; readonly runtimeId?: string; readonly objectId?: string; readonly commandId?: string; readonly details?: Readonly<Record<string, unknown>>; }
export interface NexoraDirectorRuntimeEventFeedbackPlan { readonly requestId: string; readonly accepted: boolean; readonly changed: boolean; readonly noOp: boolean; readonly mode: NexoraDirectorRuntimeRequestMode; readonly previousState: NexoraDirectorRuntimeEventFeedbackState; readonly projectedState: NexoraDirectorRuntimeEventFeedbackState; readonly normalizedEvents: readonly NexoraDirectorRuntimeEvent[]; readonly normalizedFeedback: readonly NexoraDirectorRuntimeFeedback[]; readonly staleEvents: readonly NexoraDirectorRuntimeStaleEvent[]; readonly conflicts: readonly NexoraDirectorRuntimeFeedbackConflict[]; readonly correlations: readonly NexoraDirectorRuntimeCorrelationGroup[]; readonly actions: readonly NexoraDirectorRuntimeFeedbackAction[]; readonly warnings: readonly NexoraDirectorRuntimeEventFeedbackWarning[]; readonly errors: readonly NexoraDirectorRuntimeEventFeedbackError[]; }
export interface NexoraDirectorRuntimeEventRecord { readonly recordId: string; readonly eventId: string; readonly runtimeId: string; readonly eventType: NexoraDirectorRuntimeEventType; readonly priority: number; readonly stale: boolean; readonly suppressed: boolean; readonly processedAt: string; readonly correlationId?: string; readonly causationId?: string; }
export interface NexoraDirectorRuntimeFeedbackRecord { readonly recordId: string; readonly feedbackId: string; readonly runtimeId: string; readonly classification: NexoraDirectorRuntimeFeedbackClassification; readonly severity: NexoraDirectorRuntimeFeedbackSeverity; readonly acknowledgmentState: NexoraDirectorRuntimeFeedbackAcknowledgmentState; readonly actionIds: readonly string[]; readonly processedAt: string; }
export interface NexoraDirectorRuntimeEventFeedbackResult { readonly accepted: boolean; readonly changed: boolean; readonly simulated: boolean; readonly previousState: NexoraDirectorRuntimeEventFeedbackState; readonly nextState: NexoraDirectorRuntimeEventFeedbackState; readonly plan: NexoraDirectorRuntimeEventFeedbackPlan; readonly eventRecords: readonly NexoraDirectorRuntimeEventRecord[]; readonly feedbackRecords: readonly NexoraDirectorRuntimeFeedbackRecord[]; readonly warnings: readonly NexoraDirectorRuntimeEventFeedbackWarning[]; readonly errors: readonly NexoraDirectorRuntimeEventFeedbackError[]; }
export interface NexoraDirectorRuntimeFeedbackAggregate { readonly aggregateId: string; readonly key: string; readonly feedbackIds: readonly string[]; readonly highestSeverity: NexoraDirectorRuntimeFeedbackSeverity; readonly successCount: number; readonly failureCount: number; readonly retryableCount: number; readonly acknowledgmentRequiredCount: number; }
export interface NexoraDirectorRuntimeFeedbackWindow { readonly windowId: string; readonly startedAt: string; readonly endedAt: string; readonly eventIds: readonly string[]; readonly feedbackIds: readonly string[]; readonly aggregateIds: readonly string[]; }
export interface NexoraDirectorRuntimeEventFeedbackBatchRequest { readonly requests: readonly NexoraDirectorRuntimeEventFeedbackRequest[]; readonly mode: "Atomic" | "BestEffort"; }
export interface NexoraDirectorRuntimeEventFeedbackBatchResult { readonly accepted: boolean; readonly results: readonly NexoraDirectorRuntimeEventFeedbackResult[]; readonly acceptedRequestIds: readonly string[]; readonly rejectedRequestIds: readonly string[]; readonly finalState: NexoraDirectorRuntimeEventFeedbackState; }
export interface NexoraDirectorRuntimeEventFeedbackSequenceResult { readonly plans: readonly NexoraDirectorRuntimeEventFeedbackPlan[]; readonly results: readonly NexoraDirectorRuntimeEventFeedbackResult[]; readonly firstFailureRequestId?: string; readonly finalProjectedState: NexoraDirectorRuntimeEventFeedbackState; }
export interface NexoraDirectorRuntimeEventFeedbackSnapshot { readonly snapshotId: string; readonly state: NexoraDirectorRuntimeEventFeedbackState; readonly eventQueue: NexoraDirectorRuntimeEventQueue; readonly feedbackQueue: NexoraDirectorRuntimeFeedbackQueue; readonly acknowledgments: readonly NexoraDirectorRuntimeFeedbackAcknowledgment[]; readonly createdAt: string; }
export interface NexoraDirectorRuntimeEventFeedbackSnapshotComparison { readonly equal: boolean; readonly revisionChanged: boolean; readonly pendingEventsChanged: boolean; readonly processedEventsChanged: boolean; readonly feedbackChanged: boolean; readonly acknowledgmentsChanged: boolean; readonly correlationsChanged: boolean; readonly conflictsChanged: boolean; readonly actionsChanged: boolean; }
export interface NexoraDirectorRuntimeFeedbackWindowComparison { readonly equal: boolean; readonly rangeChanged: boolean; readonly eventsChanged: boolean; readonly feedbackChanged: boolean; readonly aggregatesChanged: boolean; }
export interface NexoraDirectorRuntimeEventDeduplication { readonly events: readonly NexoraDirectorRuntimeEvent[]; readonly suppressedEvents: readonly NexoraDirectorRuntimeEvent[]; }
export interface NexoraDirectorRuntimeFeedbackDeduplication { readonly feedback: readonly NexoraDirectorRuntimeFeedback[]; readonly suppressedFeedback: readonly NexoraDirectorRuntimeFeedback[]; }
export interface NexoraDirectorRuntimeEventFeedbackValidationResult { readonly valid: boolean; readonly errors: readonly NexoraDirectorRuntimeEventFeedbackError[]; readonly warnings: readonly NexoraDirectorRuntimeEventFeedbackWarning[]; }
export interface NexoraDirectorRuntimeEventFeedbackDependencies { readonly now: () => string; readonly createStateId: () => string; readonly createActionId: (feedbackId: string, type: NexoraDirectorRuntimeFeedbackActionType) => string; readonly createConflictId: (feedbackIds: readonly string[]) => string; readonly createRecordId: () => string; readonly createAggregateId: (key: string) => string; readonly createWindowId: () => string; readonly createSnapshotId: () => string; }

export class NexoraObjectDirectorRuntimeEventFeedbackCoordinationException extends Error { constructor(message: string) { super(message); this.name = "NexoraObjectDirectorRuntimeEventFeedbackCoordinationException"; } }
function freeze<T>(value: T, seen = new Set<object>()): T { if (value === null || typeof value !== "object" || seen.has(value as object)) return value; seen.add(value as object); Object.values(value as Record<string, unknown>).forEach((x) => freeze(x, seen)); return Object.isFrozen(value) ? value : Object.freeze(value); }
function copy<T>(value: T): T { return freeze(structuredClone(value)); }
function rec(value: unknown): value is Record<string, unknown> { return value !== null && typeof value === "object" && !Array.isArray(value); }
function frozen(value: unknown, seen = new Set<object>()): boolean { if (value === null || typeof value !== "object" || seen.has(value as object)) return true; if (!Object.isFrozen(value)) return false; seen.add(value as object); return Object.values(value as Record<string, unknown>).every((x) => frozen(x, seen)); }
function stable(value: unknown): string { if (Array.isArray(value)) return `[${value.map(stable).join(",")}]`; if (rec(value)) return `{${Object.keys(value).sort().map((k) => `${JSON.stringify(k)}:${stable(value[k])}`).join(",")}}`; return JSON.stringify(value); }
function renderer(value: unknown, seen = new Set<object>()): boolean { if (typeof value === "function") return true; if (value === null || typeof value !== "object" || seen.has(value as object)) return false; seen.add(value as object); const name = (value as { constructor?: { name?: string } }).constructor?.name; if (name && /^(Mesh|Scene|Camera|Material|Geometry|Matrix|Vector|Quaternion|WebGL|WebGPU|Node|Element)/i.test(name)) return true; return Object.entries(value as Record<string, unknown>).some(([k, v]) => /^(callback|handler|mesh|scene|cameraObject|material|geometry|matrix|vector|coordinates|domNode|uiNode|renderer)$/i.test(k) || renderer(v, seen)); }
function iso(value: string): boolean { return Number.isFinite(Date.parse(value)) && /^\d{4}-\d{2}-\d{2}T/.test(value); }
function unique(values: readonly (string | undefined)[]): readonly string[] { return freeze([...new Set(values.filter((x): x is string => typeof x === "string" && x.length > 0))].sort()); }
function err(code: NexoraDirectorRuntimeEventFeedbackErrorCode, message: string, extra: Partial<NexoraDirectorRuntimeEventFeedbackError> = {}): NexoraDirectorRuntimeEventFeedbackError { return freeze({ code, message, ...extra }); }
function warn(code: NexoraDirectorRuntimeEventFeedbackWarningCode, message: string, extra: Partial<NexoraDirectorRuntimeEventFeedbackWarning> = {}): NexoraDirectorRuntimeEventFeedbackWarning { return freeze({ code, message, ...extra }); }
function result(errors: NexoraDirectorRuntimeEventFeedbackError[], warnings: NexoraDirectorRuntimeEventFeedbackWarning[] = []): NexoraDirectorRuntimeEventFeedbackValidationResult { return freeze({ valid: errors.length === 0, errors, warnings }); }
const DEFAULTS: NexoraDirectorRuntimeEventFeedbackDependencies = freeze({ now: () => "1970-01-01T00:00:00.000Z", createStateId: () => "runtime-feedback-state", createActionId: (id: string, type: string) => `${id}:action:${type}`, createConflictId: (ids: readonly string[]) => `conflict:${[...ids].sort().join(":")}`, createRecordId: () => "runtime-feedback-record", createAggregateId: (key: string) => `aggregate:${key}`, createWindowId: () => "runtime-feedback-window", createSnapshotId: () => "runtime-feedback-snapshot" });

export function createNexoraDirectorRuntimeEventFeedbackState(runtimeId: string, updatedAt: string, dependencies: NexoraDirectorRuntimeEventFeedbackDependencies = DEFAULTS): NexoraDirectorRuntimeEventFeedbackState { if (!runtimeId || !iso(updatedAt)) throw new Error("Runtime identity and ISO timestamp are required"); return freeze({ stateId: dependencies.createStateId(), runtimeId, revision: 0, status: "Idle", pendingEventIds: [], processedEventIds: [], suppressedEventIds: [], pendingFeedbackIds: [], acknowledgedFeedbackIds: [], activeCorrelationIds: [], updatedAt }); }
export function resolveNexoraDirectorRuntimeEventPriority(type: NexoraDirectorRuntimeEventType, payload: Readonly<Record<string, unknown>> = {}): number { if (type === "RuntimeFailed") return 100; if (type === "CommandFailed") return payload.severity === "Critical" ? 95 : 85; if (type === "CommandRolledBack") return 80; if (type === "RuntimeDriftDetected") return 75; if (type === "RuntimeCapabilityDegraded") return 65; if (type === "RuntimeHealthChanged") return 60; if (["RuntimeFocusChanged", "RuntimeCameraChanged", "RuntimeAttentionChanged"].includes(type)) return 50; if (type === "RuntimeDiagnostic") return 10; return 30; }
export function normalizeNexoraDirectorRuntimeEvent(input: NexoraDirectorRuntimeEvent, runtimeRevision = input.runtimeRevision): NexoraDirectorRuntimeEvent { if (renderer(input)) throw new Error("Renderer objects are forbidden in Runtime event payloads"); const event = freeze({ ...copy(input), runtimeRevision, priority: Number.isFinite(input.priority) && input.priority >= 0 ? input.priority : resolveNexoraDirectorRuntimeEventPriority(input.eventType, input.payload), occurredAt: new Date(input.occurredAt).toISOString(), payload: copy(input.payload) }); const validation = validateNexoraDirectorRuntimeEvent(event); if (!validation.valid) throw new Error(validation.errors.map((x) => x.message).join("; ")); return event; }
export function normalizeNexoraDirectorRuntimeFeedback(input: NexoraDirectorRuntimeFeedback, runtimeRevision = input.runtimeRevision): NexoraDirectorRuntimeFeedback { if (renderer(input)) throw new Error("Renderer objects are forbidden in Runtime feedback payloads"); const feedback = freeze({ ...copy(input), runtimeRevision, retryable: input.retryable === true, recoverable: input.recoverable === true, requiresAcknowledgment: input.requiresAcknowledgment === true, occurredAt: new Date(input.occurredAt).toISOString(), payload: copy(input.payload) }); const validation = validateNexoraDirectorRuntimeFeedback(feedback); if (!validation.valid) throw new Error(validation.errors.map((x) => x.message).join("; ")); return feedback; }
export function classifyNexoraDirectorRuntimeFeedback(feedback: NexoraDirectorRuntimeFeedback, mode?: NexoraDirectorRuntimeRequestMode, mixed = false): NexoraDirectorRuntimeFeedbackClassification { if (feedback.severity === "Critical" && feedback.requiresAcknowledgment) return "UserAcknowledgmentRequired"; if (feedback.feedbackType === "Diagnostic") return "DiagnosticOnly"; if (feedback.feedbackType === "Unsupported" || feedback.feedbackType === "Degraded") return "CapabilityDegradation"; if (feedback.payload.drift === true || feedback.payload.revisionMismatch === true) return "SynchronizationDrift"; if ((mode === "BestEffort" && mixed) || feedback.payload.partial === true) return "PartialSuccess"; if (feedback.feedbackType === "TimedOut" && feedback.retryable) return "TransientFailure"; if (["Failed", "Rejected", "TimedOut"].includes(feedback.feedbackType) && !feedback.recoverable) return "PermanentFailure"; if (["Accepted", "Applied", "Completed", "Acknowledged"].includes(feedback.feedbackType)) return "Success"; if (feedback.retryable) return "TransientFailure"; return "DiagnosticOnly"; }
const SEVERITY: Readonly<Record<NexoraDirectorRuntimeFeedbackSeverity, number>> = freeze({ Info: 1, Notice: 2, Warning: 3, Error: 4, Critical: 5 });
export function resolveNexoraDirectorRuntimeFeedbackPriority(feedback: NexoraDirectorRuntimeFeedback): number { const classification = classifyNexoraDirectorRuntimeFeedback(feedback); if (feedback.severity === "Critical" && !feedback.recoverable) return 100; if (feedback.severity === "Error" && feedback.requiresAcknowledgment) return 90; if (feedback.feedbackType === "RolledBack") return 80; if (classification === "SynchronizationDrift") return 75; if (classification === "TransientFailure") return 70; if (classification === "CapabilityDegradation") return 60; if (classification === "PartialSuccess") return 50; if (classification === "Success") return 30; return 10; }
function eventCompare(a: NexoraDirectorRuntimeEvent, b: NexoraDirectorRuntimeEvent): number { return b.priority - a.priority || a.occurredAt.localeCompare(b.occurredAt) || a.runtimeRevision - b.runtimeRevision || a.eventId.localeCompare(b.eventId); }
function feedbackCompare(a: NexoraDirectorRuntimeFeedback, b: NexoraDirectorRuntimeFeedback): number { return resolveNexoraDirectorRuntimeFeedbackPriority(b) - resolveNexoraDirectorRuntimeFeedbackPriority(a) || a.occurredAt.localeCompare(b.occurredAt) || a.feedbackId.localeCompare(b.feedbackId); }

export function deduplicateNexoraDirectorRuntimeEvents(events: readonly NexoraDirectorRuntimeEvent[], windowMs = 1000): NexoraDirectorRuntimeEventDeduplication { const retained: NexoraDirectorRuntimeEvent[] = [], suppressed: NexoraDirectorRuntimeEvent[] = []; for (const event of [...events].sort((a, b) => a.occurredAt.localeCompare(b.occurredAt) || a.eventId.localeCompare(b.eventId))) { const duplicate = retained.find((x) => x.runtimeId === event.runtimeId && x.eventType === event.eventType && (x.commandId ?? x.objectId) === (event.commandId ?? event.objectId) && x.correlationId === event.correlationId && x.causationId === event.causationId && stable(x.payload) === stable(event.payload) && Math.abs(Date.parse(x.occurredAt) - Date.parse(event.occurredAt)) <= windowMs && !(event.priority >= 90 && event.runtimeRevision !== x.runtimeRevision)); (duplicate ? suppressed : retained).push(event); } return freeze({ events: retained.sort(eventCompare), suppressedEvents: suppressed.sort(eventCompare) }); }
export function deduplicateNexoraDirectorRuntimeFeedback(feedback: readonly NexoraDirectorRuntimeFeedback[], windowMs = 1000): NexoraDirectorRuntimeFeedbackDeduplication { const retained: NexoraDirectorRuntimeFeedback[] = [], suppressed: NexoraDirectorRuntimeFeedback[] = []; for (const item of [...feedback].sort((a, b) => a.occurredAt.localeCompare(b.occurredAt) || a.feedbackId.localeCompare(b.feedbackId))) { const duplicate = retained.find((x) => x.runtimeId === item.runtimeId && x.feedbackType === item.feedbackType && (x.commandId ?? x.executionId ?? x.synchronizationId) === (item.commandId ?? item.executionId ?? item.synchronizationId) && x.severity === item.severity && x.message === item.message && x.causationId === item.causationId && stable(x.payload) === stable(item.payload) && Math.abs(Date.parse(x.occurredAt) - Date.parse(item.occurredAt)) <= windowMs); ((duplicate && !item.requiresAcknowledgment) ? suppressed : retained).push(item); } return freeze({ feedback: retained.sort(feedbackCompare), suppressedFeedback: suppressed.sort(feedbackCompare) }); }
export function findStaleNexoraDirectorRuntimeEvents(events: readonly NexoraDirectorRuntimeEvent[], state: NexoraDirectorRuntimeState, toleranceMs = 0, now = state.updatedAt): readonly NexoraDirectorRuntimeStaleEvent[] { const removed = new Set(state.objects.filter((x) => x.lifecycle === "Removed").flatMap((x) => [x.objectId, x.runtimeObjectId])); return freeze(events.flatMap((event) => { let reason: NexoraDirectorRuntimeStaleEvent["reason"] | undefined; if (event.runtimeRevision < state.revision) reason = "OlderRuntimeRevision"; else if (event.eventType !== "RuntimeDiagnostic" && Date.parse(now) - Date.parse(event.occurredAt) > toleranceMs) reason = "ExpiredTimestamp"; else if ((event.objectId && removed.has(event.objectId)) || (event.runtimeObjectId && removed.has(event.runtimeObjectId))) reason = "ObjectAlreadyRemoved"; else if (event.eventType === "CommandCompleted" && event.payload.rolledBack === true) reason = "SupersededByRollback"; return reason ? [{ eventId: event.eventId, reason, recoverable: reason !== "SupersededByRollback" }] : []; }).sort((a, b) => a.eventId.localeCompare(b.eventId)));
}
function conflictKey(item: NexoraDirectorRuntimeFeedback): string { return item.commandId ?? item.executionId ?? item.synchronizationId ?? item.objectId ?? item.correlationId ?? item.feedbackId; }
export function detectNexoraDirectorRuntimeFeedbackConflicts(feedback: readonly NexoraDirectorRuntimeFeedback[], dependencies: NexoraDirectorRuntimeEventFeedbackDependencies = DEFAULTS): readonly NexoraDirectorRuntimeFeedbackConflict[] { const groups = new Map<string, NexoraDirectorRuntimeFeedback[]>(); feedback.forEach((x) => groups.set(conflictKey(x), [...(groups.get(conflictKey(x)) ?? []), x])); const conflicts: NexoraDirectorRuntimeFeedbackConflict[] = []; for (const items of groups.values()) { const types = new Set(items.map((x) => x.feedbackType)); let type: NexoraDirectorRuntimeFeedbackConflict["type"] | undefined; if ([...types].some((x) => ["Completed", "Applied"].includes(x)) && [...types].some((x) => ["Failed", "Rejected"].includes(x))) type = "SuccessAndFailure"; else if (types.has("Completed") && types.has("Cancelled")) type = "CompletedAndCancelled"; else if (types.has("Applied") && types.has("RolledBack")) type = "AppliedAndRolledBack"; else if (new Set(items.map((x) => x.runtimeRevision)).size > 1) type = "RevisionMismatch"; if (type) { const ids = items.map((x) => x.feedbackId).sort(); conflicts.push(freeze({ conflictId: dependencies.createConflictId(ids), feedbackIds: ids, type, recoverable: type === "RevisionMismatch", message: `Conflicting Runtime feedback: ${type}` })); } } return freeze(conflicts.sort((a, b) => a.conflictId.localeCompare(b.conflictId))); }
export function resolveNexoraDirectorRuntimeCorrelation(events: readonly NexoraDirectorRuntimeEvent[], feedback: readonly NexoraDirectorRuntimeFeedback[]): readonly NexoraDirectorRuntimeCorrelationGroup[] { const keys = unique([...events.map((x) => x.correlationId ?? x.commandId ?? x.executionId ?? x.synchronizationId ?? x.objectId), ...feedback.map((x) => x.correlationId ?? x.commandId ?? x.executionId ?? x.synchronizationId ?? x.objectId)]); return freeze(keys.map((key) => { const es = events.filter((x) => [x.correlationId, x.causationId, x.commandId, x.executionId, x.synchronizationId, x.objectId].includes(key)); const fs = feedback.filter((x) => [x.correlationId, x.causationId, x.commandId, x.executionId, x.synchronizationId, x.objectId].includes(key)); return freeze({ correlationId: key, eventIds: unique(es.map((x) => x.eventId)), feedbackIds: unique(fs.map((x) => x.feedbackId)), commandIds: unique([...es.map((x) => x.commandId), ...fs.map((x) => x.commandId)]), executionIds: unique([...es.map((x) => x.executionId), ...fs.map((x) => x.executionId)]), synchronizationIds: unique([...es.map((x) => x.synchronizationId), ...fs.map((x) => x.synchronizationId)]), objectIds: unique([...es.map((x) => x.objectId), ...fs.map((x) => x.objectId)]) }); })); }

function action(feedback: NexoraDirectorRuntimeFeedback, type: NexoraDirectorRuntimeFeedbackActionType, target: NexoraDirectorRuntimeFeedbackAction["target"], dependencies: NexoraDirectorRuntimeEventFeedbackDependencies): NexoraDirectorRuntimeFeedbackAction { return freeze({ actionId: dependencies.createActionId(feedback.feedbackId, type), feedbackId: feedback.feedbackId, type, priority: resolveNexoraDirectorRuntimeFeedbackPriority(feedback), ...(feedback.objectId ? { objectId: feedback.objectId } : {}), ...(feedback.runtimeObjectId ? { runtimeObjectId: feedback.runtimeObjectId } : {}), ...(feedback.commandId ? { commandId: feedback.commandId } : {}), ...(feedback.executionId ? { executionId: feedback.executionId } : {}), ...(feedback.synchronizationId ? { synchronizationId: feedback.synchronizationId } : {}), target, reversible: false, payload: freeze({ classification: classifyNexoraDirectorRuntimeFeedback(feedback) }) }); }
export function planNexoraDirectorRuntimeFeedbackActions(feedback: readonly NexoraDirectorRuntimeFeedback[], dependencies: NexoraDirectorRuntimeEventFeedbackDependencies = DEFAULTS): readonly NexoraDirectorRuntimeFeedbackAction[] { const actions: NexoraDirectorRuntimeFeedbackAction[] = []; for (const item of feedback) { const classification = classifyNexoraDirectorRuntimeFeedback(item); if (item.severity === "Critical" && item.requiresAcknowledgment) actions.push(action(item, "Acknowledge", "User", dependencies), action(item, "EscalateToSystem", "System", dependencies)); else if (item.feedbackType === "RolledBack" || classification === "SynchronizationDrift") actions.push(action(item, "RequestResynchronization", "StateSynchronization", dependencies)); else if (classification === "TransientFailure") actions.push(action(item, "RetryCommand", "ExecutionModel", dependencies)); else if (classification === "PermanentFailure") { actions.push(action(item, "PreservePreviousState", "StateSynchronization", dependencies)); actions.push(action(item, item.severity === "Critical" ? "MarkRuntimeUnavailable" : "EscalateToSystem", "System", dependencies)); } else if (classification === "CapabilityDegradation") actions.push(action(item, "DegradeRuntimeHealth", "RuntimeAdapter", dependencies)); else if (item.feedbackType === "TimedOut") actions.push(action(item, "CancelCommand", "ExecutionModel", dependencies), action(item, "PlanRollback", "ExecutionModel", dependencies)); else actions.push(action(item, item.feedbackType === "Diagnostic" ? "EmitDiagnostic" : "NoAction", item.feedbackType === "Diagnostic" ? "Diagnostics" : "RuntimeAdapter", dependencies)); } return freeze(actions.sort((a, b) => b.priority - a.priority || a.actionId.localeCompare(b.actionId))); }

export function createNexoraDirectorRuntimeEventQueue(events: readonly NexoraDirectorRuntimeEvent[] = []): NexoraDirectorRuntimeEventQueue { return freeze({ events: [...events].map((x) => normalizeNexoraDirectorRuntimeEvent(x)).sort(eventCompare) }); }
export function enqueueNexoraDirectorRuntimeEvent(queue: NexoraDirectorRuntimeEventQueue, event: NexoraDirectorRuntimeEvent): NexoraDirectorRuntimeEventQueue { return createNexoraDirectorRuntimeEventQueue([...queue.events, event]); }
export function dequeueNexoraDirectorRuntimeEvent(queue: NexoraDirectorRuntimeEventQueue): readonly [NexoraDirectorRuntimeEvent | undefined, NexoraDirectorRuntimeEventQueue] { return freeze([queue.events[0], createNexoraDirectorRuntimeEventQueue(queue.events.slice(1))] as const); }
export function peekNexoraDirectorRuntimeEvent(queue: NexoraDirectorRuntimeEventQueue): NexoraDirectorRuntimeEvent | undefined { return queue.events[0]; }
export function clearNexoraDirectorRuntimeEventQueue(): NexoraDirectorRuntimeEventQueue { return createNexoraDirectorRuntimeEventQueue(); }
export function createNexoraDirectorRuntimeFeedbackQueue(feedback: readonly NexoraDirectorRuntimeFeedback[] = []): NexoraDirectorRuntimeFeedbackQueue { return freeze({ feedback: [...feedback].map((x) => normalizeNexoraDirectorRuntimeFeedback(x)).sort(feedbackCompare) }); }
export function enqueueNexoraDirectorRuntimeFeedback(queue: NexoraDirectorRuntimeFeedbackQueue, feedback: NexoraDirectorRuntimeFeedback): NexoraDirectorRuntimeFeedbackQueue { return createNexoraDirectorRuntimeFeedbackQueue([...queue.feedback, feedback]); }
export function dequeueNexoraDirectorRuntimeFeedback(queue: NexoraDirectorRuntimeFeedbackQueue): readonly [NexoraDirectorRuntimeFeedback | undefined, NexoraDirectorRuntimeFeedbackQueue] { return freeze([queue.feedback[0], createNexoraDirectorRuntimeFeedbackQueue(queue.feedback.slice(1))] as const); }
export function peekNexoraDirectorRuntimeFeedback(queue: NexoraDirectorRuntimeFeedbackQueue): NexoraDirectorRuntimeFeedback | undefined { return queue.feedback[0]; }
export function clearNexoraDirectorRuntimeFeedbackQueue(): NexoraDirectorRuntimeFeedbackQueue { return createNexoraDirectorRuntimeFeedbackQueue(); }

export function createNexoraDirectorRuntimeFeedbackAcknowledgment(feedback: NexoraDirectorRuntimeFeedback): NexoraDirectorRuntimeFeedbackAcknowledgment { return freeze({ feedbackId: feedback.feedbackId, state: feedback.requiresAcknowledgment ? "Pending" : "NotRequired" }); }
function acknowledge(current: NexoraDirectorRuntimeFeedbackAcknowledgment, state: "Acknowledged" | "Dismissed", actor: string, at: string, reason?: string): NexoraDirectorRuntimeFeedbackAcknowledgment { if (current.state !== "Pending") throw new Error(`Only Pending feedback can become ${state}`); return freeze({ feedbackId: current.feedbackId, state, acknowledgedBy: actor, acknowledgedAt: at, ...(reason ? { reason } : {}) }); }
export function acknowledgeNexoraDirectorRuntimeFeedback(current: NexoraDirectorRuntimeFeedbackAcknowledgment, acknowledgedBy: string, acknowledgedAt: string, reason?: string): NexoraDirectorRuntimeFeedbackAcknowledgment { return acknowledge(current, "Acknowledged", acknowledgedBy, acknowledgedAt, reason); }
export function dismissNexoraDirectorRuntimeFeedback(current: NexoraDirectorRuntimeFeedbackAcknowledgment, dismissedBy: string, dismissedAt: string, reason?: string): NexoraDirectorRuntimeFeedbackAcknowledgment { return acknowledge(current, "Dismissed", dismissedBy, dismissedAt, reason); }
export function expireNexoraDirectorRuntimeFeedbackAcknowledgment(current: NexoraDirectorRuntimeFeedbackAcknowledgment, reason?: string): NexoraDirectorRuntimeFeedbackAcknowledgment { if (current.state !== "Pending") throw new Error("Only Pending feedback can expire"); return freeze({ feedbackId: current.feedbackId, state: "Expired", ...(reason ? { reason } : {}) }); }

export function aggregateNexoraDirectorRuntimeFeedback(feedback: readonly NexoraDirectorRuntimeFeedback[], keySelector: (item: NexoraDirectorRuntimeFeedback) => string = (item) => item.objectId ?? item.commandId ?? item.executionId ?? item.synchronizationId ?? item.correlationId ?? item.feedbackType, dependencies: NexoraDirectorRuntimeEventFeedbackDependencies = DEFAULTS): readonly NexoraDirectorRuntimeFeedbackAggregate[] { const groups = new Map<string, NexoraDirectorRuntimeFeedback[]>(); feedback.forEach((x) => { const key = keySelector(x); groups.set(key, [...(groups.get(key) ?? []), x]); }); return freeze([...groups.entries()].sort(([a], [b]) => a.localeCompare(b)).map(([key, items]) => ({ aggregateId: dependencies.createAggregateId(key), key, feedbackIds: items.map((x) => x.feedbackId).sort(), highestSeverity: [...items].sort((a, b) => SEVERITY[b.severity] - SEVERITY[a.severity])[0]!.severity, successCount: items.filter((x) => classifyNexoraDirectorRuntimeFeedback(x) === "Success").length, failureCount: items.filter((x) => ["TransientFailure", "PermanentFailure"].includes(classifyNexoraDirectorRuntimeFeedback(x))).length, retryableCount: items.filter((x) => x.retryable).length, acknowledgmentRequiredCount: items.filter((x) => x.requiresAcknowledgment).length })));
}
export function createNexoraDirectorRuntimeFeedbackWindow(startedAt: string, endedAt: string, events: readonly NexoraDirectorRuntimeEvent[], feedback: readonly NexoraDirectorRuntimeFeedback[], aggregates: readonly NexoraDirectorRuntimeFeedbackAggregate[], dependencies: NexoraDirectorRuntimeEventFeedbackDependencies = DEFAULTS): NexoraDirectorRuntimeFeedbackWindow { if (!iso(startedAt) || !iso(endedAt) || Date.parse(startedAt) > Date.parse(endedAt)) throw new Error("Invalid feedback window range"); return freeze({ windowId: dependencies.createWindowId(), startedAt, endedAt, eventIds: unique(events.map((x) => x.eventId)), feedbackIds: unique(feedback.map((x) => x.feedbackId)), aggregateIds: unique(aggregates.map((x) => x.aggregateId)) }); }
export function compareNexoraDirectorRuntimeFeedbackWindows(left: NexoraDirectorRuntimeFeedbackWindow, right: NexoraDirectorRuntimeFeedbackWindow): NexoraDirectorRuntimeFeedbackWindowComparison { const rangeChanged = left.startedAt !== right.startedAt || left.endedAt !== right.endedAt, eventsChanged = stable(left.eventIds) !== stable(right.eventIds), feedbackChanged = stable(left.feedbackIds) !== stable(right.feedbackIds), aggregatesChanged = stable(left.aggregateIds) !== stable(right.aggregateIds); return freeze({ equal: !rangeChanged && !eventsChanged && !feedbackChanged && !aggregatesChanged, rangeChanged, eventsChanged, feedbackChanged, aggregatesChanged }); }

function previousState(request: NexoraDirectorRuntimeEventFeedbackRequest, dependencies: NexoraDirectorRuntimeEventFeedbackDependencies): NexoraDirectorRuntimeEventFeedbackState { return request.context.previousCoordinationState ?? createNexoraDirectorRuntimeEventFeedbackState(request.context.runtimeState.runtimeId, request.context.occurredAt ?? request.context.runtimeState.updatedAt, dependencies); }
export function evaluateNexoraDirectorRuntimeEventFeedbackCoordination(request: NexoraDirectorRuntimeEventFeedbackRequest, dependencies: NexoraDirectorRuntimeEventFeedbackDependencies = DEFAULTS): NexoraDirectorRuntimeEventFeedbackPlan {
  const prior = previousState(request, dependencies), errors: NexoraDirectorRuntimeEventFeedbackError[] = [], warnings: NexoraDirectorRuntimeEventFeedbackWarning[] = [];
  const validation = validateNexoraDirectorRuntimeEventFeedbackRequest(request); errors.push(...validation.errors);
  if (request.expectedCoordinationRevision !== undefined && request.expectedCoordinationRevision !== prior.revision) errors.push(err("RUNTIME_FEEDBACK_COORDINATION_REVISION_CONFLICT", `Expected coordination revision ${request.expectedCoordinationRevision}, actual ${prior.revision}`, { requestId: request.requestId, details: { expected: request.expectedCoordinationRevision, actual: prior.revision } }));
  const normalizedEvents: NexoraDirectorRuntimeEvent[] = [], normalizedFeedback: NexoraDirectorRuntimeFeedback[] = [];
  for (const event of request.events) { try { normalizedEvents.push(normalizeNexoraDirectorRuntimeEvent(event, request.context.runtimeState.revision)); } catch { if (request.context.mode === "Atomic") errors.push(err("RUNTIME_FEEDBACK_INVALID_EVENT", `Invalid event ${event.eventId}`, { eventId: event.eventId })); } }
  for (const feedback of request.feedback) { try { normalizedFeedback.push(normalizeNexoraDirectorRuntimeFeedback(feedback, request.context.runtimeState.revision)); } catch { if (request.context.mode === "Atomic") errors.push(err("RUNTIME_FEEDBACK_INVALID_FEEDBACK", `Invalid feedback ${feedback.feedbackId}`, { feedbackId: feedback.feedbackId })); } }
  const eventDedup = deduplicateNexoraDirectorRuntimeEvents(normalizedEvents, request.context.deduplicationWindowMs ?? 1000), feedbackDedup = deduplicateNexoraDirectorRuntimeFeedback(normalizedFeedback, request.context.deduplicationWindowMs ?? 1000);
  eventDedup.suppressedEvents.forEach((x) => warnings.push(warn("RUNTIME_FEEDBACK_DUPLICATE_EVENT_SUPPRESSED", "Duplicate event suppressed", { eventId: x.eventId }))); feedbackDedup.suppressedFeedback.forEach((x) => warnings.push(warn("RUNTIME_FEEDBACK_DUPLICATE_FEEDBACK_SUPPRESSED", "Duplicate feedback suppressed", { feedbackId: x.feedbackId })));
  const staleEvents = findStaleNexoraDirectorRuntimeEvents(eventDedup.events, request.context.runtimeState, request.context.staleEventToleranceMs ?? Number.POSITIVE_INFINITY, request.context.occurredAt ?? request.context.runtimeState.updatedAt); staleEvents.forEach((x) => warnings.push(warn("RUNTIME_FEEDBACK_STALE_EVENT_IGNORED", `Stale event ignored: ${x.reason}`, { eventId: x.eventId })));
  const conflicts = detectNexoraDirectorRuntimeFeedbackConflicts(feedbackDedup.feedback, dependencies); const blocking = conflicts.filter((x) => !x.recoverable); if (blocking.length && request.context.mode === "Atomic") errors.push(err("RUNTIME_FEEDBACK_UNRESOLVED_CONFLICT", "Atomic coordination has unresolved feedback conflicts", { requestId: request.requestId })); else if (conflicts.length) warnings.push(warn("RUNTIME_FEEDBACK_PARTIAL_COORDINATION", "Conflicting feedback was isolated", { requestId: request.requestId }));
  const excluded = request.context.mode === "BestEffort" ? new Set(conflicts.flatMap((x) => x.feedbackIds)) : new Set<string>(); const coordinatedFeedback = feedbackDedup.feedback.filter((x) => !excluded.has(x.feedbackId));
  const correlations = resolveNexoraDirectorRuntimeCorrelation(eventDedup.events.filter((x) => !staleEvents.some((s) => s.eventId === x.eventId)), coordinatedFeedback); const actions = planNexoraDirectorRuntimeFeedbackActions(coordinatedFeedback, dependencies);
  const changed = eventDedup.events.length + coordinatedFeedback.length + (request.acknowledgments?.length ?? 0) > 0; const accepted = errors.length === 0;
  const projectedState = accepted && changed ? freeze({ ...copy(prior), revision: prior.revision + 1, status: conflicts.length ? "PartiallyCompleted" as const : "Completed" as const, pendingEventIds: [], processedEventIds: unique([...prior.processedEventIds, ...eventDedup.events.filter((x) => !staleEvents.some((s) => s.eventId === x.eventId)).map((x) => x.eventId)]), suppressedEventIds: unique([...prior.suppressedEventIds, ...eventDedup.suppressedEvents.map((x) => x.eventId), ...staleEvents.map((x) => x.eventId)]), pendingFeedbackIds: unique([...prior.pendingFeedbackIds, ...coordinatedFeedback.filter((x) => x.requiresAcknowledgment).map((x) => x.feedbackId)]), acknowledgedFeedbackIds: unique([...prior.acknowledgedFeedbackIds, ...(request.acknowledgments ?? []).filter((x) => ["Acknowledged", "Dismissed"].includes(x.state)).map((x) => x.feedbackId)]), activeCorrelationIds: unique([...prior.activeCorrelationIds, ...correlations.map((x) => x.correlationId)]), updatedAt: request.context.occurredAt ?? dependencies.now() }) : prior;
  if (!changed && accepted) warnings.push(warn("RUNTIME_FEEDBACK_NO_ACTION_REQUIRED", "Coordination contained no events or feedback", { requestId: request.requestId }));
  return freeze({ requestId: request.requestId, accepted, changed: accepted && changed, noOp: !changed, mode: request.context.mode, previousState: prior, projectedState, normalizedEvents: eventDedup.events, normalizedFeedback: coordinatedFeedback, staleEvents, conflicts, correlations, actions, warnings, errors });
}

export function createNexoraDirectorRuntimeEventRecord(event: NexoraDirectorRuntimeEvent, stale: boolean, suppressed: boolean, processedAt: string, dependencies: NexoraDirectorRuntimeEventFeedbackDependencies = DEFAULTS): NexoraDirectorRuntimeEventRecord { return freeze({ recordId: dependencies.createRecordId(), eventId: event.eventId, runtimeId: event.runtimeId, eventType: event.eventType, priority: event.priority, stale, suppressed, processedAt, ...(event.correlationId ? { correlationId: event.correlationId } : {}), ...(event.causationId ? { causationId: event.causationId } : {}) }); }
export function createNexoraDirectorRuntimeFeedbackRecord(feedback: NexoraDirectorRuntimeFeedback, acknowledgment: NexoraDirectorRuntimeFeedbackAcknowledgment, actions: readonly NexoraDirectorRuntimeFeedbackAction[], processedAt: string, dependencies: NexoraDirectorRuntimeEventFeedbackDependencies = DEFAULTS): NexoraDirectorRuntimeFeedbackRecord { return freeze({ recordId: dependencies.createRecordId(), feedbackId: feedback.feedbackId, runtimeId: feedback.runtimeId, classification: classifyNexoraDirectorRuntimeFeedback(feedback), severity: feedback.severity, acknowledgmentState: acknowledgment.state, actionIds: actions.filter((x) => x.feedbackId === feedback.feedbackId).map((x) => x.actionId), processedAt }); }
export function applyNexoraDirectorRuntimeEventFeedbackCoordination(request: NexoraDirectorRuntimeEventFeedbackRequest, dependencies: NexoraDirectorRuntimeEventFeedbackDependencies = DEFAULTS): NexoraDirectorRuntimeEventFeedbackResult { const plan = evaluateNexoraDirectorRuntimeEventFeedbackCoordination(request, dependencies), simulated = request.context.mode === "Simulation", nextState = plan.accepted && plan.changed && !simulated ? plan.projectedState : plan.previousState, processedAt = request.context.occurredAt ?? dependencies.now(); const staleIds = new Set(plan.staleEvents.map((x) => x.eventId)); const suppressed = new Set(plan.projectedState.suppressedEventIds); const acknowledgments = new Map((request.acknowledgments ?? []).map((x) => [x.feedbackId, x])); const eventRecords = simulated ? [] : plan.normalizedEvents.map((x) => createNexoraDirectorRuntimeEventRecord(x, staleIds.has(x.eventId), suppressed.has(x.eventId), processedAt, dependencies)); const feedbackRecords = simulated ? [] : plan.normalizedFeedback.map((x) => createNexoraDirectorRuntimeFeedbackRecord(x, acknowledgments.get(x.feedbackId) ?? createNexoraDirectorRuntimeFeedbackAcknowledgment(x), plan.actions, processedAt, dependencies)); return freeze({ accepted: plan.accepted, changed: plan.changed && !simulated, simulated, previousState: plan.previousState, nextState, plan, eventRecords, feedbackRecords, warnings: plan.warnings, errors: plan.errors }); }

export function coordinateNexoraDirectorRuntimeEventFeedbackBatch(batch: NexoraDirectorRuntimeEventFeedbackBatchRequest, dependencies: NexoraDirectorRuntimeEventFeedbackDependencies = DEFAULTS): NexoraDirectorRuntimeEventFeedbackBatchResult { const ids = batch.requests.map((x) => x.requestId); if (new Set(ids).size !== ids.length) throw new Error("Duplicate Runtime feedback request IDs"); let current = previousState(batch.requests[0]!, dependencies); const results: NexoraDirectorRuntimeEventFeedbackResult[] = []; for (const source of batch.requests) { const request = freeze({ ...copy(source), context: freeze({ ...copy(source.context), mode: batch.mode, previousCoordinationState: current }) }); const coordinated = applyNexoraDirectorRuntimeEventFeedbackCoordination(request, dependencies); results.push(coordinated); if (coordinated.accepted) current = coordinated.nextState; else if (batch.mode === "Atomic") { current = previousState(batch.requests[0]!, dependencies); break; } } const rejected = results.filter((x) => !x.accepted).map((x) => x.plan.requestId), atomicRejected = batch.mode === "Atomic" && rejected.length > 0; return freeze({ accepted: rejected.length === 0, results, acceptedRequestIds: atomicRejected ? [] : results.filter((x) => x.accepted).map((x) => x.plan.requestId), rejectedRequestIds: rejected, finalState: current }); }
export function simulateNexoraDirectorRuntimeEventFeedbackSequence(requests: readonly NexoraDirectorRuntimeEventFeedbackRequest[], continueAfterFailure = false, dependencies: NexoraDirectorRuntimeEventFeedbackDependencies = DEFAULTS): NexoraDirectorRuntimeEventFeedbackSequenceResult { let current = previousState(requests[0]!, dependencies), firstFailure: string | undefined; const results: NexoraDirectorRuntimeEventFeedbackResult[] = []; for (const source of requests) { const request = freeze({ ...copy(source), context: freeze({ ...copy(source.context), mode: "Simulation" as const, previousCoordinationState: current }) }); const coordinated = applyNexoraDirectorRuntimeEventFeedbackCoordination(request, dependencies); results.push(coordinated); if (!coordinated.accepted && !firstFailure) { firstFailure = source.requestId; if (!continueAfterFailure) break; } if (coordinated.accepted) current = coordinated.plan.projectedState; } return freeze({ plans: results.map((x) => x.plan), results, ...(firstFailure ? { firstFailureRequestId: firstFailure } : {}), finalProjectedState: current }); }
export function projectNexoraDirectorRuntimeEventHistory(records: readonly NexoraDirectorRuntimeEventRecord[]): readonly NexoraDirectorRuntimeEventRecord[] { return freeze([...records].sort((a, b) => a.processedAt.localeCompare(b.processedAt) || a.eventId.localeCompare(b.eventId)).map(copy)); }
export function projectNexoraDirectorRuntimeFeedbackHistory(records: readonly NexoraDirectorRuntimeFeedbackRecord[]): readonly NexoraDirectorRuntimeFeedbackRecord[] { return freeze([...records].sort((a, b) => a.processedAt.localeCompare(b.processedAt) || a.feedbackId.localeCompare(b.feedbackId)).map(copy)); }
export function createNexoraDirectorRuntimeEventFeedbackSnapshot(state: NexoraDirectorRuntimeEventFeedbackState, eventQueue: NexoraDirectorRuntimeEventQueue, feedbackQueue: NexoraDirectorRuntimeFeedbackQueue, acknowledgments: readonly NexoraDirectorRuntimeFeedbackAcknowledgment[], dependencies: NexoraDirectorRuntimeEventFeedbackDependencies = DEFAULTS): NexoraDirectorRuntimeEventFeedbackSnapshot { return freeze({ snapshotId: dependencies.createSnapshotId(), state: copy(state), eventQueue: copy(eventQueue), feedbackQueue: copy(feedbackQueue), acknowledgments: copy(acknowledgments), createdAt: dependencies.now() }); }
export function compareNexoraDirectorRuntimeEventFeedbackSnapshots(left: NexoraDirectorRuntimeEventFeedbackSnapshot, right: NexoraDirectorRuntimeEventFeedbackSnapshot): NexoraDirectorRuntimeEventFeedbackSnapshotComparison { const revisionChanged = left.state.revision !== right.state.revision, pendingEventsChanged = stable(left.state.pendingEventIds) !== stable(right.state.pendingEventIds), processedEventsChanged = stable(left.state.processedEventIds) !== stable(right.state.processedEventIds), feedbackChanged = stable(left.feedbackQueue) !== stable(right.feedbackQueue) || stable(left.state.pendingFeedbackIds) !== stable(right.state.pendingFeedbackIds), acknowledgmentsChanged = stable(left.acknowledgments) !== stable(right.acknowledgments), correlationsChanged = stable(left.state.activeCorrelationIds) !== stable(right.state.activeCorrelationIds), conflictsChanged = false, actionsChanged = false; return freeze({ equal: !revisionChanged && !pendingEventsChanged && !processedEventsChanged && !feedbackChanged && !acknowledgmentsChanged && !correlationsChanged && !conflictsChanged && !actionsChanged, revisionChanged, pendingEventsChanged, processedEventsChanged, feedbackChanged, acknowledgmentsChanged, correlationsChanged, conflictsChanged, actionsChanged }); }

export function validateNexoraDirectorRuntimeEvent(value: unknown): NexoraDirectorRuntimeEventFeedbackValidationResult { const errors: NexoraDirectorRuntimeEventFeedbackError[] = []; if (!rec(value)) return result([err("RUNTIME_FEEDBACK_INVALID_EVENT", "Runtime event must be an object")]); if (typeof value.eventId !== "string" || !value.eventId || typeof value.runtimeId !== "string" || !value.runtimeId) errors.push(err("RUNTIME_FEEDBACK_INVALID_EVENT", "Event and Runtime identity are required")); if (!Number.isInteger(value.runtimeRevision) || Number(value.runtimeRevision) < 0) errors.push(err("RUNTIME_FEEDBACK_INVALID_REVISION", "Event revision must be non-negative")); if (typeof value.priority !== "number" || !Number.isFinite(value.priority) || value.priority < 0) errors.push(err("RUNTIME_FEEDBACK_INVALID_PRIORITY", "Event priority must be finite and non-negative")); if (typeof value.occurredAt !== "string" || !iso(value.occurredAt)) errors.push(err("RUNTIME_FEEDBACK_INVALID_TIMESTAMP", "Event timestamp must be ISO")); if (renderer(value)) errors.push(err("RUNTIME_FEEDBACK_RENDERER_OBJECT_FORBIDDEN", "Renderer objects are forbidden")); return result(errors); }
export function validateNexoraDirectorRuntimeFeedback(value: unknown): NexoraDirectorRuntimeEventFeedbackValidationResult { const errors: NexoraDirectorRuntimeEventFeedbackError[] = []; if (!rec(value)) return result([err("RUNTIME_FEEDBACK_INVALID_FEEDBACK", "Runtime feedback must be an object")]); if (typeof value.feedbackId !== "string" || !value.feedbackId || typeof value.runtimeId !== "string" || !value.runtimeId || typeof value.message !== "string") errors.push(err("RUNTIME_FEEDBACK_INVALID_FEEDBACK", "Feedback identity, Runtime identity, and message are required")); if (!Number.isInteger(value.runtimeRevision) || Number(value.runtimeRevision) < 0) errors.push(err("RUNTIME_FEEDBACK_INVALID_REVISION", "Feedback revision must be non-negative")); if (typeof value.occurredAt !== "string" || !iso(value.occurredAt)) errors.push(err("RUNTIME_FEEDBACK_INVALID_TIMESTAMP", "Feedback timestamp must be ISO")); if (["Failed", "TimedOut", "Cancelled", "Retried", "RolledBack"].includes(String(value.feedbackType)) && typeof value.commandId !== "string") errors.push(err("RUNTIME_FEEDBACK_MISSING_COMMAND_REFERENCE", "Command feedback requires commandId")); if (renderer(value)) errors.push(err("RUNTIME_FEEDBACK_RENDERER_OBJECT_FORBIDDEN", "Renderer objects are forbidden")); return result(errors); }
export function validateNexoraDirectorRuntimeFeedbackAcknowledgment(value: unknown, feedback?: NexoraDirectorRuntimeFeedback): NexoraDirectorRuntimeEventFeedbackValidationResult { const errors: NexoraDirectorRuntimeEventFeedbackError[] = []; if (!rec(value) || typeof value.feedbackId !== "string" || !["NotRequired", "Pending", "Acknowledged", "Dismissed", "Expired"].includes(String(value.state))) errors.push(err("RUNTIME_FEEDBACK_INVALID_ACKNOWLEDGMENT", "Feedback acknowledgment is invalid")); if (feedback && feedback.requiresAcknowledgment && rec(value) && value.state === "NotRequired") errors.push(err("RUNTIME_FEEDBACK_INVALID_ACKNOWLEDGMENT", "Required feedback cannot use NotRequired")); if (feedback && !feedback.requiresAcknowledgment && rec(value) && value.state !== "NotRequired") errors.push(err("RUNTIME_FEEDBACK_INVALID_ACKNOWLEDGMENT", "Optional feedback must use NotRequired")); return result(errors); }
export function validateNexoraDirectorRuntimeEventFeedbackState(value: unknown): NexoraDirectorRuntimeEventFeedbackValidationResult { const errors: NexoraDirectorRuntimeEventFeedbackError[] = []; if (!rec(value) || typeof value.runtimeId !== "string" || !value.runtimeId || !Number.isInteger(value.revision) || Number(value.revision) < 0) errors.push(err("RUNTIME_FEEDBACK_INVARIANT_VIOLATION", "Coordination state identity or revision is invalid")); if (!frozen(value)) errors.push(err("RUNTIME_FEEDBACK_INVARIANT_VIOLATION", "Coordination state must be deeply immutable")); return result(errors); }
export function validateNexoraDirectorRuntimeEventFeedbackRequest(value: unknown): NexoraDirectorRuntimeEventFeedbackValidationResult { const errors: NexoraDirectorRuntimeEventFeedbackError[] = []; if (!rec(value) || typeof value.requestId !== "string" || !value.requestId || !Array.isArray(value.events) || !Array.isArray(value.feedback) || !rec(value.context)) return result([err("RUNTIME_FEEDBACK_INVALID_REQUEST", "Coordination request is invalid")]); const events = value.events, feedback = value.feedback; events.forEach((x) => errors.push(...validateNexoraDirectorRuntimeEvent(x).errors)); feedback.forEach((x) => errors.push(...validateNexoraDirectorRuntimeFeedback(x).errors)); const eventIds = events.map((x) => rec(x) ? x.eventId : undefined), feedbackIds = feedback.map((x) => rec(x) ? x.feedbackId : undefined); if (new Set(eventIds).size !== eventIds.length) errors.push(err("RUNTIME_FEEDBACK_DUPLICATE_EVENT_ID", "Event IDs must be unique")); if (new Set(feedbackIds).size !== feedbackIds.length) errors.push(err("RUNTIME_FEEDBACK_DUPLICATE_FEEDBACK_ID", "Feedback IDs must be unique")); const context = value.context, runtimeState = rec(context.runtimeState) ? context.runtimeState : undefined; if (runtimeState && (events.some((x) => rec(x) && x.runtimeId !== runtimeState.runtimeId) || feedback.some((x) => rec(x) && x.runtimeId !== runtimeState.runtimeId))) errors.push(err("RUNTIME_FEEDBACK_RUNTIME_ID_MISMATCH", "All Runtime identities must match")); if (rec(context.runtimeContext) && !validateDirectorRuntimeAdapter(context.runtimeContext).valid) errors.push(err("RUNTIME_FEEDBACK_INVALID_REQUEST", "Runtime adapter context is invalid")); if (runtimeState && !validateNexoraDirectorRuntimeState(runtimeState).valid) errors.push(err("RUNTIME_FEEDBACK_INVALID_REQUEST", "Runtime state is invalid")); if (rec(context.executionReport) && !validateExecutionReport(context.executionReport).valid) errors.push(err("RUNTIME_FEEDBACK_INVALID_REQUEST", "Execution report is invalid")); if (rec(context.synchronizationResult) && !validateNexoraDirectorRuntimeStateSynchronizationResult(context.synchronizationResult).valid) errors.push(err("RUNTIME_FEEDBACK_INVALID_REQUEST", "Synchronization result is invalid")); if (renderer(value)) errors.push(err("RUNTIME_FEEDBACK_RENDERER_OBJECT_FORBIDDEN", "Renderer objects are forbidden")); if (!frozen(value)) errors.push(err("RUNTIME_FEEDBACK_INVARIANT_VIOLATION", "Request must be deeply immutable")); return result(errors); }
export function validateNexoraDirectorRuntimeFeedbackAction(value: unknown): NexoraDirectorRuntimeEventFeedbackValidationResult { const errors: NexoraDirectorRuntimeEventFeedbackError[] = []; if (!rec(value) || typeof value.actionId !== "string" || typeof value.feedbackId !== "string" || !Number.isFinite(value.priority) || Number(value.priority) < 0) errors.push(err("RUNTIME_FEEDBACK_ACTION_INVALID", "Feedback action is invalid")); if (renderer(value)) errors.push(err("RUNTIME_FEEDBACK_RENDERER_OBJECT_FORBIDDEN", "Renderer objects are forbidden")); return result(errors); }
export function validateNexoraDirectorRuntimeEventFeedbackPlan(value: unknown): NexoraDirectorRuntimeEventFeedbackValidationResult { const errors: NexoraDirectorRuntimeEventFeedbackError[] = []; if (!rec(value) || !Array.isArray(value.actions)) errors.push(err("RUNTIME_FEEDBACK_INVARIANT_VIOLATION", "Coordination plan is invalid")); else { value.actions.forEach((x) => errors.push(...validateNexoraDirectorRuntimeFeedbackAction(x).errors)); const ids = value.actions.map((x) => rec(x) ? x.actionId : undefined); if (new Set(ids).size !== ids.length) errors.push(err("RUNTIME_FEEDBACK_ACTION_INVALID", "Action IDs must be unique")); } if (!frozen(value)) errors.push(err("RUNTIME_FEEDBACK_INVARIANT_VIOLATION", "Plan must be deeply immutable")); return result(errors); }
export function validateNexoraDirectorRuntimeEventFeedbackResult(value: unknown): NexoraDirectorRuntimeEventFeedbackValidationResult { const errors: NexoraDirectorRuntimeEventFeedbackError[] = []; if (!rec(value) || !rec(value.plan) || !rec(value.nextState)) errors.push(err("RUNTIME_FEEDBACK_INVARIANT_VIOLATION", "Coordination result is invalid")); if (!frozen(value)) errors.push(err("RUNTIME_FEEDBACK_INVARIANT_VIOLATION", "Result must be deeply immutable")); return result(errors); }
export function assertNexoraDirectorRuntimeEventFeedbackInvariants(value: unknown): void { const validation = rec(value) && "actions" in value ? validateNexoraDirectorRuntimeEventFeedbackPlan(value) : rec(value) && "nextState" in value ? validateNexoraDirectorRuntimeEventFeedbackResult(value) : rec(value) && "eventType" in value ? validateNexoraDirectorRuntimeEvent(value) : rec(value) && "feedbackType" in value ? validateNexoraDirectorRuntimeFeedback(value) : validateNexoraDirectorRuntimeEventFeedbackState(value); if (!validation.valid) throw new NexoraObjectDirectorRuntimeEventFeedbackCoordinationException(validation.errors.map((x) => x.message).join("; ")); }

type Kind = "Event" | "Feedback" | "Acknowledgment" | "State" | "Plan" | "EventRecord" | "FeedbackRecord" | "Snapshot";
function serialize(kind: Kind, payload: unknown): string { if (renderer(payload)) throw new NexoraObjectDirectorRuntimeEventFeedbackCoordinationException("Renderer objects are forbidden"); return JSON.stringify({ identity: nexoraObjectDirectorRuntimeEventFeedbackCoordinationEngineIdentity, schemaVersion: nexoraObjectDirectorRuntimeEventFeedbackCoordinationSchemaVersion, kind, payload }); }
function deserialize<T>(json: string, kind: Kind): T { const parsed: unknown = JSON.parse(json); if (!rec(parsed) || parsed.identity !== nexoraObjectDirectorRuntimeEventFeedbackCoordinationEngineIdentity || parsed.schemaVersion !== nexoraObjectDirectorRuntimeEventFeedbackCoordinationSchemaVersion || parsed.kind !== kind) throw new NexoraObjectDirectorRuntimeEventFeedbackCoordinationException("Unsupported Runtime event feedback schema"); if (renderer(parsed.payload)) throw new NexoraObjectDirectorRuntimeEventFeedbackCoordinationException("Renderer objects are forbidden"); return freeze(parsed.payload as T); }
export const serializeNexoraDirectorRuntimeEvent = (x: NexoraDirectorRuntimeEvent): string => serialize("Event", x); export const deserializeNexoraDirectorRuntimeEvent = (x: string): NexoraDirectorRuntimeEvent => deserialize(x, "Event");
export const serializeNexoraDirectorRuntimeFeedback = (x: NexoraDirectorRuntimeFeedback): string => serialize("Feedback", x); export const deserializeNexoraDirectorRuntimeFeedback = (x: string): NexoraDirectorRuntimeFeedback => deserialize(x, "Feedback");
export const serializeNexoraDirectorRuntimeFeedbackAcknowledgment = (x: NexoraDirectorRuntimeFeedbackAcknowledgment): string => serialize("Acknowledgment", x); export const deserializeNexoraDirectorRuntimeFeedbackAcknowledgment = (x: string): NexoraDirectorRuntimeFeedbackAcknowledgment => deserialize(x, "Acknowledgment");
export const serializeNexoraDirectorRuntimeEventFeedbackState = (x: NexoraDirectorRuntimeEventFeedbackState): string => serialize("State", x); export const deserializeNexoraDirectorRuntimeEventFeedbackState = (x: string): NexoraDirectorRuntimeEventFeedbackState => deserialize(x, "State");
export const serializeNexoraDirectorRuntimeEventFeedbackPlan = (x: NexoraDirectorRuntimeEventFeedbackPlan): string => serialize("Plan", x); export const deserializeNexoraDirectorRuntimeEventFeedbackPlan = (x: string): NexoraDirectorRuntimeEventFeedbackPlan => deserialize(x, "Plan");
export const serializeNexoraDirectorRuntimeEventRecord = (x: NexoraDirectorRuntimeEventRecord): string => serialize("EventRecord", x); export const deserializeNexoraDirectorRuntimeEventRecord = (x: string): NexoraDirectorRuntimeEventRecord => deserialize(x, "EventRecord");
export const serializeNexoraDirectorRuntimeFeedbackRecord = (x: NexoraDirectorRuntimeFeedbackRecord): string => serialize("FeedbackRecord", x); export const deserializeNexoraDirectorRuntimeFeedbackRecord = (x: string): NexoraDirectorRuntimeFeedbackRecord => deserialize(x, "FeedbackRecord");
export const serializeNexoraDirectorRuntimeEventFeedbackSnapshot = (x: NexoraDirectorRuntimeEventFeedbackSnapshot): string => serialize("Snapshot", x); export const deserializeNexoraDirectorRuntimeEventFeedbackSnapshot = (x: string): NexoraDirectorRuntimeEventFeedbackSnapshot => deserialize(x, "Snapshot");
