import type { CanonicalRightPanelView } from "./rightPanelTypes";

export type RightPanelRegistryEntry = {
  label: string;
  hostRenderKey: string;
  componentExists: boolean;
  fallbackAllowed: boolean;
  fallbackTitle: string;
  fallbackMessage: string;
  isProtectedView: boolean;
  overridePolicy: "normal" | "protected";
};

export const RIGHT_PANEL_REGISTRY: Record<CanonicalRightPanelView, RightPanelRegistryEntry> = {
  strategic_command: {
    label: "Strategic Command",
    hostRenderKey: "strategic_command",
    componentExists: true,
    fallbackAllowed: true,
    fallbackTitle: "Strategic Command",
    fallbackMessage: "Strategic command context is not ready yet.",
    isProtectedView: false,
    overridePolicy: "normal",
  },
  dashboard: {
    label: "Executive Dashboard",
    hostRenderKey: "dashboard",
    componentExists: true,
    fallbackAllowed: true,
    fallbackTitle: "Executive Overview",
    fallbackMessage: "Executive overview is waiting for decision context.",
    isProtectedView: false,
    overridePolicy: "normal",
  },
  // Protected views must keep their concrete panel identity and should not be overridden by dashboard/executive fallback logic downstream.
  simulate: {
    label: "Simulation",
    hostRenderKey: "dashboard",
    componentExists: true,
    fallbackAllowed: true,
    fallbackTitle: "Simulation",
    fallbackMessage: "No simulation is available yet. Run a scenario to generate results.",
    isProtectedView: true,
    overridePolicy: "protected",
  },
  compare: {
    label: "Compare Options",
    hostRenderKey: "compare",
    componentExists: true,
    fallbackAllowed: true,
    fallbackTitle: "Compare Options",
    fallbackMessage: "No comparison data is available yet. Run analysis or simulation to compare options.",
    isProtectedView: true,
    overridePolicy: "protected",
  },
  decision_lifecycle: {
    label: "Decision Lifecycle",
    hostRenderKey: "decision_lifecycle",
    componentExists: true,
    fallbackAllowed: true,
    fallbackTitle: "Decision Lifecycle",
    fallbackMessage: "Decision lifecycle is waiting for recommendation context.",
    isProtectedView: false,
    overridePolicy: "normal",
  },
  strategic_learning: {
    label: "Strategic Learning",
    hostRenderKey: "strategic_learning",
    componentExists: true,
    fallbackAllowed: true,
    fallbackTitle: "Strategic Learning",
    fallbackMessage: "Strategic learning data is not ready yet.",
    isProtectedView: false,
    overridePolicy: "normal",
  },
  meta_decision: {
    label: "Meta Decision",
    hostRenderKey: "meta_decision",
    componentExists: true,
    fallbackAllowed: true,
    fallbackTitle: "Meta Decision",
    fallbackMessage: "Meta decision context is not ready yet.",
    isProtectedView: false,
    overridePolicy: "normal",
  },
  cognitive_style: {
    label: "Cognitive Style",
    hostRenderKey: "cognitive_style",
    componentExists: true,
    fallbackAllowed: true,
    fallbackTitle: "Cognitive Style",
    fallbackMessage: "Cognitive style guidance is not ready yet.",
    isProtectedView: false,
    overridePolicy: "normal",
  },
  team_decision: {
    label: "Team Decision",
    hostRenderKey: "team_decision",
    componentExists: true,
    fallbackAllowed: true,
    fallbackTitle: "Team Decision",
    fallbackMessage: "Team decision context is not ready yet.",
    isProtectedView: false,
    overridePolicy: "normal",
  },
  org_memory: {
    label: "Org Memory",
    hostRenderKey: "org_memory",
    componentExists: true,
    fallbackAllowed: true,
    fallbackTitle: "Organization Memory",
    fallbackMessage: "Organization memory is not available yet.",
    isProtectedView: false,
    overridePolicy: "normal",
  },
  decision_governance: {
    label: "Decision Governance",
    hostRenderKey: "decision_governance",
    componentExists: true,
    fallbackAllowed: true,
    fallbackTitle: "Decision Governance",
    fallbackMessage: "Governance posture is not ready yet for this decision.",
    isProtectedView: false,
    overridePolicy: "normal",
  },
  decision_policy: {
    label: "Decision Policy",
    hostRenderKey: "decision_policy",
    componentExists: true,
    fallbackAllowed: true,
    fallbackTitle: "Decision Policy",
    fallbackMessage: "Decision policy is not available yet for the current context.",
    isProtectedView: false,
    overridePolicy: "normal",
  },
  executive_approval: {
    label: "Executive Approval",
    hostRenderKey: "executive_approval",
    componentExists: true,
    fallbackAllowed: true,
    fallbackTitle: "Executive Approval",
    fallbackMessage: "Approval workflow is not initialized yet for this decision.",
    isProtectedView: false,
    overridePolicy: "normal",
  },
  explanation: {
    label: "Explanation",
    hostRenderKey: "explanation",
    componentExists: true,
    fallbackAllowed: true,
    fallbackTitle: "Explanation",
    fallbackMessage: "Decision explanation will appear after analysis or chat returns decision context.",
    isProtectedView: false,
    overridePolicy: "normal",
  },
  risk: {
    label: "Risk",
    hostRenderKey: "risk",
    componentExists: true,
    fallbackAllowed: true,
    fallbackTitle: "Risk",
    fallbackMessage: "Risk view is waiting for fragility or propagation context.",
    isProtectedView: false,
    overridePolicy: "normal",
  },
  fragility: {
    label: "Fragility",
    hostRenderKey: "fragility",
    componentExists: true,
    fallbackAllowed: true,
    fallbackTitle: "Fragility",
    fallbackMessage: "Fragility context is not ready yet for this scenario.",
    isProtectedView: false,
    overridePolicy: "normal",
  },
  object: {
    label: "Objects",
    hostRenderKey: "object",
    componentExists: true,
    fallbackAllowed: true,
    fallbackTitle: "Objects",
    fallbackMessage: "No scene objects are available yet.",
    isProtectedView: false,
    overridePolicy: "normal",
  },
  object_focus: {
    label: "Object Focus",
    hostRenderKey: "object",
    componentExists: true,
    fallbackAllowed: true,
    fallbackTitle: "Object Focus",
    fallbackMessage: "No object is selected yet.",
    isProtectedView: false,
    overridePolicy: "normal",
  },
  timeline: {
    label: "Timeline",
    hostRenderKey: "timeline",
    componentExists: true,
    fallbackAllowed: true,
    fallbackTitle: "Decision Timeline",
    fallbackMessage: "No timeline is available yet. Run a simulation or replay to build one.",
    isProtectedView: true,
    overridePolicy: "protected",
  },
  decision_timeline: {
    label: "Decision Timeline",
    hostRenderKey: "decision_timeline",
    componentExists: true,
    fallbackAllowed: true,
    fallbackTitle: "Decision Timeline",
    fallbackMessage: "Decision history is not available yet.",
    isProtectedView: false,
    overridePolicy: "normal",
  },
  confidence_calibration: {
    label: "Confidence Calibration",
    hostRenderKey: "confidence_calibration",
    componentExists: true,
    fallbackAllowed: true,
    fallbackTitle: "Confidence Calibration",
    fallbackMessage: "Confidence calibration is not available yet.",
    isProtectedView: false,
    overridePolicy: "normal",
  },
  outcome_feedback: {
    label: "Outcome Feedback",
    hostRenderKey: "outcome_feedback",
    componentExists: true,
    fallbackAllowed: true,
    fallbackTitle: "Outcome Feedback",
    fallbackMessage: "Outcome feedback is not available yet.",
    isProtectedView: false,
    overridePolicy: "normal",
  },
  pattern_intelligence: {
    label: "Pattern Intelligence",
    hostRenderKey: "pattern_intelligence",
    componentExists: true,
    fallbackAllowed: true,
    fallbackTitle: "Pattern Intelligence",
    fallbackMessage: "Pattern intelligence is not available yet.",
    isProtectedView: false,
    overridePolicy: "normal",
  },
  collaboration_intelligence: {
    label: "Collaboration Intelligence",
    hostRenderKey: "collaboration_intelligence",
    componentExists: true,
    fallbackAllowed: true,
    fallbackTitle: "Collaboration Intelligence",
    fallbackMessage: "Collaboration intelligence is not available yet.",
    isProtectedView: false,
    overridePolicy: "normal",
  },
  decision_council: {
    label: "Decision Council",
    hostRenderKey: "decision_council",
    componentExists: true,
    fallbackAllowed: true,
    fallbackTitle: "Decision Council",
    fallbackMessage: "Council guidance is not available yet.",
    isProtectedView: false,
    overridePolicy: "normal",
  },
  scenario_tree: {
    label: "Scenario Tree",
    hostRenderKey: "scenario_tree",
    componentExists: true,
    fallbackAllowed: true,
    fallbackTitle: "Scenario Tree",
    fallbackMessage: "Scenario branching is not available yet.",
    isProtectedView: false,
    overridePolicy: "normal",
  },
  advice: {
    label: "Strategic Advice",
    hostRenderKey: "advice",
    componentExists: true,
    fallbackAllowed: true,
    fallbackTitle: "Strategic Advice",
    fallbackMessage: "Strategic advice is not available yet. Run analysis or simulation to generate recommendations.",
    isProtectedView: true,
    overridePolicy: "protected",
  },
  kpi: {
    label: "KPI",
    hostRenderKey: "kpi",
    componentExists: false,
    fallbackAllowed: true,
    fallbackTitle: "KPI",
    fallbackMessage: "KPI analysis is not available yet for the current context.",
    isProtectedView: false,
    overridePolicy: "normal",
  },
  war_room: {
    label: "War Room",
    hostRenderKey: "war_room",
    componentExists: true,
    fallbackAllowed: true,
    fallbackTitle: "War Room",
    fallbackMessage: "War Room is not ready yet for this scenario. Generate a recommendation or simulation first.",
    isProtectedView: true,
    overridePolicy: "protected",
  },
  conflict: {
    label: "Conflict",
    hostRenderKey: "conflict",
    componentExists: true,
    fallbackAllowed: true,
    fallbackTitle: "Conflict Map",
    fallbackMessage: "Conflict analysis is not available yet.",
    isProtectedView: false,
    overridePolicy: "normal",
  },
  memory: {
    label: "Memory",
    hostRenderKey: "memory",
    componentExists: true,
    fallbackAllowed: true,
    fallbackTitle: "Decision Memory",
    fallbackMessage: "Decision memory is not ready yet.",
    isProtectedView: false,
    overridePolicy: "normal",
  },
  replay: {
    label: "Replay",
    hostRenderKey: "replay",
    componentExists: true,
    fallbackAllowed: true,
    fallbackTitle: "Decision Replay",
    fallbackMessage: "Replay is not ready yet for this decision.",
    isProtectedView: false,
    overridePolicy: "normal",
  },
  patterns: {
    label: "Patterns",
    hostRenderKey: "patterns",
    componentExists: true,
    fallbackAllowed: true,
    fallbackTitle: "Strategic Patterns",
    fallbackMessage: "Strategic patterns are not available yet.",
    isProtectedView: false,
    overridePolicy: "normal",
  },
  opponent: {
    label: "Opponent",
    hostRenderKey: "opponent",
    componentExists: true,
    fallbackAllowed: true,
    fallbackTitle: "Opponent Moves",
    fallbackMessage: "Opponent modeling is not available yet.",
    isProtectedView: false,
    overridePolicy: "normal",
  },
  collaboration: {
    label: "Collaboration",
    hostRenderKey: "collaboration",
    componentExists: true,
    fallbackAllowed: true,
    fallbackTitle: "Collaboration",
    fallbackMessage: "Collaboration context is not ready yet.",
    isProtectedView: false,
    overridePolicy: "normal",
  },
  workspace: {
    label: "Scene",
    hostRenderKey: "scene",
    componentExists: true,
    fallbackAllowed: true,
    fallbackTitle: "Scene",
    fallbackMessage: "Scene context is not ready yet.",
    isProtectedView: false,
    overridePolicy: "normal",
  },
  input: {
    label: "Input / Source",
    hostRenderKey: "input",
    componentExists: true,
    fallbackAllowed: true,
    fallbackTitle: "Input / Data Source",
    fallbackMessage: "Describe your situation or attach context for analysis.",
    isProtectedView: false,
    overridePolicy: "normal",
  },
};

export function getRightPanelRegistryEntry(view: CanonicalRightPanelView): RightPanelRegistryEntry {
  return RIGHT_PANEL_REGISTRY[view];
}

export function isProtectedRightPanelRegistryView(
  view: CanonicalRightPanelView
): boolean {
  return RIGHT_PANEL_REGISTRY[view].isProtectedView;
}

export function getRightPanelOverridePolicy(
  view: CanonicalRightPanelView
): "normal" | "protected" {
  return RIGHT_PANEL_REGISTRY[view].overridePolicy;
}
