import assert from "node:assert/strict"; import test from "node:test";
import { createNexoraCanonicalDecisionRuntime } from "./executiveDecisionRuntimeAdapter.ts";
import { createNexoraCanonicalExecutionRuntime, type NexoraCanonicalExecution } from "./executiveExecutionRuntimeAdapter.ts";
import { projectExecutionFollowUpSnapshot, executionFollowUpSnapshotFingerprint } from "./executiveFollowUpSnapshot.ts";
import { createEmptyExecutiveFollowUpMemory, captureExecutionFollowUpSnapshot, readExecutionFollowUpHistory, EXECUTIVE_FOLLOW_UP_MAX_EXECUTIONS, EXECUTIVE_FOLLOW_UP_MAX_SNAPSHOTS_PER_EXECUTION } from "./executiveFollowUpMemory.ts";
import { compareExecutionFollowUpSnapshots } from "./executiveFollowUpChange.ts";
import { reviewExecutionWithFollowUpMemory, resolveExecutiveFollowUpMemoryHandoff, EXECUTIVE_FOLLOW_UP_MEMORY_ADVISOR_BOUNDARY } from "./executiveFollowUpMemoryAdvisor.ts";
import { renderExecutiveFollowUpAdvisorText, toExecutiveFollowUpConversationalMessage } from "./executiveFollowUpAdvisorResponse.ts";

const record = (patch: Partial<NexoraCanonicalExecution> = {}): NexoraCanonicalExecution => ({ executionId: "e", decisionId: "d", title: "Capacity Expansion", status: "in-progress", progress: undefined, ownerIds: [], blockers: [], risks: [], milestones: [], source: "runtime", createdFromDecision: true, workspaceId: "w", modelId: "m", ...patch });
const runtime = (value: NexoraCanonicalExecution) => { const decisions = createNexoraCanonicalDecisionRuntime(); decisions.adapter.transitionDecision({ decisionId: value.decisionId, action: "approve", title: "Decision", workspaceId: value.workspaceId, modelId: value.modelId }); return createNexoraCanonicalExecutionRuntime({ decisionRuntime: decisions.adapter, initialExecutions: [value] }); };
const snapshot = (value: NexoraCanonicalExecution, at = "2026-08-15T00:00:00Z") => projectExecutionFollowUpSnapshot({ runtime: runtime(value), executionId: value.executionId, observedAt: at })!;

test("identity boundary is historical/session-only and mutation-free", () => assert.deepEqual(EXECUTIVE_FOLLOW_UP_MEMORY_ADVISOR_BOUNDARY, { storesCurrentExecutionTruth: false, createsExecution: false, transitionsExecution: false, mutatesDecision: false, mutatesStage: false, movesCamera: false, mutatesTopology: false, stealsFocus: false, externalSideEffects: false, durablePersistence: false }));
test("snapshot is immutable, canonical, deterministic, and ignores observedAt in fingerprint", () => { const a = snapshot(record(), "a"); const b = snapshot(record(), "b"); assert.ok(Object.isFrozen(a)); assert.equal(a.source, "canonical-execution-runtime"); assert.equal(a.snapshotId, b.snapshotId); assert.equal(executionFollowUpSnapshotFingerprint(a), executionFollowUpSnapshotFingerprint(b)); });
test("first review captures baseline; compare-only reports no history", () => { const result = reviewExecutionWithFollowUpMemory({ runtime: runtime(record()), executionId: "e", memory: createEmptyExecutiveFollowUpMemory(), compareOnly: true }); assert.equal(result.status, "baseline-captured"); assert.match(result.response!.summary, /don't have an earlier/); assert.equal(readExecutionFollowUpHistory(result.memory, record()).length, 1); });
test("duplicate semantic snapshots are suppressed and no-change is concise", () => { const rt = runtime(record()); const first = reviewExecutionWithFollowUpMemory({ runtime: rt, executionId: "e", memory: createEmptyExecutiveFollowUpMemory() }); const second = reviewExecutionWithFollowUpMemory({ runtime: rt, executionId: "e", memory: first.memory, compareOnly: true }); assert.equal(readExecutionFollowUpHistory(second.memory, record()).length, 1); assert.equal(second.response?.summary, "No material execution change is recorded since the last review."); });
test("status/blocker/risk recovery changes are factual without causality", () => { const before = snapshot(record({ status: "blocked", blockers: [{ blockerId: "procurement", label: "Procurement" }], risks: [{ riskId: "schedule", label: "Schedule" }] })); const after = snapshot(record({ status: "in-progress" })); const c = compareExecutionFollowUpSnapshots(before, after); assert.ok(c.changes.some((x) => x.kind === "resumed")); assert.ok(c.changes.some((x) => x.kind === "blocker-removed")); assert.ok(c.changes.some((x) => x.kind === "risk-removed")); assert.equal(c.causeEstablished, false); });
test("new blocker and blocked status derive critical attention", () => { const c = compareExecutionFollowUpSnapshots(snapshot(record()), snapshot(record({ status: "blocked", blockers: [{ blockerId: "procurement", label: "Procurement" }] }))); assert.equal(c.attention, "critical"); assert.ok(c.changes.some((x) => x.kind === "blocker-added")); });
test("trusted progress delta and unknown-to-known remain distinct", () => { const delta = compareExecutionFollowUpSnapshots(snapshot(record({ progress: 40 })), snapshot(record({ progress: 55 }))); assert.equal(delta.progressDelta, 15); const known = compareExecutionFollowUpSnapshots(snapshot(record()), snapshot(record({ progress: 45 }))); assert.equal(known.progressDelta, null); assert.ok(known.changes.some((x) => x.kind === "progress-became-available")); });
test("unknown progress emits no progress change", () => { const c = compareExecutionFollowUpSnapshots(snapshot(record()), snapshot(record())); assert.equal(c.progressDelta, null); assert.ok(!c.changes.some((x) => x.kind.startsWith("progress"))); });
test("owner, milestone, and deadline changes use canonical IDs/values", () => { const c = compareExecutionFollowUpSnapshots(snapshot(record()), snapshot(record({ ownerIds: ["owner-b"], milestones: [{ milestoneId: "install", label: "Install", deadline: "2026-09-20" }] }))); for (const kind of ["owner-changed", "milestone-changed", "deadline-changed"]) assert.ok(c.changes.some((x) => x.kind === kind)); });
test("workspace/model histories are isolated", () => { const a = snapshot(record()); const b = snapshot(record({ workspaceId: "other" })); let memory = captureExecutionFollowUpSnapshot(createEmptyExecutiveFollowUpMemory(), a).memory; memory = captureExecutionFollowUpSnapshot(memory, b).memory; assert.equal(readExecutionFollowUpHistory(memory, a).length, 1); assert.equal(readExecutionFollowUpHistory(memory, b).length, 1); assert.throws(() => compareExecutionFollowUpSnapshots(a, b), /scope-mismatch/); });
test("history bounds snapshots and executions", () => { let memory = createEmptyExecutiveFollowUpMemory(); for (let e = 0; e < EXECUTIVE_FOLLOW_UP_MAX_EXECUTIONS + 2; e++) for (let n = 0; n < EXECUTIVE_FOLLOW_UP_MAX_SNAPSHOTS_PER_EXECUTION + 2; n++) memory = captureExecutionFollowUpSnapshot(memory, snapshot(record({ executionId: `e${e}`, decisionId: `d${e}`, progress: n, workspaceId: `w${e}` }))).memory; assert.equal(memory.executionOrder.length, EXECUTIVE_FOLLOW_UP_MAX_EXECUTIONS); for (const h of Object.values(memory.executions)) assert.ok(h.length <= EXECUTIVE_FOLLOW_UP_MAX_SNAPSHOTS_PER_EXECUTION); });
test("failed turn preserves memory and Runtime remains current truth", () => { const rt = runtime(record({ status: "completed" })); const memory = createEmptyExecutiveFollowUpMemory(); const failed = reviewExecutionWithFollowUpMemory({ runtime: rt, executionId: "missing", memory }); assert.equal(failed.memory, memory); assert.equal(projectExecutionFollowUpSnapshot({ runtime: rt, executionId: "e" })?.status, "completed"); });
test("Advisor response renders through existing CC:5 message contract", () => { const before = snapshot(record()); const current = snapshot(record({ progress: 45 })); const comparison = compareExecutionFollowUpSnapshots(before, current); const result = reviewExecutionWithFollowUpMemory({ runtime: runtime(record({ progress: 45 })), executionId: "e", memory: captureExecutionFollowUpSnapshot(createEmptyExecutiveFollowUpMemory(), before).memory, title: "Capacity Expansion" }); const text = renderExecutiveFollowUpAdvisorText(result.response!); assert.match(text, /Trusted progress is now available at 45%/); const message = toExecutiveFollowUpConversationalMessage(result.response!, "cc12-1"); assert.equal(message.role, "nexora"); assert.equal(message.text, text); assert.equal(comparison.causeEstablished, false); });
test("handoffs preserve CC:8, CC:9, and CC:10 authorities", () => { assert.equal(resolveExecutiveFollowUpMemoryHandoff("What should I do?"), "CC:8"); assert.equal(resolveExecutiveFollowUpMemoryHandoff("What if this lasts a quarter?"), "CC:9"); assert.equal(resolveExecutiveFollowUpMemoryHandoff("Reconsider the decision"), "CC:10"); });
