import assert from "node:assert/strict";
import { existsSync, readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { describe, it } from "node:test";
import { fileURLToPath } from "node:url";
import * as frozenSurface from "./runtime/nexoraObjectDirectorRuntimeFreeze.ts";
import * as publicSurface from "./nexoraObjectDirectorRuntimePublicIndex.ts";

function deeplyFrozen(value: unknown, seen = new Set<object>()): boolean { if (value === null || typeof value !== "object" || seen.has(value as object)) return true; if (!Object.isFrozen(value)) return false; seen.add(value as object); return Object.values(value as Record<string, unknown>).every((child) => deeplyFrozen(child, seen)); }
const directory = dirname(fileURLToPath(import.meta.url));
const productionPath = join(directory, "nexoraObjectDirectorRuntimePublicIndex.ts");
const testPath = join(directory, "nexoraObjectDirectorRuntimePublicIndex.test.ts");
const source = readFileSync(productionPath, "utf8");

describe("NOL-4:9 Director Runtime Public Index", () => {
  it("1-3. identity and sole Freeze dependency are exact with no bypass", () => { assert.equal(publicSurface.publicIndexIdentity, "NOL-4:9/NexoraObjectDirectorRuntimePublicIndex"); assert.equal(publicSurface.nexoraObjectDirectorRuntimePublicIndex.identity.publicIndexIdentity, publicSurface.publicIndexIdentity); const imports = [...source.matchAll(/^import[^;]+from\s+["']([^"']+)["']/gm)].map((match) => match[1]); assert.deepEqual(imports, ["./runtime/nexoraObjectDirectorRuntimeFreeze.ts"]); assert.doesNotMatch(source, /import[^;]+(?:Certification|ValidationIntegrity|CapabilityAdapter|EventFeedback|StateSynchronization|CommandExecution|AdapterFoundation)/); assert.equal(publicSurface.runtimePublicIndexUpstream, frozenSurface.nexoraObjectDirectorRuntimeFreezeIdentity); });
  it("4-5. exactly nine namespaces exist in canonical order", () => { assert.deepEqual(publicSurface.NEXORA_DIRECTOR_RUNTIME_NAMESPACE_SECTIONS, ["Identity", "Public Types", "Public APIs", "Validation", "Certification", "Release Information", "Compatibility", "Registry", "Consumer Information"]); assert.deepEqual(Object.keys(publicSurface.nexoraObjectDirectorRuntimePublicIndex), ["identity", "publicTypes", "publicApis", "validation", "certification", "releaseInformation", "compatibility", "registry", "consumerInformation"]); assert.equal(Object.keys(publicSurface.nexoraObjectDirectorRuntimePublicIndex).length, 9); });
  it("6-9. APIs, types, validation, and certification are unchanged Freeze exports", () => { assert.equal(publicSurface.certifyNexoraDirectorRuntime, frozenSurface.certifyNexoraDirectorRuntime); assert.equal(publicSurface.validateNexoraDirectorRuntime, frozenSurface.validateNexoraDirectorRuntime); assert.equal(publicSurface.createNexoraDirectorRuntimeFreeze, frozenSurface.createNexoraDirectorRuntimeFreeze); assert.equal(publicSurface.runtimePublicApis, frozenSurface.getNexoraDirectorRuntimePublicApiRegistry()); assert.equal(publicSurface.runtimePublicTypes, frozenSurface.getNexoraDirectorRuntimePublicTypeRegistry()); assert.equal(publicSurface.runtimeValidationSurface.verifyFreeze, frozenSurface.verifyNexoraDirectorRuntimeFreeze); assert.equal(publicSurface.runtimeCertificationSurface.certify, frozenSurface.certifyNexoraDirectorRuntime); assert.doesNotMatch(source, /^export\s+(?:interface|type)\s+/m); });
  it("10-13. release, compatibility, registry, and consumer evidence originate in Freeze", () => { assert.equal(publicSurface.runtimeReleaseInformation, frozenSurface.nexoraDirectorRuntimeReleaseInformation); assert.equal(publicSurface.runtimePublicIndexStatus, frozenSurface.nexoraDirectorRuntimeFreezeStatus); assert.equal(publicSurface.runtimePublicIndexCompatibility, frozenSurface.nexoraDirectorRuntimeFreezeCompatibility); assert.equal(publicSurface.runtimeCompatibilityInformation.dependencyLock, frozenSurface.nexoraDirectorRuntimeDependencyLock); assert.equal(publicSurface.runtimeCompatibilityInformation.versionLock, frozenSurface.nexoraDirectorRuntimeVersionLock); assert.equal(publicSurface.runtimeCompatibilityInformation.schemaLock, frozenSurface.nexoraDirectorRuntimeSchemaLock); assert.equal(publicSurface.runtimePublicApiRegistry, frozenSurface.getNexoraDirectorRuntimePublicApiRegistry()); assert.equal(publicSurface.runtimePublicTypeRegistry, frozenSurface.getNexoraDirectorRuntimePublicTypeRegistry()); assert.equal(publicSurface.runtimePublicIdentityRegistry, frozenSurface.getNexoraDirectorRuntimePublicIdentityRegistry()); assert.deepEqual(publicSurface.runtimeConsumerInformation, { readyForConsumer: true, freezeOnlyDependency: true, stableApi: true, soleConsumerEntryPoint: true }); });
  it("14-19. dynamic counts and all publication metadata remain deeply immutable", () => { const registry = publicSurface.runtimeRegistryInformation; assert.equal(registry.publicApiCount, registry.publicApiRegistry.entries.length); assert.equal(registry.publicTypeCount, registry.publicTypeRegistry.entries.length); assert.equal(registry.publicIdentityCount, registry.publicIdentityRegistry.identities.length); for (const value of [registry, publicSurface.nexoraObjectDirectorRuntimePublicIndex, publicSurface.runtimeReleaseInformation, publicSurface.runtimeCompatibilityInformation, publicSurface.runtimeConsumerInformation]) assert.equal(deeplyFrozen(value), true); assert.equal(publicSurface.runtimePublicIndexCompatibility, "BackwardCompatible"); });
  it("20-24. consumer verification publishes all four required guarantees", () => { const result = publicSurface.verifyNexoraDirectorRuntimeConsumerEntry(); assert.equal(result, publicSurface.runtimeConsumerInformation); assert.deepEqual(result, { readyForConsumer: true, freezeOnlyDependency: true, stableApi: true, soleConsumerEntryPoint: true }); assert.equal(result.readyForConsumer, true); assert.equal(result.freezeOnlyDependency, true); assert.equal(result.stableApi, true); assert.equal(result.soleConsumerEntryPoint, true); assert.equal(publicSurface.nexoraObjectDirectorRuntimePublicIndex.consumerInformation.importPath, "@/app/lib/nol/nexoraObjectDirectorRuntimePublicIndex"); assert.equal(publicSurface.nexoraObjectDirectorRuntimePublicIndex.consumerInformation.status.label, "Released · Certified · Frozen · Stable · ReadyForConsumer"); });
  it("25-26. public API identities and type names remain unique", () => { const apiIdentities = publicSurface.runtimePublicApiRegistry.entries.map((entry) => entry.identity), typeNames = publicSurface.runtimePublicTypeRegistry.entries.map((entry) => entry.typeName); assert.equal(new Set(apiIdentities).size, apiIdentities.length); assert.equal(new Set(typeNames).size, typeNames.length); });
  it("27-28. deliverables, script, typecheck, and lint contracts are present", () => { assert.equal(existsSync(productionPath), true); assert.equal(existsSync(testPath), true); assert.equal(existsSync(join(directory, "nexoraObjectDirectorRuntimePublicIndex.index.ts")), false); const packageJson = JSON.parse(readFileSync(join(directory, "../../../package.json"), "utf8")) as { scripts: Record<string, string> }; assert.equal(packageJson.scripts["test:nol-runtime-public-index"], "npx tsx --test app/lib/nol/nexoraObjectDirectorRuntimePublicIndex.test.ts"); assert.doesNotMatch(source, /(?<!\.)\b(?:execute|synchronize|dispatch|certify|validate|freeze|serialize|deserialize|compare)[A-Za-z0-9_]*\s*\(/); });
});
