import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { describe, it } from "node:test";
import { sceneBindingContractCount, sceneBindingContractId, sceneBindingContractRegistry } from "./nexoraObjectDirectorSceneBindingContracts.ts";
import * as validation from "./nexoraObjectDirectorSceneBindingValidation.ts";

function freeze<T>(value: T, seen: object[] = []): T { if (value === null || typeof value !== "object" || seen.includes(value as object)) return value; seen.push(value as object); Object.values(value as Record<string, unknown>).forEach((child) => freeze(child, seen)); return Object.freeze(value); }
function deeplyFrozen(value: unknown, seen: object[] = []): boolean { if (value === null || typeof value !== "object" || seen.includes(value as object)) return true; if (!Object.isFrozen(value)) return false; seen.push(value as object); return Object.values(value as Record<string, unknown>).every((child) => deeplyFrozen(child, seen)); }
function node(id: string, parentId: string | null, children: readonly string[], order: number, overrides: Record<string, unknown> = {}) { return { nodeId: id, kind: "object", parentId, children, visibility: "visible", interaction: "selectable", binding: { rendererObjectId: `renderer:${id}`, rendererState: "minimum", rendererCapabilities: ["selectable"], rendererBindingType: "object" }, order, ...overrides }; }
function input(nodes: readonly unknown[] = [node("root", null, [], 0)], overrides: Record<string, unknown> = {}) { return { bindingId: "binding-1", nodes, ...overrides }; }
const source = readFileSync(new URL("./nexoraObjectDirectorSceneBindingValidation.ts", import.meta.url), "utf8");

describe("NOL-6:3 Director Scene Binding Validation", () => {
  it("publishes exact identity, status, and sole Contracts dependency", () => { assert.equal(validation.nexoraObjectDirectorSceneBindingValidationId, "NOL-6:3/NexoraObjectDirectorSceneBindingValidation"); assert.equal(validation.nexoraObjectDirectorSceneBindingValidationVersion, "6.3.0"); assert.equal(validation.nexoraObjectDirectorSceneBindingValidationNamespace, "nexora.nol.scene.binding.validation"); assert.equal(validation.nexoraObjectDirectorSceneBindingValidationStatus, "ReadyForCertification"); assert.equal(validation.nexoraObjectDirectorSceneBindingValidationDependency, sceneBindingContractId); const imports = [...source.matchAll(/from\s+["']([^"']+)["']/g)].map((match) => match[1]); assert.deepEqual(imports, ["./nexoraObjectDirectorSceneBindingContracts.ts"]); assert.doesNotMatch(source, /from\s+["'][^"']*(?:Foundation|renderer|runtime|react|next|three|ui|canvas|webgl)/i); });

  it("publishes ordered frozen severities, unique codes, defaults, capabilities, and APIs", () => { assert.deepEqual(validation.sceneBindingValidationSeverities, ["info", "warning", "error", "fatal"]); assert.equal(validation.sceneBindingValidationSeverityCount, validation.sceneBindingValidationSeverities.length); assert.equal(validation.sceneBindingValidationCodes.length >= 29, true); assert.equal(new Set(validation.sceneBindingValidationCodes).size, validation.sceneBindingValidationCodes.length); assert.equal(validation.sceneBindingValidationCodeCount, validation.sceneBindingValidationCodes.length); assert.deepEqual(validation.defaultSceneBindingValidationOptions, { allowUnknownFields: false, requireSingleRoot: true, requireContiguousOrder: true, requireFrozenInput: false }); assert.equal(validation.nexoraObjectDirectorSceneBindingValidationCapabilityCount, validation.nexoraObjectDirectorSceneBindingValidationCapabilities.length); assert.equal(validation.nexoraObjectDirectorSceneBindingValidationCapabilityCount, 17); assert.equal(validation.nexoraObjectDirectorSceneBindingValidationPublicApiCount, validation.nexoraObjectDirectorSceneBindingValidationPublicApiSurface.length); assert.equal(validation.nexoraObjectDirectorSceneBindingValidationPublicApiCount, 10); for (const value of [validation.sceneBindingValidationSeverities, validation.sceneBindingValidationCodes, validation.defaultSceneBindingValidationOptions, validation.nexoraObjectDirectorSceneBindingValidationCapabilities, validation.nexoraObjectDirectorSceneBindingValidationPublicApiSurface]) assert.equal(deeplyFrozen(value), true); });

  it("accepts minimal, multi-level, sibling, enum, and renderer-binding valid scenes", () => { assert.equal(validation.validateNexoraObjectDirectorSceneBinding(input()).valid, true); const hierarchy = input([node("root", null, ["left", "right"], 0), node("left", "root", ["leaf"], 0, { visibility: "hidden", interaction: "focusable", binding: { rendererObjectId: "renderer:left", rendererState: "report", rendererCapabilities: ["focusable"], rendererBindingType: "label" } }), node("right", "root", [], 1, { visibility: "collapsed", interaction: "interactive", binding: { rendererObjectId: "renderer:right", rendererState: "operation", rendererCapabilities: ["interactive"], rendererBindingType: "badge" } }), node("leaf", "left", [], 0)]); const result = validation.validateNexoraObjectDirectorSceneBinding(hierarchy); assert.equal(result.valid, true); assert.equal(result.checkedNodeCount, 4); assert.equal(result.checkedBindingCount, 4); for (const visibility of ["visible", "hidden", "collapsed"]) assert.equal(validation.validateNexoraObjectDirectorSceneBinding(input([node("root", null, [], 0, { visibility })])).valid, true); for (const interaction of ["none", "selectable", "focusable", "interactive"]) assert.equal(validation.validateNexoraObjectDirectorSceneBinding(input([node("root", null, [], 0, { interaction })])).valid, true); for (const rendererState of ["minimum", "report", "operation"]) assert.equal(validation.validateNexoraObjectDirectorRendererBinding({ rendererObjectId: "renderer", rendererState, rendererCapabilities: ["selectable"], rendererBindingType: "object" }).valid, true); });

  it("returns findings instead of throwing for invalid top-level input", () => { for (const value of [null, [], 42, "scene", true]) assert.doesNotThrow(() => validation.validateNexoraObjectDirectorSceneBinding(value)); assert.equal(validation.validateNexoraObjectDirectorSceneBinding(null).findings[0].code, "SCENE_BINDING_INPUT_REQUIRED"); assert.equal(validation.validateNexoraObjectDirectorSceneBinding([]).findings.some((entry) => entry.code === "SCENE_BINDING_INPUT_NOT_PLAIN_OBJECT"), true); class CustomInput { bindingId = "custom"; nodes: unknown[] = []; } assert.equal(validation.validateNexoraObjectDirectorSceneBinding(new CustomInput()).valid, false); assert.equal(validation.validateNexoraObjectDirectorSceneBinding({ nodes: [] }).findings.some((entry) => entry.code === "SCENE_BINDING_ID_REQUIRED"), true); assert.equal(validation.validateNexoraObjectDirectorSceneBinding({ bindingId: "binding" }).findings.some((entry) => entry.code === "SCENE_BINDING_NODE_COLLECTION_REQUIRED"), true); });

  it("rejects invalid IDs and duplicate node identities without normalizing input", () => { for (const nodeId of [undefined, "", "   ", " padded "]) { const value = input([{ ...node("valid", null, [], 0), nodeId }]), before = JSON.stringify(value), result = validation.validateNexoraObjectDirectorSceneBinding(value); assert.equal(result.valid, false); assert.equal(result.findings.some((entry) => entry.code === "SCENE_BINDING_NODE_ID_REQUIRED"), true); assert.equal(JSON.stringify(value), before); } const duplicate = input([node("same", null, [], 0), node("same", null, [], 1)]); assert.equal(validation.validateNexoraObjectDirectorSceneBinding(duplicate, { requireSingleRoot: false }).findings.some((entry) => entry.code === "SCENE_BINDING_NODE_ID_DUPLICATE"), true); });

  it("validates hierarchy references, reciprocity, roots, leaves, and cycles safely", () => { const missingParent = input([node("root", "missing", [], 0)]), missingChild = input([node("root", null, ["missing"], 0)]), mismatch = input([node("root", null, [], 0), node("child", "root", [], 0)]), selfParent = input([node("root", "root", [], 0)]), selfChild = input([node("root", null, ["root"], 0)]), duplicateChild = input([node("root", null, ["child", "child"], 0), node("child", "root", [], 0)]); for (const value of [missingParent, missingChild, mismatch, selfParent, selfChild, duplicateChild]) assert.equal(validation.validateNexoraObjectDirectorSceneBinding(value).valid, false); const roots = input([node("one", null, [], 0), node("two", null, [], 1)]); assert.equal(validation.validateNexoraObjectDirectorSceneBinding(roots).findings.some((entry) => entry.code === "SCENE_BINDING_ROOT_INVALID"), true); assert.equal(validation.validateNexoraObjectDirectorSceneBinding(roots, { requireSingleRoot: false }).valid, true); const directCycle = input([node("one", "two", ["two"], 0), node("two", "one", ["one"], 0)]), multiCycle = input([node("one", "three", ["two"], 0), node("two", "one", ["three"], 0), node("three", "two", ["one"], 0)]); assert.equal(validation.validateNexoraObjectDirectorSceneBinding(directCycle).findings.some((entry) => entry.code === "SCENE_BINDING_HIERARCHY_CYCLE"), true); assert.equal(validation.validateNexoraObjectDirectorSceneBinding(multiCycle).findings.some((entry) => entry.code === "SCENE_BINDING_HIERARCHY_CYCLE"), true); const deepNodes = Array.from({ length: 300 }, (_, index) => node(`node-${index}`, index === 0 ? null : `node-${index - 1}`, index === 299 ? [] : [`node-${index + 1}`], 0)); assert.doesNotThrow(() => validation.validateNexoraObjectDirectorSceneBinding(input(deepNodes))); assert.equal(validation.validateNexoraObjectDirectorSceneBinding(input(deepNodes)).valid, true); });

  it("enforces public visibility, interaction, and renderer vocabularies", () => { assert.equal(validation.validateNexoraObjectDirectorSceneBinding(input([node("root", null, [], 0, { visibility: "removed" })])).findings.some((entry) => entry.code === "SCENE_BINDING_VISIBILITY_INVALID"), true); assert.equal(validation.validateNexoraObjectDirectorSceneBinding(input([node("root", null, [], 0, { interaction: "actionable" })])).findings.some((entry) => entry.code === "SCENE_BINDING_INTERACTION_INVALID"), true); const rendererResult = (binding: unknown) => validation.validateNexoraObjectDirectorRendererBinding(binding); assert.equal(rendererResult({ rendererState: "minimum", rendererCapabilities: [], rendererBindingType: "object" }).findings.some((entry) => entry.code === "SCENE_BINDING_RENDERER_OBJECT_ID_REQUIRED"), true); assert.equal(rendererResult({ rendererObjectId: "id", rendererState: "detail", rendererCapabilities: [], rendererBindingType: "object" }).findings.some((entry) => entry.code === "SCENE_BINDING_RENDERER_STATE_INVALID"), true); assert.equal(rendererResult({ rendererObjectId: "id", rendererState: "minimum", rendererCapabilities: [], rendererBindingType: "mesh" }).findings.some((entry) => entry.code === "SCENE_BINDING_RENDERER_BINDING_TYPE_INVALID"), true); for (const capabilities of [["unknown"], ["selectable", "selectable"], [""], [() => true], [{ instance: "mesh" }]]) assert.equal(rendererResult({ rendererObjectId: "id", rendererState: "minimum", rendererCapabilities: capabilities, rendererBindingType: "object" }).findings.some((entry) => entry.code === "SCENE_BINDING_RENDERER_CAPABILITIES_INVALID"), true); });

  it("validates negative, fractional, infinite, duplicate, and non-contiguous ordering", () => { for (const order of [-1, 0.5, Number.POSITIVE_INFINITY]) assert.equal(validation.validateNexoraObjectDirectorSceneBinding(input([node("root", null, [], order)])).findings.some((entry) => entry.code === "SCENE_BINDING_ORDER_INVALID"), true); const duplicates = input([node("one", null, [], 0), node("two", null, [], 0)]); assert.equal(validation.validateNexoraObjectDirectorSceneBinding(duplicates, { requireSingleRoot: false }).findings.some((entry) => entry.code === "SCENE_BINDING_ORDER_DUPLICATE"), true); const gaps = input([node("one", null, [], 0), node("two", null, [], 2)]), before = JSON.stringify(gaps); assert.equal(validation.validateNexoraObjectDirectorSceneBinding(gaps, { requireSingleRoot: false }).findings.some((entry) => entry.code === "SCENE_BINDING_COLLECTION_ORDER_INVALID"), true); assert.equal(validation.validateNexoraObjectDirectorSceneBinding(gaps, { requireSingleRoot: false, requireContiguousOrder: false }).valid, true); assert.equal(JSON.stringify(gaps), before); });

  it("enforces unknown-field safety without executing or mutating values", () => { const strict = input(undefined, { extra: "plain" }); assert.equal(validation.validateNexoraObjectDirectorSceneBinding(strict).findings.some((entry) => entry.code === "SCENE_BINDING_UNKNOWN_FIELD"), true); assert.equal(validation.validateNexoraObjectDirectorSceneBinding(strict, { allowUnknownFields: true }).valid, true); let called = false; const executable = input(undefined, { extra: () => { called = true; } }); assert.equal(validation.validateNexoraObjectDirectorSceneBinding(executable, { allowUnknownFields: true }).valid, false); assert.equal(called, false); assert.equal(Object.isFrozen(executable), false); });

  it("supports optional frozen-input enforcement without freezing caller data", () => { const mutable = input(), before = JSON.stringify(mutable); assert.equal(validation.validateNexoraObjectDirectorSceneBinding(mutable).valid, true); assert.equal(validation.validateNexoraObjectDirectorSceneBinding(mutable, { requireFrozenInput: true }).findings.some((entry) => entry.code === "SCENE_BINDING_INPUT_NOT_FROZEN"), true); assert.equal(Object.isFrozen(mutable), false); assert.equal(JSON.stringify(mutable), before); const immutable = freeze(input()); assert.equal(validation.validateNexoraObjectDirectorSceneBinding(immutable, { requireFrozenInput: true }).valid, true); });

  it("canonicalizes, freezes, de-duplicates, and counts findings deterministically", () => { const broken = input([node("same", "missing", ["absent"], 2, { visibility: "gone", interaction: "actionable" }), node("same", null, [], 2)]), first = validation.validateNexoraObjectDirectorSceneBinding(broken), second = validation.validateNexoraObjectDirectorSceneBinding(structuredClone(broken)); assert.deepEqual(first, second); assert.equal(deeplyFrozen(first), true); assert.equal(first.findings.every((entry) => deeplyFrozen(entry) && Object.isFrozen(entry.path)), true); assert.equal(new Set(first.findings.map((entry) => JSON.stringify(entry))).size, first.findings.length); const priority = { fatal: 0, error: 1, warning: 2, info: 3 } as const; assert.equal(first.findings.every((entry, index) => index === 0 || priority[first.findings[index - 1].severity] <= priority[entry.severity]), true); assert.equal(first.errorCount, first.findings.filter((entry) => entry.severity === "error").length); assert.equal(first.fatalCount, first.findings.filter((entry) => entry.severity === "fatal").length); assert.equal(first.valid, false); assert.equal(first.findings.filter((entry) => entry.code === "SCENE_BINDING_PARENT_REFERENCE_INVALID").length >= 1, true); });

  it("guards result shapes and resolves all four immutable summary states", () => { const clean = validation.validateNexoraObjectDirectorSceneBinding(input()); assert.equal(validation.isNexoraObjectDirectorSceneBindingValidationResult(clean), true); assert.equal(validation.isNexoraObjectDirectorSceneBindingValidationResult({ valid: true }), false); const fabricated = (severity: "warning" | "error" | "fatal") => freeze({ valid: severity === "warning", findings: [{ code: "SCENE_BINDING_UNKNOWN_FIELD" as const, severity, message: severity, path: [] }], errorCount: severity === "error" ? 1 : 0, warningCount: severity === "warning" ? 1 : 0, fatalCount: severity === "fatal" ? 1 : 0, infoCount: 0, checkedNodeCount: 0, checkedBindingCount: 0 }); assert.equal(validation.getNexoraObjectDirectorSceneBindingValidationSummary(clean).status, "valid"); assert.equal(validation.getNexoraObjectDirectorSceneBindingValidationSummary(fabricated("warning")).status, "valid-with-warnings"); assert.equal(validation.getNexoraObjectDirectorSceneBindingValidationSummary(fabricated("error")).status, "invalid"); assert.equal(validation.getNexoraObjectDirectorSceneBindingValidationSummary(fabricated("fatal")).status, "fatal"); for (const value of [clean, fabricated("warning"), fabricated("error"), fabricated("fatal")]) { const summary = validation.getNexoraObjectDirectorSceneBindingValidationSummary(value); assert.equal(summary.findingCount, value.findings.length); assert.equal(deeplyFrozen(summary), true); } });

  it("verifies NOL-6:2 compatibility and the local validation registry", () => { assert.equal(sceneBindingContractId, "NOL-6:2/NexoraObjectDirectorSceneBindingContracts"); assert.equal(sceneBindingContractCount, sceneBindingContractRegistry.length); const required = ["SceneNodeContract", "RendererBindingContract", "RendererStateContract", "VisibilityContract", "InteractionModeContract", "SceneBindingValidationContract"]; assert.equal(required.every((name) => sceneBindingContractRegistry.some((entry) => entry.contractName === name)), true); const registry = validation.getNexoraObjectDirectorSceneBindingValidationRegistry(); assert.equal(registry, validation.nexoraObjectDirectorSceneBindingValidationRegistry); assert.deepEqual(registry.map((entry) => entry.order), Array.from({ length: registry.length }, (_, index) => index + 1)); assert.equal(validation.getNexoraObjectDirectorSceneBindingValidationRegistryCount(), registry.length); assert.equal(validation.nexoraObjectDirectorSceneBindingValidationRegistryCount, registry.length); assert.equal(validation.isNexoraObjectDirectorSceneBindingValidationRegistryFrozen(), true); assert.equal(validation.verifyNexoraObjectDirectorSceneBindingValidationRegistry().valid, true); assert.equal(validation.nexoraObjectDirectorSceneBindingValidationCapabilities.includes("cycle-detection"), true); assert.equal(validation.nexoraObjectDirectorSceneBindingValidationCapabilities.includes("contract-registry-compatibility"), true); assert.equal(deeplyFrozen(registry), true); });

  it("contains no forbidden dependency, execution, mutation, or nondeterminism", () => { assert.doesNotMatch(source, /from\s+["'][^"']*(?:Foundation|renderer|runtime|react|next|three|ui|canvas|webgl)/i); assert.doesNotMatch(source, /\b(?:async|await|Promise|setTimeout|setInterval|requestAnimationFrame|fetch|window|document|localStorage|sessionStorage|Math\.random|Date\b|Worker|process|console\.)\b/); assert.doesNotMatch(source, /\b(?:useState|useEffect|createElement|addEventListener|dispatchEvent|subscribe|observe)\s*\(/); assert.doesNotMatch(source, /class\s+[A-Za-z_$]|extends\s+[A-Za-z_$]/); assert.doesNotMatch(source, /new\s+(?:Mesh|Scene|Renderer|Object3D|Map|Set|Date|Promise)\s*\(/); });
});
