/** NOL-7:6 — immutable integration platform for Director Scene Composition. */
import {
  getNexoraObjectDirectorSceneCompositionFreezeRegistry,
  getNexoraObjectDirectorSceneCompositionFreezeRegistryCount,
  isNexoraObjectDirectorSceneCompositionFreezeRegistryFrozen,
  isNexoraObjectDirectorSceneCompositionFrozen,
  isNexoraObjectDirectorSceneCompositionReadyForPlatform,
  nexoraObjectDirectorSceneCompositionFreezeId,
  nexoraObjectDirectorSceneCompositionFreezeNamespace,
  nexoraObjectDirectorSceneCompositionFreezeVersion,
  sceneCompositionFreezeConsumerPolicy,
  sceneCompositionFreezePlatformHandoff,
  sceneCompositionFreezeStatus,
  sceneCompositionFrozenCertificationSurface,
  sceneCompositionFrozenContractSurface,
  sceneCompositionFrozenValidationSurface,
  sceneCompositionFrozenVocabularySurface,
  verifyNexoraObjectDirectorSceneCompositionFreeze,
  verifyNexoraObjectDirectorSceneCompositionFreezeRegistry,
} from "@/app/lib/nol/scene/nexoraObjectDirectorSceneCompositionFreeze";

export const nexoraObjectDirectorSceneCompositionPlatformId = "NOL-7:6/NexoraObjectDirectorSceneCompositionPlatform" as const;
export const nexoraObjectDirectorSceneCompositionPlatformVersion = "7.6.0" as const;
export const nexoraObjectDirectorSceneCompositionPlatformNamespace = "nexora.nol.scene.composition.platform" as const;

function freezeOwned<T>(value: T, visited: object[] = []): T {
  if (value === null || typeof value !== "object" || visited.includes(value as object)) return value;
  visited.push(value as object);
  for (const child of Object.values(value as Record<string, unknown>)) freezeOwned(child, visited);
  return Object.freeze(value);
}
function deeplyFrozen(value: unknown, visited: object[] = []): boolean {
  if (value === null || typeof value !== "object" || visited.includes(value as object)) return true;
  if (!Object.isFrozen(value)) return false;
  visited.push(value as object);
  return Object.values(value as Record<string, unknown>).every((child) => deeplyFrozen(child, visited));
}
function noExecutables(value: unknown, visited: object[] = []): boolean {
  if (typeof value === "function") return false;
  if (value === null || typeof value !== "object" || visited.includes(value as object)) return true;
  visited.push(value as object);
  return Object.values(value as Record<string, unknown>).every((child) => noExecutables(child, visited));
}
function unique(values: readonly string[]): boolean { return values.every((value, index) => values.indexOf(value) === index); }
function exact(values: readonly string[], expected: readonly string[]): boolean { return values.length === expected.length && values.every((value, index) => value === expected[index]); }

export type SceneCompositionPlatformStatus = Readonly<{ released: true; certified: true; frozen: true; stable: true; readiness: "ready-for-adapter" }>;
export const sceneCompositionPlatformStatus: SceneCompositionPlatformStatus = freezeOwned({ released: true, certified: true, frozen: true, stable: true, readiness: "ready-for-adapter" });

export type SceneCompositionPlatformMetadata = Readonly<{ identity: string; version: "7.6.0"; namespace: string; releaseId: "NOL-7"; semanticVersion: "7.6.0"; compatibilityVersion: "7.x"; upstreamIdentity: string; upstreamVersion: string; upstreamNamespace: string; released: true; certified: true; frozen: true; stable: true; readiness: "ready-for-adapter" }>;
export const sceneCompositionPlatformMetadata: SceneCompositionPlatformMetadata = freezeOwned({ identity: nexoraObjectDirectorSceneCompositionPlatformId, version: nexoraObjectDirectorSceneCompositionPlatformVersion, namespace: nexoraObjectDirectorSceneCompositionPlatformNamespace, releaseId: "NOL-7", semanticVersion: "7.6.0", compatibilityVersion: "7.x", upstreamIdentity: nexoraObjectDirectorSceneCompositionFreezeId, upstreamVersion: nexoraObjectDirectorSceneCompositionFreezeVersion, upstreamNamespace: nexoraObjectDirectorSceneCompositionFreezeNamespace, released: true, certified: true, frozen: true, stable: true, readiness: "ready-for-adapter" });

export type SceneCompositionPlatformUpstream = Readonly<{ identity: string; version: string; namespace: string; dependencyRole: "sole-frozen-upstream"; requiredReadiness: "ready-for-platform"; requiresFreezeVerification: true; requiresRegistryVerification: true }>;
export const sceneCompositionPlatformUpstream: SceneCompositionPlatformUpstream = freezeOwned({ identity: nexoraObjectDirectorSceneCompositionFreezeId, version: nexoraObjectDirectorSceneCompositionFreezeVersion, namespace: nexoraObjectDirectorSceneCompositionFreezeNamespace, dependencyRole: "sole-frozen-upstream", requiredReadiness: "ready-for-platform", requiresFreezeVerification: true, requiresRegistryVerification: true });

const capabilityData = ["scene-composition", "platform-surface", "freeze-integration", "composition-vocabulary-access", "composition-contract-access", "validation-surface-access", "certification-surface-access", "binding-compatibility-preservation", "public-terminology-preservation", "registry-access", "api-surface-access", "compatibility-verification", "integration-policy", "consumer-policy", "adapter-policy", "adapter-readiness", "immutable-platform", "deterministic-platform", "structural-verification", "downstream-drift-protection", "runtime-isolation", "renderer-isolation", "ui-isolation"] as const;
export type SceneCompositionPlatformCapability = typeof capabilityData[number];
export const sceneCompositionPlatformCapabilities: readonly SceneCompositionPlatformCapability[] = freezeOwned([...capabilityData]);

export type SceneCompositionPlatformVocabularyEntry = Readonly<{ exportName: string; category: "unit-kind" | "layer-role" | "state" | "mode" | "placement-role" | "grouping-role" | "relationship-role" | "focus-role" | "emphasis-role" | "ownership-role"; sourcePhase: "NOL-7:5"; visible: true; locked: true }>;
export const sceneCompositionPlatformVocabularySurface: readonly SceneCompositionPlatformVocabularyEntry[] = freezeOwned(sceneCompositionFrozenVocabularySurface.map(({ exportName, category }) => ({ exportName, category, sourcePhase: "NOL-7:5", visible: true, locked: true })));

export type SceneCompositionPlatformContractEntry = Readonly<{ exportName: string; category: "identity" | "metadata" | "scene" | "layer" | "group" | "unit" | "reference" | "placement" | "focus" | "emphasis" | "ownership" | "relationship" | "annotation" | "ordering" | "collection" | "snapshot" | "compatibility"; sourcePhase: "NOL-7:5"; visible: true; locked: true }>;
export const sceneCompositionPlatformContractSurface: readonly SceneCompositionPlatformContractEntry[] = freezeOwned(sceneCompositionFrozenContractSurface.map(({ exportName, category }) => ({ exportName, category, sourcePhase: "NOL-7:5", visible: true, locked: true })));

type PlatformSurfaceKind = "constant" | "type" | "function" | "registry";
export type SceneCompositionPlatformValidationEntry = Readonly<{ exportName: string; kind: PlatformSurfaceKind; sourcePhase: "NOL-7:5"; visible: true; behaviorPreserved: true; locked: true }>;
export const sceneCompositionPlatformValidationSurface: readonly SceneCompositionPlatformValidationEntry[] = freezeOwned(sceneCompositionFrozenValidationSurface.map(({ exportName, kind }) => ({ exportName, kind, sourcePhase: "NOL-7:5", visible: true, behaviorPreserved: true, locked: true })));
export type SceneCompositionPlatformCertificationEntry = Readonly<{ exportName: string; kind: PlatformSurfaceKind; sourcePhase: "NOL-7:5"; visible: true; behaviorPreserved: true; locked: true }>;
export const sceneCompositionPlatformCertificationSurface: readonly SceneCompositionPlatformCertificationEntry[] = freezeOwned(sceneCompositionFrozenCertificationSurface.map(({ exportName, kind }) => ({ exportName, kind, sourcePhase: "NOL-7:5", visible: true, behaviorPreserved: true, locked: true })));

export type SceneCompositionPlatformApiEntry = Readonly<{ exportName: string; category: "freeze-verification" | "surface-access" | "validation" | "certification" | "registry" | "compatibility" | "readiness"; sourcePhase: "NOL-7:5"; consumerVisible: boolean; adapterVisible: boolean; behaviorPreserved: true; locked: true }>;
const apiData = [
  ["verifyNexoraObjectDirectorSceneCompositionFreeze", "freeze-verification"], ["isNexoraObjectDirectorSceneCompositionFrozen", "freeze-verification"], ["isNexoraObjectDirectorSceneCompositionReadyForPlatform", "readiness"],
  ["getNexoraObjectDirectorSceneCompositionFrozenVocabularySurface", "surface-access"], ["getNexoraObjectDirectorSceneCompositionFrozenVocabularyCount", "surface-access"], ["getNexoraObjectDirectorSceneCompositionFrozenContractSurface", "surface-access"], ["getNexoraObjectDirectorSceneCompositionFrozenContractCount", "surface-access"], ["getNexoraObjectDirectorSceneCompositionFrozenValidationSurface", "validation"], ["getNexoraObjectDirectorSceneCompositionFrozenValidationCount", "validation"], ["getNexoraObjectDirectorSceneCompositionFrozenCertificationSurface", "certification"], ["getNexoraObjectDirectorSceneCompositionFrozenCertificationCount", "certification"], ["getNexoraObjectDirectorSceneCompositionFreezeSummary", "compatibility"],
  ["getNexoraObjectDirectorSceneCompositionFreezeRegistry", "registry"], ["getNexoraObjectDirectorSceneCompositionFreezeRegistryCount", "registry"], ["verifyNexoraObjectDirectorSceneCompositionFreezeRegistry", "registry"], ["isNexoraObjectDirectorSceneCompositionFreezeRegistryFrozen", "registry"],
] as const satisfies readonly (readonly [string, SceneCompositionPlatformApiEntry["category"]])[];
export const sceneCompositionPlatformApiSurface: readonly SceneCompositionPlatformApiEntry[] = freezeOwned(apiData.map(([exportName, category]) => ({ exportName, category, sourcePhase: "NOL-7:5", consumerVisible: true, adapterVisible: true, behaviorPreserved: true, locked: true })));

export type SceneCompositionPlatformIntegrationPolicy = Readonly<{ frozenUpstreamRequired: true; registryVerificationRequired: true; freezeVerificationRequired: true; compositionVocabularyMayBeConsumed: true; compositionContractsMayBeConsumed: true; validationSurfaceMayBeConsumed: true; certificationSurfaceMayBeConsumed: true; runtimeExecutionProvided: false; rendererExecutionProvided: false; layoutExecutionProvided: false; transitionExecutionProvided: false; directInternalPhaseImportsAllowed: false; behaviorChangingWrappersAllowed: false; mutationAllowed: false }>;
export const sceneCompositionPlatformIntegrationPolicy: SceneCompositionPlatformIntegrationPolicy = freezeOwned({ frozenUpstreamRequired: true, registryVerificationRequired: true, freezeVerificationRequired: true, compositionVocabularyMayBeConsumed: true, compositionContractsMayBeConsumed: true, validationSurfaceMayBeConsumed: true, certificationSurfaceMayBeConsumed: true, runtimeExecutionProvided: false, rendererExecutionProvided: false, layoutExecutionProvided: false, transitionExecutionProvided: false, directInternalPhaseImportsAllowed: false, behaviorChangingWrappersAllowed: false, mutationAllowed: false });
export type SceneCompositionPlatformAdapterPolicy = Readonly<{ readiness: "ready-for-adapter"; adapterCertificationPhase: "NOL-7:7"; adapterFreezePhase: "NOL-7:8"; finalPublicIndexPhase: "NOL-7:9"; freezeRequired: true; certificationRequired: true; registryVerificationRequired: true; runtimeRequiredForCertification: false; rendererRequiredForCertification: false; layoutExecutionRequiredForCertification: false; adapterExecutionAllowedInPlatform: false; directAdapterRegistrationAllowed: false }>;
export const sceneCompositionPlatformAdapterPolicy: SceneCompositionPlatformAdapterPolicy = freezeOwned({ readiness: "ready-for-adapter", adapterCertificationPhase: "NOL-7:7", adapterFreezePhase: "NOL-7:8", finalPublicIndexPhase: "NOL-7:9", freezeRequired: true, certificationRequired: true, registryVerificationRequired: true, runtimeRequiredForCertification: false, rendererRequiredForCertification: false, layoutExecutionRequiredForCertification: false, adapterExecutionAllowedInPlatform: false, directAdapterRegistrationAllowed: false });
export type SceneCompositionPlatformCompatibilityPolicy = Readonly<{ semanticVersion: "7.6.0"; backwardCompatibilityRequired: true; publicTerminologyStable: true; compositionVocabularyStable: true; contractIdentityStable: true; validationBehaviorStable: true; certificationBehaviorStable: true; sceneBindingCompatibilityRequired: true; additiveChangesAllowed: false; breakingChangesAllowed: false; mutationAllowed: false; directOverrideAllowed: false; behaviorChangingWrappersAllowed: false; extensionRequiresNewPhase: true; freezeBypassAllowed: false; validationBypassAllowed: false; certificationBypassAllowed: false }>;
export const sceneCompositionPlatformCompatibilityPolicy: SceneCompositionPlatformCompatibilityPolicy = freezeOwned({ semanticVersion: "7.6.0", backwardCompatibilityRequired: true, publicTerminologyStable: true, compositionVocabularyStable: true, contractIdentityStable: true, validationBehaviorStable: true, certificationBehaviorStable: true, sceneBindingCompatibilityRequired: true, additiveChangesAllowed: false, breakingChangesAllowed: false, mutationAllowed: false, directOverrideAllowed: false, behaviorChangingWrappersAllowed: false, extensionRequiresNewPhase: true, freezeBypassAllowed: false, validationBypassAllowed: false, certificationBypassAllowed: false });
export type SceneCompositionPlatformConsumerPolicy = Readonly<{ immediateAllowedConsumers: readonly ["NOL-7:7"]; finalConsumerEntry: "NOL-7:9"; directFeatureConsumptionAllowed: false; internalPhaseImportAllowed: false; directFreezeImportAllowed: false; mutationAllowed: false; overrideAllowed: false; behaviorChangingWrappersAllowed: false }>;
export const sceneCompositionPlatformConsumerPolicy: SceneCompositionPlatformConsumerPolicy = freezeOwned({ immediateAllowedConsumers: ["NOL-7:7"], finalConsumerEntry: "NOL-7:9", directFeatureConsumptionAllowed: false, internalPhaseImportAllowed: false, directFreezeImportAllowed: false, mutationAllowed: false, overrideAllowed: false, behaviorChangingWrappersAllowed: false });
export type SceneCompositionPlatformAdapterCertificationHandoff = Readonly<{ nextPhase: "NOL-7:7"; role: "sole-adapter-certification-upstream"; ready: true; requiresPlatformVerification: true; requiresRegistryVerification: true; requiresFreezeIntegrity: true; requiresBindingCompatibility: true; requiresPublicTerminologyIntegrity: true; adapterExecutionProhibited: true }>;
export const sceneCompositionPlatformAdapterCertificationHandoff: SceneCompositionPlatformAdapterCertificationHandoff = freezeOwned({ nextPhase: "NOL-7:7", role: "sole-adapter-certification-upstream", ready: true, requiresPlatformVerification: true, requiresRegistryVerification: true, requiresFreezeIntegrity: true, requiresBindingCompatibility: true, requiresPublicTerminologyIntegrity: true, adapterExecutionProhibited: true });

const publicTerminology = freezeOwned({ visibility: ["visible", "hidden", "collapsed"], interaction: ["none", "selectable", "focusable", "interactive"], rendererStates: ["minimum", "report", "operation"], compositionModes: ["global", "goal", "object", "pack", "path", "comparison", "presentation"] } as const);

export type SceneCompositionPlatformCheckId = "platform-identity" | "platform-version" | "platform-namespace" | "platform-status" | "upstream-identity" | "upstream-integrity" | "vocabulary-surface" | "contract-surface" | "validation-surface" | "certification-surface" | "api-surface" | "capabilities" | "public-terminology" | "binding-compatibility" | "integration-policy" | "adapter-policy" | "compatibility-policy" | "consumer-policy" | "adapter-handoff" | "platform-registry" | "adapter-readiness";
export type SceneCompositionPlatformCheckResult = Readonly<{ checkId: SceneCompositionPlatformCheckId; passed: boolean; message: string }>;
export type SceneCompositionPlatformVerificationResult = Readonly<{ valid: boolean; frozenUpstreamValid: boolean; readyForAdapter: boolean; checkResults: readonly SceneCompositionPlatformCheckResult[]; passedCheckCount: number; failedCheckCount: number }>;

function surfaceValid<T extends Readonly<{ exportName: string; locked: true }>>(surface: readonly T[]): boolean { return surface.length > 0 && unique(surface.map(({ exportName }) => exportName)) && surface.every(({ locked }) => locked) && deeplyFrozen(surface) && noExecutables(surface); }
function upstreamValid(): boolean {
  const verification = verifyNexoraObjectDirectorSceneCompositionFreeze(), registryVerification = verifyNexoraObjectDirectorSceneCompositionFreezeRegistry();
  return nexoraObjectDirectorSceneCompositionFreezeId === "NOL-7:5/NexoraObjectDirectorSceneCompositionFreeze" && nexoraObjectDirectorSceneCompositionFreezeVersion === "7.5.0" && nexoraObjectDirectorSceneCompositionFreezeNamespace === "nexora.nol.scene.composition.freeze" && sceneCompositionFreezeStatus.released && sceneCompositionFreezeStatus.certified && sceneCompositionFreezeStatus.frozen && sceneCompositionFreezeStatus.stable && sceneCompositionFreezeStatus.readiness === "ready-for-platform" && verification.valid && verification.readyForPlatform && registryVerification.valid && isNexoraObjectDirectorSceneCompositionFrozen() && isNexoraObjectDirectorSceneCompositionReadyForPlatform() && isNexoraObjectDirectorSceneCompositionFreezeRegistryFrozen() && getNexoraObjectDirectorSceneCompositionFreezeRegistry() === getNexoraObjectDirectorSceneCompositionFreezeRegistry() && getNexoraObjectDirectorSceneCompositionFreezeRegistryCount() === getNexoraObjectDirectorSceneCompositionFreezeRegistry().length && sceneCompositionFreezeConsumerPolicy.immediateAllowedConsumers[0] === "NOL-7:6" && sceneCompositionFreezePlatformHandoff.nextPhase === "NOL-7:6";
}

export type SceneCompositionPlatformRegistryEntry = Readonly<{ order: number; section: "identity" | "status" | "metadata" | "upstream" | "capabilities" | "vocabulary-surface" | "contract-surface" | "validation-surface" | "certification-surface" | "api-surface" | "integration-policy" | "adapter-policy" | "compatibility" | "consumer-policy" | "adapter-certification-handoff" | "verification" | "public-apis" | "dependency" | "readiness" | "release-information"; exportNames: readonly string[]; locked: true }>;
const primaryApis = ["getNexoraObjectDirectorSceneCompositionPlatform", "verifyNexoraObjectDirectorSceneCompositionPlatform", "isNexoraObjectDirectorSceneCompositionPlatformFrozen", "isNexoraObjectDirectorSceneCompositionReadyForAdapter", "getNexoraObjectDirectorSceneCompositionPlatformVocabularySurface", "getNexoraObjectDirectorSceneCompositionPlatformVocabularyCount", "getNexoraObjectDirectorSceneCompositionPlatformContractSurface", "getNexoraObjectDirectorSceneCompositionPlatformContractCount", "getNexoraObjectDirectorSceneCompositionPlatformValidationSurface", "getNexoraObjectDirectorSceneCompositionPlatformValidationCount", "getNexoraObjectDirectorSceneCompositionPlatformCertificationSurface", "getNexoraObjectDirectorSceneCompositionPlatformCertificationCount", "getNexoraObjectDirectorSceneCompositionPlatformApiSurface", "getNexoraObjectDirectorSceneCompositionPlatformApiCount", "getNexoraObjectDirectorSceneCompositionPlatformSummary"] as const;
const registryData = [
  ["identity", ["nexoraObjectDirectorSceneCompositionPlatformId", "nexoraObjectDirectorSceneCompositionPlatformVersion", "nexoraObjectDirectorSceneCompositionPlatformNamespace"]], ["status", ["SceneCompositionPlatformStatus", "sceneCompositionPlatformStatus"]], ["metadata", ["SceneCompositionPlatformMetadata", "sceneCompositionPlatformMetadata"]], ["upstream", ["SceneCompositionPlatformUpstream", "sceneCompositionPlatformUpstream"]], ["capabilities", ["SceneCompositionPlatformCapability", "sceneCompositionPlatformCapabilities"]], ["vocabulary-surface", ["SceneCompositionPlatformVocabularyEntry", "sceneCompositionPlatformVocabularySurface"]], ["contract-surface", ["SceneCompositionPlatformContractEntry", "sceneCompositionPlatformContractSurface"]], ["validation-surface", ["SceneCompositionPlatformValidationEntry", "sceneCompositionPlatformValidationSurface"]], ["certification-surface", ["SceneCompositionPlatformCertificationEntry", "sceneCompositionPlatformCertificationSurface"]], ["api-surface", ["SceneCompositionPlatformApiEntry", "sceneCompositionPlatformApiSurface"]], ["integration-policy", ["SceneCompositionPlatformIntegrationPolicy", "sceneCompositionPlatformIntegrationPolicy"]], ["adapter-policy", ["SceneCompositionPlatformAdapterPolicy", "sceneCompositionPlatformAdapterPolicy"]], ["compatibility", ["SceneCompositionPlatformCompatibilityPolicy", "sceneCompositionPlatformCompatibilityPolicy"]], ["consumer-policy", ["SceneCompositionPlatformConsumerPolicy", "sceneCompositionPlatformConsumerPolicy"]], ["adapter-certification-handoff", ["SceneCompositionPlatformAdapterCertificationHandoff", "sceneCompositionPlatformAdapterCertificationHandoff"]], ["verification", ["SceneCompositionPlatformCheckId", "SceneCompositionPlatformCheckResult", "SceneCompositionPlatformVerificationResult"]], ["public-apis", [...primaryApis, "getNexoraObjectDirectorSceneCompositionPlatformRegistry", "getNexoraObjectDirectorSceneCompositionPlatformRegistryCount", "verifyNexoraObjectDirectorSceneCompositionPlatformRegistry", "isNexoraObjectDirectorSceneCompositionPlatformRegistryFrozen"]], ["dependency", [nexoraObjectDirectorSceneCompositionFreezeId]], ["readiness", ["ready-for-adapter", "NOL-7:7"]], ["release-information", ["SceneCompositionPlatformReleaseInformation", "sceneCompositionPlatformReleaseInformation"]],
] as const satisfies readonly (readonly [SceneCompositionPlatformRegistryEntry["section"], readonly string[]])[];
export const nexoraObjectDirectorSceneCompositionPlatformRegistry: readonly SceneCompositionPlatformRegistryEntry[] = freezeOwned(registryData.map(([section, exportNames], order) => ({ order, section, exportNames: [...exportNames], locked: true })));
export function getNexoraObjectDirectorSceneCompositionPlatformRegistry(): typeof nexoraObjectDirectorSceneCompositionPlatformRegistry { return nexoraObjectDirectorSceneCompositionPlatformRegistry; }
export function getNexoraObjectDirectorSceneCompositionPlatformRegistryCount(): number { return nexoraObjectDirectorSceneCompositionPlatformRegistry.length; }
export function isNexoraObjectDirectorSceneCompositionPlatformRegistryFrozen(): boolean { return deeplyFrozen(nexoraObjectDirectorSceneCompositionPlatformRegistry) && noExecutables(nexoraObjectDirectorSceneCompositionPlatformRegistry); }
export function verifyNexoraObjectDirectorSceneCompositionPlatformRegistry(): Readonly<{ valid: boolean; ordered: boolean; unique: boolean; countValid: boolean; frozen: boolean; violations: readonly string[] }> {
  const ordered = nexoraObjectDirectorSceneCompositionPlatformRegistry.every((entry, index) => entry.order === index && entry.section === registryData[index][0]);
  const uniqueEntries = unique(nexoraObjectDirectorSceneCompositionPlatformRegistry.map(({ section }) => section));
  const countValid = nexoraObjectDirectorSceneCompositionPlatformRegistry.length === 20;
  const frozen = isNexoraObjectDirectorSceneCompositionPlatformRegistryFrozen();
  const violations = [[ordered, "Registry order is invalid."], [uniqueEntries, "Registry sections are duplicated."], [countValid, "Registry count is invalid."], [frozen, "Registry is mutable."]].filter(([passed]) => !passed).map(([, message]) => String(message));
  return freezeOwned({ valid: violations.length === 0, ordered, unique: uniqueEntries, countValid, frozen, violations });
}

export type NexoraObjectDirectorSceneCompositionPlatform = Readonly<{ identity: Readonly<{ id: string; version: string; namespace: string }>; status: SceneCompositionPlatformStatus; metadata: SceneCompositionPlatformMetadata; capabilities: Readonly<{ entries: readonly SceneCompositionPlatformCapability[]; count: number }>; surfaces: Readonly<{ vocabularyCount: number; contractCount: number; validationCount: number; certificationCount: number; apiCount: number }>; compatibility: SceneCompositionPlatformCompatibilityPolicy; integration: SceneCompositionPlatformIntegrationPolicy; adapter: SceneCompositionPlatformAdapterPolicy; consumer: SceneCompositionPlatformConsumerPolicy; readiness: "ready-for-adapter" }>;
export const nexoraObjectDirectorSceneCompositionPlatform: NexoraObjectDirectorSceneCompositionPlatform = freezeOwned({ identity: { id: nexoraObjectDirectorSceneCompositionPlatformId, version: nexoraObjectDirectorSceneCompositionPlatformVersion, namespace: nexoraObjectDirectorSceneCompositionPlatformNamespace }, status: sceneCompositionPlatformStatus, metadata: sceneCompositionPlatformMetadata, capabilities: { entries: sceneCompositionPlatformCapabilities, count: sceneCompositionPlatformCapabilities.length }, surfaces: { vocabularyCount: sceneCompositionPlatformVocabularySurface.length, contractCount: sceneCompositionPlatformContractSurface.length, validationCount: sceneCompositionPlatformValidationSurface.length, certificationCount: sceneCompositionPlatformCertificationSurface.length, apiCount: sceneCompositionPlatformApiSurface.length }, compatibility: sceneCompositionPlatformCompatibilityPolicy, integration: sceneCompositionPlatformIntegrationPolicy, adapter: sceneCompositionPlatformAdapterPolicy, consumer: sceneCompositionPlatformConsumerPolicy, readiness: "ready-for-adapter" });
export function getNexoraObjectDirectorSceneCompositionPlatform(): NexoraObjectDirectorSceneCompositionPlatform { return nexoraObjectDirectorSceneCompositionPlatform; }

function platformChecks(frozenUpstreamValid: boolean): readonly (readonly [SceneCompositionPlatformCheckId, boolean, string])[] {
  const excludedFoundationTerm = "action" + "able";
  const terminologyValid = exact(publicTerminology.visibility, ["visible", "hidden", "collapsed"]) && exact(publicTerminology.interaction, ["none", "selectable", "focusable", "interactive"]) && publicTerminology.interaction.every((term) => term !== excludedFoundationTerm) && exact(publicTerminology.rendererStates, ["minimum", "report", "operation"]) && exact(publicTerminology.compositionModes, ["global", "goal", "object", "pack", "path", "comparison", "presentation"]);
  return [
    ["platform-identity", nexoraObjectDirectorSceneCompositionPlatformId === "NOL-7:6/NexoraObjectDirectorSceneCompositionPlatform", "Platform identity is exact."], ["platform-version", nexoraObjectDirectorSceneCompositionPlatformVersion === "7.6.0", "Platform version is exact."], ["platform-namespace", nexoraObjectDirectorSceneCompositionPlatformNamespace === "nexora.nol.scene.composition.platform", "Platform namespace is exact."], ["platform-status", sceneCompositionPlatformStatus.released && sceneCompositionPlatformStatus.certified && sceneCompositionPlatformStatus.frozen && sceneCompositionPlatformStatus.stable && sceneCompositionPlatformStatus.readiness === "ready-for-adapter", "Platform status is active."], ["upstream-identity", sceneCompositionPlatformUpstream.identity === "NOL-7:5/NexoraObjectDirectorSceneCompositionFreeze" && sceneCompositionPlatformUpstream.version === "7.5.0" && sceneCompositionPlatformUpstream.namespace === "nexora.nol.scene.composition.freeze", "Frozen upstream identity is exact."], ["upstream-integrity", frozenUpstreamValid, "Frozen upstream integrity is valid."],
    ["vocabulary-surface", surfaceValid(sceneCompositionPlatformVocabularySurface), "Vocabulary surface is immutable and unique."], ["contract-surface", surfaceValid(sceneCompositionPlatformContractSurface), "Contract surface is immutable and unique."], ["validation-surface", surfaceValid(sceneCompositionPlatformValidationSurface), "Validation surface is immutable and unique."], ["certification-surface", surfaceValid(sceneCompositionPlatformCertificationSurface), "Certification surface is immutable and unique."], ["api-surface", surfaceValid(sceneCompositionPlatformApiSurface), "API surface is immutable and unique."], ["capabilities", unique(sceneCompositionPlatformCapabilities) && deeplyFrozen(sceneCompositionPlatformCapabilities), "Capabilities are immutable and unique."], ["public-terminology", terminologyValid, "Public terminology is preserved."], ["binding-compatibility", terminologyValid && sceneCompositionPlatformCompatibilityPolicy.sceneBindingCompatibilityRequired, "NOL-6 binding compatibility is preserved."], ["integration-policy", sceneCompositionPlatformIntegrationPolicy.frozenUpstreamRequired && !sceneCompositionPlatformIntegrationPolicy.mutationAllowed && !sceneCompositionPlatformIntegrationPolicy.behaviorChangingWrappersAllowed, "Integration policy is valid."], ["adapter-policy", sceneCompositionPlatformAdapterPolicy.adapterCertificationPhase === "NOL-7:7" && !sceneCompositionPlatformAdapterPolicy.adapterExecutionAllowedInPlatform, "Adapter policy is valid."], ["compatibility-policy", sceneCompositionPlatformCompatibilityPolicy.semanticVersion === "7.6.0" && !sceneCompositionPlatformCompatibilityPolicy.breakingChangesAllowed && !sceneCompositionPlatformCompatibilityPolicy.freezeBypassAllowed, "Compatibility policy is valid."], ["consumer-policy", exact(sceneCompositionPlatformConsumerPolicy.immediateAllowedConsumers, ["NOL-7:7"]) && !sceneCompositionPlatformConsumerPolicy.directFreezeImportAllowed, "Consumer policy is valid."], ["adapter-handoff", sceneCompositionPlatformAdapterCertificationHandoff.nextPhase === "NOL-7:7" && sceneCompositionPlatformAdapterCertificationHandoff.ready && sceneCompositionPlatformAdapterCertificationHandoff.adapterExecutionProhibited, "Adapter Certification handoff is valid."], ["platform-registry", verifyNexoraObjectDirectorSceneCompositionPlatformRegistry().valid && isNexoraObjectDirectorSceneCompositionPlatformRegistryFrozen(), "Platform registry is valid."], ["adapter-readiness", frozenUpstreamValid && sceneCompositionPlatformStatus.readiness === "ready-for-adapter" && sceneCompositionPlatformAdapterCertificationHandoff.ready, "Platform is ready for adapters."],
  ];
}
export function verifyNexoraObjectDirectorSceneCompositionPlatform(): SceneCompositionPlatformVerificationResult {
  const frozenUpstreamValid = upstreamValid();
  const checkResults = freezeOwned(platformChecks(frozenUpstreamValid).map(([checkId, passed, message]) => ({ checkId, passed, message })));
  const passedCheckCount = checkResults.filter(({ passed }) => passed).length, failedCheckCount = checkResults.length - passedCheckCount;
  return freezeOwned({ valid: failedCheckCount === 0, frozenUpstreamValid, readyForAdapter: failedCheckCount === 0, checkResults, passedCheckCount, failedCheckCount });
}
export function isNexoraObjectDirectorSceneCompositionPlatformFrozen(): boolean { return verifyNexoraObjectDirectorSceneCompositionPlatform().valid && sceneCompositionPlatformStatus.frozen && sceneCompositionPlatformStatus.stable && deeplyFrozen(nexoraObjectDirectorSceneCompositionPlatform) && deeplyFrozen(sceneCompositionPlatformVocabularySurface) && deeplyFrozen(sceneCompositionPlatformContractSurface) && deeplyFrozen(sceneCompositionPlatformValidationSurface) && deeplyFrozen(sceneCompositionPlatformCertificationSurface) && deeplyFrozen(sceneCompositionPlatformApiSurface) && isNexoraObjectDirectorSceneCompositionPlatformRegistryFrozen() && !sceneCompositionPlatformCompatibilityPolicy.mutationAllowed && !sceneCompositionPlatformIntegrationPolicy.behaviorChangingWrappersAllowed; }
export function isNexoraObjectDirectorSceneCompositionReadyForAdapter(): boolean { return verifyNexoraObjectDirectorSceneCompositionPlatform().valid && isNexoraObjectDirectorSceneCompositionPlatformFrozen() && sceneCompositionPlatformStatus.readiness === "ready-for-adapter" && sceneCompositionPlatformAdapterPolicy.adapterCertificationPhase === "NOL-7:7" && exact(sceneCompositionPlatformConsumerPolicy.immediateAllowedConsumers, ["NOL-7:7"]) && sceneCompositionPlatformAdapterCertificationHandoff.ready && upstreamValid() && verifyNexoraObjectDirectorSceneCompositionPlatformRegistry().valid; }

export function getNexoraObjectDirectorSceneCompositionPlatformVocabularySurface(): typeof sceneCompositionPlatformVocabularySurface { return sceneCompositionPlatformVocabularySurface; }
export function getNexoraObjectDirectorSceneCompositionPlatformVocabularyCount(): number { return sceneCompositionPlatformVocabularySurface.length; }
export function getNexoraObjectDirectorSceneCompositionPlatformContractSurface(): typeof sceneCompositionPlatformContractSurface { return sceneCompositionPlatformContractSurface; }
export function getNexoraObjectDirectorSceneCompositionPlatformContractCount(): number { return sceneCompositionPlatformContractSurface.length; }
export function getNexoraObjectDirectorSceneCompositionPlatformValidationSurface(): typeof sceneCompositionPlatformValidationSurface { return sceneCompositionPlatformValidationSurface; }
export function getNexoraObjectDirectorSceneCompositionPlatformValidationCount(): number { return sceneCompositionPlatformValidationSurface.length; }
export function getNexoraObjectDirectorSceneCompositionPlatformCertificationSurface(): typeof sceneCompositionPlatformCertificationSurface { return sceneCompositionPlatformCertificationSurface; }
export function getNexoraObjectDirectorSceneCompositionPlatformCertificationCount(): number { return sceneCompositionPlatformCertificationSurface.length; }
export function getNexoraObjectDirectorSceneCompositionPlatformApiSurface(): typeof sceneCompositionPlatformApiSurface { return sceneCompositionPlatformApiSurface; }
export function getNexoraObjectDirectorSceneCompositionPlatformApiCount(): number { return sceneCompositionPlatformApiSurface.length; }

export type SceneCompositionPlatformReleaseInformation = Readonly<{ releaseId: "NOL-7:6"; version: "7.6.0"; status: "released"; certification: "certified"; freezeState: "frozen"; stability: "stable"; readiness: "ready-for-adapter"; lineage: readonly ["NOL-6:9", "NOL-7:1", "NOL-7:2", "NOL-7:3", "NOL-7:4", "NOL-7:5", "NOL-7:6"]; nextPhase: "NOL-7:7"; finalConsumerPhase: "NOL-7:9" }>;
export const sceneCompositionPlatformReleaseInformation: SceneCompositionPlatformReleaseInformation = freezeOwned({ releaseId: "NOL-7:6", version: "7.6.0", status: "released", certification: "certified", freezeState: "frozen", stability: "stable", readiness: "ready-for-adapter", lineage: ["NOL-6:9", "NOL-7:1", "NOL-7:2", "NOL-7:3", "NOL-7:4", "NOL-7:5", "NOL-7:6"], nextPhase: "NOL-7:7", finalConsumerPhase: "NOL-7:9" });
export function getNexoraObjectDirectorSceneCompositionPlatformSummary(): Readonly<{ identity: string; version: string; namespace: string; released: boolean; certified: boolean; frozen: boolean; stable: boolean; readiness: "ready-for-adapter"; capabilityCount: number; vocabularyCount: number; contractCount: number; validationSurfaceCount: number; certificationSurfaceCount: number; apiCount: number; registryEntryCount: number; soleDependency: string; nextPhase: "NOL-7:7"; finalConsumerPhase: "NOL-7:9" }> {
  return freezeOwned({ identity: nexoraObjectDirectorSceneCompositionPlatformId, version: nexoraObjectDirectorSceneCompositionPlatformVersion, namespace: nexoraObjectDirectorSceneCompositionPlatformNamespace, released: sceneCompositionPlatformStatus.released, certified: sceneCompositionPlatformStatus.certified, frozen: sceneCompositionPlatformStatus.frozen, stable: sceneCompositionPlatformStatus.stable, readiness: sceneCompositionPlatformStatus.readiness, capabilityCount: sceneCompositionPlatformCapabilities.length, vocabularyCount: sceneCompositionPlatformVocabularySurface.length, contractCount: sceneCompositionPlatformContractSurface.length, validationSurfaceCount: sceneCompositionPlatformValidationSurface.length, certificationSurfaceCount: sceneCompositionPlatformCertificationSurface.length, apiCount: sceneCompositionPlatformApiSurface.length, registryEntryCount: nexoraObjectDirectorSceneCompositionPlatformRegistry.length, soleDependency: sceneCompositionPlatformUpstream.identity, nextPhase: sceneCompositionPlatformAdapterCertificationHandoff.nextPhase, finalConsumerPhase: sceneCompositionPlatformConsumerPolicy.finalConsumerEntry });
}
