import assert from "node:assert/strict";
import { readdirSync, readFileSync } from "node:fs";
import { describe, it } from "node:test";
import * as foundation from "./nexoraObjectDirectorSceneBindingFoundation.ts";
import * as contracts from "./nexoraObjectDirectorSceneBindingContracts.ts";
import * as validation from "./nexoraObjectDirectorSceneBindingValidation.ts";
import * as certification from "./nexoraObjectDirectorSceneBindingCertification.ts";
import * as baseFreeze from "./nexoraObjectDirectorSceneBindingFreeze.ts";
import * as platform from "./nexoraObjectDirectorSceneBindingPlatform.ts";
import * as adapterCertification from "./nexoraObjectDirectorSceneBindingAdapterCertification.ts";
import * as adapterFreeze from "./nexoraObjectDirectorSceneBindingAdapterFreeze.ts";
import * as publicIndex from "./nexoraObjectDirectorSceneBindingPublicIndex.ts";

function deeplyFrozen(value: unknown, seen: object[] = []): boolean { if (value === null || typeof value !== "object" || seen.includes(value as object)) return true; if (!Object.isFrozen(value)) return false; seen.push(value as object); return Object.values(value as Record<string, unknown>).every((child) => deeplyFrozen(child, seen)); }
function plainData(value: unknown, seen: object[] = []): boolean { if (value === null || ["string", "number", "boolean", "undefined"].includes(typeof value)) return true; if (typeof value !== "object" || seen.includes(value as object)) return false; const prototype = Object.getPrototypeOf(value); if (!Array.isArray(value) && prototype !== Object.prototype && prototype !== null) return false; seen.push(value as object); return Object.values(value as Record<string, unknown>).every((child) => plainData(child, seen)); }
const source = readFileSync(new URL("./nexoraObjectDirectorSceneBindingPublicIndex.ts", import.meta.url), "utf8");

describe("NOL-6:9 Director Scene Binding Public Index", () => {
  it("creates exactly the two requested NOL-6:9 files and no default export", () => { const files = readdirSync(new URL(".", import.meta.url)).filter((name) => name.startsWith("nexoraObjectDirectorSceneBindingPublicIndex")); assert.deepEqual(files.sort(), ["nexoraObjectDirectorSceneBindingPublicIndex.test.ts", "nexoraObjectDirectorSceneBindingPublicIndex.ts"]); assert.doesNotMatch(source, /\bexport\s+default\b/); });

  it("publishes the exact Public Index identity, lock, and summary identity", () => { assert.equal(publicIndex.nexoraObjectDirectorSceneBindingPublicIndexId, "NOL-6:9/NexoraObjectDirectorSceneBindingPublicIndex"); assert.equal(publicIndex.nexoraObjectDirectorSceneBindingPublicIndexVersion, "6.9.0"); assert.equal(publicIndex.nexoraObjectDirectorSceneBindingPublicIndexNamespace, "nexora.nol.scene.binding.public-index"); assert.deepEqual(publicIndex.nexoraObjectDirectorSceneBindingPublicIndexLock, { lockId: "NOL-6-DIRECTOR-SCENE-BINDING-PUBLIC-INDEX-LOCKED", active: true, reversible: false, scope: "director-scene-binding-public-index", version: "6.9.0" }); const summary = publicIndex.getNexoraObjectDirectorSceneBindingPublicIndexSummary(); assert.equal(summary.identity, publicIndex.nexoraObjectDirectorSceneBindingPublicIndexId); assert.equal(summary.version, publicIndex.nexoraObjectDirectorSceneBindingPublicIndexVersion); assert.equal(summary.namespace, publicIndex.nexoraObjectDirectorSceneBindingPublicIndexNamespace); assert.equal(deeplyFrozen(publicIndex.nexoraObjectDirectorSceneBindingPublicIndexLock), true); });

  it("activates every deeply frozen consumer-ready release status", () => { assert.deepEqual(publicIndex.sceneBindingPublicIndexStatus, { released: true, certified: true, frozen: true, stable: true, readiness: "ready-for-consumer" }); assert.equal(deeplyFrozen(publicIndex.sceneBindingPublicIndexStatus), true); });

  it("imports only NOL-6:8 Adapter Freeze", () => { const imports = [...source.matchAll(/from\s+["']([^"']+)["']/g)].map((match) => match[1]); assert.deepEqual(imports, ["./nexoraObjectDirectorSceneBindingAdapterFreeze.ts"]); assert.doesNotMatch(source, /from\s+["'][^"']*SceneBinding(?:Foundation|Contracts|Validation|Certification|Freeze|Platform|AdapterCertification)\.ts/i); assert.doesNotMatch(source, /from\s+["'][^"']*(?:runtime|renderer|react|next|three|ui|public.?index)/i); });

  it("derives immutable sole-upstream identity from NOL-6:8", () => { assert.deepEqual(publicIndex.sceneBindingPublicIndexUpstream, { identity: adapterFreeze.nexoraObjectDirectorSceneBindingAdapterFreezeId, version: adapterFreeze.nexoraObjectDirectorSceneBindingAdapterFreezeVersion, namespace: adapterFreeze.nexoraObjectDirectorSceneBindingAdapterFreezeNamespace, dependencyRole: "sole-public-index-upstream", requiredReadiness: "ready-for-public-index", requiresFreezeVerification: true, requiresRegistryVerification: true }); assert.equal(deeplyFrozen(publicIndex.sceneBindingPublicIndexUpstream), true); });

  it("directly re-exports approved NOL-6:8 values without identity-changing wrappers", () => { assert.equal(publicIndex.verifyNexoraObjectDirectorSceneBindingAdapterFreeze, adapterFreeze.verifyNexoraObjectDirectorSceneBindingAdapterFreeze); assert.equal(publicIndex.verifyNexoraObjectDirectorSceneBindingAdapterFreezeRegistry, adapterFreeze.verifyNexoraObjectDirectorSceneBindingAdapterFreezeRegistry); assert.equal(publicIndex.isNexoraObjectDirectorSceneBindingAdapterFrozen, adapterFreeze.isNexoraObjectDirectorSceneBindingAdapterFrozen); assert.equal(publicIndex.isNexoraObjectDirectorSceneBindingAdapterReadyForPublicIndex, adapterFreeze.isNexoraObjectDirectorSceneBindingAdapterReadyForPublicIndex); assert.equal(publicIndex.getNexoraObjectDirectorSceneBindingAdapterFreezeSummary, adapterFreeze.getNexoraObjectDirectorSceneBindingAdapterFreezeSummary); assert.equal(publicIndex.sceneBindingAdapterFreezeStatus, adapterFreeze.sceneBindingAdapterFreezeStatus); assert.equal(publicIndex.sceneBindingFrozenAdapterContractSurface, adapterFreeze.sceneBindingFrozenAdapterContractSurface); assert.equal(publicIndex.sceneBindingFrozenAdapterCertificationSurface, adapterFreeze.sceneBindingFrozenAdapterCertificationSurface); assert.equal(publicIndex.nexoraObjectDirectorSceneBindingAdapterFreezeId, adapterFreeze.nexoraObjectDirectorSceneBindingAdapterFreezeId); });

  it("publishes exactly nine ordered unique frozen namespace sections", () => { assert.deepEqual(publicIndex.sceneBindingPublicIndexNamespaceSections, ["identity", "public-types", "public-apis", "validation", "certification", "release-information", "compatibility", "registry", "consumer-information"]); assert.equal(publicIndex.sceneBindingPublicIndexNamespaceSectionCount, 9); assert.equal(new Set(publicIndex.sceneBindingPublicIndexNamespaceSections).size, 9); assert.equal(deeplyFrozen(publicIndex.sceneBindingPublicIndexNamespaceSections), true); });

  it("preserves the exact public terminology without aliases", () => { assert.deepEqual(publicIndex.sceneBindingPublicVisibilityValues, ["visible", "hidden", "collapsed"]); assert.deepEqual(publicIndex.sceneBindingPublicInteractionValues, ["none", "selectable", "focusable", "interactive"]); assert.deepEqual(publicIndex.sceneBindingPublicRendererStates, ["minimum", "report", "operation"]); assert.equal(publicIndex.sceneBindingPublicInteractionValues.includes("actionable" as never), false); for (const value of [publicIndex.sceneBindingPublicVisibilityValues, publicIndex.sceneBindingPublicInteractionValues, publicIndex.sceneBindingPublicRendererStates]) assert.equal(deeplyFrozen(value), true); });

  it("publishes an ordered unique locked Public Type registry", () => { const registry = publicIndex.getNexoraObjectDirectorSceneBindingPublicTypeRegistry(), names = registry.map((entry) => entry.exportName), required = ["NexoraDirectorSceneNodeKind", "NexoraDirectorSceneNodeVisibility", "NexoraDirectorSceneInteractionMode", "RendererBindingContract", "VisibilityContract", "InteractionModeContract", "SceneBindingValidationInput", "SceneBindingValidationResult", "SceneBindingCertificationEvidence", "SceneBindingCertificationResult", "SceneBindingPlatformMetadata", "SceneBindingPlatformAdapterPolicy", "SceneBindingAdapter", "SceneBindingAdapterCertificationResult", "SceneBindingAdapterFreezeStatus"]; assert.equal(required.every((name) => names.includes(name)), true); assert.equal(registry.length, 56); assert.equal(publicIndex.sceneBindingPublicTypeCount, registry.length); assert.equal(publicIndex.getNexoraObjectDirectorSceneBindingPublicTypeCount(), registry.length); assert.equal(registry, publicIndex.sceneBindingPublicTypeRegistry); assert.equal(new Set(names).size, names.length); assert.equal(registry.every((entry) => entry.consumerVisible && entry.locked && ["foundation", "contract", "validation", "certification", "platform", "adapter", "release"].includes(entry.category)), true); assert.equal(deeplyFrozen(registry), true); assert.equal(plainData(registry), true); });

  it("publishes an ordered unique behavior-preserving Public API registry", () => { const registry = publicIndex.getNexoraObjectDirectorSceneBindingPublicApiRegistry(), names = registry.map((entry) => entry.exportName), required = ["validateNexoraObjectDirectorSceneBinding", "getNexoraObjectDirectorSceneBindingValidationSummary", "certifyNexoraObjectDirectorSceneBinding", "getNexoraObjectDirectorSceneBindingCertificationSummary", "verifyNexoraObjectDirectorSceneBindingPlatform", "certifyNexoraObjectDirectorSceneBindingAdapter", "isNexoraObjectDirectorSceneBindingAdapterFreezeEligible", "verifyNexoraObjectDirectorSceneBindingAdapterFreeze", "isNexoraObjectDirectorSceneBindingAdapterReadyForPublicIndex"], forbidden = ["unlock", "reset", "override", "executeAdapter", "render"]; assert.equal(required.every((name) => names.includes(name)), true); assert.equal(registry.length, 31); assert.equal(publicIndex.sceneBindingPublicApiCount, registry.length); assert.equal(publicIndex.getNexoraObjectDirectorSceneBindingPublicApiCount(), registry.length); assert.equal(registry, publicIndex.sceneBindingPublicApiRegistry); assert.equal(new Set(names).size, names.length); assert.equal(registry.every((entry) => entry.behaviorPreserved && entry.consumerVisible && entry.locked), true); assert.equal(registry.some((entry) => forbidden.includes(entry.exportName)), false); assert.equal(deeplyFrozen(registry), true); assert.equal(plainData(registry), true); });

  it("publishes the complete declarative Validation surface", () => { const surface = publicIndex.sceneBindingPublicValidationSurface; assert.equal(surface.available, true); assert.equal(surface.identity, validation.nexoraObjectDirectorSceneBindingValidationId); assert.deepEqual(surface.severities, validation.sceneBindingValidationSeverities); assert.deepEqual(surface.codes, validation.sceneBindingValidationCodes); assert.equal(["validateNexoraObjectDirectorSceneBinding", "validateNexoraObjectDirectorSceneNode", "validateNexoraObjectDirectorSceneHierarchy", "validateNexoraObjectDirectorRendererBinding", "isNexoraObjectDirectorSceneBindingValidationResult", "getNexoraObjectDirectorSceneBindingValidationSummary"].every((name) => surface.entryPoints.includes(name)), true); assert.equal(surface.behaviorPreserved, true); assert.equal(deeplyFrozen(surface), true); });

  it("publishes the complete declarative Certification surface", () => { const surface = publicIndex.sceneBindingPublicCertificationSurface; assert.equal(surface.available, true); assert.equal(surface.identity, certification.nexoraObjectDirectorSceneBindingCertificationId); assert.deepEqual(surface.levels, certification.sceneBindingCertificationLevels); assert.deepEqual(surface.outcomes, certification.sceneBindingCertificationOutcomes); assert.deepEqual(surface.severities, certification.sceneBindingCertificationSeverities); assert.deepEqual(surface.codes, certification.sceneBindingCertificationCodes); assert.equal(surface.requirementCount, certification.sceneBindingCertificationRequirements.length); assert.equal(["certifyNexoraObjectDirectorSceneBinding", "evaluateNexoraObjectDirectorSceneBindingRequirement", "resolveNexoraObjectDirectorSceneBindingCertificationOutcome", "isNexoraObjectDirectorSceneBindingCertificationResult", "getNexoraObjectDirectorSceneBindingCertificationSummary"].every((name) => surface.entryPoints.includes(name)), true); assert.equal(deeplyFrozen(surface), true); });

  it("publishes the complete declarative Adapter Certification surface", () => { const surface = publicIndex.sceneBindingPublicAdapterCertificationSurface; assert.equal(surface.available, true); assert.equal(surface.identity, adapterCertification.nexoraObjectDirectorSceneBindingAdapterCertificationId); assert.deepEqual(surface.levels, adapterCertification.sceneBindingAdapterCertificationLevels); assert.deepEqual(surface.codes, adapterCertification.sceneBindingAdapterCertificationCodes); assert.deepEqual(surface.adapterContractFields, adapterFreeze.sceneBindingFrozenAdapterContractSurface.map((entry) => entry.fieldName)); assert.equal(["certifyNexoraObjectDirectorSceneBindingAdapter", "isNexoraObjectDirectorSceneBindingAdapterCertified", "isNexoraObjectDirectorSceneBindingAdapterFreezeEligible", "getNexoraObjectDirectorSceneBindingAdapterCertificationSummary", "verifyNexoraObjectDirectorSceneBindingAdapterCertification"].every((name) => surface.entryPoints.includes(name)), true); assert.equal(surface.entryPoints.some((name) => /execute|render|mount|invoke/i.test(name)), false); assert.equal(deeplyFrozen(surface), true); });

  it("publishes complete immutable NOL-6 release information", () => { assert.deepEqual(publicIndex.sceneBindingPublicReleaseInformation, { releaseId: "NOL-6", version: "6.9.0", status: "released", certification: "certified", freezeState: "frozen", stability: "stable", readiness: "ready-for-consumer", lockId: "NOL-6-DIRECTOR-SCENE-BINDING-PUBLIC-INDEX-LOCKED", lineage: ["NOL-6:1", "NOL-6:2", "NOL-6:3", "NOL-6:4", "NOL-6:5", "NOL-6:6", "NOL-6:7", "NOL-6:8", "NOL-6:9"] }); assert.equal(deeplyFrozen(publicIndex.sceneBindingPublicReleaseInformation), true); });

  it("publishes the exact drift-prevention compatibility policy", () => { assert.deepEqual(publicIndex.sceneBindingPublicIndexCompatibility, { semanticVersion: "6.9.0", backwardCompatibilityRequired: true, publicIdentityStable: true, publicTypeIdentityStable: true, publicApiIdentityStable: true, behaviorChangingWrappersAllowed: false, breakingChangesAllowed: false, silentAdditiveChangesAllowed: false, mutationAllowed: false, directOverrideAllowed: false, extensionRequiresNewPhase: true, freezeBypassAllowed: false, certificationBypassAllowed: false }); assert.equal(deeplyFrozen(publicIndex.sceneBindingPublicIndexCompatibility), true); });

  it("publishes the exact sole-entry consumer information", () => { assert.deepEqual(publicIndex.sceneBindingPublicIndexConsumerInformation, { supportedImportPath: "@/app/lib/nol/scene/nexoraObjectDirectorSceneBindingPublicIndex", soleConsumerEntryPoint: true, directInternalPhaseImportsAllowed: false, allowedConsumerTypes: ["director-runtime", "renderer-adapter", "executive-experience", "visualization-engine", "testing"], mutationAllowed: false, overrideAllowed: false, wrapperBehaviorChangesAllowed: false }); assert.equal(deeplyFrozen(publicIndex.sceneBindingPublicIndexConsumerInformation), true); });

  it("publishes all 15 mandatory ordered unique consumer rules", () => { const ids = publicIndex.sceneBindingPublicIndexConsumerRules.map((entry) => entry.id), required = ["consumer-imports-public-index-only", "consumer-must-not-import-foundation-directly", "consumer-must-not-import-contracts-directly", "consumer-must-not-import-validation-directly", "consumer-must-not-import-certification-directly", "consumer-must-not-import-freeze-directly", "consumer-must-not-import-platform-directly", "consumer-must-not-import-adapter-certification-directly", "consumer-must-not-import-adapter-freeze-directly", "consumer-must-not-mutate-public-exports", "consumer-must-not-override-public-semantics", "consumer-must-preserve-interactive-terminology", "consumer-must-not-execute-hidden-adapter-behavior", "consumer-must-use-approved-validation-entry-points", "consumer-must-use-approved-certification-entry-points"]; assert.deepEqual(ids, required); assert.equal(publicIndex.sceneBindingPublicIndexConsumerRuleCount, required.length); assert.equal(new Set(ids).size, ids.length); assert.equal(publicIndex.sceneBindingPublicIndexConsumerRules.every((entry) => entry.mandatory && entry.locked && entry.description.length > 0), true); assert.equal(deeplyFrozen(publicIndex.sceneBindingPublicIndexConsumerRules), true); });

  it("aggregates exactly nine deeply frozen logical namespace sections", () => { const value = publicIndex.nexoraObjectDirectorSceneBindingPublicIndex; assert.deepEqual(Object.keys(value), ["identity", "publicTypes", "publicApis", "validation", "certification", "releaseInformation", "compatibility", "registry", "consumerInformation"]); assert.equal(value.identity.id, publicIndex.nexoraObjectDirectorSceneBindingPublicIndexId); assert.equal(value.publicTypes.count, publicIndex.sceneBindingPublicTypeRegistry.length); assert.equal(value.publicApis.count, publicIndex.sceneBindingPublicApiRegistry.length); assert.equal(value.validation.available, true); assert.equal(value.certification.available, true); assert.equal(value.releaseInformation.readiness, "ready-for-consumer"); assert.equal(value.compatibility, publicIndex.sceneBindingPublicIndexCompatibility); assert.equal(value.registry.entryCount, 9); assert.equal(value.registry.verified, true); assert.equal(value.registry.frozen, true); assert.equal(value.consumerInformation, publicIndex.sceneBindingPublicIndexConsumerInformation); assert.equal(deeplyFrozen(value), true); assert.equal(plainData(value), true); });

  it("publishes and verifies the exact nine-section frozen Public Index registry", () => { const registry = publicIndex.getNexoraObjectDirectorSceneBindingPublicIndexRegistry(); assert.equal(registry, publicIndex.nexoraObjectDirectorSceneBindingPublicIndexRegistry); assert.deepEqual(registry.map((entry) => entry.section), publicIndex.sceneBindingPublicIndexNamespaceSections); assert.deepEqual(registry.map((entry) => entry.order), Array.from({ length: 9 }, (_, index) => index + 1)); assert.equal(registry.every((entry) => entry.locked && entry.exportNames.length > 0 && deeplyFrozen(entry.exportNames)), true); assert.equal(publicIndex.nexoraObjectDirectorSceneBindingPublicIndexRegistryCount, 9); assert.equal(publicIndex.getNexoraObjectDirectorSceneBindingPublicIndexRegistryCount(), registry.length); assert.equal(new Set(registry.map((entry) => entry.section)).size, registry.length); const verification = publicIndex.verifyNexoraObjectDirectorSceneBindingPublicIndexRegistry(); assert.equal(verification.valid, true); assert.equal(verification.ordered, true); assert.equal(verification.unique, true); assert.equal(verification.countValid, true); assert.equal(verification.exportsValid, true); assert.equal(verification.frozen, true); assert.equal(publicIndex.isNexoraObjectDirectorSceneBindingPublicIndexRegistryFrozen(), true); assert.equal(deeplyFrozen(verification), true); });

  it("passes all 23 deterministic Public Index verification checks", () => { const first = publicIndex.verifyNexoraObjectDirectorSceneBindingPublicIndex(), second = publicIndex.verifyNexoraObjectDirectorSceneBindingPublicIndex(); assert.deepEqual(first, second); assert.equal(first.valid, true); assert.equal(first.readyForConsumer, true); assert.equal(first.soleConsumerEntryConfirmed, true); assert.equal(first.checkResults.length, 23); assert.equal(first.checkResults.every((entry) => entry.passed), true); assert.equal(new Set(first.checkResults.map((entry) => entry.checkId)).size, first.checkResults.length); assert.equal(first.passedCheckCount, first.checkResults.filter((entry) => entry.passed).length); assert.equal(first.failedCheckCount, first.checkResults.filter((entry) => !entry.passed).length); assert.equal(deeplyFrozen(first), true); });

  it("verifies the sole consumer entry deterministically", () => { const first = publicIndex.verifyNexoraObjectDirectorSceneBindingConsumerEntry(), second = publicIndex.verifyNexoraObjectDirectorSceneBindingConsumerEntry(); assert.deepEqual(first, second); assert.equal(first.valid, true); assert.equal(first.supportedImportPath, "@/app/lib/nol/scene/nexoraObjectDirectorSceneBindingPublicIndex"); assert.equal(first.soleConsumerEntryPoint, true); assert.equal(first.upstreamReady, true); assert.equal(first.registryValid, true); assert.equal(first.publicSurfaceFrozen, true); assert.equal(first.ruleCount, publicIndex.sceneBindingPublicIndexConsumerRules.length); assert.equal(first.checks.every((check) => check.endsWith(":passed")), true); assert.equal(deeplyFrozen(first), true); });

  it("reports canonical frozen and consumer-ready guards", () => { assert.equal(publicIndex.isNexoraObjectDirectorSceneBindingPublicIndexFrozen.length, 0); assert.equal(publicIndex.isNexoraObjectDirectorSceneBindingReadyForConsumer.length, 0); assert.equal(publicIndex.isNexoraObjectDirectorSceneBindingPublicIndexFrozen(), true); assert.equal(publicIndex.isNexoraObjectDirectorSceneBindingReadyForConsumer(), true); assert.equal(publicIndex.isNexoraObjectDirectorSceneBindingReadyForConsumer(), true); });

  it("returns the exact dynamic deeply frozen Public Index summary", () => { const summary = publicIndex.getNexoraObjectDirectorSceneBindingPublicIndexSummary(); assert.deepEqual(summary, { identity: publicIndex.nexoraObjectDirectorSceneBindingPublicIndexId, version: publicIndex.nexoraObjectDirectorSceneBindingPublicIndexVersion, namespace: publicIndex.nexoraObjectDirectorSceneBindingPublicIndexNamespace, status: "released", certification: "certified", freezeState: "frozen", stability: "stable", readiness: "ready-for-consumer", namespaceSectionCount: publicIndex.sceneBindingPublicIndexNamespaceSections.length, publicTypeCount: publicIndex.sceneBindingPublicTypeRegistry.length, publicApiCount: publicIndex.sceneBindingPublicApiRegistry.length, consumerRuleCount: publicIndex.sceneBindingPublicIndexConsumerRules.length, registryEntryCount: publicIndex.nexoraObjectDirectorSceneBindingPublicIndexRegistry.length, soleDependency: adapterFreeze.nexoraObjectDirectorSceneBindingAdapterFreezeId, supportedImportPath: "@/app/lib/nol/scene/nexoraObjectDirectorSceneBindingPublicIndex", lineageCount: publicIndex.sceneBindingPublicReleaseInformation.lineage.length }); assert.equal(deeplyFrozen(summary), true); assert.deepEqual(summary, publicIndex.getNexoraObjectDirectorSceneBindingPublicIndexSummary()); });

  it("does not mutate upstream values or freeze caller-owned objects", () => { const before = JSON.stringify({ status: adapterFreeze.sceneBindingAdapterFreezeStatus, registry: adapterFreeze.nexoraObjectDirectorSceneBindingAdapterFreezeRegistry, contract: adapterFreeze.sceneBindingFrozenAdapterContractSurface }), registryIdentity = adapterFreeze.nexoraObjectDirectorSceneBindingAdapterFreezeRegistry, caller = { marker: { value: 1 } }, guard = publicIndex.isNexoraObjectDirectorSceneBindingPublicIndexFrozen as unknown as (value: unknown) => boolean; assert.equal(guard(caller), true); assert.equal(JSON.stringify({ status: adapterFreeze.sceneBindingAdapterFreezeStatus, registry: adapterFreeze.nexoraObjectDirectorSceneBindingAdapterFreezeRegistry, contract: adapterFreeze.sceneBindingFrozenAdapterContractSurface }), before); assert.equal(adapterFreeze.nexoraObjectDirectorSceneBindingAdapterFreezeRegistry, registryIdentity); assert.equal(Object.isFrozen(caller), false); assert.equal(Object.isFrozen(caller.marker), false); });

  it("keeps all Public Index-owned metadata and generated results deeply immutable", () => { const values = [publicIndex.sceneBindingPublicIndexStatus, publicIndex.nexoraObjectDirectorSceneBindingPublicIndexLock, publicIndex.sceneBindingPublicIndexUpstream, publicIndex.sceneBindingPublicIndexNamespaceSections, publicIndex.sceneBindingPublicTypeRegistry, publicIndex.sceneBindingPublicApiRegistry, publicIndex.sceneBindingPublicValidationSurface, publicIndex.sceneBindingPublicCertificationSurface, publicIndex.sceneBindingPublicAdapterCertificationSurface, publicIndex.sceneBindingPublicReleaseInformation, publicIndex.sceneBindingPublicIndexCompatibility, publicIndex.sceneBindingPublicIndexConsumerInformation, publicIndex.sceneBindingPublicIndexConsumerRules, publicIndex.nexoraObjectDirectorSceneBindingPublicIndexRegistry, publicIndex.nexoraObjectDirectorSceneBindingPublicIndex, publicIndex.verifyNexoraObjectDirectorSceneBindingPublicIndexRegistry(), publicIndex.verifyNexoraObjectDirectorSceneBindingPublicIndex(), publicIndex.verifyNexoraObjectDirectorSceneBindingConsumerEntry(), publicIndex.getNexoraObjectDirectorSceneBindingPublicIndexSummary()]; for (const value of values) { assert.equal(deeplyFrozen(value), true); assert.equal(plainData(value), true); } });

  it("preserves the exact NOL-6:1 through NOL-6:9 lineage", () => { assert.equal(foundation.foundationId, "NOL-6:1/NexoraObjectDirectorSceneBindingFoundation"); assert.equal(contracts.sceneBindingContractId, "NOL-6:2/NexoraObjectDirectorSceneBindingContracts"); assert.equal(validation.nexoraObjectDirectorSceneBindingValidationId, "NOL-6:3/NexoraObjectDirectorSceneBindingValidation"); assert.equal(certification.nexoraObjectDirectorSceneBindingCertificationId, "NOL-6:4/NexoraObjectDirectorSceneBindingCertification"); assert.equal(baseFreeze.nexoraObjectDirectorSceneBindingFreezeId, "NOL-6:5/NexoraObjectDirectorSceneBindingFreeze"); assert.equal(platform.nexoraObjectDirectorSceneBindingPlatformId, "NOL-6:6/NexoraObjectDirectorSceneBindingPlatform"); assert.equal(adapterCertification.nexoraObjectDirectorSceneBindingAdapterCertificationId, "NOL-6:7/NexoraObjectDirectorSceneBindingAdapterCertification"); assert.equal(adapterFreeze.nexoraObjectDirectorSceneBindingAdapterFreezeId, "NOL-6:8/NexoraObjectDirectorSceneBindingAdapterFreeze"); assert.equal(publicIndex.nexoraObjectDirectorSceneBindingPublicIndexId, "NOL-6:9/NexoraObjectDirectorSceneBindingPublicIndex"); assert.equal(foundation.verifyNexoraDirectorSceneBindingFoundation().valid, true); assert.equal(contracts.verifySceneBindingContracts().valid, true); assert.equal(validation.verifyNexoraObjectDirectorSceneBindingValidationRegistry().valid, true); assert.equal(certification.verifyNexoraObjectDirectorSceneBindingCertificationRegistry().valid, true); assert.equal(baseFreeze.verifyNexoraObjectDirectorSceneBindingFreeze().valid, true); assert.equal(platform.verifyNexoraObjectDirectorSceneBindingPlatform().valid, true); assert.equal(adapterCertification.verifyNexoraObjectDirectorSceneBindingAdapterCertification().valid, true); assert.equal(adapterFreeze.verifyNexoraObjectDirectorSceneBindingAdapterFreeze().valid, true); });

  it("contains no runtime, rendering, adapter execution, framework, alternate index, or effects", () => { assert.doesNotMatch(source, /\basync\s+(?:function|\()/); assert.doesNotMatch(source, /\b(?:await|Promise|setTimeout|setInterval|requestAnimationFrame|fetch|window|document|localStorage|sessionStorage|Math\.random|Date\b|Worker|process|console\.)\b/); assert.doesNotMatch(source, /\b(?:useState|useEffect|createElement|addEventListener|dispatchEvent|subscribe|observe)\s*\(/); assert.doesNotMatch(source, /class\s+[A-Za-z_$]|extends\s+[A-Za-z_$]/); assert.doesNotMatch(source, /new\s+(?:Mesh|Scene|Renderer|Object3D|Map|Set|Date|Promise)\s*\(/); assert.doesNotMatch(source, /\b(?:execute|render|synchronize|mount|invoke)Adapter\s*\(/); assert.doesNotMatch(source, /\bexport\s+default\b/); assert.equal(Object.keys(publicIndex).some((name) => /(?:unlock|reset|override|replace|patch)/i.test(name)), false); });
});
