import assert from "node:assert/strict";
import { readdirSync, readFileSync } from "node:fs";
import { describe, it } from "node:test";
import * as foundation from "./nexoraObjectDirectorSceneBindingFoundation.ts";
import * as contracts from "./nexoraObjectDirectorSceneBindingContracts.ts";
import * as validation from "./nexoraObjectDirectorSceneBindingValidation.ts";
import * as certification from "./nexoraObjectDirectorSceneBindingCertification.ts";
import * as freeze from "./nexoraObjectDirectorSceneBindingFreeze.ts";
import * as platform from "./nexoraObjectDirectorSceneBindingPlatform.ts";
import * as adapterCertification from "./nexoraObjectDirectorSceneBindingAdapterCertification.ts";
import type { SceneBindingAdapter } from "./nexoraObjectDirectorSceneBindingAdapterCertification.ts";

function deeplyFrozen(value: unknown, seen: object[] = []): boolean { if (value === null || typeof value !== "object" || seen.includes(value as object)) return true; if (!Object.isFrozen(value)) return false; seen.push(value as object); return Object.values(value as Record<string, unknown>).every((child) => deeplyFrozen(child, seen)); }
function validAdapter(overrides: Partial<SceneBindingAdapter> = {}): SceneBindingAdapter { return { adapterId: "scene-binding:adapter", adapterName: "Scene Binding Visualization Bridge", adapterVersion: "1.0.0", platformVersion: platform.nexoraObjectDirectorSceneBindingPlatformVersion, capabilities: [...adapterCertification.sceneBindingAdapterRequiredCapabilities], supportedApis: [...adapterCertification.sceneBindingAdapterRequiredApis], dependencies: ["NOL-6:6"], ...overrides }; }
const source = readFileSync(new URL("./nexoraObjectDirectorSceneBindingAdapterCertification.ts", import.meta.url), "utf8");

describe("NOL-6:7 Director Scene Binding Adapter Certification", () => {
  it("creates exactly the two requested NOL-6:7 files", () => { const files = readdirSync(new URL(".", import.meta.url)).filter((name) => name.startsWith("nexoraObjectDirectorSceneBindingAdapterCertification")); assert.deepEqual(files.sort(), ["nexoraObjectDirectorSceneBindingAdapterCertification.test.ts", "nexoraObjectDirectorSceneBindingAdapterCertification.ts"]); });

  it("publishes exact identity and release readiness", () => { assert.equal(adapterCertification.nexoraObjectDirectorSceneBindingAdapterCertificationId, "NOL-6:7/NexoraObjectDirectorSceneBindingAdapterCertification"); assert.equal(adapterCertification.nexoraObjectDirectorSceneBindingAdapterCertificationVersion, "6.7.0"); assert.equal(adapterCertification.nexoraObjectDirectorSceneBindingAdapterCertificationNamespace, "nexora.nol.scene.binding.adapter.certification"); assert.deepEqual(adapterCertification.sceneBindingAdapterCertificationStatus, { released: true, certified: true, frozen: true, stable: true, readiness: "ready-for-adapter-freeze" }); assert.equal(deeplyFrozen(adapterCertification.sceneBindingAdapterCertificationStatus), true); });

  it("imports only NOL-6:6 Platform", () => { const imports = [...source.matchAll(/from\s+["']([^"']+)["']/g)].map((match) => match[1]); assert.deepEqual(imports, ["./nexoraObjectDirectorSceneBindingPlatform.ts"]); assert.doesNotMatch(source, /from\s+["'][^"']*(?:Foundation|Contracts|Validation|(?<!Adapter)Certification|Freeze|runtime|renderer|react|next|three|ui|public.?index)/i); });

  it("publishes five ordered unique deeply frozen certification levels", () => { assert.deepEqual(adapterCertification.sceneBindingAdapterCertificationLevels, ["identity", "platform", "capability", "compatibility", "release"]); assert.equal(adapterCertification.sceneBindingAdapterCertificationLevelCount, 5); assert.equal(new Set(adapterCertification.sceneBindingAdapterCertificationLevels).size, 5); assert.equal(deeplyFrozen(adapterCertification.sceneBindingAdapterCertificationLevels), true); });

  it("publishes all eleven canonical ordered unique frozen codes", () => { assert.deepEqual(adapterCertification.sceneBindingAdapterCertificationCodes, ["ADAPTER_CERTIFIED", "INVALID_IDENTITY", "INVALID_PLATFORM", "INVALID_CAPABILITY", "INVALID_API", "INVALID_METADATA", "INVALID_VERSION", "INVALID_DEPENDENCY", "NOT_PLATFORM_COMPATIBLE", "FREEZE_ELIGIBLE", "FREEZE_INELIGIBLE"]); assert.equal(adapterCertification.sceneBindingAdapterCertificationCodeCount, 11); assert.equal(new Set(adapterCertification.sceneBindingAdapterCertificationCodes).size, 11); assert.equal(deeplyFrozen(adapterCertification.sceneBindingAdapterCertificationCodes), true); });

  it("derives immutable required capabilities and APIs from NOL-6:6", () => { assert.deepEqual(adapterCertification.sceneBindingAdapterRequiredCapabilities, platform.sceneBindingPlatformCapabilities); assert.deepEqual(adapterCertification.sceneBindingAdapterRequiredApis, platform.sceneBindingPlatformApiSurface.map((entry) => entry.exportName)); assert.equal(adapterCertification.sceneBindingAdapterRequiredCapabilityCount, platform.sceneBindingPlatformCapabilities.length); assert.equal(adapterCertification.sceneBindingAdapterRequiredApiCount, platform.sceneBindingPlatformApiSurface.length); assert.equal(deeplyFrozen(adapterCertification.sceneBindingAdapterRequiredCapabilities), true); assert.equal(deeplyFrozen(adapterCertification.sceneBindingAdapterRequiredApis), true); });

  it("certifies a complete compatible adapter and makes it Freeze eligible", () => { const result = adapterCertification.certifyNexoraObjectDirectorSceneBindingAdapter(validAdapter()); assert.equal(result.certified, true); assert.equal(result.freezeEligible, true); assert.deepEqual(result.passedLevels, adapterCertification.sceneBindingAdapterCertificationLevels); assert.deepEqual(result.failedLevels, []); assert.equal(result.findings.some((entry) => entry.code === "ADAPTER_CERTIFIED" && entry.severity === "info"), true); assert.equal(result.findings.some((entry) => entry.code === "FREEZE_ELIGIBLE"), true); assert.equal(adapterCertification.isNexoraObjectDirectorSceneBindingAdapterCertified(result), true); assert.equal(adapterCertification.isNexoraObjectDirectorSceneBindingAdapterFreezeEligible(result), true); assert.equal(deeplyFrozen(result), true); });

  it("rejects invalid identity, version, and platform metadata", () => { const identity = adapterCertification.certifyNexoraObjectDirectorSceneBindingAdapter(validAdapter({ adapterId: " padded ", adapterName: "" })), version = adapterCertification.certifyNexoraObjectDirectorSceneBindingAdapter(validAdapter({ adapterVersion: "version-one" })), platformResult = adapterCertification.certifyNexoraObjectDirectorSceneBindingAdapter(validAdapter({ platformVersion: "6.5.0" })); assert.equal(identity.certified, false); assert.equal(identity.findings.some((entry) => entry.code === "INVALID_IDENTITY"), true); assert.equal(version.findings.some((entry) => entry.code === "INVALID_VERSION"), true); assert.equal(platformResult.findings.some((entry) => entry.code === "INVALID_PLATFORM"), true); for (const result of [identity, version, platformResult]) { assert.equal(result.freezeEligible, false); assert.equal(result.findings.some((entry) => entry.code === "FREEZE_INELIGIBLE"), true); } });

  it("rejects missing, duplicate, and noncanonical capability declarations", () => { const missing = adapterCertification.certifyNexoraObjectDirectorSceneBindingAdapter(validAdapter({ capabilities: adapterCertification.sceneBindingAdapterRequiredCapabilities.slice(1) })), duplicate = adapterCertification.certifyNexoraObjectDirectorSceneBindingAdapter(validAdapter({ capabilities: [...adapterCertification.sceneBindingAdapterRequiredCapabilities, adapterCertification.sceneBindingAdapterRequiredCapabilities[0]] })), reversed = adapterCertification.certifyNexoraObjectDirectorSceneBindingAdapter(validAdapter({ capabilities: [...adapterCertification.sceneBindingAdapterRequiredCapabilities].reverse() })); for (const result of [missing, duplicate, reversed]) { assert.equal(result.certified, false); assert.equal(result.findings.some((entry) => entry.code === "INVALID_CAPABILITY"), true); } });

  it("rejects missing, duplicate, and noncanonical API declarations", () => { const missing = adapterCertification.certifyNexoraObjectDirectorSceneBindingAdapter(validAdapter({ supportedApis: adapterCertification.sceneBindingAdapterRequiredApis.slice(1) })), duplicate = adapterCertification.certifyNexoraObjectDirectorSceneBindingAdapter(validAdapter({ supportedApis: [...adapterCertification.sceneBindingAdapterRequiredApis, adapterCertification.sceneBindingAdapterRequiredApis[0]] })), reversed = adapterCertification.certifyNexoraObjectDirectorSceneBindingAdapter(validAdapter({ supportedApis: [...adapterCertification.sceneBindingAdapterRequiredApis].reverse() })); for (const result of [missing, duplicate, reversed]) { assert.equal(result.certified, false); assert.equal(result.findings.some((entry) => entry.code === "INVALID_API"), true); } });

  it("rejects dependency bypass and executable or custom metadata", () => { const dependency = adapterCertification.certifyNexoraObjectDirectorSceneBindingAdapter(validAdapter({ dependencies: ["NOL-6:5"] })), executable = adapterCertification.certifyNexoraObjectDirectorSceneBindingAdapter({ ...validAdapter(), callback: () => true }); class AdapterMetadata { adapterId = "custom"; } const custom = adapterCertification.certifyNexoraObjectDirectorSceneBindingAdapter(new AdapterMetadata()); assert.equal(dependency.findings.some((entry) => entry.code === "INVALID_DEPENDENCY" && entry.severity === "fatal"), true); for (const result of [executable, custom]) { assert.equal(result.certified, false); assert.equal(result.findings.some((entry) => entry.code === "INVALID_METADATA"), true); } });

  it("returns immutable rejected results rather than throwing for ordinary invalid input", () => { for (const input of [null, undefined, [], 42, "adapter", {}, { adapterId: "only-id" }]) { let result: adapterCertification.SceneBindingAdapterCertificationResult | undefined; assert.doesNotThrow(() => { result = adapterCertification.certifyNexoraObjectDirectorSceneBindingAdapter(input); }); assert.equal(result?.certified, false); assert.equal(result?.freezeEligible, false); assert.equal(deeplyFrozen(result), true); } });

  it("does not mutate or freeze caller adapter metadata", () => { const adapter = validAdapter(), before = structuredClone(adapter), result = adapterCertification.certifyNexoraObjectDirectorSceneBindingAdapter(adapter); assert.equal(result.certified, true); assert.deepEqual(adapter, before); assert.equal(Object.isFrozen(adapter), false); assert.equal(Object.isFrozen(adapter.capabilities), false); assert.equal(Object.isFrozen(adapter.supportedApis), false); });

  it("produces deterministic canonical duplicate-free findings and results", () => { const adapter = validAdapter({ adapterId: "", adapterVersion: "bad", platformVersion: "bad", capabilities: [], supportedApis: [], dependencies: ["NOL-6:5"] }), first = adapterCertification.certifyNexoraObjectDirectorSceneBindingAdapter(adapter), second = adapterCertification.certifyNexoraObjectDirectorSceneBindingAdapter(structuredClone(adapter)); assert.deepEqual(first, second); assert.equal(new Set(first.findings.map((entry) => JSON.stringify(entry))).size, first.findings.length); const order = adapterCertification.sceneBindingAdapterCertificationCodes; assert.equal(first.findings.every((entry, index) => index === 0 || order.indexOf(first.findings[index - 1].code) <= order.indexOf(entry.code)), true); assert.equal(deeplyFrozen(first), true); });

  it("guards certified and Freeze-eligible results structurally", () => { const certified = adapterCertification.certifyNexoraObjectDirectorSceneBindingAdapter(validAdapter()), rejected = adapterCertification.certifyNexoraObjectDirectorSceneBindingAdapter(null), mutable = structuredClone(certified), before = structuredClone(mutable); assert.equal(adapterCertification.isNexoraObjectDirectorSceneBindingAdapterCertified(certified), true); assert.equal(adapterCertification.isNexoraObjectDirectorSceneBindingAdapterFreezeEligible(certified), true); assert.equal(adapterCertification.isNexoraObjectDirectorSceneBindingAdapterCertified(rejected), false); assert.equal(adapterCertification.isNexoraObjectDirectorSceneBindingAdapterFreezeEligible(rejected), false); assert.equal(adapterCertification.isNexoraObjectDirectorSceneBindingAdapterCertified({ ...mutable, failedLevels: ["release"] }), false); assert.equal(adapterCertification.isNexoraObjectDirectorSceneBindingAdapterCertified(mutable), true); assert.deepEqual(mutable, before); assert.equal(Object.isFrozen(mutable), false); });

  it("returns correct deeply frozen dynamic summaries", () => { const certified = adapterCertification.certifyNexoraObjectDirectorSceneBindingAdapter(validAdapter()), rejected = adapterCertification.certifyNexoraObjectDirectorSceneBindingAdapter(null), certifiedSummary = adapterCertification.getNexoraObjectDirectorSceneBindingAdapterCertificationSummary(certified), rejectedSummary = adapterCertification.getNexoraObjectDirectorSceneBindingAdapterCertificationSummary(rejected); assert.deepEqual(certifiedSummary, { adapterId: certified.adapterId, certified: true, freezeEligible: true, passedLevelCount: 5, failedLevelCount: 0, findingCount: certified.findings.length, nextPhase: "NOL-6:8" }); assert.equal(rejectedSummary.certified, false); assert.equal(rejectedSummary.freezeEligible, false); assert.equal(rejectedSummary.passedLevelCount, rejected.passedLevels.length); assert.equal(rejectedSummary.failedLevelCount, rejected.failedLevels.length); assert.equal(rejectedSummary.findingCount, rejected.findings.length); assert.equal(rejectedSummary.nextPhase, "NOL-6:8"); assert.equal(deeplyFrozen(certifiedSummary), true); assert.equal(deeplyFrozen(rejectedSummary), true); });

  it("publishes the immutable compatibility policy", () => { assert.deepEqual(adapterCertification.sceneBindingAdapterCompatibilityPolicy, { backwardCompatible: true, breakingChangesAllowed: false, overrideAllowed: false, mutationAllowed: false }); assert.equal(deeplyFrozen(adapterCertification.sceneBindingAdapterCompatibilityPolicy), true); });

  it("publishes and verifies the ordered nine-section frozen registry", () => { const registry = adapterCertification.getNexoraObjectDirectorSceneBindingAdapterCertificationRegistry(); assert.equal(registry, adapterCertification.nexoraObjectDirectorSceneBindingAdapterCertificationRegistry); assert.deepEqual(registry.map((entry) => entry.name), ["Identity", "Levels", "Codes", "Findings", "Result", "Registry", "Public APIs", "Dependency", "Release"]); assert.deepEqual(registry.map((entry) => entry.order), Array.from({ length: 9 }, (_, index) => index + 1)); assert.equal(adapterCertification.getNexoraObjectDirectorSceneBindingAdapterCertificationRegistryCount(), registry.length); assert.equal(adapterCertification.nexoraObjectDirectorSceneBindingAdapterCertificationRegistryCount, 9); assert.equal(adapterCertification.verifyNexoraObjectDirectorSceneBindingAdapterCertificationRegistry().valid, true); assert.equal(adapterCertification.isNexoraObjectDirectorSceneBindingAdapterCertificationRegistryFrozen(), true); assert.equal(deeplyFrozen(registry), true); });

  it("exports all nine Public APIs and passes layer verification", () => { const required = ["certifyNexoraObjectDirectorSceneBindingAdapter", "verifyNexoraObjectDirectorSceneBindingAdapterCertification", "isNexoraObjectDirectorSceneBindingAdapterCertified", "isNexoraObjectDirectorSceneBindingAdapterFreezeEligible", "getNexoraObjectDirectorSceneBindingAdapterCertificationSummary", "getNexoraObjectDirectorSceneBindingAdapterCertificationRegistry", "getNexoraObjectDirectorSceneBindingAdapterCertificationRegistryCount", "verifyNexoraObjectDirectorSceneBindingAdapterCertificationRegistry", "isNexoraObjectDirectorSceneBindingAdapterCertificationRegistryFrozen"]; assert.deepEqual(adapterCertification.nexoraObjectDirectorSceneBindingAdapterCertificationPublicApiSurface, required); assert.equal(adapterCertification.nexoraObjectDirectorSceneBindingAdapterCertificationPublicApiCount, 9); assert.equal(required.every((name) => typeof adapterCertification[name as keyof typeof adapterCertification] === "function"), true); const verification = adapterCertification.verifyNexoraObjectDirectorSceneBindingAdapterCertification(); assert.equal(verification.valid, true); assert.equal(verification.registryValid, true); assert.equal(verification.identityValid, true); assert.equal(verification.apiSurfaceValid, true); assert.equal(verification.capabilityDeclarationsValid, true); assert.equal(verification.dependencyDeclarationsValid, true); assert.equal(verification.releaseMetadataValid, true); assert.equal(verification.checkCount, 6); assert.equal(deeplyFrozen(verification), true); });

  it("preserves the full NOL-6:1 through NOL-6:6 lineage", () => { assert.equal(foundation.foundationId, "NOL-6:1/NexoraObjectDirectorSceneBindingFoundation"); assert.equal(contracts.sceneBindingContractId, "NOL-6:2/NexoraObjectDirectorSceneBindingContracts"); assert.equal(validation.nexoraObjectDirectorSceneBindingValidationId, "NOL-6:3/NexoraObjectDirectorSceneBindingValidation"); assert.equal(certification.nexoraObjectDirectorSceneBindingCertificationId, "NOL-6:4/NexoraObjectDirectorSceneBindingCertification"); assert.equal(freeze.nexoraObjectDirectorSceneBindingFreezeId, "NOL-6:5/NexoraObjectDirectorSceneBindingFreeze"); assert.equal(platform.nexoraObjectDirectorSceneBindingPlatformId, "NOL-6:6/NexoraObjectDirectorSceneBindingPlatform"); assert.equal(foundation.verifyNexoraDirectorSceneBindingFoundation().valid, true); assert.equal(contracts.verifySceneBindingContracts().valid, true); assert.equal(validation.verifyNexoraObjectDirectorSceneBindingValidationRegistry().valid, true); assert.equal(certification.verifyNexoraObjectDirectorSceneBindingCertificationRegistry().valid, true); assert.equal(freeze.verifyNexoraObjectDirectorSceneBindingFreeze().valid, true); assert.equal(platform.verifyNexoraObjectDirectorSceneBindingPlatform().valid, true); });

  it("contains no adapter execution, rendering, runtime, framework, synchronization, or effects", () => { assert.doesNotMatch(source, /\basync\s+(?:function|\()/); assert.doesNotMatch(source, /\b(?:await|Promise|setTimeout|setInterval|requestAnimationFrame|fetch|window|document|localStorage|sessionStorage|Math\.random|Date\b|Worker|process|console\.)\b/); assert.doesNotMatch(source, /\b(?:useState|useEffect|createElement|addEventListener|dispatchEvent|subscribe|observe)\s*\(/); assert.doesNotMatch(source, /class\s+[A-Za-z_$]|extends\s+[A-Za-z_$]/); assert.doesNotMatch(source, /new\s+(?:Mesh|Scene|Renderer|Object3D|Map|Set|Date|Promise)\s*\(/); assert.doesNotMatch(source, /\b(?:execute|render|synchronize|mount|invoke)Adapter\s*\(/); });
});
