import assert from "node:assert/strict";
import { readdirSync, readFileSync } from "node:fs";
import { describe, it } from "node:test";
import * as foundation from "./nexoraObjectDirectorSceneBindingFoundation.ts";
import * as contracts from "./nexoraObjectDirectorSceneBindingContracts.ts";
import * as validation from "./nexoraObjectDirectorSceneBindingValidation.ts";
import * as certification from "./nexoraObjectDirectorSceneBindingCertification.ts";
import * as baseFreeze from "./nexoraObjectDirectorSceneBindingFreeze.ts";
import * as platform from "./nexoraObjectDirectorSceneBindingPlatform.ts";
import * as adapterCertification from "./nexoraObjectDirectorSceneBindingAdapterCertification.ts";
import * as adapterFreeze from "./nexoraObjectDirectorSceneBindingAdapterFreeze.ts";

function deeplyFrozen(value: unknown, seen: object[] = []): boolean { if (value === null || typeof value !== "object" || seen.includes(value as object)) return true; if (!Object.isFrozen(value)) return false; seen.push(value as object); return Object.values(value as Record<string, unknown>).every((child) => deeplyFrozen(child, seen)); }
function plainData(value: unknown, seen: object[] = []): boolean { if (value === null || ["string", "number", "boolean", "undefined"].includes(typeof value)) return true; if (typeof value !== "object" || seen.includes(value as object)) return false; const prototype = Object.getPrototypeOf(value); if (!Array.isArray(value) && prototype !== Object.prototype && prototype !== null) return false; seen.push(value as object); return Object.values(value as Record<string, unknown>).every((child) => plainData(child, seen)); }
const source = readFileSync(new URL("./nexoraObjectDirectorSceneBindingAdapterFreeze.ts", import.meta.url), "utf8");

describe("NOL-6:8 Director Scene Binding Adapter Freeze", () => {
  it("creates exactly the two requested NOL-6:8 files", () => { const files = readdirSync(new URL(".", import.meta.url)).filter((name) => name.startsWith("nexoraObjectDirectorSceneBindingAdapterFreeze")); assert.deepEqual(files.sort(), ["nexoraObjectDirectorSceneBindingAdapterFreeze.test.ts", "nexoraObjectDirectorSceneBindingAdapterFreeze.ts"]); });

  it("publishes exact identity and preserves it in the summary", () => { assert.equal(adapterFreeze.nexoraObjectDirectorSceneBindingAdapterFreezeId, "NOL-6:8/NexoraObjectDirectorSceneBindingAdapterFreeze"); assert.equal(adapterFreeze.nexoraObjectDirectorSceneBindingAdapterFreezeVersion, "6.8.0"); assert.equal(adapterFreeze.nexoraObjectDirectorSceneBindingAdapterFreezeNamespace, "nexora.nol.scene.binding.adapter.freeze"); const summary = adapterFreeze.getNexoraObjectDirectorSceneBindingAdapterFreezeSummary(); assert.equal(summary.identity, adapterFreeze.nexoraObjectDirectorSceneBindingAdapterFreezeId); assert.equal(summary.version, adapterFreeze.nexoraObjectDirectorSceneBindingAdapterFreezeVersion); assert.equal(summary.namespace, adapterFreeze.nexoraObjectDirectorSceneBindingAdapterFreezeNamespace); });

  it("activates every immutable Adapter Freeze status", () => { assert.deepEqual(adapterFreeze.sceneBindingAdapterFreezeStatus, { released: true, certified: true, frozen: true, stable: true, readiness: "ready-for-public-index" }); assert.equal(deeplyFrozen(adapterFreeze.sceneBindingAdapterFreezeStatus), true); });

  it("publishes the exact active irreversible Adapter Freeze lock", () => { assert.deepEqual(adapterFreeze.nexoraObjectDirectorSceneBindingAdapterFreezeLock, { lockId: "NOL-6-DIRECTOR-SCENE-BINDING-ADAPTER-LOCKED", active: true, reversible: false, scope: "director-scene-binding-adapter", version: "6.8.0" }); assert.equal(deeplyFrozen(adapterFreeze.nexoraObjectDirectorSceneBindingAdapterFreezeLock), true); assert.equal(Object.keys(adapterFreeze).some((name) => /(?:unlock|reset|override|replace|patch)/i.test(name)), false); });

  it("imports only NOL-6:7 Adapter Certification", () => { const imports = [...source.matchAll(/from\s+["']([^"']+)["']/g)].map((match) => match[1]); assert.deepEqual(imports, ["./nexoraObjectDirectorSceneBindingAdapterCertification.ts"]); assert.doesNotMatch(source, /from\s+["'][^"']*SceneBinding(?:Foundation|Contracts|Validation|Certification|Freeze|Platform)\.ts/i); assert.doesNotMatch(source, /from\s+["'][^"']*(?:runtime|renderer|react|next|three|ui|public.?index)/i); });

  it("derives immutable sole-upstream metadata from NOL-6:7", () => { assert.deepEqual(adapterFreeze.sceneBindingAdapterFrozenUpstream, { identity: adapterCertification.nexoraObjectDirectorSceneBindingAdapterCertificationId, version: adapterCertification.nexoraObjectDirectorSceneBindingAdapterCertificationVersion, namespace: adapterCertification.nexoraObjectDirectorSceneBindingAdapterCertificationNamespace, dependencyRole: "sole-certified-upstream", requiredCertificationState: true, requiredFreezeEligibility: true, requiredReadiness: "ready-for-adapter-freeze" }); assert.equal(deeplyFrozen(adapterFreeze.sceneBindingAdapterFrozenUpstream), true); });

  it("publishes all ten canonical unique frozen invariant categories", () => { assert.deepEqual(adapterFreeze.sceneBindingAdapterFreezeInvariantCategories, ["identity", "dependency", "certification", "adapter-contract", "immutability", "api", "registry", "compatibility", "consumer", "release"]); assert.equal(adapterFreeze.sceneBindingAdapterFreezeInvariantCategoryCount, 10); assert.equal(new Set(adapterFreeze.sceneBindingAdapterFreezeInvariantCategories).size, 10); assert.equal(deeplyFrozen(adapterFreeze.sceneBindingAdapterFreezeInvariantCategories), true); });

  it("publishes all 77 mandatory locked invariants in canonical order", () => { const groups = [
    ["adapter-freeze-identity-fixed", "adapter-freeze-version-fixed", "adapter-freeze-namespace-fixed", "adapter-release-status-fixed", "adapter-lock-identity-fixed"],
    ["adapter-certification-is-sole-production-dependency", "no-foundation-direct-import", "no-contracts-direct-import", "no-validation-direct-import", "no-certification-direct-import", "no-base-freeze-direct-import", "no-platform-direct-import", "no-runtime-dependency", "no-renderer-dependency", "no-ui-dependency", "no-react-dependency", "no-threejs-dependency", "no-public-index-dependency"],
    ["upstream-adapter-certification-identity-fixed", "adapter-certified-state-required", "adapter-freeze-eligible-state-required", "rejected-adapter-not-accepted", "non-freeze-eligible-adapter-not-accepted", "certification-levels-preserved", "certification-codes-preserved", "certification-result-contract-preserved"],
    ["adapter-identity-contract-fixed", "adapter-version-contract-fixed", "platform-version-contract-fixed", "adapter-capability-contract-fixed", "supported-api-contract-fixed", "adapter-metadata-remains-plain-data", "no-executable-adapter-fields", "no-adapter-instance-storage", "no-adapter-execution"],
    ["all-adapter-freeze-exports-deeply-frozen", "no-caller-input-mutation", "no-caller-input-freezing", "no-imported-upstream-mutation", "no-mutable-api-surface", "no-mutable-registry", "no-runtime-state", "no-unlock-mechanism"],
    ["adapter-freeze-public-api-identities-fixed", "adapter-freeze-api-count-dynamic", "no-hidden-executable-api", "no-callback-api", "no-async-api", "no-runtime-api", "no-renderer-api", "no-certification-candidate-api"],
    ["adapter-freeze-registry-ordered", "adapter-freeze-registry-deeply-frozen", "adapter-freeze-registry-duplicate-free", "adapter-freeze-registry-count-dynamic", "adapter-freeze-registry-verifiable", "upstream-adapter-registry-compatible"],
    ["nol-6-adapter-lineage-preserved", "adapter-certification-contract-preserved", "semantic-version-fixed", "breaking-change-requires-new-phase", "downstream-cannot-redefine-adapter-freeze", "downstream-cannot-bypass-adapter-certification", "adapter-capabilities-cannot-be-silently-expanded", "adapter-supported-apis-cannot-be-silently-redefined"],
    ["public-index-is-only-immediate-consumer", "feature-consumers-must-use-public-index", "direct-feature-consumption-prohibited", "consumer-mutation-prohibited", "consumer-override-prohibited", "adapter-freeze-internals-not-consumer-visible"],
    ["released-state-required", "certified-state-required", "frozen-state-required", "stable-state-required", "ready-for-public-index-required", "all-mandatory-invariants-pass"],
  ], required = groups.flat(), ids = adapterFreeze.sceneBindingAdapterFreezeInvariants.map((entry) => entry.id); assert.equal(required.length, 77); assert.deepEqual(ids, required); assert.equal(adapterFreeze.sceneBindingAdapterFreezeInvariantCount, required.length); assert.equal(new Set(ids).size, ids.length); assert.equal(adapterFreeze.sceneBindingAdapterFreezeInvariants.every((entry) => entry.mandatory && entry.locked && entry.title.length > 0 && entry.description.length > 0), true); const order = adapterFreeze.sceneBindingAdapterFreezeInvariantCategories; assert.equal(adapterFreeze.sceneBindingAdapterFreezeInvariants.every((entry, index) => index === 0 || order.indexOf(adapterFreeze.sceneBindingAdapterFreezeInvariants[index - 1].category) <= order.indexOf(entry.category)), true); assert.equal(deeplyFrozen(adapterFreeze.sceneBindingAdapterFreezeInvariants), true); });

  it("locks the complete seven-field adapter metadata contract", () => { const surface = adapterFreeze.getNexoraObjectDirectorSceneBindingFrozenAdapterContractSurface(); assert.equal(surface, adapterFreeze.sceneBindingFrozenAdapterContractSurface); assert.deepEqual(surface.map((entry) => entry.fieldName), ["adapterId", "adapterName", "adapterVersion", "platformVersion", "capabilities", "supportedApis", "dependencies"]); assert.equal(surface.find((entry) => entry.fieldName === "dependencies")?.required, false); assert.equal(surface.filter((entry) => entry.fieldName !== "dependencies").every((entry) => entry.required), true); assert.equal(surface.every((entry) => entry.sourcePhase === "NOL-6:7" && entry.locked && typeof entry.fieldType === "string"), true); assert.equal(new Set(surface.map((entry) => entry.fieldName)).size, surface.length); assert.equal(adapterFreeze.getNexoraObjectDirectorSceneBindingFrozenAdapterContractCount(), surface.length); assert.equal(adapterFreeze.sceneBindingFrozenAdapterContractCount, 7); assert.equal(plainData(surface), true); assert.equal(deeplyFrozen(surface), true); });

  it("locks every approved NOL-6:7 export identity as plain certification metadata", () => { const surface = adapterFreeze.getNexoraObjectDirectorSceneBindingFrozenAdapterCertificationSurface(), names = surface.map((entry) => entry.exportName), required = ["nexoraObjectDirectorSceneBindingAdapterCertificationId", "SceneBindingAdapter", "sceneBindingAdapterCertificationLevels", "sceneBindingAdapterCertificationCodes", "SceneBindingAdapterCertificationFinding", "SceneBindingAdapterCertificationResult", "sceneBindingAdapterCompatibilityPolicy", "certifyNexoraObjectDirectorSceneBindingAdapter", "isNexoraObjectDirectorSceneBindingAdapterCertified", "isNexoraObjectDirectorSceneBindingAdapterFreezeEligible", "getNexoraObjectDirectorSceneBindingAdapterCertificationSummary", "nexoraObjectDirectorSceneBindingAdapterCertificationRegistry", "verifyNexoraObjectDirectorSceneBindingAdapterCertificationRegistry", "verifyNexoraObjectDirectorSceneBindingAdapterCertification"]; assert.equal(required.every((name) => names.includes(name)), true); assert.equal(surface.length, 32); assert.equal(adapterFreeze.sceneBindingFrozenAdapterCertificationCount, surface.length); assert.equal(adapterFreeze.getNexoraObjectDirectorSceneBindingFrozenAdapterCertificationCount(), surface.length); assert.equal(surface, adapterFreeze.sceneBindingFrozenAdapterCertificationSurface); assert.equal(new Set(names).size, names.length); assert.equal(surface.every((entry) => entry.sourcePhase === "NOL-6:7" && entry.locked && entry.publicIndexEligible), true); assert.equal(surface.some((entry) => /(?:assessAdapter|freezeOwned|canonicalFindings|certificationResult)/.test(entry.exportName)), false); assert.equal(plainData(surface), true); assert.equal(deeplyFrozen(surface), true); });

  it("publishes the exact frozen architectural compatibility policy", () => { assert.deepEqual(adapterFreeze.sceneBindingAdapterFreezeCompatibilityPolicy, { semanticVersion: "6.8.0", backwardCompatibilityRequired: true, additiveChangesAllowed: false, breakingChangesAllowed: false, mutationAllowed: false, directOverrideAllowed: false, adapterExecutionAllowed: false, extensionRequiresNewPhase: true, certificationBypassAllowed: false, platformBypassAllowed: false }); assert.equal(deeplyFrozen(adapterFreeze.sceneBindingAdapterFreezeCompatibilityPolicy), true); });

  it("publishes the exact frozen Public Index consumer policy", () => { assert.deepEqual(adapterFreeze.sceneBindingAdapterFreezeConsumerPolicy, { immediateAllowedConsumers: ["NOL-6:9"], finalConsumerEntry: "NOL-6:9", directFeatureConsumptionAllowed: false, internalContractImportAllowed: false, mutationAllowed: false, overrideAllowed: false }); assert.equal(deeplyFrozen(adapterFreeze.sceneBindingAdapterFreezeConsumerPolicy), true); });

  it("publishes a complete immutable Public Index handoff", () => { assert.deepEqual(adapterFreeze.sceneBindingAdapterFreezePublicIndexHandoff, { nextPhase: "NOL-6:9", role: "sole-public-index-upstream", ready: true, requiresFreezeVerification: true, requiresRegistryVerification: true, directConsumerImportsProhibited: true }); assert.equal(deeplyFrozen(adapterFreeze.sceneBindingAdapterFreezePublicIndexHandoff), true); });

  it("verifies all 24 required Adapter Freeze checks deterministically", () => { const first = adapterFreeze.verifyNexoraObjectDirectorSceneBindingAdapterFreeze(), second = adapterFreeze.verifyNexoraObjectDirectorSceneBindingAdapterFreeze(); assert.deepEqual(first, second); assert.equal(first.valid, true); assert.equal(first.lockActive, true); assert.equal(first.readyForPublicIndex, true); assert.equal(first.checkResults.length, 24); assert.equal(first.checkResults.every((entry) => entry.passed), true); assert.equal(new Set(first.checkResults.map((entry) => entry.checkId)).size, first.checkResults.length); assert.equal(first.passedCheckCount, first.checkResults.filter((entry) => entry.passed).length); assert.equal(first.failedCheckCount, first.checkResults.filter((entry) => !entry.passed).length); assert.equal(deeplyFrozen(first), true); });

  it("reports canonical frozen and Public Index-ready guards", () => { assert.equal(adapterFreeze.isNexoraObjectDirectorSceneBindingAdapterFrozen.length, 0); assert.equal(adapterFreeze.isNexoraObjectDirectorSceneBindingAdapterReadyForPublicIndex.length, 0); assert.equal(adapterFreeze.isNexoraObjectDirectorSceneBindingAdapterFrozen(), true); assert.equal(adapterFreeze.isNexoraObjectDirectorSceneBindingAdapterReadyForPublicIndex(), true); assert.equal(adapterFreeze.isNexoraObjectDirectorSceneBindingAdapterReadyForPublicIndex(), true); });

  it("returns the exact dynamic deeply frozen Adapter Freeze summary", () => { const summary = adapterFreeze.getNexoraObjectDirectorSceneBindingAdapterFreezeSummary(); assert.deepEqual(summary, { identity: adapterFreeze.nexoraObjectDirectorSceneBindingAdapterFreezeId, version: adapterFreeze.nexoraObjectDirectorSceneBindingAdapterFreezeVersion, namespace: adapterFreeze.nexoraObjectDirectorSceneBindingAdapterFreezeNamespace, lockId: adapterFreeze.nexoraObjectDirectorSceneBindingAdapterFreezeLock.lockId, released: true, certified: true, frozen: true, stable: true, readiness: "ready-for-public-index", invariantCount: adapterFreeze.sceneBindingAdapterFreezeInvariants.length, frozenAdapterContractCount: adapterFreeze.sceneBindingFrozenAdapterContractSurface.length, frozenCertificationApiCount: adapterFreeze.sceneBindingFrozenAdapterCertificationSurface.length, registryEntryCount: adapterFreeze.nexoraObjectDirectorSceneBindingAdapterFreezeRegistry.length, soleDependency: adapterCertification.nexoraObjectDirectorSceneBindingAdapterCertificationId, nextPhase: "NOL-6:9" }); assert.equal(deeplyFrozen(summary), true); assert.deepEqual(summary, adapterFreeze.getNexoraObjectDirectorSceneBindingAdapterFreezeSummary()); });

  it("publishes and verifies exactly 17 ordered frozen registry sections", () => { const registry = adapterFreeze.getNexoraObjectDirectorSceneBindingAdapterFreezeRegistry(); assert.equal(registry, adapterFreeze.nexoraObjectDirectorSceneBindingAdapterFreezeRegistry); assert.deepEqual(registry.map((entry) => entry.name), ["Identity", "Release Status", "Freeze Lock", "Certified Upstream", "Invariant Categories", "Freeze Invariants", "Frozen Adapter Contract Surface", "Frozen Certification Surface", "Compatibility Policy", "Consumer Policy", "Public Index Handoff", "Verification Contracts", "Public APIs", "Dependency Boundary", "Freeze Capabilities", "Readiness", "Release Information"]); assert.deepEqual(registry.map((entry) => entry.order), Array.from({ length: 17 }, (_, index) => index + 1)); assert.equal(adapterFreeze.nexoraObjectDirectorSceneBindingAdapterFreezeRegistryCount, 17); assert.equal(adapterFreeze.getNexoraObjectDirectorSceneBindingAdapterFreezeRegistryCount(), registry.length); assert.equal(new Set(registry.map((entry) => entry.name)).size, registry.length); const verification = adapterFreeze.verifyNexoraObjectDirectorSceneBindingAdapterFreezeRegistry(); assert.equal(verification.valid, true); assert.equal(verification.ordered, true); assert.equal(verification.unique, true); assert.equal(verification.countValid, true); assert.equal(verification.publicApisValid, true); assert.equal(verification.capabilitiesValid, true); assert.equal(verification.frozen, true); assert.equal(adapterFreeze.isNexoraObjectDirectorSceneBindingAdapterFreezeRegistryFrozen(), true); assert.equal(deeplyFrozen(verification), true); });

  it("publishes all 26 required capabilities and twelve Public APIs", () => { const capabilities = ["adapter-release-identity-lock", "adapter-certification-boundary-lock", "adapter-contract-lock", "adapter-capability-lock", "adapter-api-surface-lock", "dependency-boundary-lock", "registry-lock", "compatibility-lock", "consumer-policy-lock", "public-index-handoff-lock", "immutability-lock", "semantic-version-lock", "lineage-lock", "freeze-verification", "public-index-readiness-verification", "dynamic-contract-count", "dynamic-api-count", "dynamic-registry-count", "deep-immutability", "structural-integrity", "downstream-drift-protection", "certification-bypass-protection", "adapter-execution-prohibition", "runtime-isolation", "renderer-isolation", "ui-isolation"]; assert.deepEqual(adapterFreeze.nexoraObjectDirectorSceneBindingAdapterFreezeCapabilities, capabilities); assert.equal(adapterFreeze.nexoraObjectDirectorSceneBindingAdapterFreezeCapabilityCount, 26); assert.equal(new Set(capabilities).size, capabilities.length); assert.equal(adapterFreeze.nexoraObjectDirectorSceneBindingAdapterFreezePublicApiCount, 12); assert.equal(new Set(adapterFreeze.nexoraObjectDirectorSceneBindingAdapterFreezePublicApiSurface).size, 12); assert.equal(deeplyFrozen(adapterFreeze.nexoraObjectDirectorSceneBindingAdapterFreezeCapabilities), true); assert.equal(deeplyFrozen(adapterFreeze.nexoraObjectDirectorSceneBindingAdapterFreezePublicApiSurface), true); });

  it("structurally verifies the complete NOL-6:7 upstream surface", () => { assert.equal(adapterCertification.nexoraObjectDirectorSceneBindingAdapterCertificationId, "NOL-6:7/NexoraObjectDirectorSceneBindingAdapterCertification"); assert.equal(adapterCertification.nexoraObjectDirectorSceneBindingAdapterCertificationVersion, "6.7.0"); assert.equal(adapterCertification.nexoraObjectDirectorSceneBindingAdapterCertificationNamespace, "nexora.nol.scene.binding.adapter.certification"); assert.equal(adapterCertification.sceneBindingAdapterCertificationStatus.readiness, "ready-for-adapter-freeze"); assert.equal(adapterCertification.sceneBindingAdapterCertificationLevels.length, 5); for (const code of ["ADAPTER_CERTIFIED", "FREEZE_ELIGIBLE", "FREEZE_INELIGIBLE"]) assert.equal(adapterCertification.sceneBindingAdapterCertificationCodes.includes(code as never), true); assert.equal(adapterCertification.verifyNexoraObjectDirectorSceneBindingAdapterCertificationRegistry().valid, true); assert.equal(adapterCertification.isNexoraObjectDirectorSceneBindingAdapterCertificationRegistryFrozen(), true); assert.equal(adapterCertification.verifyNexoraObjectDirectorSceneBindingAdapterCertification().valid, true); assert.equal(adapterCertification.nexoraObjectDirectorSceneBindingAdapterCertificationPublicApiSurface.includes("isNexoraObjectDirectorSceneBindingAdapterFreezeEligible"), true); });

  it("does not mutate upstream data or freeze caller-owned values", () => { const before = JSON.stringify({ levels: adapterCertification.sceneBindingAdapterCertificationLevels, codes: adapterCertification.sceneBindingAdapterCertificationCodes, registry: adapterCertification.nexoraObjectDirectorSceneBindingAdapterCertificationRegistry }), registryIdentity = adapterCertification.nexoraObjectDirectorSceneBindingAdapterCertificationRegistry, caller = { marker: { value: 1 } }, guard = adapterFreeze.isNexoraObjectDirectorSceneBindingAdapterFrozen as unknown as (value: unknown) => boolean; assert.equal(guard(caller), true); assert.equal(JSON.stringify({ levels: adapterCertification.sceneBindingAdapterCertificationLevels, codes: adapterCertification.sceneBindingAdapterCertificationCodes, registry: adapterCertification.nexoraObjectDirectorSceneBindingAdapterCertificationRegistry }), before); assert.equal(adapterCertification.nexoraObjectDirectorSceneBindingAdapterCertificationRegistry, registryIdentity); assert.equal(Object.isFrozen(caller), false); assert.equal(Object.isFrozen(caller.marker), false); });

  it("keeps every owned object and generated result deeply frozen plain data", () => { const values = [adapterFreeze.sceneBindingAdapterFreezeStatus, adapterFreeze.nexoraObjectDirectorSceneBindingAdapterFreezeLock, adapterFreeze.sceneBindingAdapterFrozenUpstream, adapterFreeze.sceneBindingAdapterFreezeInvariantCategories, adapterFreeze.sceneBindingAdapterFreezeInvariants, adapterFreeze.sceneBindingFrozenAdapterContractSurface, adapterFreeze.sceneBindingFrozenAdapterCertificationSurface, adapterFreeze.sceneBindingAdapterFreezeCompatibilityPolicy, adapterFreeze.sceneBindingAdapterFreezeConsumerPolicy, adapterFreeze.sceneBindingAdapterFreezePublicIndexHandoff, adapterFreeze.nexoraObjectDirectorSceneBindingAdapterFreezeRegistry, adapterFreeze.nexoraObjectDirectorSceneBindingAdapterFreezeCapabilities, adapterFreeze.verifyNexoraObjectDirectorSceneBindingAdapterFreezeRegistry(), adapterFreeze.verifyNexoraObjectDirectorSceneBindingAdapterFreeze(), adapterFreeze.getNexoraObjectDirectorSceneBindingAdapterFreezeSummary()]; for (const value of values) { assert.equal(deeplyFrozen(value), true); assert.equal(plainData(value), true); } });

  it("preserves the complete NOL-6:1 through NOL-6:7 lineage", () => { assert.equal(foundation.foundationId, "NOL-6:1/NexoraObjectDirectorSceneBindingFoundation"); assert.equal(contracts.sceneBindingContractId, "NOL-6:2/NexoraObjectDirectorSceneBindingContracts"); assert.equal(validation.nexoraObjectDirectorSceneBindingValidationId, "NOL-6:3/NexoraObjectDirectorSceneBindingValidation"); assert.equal(certification.nexoraObjectDirectorSceneBindingCertificationId, "NOL-6:4/NexoraObjectDirectorSceneBindingCertification"); assert.equal(baseFreeze.nexoraObjectDirectorSceneBindingFreezeId, "NOL-6:5/NexoraObjectDirectorSceneBindingFreeze"); assert.equal(platform.nexoraObjectDirectorSceneBindingPlatformId, "NOL-6:6/NexoraObjectDirectorSceneBindingPlatform"); assert.equal(adapterCertification.nexoraObjectDirectorSceneBindingAdapterCertificationId, "NOL-6:7/NexoraObjectDirectorSceneBindingAdapterCertification"); assert.equal(foundation.verifyNexoraDirectorSceneBindingFoundation().valid, true); assert.equal(contracts.verifySceneBindingContracts().valid, true); assert.equal(validation.verifyNexoraObjectDirectorSceneBindingValidationRegistry().valid, true); assert.equal(certification.verifyNexoraObjectDirectorSceneBindingCertificationRegistry().valid, true); assert.equal(baseFreeze.verifyNexoraObjectDirectorSceneBindingFreeze().valid, true); assert.equal(platform.verifyNexoraObjectDirectorSceneBindingPlatform().valid, true); assert.equal(adapterCertification.verifyNexoraObjectDirectorSceneBindingAdapterCertification().valid, true); });

  it("contains no adapter certification, execution, rendering, runtime, framework, or effects", () => { assert.doesNotMatch(source, /\basync\s+(?:function|\()/); assert.doesNotMatch(source, /\b(?:await|Promise|setTimeout|setInterval|requestAnimationFrame|fetch|window|document|localStorage|sessionStorage|Math\.random|Date\b|Worker|process|console\.)\b/); assert.doesNotMatch(source, /\b(?:useState|useEffect|createElement|addEventListener|dispatchEvent|subscribe|observe)\s*\(/); assert.doesNotMatch(source, /class\s+[A-Za-z_$]|extends\s+[A-Za-z_$]/); assert.doesNotMatch(source, /new\s+(?:Mesh|Scene|Renderer|Object3D|Map|Set|Date|Promise)\s*\(/); assert.doesNotMatch(source, /\bcertifyNexoraObjectDirectorSceneBindingAdapter\s*\(/); assert.doesNotMatch(source, /\b(?:execute|render|synchronize|mount|invoke)Adapter\s*\(/); });
});
