import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { describe, it } from "node:test";
import * as foundation from "./nexoraObjectDirectorSceneBindingFoundation.ts";
import * as contracts from "./nexoraObjectDirectorSceneBindingContracts.ts";
import * as validation from "./nexoraObjectDirectorSceneBindingValidation.ts";
import * as certification from "./nexoraObjectDirectorSceneBindingCertification.ts";
import type { SceneBindingCertificationEvidence, SceneBindingCertificationLevelResult } from "./nexoraObjectDirectorSceneBindingCertification.ts";

function freeze<T>(value: T, seen: object[] = []): T { if (value === null || typeof value !== "object" || seen.includes(value as object)) return value; seen.push(value as object); for (const child of Object.values(value as Record<string, unknown>)) freeze(child, seen); return Object.freeze(value); }
function deeplyFrozen(value: unknown, seen: object[] = []): boolean { if (value === null || typeof value !== "object" || seen.includes(value as object)) return true; if (!Object.isFrozen(value)) return false; seen.push(value as object); return Object.values(value as Record<string, unknown>).every((child) => deeplyFrozen(child, seen)); }
function node(id = "root") { return { nodeId: id, kind: "object", parentId: null, children: [], visibility: "visible", interaction: "selectable", binding: { rendererObjectId: `renderer:${id}`, rendererState: "minimum", rendererCapabilities: ["selectable"], rendererBindingType: "object" }, order: 0 }; }
function validationResult(id = "root") { return validation.validateNexoraObjectDirectorSceneBinding({ bindingId: `binding:${id}`, nodes: [node(id)] }); }
function differentValidationResult() { return validation.validateNexoraObjectDirectorSceneBinding({ bindingId: "binding:different", nodes: [{ ...node("root"), children: ["child"] }, { ...node("child"), parentId: "root" }] }); }
function evidence(overrides: Partial<SceneBindingCertificationEvidence> = {}): SceneBindingCertificationEvidence { const result = validationResult(); return { validationResult: result, repeatedValidationResult: validationResult(), inputWasMutated: false, inputWasFrozenByValidation: false, dependencyBoundaryConfirmed: true, registryCompatibilityConfirmed: true, plainDataBoundaryConfirmed: true, forbiddenDependenciesAbsent: true, notes: ["deterministic validation probe"], ...overrides }; }
function certify(overrides: Partial<SceneBindingCertificationEvidence> = {}, options?: Parameters<typeof certification.certifyNexoraObjectDirectorSceneBinding>[1]) { return certification.certifyNexoraObjectDirectorSceneBinding({ candidateId: "scene-binding:candidate", evidence: evidence(overrides) }, options); }
const source = readFileSync(new URL("./nexoraObjectDirectorSceneBindingCertification.ts", import.meta.url), "utf8");

describe("NOL-6:4 Director Scene Binding Certification", () => {
  it("publishes exact identity, readiness, and sole Validation dependency", () => { assert.equal(certification.nexoraObjectDirectorSceneBindingCertificationId, "NOL-6:4/NexoraObjectDirectorSceneBindingCertification"); assert.equal(certification.nexoraObjectDirectorSceneBindingCertificationVersion, "6.4.0"); assert.equal(certification.nexoraObjectDirectorSceneBindingCertificationNamespace, "nexora.nol.scene.binding.certification"); assert.equal(certification.nexoraObjectDirectorSceneBindingCertificationStatus, "ReadyForFreeze"); assert.equal(certification.nexoraObjectDirectorSceneBindingCertificationDependency, validation.nexoraObjectDirectorSceneBindingValidationId); const imports = [...source.matchAll(/from\s+["']([^"']+)["']/g)].map((match) => match[1]); assert.deepEqual(imports, ["./nexoraObjectDirectorSceneBindingValidation.ts"]); });

  it("publishes frozen levels, outcomes, severities, codes, and default policy", () => { assert.deepEqual(certification.sceneBindingCertificationLevels, ["structural", "behavioral", "architectural", "release"]); assert.deepEqual(certification.sceneBindingCertificationOutcomes, ["certified", "partially-certified", "rejected"]); assert.deepEqual(certification.sceneBindingCertificationSeverities, ["info", "warning", "error", "fatal"]); assert.equal(certification.sceneBindingCertificationLevelCount, 4); assert.equal(certification.sceneBindingCertificationOutcomeCount, 3); assert.equal(certification.sceneBindingCertificationSeverityCount, 4); assert.equal(certification.sceneBindingCertificationCodeCount, 32); assert.equal(new Set(certification.sceneBindingCertificationCodes).size, 32); assert.deepEqual(certification.defaultSceneBindingCertificationOptions, { requiredLevels: ["structural", "behavioral", "architectural", "release"], failOnWarning: false, requireRepeatedValidationEvidence: true, requireDependencyEvidence: true, requireRegistryEvidence: true, requirePlainDataEvidence: true }); for (const value of [certification.sceneBindingCertificationLevels, certification.sceneBindingCertificationOutcomes, certification.sceneBindingCertificationSeverities, certification.sceneBindingCertificationCodes, certification.defaultSceneBindingCertificationOptions]) assert.equal(deeplyFrozen(value), true); });

  it("defines all 31 ordered blocking requirements at their canonical levels", () => { assert.equal(certification.sceneBindingCertificationRequirementCount, 31); assert.deepEqual(certification.sceneBindingCertificationRequirements.reduce<Record<string, number>>((counts, entry) => ({ ...counts, [entry.level]: (counts[entry.level] ?? 0) + 1 }), {}), { structural: 8, behavioral: 8, architectural: 9, release: 6 }); assert.equal(new Set(certification.sceneBindingCertificationRequirements.map((entry) => entry.id)).size, 31); assert.equal(certification.sceneBindingCertificationRequirements.every((entry) => entry.required && entry.blocking && entry.title.length > 0 && entry.description.length > 0), true); assert.equal(deeplyFrozen(certification.sceneBindingCertificationRequirements), true); });

  it("certifies complete clean evidence and resolves freeze eligibility", () => { const result = certify(); assert.equal(result.outcome, "certified"); assert.equal(result.certified, true); assert.equal(result.freezeEligible, true); assert.equal(result.passedRequirementCount, 31); assert.equal(result.failedRequirementCount, 0); assert.equal(result.levelResults.every((entry) => entry.passed), true); assert.equal(result.findings.some((entry) => entry.code === "SCENE_BINDING_CERTIFIED"), true); assert.equal(result.findings.some((entry) => entry.code === "SCENE_BINDING_FREEZE_INELIGIBLE"), false); assert.equal(deeplyFrozen(result), true); });

  it("evaluates every requirement deterministically and handles unsupported IDs", () => { const complete = evidence(); for (const requirement of certification.sceneBindingCertificationRequirements) { const first = certification.evaluateNexoraObjectDirectorSceneBindingRequirement(requirement.id, complete); const second = certification.evaluateNexoraObjectDirectorSceneBindingRequirement(requirement.id, complete); assert.deepEqual(first, second); assert.equal(first.passed, true, requirement.id); assert.equal(deeplyFrozen(first), true); } const unsupported = certification.evaluateNexoraObjectDirectorSceneBindingRequirement("unknown", complete); assert.deepEqual(unsupported, { requirementId: "unsupported-requirement", level: "structural", passed: false, blocking: true, findingCodes: ["SCENE_BINDING_CERTIFICATION_REQUIREMENT_FAILED"] }); assert.equal(deeplyFrozen(unsupported), true); });

  it("returns partial certification for deterministic mismatch without mutation", () => { const supplied = evidence({ repeatedValidationResult: differentValidationResult() }), before = structuredClone(supplied), result = certification.certifyNexoraObjectDirectorSceneBinding({ candidateId: "partial", evidence: supplied }); assert.equal(result.outcome, "partially-certified"); assert.equal(result.certified, false); assert.equal(result.freezeEligible, false); assert.equal(result.levelResults.find((entry) => entry.level === "behavioral")?.passed, false); assert.equal(result.findings.some((entry) => entry.code === "SCENE_BINDING_DETERMINISM_FAILED"), true); assert.deepEqual(supplied, before); assert.equal(Object.isFrozen(supplied), false); });

  it("rejects fatal architectural evidence failures", () => { const result = certify({ dependencyBoundaryConfirmed: false, forbiddenDependenciesAbsent: false }); assert.equal(result.outcome, "rejected"); assert.equal(result.certified, false); assert.equal(result.freezeEligible, false); assert.equal(result.fatalCount > 0, true); assert.equal(result.findings.some((entry) => entry.code === "SCENE_BINDING_DEPENDENCY_BOUNDARY_FAILED"), true); });

  it("rejects fatal validation evidence and fails corrupt structural counts", () => { const fatal = freeze({ valid: false, findings: [{ code: "SCENE_BINDING_INPUT_NOT_PLAIN_OBJECT" as const, severity: "fatal" as const, message: "fatal", path: [] }], errorCount: 0, warningCount: 0, fatalCount: 1, infoCount: 0, checkedNodeCount: 0, checkedBindingCount: 0 }), fatalResult = certify({ validationResult: fatal, repeatedValidationResult: fatal }); assert.equal(fatalResult.outcome, "rejected"); assert.equal(fatalResult.findings.some((entry) => entry.code === "SCENE_BINDING_VALIDATION_FAILED" && entry.validationCode === "SCENE_BINDING_INPUT_NOT_PLAIN_OBJECT"), true); const clean = validationResult(), corrupt = freeze({ ...clean, errorCount: clean.errorCount + 1 }), corruptResult = certify({ validationResult: corrupt, repeatedValidationResult: corrupt }); assert.equal(corruptResult.levelResults.find((entry) => entry.level === "structural")?.passed, false); assert.equal(corruptResult.requirementResults.find((entry) => entry.requirementId === "finding-count-integrity")?.passed, false); });

  it("honors warning policy without changing validation warning semantics", () => { const warning = freeze({ valid: true, findings: [{ code: "SCENE_BINDING_UNKNOWN_FIELD" as const, severity: "warning" as const, message: "Unknown field", path: [] }], errorCount: 0, warningCount: 1, fatalCount: 0, infoCount: 0, checkedNodeCount: 1, checkedBindingCount: 1 }), permissive = certify({ validationResult: warning, repeatedValidationResult: warning }), strict = certify({ validationResult: warning, repeatedValidationResult: warning }, { failOnWarning: true }); assert.equal(permissive.outcome, "certified"); assert.equal(permissive.warningCount, 1); assert.equal(permissive.findings.some((entry) => entry.code === "SCENE_BINDING_VALIDATION_WARNING_PRESENT" && entry.severity === "warning"), true); assert.equal(strict.outcome, "partially-certified"); assert.equal(strict.freezeEligible, false); assert.equal(strict.warningCount, 1); });

  it("allows explicitly optional repeated validation evidence", () => { const withoutRepeat = evidence(); const mutable = { ...withoutRepeat }; delete mutable.repeatedValidationResult; const result = certification.certifyNexoraObjectDirectorSceneBinding({ candidateId: "single-pass", evidence: mutable }, { requireRepeatedValidationEvidence: false }); assert.equal(result.outcome, "certified"); assert.equal(result.freezeEligible, true); assert.equal(result.requirementResults.find((entry) => entry.requirementId === "deterministic-results")?.passed, true); });

  it("reports incomplete evidence when required attestations are omitted", () => { const incomplete = { validationResult: validationResult() }, result = certification.certifyNexoraObjectDirectorSceneBinding({ candidateId: "incomplete", evidence: incomplete }); assert.equal(result.outcome, "rejected"); assert.equal(result.findings.some((entry) => entry.code === "SCENE_BINDING_EVIDENCE_INCOMPLETE" && entry.requirementId === "deterministic-results"), true); assert.equal(result.findings.some((entry) => entry.code === "SCENE_BINDING_EVIDENCE_INCOMPLETE" && entry.level === "architectural"), true); assert.equal(Object.isFrozen(incomplete), false); });

  it("rejects missing, invalid, executable, and custom-instance inputs without throwing", () => { class Candidate { candidateId = "custom"; evidence = evidence(); } for (const input of [null, undefined, [], 42, "candidate", {}, { candidateId: "" }, { candidateId: "candidate" }, { candidateId: "candidate", evidence: { validationResult: { valid: true } } }, { candidateId: "candidate", evidence: { ...evidence(), notes: [() => true] } }, new Candidate()]) { let result: certification.SceneBindingCertificationResult | undefined; assert.doesNotThrow(() => { result = certification.certifyNexoraObjectDirectorSceneBinding(input); }); assert.equal(result?.outcome, "rejected"); assert.equal(result?.freezeEligible, false); assert.equal(deeplyFrozen(result), true); } });

  it("canonicalizes and de-duplicates findings with internally consistent counts", () => { const first = certify({ repeatedValidationResult: differentValidationResult(), inputWasMutated: true }), second = certify({ repeatedValidationResult: differentValidationResult(), inputWasMutated: true }); assert.deepEqual(first, second); assert.equal(new Set(first.findings.map((entry) => JSON.stringify(entry))).size, first.findings.length); const priority = { fatal: 0, error: 1, warning: 2, info: 3 } as const; assert.equal(first.findings.every((entry, index) => index === 0 || priority[first.findings[index - 1].severity] <= priority[entry.severity]), true); assert.equal(first.warningCount, first.findings.filter((entry) => entry.severity === "warning").length); assert.equal(first.errorCount, first.findings.filter((entry) => entry.severity === "error").length); assert.equal(first.fatalCount, first.findings.filter((entry) => entry.severity === "fatal").length); });

  it("resolves certified, partial, rejected, and warning-blocked outcomes purely", () => { const levels = (passed: number): readonly SceneBindingCertificationLevelResult[] => freeze(certification.sceneBindingCertificationLevels.map((level, index) => ({ level, passed: index < passed, requiredRequirementCount: 1, passedRequirementCount: index < passed ? 1 : 0, failedRequirementCount: index < passed ? 0 : 1, blockingFailureCount: index < passed ? 0 : 1 }))); assert.equal(certification.resolveNexoraObjectDirectorSceneBindingCertificationOutcome(levels(4), []), "certified"); assert.equal(certification.resolveNexoraObjectDirectorSceneBindingCertificationOutcome(levels(2), []), "partially-certified"); assert.equal(certification.resolveNexoraObjectDirectorSceneBindingCertificationOutcome(levels(0), []), "rejected"); const warning = freeze([{ code: "SCENE_BINDING_VALIDATION_WARNING_PRESENT" as const, severity: "warning" as const, message: "warning" }]); assert.equal(certification.resolveNexoraObjectDirectorSceneBindingCertificationOutcome(levels(4), warning, { failOnWarning: true }), "partially-certified"); });

  it("guards result shapes without mutation and returns an immutable dynamic summary", () => { const result = certify(), mutable = structuredClone(result), before = structuredClone(mutable), summary = certification.getNexoraObjectDirectorSceneBindingCertificationSummary(result); assert.equal(certification.isNexoraObjectDirectorSceneBindingCertificationResult(result), true); assert.equal(certification.isNexoraObjectDirectorSceneBindingCertificationResult(mutable), true); assert.deepEqual(mutable, before); assert.equal(Object.isFrozen(mutable), false); assert.equal(certification.isNexoraObjectDirectorSceneBindingCertificationResult({ ...mutable, passedRequirementCount: 999 }), false); assert.equal(certification.isNexoraObjectDirectorSceneBindingCertificationResult({ outcome: "certified" }), false); assert.deepEqual(summary, { candidateId: result.candidateId, status: "certified", certified: true, freezeEligible: true, passedLevelCount: 4, failedLevelCount: 0, passedRequirementCount: 31, failedRequirementCount: 0, warningCount: result.warningCount, errorCount: result.errorCount, fatalCount: result.fatalCount }); assert.equal(deeplyFrozen(summary), true); });

  it("rejects unsupported option shapes and de-duplicates requested levels", () => { const invalidValues: unknown[] = [{ requiredLevels: ["structural", "unknown"] }, { failOnWarning: "yes" }, { unexpected: true }, new (class Options { failOnWarning = false; })()]; for (const options of invalidValues) assert.equal(certification.certifyNexoraObjectDirectorSceneBinding({ candidateId: "options", evidence: evidence() }, options as never).outcome, "rejected"); const duplicate = certification.certifyNexoraObjectDirectorSceneBinding({ candidateId: "options", evidence: evidence() }, { requiredLevels: ["structural", "structural", "behavioral", "architectural", "release"] }); assert.equal(duplicate.outcome, "certified"); });

  it("publishes and verifies the frozen ordered registry, capabilities, and API surface", () => { const registry = certification.getNexoraObjectDirectorSceneBindingCertificationRegistry(); assert.equal(registry, certification.nexoraObjectDirectorSceneBindingCertificationRegistry); assert.equal(registry.length, 20); assert.equal(certification.getNexoraObjectDirectorSceneBindingCertificationRegistryCount(), registry.length); assert.equal(certification.nexoraObjectDirectorSceneBindingCertificationRegistryCount, registry.length); assert.deepEqual(registry.map((entry) => entry.order), Array.from({ length: 20 }, (_, index) => index + 1)); assert.equal(new Set(registry.map((entry) => entry.name)).size, 20); assert.equal(certification.nexoraObjectDirectorSceneBindingCertificationCapabilityCount, 21); assert.equal(certification.nexoraObjectDirectorSceneBindingCertificationPublicApiCount, 9); assert.equal(certification.isNexoraObjectDirectorSceneBindingCertificationRegistryFrozen(), true); assert.equal(certification.verifyNexoraObjectDirectorSceneBindingCertificationRegistry().valid, true); for (const value of [registry, certification.nexoraObjectDirectorSceneBindingCertificationCapabilities, certification.nexoraObjectDirectorSceneBindingCertificationPublicApiSurface]) assert.equal(deeplyFrozen(value), true); });

  it("preserves NOL-6:1 through NOL-6:3 public identities and registries", () => { assert.equal(foundation.foundationId, "NOL-6:1/NexoraObjectDirectorSceneBindingFoundation"); assert.equal(contracts.sceneBindingContractId, "NOL-6:2/NexoraObjectDirectorSceneBindingContracts"); assert.equal(validation.nexoraObjectDirectorSceneBindingValidationId, "NOL-6:3/NexoraObjectDirectorSceneBindingValidation"); assert.equal(foundation.verifyNexoraDirectorSceneBindingFoundation().valid, true); assert.equal(contracts.verifySceneBindingContracts().valid, true); assert.equal(validation.verifyNexoraObjectDirectorSceneBindingValidationRegistry().valid, true); });

  it("contains no forbidden dependencies, rendering, runtime, effects, mutation, or nondeterminism", () => { assert.doesNotMatch(source, /from\s+["'][^"']*(?:Foundation|Contracts|renderer|runtime|react|next|three|ui|canvas|svg|webgl)/i); assert.doesNotMatch(source, /\b(?:async|await|Promise|setTimeout|setInterval|requestAnimationFrame|fetch|window|document|localStorage|sessionStorage|Math\.random|Date\b|Worker|process|console\.)\b/); assert.doesNotMatch(source, /\b(?:useState|useEffect|createElement|addEventListener|dispatchEvent|subscribe|observe)\s*\(/); assert.doesNotMatch(source, /class\s+[A-Za-z_$]|extends\s+[A-Za-z_$]/); assert.doesNotMatch(source, /new\s+(?:Mesh|Scene|Renderer|Object3D|Map|Set|Date|Promise)\s*\(/); });
});
