import assert from "node:assert/strict";
import { readdirSync, readFileSync } from "node:fs";
import { describe, it } from "node:test";
import * as foundation from "./nexoraObjectDirectorSceneBindingFoundation.ts";
import * as contracts from "./nexoraObjectDirectorSceneBindingContracts.ts";
import * as validation from "./nexoraObjectDirectorSceneBindingValidation.ts";
import * as certification from "./nexoraObjectDirectorSceneBindingCertification.ts";
import * as freeze from "./nexoraObjectDirectorSceneBindingFreeze.ts";
import * as platform from "./nexoraObjectDirectorSceneBindingPlatform.ts";

function deeplyFrozen(value: unknown, seen: object[] = []): boolean { if (value === null || typeof value !== "object" || seen.includes(value as object)) return true; if (!Object.isFrozen(value)) return false; seen.push(value as object); return Object.values(value as Record<string, unknown>).every((child) => deeplyFrozen(child, seen)); }
function plainData(value: unknown, seen: object[] = []): boolean { if (value === null || ["string", "number", "boolean", "undefined"].includes(typeof value)) return true; if (typeof value !== "object" || seen.includes(value as object)) return false; const prototype = Object.getPrototypeOf(value); if (!Array.isArray(value) && prototype !== Object.prototype && prototype !== null) return false; seen.push(value as object); return Object.values(value as Record<string, unknown>).every((child) => plainData(child, seen)); }
const source = readFileSync(new URL("./nexoraObjectDirectorSceneBindingPlatform.ts", import.meta.url), "utf8");

describe("NOL-6:6 Director Scene Binding Platform", () => {
  it("creates exactly the two requested NOL-6:6 files", () => { const files = readdirSync(new URL(".", import.meta.url)).filter((name) => name.startsWith("nexoraObjectDirectorSceneBindingPlatform")); assert.deepEqual(files.sort(), ["nexoraObjectDirectorSceneBindingPlatform.test.ts", "nexoraObjectDirectorSceneBindingPlatform.ts"]); });

  it("publishes the exact Platform identity", () => { assert.equal(platform.nexoraObjectDirectorSceneBindingPlatformId, "NOL-6:6/NexoraObjectDirectorSceneBindingPlatform"); assert.equal(platform.nexoraObjectDirectorSceneBindingPlatformVersion, "6.6.0"); assert.equal(platform.nexoraObjectDirectorSceneBindingPlatformNamespace, "nexora.nol.scene.binding.platform"); });

  it("imports only NOL-6:5 Freeze", () => { const imports = [...source.matchAll(/from\s+["']([^"']+)["']/g)].map((match) => match[1]); assert.deepEqual(imports, ["./nexoraObjectDirectorSceneBindingFreeze.ts"]); assert.doesNotMatch(source, /from\s+["'][^"']*(?:Foundation|Contracts|Validation|Certification|runtime|renderer|react|next|three|ui|adapter|public.?index)/i); });

  it("publishes every active immutable Platform status", () => { assert.deepEqual(platform.sceneBindingPlatformStatus, { released: true, certified: true, frozen: true, stable: true, readiness: "ready-for-adapter" }); assert.equal(deeplyFrozen(platform.sceneBindingPlatformStatus), true); });

  it("publishes exact metadata derived from the frozen upstream", () => { assert.deepEqual(platform.sceneBindingPlatformMetadata, { identity: platform.nexoraObjectDirectorSceneBindingPlatformId, version: platform.nexoraObjectDirectorSceneBindingPlatformVersion, namespace: platform.nexoraObjectDirectorSceneBindingPlatformNamespace, releaseState: "released", readiness: "ready-for-adapter", upstreamIdentity: freeze.nexoraObjectDirectorSceneBindingFreezeId, semanticVersion: "6.6.0", compatibilityVersion: freeze.nexoraObjectDirectorSceneBindingFreezeVersion }); assert.equal(deeplyFrozen(platform.sceneBindingPlatformMetadata), true); });

  it("publishes nine ordered unique frozen capabilities with a dynamic count", () => { const expected = ["scene-binding", "platform-surface", "freeze-integration", "registry-access", "api-surface-access", "compatibility-check", "consumer-policy", "adapter-readiness", "immutable-platform"]; assert.deepEqual(platform.sceneBindingPlatformCapabilities, expected); assert.equal(platform.sceneBindingPlatformCapabilityCount, expected.length); assert.equal(new Set(platform.sceneBindingPlatformCapabilities).size, expected.length); assert.equal(deeplyFrozen(platform.sceneBindingPlatformCapabilities), true); });

  it("represents every NOL-6:5 export identity as ordered plain metadata", () => { const surface = platform.getNexoraObjectDirectorSceneBindingPlatformApiSurface(), names = surface.map((entry) => entry.exportName), required = ["nexoraObjectDirectorSceneBindingFreezeId", "sceneBindingFreezeStatus", "nexoraObjectDirectorSceneBindingFreezeLock", "sceneBindingFrozenUpstream", "sceneBindingFreezeInvariantCategories", "sceneBindingFreezeInvariants", "sceneBindingFrozenPublicApiSurface", "sceneBindingFreezeCompatibilityPolicy", "sceneBindingFreezeConsumerPolicy", "nexoraObjectDirectorSceneBindingFreezeCapabilities", "nexoraObjectDirectorSceneBindingFreezeRegistry", "verifyNexoraObjectDirectorSceneBindingFreezeRegistry", "verifyNexoraObjectDirectorSceneBindingFreeze", "isNexoraObjectDirectorSceneBindingFrozen", "isNexoraObjectDirectorSceneBindingReadyForPlatform", "getNexoraObjectDirectorSceneBindingFreezeSummary"]; assert.equal(required.every((name) => names.includes(name)), true); assert.equal(surface.length, 43); assert.equal(platform.sceneBindingPlatformApiCount, surface.length); assert.equal(platform.getNexoraObjectDirectorSceneBindingPlatformApiCount(), surface.length); assert.equal(surface, platform.sceneBindingPlatformApiSurface); assert.equal(new Set(names).size, names.length); assert.equal(surface.every((entry) => entry.source === "NOL-6:5" && entry.visible && entry.category.length > 0), true); assert.equal(surface.some((entry) => /(?:freezeOwned|deeplyFrozen|verificationStates)/.test(entry.exportName)), false); assert.equal(plainData(surface), true); assert.equal(deeplyFrozen(surface), true); });

  it("publishes the exact consumer policy", () => { assert.deepEqual(platform.sceneBindingPlatformConsumerPolicy, { immediateConsumer: "NOL-6:7", finalConsumer: "NOL-6:9 Public Index", directFeatureImportAllowed: false }); assert.equal(deeplyFrozen(platform.sceneBindingPlatformConsumerPolicy), true); });

  it("publishes adapter readiness without an adapter implementation", () => { assert.deepEqual(platform.sceneBindingPlatformAdapterPolicy, { adapterReady: true, freezeRequired: true, certificationRequired: true, validationRequired: false, runtimeRequired: false }); assert.equal(deeplyFrozen(platform.sceneBindingPlatformAdapterPolicy), true); assert.doesNotMatch(source, /\b(?:create|execute|run|render|synchronize)NexoraObjectDirectorSceneBindingAdapter\s*\(/); });

  it("publishes the exact compatibility policy", () => { assert.deepEqual(platform.sceneBindingPlatformCompatibilityPolicy, { breakingChangesAllowed: false, apiMutationAllowed: false, overrideAllowed: false, newPhaseRequired: true, backwardCompatible: true }); assert.equal(deeplyFrozen(platform.sceneBindingPlatformCompatibilityPolicy), true); });

  it("aggregates one canonical deeply frozen plain Platform object", () => { const value = platform.getNexoraObjectDirectorSceneBindingPlatform(); assert.equal(value, platform.nexoraObjectDirectorSceneBindingPlatform); assert.equal(value.metadata, platform.sceneBindingPlatformMetadata); assert.equal(value.status, platform.sceneBindingPlatformStatus); assert.equal(value.capabilities, platform.sceneBindingPlatformCapabilities); assert.equal(value.apiSurface, platform.sceneBindingPlatformApiSurface); assert.equal(value.registry, platform.nexoraObjectDirectorSceneBindingPlatformRegistry); assert.equal(value.upstream, freeze.nexoraObjectDirectorSceneBindingFreezeId); assert.equal(deeplyFrozen(value), true); assert.equal(plainData(value), true); });

  it("publishes and verifies all eleven ordered Platform registry sections", () => { const registry = platform.getNexoraObjectDirectorSceneBindingPlatformRegistry(); assert.equal(registry, platform.nexoraObjectDirectorSceneBindingPlatformRegistry); assert.deepEqual(registry.map((entry) => entry.name), ["Identity", "Metadata", "Status", "Capabilities", "API Surface", "Consumer Policy", "Adapter Policy", "Compatibility Policy", "Public APIs", "Dependency", "Release Information"]); assert.deepEqual(registry.map((entry) => entry.order), Array.from({ length: 11 }, (_, index) => index + 1)); assert.equal(platform.nexoraObjectDirectorSceneBindingPlatformRegistryCount, 11); assert.equal(platform.getNexoraObjectDirectorSceneBindingPlatformRegistryCount(), registry.length); assert.equal(new Set(registry.map((entry) => entry.name)).size, registry.length); const verification = platform.verifyNexoraObjectDirectorSceneBindingPlatformRegistry(); assert.equal(verification.valid, true); assert.equal(verification.ordered, true); assert.equal(verification.unique, true); assert.equal(verification.countValid, true); assert.equal(verification.publicApisValid, true); assert.equal(verification.frozen, true); assert.equal(platform.isNexoraObjectDirectorSceneBindingPlatformRegistryFrozen(), true); assert.equal(deeplyFrozen(verification), true); });

  it("exports all eleven immutable Public API identities", () => { const required = ["getNexoraObjectDirectorSceneBindingPlatform", "getNexoraObjectDirectorSceneBindingPlatformRegistry", "getNexoraObjectDirectorSceneBindingPlatformRegistryCount", "getNexoraObjectDirectorSceneBindingPlatformApiSurface", "getNexoraObjectDirectorSceneBindingPlatformApiCount", "verifyNexoraObjectDirectorSceneBindingPlatform", "isNexoraObjectDirectorSceneBindingPlatformFrozen", "isNexoraObjectDirectorSceneBindingReadyForAdapter", "getNexoraObjectDirectorSceneBindingPlatformSummary", "verifyNexoraObjectDirectorSceneBindingPlatformRegistry", "isNexoraObjectDirectorSceneBindingPlatformRegistryFrozen"]; assert.deepEqual(platform.nexoraObjectDirectorSceneBindingPlatformPublicApiSurface, required); assert.equal(platform.nexoraObjectDirectorSceneBindingPlatformPublicApiCount, required.length); assert.equal(required.every((name) => typeof platform[name as keyof typeof platform] === "function"), true); assert.equal(deeplyFrozen(platform.nexoraObjectDirectorSceneBindingPlatformPublicApiSurface), true); });

  it("passes every deterministic Platform verification check", () => { const first = platform.verifyNexoraObjectDirectorSceneBindingPlatform(), second = platform.verifyNexoraObjectDirectorSceneBindingPlatform(); assert.deepEqual(first, second); assert.equal(first.valid, true); assert.equal(first.readyForAdapter, true); assert.equal(first.checkResults.length, 11); assert.equal(first.checkResults.every((entry) => entry.passed), true); assert.equal(new Set(first.checkResults.map((entry) => entry.checkId)).size, first.checkResults.length); assert.equal(first.passedCheckCount, first.checkResults.filter((entry) => entry.passed).length); assert.equal(first.failedCheckCount, first.checkResults.filter((entry) => !entry.passed).length); assert.equal(deeplyFrozen(first), true); });

  it("reports the canonical frozen and adapter-ready state", () => { assert.equal(platform.isNexoraObjectDirectorSceneBindingPlatformFrozen.length, 0); assert.equal(platform.isNexoraObjectDirectorSceneBindingReadyForAdapter.length, 0); assert.equal(platform.isNexoraObjectDirectorSceneBindingPlatformFrozen(), true); assert.equal(platform.isNexoraObjectDirectorSceneBindingReadyForAdapter(), true); assert.equal(platform.isNexoraObjectDirectorSceneBindingReadyForAdapter(), true); });

  it("returns the exact dynamic immutable Platform summary", () => { const summary = platform.getNexoraObjectDirectorSceneBindingPlatformSummary(); assert.deepEqual(summary, { identity: platform.nexoraObjectDirectorSceneBindingPlatformId, version: platform.nexoraObjectDirectorSceneBindingPlatformVersion, namespace: platform.nexoraObjectDirectorSceneBindingPlatformNamespace, readiness: "ready-for-adapter", capabilityCount: platform.sceneBindingPlatformCapabilities.length, apiCount: platform.sceneBindingPlatformApiSurface.length, registryCount: platform.nexoraObjectDirectorSceneBindingPlatformRegistry.length, upstream: freeze.nexoraObjectDirectorSceneBindingFreezeId, nextPhase: "NOL-6:7" }); assert.equal(deeplyFrozen(summary), true); assert.deepEqual(summary, platform.getNexoraObjectDirectorSceneBindingPlatformSummary()); });

  it("does not mutate or freeze imported upstream or caller-owned data", () => { const before = JSON.stringify({ status: freeze.sceneBindingFreezeStatus, registry: freeze.nexoraObjectDirectorSceneBindingFreezeRegistry }), registryIdentity = freeze.nexoraObjectDirectorSceneBindingFreezeRegistry, caller = { marker: { value: 1 } }, guard = platform.isNexoraObjectDirectorSceneBindingPlatformFrozen as unknown as (value: unknown) => boolean; assert.equal(guard(caller), true); assert.equal(JSON.stringify({ status: freeze.sceneBindingFreezeStatus, registry: freeze.nexoraObjectDirectorSceneBindingFreezeRegistry }), before); assert.equal(freeze.nexoraObjectDirectorSceneBindingFreezeRegistry, registryIdentity); assert.equal(Object.isFrozen(caller), false); assert.equal(Object.isFrozen(caller.marker), false); });

  it("keeps all owned objects, collections, and generated results deeply immutable", () => { const values = [platform.sceneBindingPlatformStatus, platform.sceneBindingPlatformMetadata, platform.sceneBindingPlatformCapabilities, platform.sceneBindingPlatformApiSurface, platform.sceneBindingPlatformConsumerPolicy, platform.sceneBindingPlatformAdapterPolicy, platform.sceneBindingPlatformCompatibilityPolicy, platform.nexoraObjectDirectorSceneBindingPlatformRegistry, platform.nexoraObjectDirectorSceneBindingPlatformPublicApiSurface, platform.nexoraObjectDirectorSceneBindingPlatform, platform.verifyNexoraObjectDirectorSceneBindingPlatformRegistry(), platform.verifyNexoraObjectDirectorSceneBindingPlatform(), platform.getNexoraObjectDirectorSceneBindingPlatformSummary()]; for (const value of values) { assert.equal(deeplyFrozen(value), true); assert.equal(plainData(value), true); } });

  it("preserves the complete NOL-6:1 through NOL-6:5 lineage", () => { assert.equal(foundation.foundationId, "NOL-6:1/NexoraObjectDirectorSceneBindingFoundation"); assert.equal(contracts.sceneBindingContractId, "NOL-6:2/NexoraObjectDirectorSceneBindingContracts"); assert.equal(validation.nexoraObjectDirectorSceneBindingValidationId, "NOL-6:3/NexoraObjectDirectorSceneBindingValidation"); assert.equal(certification.nexoraObjectDirectorSceneBindingCertificationId, "NOL-6:4/NexoraObjectDirectorSceneBindingCertification"); assert.equal(freeze.nexoraObjectDirectorSceneBindingFreezeId, "NOL-6:5/NexoraObjectDirectorSceneBindingFreeze"); assert.equal(foundation.verifyNexoraDirectorSceneBindingFoundation().valid, true); assert.equal(contracts.verifySceneBindingContracts().valid, true); assert.equal(validation.verifyNexoraObjectDirectorSceneBindingValidationRegistry().valid, true); assert.equal(certification.verifyNexoraObjectDirectorSceneBindingCertificationRegistry().valid, true); assert.equal(freeze.verifyNexoraObjectDirectorSceneBindingFreeze().valid, true); });

  it("contains no runtime, rendering, framework, synchronization, certification, or validation behavior", () => { assert.doesNotMatch(source, /\basync\s+(?:function|\()/); assert.doesNotMatch(source, /\b(?:await|Promise|setTimeout|setInterval|requestAnimationFrame|fetch|window|document|localStorage|sessionStorage|Math\.random|Date\b|Worker|process|console\.)\b/); assert.doesNotMatch(source, /\b(?:useState|useEffect|createElement|addEventListener|dispatchEvent|subscribe|observe)\s*\(/); assert.doesNotMatch(source, /class\s+[A-Za-z_$]|extends\s+[A-Za-z_$]/); assert.doesNotMatch(source, /new\s+(?:Mesh|Scene|Renderer|Object3D|Map|Set|Date|Promise)\s*\(/); assert.doesNotMatch(source, /\b(?:certify|validate|render|synchronize|createBinding)NexoraObjectDirectorSceneBinding\s*\(/); });
});
