import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { describe, it } from "node:test";
import { nexoraDirectorSceneBindingStates, nexoraDirectorSceneNodeKinds, nexoraDirectorSceneNodeVisibilities } from "./nexoraObjectDirectorSceneBindingFoundation.ts";
import * as contracts from "./nexoraObjectDirectorSceneBindingContracts.ts";

function deeplyFrozen(value: unknown, seen = new Set<object>()): boolean { if (value === null || typeof value !== "object" || seen.has(value as object)) return true; if (!Object.isFrozen(value)) return false; seen.add(value as object); return Object.values(value as Record<string, unknown>).every((child) => deeplyFrozen(child, seen)); }
const source = readFileSync(new URL("./nexoraObjectDirectorSceneBindingContracts.ts", import.meta.url), "utf8");
const expectedNames = ["SceneNodeContract", "SceneNodeIdentityContract", "SceneNodeRelationshipContract", "SceneNodeCollectionContract", "RendererBindingContract", "RendererObjectContract", "RendererStateContract", "VisibilityContract", "VisibilityCollectionContract", "InteractionContract", "InteractionModeContract", "InteractionCollectionContract", "SceneOrderContract", "SceneHierarchyContract", "SceneBindingValidationContract", "SceneBindingCertificationContract"];

describe("NOL-6:2 Director Scene Binding Contracts", () => {
  it("publishes the exact immutable contract identity", () => { assert.equal(contracts.sceneBindingContractId, "NOL-6:2/NexoraObjectDirectorSceneBindingContracts"); assert.equal(contracts.sceneBindingContractVersion, "6.2.0"); assert.equal(contracts.sceneBindingContractNamespace, "nexora.nol.scene.binding.contracts"); });

  it("imports only NOL-6:1 Foundation and excludes forbidden dependencies", () => { const imports = [...source.matchAll(/from\s+["']([^"']+)["']/g)].map((match) => match[1]); assert.deepEqual(imports, ["./nexoraObjectDirectorSceneBindingFoundation.ts"]); assert.doesNotMatch(source, /from\s+["'][^"']*(?:renderer|runtime|react|next|three|ui|canvas|svg|webgl)/i); });

  it("exports every Scene Node contract as frozen definition-only data", () => { for (const value of [contracts.SceneNodeContract, contracts.SceneNodeIdentityContract, contracts.SceneNodeRelationshipContract, contracts.SceneNodeCollectionContract]) assert.equal(deeplyFrozen(value), true); assert.deepEqual(contracts.SceneNodeContract.requiredFields, ["nodeId", "kind", "parentId", "children", "visibility", "interaction", "binding", "order"]); assert.equal(contracts.SceneNodeContract.methodsForbidden, true); assert.equal(contracts.SceneNodeIdentityContract.supportedKinds, nexoraDirectorSceneNodeKinds); assert.deepEqual(contracts.SceneNodeRelationshipContract.supportedDefinitions, ["parent", "children", "ancestor", "descendant", "root", "leaf"]); assert.equal(contracts.SceneNodeCollectionContract.ordered, true); });

  it("exports renderer contracts without renderer implementation details", () => { assert.deepEqual(contracts.RendererBindingContract.requiredFields, ["rendererObjectId", "rendererState", "rendererCapabilities", "rendererBindingType"]); assert.deepEqual(contracts.RendererObjectContract.requiredFields, ["rendererObjectId", "rendererState", "rendererCapabilities", "rendererBindingType"]); assert.deepEqual(contracts.RendererStateContract.supportedStates, ["minimum", "report", "operation"]); assert.equal(contracts.RendererBindingContract.implementationForbidden, true); assert.equal(contracts.RendererObjectContract.implementationForbidden, true); assert.equal(deeplyFrozen(contracts.RendererStateContract), true); });

  it("aligns visibility contracts exactly with Foundation", () => { assert.equal(contracts.VisibilityContract.supportedValues, nexoraDirectorSceneNodeVisibilities); assert.deepEqual(contracts.VisibilityContract.supportedValues, ["visible", "hidden", "collapsed"]); assert.equal(contracts.VisibilityContract.foundationAligned, true); assert.equal(contracts.VisibilityCollectionContract.ordered, true); assert.equal(contracts.VisibilityCollectionContract.countDerivedFromItems, true); assert.equal(deeplyFrozen(contracts.VisibilityCollectionContract), true); });

  it("publishes immutable abstract interaction contracts", () => { assert.deepEqual(contracts.InteractionModeContract.supportedModes, ["none", "selectable", "focusable", "interactive"]); assert.deepEqual(contracts.InteractionContract.requiredFields, ["mode", "selectable", "focusable", "interactive"]); assert.equal(contracts.InteractionContract.executableHandlersForbidden, true); assert.equal(contracts.InteractionContract.capabilityDefinitionsOnly, true); assert.equal(contracts.InteractionCollectionContract.ordered, true); assert.equal(contracts.InteractionCollectionContract.countDerivedFromItems, true); assert.equal(deeplyFrozen(contracts.InteractionModeContract), true); });

  it("exports ordering and hierarchy definitions without traversal behavior", () => { assert.equal(contracts.SceneOrderContract.sequential, true); assert.equal(contracts.SceneOrderContract.stable, true); assert.equal(contracts.SceneOrderContract.sourceOrderPreserved, true); assert.equal(contracts.SceneHierarchyContract.relationshipDefinitions, contracts.SceneNodeRelationshipContract.supportedDefinitions); assert.deepEqual(contracts.SceneHierarchyContract.requiredFields, ["parentId", "children"]); assert.equal(deeplyFrozen(contracts.SceneHierarchyContract), true); });

  it("exports complete validation and certification description contracts", () => { assert.deepEqual(contracts.SceneBindingValidationContract.requiredFields, ["requiredFields", "supportedEnums", "orderingRules", "hierarchyRules", "bindingRules"]); assert.equal(contracts.SceneBindingValidationContract.supportedEnums.nodeKinds, nexoraDirectorSceneNodeKinds); assert.equal(contracts.SceneBindingValidationContract.supportedEnums.bindingStates, nexoraDirectorSceneBindingStates); assert.equal(contracts.SceneBindingValidationContract.supportedEnums.visibility, nexoraDirectorSceneNodeVisibilities); assert.deepEqual(contracts.SceneBindingValidationContract.supportedEnums.rendererStates, ["minimum", "report", "operation"]); assert.equal(contracts.SceneBindingValidationContract.executionForbidden, true); assert.equal(contracts.SceneBindingCertificationContract.structuralCertificationOnly, true); assert.equal(contracts.SceneBindingCertificationContract.runtimeCertificationForbidden, true); assert.equal(deeplyFrozen(contracts.SceneBindingValidationContract) && deeplyFrozen(contracts.SceneBindingCertificationContract), true); });

  it("publishes an exact ordered, unique, dynamically counted frozen registry", () => { assert.deepEqual(contracts.sceneBindingContractRegistry.map((contract) => contract.contractName), expectedNames); assert.deepEqual(contracts.sceneBindingContractRegistry.map((contract) => contract.order), Array.from({ length: 16 }, (_, index) => index + 1)); assert.equal(new Set(expectedNames).size, expectedNames.length); assert.equal(contracts.sceneBindingContractCount, contracts.sceneBindingContractRegistry.length); assert.equal(contracts.sceneBindingContractCount, 16); assert.equal(contracts.getSceneBindingContractRegistry(), contracts.sceneBindingContractRegistry); assert.equal(contracts.getSceneBindingContractCount(), contracts.sceneBindingContractRegistry.length); assert.equal(deeplyFrozen(contracts.sceneBindingContractRegistry), true); });

  it("exports all four inspection APIs and verifies structural integrity", () => { assert.equal(typeof contracts.getSceneBindingContractRegistry, "function"); assert.equal(typeof contracts.getSceneBindingContractCount, "function"); assert.equal(typeof contracts.verifySceneBindingContracts, "function"); assert.equal(typeof contracts.isSceneBindingContractsFrozen, "function"); assert.equal(contracts.isSceneBindingContractsFrozen(), true); const report = contracts.verifySceneBindingContracts(); assert.equal(report.valid, true); assert.equal(report.identityValid && report.registryComplete && report.registryOrdered && report.registryUnique && report.contractsFrozen && report.foundationAligned, true); assert.deepEqual(report.violations, []); assert.equal(deeplyFrozen(report), true); });

  it("deep-freezes every exported contract and all nested definitions", () => { for (const name of expectedNames) assert.equal(deeplyFrozen((contracts as Record<string, unknown>)[name]), true, name); assert.equal(Object.isFrozen(contracts.SceneBindingValidationContract.supportedEnums), true); assert.equal(Object.isFrozen(contracts.SceneHierarchyContract.rules), true); assert.throws(() => (contracts.SceneNodeContract.requiredFields as string[]).push("method"), TypeError); });

  it("contains contracts and structural verification only", () => { assert.doesNotMatch(source, /\b(?:async|await|Promise|setTimeout|setInterval|requestAnimationFrame|fetch|window|document|localStorage|sessionStorage|Math\.random|Date\b|Worker|console\.)\b/); assert.doesNotMatch(source, /\b(?:useState|useEffect|useMemo|useCallback|createElement|addEventListener|dispatchEvent|emit|subscribe|observe)\s*\(/); assert.doesNotMatch(source, /new\s+[A-Z][A-Za-z0-9_$]*\s*\(/); assert.doesNotMatch(source, /class\s+[A-Za-z_$]|extends\s+[A-Za-z_$]/); assert.doesNotMatch(source, /^\s*(?:let|var)\s+[A-Za-z_$]/m); });
});
