import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { describe, it } from "node:test";
import { freezeRendererObject, type RendererObject } from "../renderer/nexoraObjectDirectorRendererAdapterPublicIndex.ts";
import * as scene from "./nexoraObjectDirectorSceneBindingFoundation.ts";

function deeplyFrozen(value: unknown, seen = new Set<object>()): boolean { if (value === null || typeof value !== "object" || seen.has(value as object)) return true; if (!Object.isFrozen(value)) return false; seen.add(value as object); return Object.values(value as Record<string, unknown>).every((child) => deeplyFrozen(child, seen)); }
function renderer(overrides: Partial<RendererObject> = {}): RendererObject { return freezeRendererObject({ id: "renderer-1", type: "NexoraObject", caption: "Revenue", position: { x: 1, y: 2, z: 3 }, rotation: { x: 0.1, y: 0.2, z: 0.3 }, scale: { x: 1, y: 2, z: 1 }, color: { base: "Green", accent: "Blue", background: "White", text: "Black" }, status: "Ready", visibility: "visible", emphasis: "focused", badges: [{ id: "ready", text: "Ready", severity: "success" }, { id: "focus", text: "Focus", severity: "info" }], label: "Revenue label", icon: "object", metadata: { rendererState: "report", nested: { value: 42 } }, ...overrides } as RendererObject); }
const source = readFileSync(new URL("./nexoraObjectDirectorSceneBindingFoundation.ts", import.meta.url), "utf8");

describe("NOL-6:1 Director Scene Binding Foundation", () => {
  it("1-8. exposes exact identity and only the NOL-5 Public Index dependency", () => { assert.equal(scene.foundationId, "NOL-6:1/NexoraObjectDirectorSceneBindingFoundation"); assert.equal(scene.foundationVersion, "6.1.0"); assert.equal(scene.foundationNamespace, "nexora.nol.scene.binding.foundation"); assert.equal(scene.foundationStatus, "Foundation"); assert.equal(scene.foundationLock, "NOL-6-1-DIRECTOR-SCENE-BINDING-FOUNDATION-LOCKED"); const imports = [...source.matchAll(/from\s+["']([^"']+)["']/g)].map((match) => match[1]); assert.deepEqual(imports, ["../renderer/nexoraObjectDirectorRendererAdapterPublicIndex.ts"]); assert.doesNotMatch(source, /from\s+["'][^"']*(?:Foundation|Contracts|Engine|Integration|Validation|Platform|Certification|Freeze|DirectorRuntime)/); });

  it("9-26. publishes exact dynamically counted and deeply frozen registries and defaults", () => { assert.deepEqual(scene.nexoraDirectorSceneNodeKinds, ["object", "group", "label", "badge", "connection", "anchor"]); assert.equal(scene.nexoraDirectorSceneNodeKindCount, scene.nexoraDirectorSceneNodeKinds.length); assert.deepEqual(scene.nexoraDirectorSceneBindingStates, ["bound", "unbound", "suspended"]); assert.equal(scene.nexoraDirectorSceneBindingStateCount, scene.nexoraDirectorSceneBindingStates.length); assert.deepEqual(scene.nexoraDirectorSceneNodeVisibilities, ["visible", "hidden", "collapsed"]); assert.equal(scene.nexoraDirectorSceneNodeVisibilityCount, scene.nexoraDirectorSceneNodeVisibilities.length); assert.deepEqual(scene.nexoraDirectorSceneInteractionModes, ["none", "selectable", "focusable", "actionable"]); assert.equal(scene.nexoraDirectorSceneInteractionModeCount, scene.nexoraDirectorSceneInteractionModes.length); assert.deepEqual(scene.nexoraDirectorSceneDefaultPosition, { x: 0, y: 0, z: 0 }); assert.deepEqual(scene.nexoraDirectorSceneDefaultRotation, { x: 0, y: 0, z: 0 }); assert.deepEqual(scene.nexoraDirectorSceneDefaultScale, { x: 1, y: 1, z: 1 }); assert.deepEqual(scene.nexoraDirectorSceneDefaultBounds, { width: 1, height: 1, depth: 1 }); assert.deepEqual(scene.nexoraDirectorSceneBindingFoundationRegistry, ["Scene Vector", "Scene Bounds", "Scene Transform", "Scene Style", "Scene Label", "Scene Badge", "Interaction Contract", "Relationship Reference", "Scene Node", "Scene Binding", "Binding Collection", "Binding Validation", "Binding Verification"]); assert.equal(scene.nexoraDirectorSceneBindingFoundationRegistryCount, scene.nexoraDirectorSceneBindingFoundationRegistry.length); assert.equal(scene.nexoraDirectorSceneBindingFoundationPublicApiCount, scene.nexoraDirectorSceneBindingFoundationPublicApiSurface.length); assert.equal(scene.nexoraDirectorSceneBindingFoundationPublicApiCount, 16); for (const value of [scene.nexoraDirectorSceneNodeKinds, scene.nexoraDirectorSceneBindingStates, scene.nexoraDirectorSceneNodeVisibilities, scene.nexoraDirectorSceneInteractionModes, scene.nexoraDirectorSceneDefaultPosition, scene.nexoraDirectorSceneDefaultRotation, scene.nexoraDirectorSceneDefaultScale, scene.nexoraDirectorSceneDefaultBounds, scene.nexoraDirectorSceneBindingFoundationRegistry, scene.nexoraDirectorSceneBindingFoundationPublicApiSurface]) assert.equal(deeplyFrozen(value), true); });

  it("27-32. creates valid frozen vectors, bounds, and transforms and rejects invalid numbers", () => { const vector = scene.createNexoraDirectorSceneVector(1, 2, 3), bounds = scene.createNexoraDirectorSceneBounds(4, 5, 0), transform = scene.createNexoraDirectorSceneTransform(vector, { x: 0, y: 0, z: 0 }, { x: 1, y: 2, z: -1 }); assert.deepEqual(vector, { x: 1, y: 2, z: 3 }); assert.deepEqual(bounds, { width: 4, height: 5, depth: 0 }); assert.equal(deeplyFrozen(transform), true); assert.throws(() => scene.createNexoraDirectorSceneVector(Number.NaN, 0, 0), /finite/); assert.throws(() => scene.createNexoraDirectorSceneBounds(-1, 1, 1), /non-negative/); assert.throws(() => scene.createNexoraDirectorSceneTransform(vector, vector, { x: 0, y: 1, z: 1 }), /non-zero/); });

  it("33-41. preserves visibility and resolves binding state and abstract interaction consistently", () => { for (const visibility of scene.nexoraDirectorSceneNodeVisibilities) { const result = scene.resolveNexoraDirectorSceneVisibility(visibility); assert.equal(result.sceneVisibility, visibility); assert.equal(result.supported, true); assert.equal(result.fallbackApplied, false); } assert.deepEqual(scene.resolveNexoraDirectorSceneVisibility("unsupported"), { sourceVisibility: "unsupported", sceneVisibility: "hidden", supported: false, fallbackApplied: true }); assert.equal(scene.resolveNexoraDirectorSceneBindingState("visible").bindingState, "bound"); assert.equal(scene.resolveNexoraDirectorSceneBindingState("hidden").bindingState, "bound"); assert.equal(scene.resolveNexoraDirectorSceneBindingState("collapsed").bindingState, "suspended"); assert.equal(scene.resolveNexoraDirectorSceneBindingState("visible", false).bindingState, "unbound"); const minimum = scene.resolveNexoraDirectorSceneInteraction("minimum"), report = scene.resolveNexoraDirectorSceneInteraction("report"), operation = scene.resolveNexoraDirectorSceneInteraction("operation"); assert.equal(minimum.mode, "selectable"); assert.deepEqual([minimum.selectable, minimum.focusable, minimum.actionable], [true, false, false]); assert.equal(report.mode, "focusable"); assert.deepEqual([report.selectable, report.focusable, report.actionable], [true, true, false]); assert.equal(operation.mode, "actionable"); assert.deepEqual([operation.selectable, operation.focusable, operation.actionable], [true, true, true]); for (const contract of [minimum, report, operation]) { assert.equal(contract.draggable, false); assert.equal(contract.eventHandlersForbidden, true); assert.equal(Object.values(contract).some((value) => typeof value === "function"), false); } });

  it("42-48. derives immutable Seed style, labels, fallbacks, and ordered badges", () => { const value = renderer(), style = scene.resolveNexoraDirectorSceneStyle(value), label = scene.resolveNexoraDirectorSceneLabel(value), badges = scene.resolveNexoraDirectorSceneBadges(value); assert.deepEqual(style, { baseColor: "Green", accentColor: "Blue", backgroundColor: "White", textColor: "Black", opacity: 1, emphasis: true }); assert.equal(style.opacity >= 0 && style.opacity <= 1, true); assert.equal(label.text, "Revenue label"); assert.equal(label.role, "caption"); assert.equal(scene.resolveNexoraDirectorSceneLabel(renderer({ label: "", caption: "" })).text, "renderer-1"); assert.deepEqual(badges.map((badge) => badge.id), ["ready", "focus"]); assert.deepEqual(badges.map((badge) => badge.order), [1, 2]); assert.equal(deeplyFrozen(style) && deeplyFrozen(label) && deeplyFrozen(badges), true); });

  it("49-57. creates a complete abstract Scene Node with stable identity and preserved source semantics", () => { const value = renderer(), relationship = freezeRendererObject({ relationshipId: "rel-1", sourceNodeId: "parent", targetNodeId: "child", relationshipType: "depends-on", directed: true, visible: true }), before = JSON.stringify(value), node = scene.createNexoraDirectorSceneNode({ rendererObject: value, nodeId: "custom-node", kind: "group", parentNodeId: "parent", childNodeIds: ["child-a", "child-b"], relationships: [relationship], bounds: { width: 2, height: 3, depth: 4 } }); assert.equal(scene.createNexoraDirectorSceneNode({ rendererObject: value }).nodeId, "scene-node:renderer-1"); assert.equal(node.nodeId, "custom-node"); assert.equal(node.rendererState, "report"); assert.deepEqual(node.transform.position, value.position); assert.equal(node.visibility, "visible"); assert.deepEqual(node.childNodeIds, ["child-a", "child-b"]); assert.deepEqual(node.relationships, [relationship]); assert.deepEqual(node.metadata, value.metadata); assert.equal(JSON.stringify(value), before); assert.equal(deeplyFrozen(node), true); });

  it("58-71. creates consistent bindings and ordered collections with duplicate-ID truth", () => { const first = renderer(), second = renderer({ id: "renderer-2", caption: "Cost", label: "Cost", metadata: { rendererState: "minimum" } }), node = scene.createNexoraDirectorSceneNode({ rendererObject: first }), binding = scene.createNexoraDirectorSceneBinding(first, node); assert.equal(binding.bindingId, "scene-binding:renderer-1"); assert.equal(binding.sourceRendererObjectId, node.rendererObjectId); assert.equal(binding.nodeId, node.nodeId); assert.equal(binding.state, node.bindingState); assert.equal(binding.sourcePreserved, true); const collection = scene.createNexoraDirectorSceneBindingCollection([first, second]); assert.deepEqual(collection.bindings.map((entry) => entry.sourceRendererObjectId), [first.id, second.id]); assert.deepEqual(collection.nodes.map((entry) => entry.rendererObjectId), [first.id, second.id]); assert.equal(collection.sourceCount, 2); assert.equal(collection.bindingCount, collection.bindings.length); assert.equal(collection.nodeCount, collection.nodes.length); assert.equal(collection.orderPreserved, true); assert.equal(collection.uniqueBindingIds, true); assert.equal(collection.uniqueNodeIds, true); const duplicates = scene.createNexoraDirectorSceneBindingCollection([first, first]); assert.equal(duplicates.uniqueBindingIds, false); assert.equal(duplicates.uniqueNodeIds, false); assert.equal(deeplyFrozen(binding) && deeplyFrozen(collection), true); });

  it("72-83. validates nodes and detects every structural corruption", () => { const valid = scene.createNexoraDirectorSceneNode({ rendererObject: renderer() }); assert.equal(scene.validateNexoraDirectorSceneNode(valid).valid, true); const invalid = (patch: Record<string, unknown>) => scene.validateNexoraDirectorSceneNode(freezeRendererObject({ ...valid, ...patch }) as typeof valid); assert.equal(invalid({ kind: "mesh" }).nodeIdValid, false); assert.equal(invalid({ bindingState: "pending" }).bindingIdValid, false); assert.equal(invalid({ rendererState: "detail" }).rendererObjectValid, false); assert.equal(invalid({ visibility: "gone" }).visibilityValid, false); assert.equal(invalid({ transform: { ...valid.transform, scale: { x: 0, y: 1, z: 1 } } }).transformValid, false); assert.equal(invalid({ bounds: { width: -1, height: 1, depth: 1 } }).boundsValid, false); assert.equal(invalid({ style: { ...valid.style, opacity: 2 } }).styleValid, false); assert.equal(invalid({ interaction: { ...valid.interaction, actionable: true } }).interactionValid, false); assert.equal(invalid({ parentNodeId: valid.nodeId }).hierarchyValid, false); assert.equal(invalid({ childNodeIds: [valid.nodeId] }).hierarchyValid, false); assert.equal(invalid({ childNodeIds: ["child", "child"] }).hierarchyValid, false); });

  it("84-93. validates bindings, preserves sources, and rejects executable or circular metadata", () => { const value = renderer(), before = JSON.stringify(value), node = scene.createNexoraDirectorSceneNode({ rendererObject: value }), binding = scene.createNexoraDirectorSceneBinding(value, node); assert.equal(scene.validateNexoraDirectorSceneBinding(binding).valid, true); assert.throws(() => scene.createNexoraDirectorSceneBinding(renderer({ id: "other" }), node), /inconsistent/); const badNodeId = freezeRendererObject({ ...binding, nodeId: "wrong" }); assert.equal(scene.validateNexoraDirectorSceneBinding(badNodeId).nodeIdValid, false); assert.equal(binding.sourcePreserved, true); assert.equal(JSON.stringify(value), before); assert.deepEqual(value.metadata, { rendererState: "report", nested: { value: 42 } }); const executable = renderer({ metadata: freezeRendererObject({ rendererState: "report", callback: () => true }) }); assert.throws(() => scene.createNexoraDirectorSceneNode({ rendererObject: executable }), /plain values/); const circular: Record<string, unknown> = { rendererState: "report" }; circular.self = circular; const circularSource = renderer({ metadata: freezeRendererObject(circular) }); assert.throws(() => scene.createNexoraDirectorSceneNode({ rendererObject: circularSource }), /plain values|circular/); assert.equal(Object.values(binding.node.interaction).some((entry) => typeof entry === "function"), false); assert.equal(Object.values(binding.node).some((entry) => entry?.constructor?.name === "Mesh"), false); });

  it("94-104. proves structural determinism, source immutability, and deep freezing", () => { const value = renderer(), copy = renderer(), before = JSON.stringify(value), firstNode = scene.createNexoraDirectorSceneNode({ rendererObject: value }), secondNode = scene.createNexoraDirectorSceneNode({ rendererObject: copy }); assert.deepEqual(firstNode, secondNode); assert.deepEqual(scene.createNexoraDirectorSceneBinding(value), scene.createNexoraDirectorSceneBinding(copy)); assert.deepEqual(scene.createNexoraDirectorSceneBindingCollection([value]), scene.createNexoraDirectorSceneBindingCollection([copy])); const report = scene.verifyNexoraDirectorSceneBindingDeterminism(value, copy); assert.equal(report.deterministic, true); assert.equal(report.rendererInputEquivalent && report.nodeEquivalent && report.bindingEquivalent && report.collectionEquivalent, true); assert.equal(JSON.stringify(value), before); const binding = scene.createNexoraDirectorSceneBinding(value), collection = scene.createNexoraDirectorSceneBindingCollection([value]), validation = scene.validateNexoraDirectorSceneBinding(binding); for (const output of [firstNode, binding, collection, firstNode.transform, firstNode.badges, firstNode.metadata, validation, report]) assert.equal(deeplyFrozen(output), true); });

  it("105 and 120. verifies the complete Foundation and readiness for Contracts", () => { const report = scene.verifyNexoraDirectorSceneBindingFoundation(); assert.equal(report.valid, true); for (const [key, value] of Object.entries(report)) if (key !== "violations") assert.equal(value, true, key); assert.deepEqual(report.violations, []); assert.equal(deeplyFrozen(report), true); });

  it("106-119. contains no prohibited dependency, execution, framework, or nondeterminism", () => { assert.doesNotMatch(source, /from\s+["'][^"']*(?:react|next|three|fiber|webgl|canvas|svg|dom)/i); assert.doesNotMatch(source, /\b(?:async|await|Promise|setTimeout|setInterval|requestAnimationFrame|fetch|localStorage|sessionStorage|window|document|globalThis|Math\.random|Date\b|Worker|process|console\.)\b/); assert.doesNotMatch(source, /new\s+(?:Object3D|Mesh|Group|Scene|Camera|Raycaster)|\b(?:Matrix4|Quaternion|Euler|Geometry|Material|Shader|Texture)\b/); assert.doesNotMatch(source, /addEventListener|removeEventListener|emit\s*\(|dispatchEvent|createElement/); assert.doesNotMatch(source, /^\s*(?:let|var)\s+[A-Za-z_$][\w$]*\s*=/m); assert.equal(scene.nexoraDirectorSceneNodeKindCount, scene.nexoraDirectorSceneNodeKinds.length); assert.equal(scene.nexoraDirectorSceneBindingStateCount, scene.nexoraDirectorSceneBindingStates.length); assert.equal(scene.nexoraDirectorSceneNodeVisibilityCount, scene.nexoraDirectorSceneNodeVisibilities.length); assert.equal(scene.nexoraDirectorSceneInteractionModeCount, scene.nexoraDirectorSceneInteractionModes.length); assert.equal(scene.nexoraDirectorSceneBindingFoundationRegistryCount, scene.nexoraDirectorSceneBindingFoundationRegistry.length); assert.equal(scene.nexoraDirectorSceneBindingFoundationPublicApiCount, scene.nexoraDirectorSceneBindingFoundationPublicApiSurface.length); });
});
