/** NOL-6:7 — metadata-only certification for Director Scene Binding adapters. */
import {
  isNexoraObjectDirectorSceneBindingPlatformFrozen,
  isNexoraObjectDirectorSceneBindingPlatformRegistryFrozen,
  isNexoraObjectDirectorSceneBindingReadyForAdapter,
  nexoraObjectDirectorSceneBindingPlatformId,
  nexoraObjectDirectorSceneBindingPlatformNamespace,
  nexoraObjectDirectorSceneBindingPlatformRegistry,
  nexoraObjectDirectorSceneBindingPlatformRegistryCount,
  nexoraObjectDirectorSceneBindingPlatformVersion,
  sceneBindingPlatformApiSurface,
  sceneBindingPlatformCapabilities,
  sceneBindingPlatformStatus,
  verifyNexoraObjectDirectorSceneBindingPlatform,
  verifyNexoraObjectDirectorSceneBindingPlatformRegistry,
} from "./nexoraObjectDirectorSceneBindingPlatform.ts";

export const nexoraObjectDirectorSceneBindingAdapterCertificationId = "NOL-6:7/NexoraObjectDirectorSceneBindingAdapterCertification" as const;
export const nexoraObjectDirectorSceneBindingAdapterCertificationVersion = "6.7.0" as const;
export const nexoraObjectDirectorSceneBindingAdapterCertificationNamespace = "nexora.nol.scene.binding.adapter.certification" as const;
export const sceneBindingAdapterCertificationStatus = freezeOwned({ released: true, certified: true, frozen: true, stable: true, readiness: "ready-for-adapter-freeze" } as const);

function freezeOwned<T>(value: T, visited: object[] = []): T { if (value === null || typeof value !== "object" || visited.includes(value as object)) return value; visited.push(value as object); for (const child of Object.values(value as Record<string, unknown>)) freezeOwned(child, visited); return Object.freeze(value); }
function deeplyFrozen(value: unknown, visited: object[] = []): boolean { if (value === null || typeof value !== "object" || visited.includes(value as object)) return true; if (!Object.isFrozen(value)) return false; visited.push(value as object); return Object.values(value as Record<string, unknown>).every((child) => deeplyFrozen(child, visited)); }
function plainObject(value: unknown): value is Record<string, unknown> { if (value === null || typeof value !== "object" || Array.isArray(value)) return false; const prototype = Object.getPrototypeOf(value); return prototype === Object.prototype || prototype === null; }
function plainData(value: unknown, ancestors: object[] = []): boolean { if (value === null || ["string", "boolean", "undefined"].includes(typeof value)) return true; if (typeof value === "number") return Number.isFinite(value); if (typeof value !== "object") return false; const object = value as object; if (ancestors.includes(object) || !Array.isArray(value) && !plainObject(value)) return false; ancestors.push(object); const valid = Object.values(value).every((child) => plainData(child, ancestors)); ancestors.pop(); return valid; }
function unique(values: readonly string[]): boolean { return values.every((value, index) => values.indexOf(value) === index); }
function trimmed(value: unknown): value is string { return typeof value === "string" && value.length > 0 && value.trim() === value; }
function semanticVersion(value: unknown): value is string { return trimmed(value) && /^(?:0|[1-9]\d*)\.(?:0|[1-9]\d*)\.(?:0|[1-9]\d*)(?:-[0-9A-Za-z.-]+)?$/.test(value); }

export type SceneBindingAdapter = Readonly<{ adapterId: string; adapterName: string; adapterVersion: string; platformVersion: string; capabilities: readonly string[]; supportedApis: readonly string[]; dependencies?: readonly string[] }>;
export type SceneBindingAdapterCertificationLevel = "identity" | "platform" | "capability" | "compatibility" | "release";
export const sceneBindingAdapterCertificationLevels = freezeOwned(["identity", "platform", "capability", "compatibility", "release"] as const satisfies readonly SceneBindingAdapterCertificationLevel[]);
export const sceneBindingAdapterCertificationLevelCount = sceneBindingAdapterCertificationLevels.length;

export const sceneBindingAdapterCertificationCodes = freezeOwned(["ADAPTER_CERTIFIED", "INVALID_IDENTITY", "INVALID_PLATFORM", "INVALID_CAPABILITY", "INVALID_API", "INVALID_METADATA", "INVALID_VERSION", "INVALID_DEPENDENCY", "NOT_PLATFORM_COMPATIBLE", "FREEZE_ELIGIBLE", "FREEZE_INELIGIBLE"] as const);
export type SceneBindingAdapterCertificationCode = typeof sceneBindingAdapterCertificationCodes[number];
export const sceneBindingAdapterCertificationCodeCount = sceneBindingAdapterCertificationCodes.length;
export type SceneBindingAdapterCertificationSeverity = "info" | "warning" | "error" | "fatal";
const sceneBindingAdapterCertificationSeverities = freezeOwned(["info", "warning", "error", "fatal"] as const satisfies readonly SceneBindingAdapterCertificationSeverity[]);
export type SceneBindingAdapterCertificationFinding = Readonly<{ code: SceneBindingAdapterCertificationCode; severity: SceneBindingAdapterCertificationSeverity; message: string }>;
export type SceneBindingAdapterCertificationResult = Readonly<{ certified: boolean; findings: readonly SceneBindingAdapterCertificationFinding[]; passedLevels: readonly SceneBindingAdapterCertificationLevel[]; failedLevels: readonly SceneBindingAdapterCertificationLevel[]; adapterId: string; freezeEligible: boolean }>;

export const sceneBindingAdapterRequiredCapabilities = freezeOwned([...sceneBindingPlatformCapabilities]);
export const sceneBindingAdapterRequiredCapabilityCount = sceneBindingAdapterRequiredCapabilities.length;
export const sceneBindingAdapterRequiredApis = freezeOwned(sceneBindingPlatformApiSurface.map((entry) => entry.exportName));
export const sceneBindingAdapterRequiredApiCount = sceneBindingAdapterRequiredApis.length;
export const sceneBindingAdapterCompatibilityPolicy = freezeOwned({ backwardCompatible: true, breakingChangesAllowed: false, overrideAllowed: false, mutationAllowed: false } as const);

type AdapterAssessment = Readonly<{ adapterId: string; metadataValid: boolean; identityValid: boolean; versionValid: boolean; platformValid: boolean; capabilityValid: boolean; apiValid: boolean; dependencyValid: boolean; platformCompatible: boolean }>;
function orderedRequired(values: unknown, required: readonly string[]): boolean { if (!Array.isArray(values) || !values.every(trimmed) || !unique(values)) return false; let previous = -1; for (const item of required) { const index = values.indexOf(item); if (index <= previous) return false; previous = index; } return true; }
function dependenciesValid(value: unknown): boolean { if (value === undefined) return true; if (!Array.isArray(value) || !value.every(trimmed) || !unique(value)) return false; return value.every((dependency) => dependency === "NOL-6:6" || dependency === nexoraObjectDirectorSceneBindingPlatformId); }
function platformCompatible(): boolean { const verification = verifyNexoraObjectDirectorSceneBindingPlatform(), registry = verifyNexoraObjectDirectorSceneBindingPlatformRegistry(); return nexoraObjectDirectorSceneBindingPlatformId === "NOL-6:6/NexoraObjectDirectorSceneBindingPlatform" && nexoraObjectDirectorSceneBindingPlatformVersion === "6.6.0" && nexoraObjectDirectorSceneBindingPlatformNamespace === "nexora.nol.scene.binding.platform" && sceneBindingPlatformStatus.readiness === "ready-for-adapter" && verification.valid && isNexoraObjectDirectorSceneBindingPlatformFrozen() && isNexoraObjectDirectorSceneBindingReadyForAdapter() && registry.valid && isNexoraObjectDirectorSceneBindingPlatformRegistryFrozen() && nexoraObjectDirectorSceneBindingPlatformRegistryCount === nexoraObjectDirectorSceneBindingPlatformRegistry.length; }
function assessAdapter(input: unknown): AdapterAssessment {
  const allowedFields = ["adapterId", "adapterName", "adapterVersion", "platformVersion", "capabilities", "supportedApis", "dependencies"];
  const metadataValid = plainObject(input) && plainData(input) && Object.keys(input).every((key) => allowedFields.includes(key));
  if (!metadataValid) return freezeOwned({ adapterId: "", metadataValid: false, identityValid: false, versionValid: false, platformValid: false, capabilityValid: false, apiValid: false, dependencyValid: false, platformCompatible: platformCompatible() });
  return freezeOwned({ adapterId: trimmed(input.adapterId) ? input.adapterId : "", metadataValid, identityValid: trimmed(input.adapterId) && trimmed(input.adapterName), versionValid: semanticVersion(input.adapterVersion), platformValid: input.platformVersion === nexoraObjectDirectorSceneBindingPlatformVersion, capabilityValid: orderedRequired(input.capabilities, sceneBindingAdapterRequiredCapabilities), apiValid: orderedRequired(input.supportedApis, sceneBindingAdapterRequiredApis), dependencyValid: dependenciesValid(input.dependencies), platformCompatible: platformCompatible() });
}

function finding(code: SceneBindingAdapterCertificationCode, severity: SceneBindingAdapterCertificationSeverity, message: string): SceneBindingAdapterCertificationFinding { return freezeOwned({ code, severity, message }); }
function canonicalFindings(values: readonly SceneBindingAdapterCertificationFinding[]): readonly SceneBindingAdapterCertificationFinding[] { const output: SceneBindingAdapterCertificationFinding[] = [], keys: string[] = []; for (const value of values) { const key = JSON.stringify([value.code, value.severity, value.message]); if (!keys.includes(key)) { keys.push(key); output.push(value); } } output.sort((left, right) => sceneBindingAdapterCertificationCodes.indexOf(left.code) - sceneBindingAdapterCertificationCodes.indexOf(right.code) || (left.message < right.message ? -1 : left.message > right.message ? 1 : 0)); return freezeOwned(output); }

export function certifyNexoraObjectDirectorSceneBindingAdapter(input: unknown): SceneBindingAdapterCertificationResult {
  const assessment = assessAdapter(input), findings: SceneBindingAdapterCertificationFinding[] = [];
  if (!assessment.metadataValid) findings.push(finding("INVALID_METADATA", "fatal", "Adapter metadata must be immutable-compatible plain data."));
  if (!assessment.identityValid) findings.push(finding("INVALID_IDENTITY", "error", "Adapter identity and name must be non-empty trimmed strings."));
  if (!assessment.versionValid) findings.push(finding("INVALID_VERSION", "error", "Adapter version must be a semantic version."));
  if (!assessment.platformValid) findings.push(finding("INVALID_PLATFORM", "error", "Adapter platform version must match NOL-6:6."));
  if (!assessment.capabilityValid) findings.push(finding("INVALID_CAPABILITY", "error", "Adapter capabilities must include the canonical ordered Platform capabilities without duplicates."));
  if (!assessment.apiValid) findings.push(finding("INVALID_API", "error", "Adapter APIs must include the canonical ordered Platform API identities without duplicates."));
  if (!assessment.dependencyValid) findings.push(finding("INVALID_DEPENDENCY", "fatal", "Adapter dependencies must not bypass the NOL-6:6 Platform."));
  if (!assessment.platformCompatible) findings.push(finding("NOT_PLATFORM_COMPATIBLE", "fatal", "The NOL-6:6 Platform is not structurally ready for adapter certification."));
  const levelPass: Readonly<Record<SceneBindingAdapterCertificationLevel, boolean>> = freezeOwned({ identity: assessment.metadataValid && assessment.identityValid && assessment.versionValid, platform: assessment.platformValid && assessment.apiValid && assessment.platformCompatible, capability: assessment.capabilityValid, compatibility: assessment.metadataValid && assessment.dependencyValid && assessment.platformCompatible, release: assessment.metadataValid && assessment.identityValid && assessment.versionValid && assessment.platformValid && assessment.capabilityValid && assessment.apiValid && assessment.dependencyValid && assessment.platformCompatible });
  const passedLevels = freezeOwned(sceneBindingAdapterCertificationLevels.filter((level) => levelPass[level])), failedLevels = freezeOwned(sceneBindingAdapterCertificationLevels.filter((level) => !levelPass[level])), certified = failedLevels.length === 0;
  findings.push(certified ? finding("ADAPTER_CERTIFIED", "info", "Adapter metadata satisfies the NOL-6:6 Platform contract.") : finding("FREEZE_INELIGIBLE", "error", "Adapter certification is not eligible for NOL-6:8 Freeze."));
  if (certified) findings.push(finding("FREEZE_ELIGIBLE", "info", "Certified adapter metadata is eligible for NOL-6:8 Freeze."));
  const ordered = canonicalFindings(findings), freezeEligible = certified && !ordered.some((entry) => entry.severity === "error" || entry.severity === "fatal");
  return freezeOwned({ certified, findings: ordered, passedLevels, failedLevels, adapterId: assessment.adapterId, freezeEligible });
}

function hasCertificationCode(value: unknown): value is SceneBindingAdapterCertificationCode { const codes: readonly string[] = sceneBindingAdapterCertificationCodes; return typeof value === "string" && codes.includes(value); }
function hasCertificationLevel(value: unknown): value is SceneBindingAdapterCertificationLevel { const levels: readonly string[] = sceneBindingAdapterCertificationLevels; return typeof value === "string" && levels.includes(value); }
function hasCertificationSeverity(value: unknown): value is SceneBindingAdapterCertificationSeverity { const severities: readonly string[] = sceneBindingAdapterCertificationSeverities; return typeof value === "string" && severities.includes(value); }
function canonicalLevelSubset(values: readonly unknown[]): boolean { let previous = -1; for (const value of values) { if (!hasCertificationLevel(value)) return false; const index = sceneBindingAdapterCertificationLevels.indexOf(value); if (index <= previous) return false; previous = index; } return true; }
function certificationResult(value: unknown): value is SceneBindingAdapterCertificationResult { if (!plainObject(value) || !plainData(value) || typeof value.certified !== "boolean" || typeof value.freezeEligible !== "boolean" || typeof value.adapterId !== "string" || !Array.isArray(value.findings) || !Array.isArray(value.passedLevels) || !Array.isArray(value.failedLevels)) return false; const levels: string[] = []; for (const level of [...value.passedLevels, ...value.failedLevels]) { if (!hasCertificationLevel(level)) return false; levels.push(level); } return value.findings.every((entry) => plainObject(entry) && hasCertificationCode(entry.code) && hasCertificationSeverity(entry.severity) && typeof entry.message === "string") && canonicalLevelSubset(value.passedLevels) && canonicalLevelSubset(value.failedLevels) && unique(levels) && levels.length === sceneBindingAdapterCertificationLevels.length && value.certified === (value.failedLevels.length === 0) && (!value.freezeEligible || value.certified && value.findings.some((entry) => plainObject(entry) && entry.code === "FREEZE_ELIGIBLE") && !value.findings.some((entry) => plainObject(entry) && (entry.severity === "error" || entry.severity === "fatal"))); }
export function isNexoraObjectDirectorSceneBindingAdapterCertified(value: unknown): boolean { return certificationResult(value) && value.certified; }
export function isNexoraObjectDirectorSceneBindingAdapterFreezeEligible(value: unknown): boolean { return certificationResult(value) && value.freezeEligible; }
export function getNexoraObjectDirectorSceneBindingAdapterCertificationSummary(result: SceneBindingAdapterCertificationResult): Readonly<{ adapterId: string; certified: boolean; freezeEligible: boolean; passedLevelCount: number; failedLevelCount: number; findingCount: number; nextPhase: "NOL-6:8" }> { return freezeOwned({ adapterId: result.adapterId, certified: result.certified, freezeEligible: result.freezeEligible, passedLevelCount: result.passedLevels.length, failedLevelCount: result.failedLevels.length, findingCount: result.findings.length, nextPhase: "NOL-6:8" }); }

export const nexoraObjectDirectorSceneBindingAdapterCertificationPublicApiSurface = freezeOwned(["certifyNexoraObjectDirectorSceneBindingAdapter", "verifyNexoraObjectDirectorSceneBindingAdapterCertification", "isNexoraObjectDirectorSceneBindingAdapterCertified", "isNexoraObjectDirectorSceneBindingAdapterFreezeEligible", "getNexoraObjectDirectorSceneBindingAdapterCertificationSummary", "getNexoraObjectDirectorSceneBindingAdapterCertificationRegistry", "getNexoraObjectDirectorSceneBindingAdapterCertificationRegistryCount", "verifyNexoraObjectDirectorSceneBindingAdapterCertificationRegistry", "isNexoraObjectDirectorSceneBindingAdapterCertificationRegistryFrozen"] as const);
export const nexoraObjectDirectorSceneBindingAdapterCertificationPublicApiCount = nexoraObjectDirectorSceneBindingAdapterCertificationPublicApiSurface.length;
export const nexoraObjectDirectorSceneBindingAdapterCertificationRegistry = freezeOwned(["Identity", "Levels", "Codes", "Findings", "Result", "Registry", "Public APIs", "Dependency", "Release"].map((name, index) => freezeOwned({ name, order: index + 1 })));
export const nexoraObjectDirectorSceneBindingAdapterCertificationRegistryCount = nexoraObjectDirectorSceneBindingAdapterCertificationRegistry.length;
export function getNexoraObjectDirectorSceneBindingAdapterCertificationRegistry(): typeof nexoraObjectDirectorSceneBindingAdapterCertificationRegistry { return nexoraObjectDirectorSceneBindingAdapterCertificationRegistry; }
export function getNexoraObjectDirectorSceneBindingAdapterCertificationRegistryCount(): number { return nexoraObjectDirectorSceneBindingAdapterCertificationRegistry.length; }
export function isNexoraObjectDirectorSceneBindingAdapterCertificationRegistryFrozen(): boolean { return deeplyFrozen(nexoraObjectDirectorSceneBindingAdapterCertificationRegistry) && deeplyFrozen(nexoraObjectDirectorSceneBindingAdapterCertificationPublicApiSurface) && deeplyFrozen(sceneBindingAdapterCertificationLevels) && deeplyFrozen(sceneBindingAdapterCertificationCodes) && deeplyFrozen(sceneBindingAdapterRequiredCapabilities) && deeplyFrozen(sceneBindingAdapterRequiredApis); }
export function verifyNexoraObjectDirectorSceneBindingAdapterCertificationRegistry(): Readonly<{ valid: boolean; ordered: boolean; unique: boolean; countValid: boolean; publicApisValid: boolean; dependencyValid: boolean; releaseValid: boolean; frozen: boolean; violations: readonly string[] }> { const ordered = nexoraObjectDirectorSceneBindingAdapterCertificationRegistry.every((entry, index) => entry.order === index + 1), names = nexoraObjectDirectorSceneBindingAdapterCertificationRegistry.map((entry) => entry.name), uniqueEntries = unique(names), countValid = nexoraObjectDirectorSceneBindingAdapterCertificationRegistryCount === nexoraObjectDirectorSceneBindingAdapterCertificationRegistry.length, publicApisValid = nexoraObjectDirectorSceneBindingAdapterCertificationPublicApiCount === nexoraObjectDirectorSceneBindingAdapterCertificationPublicApiSurface.length && unique([...nexoraObjectDirectorSceneBindingAdapterCertificationPublicApiSurface]), dependencyValid = platformCompatible(), releaseValid = sceneBindingAdapterCertificationStatus.released && sceneBindingAdapterCertificationStatus.certified && sceneBindingAdapterCertificationStatus.frozen && sceneBindingAdapterCertificationStatus.stable && sceneBindingAdapterCertificationStatus.readiness === "ready-for-adapter-freeze", frozen = isNexoraObjectDirectorSceneBindingAdapterCertificationRegistryFrozen(), checks: readonly [boolean, string][] = [[ordered, "Adapter Certification registry order is invalid"], [uniqueEntries, "Adapter Certification registry entries are duplicated"], [countValid, "Adapter Certification registry count is invalid"], [publicApisValid, "Adapter Certification Public APIs are invalid"], [dependencyValid, "Adapter Certification dependency is invalid"], [releaseValid, "Adapter Certification release metadata is invalid"], [frozen, "Adapter Certification registry is mutable"]], violations = checks.filter(([passed]) => !passed).map(([, message]) => message); return freezeOwned({ valid: violations.length === 0, ordered, unique: uniqueEntries, countValid, publicApisValid, dependencyValid, releaseValid, frozen, violations: freezeOwned(violations) }); }
export function verifyNexoraObjectDirectorSceneBindingAdapterCertification(): Readonly<{ valid: boolean; registryValid: boolean; identityValid: boolean; apiSurfaceValid: boolean; capabilityDeclarationsValid: boolean; dependencyDeclarationsValid: boolean; releaseMetadataValid: boolean; checkCount: number; violations: readonly string[] }> { const registry = verifyNexoraObjectDirectorSceneBindingAdapterCertificationRegistry(), identityValid = nexoraObjectDirectorSceneBindingAdapterCertificationId === "NOL-6:7/NexoraObjectDirectorSceneBindingAdapterCertification" && nexoraObjectDirectorSceneBindingAdapterCertificationVersion === "6.7.0" && nexoraObjectDirectorSceneBindingAdapterCertificationNamespace === "nexora.nol.scene.binding.adapter.certification", apiSurfaceValid = nexoraObjectDirectorSceneBindingAdapterCertificationPublicApiCount === 9 && unique([...nexoraObjectDirectorSceneBindingAdapterCertificationPublicApiSurface]), capabilityDeclarationsValid = sceneBindingAdapterRequiredCapabilityCount === sceneBindingAdapterRequiredCapabilities.length && unique([...sceneBindingAdapterRequiredCapabilities]), dependencyDeclarationsValid = platformCompatible(), releaseMetadataValid = sceneBindingAdapterCertificationStatus.readiness === "ready-for-adapter-freeze", checks: readonly [boolean, string][] = [[registry.valid, "Registry verification failed"], [identityValid, "Identity verification failed"], [apiSurfaceValid, "Public API verification failed"], [capabilityDeclarationsValid, "Capability verification failed"], [dependencyDeclarationsValid, "Dependency verification failed"], [releaseMetadataValid, "Release metadata verification failed"]], violations = checks.filter(([passed]) => !passed).map(([, message]) => message); return freezeOwned({ valid: violations.length === 0, registryValid: registry.valid, identityValid, apiSurfaceValid, capabilityDeclarationsValid, dependencyDeclarationsValid, releaseMetadataValid, checkCount: checks.length, violations: freezeOwned(violations) }); }
