export type {
  DomainRecommendationAssumptionLookupResult,
  DomainRecommendationConstraintLookupResult,
  DomainRecommendationDiff,
  DomainRecommendationDiffEntry,
  DomainRecommendationDiffType,
  DomainRecommendationFilter,
  DomainRecommendationInputLookupResult,
  DomainRecommendationLookupResult,
  DomainRecommendationMetadataLookup,
  DomainRecommendationOutputLookupResult,
  DomainRecommendationQuery,
  DomainRecommendationRationaleLookupResult,
  DomainRecommendationReferenceLookupResult,
  DomainRecommendationSnapshot,
  DomainRecommendationSnapshotEntry,
  DomainRecommendationSortDirection,
  DomainRecommendationSortKey,
} from "./domainRecommendationQueryTypes.ts";
export {
  filterDomainRecommendationPackages,
  findRecommendationPackageContainingContract,
  findRecommendationPackagesByDomain,
  findRecommendationPackagesByScope,
  findRecommendationPackagesByStatus,
  queryDomainRecommendationPackages,
  sortDomainRecommendationPackages,
} from "./domainRecommendationQuery.ts";
export {
  findDomainRecommendationContract,
  findRecommendationAssumptions,
  findRecommendationConfidenceMetadata,
  findRecommendationConstraints,
  findRecommendationInputs,
  findRecommendationOutputs,
  findRecommendationRationale,
  findRecommendationTraceMetadata,
  findRecommendationUncertaintyMetadata,
} from "./domainRecommendationLookup.ts";
export {
  buildDomainRecommendationReferenceLookup,
  findRecommendationsReferencingKpi,
  findRecommendationsReferencingOntologyAttribute,
  findRecommendationsReferencingOntologyEntity,
  findRecommendationsReferencingReasoning,
  findRecommendationsReferencingRegulation,
  findRecommendationsReferencingVocabularyTerm,
} from "./domainRecommendationReferenceInspection.ts";
export {
  buildDomainRecommendationSnapshot,
  compareDomainRecommendationSnapshots,
  diffDomainRecommendationSnapshots,
  validateDomainRecommendationSnapshot,
} from "./domainRecommendationSnapshot.ts";

import {
  findDomainRecommendationContract,
  findRecommendationAssumptions,
  findRecommendationConfidenceMetadata,
  findRecommendationConstraints,
  findRecommendationInputs,
  findRecommendationOutputs,
  findRecommendationRationale,
  findRecommendationTraceMetadata,
  findRecommendationUncertaintyMetadata,
} from "./domainRecommendationLookup.ts";
import {
  filterDomainRecommendationPackages,
  findRecommendationPackageContainingContract,
  findRecommendationPackagesByDomain,
  findRecommendationPackagesByScope,
  findRecommendationPackagesByStatus,
  queryDomainRecommendationPackages,
  sortDomainRecommendationPackages,
} from "./domainRecommendationQuery.ts";
import {
  buildDomainRecommendationReferenceLookup,
  findRecommendationsReferencingKpi,
  findRecommendationsReferencingOntologyAttribute,
  findRecommendationsReferencingOntologyEntity,
  findRecommendationsReferencingReasoning,
  findRecommendationsReferencingRegulation,
  findRecommendationsReferencingVocabularyTerm,
} from "./domainRecommendationReferenceInspection.ts";
import {
  buildDomainRecommendationSnapshot,
  compareDomainRecommendationSnapshots,
  diffDomainRecommendationSnapshots,
  validateDomainRecommendationSnapshot,
} from "./domainRecommendationSnapshot.ts";

export const DomainRecommendationQueryLayer = Object.freeze({
  queryDomainRecommendationPackages,
  filterDomainRecommendationPackages,
  sortDomainRecommendationPackages,
  findRecommendationPackagesByDomain,
  findRecommendationPackagesByScope,
  findRecommendationPackagesByStatus,
  findRecommendationPackageContainingContract,
  findDomainRecommendationContract,
  findRecommendationInputs,
  findRecommendationOutputs,
  findRecommendationRationale,
  findRecommendationConstraints,
  findRecommendationAssumptions,
  findRecommendationConfidenceMetadata,
  findRecommendationUncertaintyMetadata,
  findRecommendationTraceMetadata,
  findRecommendationsReferencingVocabularyTerm,
  findRecommendationsReferencingOntologyEntity,
  findRecommendationsReferencingOntologyAttribute,
  findRecommendationsReferencingKpi,
  findRecommendationsReferencingRegulation,
  findRecommendationsReferencingReasoning,
  buildDomainRecommendationReferenceLookup,
  buildDomainRecommendationSnapshot,
  validateDomainRecommendationSnapshot,
  compareDomainRecommendationSnapshots,
  diffDomainRecommendationSnapshots,
});
