/**
 * Nexora Type-C Architecture Freeze Registry.
 * Authoritative frozen contracts — extend only via explicit architecture review.
 */

import { MAIN_RIGHT_PANEL_TABS } from "../ui/mainRightPanelContract.ts";
import { CANONICAL_NEXORA_LEFT_NAV_ITEMS } from "../ui/nexoraLeftNavContract.ts";
import { CANONICAL_OBJECT_SELECTION_OWNER } from "./nexoraArchitectureFreezeConstants.ts";
import { CANONICAL_DASHBOARD_RUNTIME_OWNER } from "../dashboard/dashboardRuntimeContract.ts";
import { CANONICAL_DASHBOARD_CONTEXT_ROUTER } from "../dashboard/dashboardContextTypes.ts";
import { CANONICAL_DASHBOARD_ACCORDION_OWNER } from "../dashboard/dashboardAccordionPanelContract.ts";
import { CANONICAL_DASHBOARD_VISUAL_OWNER } from "../dashboard/dashboardVisualSignalContract.ts";
import { CANONICAL_EXECUTIVE_SUMMARY_OWNER } from "../dashboard/executiveSummary/executiveSummaryContract.ts";
import { CANONICAL_OPERATIONAL_INTELLIGENCE_OWNER } from "../dashboard/operationalIntelligence/operationalIntelligenceContract.ts";
import { CANONICAL_RISK_INTELLIGENCE_OWNER } from "../dashboard/riskIntelligence/riskIntelligenceContract.ts";
import { CANONICAL_TIMELINE_INTELLIGENCE_OWNER } from "../dashboard/timelineIntelligence/timelineIntelligenceContract.ts";
import { CANONICAL_SCENARIO_INTELLIGENCE_OWNER } from "../dashboard/scenarioIntelligence/scenarioIntelligenceContract.ts";
import { CANONICAL_WAR_ROOM_INTELLIGENCE_OWNER } from "../dashboard/warRoomIntelligence/warRoomIntelligenceContract.ts";
import { CANONICAL_EXECUTIVE_ADVISORY_OWNER } from "../dashboard/executiveAdvisory/executiveAdvisoryContract.ts";
import { CANONICAL_ADVISORY_AGGREGATION_OWNER } from "../dashboard/executiveAdvisory/aggregation/advisoryContextContract.ts";
import { CANONICAL_ADVISORY_CONFIDENCE_OWNER } from "../dashboard/executiveAdvisory/confidence/advisoryConfidenceContract.ts";
import { CANONICAL_ADVISORY_EXPLAINABILITY_OWNER } from "../dashboard/executiveAdvisory/explainability/advisoryExplainabilityContract.ts";
import { CANONICAL_DECISION_GUIDANCE_OWNER } from "../dashboard/decisionGuidance/decisionGuidanceContract.ts";
import { CANONICAL_ADVISORY_WAR_ROOM_INTEGRATION_OWNER } from "../dashboard/advisoryWarRoomIntegration/advisoryWarRoomIntegrationContract.ts";
import { CANONICAL_GOVERNANCE_INTELLIGENCE_OWNER } from "../dashboard/governanceIntelligence/governanceIntelligenceContract.ts";
import { CANONICAL_STRATEGIC_ALIGNMENT_OWNER } from "../dashboard/strategicAlignment/strategicAlignmentContract.ts";
import { CANONICAL_POLICY_CONSTRAINT_INTELLIGENCE_OWNER } from "../dashboard/policyConstraintIntelligence/policyConstraintIntelligenceContract.ts";
import { CANONICAL_STAKEHOLDER_INTELLIGENCE_OWNER } from "../dashboard/stakeholderIntelligence/stakeholderIntelligenceContract.ts";
import { CANONICAL_CONSENSUS_INTELLIGENCE_OWNER } from "../dashboard/consensusIntelligence/consensusIntelligenceContract.ts";
import { CANONICAL_INSTITUTIONAL_ALIGNMENT_OWNER } from "../dashboard/institutionalAlignment/institutionalAlignmentContract.ts";
import { DASHBOARD_PERFORMANCE_BUDGETS } from "../dashboard/dashboardPerformanceBudget.ts";
import {
  CANONICAL_DASHBOARD_HOME_OWNER,
  DASHBOARD_HOME_MVP_APPROVAL_STATUS,
} from "../dashboard/dashboardHomeFreeze/dashboardHomeFreezeContract.ts";

export type ArchitectureFreezeDomain =
  | "right_panel"
  | "scene_runtime"
  | "selection"
  | "navigation"
  | "dashboard_routing"
  | "dashboard_home";

export type FrozenArchitectureContract = Readonly<{
  id: string;
  domain: ArchitectureFreezeDomain;
  title: string;
  owner: string;
  allowed: readonly string[];
  prohibited: readonly string[];
  notes?: string;
}>;

export const NEXORA_ARCHITECTURE_FREEZE_REGISTRY = Object.freeze({
  version: "2.5.0",
  phase: "Type-C Executive",
  description:
    "Frozen Nexora manager workspace architecture. New features may extend surfaces; they must not replace ownership contracts silently.",
  contracts: Object.freeze([
    Object.freeze({
      id: "mrp.dashboard_assistant_only",
      domain: "right_panel",
      title: "Main Right Panel surfaces",
      owner: "mainRightPanelContract + mainRightPanelRuntimeEnforcement",
      allowed: [...MAIN_RIGHT_PANEL_TABS],
      prohibited: [
        "legacy_scene_tab",
        "legacy_objects_tab",
        "legacy_focus_tab",
        "legacy_right_rail_runtime_surface",
        "workspace_mrp_tab",
        "object_mrp_tab",
        "risk_mrp_tab",
      ],
      notes: "Dashboard and Assistant only. Legacy right-rail views redirect to Dashboard context.",
    }),
    Object.freeze({
      id: "scene.scene_native_interactions",
      domain: "scene_runtime",
      title: "Scene-native interactions",
      owner: "SceneCanvas + SceneContext + topology runtime",
      allowed: [
        "scene_native_object_click",
        "scene_native_hud_panels",
        "topology_driven_placement",
        "scene_context_mirror",
      ],
      prohibited: ["hidden_legacy_scene_owner", "duplicate_scene_runtime_owner", "legacy_scene_mrp_tab"],
      notes: "Scene interactions stay scene-native; MRP does not own scene/object/focus tabs.",
    }),
    Object.freeze({
      id: "selection.single_owner",
      domain: "selection",
      title: "Object selection ownership",
      owner: CANONICAL_OBJECT_SELECTION_OWNER,
      allowed: [CANONICAL_OBJECT_SELECTION_OWNER],
      prohibited: [
        "SceneContext.selectedId_authority",
        "objectPlacementRuntime_authority",
        "duplicate_selection_pipeline",
        "competing_selection_managers",
      ],
      notes: "SceneContext.selectedId mirrors HomeScreen authority; it must not become a competing owner.",
    }),
    Object.freeze({
      id: "navigation.canonical_hydration",
      domain: "navigation",
      title: "Left navigation canonical hydration",
      owner: "leftNavCanonicalHydration + NexoraShell",
      allowed: [
        "canonical_left_nav_modes",
        "preferredRightPanelTab_seed",
        "inspector_context_bridge",
      ],
      prohibited: [
        "hydration_time_navigation_replacement",
        "multiple_navigation_authorities",
        "client_only_default_plane_switch",
      ],
      notes: "SSR and client must derive the same left-nav state from preferredRightPanelTab.",
    }),
    Object.freeze({
      id: "routing.dashboard_context_only",
      domain: "dashboard_routing",
      title: "Dashboard context routing",
      owner: "nexoraRoutingContract + mainRightPanelContract",
      allowed: [
        "overview",
        "sources",
        "scenario",
        "risk",
        "war_room",
        "timeline",
        "settings",
      ],
      prohibited: ["legacy_mrp_tab_route", "unauthorized_mrp_tab_creation", "duplicate_route_state"],
      notes: "Left-nav modes route into Dashboard context; legacy routes are compatibility inputs only.",
    }),
    Object.freeze({
      id: "dashboard.runtime_foundation",
      domain: "dashboard_routing",
      title: "Dashboard runtime foundation",
      owner: CANONICAL_DASHBOARD_RUNTIME_OWNER,
      allowed: [
        "dashboard_runtime_contract",
        "dashboard_surface_registry",
        "dashboard_runtime_container",
        "dashboard_context_bridge",
      ],
      prohibited: [
        "duplicate_dashboard_owner",
        "parallel_dashboard_render_path",
        "legacy_router_dashboard_ownership",
        "unauthorized_mrp_dashboard_tab",
      ],
      notes: "Dashboard surfaces render through DashboardRuntimeContainer; workspace state owns dashboard context.",
    }),
    Object.freeze({
      id: "dashboard.context_routing",
      domain: "dashboard_routing",
      title: "Dashboard context routing",
      owner: CANONICAL_DASHBOARD_CONTEXT_ROUTER,
      allowed: [
        "dashboard_context_router",
        "context_normalization",
        "surface_resolution",
        "context_lifecycle",
        "approved_source_routing",
      ],
      prohibited: [
        "direct_dashboard_context_write",
        "parallel_dashboard_routing",
        "legacy_router_context_ownership",
        "raw_payload_surface_render",
      ],
      notes: "All executive context flows through DashboardContextRouter before reaching DashboardRuntimeContainer.",
    }),
    Object.freeze({
      id: "dashboard.accordion_system",
      domain: "dashboard_routing",
      title: "Dashboard accordion presentation",
      owner: CANONICAL_DASHBOARD_ACCORDION_OWNER,
      allowed: [
        "dashboard_accordion_runtime",
        "accordion_panel_contract",
        "accordion_registry",
        "multi_panel_expansion",
        "header_always_visible",
        "panel_priority_ordering",
        "expansion_persistence",
      ],
      prohibited: [
        "standalone_dashboard_panel_system",
        "competing_dashboard_layout",
        "custom_panel_contract",
        "forced_single_panel_mode",
        "accordion_bypass_render",
      ],
      notes: "All dashboard surfaces render through DashboardAccordionSystem inside DashboardRuntimeContainer.",
    }),
    Object.freeze({
      id: "dashboard.performance_optimization",
      domain: "dashboard_routing",
      title: "Dashboard runtime performance optimization",
      owner: "dashboardPerformanceMetrics + dashboardPerformanceRegression",
      allowed: [
        "dashboard_trace_profiling",
        "context_route_dedupe",
        "accordion_panel_cache",
        "performance_budgets",
        "regression_warnings",
      ],
      prohibited: [
        "architecture_bypass_for_speed",
        "removed_context_router",
        "removed_accordion_system",
        "runtime_crash_on_slow_trace",
      ],
      notes: `Performance budgets (goals): context routing < ${DASHBOARD_PERFORMANCE_BUDGETS.contextRoutingMs}ms, trace < ${DASHBOARD_PERFORMANCE_BUDGETS.dashboardTraceMs}ms.`,
    }),
    Object.freeze({
      id: "dashboard.visual_intelligence",
      domain: "dashboard_routing",
      title: "Dashboard executive visual intelligence",
      owner: CANONICAL_DASHBOARD_VISUAL_OWNER,
      allowed: [
        "micro_charts",
        "impact_cards",
        "trend_indicators",
        "accordion_header_signals",
        "visual_signal_framework",
        "day_night_token_adaptation",
      ],
      prohibited: [
        "full_analytics_dashboard",
        "large_chart_canvas",
        "spreadsheet_interface",
        "kpi_wall_layout",
        "analytics_heavy_layout",
        "visual_bypass_accordion",
      ],
      notes: "Lightweight executive visual signals inside accordion panels — not a BI reporting layer.",
    }),
    Object.freeze({
      id: "dashboard.executive_summary_surface",
      domain: "dashboard_routing",
      title: "Executive Summary intelligence surface",
      owner: CANONICAL_EXECUTIVE_SUMMARY_OWNER,
      allowed: [
        "executive_summary_runtime",
        "summary_aggregation_contract",
        "executive_attention_model",
        "summary_cards",
        "default_dashboard_landing",
        "visual_framework_integration",
      ],
      prohibited: [
        "independent_executive_dashboard",
        "runtime_container_bypass",
        "context_router_bypass",
        "parallel_summary_owner",
        "bi_reporting_layout",
      ],
      notes: "Executive Summary Surface is the default dashboard landing intelligence layer inside DashboardRuntimeContainer.",
    }),
    Object.freeze({
      id: "dashboard.operational_intelligence_surface",
      domain: "dashboard_routing",
      title: "Operational Intelligence surface",
      owner: CANONICAL_OPERATIONAL_INTELLIGENCE_OWNER,
      allowed: [
        "operational_intelligence_runtime",
        "operational_aggregation_contract",
        "operational_health_card",
        "operational_domain_cards",
        "executive_summary_feed",
        "visual_framework_integration",
      ],
      prohibited: [
        "standalone_operational_dashboard",
        "runtime_container_bypass",
        "context_router_bypass",
        "parallel_operational_owner",
        "executive_summary_ownership",
        "bi_reporting_layout",
      ],
      notes: "Operational Intelligence feeds Executive Summary through approved snapshot contract only.",
    }),
    Object.freeze({
      id: "dashboard.risk_intelligence_surface",
      domain: "dashboard_routing",
      title: "Risk Intelligence surface",
      owner: CANONICAL_RISK_INTELLIGENCE_OWNER,
      allowed: [
        "risk_intelligence_runtime",
        "risk_aggregation_contract",
        "active_risks_card",
        "risk_domain_cards",
        "operational_intelligence_feed",
        "executive_summary_feed",
        "visual_framework_integration",
      ],
      prohibited: [
        "standalone_risk_dashboard",
        "runtime_container_bypass",
        "context_router_bypass",
        "parallel_risk_owner",
        "executive_summary_ownership",
        "predictive_forecasting_layout",
      ],
      notes: "Risk Intelligence consumes Operational Intelligence and feeds Executive Summary through approved snapshots.",
    }),
    Object.freeze({
      id: "dashboard.timeline_intelligence_surface",
      domain: "dashboard_routing",
      title: "Timeline Intelligence surface",
      owner: CANONICAL_TIMELINE_INTELLIGENCE_OWNER,
      allowed: [
        "timeline_intelligence_runtime",
        "timeline_aggregation_contract",
        "timeline_momentum_card",
        "timeline_domain_cards",
        "graphical_timeline_contract",
        "operational_intelligence_feed",
        "risk_intelligence_feed",
        "executive_summary_feed",
        "visual_framework_integration",
      ],
      prohibited: [
        "standalone_timeline_dashboard",
        "runtime_container_bypass",
        "context_router_bypass",
        "parallel_timeline_owner",
        "executive_summary_ownership",
        "gantt_planning_layout",
        "forecasting_engine",
      ],
      notes: "Timeline Intelligence provides temporal awareness and feeds Risk and Executive Summary through approved snapshots.",
    }),
    Object.freeze({
      id: "dashboard.scenario_intelligence_surface",
      domain: "dashboard_routing",
      title: "Scenario Intelligence surface",
      owner: CANONICAL_SCENARIO_INTELLIGENCE_OWNER,
      allowed: [
        "scenario_intelligence_runtime",
        "scenario_aggregation_contract",
        "scenario_portfolio_card",
        "scenario_domain_cards",
        "scenario_comparison_contract",
        "war_room_escalation_contract",
        "operational_intelligence_feed",
        "risk_intelligence_feed",
        "timeline_intelligence_feed",
        "executive_summary_feed",
        "visual_framework_integration",
      ],
      prohibited: [
        "standalone_scenario_dashboard",
        "runtime_container_bypass",
        "context_router_bypass",
        "parallel_scenario_owner",
        "executive_summary_ownership",
        "predictive_forecasting_engine",
        "autonomous_decision_engine",
        "simulation_engine",
      ],
      notes: "Scenario Intelligence organizes alternative futures and feeds Executive Summary through approved snapshots.",
    }),
    Object.freeze({
      id: "dashboard.war_room_intelligence_surface",
      domain: "dashboard_routing",
      title: "War Room Intelligence surface",
      owner: CANONICAL_WAR_ROOM_INTELLIGENCE_OWNER,
      allowed: [
        "war_room_intelligence_runtime",
        "war_room_aggregation_contract",
        "situation_overview_card",
        "critical_risks_card",
        "timeline_pressure_card",
        "scenario_comparison_card",
        "tradeoff_analysis_card",
        "decision_focus_card",
        "advisory_integration_contract",
        "operational_intelligence_feed",
        "risk_intelligence_feed",
        "timeline_intelligence_feed",
        "scenario_intelligence_feed",
        "executive_summary_feed",
        "visual_framework_integration",
      ],
      prohibited: [
        "standalone_war_room_application",
        "runtime_container_bypass",
        "context_router_bypass",
        "parallel_war_room_owner",
        "executive_summary_ownership",
        "autonomous_decision_engine",
        "advisory_intelligence_engine",
        "simulation_engine",
      ],
      notes: "War Room Intelligence unifies intelligence streams into executive decision context.",
    }),
    Object.freeze({
      id: "dashboard.executive_advisory_surface",
      domain: "dashboard_routing",
      title: "Executive Advisory surface",
      owner: CANONICAL_EXECUTIVE_ADVISORY_OWNER,
      allowed: [
        "executive_advisory_runtime",
        "advisory_aggregation_contract",
        "advisory_focus_card",
        "priority_signals_card",
        "advisory_narrative_card",
        "guidance_candidates_card",
        "advisory_confidence_card",
        "war_room_context_feed",
        "operational_intelligence_feed",
        "risk_intelligence_feed",
        "timeline_intelligence_feed",
        "scenario_intelligence_feed",
        "war_room_intelligence_feed",
        "executive_summary_feed",
        "visual_framework_integration",
      ],
      prohibited: [
        "standalone_advisory_dashboard",
        "runtime_container_bypass",
        "context_router_bypass",
        "parallel_advisory_owner",
        "executive_summary_ownership",
        "autonomous_decision_engine",
        "confidence_scoring_engine",
        "explainability_engine",
        "governance_engine",
      ],
      notes: "Executive Advisory organizes guidance from intelligence feeds without replacing executive judgment.",
    }),
    Object.freeze({
      id: "dashboard.advisory_context_aggregation",
      domain: "dashboard_routing",
      title: "Advisory Context Aggregation",
      owner: CANONICAL_ADVISORY_AGGREGATION_OWNER,
      allowed: [
        "advisory_aggregation_runtime",
        "advisory_aggregation_registry",
        "advisory_input_contract",
        "context_normalization",
        "priority_scoring",
        "advisory_context_generation",
        "reasoning_trace_contract",
        "aggregation_audit_trail",
        "operational_intelligence_feed",
        "risk_intelligence_feed",
        "timeline_intelligence_feed",
        "scenario_intelligence_feed",
        "war_room_intelligence_feed",
        "executive_advisory_feed",
        "executive_summary_feed",
      ],
      prohibited: [
        "parallel_advisory_aggregation",
        "raw_intelligence_consumption_by_surface",
        "runtime_container_bypass",
        "context_router_bypass",
        "recommendation_engine",
        "confidence_scoring_engine",
        "explainability_ui",
        "autonomous_decision_engine",
      ],
      notes: "Advisory Context Aggregation normalizes intelligence into structured advisory context.",
    }),
    Object.freeze({
      id: "dashboard.advisory_confidence_framework",
      domain: "dashboard_routing",
      title: "Advisory Confidence Framework",
      owner: CANONICAL_ADVISORY_CONFIDENCE_OWNER,
      allowed: [
        "advisory_confidence_runtime",
        "confidence_input_contract",
        "evidence_coverage_evaluation",
        "evidence_consistency_evaluation",
        "evidence_freshness_evaluation",
        "source_diversity_evaluation",
        "reasoning_stability_evaluation",
        "overall_confidence_aggregation",
        "confidence_explanation_contract",
        "confidence_visual_layer",
        "advisory_context_feed",
        "executive_advisory_feed",
        "executive_summary_feed",
      ],
      prohibited: [
        "parallel_confidence_owner",
        "legacy_confidence_scoring",
        "raw_intelligence_consumption",
        "runtime_container_bypass",
        "context_router_bypass",
        "explainability_ui",
        "recommendation_engine",
        "autonomous_decision_engine",
      ],
      notes: "Advisory Confidence Framework is the canonical confidence authority for executive guidance.",
    }),
    Object.freeze({
      id: "dashboard.advisory_explainability_layer",
      domain: "dashboard_routing",
      title: "Advisory Explainability Layer",
      owner: CANONICAL_ADVISORY_EXPLAINABILITY_OWNER,
      allowed: [
        "advisory_explainability_runtime",
        "explainability_input_contract",
        "guidance_explanation_generator",
        "supporting_evidence_layer",
        "confidence_driver_layer",
        "confidence_limiter_layer",
        "reasoning_path_renderer",
        "assumptions_unknowns_layer",
        "explainability_visual_layer",
        "advisory_context_feed",
        "confidence_framework_feed",
        "executive_advisory_feed",
        "executive_summary_feed",
        "war_room_intelligence_feed",
      ],
      prohibited: [
        "parallel_explainability_owner",
        "legacy_explainability_engine",
        "raw_intelligence_consumption",
        "runtime_container_bypass",
        "context_router_bypass",
        "recommendation_engine",
        "autonomous_decision_engine",
        "governance_engine",
      ],
      notes: "Advisory Explainability Layer is the canonical explanation authority for executive guidance.",
    }),
    Object.freeze({
      id: "dashboard.decision_guidance_surface",
      domain: "dashboard_routing",
      title: "Decision Guidance Surface",
      owner: CANONICAL_DECISION_GUIDANCE_OWNER,
      allowed: [
        "decision_guidance_runtime",
        "decision_guidance_contract",
        "decision_focus_card",
        "executive_guidance_card",
        "confidence_summary_card",
        "explanation_summary_card",
        "tradeoff_summary_card",
        "decision_context_card",
        "executive_advisory_feed",
        "confidence_framework_feed",
        "explainability_layer_feed",
        "war_room_intelligence_feed",
        "executive_summary_feed",
        "visual_framework_integration",
      ],
      prohibited: [
        "parallel_decision_guidance_owner",
        "standalone_guidance_system",
        "autonomous_decision_engine",
        "recommendation_engine",
        "governance_engine",
        "runtime_container_bypass",
        "context_router_bypass",
        "raw_intelligence_consumption",
      ],
      notes: "Decision Guidance Surface is the primary executive decision preparation interface.",
    }),
    Object.freeze({
      id: "dashboard.advisory_war_room_integration",
      domain: "dashboard_routing",
      title: "Advisory–War Room Integration Layer",
      owner: CANONICAL_ADVISORY_WAR_ROOM_INTEGRATION_OWNER,
      allowed: [
        "advisory_war_room_integration_runtime",
        "integration_registry",
        "war_room_intake_contract",
        "advisory_transformation_layer",
        "confidence_propagation_layer",
        "explainability_propagation_layer",
        "tradeoff_propagation_layer",
        "guidance_delivery_layer",
        "integration_trace_contract",
        "war_room_intelligence_feed",
        "executive_advisory_feed",
        "decision_guidance_feed",
        "executive_summary_feed",
      ],
      prohibited: [
        "parallel_integration_owner",
        "bypassed_integration_path",
        "direct_war_room_to_guidance_bypass",
        "duplicate_advisory_ownership",
        "parallel_guidance_pipeline",
        "autonomous_decision_engine",
        "runtime_container_bypass",
      ],
      notes: "Advisory–War Room Integration is the canonical bridge for executive decision context.",
    }),
    Object.freeze({
      id: "dashboard.governance_intelligence_surface",
      domain: "dashboard_routing",
      title: "Governance Intelligence Surface",
      owner: CANONICAL_GOVERNANCE_INTELLIGENCE_OWNER,
      allowed: [
        "governance_intelligence_runtime",
        "governance_intelligence_contract",
        "governance_context_contract",
        "governance_aggregation_layer",
        "governance_alignment_card",
        "policy_awareness_card",
        "constraint_awareness_card",
        "stakeholder_impact_card",
        "accountability_context_card",
        "governance_attention_card",
        "decision_guidance_feed",
        "executive_advisory_feed",
        "confidence_framework_feed",
        "explainability_layer_feed",
        "war_room_intelligence_feed",
        "scenario_intelligence_feed",
        "executive_summary_feed",
        "visual_framework_integration",
      ],
      prohibited: [
        "parallel_governance_owner",
        "legacy_governance_engine",
        "governance_engine",
        "compliance_automation",
        "approval_engine",
        "autonomous_governance_system",
        "recommendation_engine",
        "runtime_container_bypass",
        "context_router_bypass",
        "raw_intelligence_consumption",
      ],
      notes: "Governance Intelligence is the canonical institutional alignment awareness layer.",
    }),
    Object.freeze({
      id: "dashboard.strategic_alignment_surface",
      domain: "dashboard_routing",
      title: "Strategic Alignment Surface",
      owner: CANONICAL_STRATEGIC_ALIGNMENT_OWNER,
      allowed: [
        "strategic_alignment_runtime",
        "strategic_alignment_contract",
        "strategic_context_contract",
        "strategic_objective_registry",
        "alignment_evaluation_layer",
        "alignment_score_card",
        "objectives_impact_card",
        "strategic_direction_card",
        "strategic_tradeoff_card",
        "strategic_tension_card",
        "strategic_confidence_card",
        "strategic_attention_card",
        "decision_guidance_feed",
        "governance_intelligence_feed",
        "executive_advisory_feed",
        "confidence_framework_feed",
        "war_room_intelligence_feed",
        "scenario_intelligence_feed",
        "executive_summary_feed",
        "visual_framework_integration",
      ],
      prohibited: [
        "parallel_strategic_owner",
        "legacy_strategic_engine",
        "governance_engine",
        "enterprise_strategy_engine",
        "autonomous_strategic_decision_system",
        "goal_tracking_software",
        "recommendation_engine",
        "runtime_container_bypass",
        "context_router_bypass",
        "raw_intelligence_consumption",
      ],
      notes: "Strategic Alignment is the canonical institutional direction awareness layer.",
    }),
    Object.freeze({
      id: "dashboard.policy_constraint_intelligence_surface",
      domain: "dashboard_routing",
      title: "Policy & Constraint Intelligence Surface",
      owner: CANONICAL_POLICY_CONSTRAINT_INTELLIGENCE_OWNER,
      allowed: [
        "policy_constraint_intelligence_runtime",
        "policy_constraint_intelligence_contract",
        "policy_context_contract",
        "policy_registry",
        "policy_evaluation_layer",
        "constraint_evaluation_layer",
        "policy_alignment_card",
        "policy_impact_card",
        "resource_constraints_card",
        "operational_constraints_card",
        "governance_constraints_card",
        "constraint_severity_card",
        "policy_attention_card",
        "decision_guidance_feed",
        "governance_intelligence_feed",
        "strategic_alignment_feed",
        "scenario_intelligence_feed",
        "war_room_intelligence_feed",
        "executive_summary_feed",
        "visual_framework_integration",
      ],
      prohibited: [
        "parallel_policy_owner",
        "legacy_policy_engine",
        "governance_engine",
        "compliance_enforcement",
        "approval_workflow_engine",
        "autonomous_policy_enforcement",
        "regulatory_engine",
        "recommendation_engine",
        "runtime_container_bypass",
        "context_router_bypass",
        "raw_intelligence_consumption",
      ],
      notes: "Policy & Constraint Intelligence is the canonical institutional guardrail layer.",
    }),
    Object.freeze({
      id: "dashboard.stakeholder_intelligence_surface",
      domain: "dashboard_routing",
      title: "Stakeholder Intelligence Surface",
      owner: CANONICAL_STAKEHOLDER_INTELLIGENCE_OWNER,
      allowed: [
        "stakeholder_intelligence_runtime",
        "stakeholder_intelligence_contract",
        "stakeholder_context_contract",
        "stakeholder_registry",
        "stakeholder_evaluation_layer",
        "stakeholder_visibility_card",
        "stakeholder_impact_card",
        "stakeholder_alignment_card",
        "stakeholder_influence_card",
        "stakeholder_tension_card",
        "stakeholder_support_card",
        "stakeholder_confidence_card",
        "stakeholder_attention_card",
        "decision_guidance_feed",
        "governance_intelligence_feed",
        "strategic_alignment_feed",
        "policy_constraint_intelligence_feed",
        "scenario_intelligence_feed",
        "war_room_intelligence_feed",
        "confidence_framework_feed",
        "executive_summary_feed",
        "visual_framework_integration",
      ],
      prohibited: [
        "parallel_stakeholder_owner",
        "legacy_stakeholder_engine",
        "people_management_software",
        "organizational_voting_system",
        "hr_system",
        "autonomous_stakeholder_management",
        "consensus_engine",
        "recommendation_engine",
        "runtime_container_bypass",
        "context_router_bypass",
        "raw_intelligence_consumption",
      ],
      notes: "Stakeholder Intelligence is the canonical organizational impact awareness layer.",
    }),
    Object.freeze({
      id: "dashboard.consensus_intelligence_surface",
      domain: "dashboard_routing",
      title: "Consensus Intelligence Surface",
      owner: CANONICAL_CONSENSUS_INTELLIGENCE_OWNER,
      allowed: [
        "consensus_intelligence_runtime",
        "consensus_intelligence_contract",
        "consensus_context_contract",
        "consensus_registry",
        "consensus_evaluation_layer",
        "consensus_level_card",
        "alignment_zones_card",
        "disagreement_zones_card",
        "convergence_card",
        "divergence_card",
        "institutional_tension_card",
        "consensus_confidence_card",
        "consensus_attention_card",
        "stakeholder_intelligence_feed",
        "policy_constraint_intelligence_feed",
        "strategic_alignment_feed",
        "governance_intelligence_feed",
        "decision_guidance_feed",
        "confidence_framework_feed",
        "executive_summary_feed",
        "visual_framework_integration",
      ],
      prohibited: [
        "parallel_consensus_owner",
        "legacy_consensus_engine",
        "voting_software",
        "board_governance_workflow",
        "enterprise_approval_engine",
        "autonomous_consensus_generation",
        "recommendation_engine",
        "runtime_container_bypass",
        "context_router_bypass",
        "raw_intelligence_consumption",
      ],
      notes: "Consensus Intelligence is the canonical institutional alignment awareness layer.",
    }),
    Object.freeze({
      id: "dashboard.institutional_alignment_surface",
      domain: "dashboard_routing",
      title: "Institutional Alignment Surface",
      owner: CANONICAL_INSTITUTIONAL_ALIGNMENT_OWNER,
      allowed: [
        "institutional_alignment_runtime",
        "institutional_alignment_contract",
        "institutional_context_contract",
        "institutional_aggregation_layer",
        "institutional_evaluation_layer",
        "institutional_health_card",
        "governance_status_card",
        "strategic_alignment_status_card",
        "policy_status_card",
        "stakeholder_status_card",
        "consensus_status_card",
        "institutional_attention_card",
        "board_intelligence_contract",
        "governance_intelligence_feed",
        "strategic_alignment_feed",
        "policy_constraint_intelligence_feed",
        "stakeholder_intelligence_feed",
        "consensus_intelligence_feed",
        "executive_summary_feed",
        "visual_framework_integration",
      ],
      prohibited: [
        "parallel_institutional_owner",
        "legacy_institutional_engine",
        "corporate_reporting_system",
        "board_intelligence_engine",
        "enterprise_governance_workflow",
        "organizational_voting_system",
        "portfolio_governance_engine",
        "recommendation_engine",
        "runtime_container_bypass",
        "context_router_bypass",
        "raw_intelligence_consumption",
      ],
      notes: "Institutional Alignment is the canonical executive institutional command center.",
    }),
    Object.freeze({
      id: "dashboard.home_executive_landing_surface",
      domain: "dashboard_home",
      title: "Dashboard Home Executive Landing Surface",
      owner: CANONICAL_DASHBOARD_HOME_OWNER,
      allowed: [
        "executive_status_zone",
        "executive_action_zone",
        "executive_guidance_zone",
        "executive_continuity_zone",
        "overview_default_landing",
        "workspace_launch_from_home",
        "read_only_home_projections",
        "object_panel_mode_launch",
        "assistant_tab_isolation",
      ],
      prohibited: [
        "hierarchy_reorder",
        "replace_dashboard_home",
        "bypass_dashboard_home",
        "merge_dashboard_assistant",
        "dashboard_home_as_dedicated_mode",
        "assistant_replaces_home",
        "object_panel_replaces_home",
        "legacy_right_rail_home_authority",
        "polling_home_layers",
        "operations_wallboard_drift",
      ],
      notes: `Dashboard Home is the MVP executive landing surface (${DASHBOARD_HOME_MVP_APPROVAL_STATUS}). MRP:10:10 freeze — extend modes/intelligence; do not alter hierarchy without migration.`,
    }),
  ] satisfies readonly FrozenArchitectureContract[]),
  coverageMatrix: Object.freeze({
    rightPanel: Object.freeze(["dashboard", "assistant", "legacy_surface_detection"]),
    navigation: Object.freeze(["canonical_ownership", "hydration_stability"]),
    selection: Object.freeze(["single_ownership", "selection_contract"]),
    sceneRuntime: Object.freeze(["scene_ownership", "topology_ownership"]),
    dashboardRouting: Object.freeze([
      "dashboard_context_routing",
      "deprecated_route_detection",
      "dashboard_runtime_foundation",
      "dashboard_context_routing",
      "dashboard_accordion_system",
      "dashboard_performance_optimization",
      "dashboard_visual_intelligence",
      "dashboard_executive_summary_surface",
      "dashboard_operational_intelligence_surface",
      "dashboard_risk_intelligence_surface",
      "dashboard_timeline_intelligence_surface",
      "dashboard_scenario_intelligence_surface",
      "dashboard_war_room_intelligence_surface",
      "dashboard_executive_advisory_surface",
      "dashboard_advisory_context_aggregation",
      "dashboard_advisory_confidence_framework",
      "dashboard_advisory_explainability_layer",
      "dashboard_decision_guidance_surface",
      "dashboard_advisory_war_room_integration",
      "dashboard_governance_intelligence_surface",
      "dashboard_strategic_alignment_surface",
      "dashboard_policy_constraint_intelligence_surface",
      "dashboard_stakeholder_intelligence_surface",
      "dashboard_consensus_intelligence_surface",
      "dashboard_institutional_alignment_surface",
      "dashboard_home_executive_landing_surface",
    ]),
  }),
  leftNavModeCount: CANONICAL_NEXORA_LEFT_NAV_ITEMS.length,
  selectionAuthority: CANONICAL_OBJECT_SELECTION_OWNER,
});

export type ArchitectureFreezeRegistry = typeof NEXORA_ARCHITECTURE_FREEZE_REGISTRY;
