import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { describe, it } from "node:test";
import {
  assessRendererAdapterCertificationReadiness,
  certificationId,
  certificationLock,
  certificationNamespace,
  certificationStatus,
  certificationVersion,
  certifyRendererAdapterPlatformArchitecture,
  certifyRendererAdapterPlatformBehavior,
  certifyRendererAdapterPlatformRelease,
  certifyRendererAdapterPlatformStructure,
  collectRendererAdapterCertificationEvidence,
  collectRendererAdapterCertificationFindings,
  createRendererAdapterCertificationFinding,
  createRendererAdapterCertificationSummary,
  executeRendererAdapterCertification,
  isRendererAdapterPlatformCertificationRejected,
  isRendererAdapterPlatformCertified,
  isRendererAdapterPlatformConditionallyCertified,
  isRendererAdapterPlatformFreezeReady,
  rendererAdapterCertificationCompatibility,
  rendererAdapterCertificationLevelCount,
  rendererAdapterCertificationLevels,
  rendererAdapterCertificationOutcomeCount,
  rendererAdapterCertificationOutcomes,
  rendererAdapterCertificationPipeline,
  rendererAdapterCertificationPipelineStepCount,
  rendererAdapterCertificationPolicy,
  rendererAdapterCertificationPublicApiCount,
  rendererAdapterCertificationPublicApiSurface,
  rendererAdapterCertificationRegistry,
  rendererAdapterCertificationRegistryCount,
  rendererAdapterCertificationRequirementCount,
  rendererAdapterCertificationRequirements,
  rendererAdapterCertificationSeverities,
  rendererAdapterCertificationSeverityCount,
  resolveRendererAdapterCertificationLevels,
  validateRendererAdapterCertificationRequest,
  verifyRendererAdapterCertification,
  verifyRendererAdapterCertificationDeterminism,
  type NexoraObjectDirectorRendererAdapterCertificationFinding,
  type NexoraObjectDirectorRendererAdapterCertificationRequest,
  type NexoraObjectDirectorRendererAdapterCertificationRequirementResult,
  type RendererAdapterCertificationLevel,
} from "./nexoraObjectDirectorRendererAdapterCertification.ts";

function freeze<T>(value: T, seen = new Set<object>()): T { if (value === null || typeof value !== "object" || seen.has(value as object)) return value; seen.add(value as object); Object.values(value as Record<string, unknown>).forEach((child) => freeze(child, seen)); return Object.freeze(value); }
function deeplyFrozen(value: unknown, seen = new Set<object>()): boolean { if (value === null || typeof value !== "object" || seen.has(value as object)) return true; if (!Object.isFrozen(value)) return false; seen.add(value as object); return Object.values(value as Record<string, unknown>).every((child) => deeplyFrozen(child, seen)); }
function request(levels: readonly RendererAdapterCertificationLevel[] = rendererAdapterCertificationLevels, options: Partial<NexoraObjectDirectorRendererAdapterCertificationRequest> = {}): NexoraObjectDirectorRendererAdapterCertificationRequest { return freeze({ certificationId: "certification-request", requestedLevels: levels, includeFindings: true, includeEvidence: true, executeBehaviorChecks: true, failOnWarning: false, ...options }); }
const source = readFileSync(new URL("./nexoraObjectDirectorRendererAdapterCertification.ts", import.meta.url), "utf8");

describe("NOL-5:7 Director Renderer Adapter Certification", () => {
  it("1-12. exposes exact identity and a Platform-only production dependency", () => { assert.equal(certificationId, "NOL-5:7/NexoraObjectDirectorRendererAdapterCertification"); assert.equal(certificationVersion, "5.7.0"); assert.equal(certificationNamespace, "nexora.nol.renderer.adapter.certification"); assert.equal(certificationStatus, "Certification"); assert.equal(certificationLock, "NOL-5-7-DIRECTOR-RENDERER-ADAPTER-CERTIFICATION-LOCKED"); const imports = [...source.matchAll(/from\s+["']([^"']+)["']/g)].map((match) => match[1]); assert.deepEqual(imports, ["./nexoraObjectDirectorRendererAdapterPlatform.ts"]); assert.doesNotMatch(imports.join(" "), /Validation|Integration|Engine|Contracts|Foundation|nexoraObjectDirectorRuntime/i); });

  it("13-40 and 137-138. exposes exact dynamically counted and frozen registries", () => { assert.deepEqual(rendererAdapterCertificationLevels, ["structural", "behavioral", "architectural", "release"]); assert.equal(rendererAdapterCertificationLevelCount, rendererAdapterCertificationLevels.length); assert.deepEqual(rendererAdapterCertificationOutcomes, ["certified", "conditionally-certified", "rejected"]); assert.equal(rendererAdapterCertificationOutcomeCount, rendererAdapterCertificationOutcomes.length); assert.deepEqual(rendererAdapterCertificationSeverities, ["information", "warning", "error", "blocker"]); assert.equal(rendererAdapterCertificationSeverityCount, rendererAdapterCertificationSeverities.length); assert.deepEqual(rendererAdapterCertificationRequirements.map((entry) => entry.order), Array.from({ length: 32 }, (_, index) => index + 1)); assert.equal(new Set(rendererAdapterCertificationRequirements.map((entry) => entry.id)).size, 32); assert.equal(rendererAdapterCertificationRequirements.every((entry) => entry.mandatory), true); assert.equal(rendererAdapterCertificationRequirements.filter((entry) => ["architectural", "release"].includes(entry.level)).every((entry) => entry.freezeBlocking), true); assert.equal(rendererAdapterCertificationRequirementCount, rendererAdapterCertificationRequirements.length); assert.deepEqual(rendererAdapterCertificationPipeline.map((entry) => entry.order), Array.from({ length: 15 }, (_, index) => index + 1)); assert.equal(rendererAdapterCertificationPipelineStepCount, rendererAdapterCertificationPipeline.length); assert.equal(rendererAdapterCertificationRegistryCount, rendererAdapterCertificationRegistry.length); assert.equal(rendererAdapterCertificationPublicApiCount, rendererAdapterCertificationPublicApiSurface.length); for (const value of [rendererAdapterCertificationLevels, rendererAdapterCertificationOutcomes, rendererAdapterCertificationSeverities, rendererAdapterCertificationRequirements, rendererAdapterCertificationPipeline, rendererAdapterCertificationPolicy, rendererAdapterCertificationCompatibility, rendererAdapterCertificationRegistry, rendererAdapterCertificationPublicApiSurface]) assert.equal(deeplyFrozen(value), true); });

  it("41-47. validates immutable requests and canonicalizes duplicate levels", () => { const valid = request(), before = JSON.stringify(valid); assert.equal(validateRendererAdapterCertificationRequest(valid).valid, true); assert.equal(validateRendererAdapterCertificationRequest(request(rendererAdapterCertificationLevels, { certificationId: "" })).certificationIdValid, false); assert.equal(validateRendererAdapterCertificationRequest(request([])).levelsValid, false); assert.equal(validateRendererAdapterCertificationRequest(request(["unknown" as RendererAdapterCertificationLevel])).levelsValid, false); assert.deepEqual(resolveRendererAdapterCertificationLevels(["release", "structural", "release", "behavioral"]), ["structural", "behavioral", "release"]); assert.throws(() => resolveRendererAdapterCertificationLevels(["unknown" as RendererAdapterCertificationLevel]), /Unsupported certification level/); assert.equal(JSON.stringify(valid), before); });

  it("48-53. creates plain frozen findings and orders and de-duplicates them", () => { const structural = rendererAdapterCertificationRequirements[0], behavioral = rendererAdapterCertificationRequirements[6], first = createRendererAdapterCertificationFinding({ requirementId: behavioral.id, level: behavioral.level, severity: behavioral.severity, passed: true, code: "BEHAVIOR", message: "Behavior passed.", expected: freeze({ nested: true }), actual: freeze({ nested: true }), freezeBlocking: behavioral.freezeBlocking }), second = createRendererAdapterCertificationFinding({ requirementId: structural.id, level: structural.level, severity: structural.severity, passed: true, code: "STRUCTURE", message: "Structure passed.", expected: true, actual: true, freezeBlocking: structural.freezeBlocking }); assert.equal(deeplyFrozen(first.expected) && deeplyFrozen(first.actual), true); assert.deepEqual(collectRendererAdapterCertificationFindings([first, second], [first]).map((item) => item.requirementId), [structural.id, behavioral.id]); assert.throws(() => createRendererAdapterCertificationFinding({ ...first, level: "release" }), /inconsistent/); assert.throws(() => createRendererAdapterCertificationFinding({ ...first, severity: "unknown" as typeof first.severity }), /inconsistent/); });

  it("54-57. collects deterministic evidence and rejects executable or circular values", () => { const evidence = { evidenceId: "evidence-1", requirementId: "CERT-STRUCT-001", source: certificationId, path: "identity", value: freeze({ valid: true }), frozen: true }, collected = collectRendererAdapterCertificationEvidence([evidence], [evidence]); assert.equal(collected.length, 1); assert.equal(deeplyFrozen(collected), true); assert.throws(() => collectRendererAdapterCertificationEvidence([{ ...evidence, value: () => true }]), /plain values/); const circular: Record<string, unknown> = {}; circular.self = circular; assert.throws(() => collectRendererAdapterCertificationEvidence([{ ...evidence, value: circular }]), /circular/); });

  it("58-63. certifies all structural Platform requirements", () => { const results = certifyRendererAdapterPlatformStructure(); assert.equal(results.length, 6); assert.equal(results.every((entry) => entry.passed), true); assert.deepEqual(results.map((entry) => entry.requirement.id), rendererAdapterCertificationRequirements.slice(0, 6).map((entry) => entry.id)); assert.equal(deeplyFrozen(results), true); });

  it("64-75. certifies representative behavior and refuses false disabled attestation", () => { const executed = certifyRendererAdapterPlatformBehavior(true), disabled = certifyRendererAdapterPlatformBehavior(false); assert.equal(executed.length, 10); assert.equal(executed.every((entry) => entry.passed), true); assert.equal(executed.some((entry) => entry.requirement.id === "CERT-BEHAV-002"), true); assert.equal(executed.some((entry) => entry.requirement.id === "CERT-BEHAV-005"), true); assert.equal(executed.some((entry) => entry.requirement.id === "CERT-BEHAV-008"), true); assert.equal(executed.some((entry) => entry.requirement.id === "CERT-BEHAV-009"), true); assert.equal(disabled.every((entry) => !entry.passed && entry.findings[0].severity === "information"), true); const fullDisabled = executeRendererAdapterCertification(request(rendererAdapterCertificationLevels, { executeBehaviorChecks: false })); assert.equal(fullDisabled.certified, false); assert.equal(fullDisabled.freezeReady, false); assert.equal(fullDisabled.outcome, "rejected"); });

  it("76-86. certifies every architectural safety and dependency requirement", () => { const results = certifyRendererAdapterPlatformArchitecture(); assert.equal(results.length, 10); assert.equal(results.every((entry) => entry.passed && entry.requirement.freezeBlocking), true); assert.deepEqual(results.map((entry) => entry.requirement.id), rendererAdapterCertificationRequirements.slice(16, 26).map((entry) => entry.id)); assert.equal(deeplyFrozen(results), true); });

  it("87-93. attests Platform health, readiness, verification, guarantees, and Freeze transition", () => { const lower = [...certifyRendererAdapterPlatformStructure(), ...certifyRendererAdapterPlatformBehavior(), ...certifyRendererAdapterPlatformArchitecture()], release = certifyRendererAdapterPlatformRelease(lower); assert.equal(release.length, 6); assert.equal(release.every((entry) => entry.passed && entry.requirement.freezeBlocking), true); assert.equal(release[0].evidence[0].value && typeof release[0].evidence[0].value === "object", true); });

  it("94-107. resolves certified, conditional, rejected, partial, and Freeze-ready outcomes", () => { const structural = certifyRendererAdapterPlatformStructure(), partial = executeRendererAdapterCertification(request(["structural"])), full = executeRendererAdapterCertification(request()); assert.equal(partial.certified, true); assert.equal(partial.freezeReady, false); assert.equal(full.certified, true); assert.equal(full.freezeReady, true); assert.equal(full.outcome, "certified"); const base = structural[0], warningFinding: NexoraObjectDirectorRendererAdapterCertificationFinding = freeze({ ...base.findings[0], severity: "warning", passed: false }), warningResult: NexoraObjectDirectorRendererAdapterCertificationRequirementResult = freeze({ ...base, passed: false, findings: freeze([warningFinding]), freezeBlockingFailure: false }), conditional = createRendererAdapterCertificationSummary([warningResult], ["structural"], false), warningRejected = createRendererAdapterCertificationSummary([warningResult], ["structural"], true); assert.equal(conditional.outcome, "conditionally-certified"); assert.equal(conditional.freezeReady, false); assert.equal(warningRejected.outcome, "rejected"); assert.equal(warningResult.findings[0].severity, "warning"); const errorResult = freeze({ ...base, passed: false, findings: freeze([{ ...base.findings[0], passed: false }]) }), blocker = certifyRendererAdapterPlatformArchitecture()[0], blockerResult = freeze({ ...blocker, passed: false, findings: freeze([{ ...blocker.findings[0], passed: false }]), freezeBlockingFailure: true }); assert.equal(createRendererAdapterCertificationSummary([errorResult], ["structural"], false).outcome, "rejected"); assert.equal(createRendererAdapterCertificationSummary([blockerResult], ["architectural"], false).outcome, "rejected"); });

  it("108-114. respects finding and evidence flags and preserves Platform attestation truth", () => { const complete = executeRendererAdapterCertification(request()), omitted = executeRendererAdapterCertification(request(rendererAdapterCertificationLevels, { includeFindings: false, includeEvidence: false })); assert.ok(complete.findings.length > 0); assert.ok(complete.evidence.length > 0); assert.deepEqual(omitted.findings, []); assert.deepEqual(omitted.evidence, []); assert.equal(omitted.summary.findingCount, 32); assert.equal(complete.platformHealth.healthy, true); assert.equal(complete.platformReadiness.ready, true); assert.equal(complete.platformVerification.valid, true); });

  it("115-120. exposes certification predicates, readiness, and exact compatibility", () => { const certified = executeRendererAdapterCertification(request()), rejected = executeRendererAdapterCertification(request([], { certificationId: "" })); assert.equal(isRendererAdapterPlatformCertified(certified), true); assert.equal(isRendererAdapterPlatformConditionallyCertified(certified), false); assert.equal(isRendererAdapterPlatformCertificationRejected(rejected), true); assert.equal(isRendererAdapterPlatformFreezeReady(certified), true); const readiness = assessRendererAdapterCertificationReadiness(); assert.equal(readiness.ready && readiness.freezeTransitionReady, true); assert.deepEqual(rendererAdapterCertificationCompatibility, { certificationIdentity: certificationId, platformIdentity: "NOL-5:6/NexoraObjectDirectorRendererAdapterPlatform", compatiblePlatformVersion: "5.6.0", platformOnlyDependency: true, structuralCertificationCompatible: true, behavioralCertificationCompatible: true, architecturalCertificationCompatible: true, releaseCertificationCompatible: true, freezeTransitionCompatible: true, rendererFrameworkAgnostic: true }); });

  it("121-130. proves determinism, deep freezing, and non-mutation without repair", () => { const original = request(), cloned = freeze({ ...original, requestedLevels: freeze([...original.requestedLevels]) }), first = executeRendererAdapterCertification(original), before = JSON.stringify(first.platformVerification); assert.deepEqual(first, executeRendererAdapterCertification(original)); assert.equal(verifyRendererAdapterCertificationDeterminism(original, cloned).deterministic, true); assert.equal(deeplyFrozen(first), true); assert.equal(deeplyFrozen(first.requirementResults), true); assert.equal(deeplyFrozen(first.findings), true); assert.equal(deeplyFrozen(first.evidence), true); assert.equal(deeplyFrozen(first.summary), true); assert.equal(JSON.stringify(first.platformVerification), before); assert.equal(rendererAdapterCertificationPolicy.certificationDoesNotRepair, true); assert.equal(rendererAdapterCertificationPolicy.runtimeMutationForbidden, true); });

  it("131-140. verifies Certification, prohibited-capability absence, and Freeze readiness", () => { const report = verifyRendererAdapterCertification(); assert.equal(report.valid, true); assert.equal(report.freezeTransitionValid, true); assert.equal(report.publicSurfacesFrozen, true); assert.equal(deeplyFrozen(report), true); assert.doesNotMatch(source, /from\s+["'][^"']*(?:Validation|Integration|Engine|Contracts|Foundation|nexoraObjectDirectorRuntime|react|next|three|webgl|canvas|svg|dom)/i); assert.doesNotMatch(source, /\b(?:async|await|Promise|setTimeout|setInterval|fetch|localStorage|sessionStorage|window|document|globalThis|Math\.random|Date\b|Worker|process|filesystem)\b|new\s+(?:Mesh|Scene|Camera|Renderer)|console\./); assert.equal(executeRendererAdapterCertification(request()).freezeReady, true); });
});
