/** NOL-5:5 — immutable validation of the public renderer-adapter Integration. */
import {
  assessRendererAdapterIntegrationReadiness,
  freezeRendererObject,
  integrateRendererAdapterCollection,
  integrateRendererAdapterObject,
  integrationId,
  integrationVersion,
  rendererAdapterIntegrationStages,
  validateRendererAdapterCollectionIntegrationRequest,
  validateRendererAdapterIntegrationRequest,
  verifyRendererAdapterIntegration,
  verifyRendererValueFrozen,
  type NexoraObjectDirectorRendererAdapterCollectionIntegrationRequest,
  type NexoraObjectDirectorRendererAdapterCollectionIntegrationResult,
  type NexoraObjectDirectorRendererAdapterIntegrationRequest,
  type NexoraObjectDirectorRendererAdapterIntegrationResult,
  type RendererAdapterIntegrationSummary,
  type RendererAdapterIntegrationTrace,
} from "./nexoraObjectDirectorRendererAdapterIntegration.ts";

// NOL-5:5 exposes canonical immutability primitives to the Platform boundary.
export { freezeRendererObject, verifyRendererValueFrozen };

export const validationId = "NOL-5:5/NexoraObjectDirectorRendererAdapterValidation" as const;
export const validationVersion = "5.5.0" as const;
export const validationNamespace = "nexora.nol.renderer.adapter.validation" as const;
export const validationStatus = "Validation" as const;
export const validationLock = "NOL-5-5-DIRECTOR-RENDERER-ADAPTER-VALIDATION-LOCKED" as const;

export type RendererAdapterValidationSeverity = "info" | "warning" | "error" | "critical";
export type RendererAdapterValidationRuleCategory = "identity" | "dependency" | "request" | "integration" | "renderer-output" | "collection" | "determinism" | "immutability" | "compatibility" | "architecture";

export interface NexoraObjectDirectorRendererAdapterValidationRule { readonly id: string; readonly order: number; readonly name: string; readonly category: RendererAdapterValidationRuleCategory; readonly severity: RendererAdapterValidationSeverity; readonly required: true; readonly description: string; }
export interface NexoraObjectDirectorRendererAdapterValidationFinding { readonly ruleId: string; readonly category: RendererAdapterValidationRuleCategory; readonly severity: RendererAdapterValidationSeverity; readonly valid: boolean; readonly code: string; readonly message: string; readonly path: string; readonly expected: unknown; readonly actual: unknown; }
export interface NexoraObjectDirectorRendererAdapterValidationRequest { readonly validationId: string; readonly integrationRequest: NexoraObjectDirectorRendererAdapterIntegrationRequest; readonly executeIntegration: boolean; readonly includeFindings: boolean; readonly includeEvidence: boolean; readonly failOnWarning: boolean; }
export interface NexoraObjectDirectorRendererAdapterCollectionValidationRequest { readonly validationId: string; readonly integrationRequest: NexoraObjectDirectorRendererAdapterCollectionIntegrationRequest; readonly executeIntegration: boolean; readonly includeFindings: boolean; readonly includeEvidence: boolean; readonly failOnWarning: boolean; readonly preserveOrder: true; }
export interface RendererAdapterValidationEvidence { readonly identity: string; readonly source: string; readonly path: string; readonly value: unknown; readonly frozen: boolean; }
export interface RendererAdapterValidationSummary { readonly ruleCount: number; readonly findingCount: number; readonly passedCount: number; readonly failedCount: number; readonly infoCount: number; readonly warningCount: number; readonly errorCount: number; readonly criticalCount: number; readonly valid: boolean; readonly failOnWarning: boolean; }
export interface NexoraObjectDirectorRendererAdapterValidationResult { readonly validationId: string; readonly valid: boolean; readonly accepted: boolean; readonly integrationExecuted: boolean; readonly integrationResult: NexoraObjectDirectorRendererAdapterIntegrationResult | null; readonly findings: readonly NexoraObjectDirectorRendererAdapterValidationFinding[]; readonly evidence: readonly RendererAdapterValidationEvidence[]; readonly summary: RendererAdapterValidationSummary; readonly warnings: readonly string[]; readonly errors: readonly string[]; readonly deterministic: true; readonly deeplyFrozen: true; }
export interface NexoraObjectDirectorRendererAdapterCollectionValidationItemResult { readonly index: number; readonly sourceRuntimeId: string; readonly accepted: boolean; readonly valid: boolean; readonly findings: readonly NexoraObjectDirectorRendererAdapterValidationFinding[]; readonly warningCount: number; readonly errorCount: number; readonly criticalCount: number; readonly deeplyFrozen: true; }
export interface NexoraObjectDirectorRendererAdapterCollectionValidationResult { readonly validationId: string; readonly valid: boolean; readonly accepted: boolean; readonly integrationExecuted: boolean; readonly integrationResult: NexoraObjectDirectorRendererAdapterCollectionIntegrationResult | null; readonly itemResults: readonly NexoraObjectDirectorRendererAdapterCollectionValidationItemResult[]; readonly findings: readonly NexoraObjectDirectorRendererAdapterValidationFinding[]; readonly evidence: readonly RendererAdapterValidationEvidence[]; readonly summary: RendererAdapterValidationSummary; readonly sourceCount: number; readonly outputCount: number; readonly failedItemCount: number; readonly orderPreserved: true; readonly warnings: readonly string[]; readonly errors: readonly string[]; readonly deterministic: true; readonly deeplyFrozen: true; }
export interface NexoraObjectDirectorRendererAdapterValidationPolicy { readonly integrationOnlyDependency: true; readonly synchronous: true; readonly pure: true; readonly deterministic: true; readonly sideEffectFree: true; readonly validationDoesNotMutate: true; readonly validationDoesNotRepair: true; readonly runtimeMutationForbidden: true; readonly rendererExecutionForbidden: true; readonly collectionOrderPreserved: true; readonly findingsDeterministicallyOrdered: true; readonly evidenceOptional: true; readonly warningsCanFailValidation: true; readonly deeplyFrozenOutputs: true; }
export interface NexoraObjectDirectorRendererAdapterValidationCompatibility { readonly validationIdentity: string; readonly integrationIdentity: string; readonly compatibleIntegrationVersion: string; readonly integrationOnlyDependency: true; readonly singleValidationCompatible: boolean; readonly collectionValidationCompatible: boolean; readonly strictModeCompatible: boolean; readonly compatibleModeCompatible: boolean; readonly rendererFrameworkAgnostic: true; }
export interface RendererAdapterValidationReadinessReport { readonly ready: boolean; readonly identityReady: boolean; readonly dependencyReady: boolean; readonly integrationReady: boolean; readonly rulesReady: boolean; readonly policyReady: boolean; readonly compatibilityReady: boolean; readonly deterministicValidationReady: boolean; readonly publicSurfacesFrozen: boolean; readonly violations: readonly string[]; }
export interface NexoraObjectDirectorRendererAdapterValidationVerificationReport { readonly valid: boolean; readonly identityValid: boolean; readonly namespaceValid: boolean; readonly versionValid: boolean; readonly statusValid: boolean; readonly lockValid: boolean; readonly dependencyValid: boolean; readonly integrationCompatible: boolean; readonly ruleRegistryValid: boolean; readonly policyValid: boolean; readonly pipelineValid: boolean; readonly readinessValid: boolean; readonly deterministicValidationValid: boolean; readonly publicSurfacesFrozen: boolean; readonly prohibitedCapabilitiesAbsent: boolean; readonly violations: readonly string[]; }
export interface RendererAdapterValidationRequestValidationResult { readonly valid: boolean; readonly validationIdValid: boolean; readonly integrationRequestValid: boolean; readonly configurationValid: boolean; readonly dependencyCompatible: boolean; readonly violations: readonly string[]; }
export interface RendererAdapterValidationDeterminismReport { readonly deterministic: boolean; readonly requestEquivalent: boolean; readonly integrationEquivalent: boolean; readonly findingsEquivalent: boolean; readonly evidenceEquivalent: boolean; readonly summaryEquivalent: boolean; readonly warningEquivalent: boolean; readonly errorEquivalent: boolean; readonly violations: readonly string[]; }
export interface RendererAdapterRuntimeImmutabilityReport { readonly immutable: boolean; readonly structurallyEquivalent: boolean; readonly referenceMutationDetected: boolean; readonly violations: readonly string[]; }

export const rendererAdapterValidationSeverities = freezeRendererObject(["info", "warning", "error", "critical"] as const satisfies readonly RendererAdapterValidationSeverity[]);
export const rendererAdapterValidationSeverityCount = rendererAdapterValidationSeverities.length;
export const rendererAdapterValidationRuleCategories = freezeRendererObject(["identity", "dependency", "request", "integration", "renderer-output", "collection", "determinism", "immutability", "compatibility", "architecture"] as const satisfies readonly RendererAdapterValidationRuleCategory[]);
export const rendererAdapterValidationRuleCategoryCount = rendererAdapterValidationRuleCategories.length;

export const rendererAdapterValidationRules = freezeRendererObject([
  { id: "VAL-IDENTITY-001", order: 1, name: "Validation Identity", category: "identity", severity: "critical", required: true, description: "Requires the exact NOL-5:5 validation identity." },
  { id: "VAL-DEPENDENCY-001", order: 2, name: "Integration-Only Dependency", category: "dependency", severity: "critical", required: true, description: "Requires the sequential NOL-5:4 dependency boundary." },
  { id: "VAL-REQUEST-001", order: 3, name: "Validation Request Structure", category: "request", severity: "error", required: true, description: "Requires a complete deterministic validation request." },
  { id: "VAL-REQUEST-002", order: 4, name: "Integration Request Validity", category: "request", severity: "error", required: true, description: "Requires a valid NOL-5:4 Integration request." },
  { id: "VAL-INTEGRATION-001", order: 5, name: "Integration Execution Consistency", category: "integration", severity: "error", required: true, description: "Requires execution declarations to match Integration truth." },
  { id: "VAL-INTEGRATION-002", order: 6, name: "Integration Acceptance Consistency", category: "integration", severity: "critical", required: true, description: "Requires acceptance and exposed output to agree." },
  { id: "VAL-OUTPUT-001", order: 7, name: "Renderer Object Presence", category: "renderer-output", severity: "critical", required: true, description: "Requires accepted results to expose renderer output only." },
  { id: "VAL-OUTPUT-002", order: 8, name: "Renderer State Compliance", category: "renderer-output", severity: "error", required: true, description: "Restricts renderer state to minimum, report, or operation." },
  { id: "VAL-OUTPUT-003", order: 9, name: "Renderer Visibility Compliance", category: "renderer-output", severity: "error", required: true, description: "Restricts visibility to visible, hidden, or collapsed." },
  { id: "VAL-OUTPUT-004", order: 10, name: "Seed Color Compliance", category: "renderer-output", severity: "error", required: true, description: "Restricts colors to Seed semantic groups." },
  { id: "VAL-COLLECTION-001", order: 11, name: "Collection Count Consistency", category: "collection", severity: "error", required: true, description: "Requires collection counts to match current result data." },
  { id: "VAL-COLLECTION-002", order: 12, name: "Collection Order Preservation", category: "collection", severity: "critical", required: true, description: "Requires source and output order preservation." },
  { id: "VAL-COLLECTION-003", order: 13, name: "Item Alignment", category: "collection", severity: "error", required: true, description: "Requires sequential indexes and aligned source identifiers." },
  { id: "VAL-DETERMINISM-001", order: 14, name: "Structural Determinism", category: "determinism", severity: "error", required: true, description: "Requires equivalent inputs to produce equivalent results." },
  { id: "VAL-IMMUTABILITY-001", order: 15, name: "Deep Freeze Compliance", category: "immutability", severity: "critical", required: true, description: "Requires every public result surface to be deeply frozen." },
  { id: "VAL-IMMUTABILITY-002", order: 16, name: "Runtime Input Preservation", category: "immutability", severity: "critical", required: true, description: "Requires runtime input structural preservation." },
  { id: "VAL-COMPATIBILITY-001", order: 17, name: "Integration Compatibility", category: "compatibility", severity: "critical", required: true, description: "Requires compatible NOL-5:4 identity and version." },
  { id: "VAL-ARCHITECTURE-001", order: 18, name: "Renderer Execution Absence", category: "architecture", severity: "critical", required: true, description: "Forbids executable renderer resources." },
  { id: "VAL-ARCHITECTURE-002", order: 19, name: "Browser Capability Absence", category: "architecture", severity: "critical", required: true, description: "Forbids browser capability handles." },
  { id: "VAL-ARCHITECTURE-003", order: 20, name: "Sequential Dependency Boundary", category: "architecture", severity: "critical", required: true, description: "Requires validation through NOL-5:4 only." },
] as const satisfies readonly NexoraObjectDirectorRendererAdapterValidationRule[]);
export const rendererAdapterValidationRuleCount = rendererAdapterValidationRules.length;

export const rendererAdapterValidationPipeline = freezeRendererObject([
  { id: "validate-validation-request", order: 1, name: "Validate Validation Request", required: true },
  { id: "validate-integration-compatibility", order: 2, name: "Validate Integration Compatibility", required: true },
  { id: "execute-or-inspect-integration", order: 3, name: "Execute or Inspect Integration", required: true },
  { id: "validate-integration-result", order: 4, name: "Validate Integration Result", required: true },
  { id: "validate-renderer-output", order: 5, name: "Validate Renderer Output", required: true },
  { id: "validate-collection-consistency", order: 6, name: "Validate Collection Consistency", required: true },
  { id: "validate-determinism", order: 7, name: "Validate Determinism", required: true },
  { id: "validate-immutability", order: 8, name: "Validate Immutability", required: true },
  { id: "build-findings-evidence", order: 9, name: "Build Findings and Evidence", required: true },
  { id: "build-validation-summary", order: 10, name: "Build Validation Summary", required: true },
  { id: "freeze-validation-result", order: 11, name: "Freeze Validation Result", required: true },
] as const);
export const rendererAdapterValidationPipelineStepCount = rendererAdapterValidationPipeline.length;

export const rendererAdapterValidationPolicy: NexoraObjectDirectorRendererAdapterValidationPolicy = freezeRendererObject({ integrationOnlyDependency: true, synchronous: true, pure: true, deterministic: true, sideEffectFree: true, validationDoesNotMutate: true, validationDoesNotRepair: true, runtimeMutationForbidden: true, rendererExecutionForbidden: true, collectionOrderPreserved: true, findingsDeterministicallyOrdered: true, evidenceOptional: true, warningsCanFailValidation: true, deeplyFrozenOutputs: true } as const);
export const rendererAdapterValidationCompatibility: NexoraObjectDirectorRendererAdapterValidationCompatibility = freezeRendererObject({ validationIdentity: validationId, integrationIdentity: integrationId, compatibleIntegrationVersion: integrationVersion, integrationOnlyDependency: true, singleValidationCompatible: true, collectionValidationCompatible: true, strictModeCompatible: true, compatibleModeCompatible: true, rendererFrameworkAgnostic: true } as const);
export const rendererAdapterValidationRegistry = freezeRendererObject(["Request Validation", "Integration Validation", "Renderer Output Validation", "Collection Validation", "Strict Mode Validation", "Compatible Mode Validation", "Determinism Validation", "Immutability Validation", "Evidence Collection", "Summary Creation", "Readiness", "Compatibility", "Verification"] as const);
export const rendererAdapterValidationRegistryCount = rendererAdapterValidationRegistry.length;
export const rendererAdapterValidationPublicApiSurface = freezeRendererObject(["validateRendererAdapterValidationRequest", "validateRendererAdapterCollectionValidationRequest", "executeRendererAdapterValidation", "executeRendererAdapterCollectionValidation", "validateRendererAdapterIntegrationResult", "validateRendererAdapterCollectionIntegrationResult", "validateRendererAdapterRendererObject", "validateRendererAdapterSeedColor", "validateRendererAdapterIntegrationSummary", "validateRendererAdapterIntegrationTrace", "createRendererAdapterValidationFinding", "collectRendererAdapterValidationFindings", "collectRendererAdapterValidationEvidence", "createRendererAdapterValidationSummary", "assessRendererAdapterValidationReadiness", "verifyRendererAdapterValidationDeterminism", "verifyRendererAdapterRuntimeImmutability", "isRendererAdapterValidationSuccessful", "isRendererAdapterCollectionValidationSuccessful", "verifyRendererAdapterValidation"] as const);
export const rendererAdapterValidationPublicApiCount = rendererAdapterValidationPublicApiSurface.length;

function record(value: unknown): value is Record<string, unknown> { return value !== null && typeof value === "object" && !Array.isArray(value); }
function structurallyEquivalent(left: unknown, right: unknown): boolean { if (Object.is(left, right)) return true; if (Array.isArray(left) || Array.isArray(right)) return Array.isArray(left) && Array.isArray(right) && left.length === right.length && left.every((value, index) => structurallyEquivalent(value, right[index])); if (!record(left) || !record(right)) return false; const a = Object.keys(left).sort(), b = Object.keys(right).sort(); return a.length === b.length && a.every((key, index) => key === b[index] && structurallyEquivalent(left[key], right[key])); }

function clonePlain(value: unknown, seen = new Set<object>()): unknown {
  if (value === null || ["string", "number", "boolean", "undefined"].includes(typeof value)) return value;
  if (typeof value === "function" || typeof value === "symbol" || typeof value === "bigint") throw new TypeError("Validation data must contain deterministic plain values");
  if (seen.has(value as object)) throw new TypeError("Validation data must not be circular");
  seen.add(value as object);
  if (Array.isArray(value)) { const cloned = value.map((item) => clonePlain(item, seen)); seen.delete(value); return cloned; }
  if (!record(value) || ((value as { constructor?: { name?: string } }).constructor?.name ?? "Object") !== "Object") throw new TypeError("Validation data must contain plain objects only");
  const cloned = Object.fromEntries(Object.entries(value).map(([key, child]) => [key, clonePlain(child, seen)]));
  seen.delete(value);
  return cloned;
}

function messages(values: readonly string[]): readonly string[] { const result: string[] = [], seen = new Set<string>(); for (const value of values) { const normalized = value.trim(); if (normalized && !seen.has(normalized)) { seen.add(normalized); result.push(normalized); } } return freezeRendererObject(result); }
function rule(ruleId: string): NexoraObjectDirectorRendererAdapterValidationRule { const value = rendererAdapterValidationRules.find((entry) => entry.id === ruleId); if (!value) throw new TypeError(`Unknown validation rule: ${ruleId}`); return value; }

export function createRendererAdapterValidationFinding(input: Omit<NexoraObjectDirectorRendererAdapterValidationFinding, "category" | "severity"> & { readonly category?: RendererAdapterValidationRuleCategory; readonly severity?: RendererAdapterValidationSeverity }): NexoraObjectDirectorRendererAdapterValidationFinding {
  const registered = rule(input.ruleId);
  const category = input.category ?? registered.category, severity = input.severity ?? registered.severity;
  if (!input.ruleId.trim() || !rendererAdapterValidationRuleCategories.includes(category) || !rendererAdapterValidationSeverities.includes(severity) || !input.code.trim() || !input.message.trim()) throw new TypeError("Finding identity, category, severity, code, and message must be supported");
  return freezeRendererObject({ ...input, category, severity, expected: clonePlain(input.expected), actual: clonePlain(input.actual) });
}

export function collectRendererAdapterValidationFindings(...collections: readonly (readonly NexoraObjectDirectorRendererAdapterValidationFinding[])[]): readonly NexoraObjectDirectorRendererAdapterValidationFinding[] {
  const indexed = collections.flat().map((finding, occurrence) => ({ finding, occurrence }));
  indexed.sort((left, right) => rule(left.finding.ruleId).order - rule(right.finding.ruleId).order || left.occurrence - right.occurrence);
  const result: NexoraObjectDirectorRendererAdapterValidationFinding[] = [], seen = new Set<string>();
  for (const { finding } of indexed) { const key = JSON.stringify(finding); if (!seen.has(key)) { seen.add(key); result.push(createRendererAdapterValidationFinding(finding)); } }
  return freezeRendererObject(result);
}

export function collectRendererAdapterValidationEvidence(...collections: readonly (readonly RendererAdapterValidationEvidence[])[]): readonly RendererAdapterValidationEvidence[] {
  const result: RendererAdapterValidationEvidence[] = [], seen = new Set<string>();
  for (const evidence of collections.flat()) { if (!evidence.identity.trim() || !evidence.source.trim() || !evidence.path.trim()) throw new TypeError("Evidence identity, source, and path are required"); const value = clonePlain(evidence.value), normalized = freezeRendererObject({ ...evidence, value, frozen: true }); const key = JSON.stringify(normalized); if (!seen.has(key)) { seen.add(key); result.push(normalized); } }
  return freezeRendererObject(result);
}

export function createRendererAdapterValidationSummary(findings: readonly NexoraObjectDirectorRendererAdapterValidationFinding[], failOnWarning: boolean): RendererAdapterValidationSummary {
  const failed = findings.filter((finding) => !finding.valid), errorFailure = failed.some((finding) => finding.severity === "error" || finding.severity === "critical"), warningFailure = failOnWarning && failed.some((finding) => finding.severity === "warning");
  return freezeRendererObject({ ruleCount: rendererAdapterValidationRuleCount, findingCount: findings.length, passedCount: findings.length - failed.length, failedCount: failed.length, infoCount: findings.filter((finding) => finding.severity === "info").length, warningCount: findings.filter((finding) => finding.severity === "warning").length, errorCount: findings.filter((finding) => finding.severity === "error").length, criticalCount: findings.filter((finding) => finding.severity === "critical").length, valid: !errorFailure && !warningFailure, failOnWarning });
}

function requestValidation(value: unknown, collection: boolean): RendererAdapterValidationRequestValidationResult {
  const request: Record<string, unknown> = record(value) ? value : {}, validationIdValid = typeof request.validationId === "string" && request.validationId.trim().length > 0;
  const integrationRequestPresent = record(request.integrationRequest);
  const integrationValidation = integrationRequestPresent ? (collection ? validateRendererAdapterCollectionIntegrationRequest(request.integrationRequest as unknown as NexoraObjectDirectorRendererAdapterCollectionIntegrationRequest) : validateRendererAdapterIntegrationRequest(request.integrationRequest as unknown as NexoraObjectDirectorRendererAdapterIntegrationRequest)) : null;
  const integrationRequest: Record<string, unknown> = integrationRequestPresent ? request.integrationRequest as Record<string, unknown> : {};
  const integrationRequestValid = integrationRequestPresent && integrationValidation?.integrationIdValid === true && integrationValidation.consumerIdValid && integrationValidation.modeValid && integrationValidation.dependencyCompatible && record(integrationRequest.engineRequest) && (!collection || integrationRequest.preserveOrder === true);
  const configurationValid = [request.executeIntegration, request.includeFindings, request.includeEvidence, request.failOnWarning].every((setting) => typeof setting === "boolean") && (!collection || request.preserveOrder === true);
  const dependencyCompatible = verifyRendererAdapterIntegration().valid;
  const violations: string[] = [];
  if (!validationIdValid) violations.push("validationId is required");
  if (!integrationRequestPresent) violations.push("integrationRequest is required"); else if (!integrationRequestValid) violations.push(...integrationValidation?.violations ?? ["integrationRequest is invalid"]);
  if (!configurationValid) violations.push("Validation configuration is invalid");
  if (!dependencyCompatible) violations.push("NOL-5:4 Integration is incompatible");
  return freezeRendererObject({ valid: validationIdValid && integrationRequestValid && configurationValid && dependencyCompatible, validationIdValid, integrationRequestValid, configurationValid, dependencyCompatible, violations: messages(violations) });
}

export function validateRendererAdapterValidationRequest(request: NexoraObjectDirectorRendererAdapterValidationRequest): RendererAdapterValidationRequestValidationResult { return requestValidation(request, false); }
export function validateRendererAdapterCollectionValidationRequest(request: NexoraObjectDirectorRendererAdapterCollectionValidationRequest): RendererAdapterValidationRequestValidationResult { return requestValidation(request, true); }

function finding(ruleId: string, valid: boolean, code: string, message: string, path: string, expected: unknown, actual: unknown, severity?: RendererAdapterValidationSeverity): NexoraObjectDirectorRendererAdapterValidationFinding { return createRendererAdapterValidationFinding({ ruleId, valid, code, message, path, expected, actual, ...(severity ? { severity } : {}) }); }

export function validateRendererAdapterSeedColor(color: unknown, path = "rendererObject.color"): readonly NexoraObjectDirectorRendererAdapterValidationFinding[] {
  const palette = ["Green", "Yellow", "Red", "Blue", "White", "Black"], semantic = typeof color === "string" ? ["green", "yellow", "red", "blue", "neutral"].includes(color) : record(color) && ["base", "accent", "background", "text"].every((key) => palette.includes(String(color[key])));
  return freezeRendererObject([finding("VAL-OUTPUT-004", semantic, semantic ? "SEED_COLOR_VALID" : "SEED_COLOR_INVALID", semantic ? "Renderer color uses the Seed palette." : "Renderer color contains an unsupported Seed semantic.", path, "green|yellow|red|blue|neutral", color)]);
}

function executableAbsent(value: unknown, seen = new Set<object>()): boolean { if (typeof value === "function" || typeof value === "symbol") return false; if (value === null || typeof value !== "object" || seen.has(value as object)) return true; seen.add(value as object); const name = (value as { constructor?: { name?: string } }).constructor?.name; if (name && !["Object", "Array"].includes(name)) return false; return Object.entries(value as Record<string, unknown>).every(([key, child]) => !/^(renderer|scene|mesh|geometry|material|shader|camera|browser|element|handler|callback)$/i.test(key) && executableAbsent(child, seen)); }

export function validateRendererAdapterRendererObject(rendererObject: unknown, path = "rendererObject"): readonly NexoraObjectDirectorRendererAdapterValidationFinding[] {
  const object = record(rendererObject) ? rendererObject : {}, present = record(rendererObject) && typeof object.id === "string" && object.id.length > 0 && typeof object.type === "string" && object.type.length > 0;
  const metadata = record(object.metadata) ? object.metadata : {}, state = metadata.rendererState, visibility = object.visibility;
  const stateValid = ["minimum", "report", "operation"].includes(String(state)), visibilityValid = ["visible", "hidden", "collapsed"].includes(String(visibility));
  const badgesFrozen = Array.isArray(object.badges) && verifyRendererValueFrozen(object.badges), metadataFrozen = record(object.metadata) && verifyRendererValueFrozen(object.metadata), executableFree = executableAbsent(rendererObject);
  return collectRendererAdapterValidationFindings(
    [finding("VAL-OUTPUT-001", present, present ? "OUTPUT_PRESENT" : "OUTPUT_MISSING", present ? "Renderer object identity is present." : "Renderer object identity is missing.", path, "renderer object with id and type", { id: object.id, type: object.type })],
    [finding("VAL-OUTPUT-002", stateValid, stateValid ? "STATE_VALID" : "STATE_INVALID", stateValid ? "Renderer state is supported." : "Renderer state is unsupported.", `${path}.metadata.rendererState`, ["minimum", "report", "operation"], state)],
    [finding("VAL-OUTPUT-003", visibilityValid, visibilityValid ? "VISIBILITY_VALID" : "VISIBILITY_INVALID", visibilityValid ? "Renderer visibility is supported." : "Renderer visibility is unsupported.", `${path}.visibility`, ["visible", "hidden", "collapsed"], visibility)],
    validateRendererAdapterSeedColor(object.color, `${path}.color`),
    [finding("VAL-IMMUTABILITY-001", badgesFrozen && metadataFrozen && verifyRendererValueFrozen(rendererObject), badgesFrozen && metadataFrozen ? "OUTPUT_FROZEN" : "OUTPUT_MUTABLE", badgesFrozen && metadataFrozen ? "Renderer output is deeply frozen." : "Renderer badges or metadata are mutable.", path, true, badgesFrozen && metadataFrozen && verifyRendererValueFrozen(rendererObject))],
    [finding("VAL-ARCHITECTURE-001", executableFree, executableFree ? "EXECUTION_ABSENT" : "EXECUTION_PRESENT", executableFree ? "Renderer execution handles are absent." : "Renderer execution handle detected.", path, true, executableFree)],
  );
}

export function validateRendererAdapterIntegrationSummary(summary: RendererAdapterIntegrationSummary | null, result: NexoraObjectDirectorRendererAdapterIntegrationResult | NexoraObjectDirectorRendererAdapterCollectionIntegrationResult): readonly NexoraObjectDirectorRendererAdapterValidationFinding[] {
  if (summary === null) return freezeRendererObject([finding("VAL-INTEGRATION-001", true, "SUMMARY_OMITTED", "Optional Integration summary was omitted.", "summary", null, null, "info")]);
  const collection = "itemResults" in result, sourceCount = collection ? result.sourceCount : 1, outputCount = collection ? result.outputCount : result.rendererObject ? 1 : 0, acceptedCount = collection ? result.itemResults.filter((item) => item.accepted).length : result.accepted ? 1 : 0, rejectedCount = sourceCount - acceptedCount;
  const expectedStatus = outputCount === 0 ? "rejected" : rejectedCount > 0 ? "partially-accepted" : "accepted";
  const consistent = summary.sourceCount === sourceCount && summary.acceptedCount === acceptedCount && summary.rejectedCount === rejectedCount && summary.outputCount === outputCount && summary.warningCount === result.warnings.length && summary.errorCount === result.errors.length && summary.compatible === result.compatible && summary.status === expectedStatus;
  return freezeRendererObject([finding("VAL-INTEGRATION-001", consistent, consistent ? "SUMMARY_VALID" : "SUMMARY_MISMATCH", consistent ? "Integration summary matches execution truth." : "Integration summary does not match execution truth.", "summary", { sourceCount, acceptedCount, rejectedCount, outputCount, warningCount: result.warnings.length, errorCount: result.errors.length, status: expectedStatus }, summary)]);
}

export function validateRendererAdapterIntegrationTrace(trace: RendererAdapterIntegrationTrace | null): readonly NexoraObjectDirectorRendererAdapterValidationFinding[] {
  if (trace === null) return freezeRendererObject([finding("VAL-INTEGRATION-001", true, "TRACE_OMITTED", "Optional Integration trace was omitted.", "trace", null, null, "info")]);
  const exactPrefix = trace.stages.every((stage, index) => rendererAdapterIntegrationStages[index] === stage), unique = new Set(trace.stages).size === trace.stages.length, known = trace.stages.every((stage) => rendererAdapterIntegrationStages.includes(stage)), completed = trace.completed === (trace.stages.length === rendererAdapterIntegrationStages.length && exactPrefix && unique && known), plain = executableAbsent(trace) && !Object.keys(trace).some((key) => /timestamp|duration|environment/i.test(key));
  const valid = exactPrefix && unique && known && completed && plain;
  return freezeRendererObject([finding("VAL-INTEGRATION-001", valid, valid ? "TRACE_VALID" : "TRACE_INVALID", valid ? "Integration trace is ordered and deterministic." : "Integration trace is unknown, duplicate, unordered, or incomplete.", "trace", rendererAdapterIntegrationStages, trace.stages)]);
}

export function validateRendererAdapterIntegrationResult(result: NexoraObjectDirectorRendererAdapterIntegrationResult): readonly NexoraObjectDirectorRendererAdapterValidationFinding[] {
  const acceptance = result.accepted === (result.rendererObject !== null), compatible = result.compatible && result.deterministic && result.deeplyFrozen;
  const fallbackRequiresWarning = result.mode === "compatible" && result.rendererObject?.color.base === "White";
  const fallbackReported = !fallbackRequiresWarning || result.warnings.length > 0;
  return collectRendererAdapterValidationFindings(
    [finding("VAL-INTEGRATION-002", acceptance, acceptance ? "ACCEPTANCE_VALID" : "ACCEPTANCE_INVALID", acceptance ? "Integration acceptance matches renderer output." : "Integration acceptance contradicts renderer output.", "accepted", result.rendererObject !== null, result.accepted)],
    result.rendererObject ? validateRendererAdapterRendererObject(result.rendererObject) : [finding("VAL-OUTPUT-001", !result.accepted, !result.accepted ? "REJECTED_OUTPUT_ABSENT" : "ACCEPTED_OUTPUT_MISSING", !result.accepted ? "Rejected Integration exposes no renderer object." : "Accepted Integration is missing renderer output.", "rendererObject", result.accepted ? "renderer object" : null, null)],
    validateRendererAdapterIntegrationSummary(result.summary, result), validateRendererAdapterIntegrationTrace(result.trace),
    [finding("VAL-INTEGRATION-001", fallbackReported, fallbackReported ? "FALLBACK_REPORTING_VALID" : "FALLBACK_WARNING_MISSING", fallbackReported ? "Compatible fallback reporting is consistent." : "Compatible fallback acceptance requires a warning.", "warnings", fallbackRequiresWarning ? "non-empty warning collection" : "optional", result.warnings, "warning")],
    [finding("VAL-COMPATIBILITY-001", compatible, compatible ? "INTEGRATION_COMPATIBLE" : "INTEGRATION_INCOMPATIBLE", compatible ? "Integration result is compatible." : "Integration result compatibility declaration is invalid.", "compatible", true, compatible)],
    [finding("VAL-IMMUTABILITY-001", verifyRendererValueFrozen(result), verifyRendererValueFrozen(result) ? "RESULT_FROZEN" : "RESULT_MUTABLE", verifyRendererValueFrozen(result) ? "Integration result is deeply frozen." : "Integration result is mutable.", "integrationResult", true, verifyRendererValueFrozen(result))],
  );
}

export function validateRendererAdapterCollectionIntegrationResult(result: NexoraObjectDirectorRendererAdapterCollectionIntegrationResult, request?: NexoraObjectDirectorRendererAdapterCollectionIntegrationRequest): readonly NexoraObjectDirectorRendererAdapterValidationFinding[] {
  const acceptedItems = result.itemResults.filter((item) => item.accepted), expectedRendererCount = result.accepted ? acceptedItems.length : 0, countValid = result.sourceCount === result.itemResults.length && result.outputCount === result.engineResult.outputCount && result.failedCount === result.itemResults.filter((item) => !item.accepted).length && result.rendererObjects.length === expectedRendererCount;
  const indexesValid = result.itemResults.every((item, index) => item.index === index), sourceIdsValid = !request || result.itemResults.every((item, index) => item.sourceRuntimeId === request.engineRequest.inputs[index]?.sourceRuntimeId), orderValid = result.orderPreserved && indexesValid && sourceIdsValid && result.rendererObjects.every((object, index) => object === acceptedItems[index]?.rendererObject);
  const nested = result.rendererObjects.flatMap((object, index) => validateRendererAdapterRendererObject(object, `rendererObjects[${index}]`));
  return collectRendererAdapterValidationFindings(
    [finding("VAL-COLLECTION-001", countValid, countValid ? "COUNTS_VALID" : "COUNTS_INVALID", countValid ? "Collection counts are consistent." : "Collection counts are inconsistent.", "collection", { sourceCount: result.itemResults.length, outputCount: result.rendererObjects.length, failedCount: result.itemResults.filter((item) => !item.accepted).length }, { sourceCount: result.sourceCount, outputCount: result.outputCount, failedCount: result.failedCount })],
    [finding("VAL-COLLECTION-002", orderValid, orderValid ? "ORDER_VALID" : "ORDER_INVALID", orderValid ? "Collection order is preserved." : "Collection order is not preserved.", "orderPreserved", true, orderValid)],
    result.itemResults.map((item, index) => finding("VAL-COLLECTION-003", item.index === index && (!request || item.sourceRuntimeId === request.engineRequest.inputs[index]?.sourceRuntimeId), item.index === index ? "ITEM_ALIGNED" : "ITEM_MISALIGNED", item.index === index ? "Collection item is source-aligned." : "Collection item index is misaligned.", `itemResults[${index}]`, { index, sourceRuntimeId: request?.engineRequest.inputs[index]?.sourceRuntimeId ?? item.sourceRuntimeId }, { index: item.index, sourceRuntimeId: item.sourceRuntimeId })),
    nested, validateRendererAdapterIntegrationSummary(result.summary, result), validateRendererAdapterIntegrationTrace(result.trace),
    [finding("VAL-COMPATIBILITY-001", result.compatible, result.compatible ? "INTEGRATION_COMPATIBLE" : "INTEGRATION_INCOMPATIBLE", result.compatible ? "Collection Integration is compatible." : "Collection Integration is incompatible.", "compatible", true, result.compatible)],
    [finding("VAL-IMMUTABILITY-001", verifyRendererValueFrozen(result), verifyRendererValueFrozen(result) ? "RESULT_FROZEN" : "RESULT_MUTABLE", verifyRendererValueFrozen(result) ? "Collection Integration result is deeply frozen." : "Collection Integration result is mutable.", "integrationResult", true, verifyRendererValueFrozen(result))],
  );
}

function requestFindings(validation: RendererAdapterValidationRequestValidationResult): readonly NexoraObjectDirectorRendererAdapterValidationFinding[] { return collectRendererAdapterValidationFindings(
  [finding("VAL-IDENTITY-001", validation.validationIdValid, validation.validationIdValid ? "VALIDATION_ID_VALID" : "VALIDATION_ID_INVALID", validation.validationIdValid ? "Validation identity is present." : "Validation identity is missing.", "validationId", "non-empty string", validation.validationIdValid)],
  [finding("VAL-DEPENDENCY-001", validation.dependencyCompatible, validation.dependencyCompatible ? "DEPENDENCY_VALID" : "DEPENDENCY_INVALID", validation.dependencyCompatible ? "Integration dependency is compatible." : "Integration dependency is incompatible.", "dependency", integrationId, rendererAdapterValidationCompatibility.integrationIdentity)],
  [finding("VAL-REQUEST-001", validation.configurationValid, validation.configurationValid ? "REQUEST_STRUCTURE_VALID" : "REQUEST_STRUCTURE_INVALID", validation.configurationValid ? "Validation request structure is valid." : "Validation request structure is invalid.", "request", true, validation.configurationValid)],
  [finding("VAL-REQUEST-002", validation.integrationRequestValid, validation.integrationRequestValid ? "INTEGRATION_REQUEST_VALID" : "INTEGRATION_REQUEST_INVALID", validation.integrationRequestValid ? "Integration request is valid." : "Integration request is invalid.", "integrationRequest", true, validation.integrationRequestValid)],
); }

function evidenceFor(result: NexoraObjectDirectorRendererAdapterIntegrationResult | NexoraObjectDirectorRendererAdapterCollectionIntegrationResult): readonly RendererAdapterValidationEvidence[] { return collectRendererAdapterValidationEvidence([
  { identity: "integration-identity", source: validationId, path: "integrationId", value: result.integrationId, frozen: true },
  { identity: "integration-acceptance", source: validationId, path: "accepted", value: result.accepted, frozen: true },
  { identity: "integration-mode", source: validationId, path: "mode", value: result.mode, frozen: true },
  { identity: "integration-freeze", source: validationId, path: "deeplyFrozen", value: verifyRendererValueFrozen(result), frozen: true },
]); }

export function executeRendererAdapterValidation(request: NexoraObjectDirectorRendererAdapterValidationRequest): NexoraObjectDirectorRendererAdapterValidationResult {
  const validation = validateRendererAdapterValidationRequest(request), initial = requestFindings(validation);
  if (!validation.valid) { const summary = createRendererAdapterValidationSummary(initial, record(request) && request.failOnWarning === true); return freezeRendererObject({ validationId: record(request) && typeof request.validationId === "string" ? request.validationId : "", valid: false, accepted: false, integrationExecuted: false, integrationResult: null, findings: record(request) && request.includeFindings === true ? initial : freezeRendererObject([]), evidence: freezeRendererObject([]), summary, warnings: freezeRendererObject([]), errors: messages([...validation.violations, ...initial.filter((item) => !item.valid).map((item) => item.message)]), deterministic: true, deeplyFrozen: true }); }
  if (!request.executeIntegration) { const skipped = finding("VAL-INTEGRATION-001", true, "INTEGRATION_SKIPPED", "Integration execution was intentionally disabled.", "executeIntegration", false, false, "info"), internal = collectRendererAdapterValidationFindings(initial, [skipped]), summary = createRendererAdapterValidationSummary(internal, request.failOnWarning); return freezeRendererObject({ validationId: request.validationId, valid: summary.valid, accepted: false, integrationExecuted: false, integrationResult: null, findings: request.includeFindings ? internal : freezeRendererObject([]), evidence: freezeRendererObject([]), summary, warnings: freezeRendererObject([]), errors: freezeRendererObject([]), deterministic: true, deeplyFrozen: true }); }
  const integrationResult = integrateRendererAdapterObject(request.integrationRequest), resultFindings = validateRendererAdapterIntegrationResult(integrationResult), execution = finding("VAL-INTEGRATION-001", true, "INTEGRATION_EXECUTED", "Integration executed through NOL-5:4.", "integrationExecuted", true, true), internal = collectRendererAdapterValidationFindings(initial, [execution], resultFindings), summary = createRendererAdapterValidationSummary(internal, request.failOnWarning);
  return freezeRendererObject({ validationId: request.validationId, valid: summary.valid, accepted: integrationResult.accepted, integrationExecuted: true, integrationResult, findings: request.includeFindings ? internal : freezeRendererObject([]), evidence: request.includeEvidence ? evidenceFor(integrationResult) : freezeRendererObject([]), summary, warnings: messages(integrationResult.warnings), errors: messages([...integrationResult.errors, ...internal.filter((item) => !item.valid && ["error", "critical"].includes(item.severity)).map((item) => item.message)]), deterministic: true, deeplyFrozen: true });
}

export function executeRendererAdapterCollectionValidation(request: NexoraObjectDirectorRendererAdapterCollectionValidationRequest): NexoraObjectDirectorRendererAdapterCollectionValidationResult {
  const validation = validateRendererAdapterCollectionValidationRequest(request), initial = requestFindings(validation);
  if (!validation.valid) { const summary = createRendererAdapterValidationSummary(initial, record(request) && request.failOnWarning === true); return freezeRendererObject({ validationId: record(request) && typeof request.validationId === "string" ? request.validationId : "", valid: false, accepted: false, integrationExecuted: false, integrationResult: null, itemResults: freezeRendererObject([]), findings: record(request) && request.includeFindings === true ? initial : freezeRendererObject([]), evidence: freezeRendererObject([]), summary, sourceCount: 0, outputCount: 0, failedItemCount: 0, orderPreserved: true, warnings: freezeRendererObject([]), errors: messages([...validation.violations, ...initial.filter((item) => !item.valid).map((item) => item.message)]), deterministic: true, deeplyFrozen: true }); }
  if (!request.executeIntegration) { const skipped = finding("VAL-INTEGRATION-001", true, "INTEGRATION_SKIPPED", "Collection Integration execution was intentionally disabled.", "executeIntegration", false, false, "info"), internal = collectRendererAdapterValidationFindings(initial, [skipped]), summary = createRendererAdapterValidationSummary(internal, request.failOnWarning); return freezeRendererObject({ validationId: request.validationId, valid: summary.valid, accepted: false, integrationExecuted: false, integrationResult: null, itemResults: freezeRendererObject([]), findings: request.includeFindings ? internal : freezeRendererObject([]), evidence: freezeRendererObject([]), summary, sourceCount: request.integrationRequest.engineRequest.inputs.length, outputCount: 0, failedItemCount: 0, orderPreserved: true, warnings: freezeRendererObject([]), errors: freezeRendererObject([]), deterministic: true, deeplyFrozen: true }); }
  const integrationResult = integrateRendererAdapterCollection(request.integrationRequest), resultFindings = validateRendererAdapterCollectionIntegrationResult(integrationResult, request.integrationRequest), internal = collectRendererAdapterValidationFindings(initial, resultFindings), summary = createRendererAdapterValidationSummary(internal, request.failOnWarning);
  const itemResults = freezeRendererObject(integrationResult.itemResults.map((item, index): NexoraObjectDirectorRendererAdapterCollectionValidationItemResult => { const findings = resultFindings.filter((entry) => entry.path.startsWith(`itemResults[${index}]`) || entry.path.startsWith(`rendererObjects[${index}]`)); const failures = findings.filter((entry) => !entry.valid); return freezeRendererObject({ index, sourceRuntimeId: item.sourceRuntimeId, accepted: item.accepted, valid: !failures.some((entry) => entry.severity === "error" || entry.severity === "critical"), findings, warningCount: findings.filter((entry) => entry.severity === "warning").length, errorCount: findings.filter((entry) => entry.severity === "error").length, criticalCount: findings.filter((entry) => entry.severity === "critical").length, deeplyFrozen: true }); }));
  return freezeRendererObject({ validationId: request.validationId, valid: summary.valid, accepted: integrationResult.accepted, integrationExecuted: true, integrationResult, itemResults, findings: request.includeFindings ? internal : freezeRendererObject([]), evidence: request.includeEvidence ? evidenceFor(integrationResult) : freezeRendererObject([]), summary, sourceCount: integrationResult.sourceCount, outputCount: integrationResult.outputCount, failedItemCount: itemResults.filter((item) => !item.accepted).length, orderPreserved: true, warnings: messages(integrationResult.warnings), errors: messages([...integrationResult.errors, ...internal.filter((item) => !item.valid && ["error", "critical"].includes(item.severity)).map((item) => item.message)]), deterministic: true, deeplyFrozen: true });
}

export function verifyRendererAdapterRuntimeImmutability(before: unknown, after: unknown): RendererAdapterRuntimeImmutabilityReport { const equivalent = structurallyEquivalent(before, after), referenceMutationDetected = before === after && !verifyRendererValueFrozen(after), violations: string[] = []; if (!equivalent) violations.push("Runtime values are not structurally equivalent"); if (referenceMutationDetected) violations.push("Mutable shared runtime reference detected"); return freezeRendererObject({ immutable: equivalent && !referenceMutationDetected, structurallyEquivalent: equivalent, referenceMutationDetected, violations }); }
export function isRendererAdapterValidationSuccessful(result: NexoraObjectDirectorRendererAdapterValidationResult): boolean { return result.valid && (result.integrationExecuted ? result.accepted : true); }
export function isRendererAdapterCollectionValidationSuccessful(result: NexoraObjectDirectorRendererAdapterCollectionValidationResult): boolean { return result.valid && result.orderPreserved && !result.findings.some((findingValue) => !findingValue.valid && findingValue.severity === "critical") && result.sourceCount === (result.integrationResult?.sourceCount ?? result.sourceCount); }

type ValidationRequest = NexoraObjectDirectorRendererAdapterValidationRequest | NexoraObjectDirectorRendererAdapterCollectionValidationRequest;
type ValidationResult = NexoraObjectDirectorRendererAdapterValidationResult | NexoraObjectDirectorRendererAdapterCollectionValidationResult;
function executeValidation(request: ValidationRequest): ValidationResult { return "preserveOrder" in request ? executeRendererAdapterCollectionValidation(request) : executeRendererAdapterValidation(request); }
export function verifyRendererAdapterValidationDeterminism(request: ValidationRequest, equivalentRequest: ValidationRequest = request): RendererAdapterValidationDeterminismReport { const first = executeValidation(request), second = executeValidation(equivalentRequest), requestEquivalent = structurallyEquivalent(request, equivalentRequest), integrationEquivalent = structurallyEquivalent(first.integrationResult, second.integrationResult), findingsEquivalent = structurallyEquivalent(first.findings, second.findings), evidenceEquivalent = structurallyEquivalent(first.evidence, second.evidence), summaryEquivalent = structurallyEquivalent(first.summary, second.summary), warningEquivalent = structurallyEquivalent(first.warnings, second.warnings), errorEquivalent = structurallyEquivalent(first.errors, second.errors), violations: string[] = []; if (!requestEquivalent) violations.push("Validation requests are not equivalent"); if (!integrationEquivalent) violations.push("Integration results are not equivalent"); if (!findingsEquivalent) violations.push("Findings are not equivalent"); if (!evidenceEquivalent) violations.push("Evidence is not equivalent"); if (!summaryEquivalent) violations.push("Summaries are not equivalent"); if (!warningEquivalent) violations.push("Warnings are not equivalent"); if (!errorEquivalent) violations.push("Errors are not equivalent"); return freezeRendererObject({ deterministic: violations.length === 0, requestEquivalent, integrationEquivalent, findingsEquivalent, evidenceEquivalent, summaryEquivalent, warningEquivalent, errorEquivalent, violations }); }

export function assessRendererAdapterValidationReadiness(): RendererAdapterValidationReadinessReport { const identityReady = validationId === "NOL-5:5/NexoraObjectDirectorRendererAdapterValidation" && validationVersion === "5.5.0" && validationNamespace === "nexora.nol.renderer.adapter.validation" && validationStatus === "Validation" && validationLock === "NOL-5-5-DIRECTOR-RENDERER-ADAPTER-VALIDATION-LOCKED", dependencyReady = rendererAdapterValidationPolicy.integrationOnlyDependency, integrationReady = assessRendererAdapterIntegrationReadiness().ready, rulesReady = rendererAdapterValidationRules.length === rendererAdapterValidationRuleCount && rendererAdapterValidationRules.every((entry, index) => entry.order === index + 1 && entry.required), policyReady = Object.values(rendererAdapterValidationPolicy).every((value) => value === true), compatibilityReady = rendererAdapterValidationCompatibility.integrationIdentity === integrationId && rendererAdapterValidationCompatibility.compatibleIntegrationVersion === integrationVersion, deterministicValidationReady = rendererAdapterValidationPipeline.every((entry, index) => entry.order === index + 1), publicSurfacesFrozen = [rendererAdapterValidationSeverities, rendererAdapterValidationRuleCategories, rendererAdapterValidationRules, rendererAdapterValidationPipeline, rendererAdapterValidationPolicy, rendererAdapterValidationCompatibility, rendererAdapterValidationRegistry, rendererAdapterValidationPublicApiSurface].every(verifyRendererValueFrozen), violations: string[] = []; if (!identityReady) violations.push("Validation identity is not ready"); if (!dependencyReady) violations.push("Validation dependency is not ready"); if (!integrationReady) violations.push("Integration is not ready"); if (!rulesReady) violations.push("Validation rules are not ready"); if (!policyReady) violations.push("Validation policy is not ready"); if (!compatibilityReady) violations.push("Validation compatibility is not ready"); if (!deterministicValidationReady) violations.push("Deterministic validation is not ready"); if (!publicSurfacesFrozen) violations.push("A Validation public surface is mutable"); return freezeRendererObject({ ready: violations.length === 0, identityReady, dependencyReady, integrationReady, rulesReady, policyReady, compatibilityReady, deterministicValidationReady, publicSurfacesFrozen, violations }); }

export function verifyRendererAdapterValidation(): NexoraObjectDirectorRendererAdapterValidationVerificationReport {
  const identityValid = validationId === "NOL-5:5/NexoraObjectDirectorRendererAdapterValidation", namespaceValid = validationNamespace === "nexora.nol.renderer.adapter.validation", versionValid = validationVersion === "5.5.0", statusValid = validationStatus === "Validation", lockValid = validationLock === "NOL-5-5-DIRECTOR-RENDERER-ADAPTER-VALIDATION-LOCKED", dependencyValid = rendererAdapterValidationPolicy.integrationOnlyDependency, integrationCompatible = verifyRendererAdapterIntegration().valid && rendererAdapterValidationCompatibility.integrationIdentity === integrationId, ruleRegistryValid = rendererAdapterValidationRules.length === rendererAdapterValidationRuleCount && rendererAdapterValidationRules.every((entry, index) => entry.order === index + 1), policyValid = Object.values(rendererAdapterValidationPolicy).every((value) => value === true), pipelineValid = rendererAdapterValidationPipeline.length === rendererAdapterValidationPipelineStepCount && rendererAdapterValidationPipeline.every((entry, index) => entry.order === index + 1) && rendererAdapterValidationRegistry.length === rendererAdapterValidationRegistryCount && rendererAdapterValidationPublicApiSurface.length === rendererAdapterValidationPublicApiCount, readinessValid = assessRendererAdapterValidationReadiness().ready, deterministicValidationValid = collectRendererAdapterValidationFindings([finding("VAL-IDENTITY-001", true, "PROBE", "Deterministic validation probe.", "probe", true, true)]).length === 1, publicSurfacesFrozen = [rendererAdapterValidationSeverities, rendererAdapterValidationRuleCategories, rendererAdapterValidationRules, rendererAdapterValidationPipeline, rendererAdapterValidationPolicy, rendererAdapterValidationCompatibility, rendererAdapterValidationRegistry, rendererAdapterValidationPublicApiSurface].every(verifyRendererValueFrozen), prohibitedCapabilitiesAbsent = rendererAdapterValidationPolicy.rendererExecutionForbidden && rendererAdapterValidationPolicy.sideEffectFree, violations: string[] = [];
  if (!identityValid) violations.push("Validation identity is invalid"); if (!namespaceValid) violations.push("Validation namespace is invalid"); if (!versionValid) violations.push("Validation version is invalid"); if (!statusValid) violations.push("Validation status is invalid"); if (!lockValid) violations.push("Validation lock is invalid"); if (!dependencyValid) violations.push("Validation dependency is invalid"); if (!integrationCompatible) violations.push("Integration compatibility is invalid"); if (!ruleRegistryValid) violations.push("Validation rule registry is invalid"); if (!policyValid) violations.push("Validation policy is invalid"); if (!pipelineValid) violations.push("Validation pipeline or registry is invalid"); if (!readinessValid) violations.push("Validation readiness is invalid"); if (!deterministicValidationValid) violations.push("Validation determinism is invalid"); if (!publicSurfacesFrozen) violations.push("A Validation public surface is mutable"); if (!prohibitedCapabilitiesAbsent) violations.push("A prohibited capability is present");
  return freezeRendererObject({ valid: violations.length === 0, identityValid, namespaceValid, versionValid, statusValid, lockValid, dependencyValid, integrationCompatible, ruleRegistryValid, policyValid, pipelineValid, readinessValid, deterministicValidationValid, publicSurfacesFrozen, prohibitedCapabilitiesAbsent, violations });
}
