import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { describe, it } from "node:test";
import { type NexoraDirectorRuntimeObjectState } from "./nexoraObjectDirectorRendererAdapterFoundation.ts";
import {
  assessRendererAdapterPlatformHealth,
  assessRendererAdapterPlatformReadiness,
  createRendererAdapterCollectionPlatformValidationRequest,
  createRendererAdapterPlatformConfiguration,
  createRendererAdapterPlatformMetadata,
  createRendererAdapterPlatformValidationRequest,
  executeRendererAdapterCollectionPlatform,
  executeRendererAdapterPlatform,
  inspectRendererAdapterPlatform,
  isRendererAdapterPlatformBlockedResult,
  isRendererAdapterPlatformDegradedResult,
  isRendererAdapterPlatformReadyResult,
  platformId,
  platformLock,
  platformNamespace,
  platformStatus,
  platformVersion,
  rendererAdapterPlatformCapabilities,
  rendererAdapterPlatformCapabilityCount,
  rendererAdapterPlatformCompatibility,
  rendererAdapterPlatformDefaultConfiguration,
  rendererAdapterPlatformGuarantees,
  rendererAdapterPlatformModeCount,
  rendererAdapterPlatformModes,
  rendererAdapterPlatformOperationCount,
  rendererAdapterPlatformOperations,
  rendererAdapterPlatformPipeline,
  rendererAdapterPlatformPipelineStepCount,
  rendererAdapterPlatformPublicApiCount,
  rendererAdapterPlatformPublicApiSurface,
  rendererAdapterPlatformRegistry,
  rendererAdapterPlatformRegistryCount,
  rendererAdapterPlatformStatusCount,
  rendererAdapterPlatformStatuses,
  resolveRendererAdapterPlatformStatus,
  validateRendererAdapterPlatformRequest,
  verifyRendererAdapterPlatform,
  verifyRendererAdapterPlatformDeterminism,
  type NexoraObjectDirectorRendererAdapterCollectionPlatformRequest,
  type NexoraObjectDirectorRendererAdapterPlatformConfiguration,
  type NexoraObjectDirectorRendererAdapterPlatformInspectionRequest,
  type NexoraObjectDirectorRendererAdapterPlatformRequest,
  type RendererAdapterPlatformMode,
} from "./nexoraObjectDirectorRendererAdapterPlatform.ts";

function freeze<T>(value: T, seen = new Set<object>()): T { if (value === null || typeof value !== "object" || seen.has(value as object)) return value; seen.add(value as object); Object.values(value as Record<string, unknown>).forEach((child) => freeze(child, seen)); return Object.freeze(value); }
function deeplyFrozen(value: unknown, seen = new Set<object>()): boolean { if (value === null || typeof value !== "object" || seen.has(value as object)) return true; if (!Object.isFrozen(value)) return false; seen.add(value as object); return Object.values(value as Record<string, unknown>).every((child) => deeplyFrozen(child, seen)); }
function runtime(id = "one", overrides: Readonly<Record<string, unknown>> = {}): NexoraDirectorRuntimeObjectState { return freeze({ runtimeObjectId: `runtime-${id}`, objectId: id, sceneObjectId: `scene-${id}`, sourceCommandIds: [], generation: 1, lifecycle: "Active", visible: true, interactive: true, focused: false, operating: false, attentionLevel: "None", renderingLevel: "Normal", cameraIntent: "None", relationshipMode: "Direct", labelMode: "Full", indicatorMode: "Essential", animationPending: false, lastExecutionState: "Completed", updatedAt: "2035-01-01T00:00:00.000Z", ...overrides } as NexoraDirectorRuntimeObjectState); }
function configuration(mode: RendererAdapterPlatformMode = "strict", options: Partial<NexoraObjectDirectorRendererAdapterPlatformConfiguration> = {}): NexoraObjectDirectorRendererAdapterPlatformConfiguration { return createRendererAdapterPlatformConfiguration({ mode, ...options }); }
function single(runtimeObject = runtime(), mode: RendererAdapterPlatformMode = "strict", options: Partial<NexoraObjectDirectorRendererAdapterPlatformRequest> = {}): NexoraObjectDirectorRendererAdapterPlatformRequest { return freeze({ platformRequestId: "platform-request", consumerId: "consumer-1", operation: "single", runtimeObject, sourceRuntimeId: runtimeObject.runtimeObjectId, configuration: configuration(mode), ...options }); }
function collection(runtimeObjects: readonly NexoraDirectorRuntimeObjectState[], mode: RendererAdapterPlatformMode = "strict", sourceRuntimeIds = runtimeObjects.map((item) => item.runtimeObjectId)): NexoraObjectDirectorRendererAdapterCollectionPlatformRequest { return freeze({ platformRequestId: "platform-collection", consumerId: "consumer-1", operation: "collection", runtimeObjects, sourceRuntimeIds, configuration: configuration(mode), preserveOrder: true }); }
function inspection(options: Partial<NexoraObjectDirectorRendererAdapterPlatformInspectionRequest> = {}): NexoraObjectDirectorRendererAdapterPlatformInspectionRequest { return freeze({ platformRequestId: "platform-inspection", consumerId: "consumer-1", operation: "inspect", includeCapabilities: true, includeHealth: true, includeReadiness: true, ...options }); }
const source = readFileSync(new URL("./nexoraObjectDirectorRendererAdapterPlatform.ts", import.meta.url), "utf8");

describe("NOL-5:6 Director Renderer Adapter Platform", () => {
  it("1-11. exposes exact identity and a Validation-only production dependency", () => { assert.equal(platformId, "NOL-5:6/NexoraObjectDirectorRendererAdapterPlatform"); assert.equal(platformVersion, "5.6.0"); assert.equal(platformNamespace, "nexora.nol.renderer.adapter.platform"); assert.equal(platformStatus, "Platform"); assert.equal(platformLock, "NOL-5-6-DIRECTOR-RENDERER-ADAPTER-PLATFORM-LOCKED"); const imports = [...source.matchAll(/from\s+["']([^"']+)["']/g)].map((match) => match[1]); assert.deepEqual(imports, ["./nexoraObjectDirectorRendererAdapterValidation.ts"]); assert.doesNotMatch(imports.join(" "), /Integration|Engine|Contracts|Foundation|nexoraObjectDirectorRuntime/i); });

  it("12-37 and 118-119. exposes exact dynamically counted and deeply frozen surfaces", () => { assert.deepEqual(rendererAdapterPlatformModes, ["strict", "compatible"]); assert.equal(rendererAdapterPlatformModeCount, rendererAdapterPlatformModes.length); assert.deepEqual(rendererAdapterPlatformOperations, ["single", "collection", "inspect"]); assert.equal(rendererAdapterPlatformOperationCount, rendererAdapterPlatformOperations.length); assert.deepEqual(rendererAdapterPlatformStatuses, ["ready", "degraded", "blocked"]); assert.equal(rendererAdapterPlatformStatusCount, rendererAdapterPlatformStatuses.length); assert.deepEqual(rendererAdapterPlatformDefaultConfiguration, { mode: "strict", validationEnabled: true, failOnWarning: false, includeFindings: true, includeEvidence: false, includeSummary: true, includeTrace: false, preserveCollectionOrder: true }); assert.deepEqual(rendererAdapterPlatformCapabilities.map((entry) => entry.order), Array.from({ length: 18 }, (_, index) => index + 1)); assert.equal(rendererAdapterPlatformCapabilityCount, rendererAdapterPlatformCapabilities.length); assert.deepEqual(rendererAdapterPlatformPipeline.map((entry) => entry.order), Array.from({ length: 10 }, (_, index) => index + 1)); assert.equal(rendererAdapterPlatformPipelineStepCount, rendererAdapterPlatformPipeline.length); assert.equal(rendererAdapterPlatformRegistryCount, rendererAdapterPlatformRegistry.length); assert.equal(rendererAdapterPlatformPublicApiCount, rendererAdapterPlatformPublicApiSurface.length); for (const value of [rendererAdapterPlatformModes, rendererAdapterPlatformOperations, rendererAdapterPlatformStatuses, rendererAdapterPlatformDefaultConfiguration, rendererAdapterPlatformCapabilities, rendererAdapterPlatformPipeline, rendererAdapterPlatformGuarantees, rendererAdapterPlatformCompatibility, rendererAdapterPlatformRegistry, rendererAdapterPlatformPublicApiSurface]) assert.equal(deeplyFrozen(value), true); });

  it("18-22. creates custom immutable configuration and forbids validation or order bypass", () => { const custom = configuration("compatible", { includeEvidence: true, includeTrace: true, failOnWarning: true }); assert.equal(custom.mode, "compatible"); assert.equal(custom.includeEvidence, true); assert.equal(deeplyFrozen(custom), true); assert.throws(() => createRendererAdapterPlatformConfiguration({ validationEnabled: false as true }), /mandatory validation/); assert.throws(() => createRendererAdapterPlatformConfiguration({ preserveCollectionOrder: false as true }), /mandatory validation/); });

  it("38-48. validates single, collection, and inspection structures deterministically", () => { assert.equal(validateRendererAdapterPlatformRequest(single()).valid, true); assert.equal(validateRendererAdapterPlatformRequest(single(runtime(), "strict", { platformRequestId: "" })).platformRequestIdValid, false); assert.equal(validateRendererAdapterPlatformRequest(single(runtime(), "strict", { consumerId: "" })).consumerIdValid, false); assert.equal(validateRendererAdapterPlatformRequest(single(runtime(), "strict", { runtimeObject: null })).payloadValid, false); assert.equal(validateRendererAdapterPlatformRequest(single(runtime(), "strict", { sourceRuntimeId: "" })).payloadValid, false); const invalidConfig = freeze({ ...rendererAdapterPlatformDefaultConfiguration, validationEnabled: false }) as unknown as NexoraObjectDirectorRendererAdapterPlatformConfiguration; assert.equal(validateRendererAdapterPlatformRequest(single(runtime(), "strict", { configuration: invalidConfig })).configurationValid, false); assert.equal(validateRendererAdapterPlatformRequest(collection([runtime("a"), runtime("b")])).valid, true); assert.equal(validateRendererAdapterPlatformRequest({ ...collection([runtime("a")]), sourceRuntimeIds: [] }).payloadValid, false); assert.equal(validateRendererAdapterPlatformRequest({ ...collection([runtime("a")]), sourceRuntimeIds: [""] }).payloadValid, false); assert.equal(validateRendererAdapterPlatformRequest({ ...collection([runtime("a")]), preserveOrder: false as true }).payloadValid, false); assert.equal(validateRendererAdapterPlatformRequest(inspection()).valid, true); });

  it("49-54. translates single and collection requests without mutation or order loss", () => { const runtimeObject = runtime("translate"), request = single(runtimeObject), before = JSON.stringify(runtimeObject), strict = createRendererAdapterPlatformValidationRequest(request), compatible = createRendererAdapterPlatformValidationRequest(single(runtimeObject, "compatible")); assert.equal(strict.integrationRequest.engineRequest.strict, true); assert.equal(strict.integrationRequest.mode, "strict"); assert.equal(compatible.integrationRequest.engineRequest.strict, false); assert.equal(compatible.integrationRequest.mode, "compatible"); assert.equal(strict.integrationRequest.engineRequest.input.runtimeObject, runtimeObject); const collectionRequest = collection([runtime("a"), runtime("b")]), translated = createRendererAdapterCollectionPlatformValidationRequest(collectionRequest); assert.deepEqual(translated.integrationRequest.engineRequest.inputs.map((item) => item.sourceRuntimeId), ["runtime-a", "runtime-b"]); assert.equal(translated.preserveOrder, true); assert.equal(JSON.stringify(runtimeObject), before); assert.equal(deeplyFrozen(translated), true); });

  it("55-69. processes clean, fallback, rejected, and invalid single requests through mandatory Validation", () => { const strict = executeRendererAdapterPlatform(single()), compatible = executeRendererAdapterPlatform(single(runtime("compatible"), "compatible")), fallback = executeRendererAdapterPlatform(single(runtime("fallback", { lifecycle: "Unmapped" }), "compatible")), strictRejected = executeRendererAdapterPlatform(single(runtime("strict-fallback", { lifecycle: "Unmapped" }), "strict")), invalid = executeRendererAdapterPlatform(single(runtime(), "strict", { platformRequestId: "" })); assert.equal(strict.accepted && strict.valid, true); assert.equal(strict.metadata.status, "ready"); assert.equal(compatible.accepted && compatible.valid, true); assert.equal(fallback.accepted, true); assert.ok(fallback.warnings.length > 0); assert.equal(fallback.metadata.status, "degraded"); assert.equal(strictRejected.accepted, false); assert.equal(strictRejected.rendererObject, null); assert.equal(strictRejected.metadata.status, "blocked"); assert.equal(invalid.accepted, false); assert.equal(invalid.valid, false); assert.equal(invalid.rendererObject, null); assert.equal(invalid.validationResult, null); assert.equal(invalid.metadata.status, "blocked"); assert.equal(strict.findings, strict.validationResult?.findings); assert.equal(strict.evidence, strict.validationResult?.evidence); assert.equal(strict.summary, strict.validationResult?.summary); assert.equal(deeplyFrozen(strict), true); });

  it("70-84. preserves strict collection rejection, compatible partial truth, alignment, and duplicates", () => { const a = runtime("a"), b = runtime("b"), strict = executeRendererAdapterCollectionPlatform(collection([a, b])), compatible = executeRendererAdapterCollectionPlatform(collection([a, b], "compatible")); assert.equal(strict.accepted && strict.valid, true); assert.equal(compatible.accepted && compatible.valid, true); assert.deepEqual(strict.rendererObjects.map((item) => item.id), ["runtime-a", "runtime-b"]); assert.deepEqual(strict.itemResults.map((item) => [item.index, item.sourceRuntimeId]), [[0, "runtime-a"], [1, "runtime-b"]]); assert.equal(strict.sourceCount, 2); assert.equal(strict.outputCount, 2); assert.equal(strict.failedItemCount, 0); assert.equal(strict.orderPreserved, true); assert.equal(strict.partial, false); const invalidRuntime = freeze({ ...runtime("invalid"), runtimeObjectId: "" }) as NexoraDirectorRuntimeObjectState, rejected = executeRendererAdapterCollectionPlatform(collection([a, invalidRuntime], "strict", ["runtime-a", "runtime-invalid"])), partial = executeRendererAdapterCollectionPlatform(collection([invalidRuntime, b], "compatible", ["runtime-invalid", "runtime-b"])); assert.equal(rejected.accepted, false); assert.deepEqual(rejected.rendererObjects, []); assert.equal(rejected.metadata.status, "blocked"); assert.equal(partial.accepted, true); assert.equal(partial.partial, true); assert.equal(partial.metadata.status, "degraded"); assert.equal(partial.itemResults[0].accepted, false); assert.equal(partial.itemResults[1].accepted, true); assert.deepEqual(partial.rendererObjects.map((item) => item.id), ["runtime-b"]); const duplicate = executeRendererAdapterCollectionPlatform(collection([a, b], "compatible", ["duplicate", "duplicate"])); assert.ok(duplicate.warnings.some((warning) => /Duplicate source runtime ID retained/.test(warning))); assert.deepEqual(duplicate.itemResults.map((item) => item.sourceRuntimeId), ["duplicate", "duplicate"]); assert.equal(deeplyFrozen(duplicate), true); assert.equal(deeplyFrozen(duplicate.itemResults), true); });

  it("85-89. inspects capabilities, health, and readiness without adaptation", () => { const complete = inspectRendererAdapterPlatform(inspection()), omitted = inspectRendererAdapterPlatform(inspection({ includeCapabilities: false, includeHealth: false, includeReadiness: false })); assert.equal(complete.ready, true); assert.equal(complete.metadata.operation, "inspect"); assert.equal(complete.metadata.mode, null); assert.equal(complete.capabilities.length, 18); assert.equal(complete.health?.healthy, true); assert.equal(complete.readiness?.ready, true); assert.deepEqual(omitted.capabilities, []); assert.equal(omitted.health, null); assert.equal(omitted.readiness, null); assert.equal("rendererObject" in complete, false); assert.equal(deeplyFrozen(complete), true); });

  it("90-94. creates deterministic metadata and resolves ready, degraded, and blocked", () => { const first = createRendererAdapterPlatformMetadata("request", "consumer", "single", "strict", "ready", true), second = createRendererAdapterPlatformMetadata("request", "consumer", "single", "strict", "ready", true); assert.deepEqual(first, second); assert.equal(Object.keys(first).some((key) => /time|duration|host/i.test(key)), false); const ready = executeRendererAdapterPlatform(single()), degraded = executeRendererAdapterPlatform(single(runtime("fallback", { lifecycle: "Unmapped" }), "compatible")), blocked = executeRendererAdapterPlatform(single(runtime(), "strict", { platformRequestId: "" })); assert.equal(resolveRendererAdapterPlatformStatus(true, "single", ready.validationResult, "strict"), "ready"); assert.equal(degraded.metadata.status, "degraded"); assert.equal(blocked.metadata.status, "blocked"); });

  it("95-97 and 120. reports healthy, Validation-compatible readiness for Certification", () => { const health = assessRendererAdapterPlatformHealth(), readiness = assessRendererAdapterPlatformReadiness(); assert.equal(health.healthy, true); assert.equal(health.status, "ready"); assert.equal(readiness.ready, true); assert.equal(readiness.validationReady, true); assert.deepEqual(rendererAdapterPlatformCompatibility, { platformIdentity: platformId, validationIdentity: "NOL-5:5/NexoraObjectDirectorRendererAdapterValidation", compatibleValidationVersion: "5.5.0", validationOnlyDependency: true, strictModeCompatible: true, compatibleModeCompatible: true, singleProcessingCompatible: true, collectionProcessingCompatible: true, inspectionCompatible: true, rendererFrameworkAgnostic: true }); assert.equal(deeplyFrozen(health) && deeplyFrozen(readiness), true); });

  it("98-101. verifies structural determinism for single, collection, inspection, and clones", () => { const singleRequest = single(), collectionRequest = collection([runtime("a"), runtime("b")], "compatible"), inspectionRequest = inspection(); assert.equal(verifyRendererAdapterPlatformDeterminism(singleRequest).deterministic, true); assert.equal(verifyRendererAdapterPlatformDeterminism(collectionRequest).deterministic, true); assert.equal(verifyRendererAdapterPlatformDeterminism(inspectionRequest).deterministic, true); const clone = freeze({ ...singleRequest, configuration: freeze({ ...singleRequest.configuration }) }); assert.equal(verifyRendererAdapterPlatformDeterminism(singleRequest, clone).deterministic, true); });

  it("102-104. exposes exact ready, degraded, and blocked predicates", () => { const ready = executeRendererAdapterPlatform(single()), degraded = executeRendererAdapterPlatform(single(runtime("fallback", { lifecycle: "Unmapped" }), "compatible")), blocked = executeRendererAdapterPlatform(single(runtime(), "strict", { platformRequestId: "" })); assert.equal(isRendererAdapterPlatformReadyResult(ready), true); assert.equal(isRendererAdapterPlatformDegradedResult(degraded), true); assert.equal(isRendererAdapterPlatformBlockedResult(blocked), true); });

  it("105-112. freezes results and preserves runtime and Validation truth without repair", () => { const runtimeObject = runtime("immutable"), before = JSON.stringify(runtimeObject), result = executeRendererAdapterPlatform(single(runtimeObject, "strict", { configuration: configuration("strict", { includeEvidence: true }) })), validationBefore = JSON.stringify(result.validationResult); assert.equal(JSON.stringify(runtimeObject), before); assert.equal(JSON.stringify(result.validationResult), validationBefore); assert.equal(deeplyFrozen(result), true); assert.equal(deeplyFrozen(result.findings), true); assert.equal(deeplyFrozen(result.evidence), true); assert.equal(rendererAdapterPlatformGuarantees.validationRepairForbidden, true); });

  it("113-117. verifies the Platform and excludes all prohibited capabilities", () => { const report = verifyRendererAdapterPlatform(); assert.equal(report.valid, true); assert.equal(report.readinessValid, true); assert.equal(report.publicSurfacesFrozen, true); assert.equal(deeplyFrozen(report), true); assert.doesNotMatch(source, /from\s+["'][^"']*(?:Integration|Engine|Contracts|Foundation|nexoraObjectDirectorRuntime|react|next|three|webgl|canvas|svg|dom)/i); assert.doesNotMatch(source, /\b(?:async|await|Promise|setTimeout|setInterval|fetch|localStorage|sessionStorage|window|document|globalThis|Math\.random|Date\b|Worker|process|filesystem)\b|new\s+(?:Mesh|Scene|Camera|Renderer)|console\./); });
});
