import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { describe, it } from "node:test";
import * as frozenSurface from "./nexoraObjectDirectorRendererAdapterFreeze.ts";
import * as publicSurface from "./nexoraObjectDirectorRendererAdapterPublicIndex.ts";

function deeplyFrozen(value: unknown, seen = new Set<object>()): boolean { if (value === null || (typeof value !== "object" && typeof value !== "function") || seen.has(value as object)) return true; if (typeof value === "function") return true; if (!Object.isFrozen(value)) return false; seen.add(value as object); return Object.values(value as Record<string, unknown>).every((child) => deeplyFrozen(child, seen)); }
const source = readFileSync(new URL("./nexoraObjectDirectorRendererAdapterPublicIndex.ts", import.meta.url), "utf8");
const namespaceOrder = ["Identity", "Public Types", "Public APIs", "Validation", "Certification", "Release Information", "Compatibility", "Registry", "Consumer Information"];
const consumerRuleOrder = ["Use Public Index Import Path", "Public Index Is Sole Consumer Entry", "Direct Freeze Import Is Forbidden", "Direct Certification Import Is Forbidden", "Direct Platform Import Is Forbidden", "Direct Validation Import Is Forbidden", "Direct Integration Import Is Forbidden", "Direct Engine Import Is Forbidden", "Direct Contracts Import Is Forbidden", "Direct Foundation Import Is Forbidden", "Direct NOL-4 Import Is Forbidden", "Public API Wrappers Are Forbidden", "Export Identity Must Be Preserved", "Public Types Must Come From Public Index", "Consumer Mutation Is Forbidden", "Renderer Execution Remains External", "Framework-Specific Adaptation Remains External", "Public Manifest Defines Supported Surface"];

describe("NOL-5:9 Director Renderer Adapter Public Index", () => {
  it("1-16. publishes exact identity through a Freeze-only production dependency", () => { assert.equal(publicSurface.publicIndexId, "NOL-5:9/NexoraObjectDirectorRendererAdapterPublicIndex"); assert.equal(publicSurface.publicIndexVersion, "5.9.0"); assert.equal(publicSurface.publicIndexNamespace, "nexora.nol.renderer.adapter.public-index"); assert.equal(publicSurface.publicIndexStatus, "PublicIndex"); assert.equal(publicSurface.publicIndexReleaseStatus, "Released"); assert.equal(publicSurface.publicIndexReadiness, "ReadyForConsumer"); assert.equal(publicSurface.publicIndexLock, "NOL-5-9-DIRECTOR-RENDERER-ADAPTER-PUBLIC-INDEX-LOCKED"); const dependencies = [...source.matchAll(/from\s+["']([^"']+)["']/g)].map((match) => match[1]); assert.ok(dependencies.length > 0); assert.equal(dependencies.every((dependency) => dependency === "./nexoraObjectDirectorRendererAdapterFreeze.ts"), true); assert.doesNotMatch(source, /from\s+["'][^"']*(?:Certification|Platform|Validation|Integration|Engine|Contracts|Foundation|DirectorRuntime)/); });

  it("17-30. publishes exactly nine ordered, sequential, immutable namespaces", () => { assert.deepEqual(publicSurface.rendererAdapterPublicNamespaceNames, namespaceOrder); assert.equal(publicSurface.rendererAdapterPublicNamespaceCount, publicSurface.rendererAdapterPublicNamespaceNames.length); assert.equal(publicSurface.rendererAdapterPublicNamespaces.length, 9); assert.deepEqual(publicSurface.rendererAdapterPublicNamespaces.map((entry) => entry.name), namespaceOrder); assert.deepEqual(publicSurface.rendererAdapterPublicNamespaces.map((entry) => entry.order), Array.from({ length: 9 }, (_, index) => index + 1)); for (const entry of publicSurface.rendererAdapterPublicNamespaces) { assert.equal(entry.exportCount, entry.exportNames.length); assert.equal(entry.frozen, true); } assert.equal(deeplyFrozen(publicSurface.rendererAdapterPublicNamespaces), true); for (const required of namespaceOrder) assert.ok(publicSurface.rendererAdapterPublicNamespaces.some((entry) => entry.name === required)); });

  it("31-38. builds exact upstream-derived identity and stable release truth without generated metadata", () => { const identity = publicSurface.buildRendererAdapterPublicIdentity(), release = publicSurface.buildRendererAdapterPublicReleaseInformation(); assert.deepEqual(identity, { publicIndexIdentity: publicSurface.publicIndexId, freezeIdentity: frozenSurface.freezeId, certificationIdentity: frozenSurface.rendererAdapterFrozenIdentity.certificationIdentity, platformIdentity: frozenSurface.rendererAdapterFrozenIdentity.platformIdentity, moduleIdentity: frozenSurface.rendererAdapterFrozenIdentity.moduleIdentity, namespace: publicSurface.publicIndexNamespace, version: publicSurface.publicIndexVersion, status: "PublicIndex", releaseStatus: "Released", readiness: "ReadyForConsumer", lock: publicSurface.publicIndexLock }); assert.equal(release.stability, "stable"); assert.equal(release.certified && release.frozen && release.readyForConsumer, true); assert.equal(release.frozenReleaseVersion, frozenSurface.freezeVersion); assert.equal(deeplyFrozen(identity) && deeplyFrozen(release), true); assert.doesNotMatch(JSON.stringify(release), /timestamp|date|build|commit|host|environment/i); });

  it("39-49. derives a unique deterministic export registry aligned to the frozen manifest", () => { const registry = publicSurface.buildRendererAdapterPublicExportRegistry(), verification = publicSurface.verifyRendererAdapterPublicExportRegistry(registry); assert.equal(registry.exportCount, registry.exports.length); assert.equal(registry.exportCount, frozenSurface.rendererAdapterFreezePublicApiEntries.length); assert.deepEqual(registry.exports.map((entry) => entry.exportName), frozenSurface.rendererAdapterFreezePublicApiEntries.map((entry) => entry.exportName)); assert.deepEqual(registry.exports.map((entry) => entry.order), Array.from({ length: registry.exports.length }, (_, index) => index + 1)); assert.equal(new Set(registry.exports.map((entry) => entry.exportName)).size, registry.exports.length); assert.equal(registry.exports.every((entry) => entry.certified && entry.frozen && entry.stable && entry.consumerSafe && entry.source === "NOL-5:8 Freeze"), true); assert.equal(verification.valid, true); assert.equal(verification.freezeManifestAligned, true); assert.equal(publicSurface.rendererAdapterPublicExportCount, publicSurface.rendererAdapterPublicExportDescriptors.length); assert.equal(deeplyFrozen(registry), true); });

  it("50-67. publishes exact ordered consumer rules and the sole supported entry", () => { assert.deepEqual(publicSurface.rendererAdapterPublicConsumerRules.map((entry) => entry.name), consumerRuleOrder); assert.deepEqual(publicSurface.rendererAdapterPublicConsumerRules.map((entry) => entry.order), Array.from({ length: 18 }, (_, index) => index + 1)); assert.equal(publicSurface.rendererAdapterPublicConsumerRules.every((entry) => entry.required), true); assert.equal(publicSurface.rendererAdapterPublicConsumerRuleCount, publicSurface.rendererAdapterPublicConsumerRules.length); const information = publicSurface.buildRendererAdapterPublicConsumerInformation(); assert.equal(information.supportedImportPath, "@/app/lib/nol/renderer/nexoraObjectDirectorRendererAdapterPublicIndex"); assert.equal(information.soleConsumerEntryPoint, true); assert.equal(information.directFreezeImportsForbidden, true); assert.equal(information.directCertificationImportsForbidden, true); assert.equal(information.directPlatformImportsForbidden, true); assert.equal(information.directValidationImportsForbidden, true); assert.equal(information.directIntegrationImportsForbidden, true); assert.equal(information.directEngineImportsForbidden, true); assert.equal(information.directContractsImportsForbidden, true); assert.equal(information.directFoundationImportsForbidden, true); assert.equal(information.directNol4ImportsForbidden, true); assert.equal(information.wrappersForbidden, true); assert.equal(information.exportIdentityPreservationRequired, true); assert.equal(information.consumerRuleCount, information.consumerRules.length); assert.equal(deeplyFrozen(information), true); });

  it("68-76. publishes compatible stable registry and API metadata with dynamic counts", () => { const compatibility = publicSurface.rendererAdapterPublicCompatibility; assert.equal(compatibility.freezeIdentity, frozenSurface.freezeId); assert.equal(compatibility.compatibleFreezeVersion, frozenSurface.freezeVersion); assert.equal(compatibility.consumerApiVersion, publicSurface.publicIndexVersion); assert.equal(compatibility.freezeOnlyDependency && compatibility.frozenManifestAligned && compatibility.rendererFrameworkAgnostic, true); assert.equal(compatibility.stableConsumerEntry && compatibility.readyForConsumer, true); assert.deepEqual(publicSurface.rendererAdapterPublicIndexRegistry, ["Identity", "Public Types", "Public APIs", "Validation", "Certification", "Release Information", "Compatibility", "Registry", "Consumer Information", "Readiness", "Consumer Entry Verification", "Public Index Verification"]); assert.equal(publicSurface.rendererAdapterPublicIndexRegistryCount, publicSurface.rendererAdapterPublicIndexRegistry.length); assert.equal(publicSurface.rendererAdapterPublicIndexPublicApiCount, publicSurface.rendererAdapterPublicIndexPublicApiSurface.length); assert.equal(publicSurface.rendererAdapterPublicIndexPublicApiCount, 10); assert.equal(deeplyFrozen(compatibility) && deeplyFrozen(publicSurface.rendererAdapterPublicIndexPublicApiSurface), true); });

  it("77-91. exposes the canonical nine-property deeply frozen public object", () => { const index = publicSurface.nexoraObjectDirectorRendererAdapterPublicIndex; assert.deepEqual(Object.keys(index), ["identity", "publicTypes", "publicApis", "validation", "certification", "releaseInformation", "compatibility", "registry", "consumerInformation"]); assert.equal(Object.keys(index).length, 9); assert.equal(index.identity, publicSurface.rendererAdapterPublicIdentity); assert.equal(index.certification, frozenSurface.rendererAdapterFrozenCertificationAttestation); assert.equal(index.releaseInformation.frozenRelease, frozenSurface.rendererAdapterFrozenReleaseInformation); assert.equal(index.releaseInformation.capabilities, frozenSurface.rendererAdapterFreezeCapabilities); assert.equal(index.releaseInformation.consumerGuarantees, frozenSurface.rendererAdapterFreezeConsumerGuarantees); assert.equal(index.compatibility.frozenCompatibility, frozenSurface.rendererAdapterFreezeCompatibility); assert.equal(index.compatibility.dependencyContract, frozenSurface.rendererAdapterFreezeDependencyContract); assert.equal(index.registry.frozenPublicApiManifest, frozenSurface.rendererAdapterFrozenPublicApiManifest); assert.equal(index.registry.freezeRegistry, frozenSurface.rendererAdapterFreezeRegistry); assert.equal(index.registry.freezePublicApiSurface, frozenSurface.rendererAdapterFreezePublicApiSurface); assert.equal(deeplyFrozen(index), true); });

  it("82-91. directly re-exports every runtime manifest entry with preserved identity", () => { const runtimeEntries = frozenSurface.rendererAdapterFreezePublicApiEntries.filter((entry) => entry.kind !== "type"); for (const entry of runtimeEntries) assert.equal((publicSurface as Record<string, unknown>)[entry.exportName], (frozenSurface as Record<string, unknown>)[entry.exportName], entry.exportName); assert.equal(publicSurface.executeRendererAdapterFreeze, frozenSurface.executeRendererAdapterFreeze); assert.equal(publicSurface.verifyRendererAdapterFreeze, frozenSurface.verifyRendererAdapterFreeze); assert.equal(publicSurface.rendererAdapterFreezeCapabilities, frozenSurface.rendererAdapterFreezeCapabilities); assert.equal(publicSurface.rendererAdapterFrozenPublicApiManifest, frozenSurface.rendererAdapterFrozenPublicApiManifest); assert.doesNotMatch(source, /export\s+function\s+(?:executeRendererAdapterFreeze|assessRendererAdapterFreezeReadiness|isRendererAdapterFrozen|isRendererAdapterPublicIndexReady|isRendererAdapterFreezeBlocked|verifyRendererAdapterFreeze)/); });

  it("92-101. verifies the consumer entry and every boundary invariant", () => { const report = publicSurface.verifyNexoraDirectorRendererAdapterConsumerEntry(); assert.equal(report.valid, true); assert.equal(report.supportedPathValid, true); assert.equal(report.soleEntryValid, true); assert.equal(report.freezeOnlyDependencyValid, true); assert.equal(report.namespaceOrderValid, true); assert.equal(report.exportRegistryValid, true); assert.equal(report.exportIdentityValid, true); assert.equal(report.releaseValid, true); assert.equal(report.consumerRulesValid, true); assert.equal(report.prohibitedDirectImportsAbsent, true); assert.equal(deeplyFrozen(report), true); });

  it("102-113. reports complete public readiness", () => { const report = publicSurface.assessRendererAdapterPublicIndexReadiness(); assert.equal(report.ready, true); for (const value of [report.identityReady, report.freezeReady, report.releaseReady, report.namespacesReady, report.exportsReady, report.validationReady, report.certificationReady, report.compatibilityReady, report.registryReady, report.consumerRulesReady, report.publicSurfacesFrozen, report.soleEntryReady]) assert.equal(value, true); assert.deepEqual(report.violations, []); assert.equal(deeplyFrozen(report), true); });

  it("114-123. rebuilds every public surface deterministically", () => { assert.deepEqual(publicSurface.buildRendererAdapterPublicIdentity(), publicSurface.buildRendererAdapterPublicIdentity()); assert.deepEqual(publicSurface.buildRendererAdapterPublicReleaseInformation(), publicSurface.buildRendererAdapterPublicReleaseInformation()); assert.deepEqual(publicSurface.buildRendererAdapterPublicNamespaces(), publicSurface.buildRendererAdapterPublicNamespaces()); assert.deepEqual(publicSurface.buildRendererAdapterPublicExportRegistry(), publicSurface.buildRendererAdapterPublicExportRegistry()); assert.deepEqual(publicSurface.buildRendererAdapterPublicConsumerInformation(), publicSurface.buildRendererAdapterPublicConsumerInformation()); const report = publicSurface.verifyRendererAdapterPublicIndexDeterminism(); assert.equal(report.deterministic, true); for (const value of [report.identityEquivalent, report.releaseEquivalent, report.namespacesEquivalent, report.exportRegistryEquivalent, report.compatibilityEquivalent, report.consumerInformationEquivalent, report.readinessEquivalent, report.consumerEntryEquivalent]) assert.equal(value, true); assert.equal(deeplyFrozen(report), true); });

  it("124-127 and 139-140. verifies the complete released Public Index", () => { const report = publicSurface.verifyRendererAdapterPublicIndex(); assert.equal(report.valid, true); for (const [key, value] of Object.entries(report)) if (key !== "violations") assert.equal(value, true, key); assert.deepEqual(report.violations, []); assert.equal(deeplyFrozen(report), true); assert.equal(publicSurface.publicIndexReadiness, "ReadyForConsumer"); });

  it("128-138. excludes execution frameworks, browser state, nondeterminism, and mutation", () => { assert.doesNotMatch(source, /from\s+["'][^"']*(?:react|next|three|webgl|canvas|svg)/i); assert.doesNotMatch(source, /\b(?:async|await|Promise|setTimeout|setInterval|fetch|localStorage|sessionStorage|window|document|globalThis|Math\.random|Date\b|Worker|process|console\.)\b/); assert.doesNotMatch(source, /new\s+(?:Mesh|Scene|Camera|Renderer)|createElement|addEventListener|emit\s*\(/); assert.equal(frozenSurface.rendererAdapterFreezePolicy.rendererExecutionForbidden, true); assert.equal(frozenSurface.rendererAdapterFreezePolicy.runtimeExecutionForbidden, true); assert.equal(frozenSurface.rendererAdapterFreezePolicy.freezeDoesNotMutate, true); assert.equal(frozenSurface.rendererAdapterFreezePolicy.sideEffectFree, true); for (const value of [publicSurface.rendererAdapterPublicNamespaceNames, publicSurface.rendererAdapterPublicNamespaces, publicSurface.rendererAdapterPublicExportDescriptors, publicSurface.rendererAdapterPublicExportRegistry, publicSurface.rendererAdapterPublicConsumerRules, publicSurface.rendererAdapterPublicConsumerInformation, publicSurface.rendererAdapterPublicCompatibility, publicSurface.rendererAdapterPublicIndexRegistry, publicSurface.rendererAdapterPublicIndexPublicApiSurface, publicSurface.nexoraObjectDirectorRendererAdapterPublicIndex]) assert.equal(deeplyFrozen(value), true); });
});
