import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { describe, it } from "node:test";
import {
  assessRendererAdapterFreezeReadiness,
  buildRendererAdapterFreezeCapabilities,
  buildRendererAdapterFreezeConsumerGuarantees,
  buildRendererAdapterFrozenCertificationAttestation,
  buildRendererAdapterFrozenIdentity,
  buildRendererAdapterFrozenPublicApiManifest,
  buildRendererAdapterFrozenReleaseInformation,
  collectRendererAdapterFreezeEvidence,
  collectRendererAdapterFreezeFindings,
  createRendererAdapterFreezeFinding,
  executeRendererAdapterFreeze,
  freezeId,
  freezeLock,
  freezeNamespace,
  freezeReadiness,
  freezeStatus,
  freezeVersion,
  isRendererAdapterFreezeBlocked,
  isRendererAdapterFrozen,
  isRendererAdapterPublicIndexReady,
  rendererAdapterFreezeCapabilities,
  rendererAdapterFreezeCapabilityCount,
  rendererAdapterFreezeCompatibility,
  rendererAdapterFreezeConsumerGuaranteeCount,
  rendererAdapterFreezeConsumerGuarantees,
  rendererAdapterFreezeDependencyContract,
  rendererAdapterFreezePipeline,
  rendererAdapterFreezePipelineStepCount,
  rendererAdapterFreezePolicy,
  rendererAdapterFreezePublicApiCount,
  rendererAdapterFreezePublicApiEntries,
  rendererAdapterFreezePublicApiEntryCount,
  rendererAdapterFreezePublicApiSurface,
  rendererAdapterFreezeRegistry,
  rendererAdapterFreezeRegistryCount,
  rendererAdapterFreezeRequirementCount,
  rendererAdapterFreezeRequirements,
  rendererAdapterFreezeStatusCount,
  rendererAdapterFreezeStatuses,
  rendererAdapterReleaseStabilities,
  rendererAdapterReleaseStabilityCount,
  validateRendererAdapterFreezeRequest,
  verifyRendererAdapterFreeze,
  verifyRendererAdapterFreezeConsumerGuarantees,
  verifyRendererAdapterFreezeDeterminism,
  verifyRendererAdapterFrozenPublicApiManifest,
  type NexoraObjectDirectorRendererAdapterFreezeRequest,
} from "./nexoraObjectDirectorRendererAdapterFreeze.ts";
import { executeRendererAdapterCertification, rendererAdapterCertificationLevels, type NexoraObjectDirectorRendererAdapterCertificationRequest } from "./nexoraObjectDirectorRendererAdapterCertification.ts";

function freeze<T>(value: T, seen = new Set<object>()): T { if (value === null || typeof value !== "object" || seen.has(value as object)) return value; seen.add(value as object); Object.values(value as Record<string, unknown>).forEach((child) => freeze(child, seen)); return Object.freeze(value); }
function deeplyFrozen(value: unknown, seen = new Set<object>()): boolean { if (value === null || typeof value !== "object" || seen.has(value as object)) return true; if (!Object.isFrozen(value)) return false; seen.add(value as object); return Object.values(value as Record<string, unknown>).every((child) => deeplyFrozen(child, seen)); }
function certificationRequest(options: Partial<NexoraObjectDirectorRendererAdapterCertificationRequest> = {}): NexoraObjectDirectorRendererAdapterCertificationRequest { return freeze({ certificationId: "freeze-certification", requestedLevels: rendererAdapterCertificationLevels, includeFindings: true, includeEvidence: true, executeBehaviorChecks: true, failOnWarning: false, ...options }); }
function request(options: Partial<NexoraObjectDirectorRendererAdapterFreezeRequest> = {}): NexoraObjectDirectorRendererAdapterFreezeRequest { return freeze({ freezeId: "freeze-request", certificationRequest: certificationRequest(), executeCertification: true, includeFindings: true, includeEvidence: true, verifyPublicApiManifest: true, verifyConsumerGuarantees: true, ...options }); }
const source = readFileSync(new URL("./nexoraObjectDirectorRendererAdapterFreeze.ts", import.meta.url), "utf8");

describe("NOL-5:8 Director Renderer Adapter Freeze", () => {
  it("1-14. exposes exact identity and a Certification-only production dependency", () => { assert.equal(freezeId, "NOL-5:8/NexoraObjectDirectorRendererAdapterFreeze"); assert.equal(freezeVersion, "5.8.0"); assert.equal(freezeNamespace, "nexora.nol.renderer.adapter.freeze"); assert.equal(freezeStatus, "Freeze"); assert.equal(freezeReadiness, "ReadyForPublicIndex"); assert.equal(freezeLock, "NOL-5-8-DIRECTOR-RENDERER-ADAPTER-FREEZE-LOCKED"); const imports = [...source.matchAll(/from\s+["']([^"']+)["']/g)].map((match) => match[1]); assert.deepEqual(imports, ["./nexoraObjectDirectorRendererAdapterCertification.ts"]); assert.doesNotMatch(imports.join(" "), /Platform|Validation|Integration|Engine|Contracts|Foundation|nexoraObjectDirectorRuntime/i); });

  it("15-44 and 139-145. exposes exact dynamic and deeply frozen release registries", () => { assert.deepEqual(rendererAdapterFreezeStatuses, ["frozen", "blocked"]); assert.equal(rendererAdapterFreezeStatusCount, rendererAdapterFreezeStatuses.length); assert.deepEqual(rendererAdapterReleaseStabilities, ["stable", "unstable"]); assert.equal(rendererAdapterReleaseStabilityCount, rendererAdapterReleaseStabilities.length); assert.deepEqual(rendererAdapterFreezeRequirements.map((entry) => entry.order), Array.from({ length: 28 }, (_, index) => index + 1)); assert.equal(rendererAdapterFreezeRequirements.every((entry) => entry.mandatory && entry.releaseBlocking), true); assert.equal(rendererAdapterFreezeRequirementCount, rendererAdapterFreezeRequirements.length); assert.deepEqual(rendererAdapterFreezeCapabilities.map((entry) => entry.order), Array.from({ length: 18 }, (_, index) => index + 1)); assert.equal(rendererAdapterFreezeCapabilityCount, rendererAdapterFreezeCapabilities.length); assert.deepEqual(rendererAdapterFreezeConsumerGuarantees.map((entry) => entry.order), Array.from({ length: 20 }, (_, index) => index + 1)); assert.equal(rendererAdapterFreezeConsumerGuaranteeCount, rendererAdapterFreezeConsumerGuarantees.length); assert.deepEqual(rendererAdapterFreezePipeline.map((entry) => entry.order), Array.from({ length: 18 }, (_, index) => index + 1)); assert.equal(rendererAdapterFreezePipelineStepCount, rendererAdapterFreezePipeline.length); assert.equal(rendererAdapterFreezeRegistryCount, rendererAdapterFreezeRegistry.length); assert.equal(rendererAdapterFreezePublicApiCount, rendererAdapterFreezePublicApiSurface.length); assert.equal(rendererAdapterFreezePublicApiEntryCount, rendererAdapterFreezePublicApiEntries.length); for (const value of [rendererAdapterFreezeRequirements, rendererAdapterFreezeCapabilities, rendererAdapterFreezeConsumerGuarantees, rendererAdapterFreezePublicApiEntries, rendererAdapterFreezePipeline, rendererAdapterFreezePolicy, rendererAdapterFreezeCompatibility, rendererAdapterFreezeDependencyContract, rendererAdapterFreezeRegistry, rendererAdapterFreezePublicApiSurface]) assert.equal(deeplyFrozen(value), true); });

  it("45-50. validates immutable full-Certification Freeze requests and rejects incomplete ones", () => { const valid = request(), before = JSON.stringify(valid); assert.equal(validateRendererAdapterFreezeRequest(valid).valid, true); assert.equal(validateRendererAdapterFreezeRequest(request({ freezeId: "" })).freezeIdValid, false); assert.equal(validateRendererAdapterFreezeRequest({ ...valid, certificationRequest: null } as unknown as NexoraObjectDirectorRendererAdapterFreezeRequest).certificationRequestValid, false); assert.equal(validateRendererAdapterFreezeRequest(request({ certificationRequest: certificationRequest({ requestedLevels: ["structural"] }) })).fullCertificationRequested, false); assert.equal(validateRendererAdapterFreezeRequest(request({ certificationRequest: certificationRequest({ executeBehaviorChecks: false }) })).behavioralChecksEnabled, false); assert.equal(JSON.stringify(valid), before); });

  it("51-59. creates, orders, de-duplicates, and safely freezes findings and evidence", () => { const later = rendererAdapterFreezeRequirements[5], first = rendererAdapterFreezeRequirements[0], laterFinding = createRendererAdapterFreezeFinding({ requirementId: later.id, passed: true, code: "LATER", message: "Later passed.", expected: freeze({ valid: true }), actual: freeze({ valid: true }), releaseBlocking: true }), firstFinding = createRendererAdapterFreezeFinding({ requirementId: first.id, passed: true, code: "FIRST", message: "First passed.", expected: true, actual: true, releaseBlocking: true }); assert.equal(deeplyFrozen(laterFinding.expected), true); assert.deepEqual(collectRendererAdapterFreezeFindings([laterFinding, firstFinding], [laterFinding]).map((item) => item.requirementId), [first.id, later.id]); assert.throws(() => createRendererAdapterFreezeFinding({ ...firstFinding, requirementId: "UNKNOWN" }), /Unknown Freeze requirement/); const evidence = { evidenceId: "freeze-evidence", requirementId: first.id, source: freezeId, path: "identity", value: freeze({ valid: true }), frozen: true }, collected = collectRendererAdapterFreezeEvidence([evidence], [evidence]); assert.equal(collected.length, 1); assert.throws(() => collectRendererAdapterFreezeEvidence([{ ...evidence, value: () => true }]), /plain values/); const circular: Record<string, unknown> = {}; circular.self = circular; assert.throws(() => collectRendererAdapterFreezeEvidence([{ ...evidence, value: circular }]), /circular/); });

  it("60-71. builds exact identity, stable release metadata, and valid Certification attestation", () => { const identity = buildRendererAdapterFrozenIdentity(), certification = executeRendererAdapterCertification(certificationRequest()), release = buildRendererAdapterFrozenReleaseInformation(certification), blockedRelease = buildRendererAdapterFrozenReleaseInformation(null), attestation = buildRendererAdapterFrozenCertificationAttestation(certification); assert.deepEqual(identity, { freezeIdentity: freezeId, certificationIdentity: "NOL-5:7/NexoraObjectDirectorRendererAdapterCertification", platformIdentity: "NOL-5:6/NexoraObjectDirectorRendererAdapterPlatform", moduleIdentity: "NOL-5/NexoraObjectDirectorRendererAdapter", namespace: freezeNamespace, version: freezeVersion, status: "Freeze", readiness: "ReadyForPublicIndex", lock: freezeLock }); assert.equal(release.stability, "stable"); assert.equal(blockedRelease.stability, "unstable"); assert.equal(attestation?.certificationOutcome, "certified"); assert.equal(attestation?.platformHealthy && attestation.platformReady && attestation.platformVerified, true); const rejected = executeRendererAdapterCertification(certificationRequest({ requestedLevels: [] })), partial = executeRendererAdapterCertification(certificationRequest({ requestedLevels: ["structural"] })), conditional = freeze({ ...certification, outcome: "conditionally-certified", certified: false, freezeReady: false }); assert.equal(buildRendererAdapterFrozenCertificationAttestation(rejected), null); assert.equal(buildRendererAdapterFrozenCertificationAttestation(partial), null); assert.equal(buildRendererAdapterFrozenCertificationAttestation(conditional as typeof certification), null); assert.equal(deeplyFrozen(identity) && deeplyFrozen(release) && deeplyFrozen(attestation), true); });

  it("72-75. preserves certified capability order and complete consumer guarantees", () => { const capabilities = buildRendererAdapterFreezeCapabilities(), guarantees = buildRendererAdapterFreezeConsumerGuarantees(); assert.deepEqual(capabilities.map((entry) => entry.order), Array.from({ length: 18 }, (_, index) => index + 1)); assert.equal(capabilities.every((entry) => entry.frozen), true); assert.deepEqual(guarantees.map((entry) => entry.name), rendererAdapterFreezeConsumerGuarantees.map((entry) => entry.name)); assert.equal(verifyRendererAdapterFreezeConsumerGuarantees(guarantees).valid, true); assert.equal(deeplyFrozen(capabilities) && deeplyFrozen(guarantees), true); });

  it("76-86. builds and verifies a unique deterministic Public API manifest and dependency boundary", () => { const manifest = buildRendererAdapterFrozenPublicApiManifest(), verification = verifyRendererAdapterFrozenPublicApiManifest(manifest); assert.equal(manifest.exportCount, manifest.entries.length); assert.equal(manifest.uniqueExportNames, true); assert.deepEqual(manifest.entries.map((entry) => entry.order), Array.from({ length: manifest.entries.length }, (_, index) => index + 1)); assert.equal(manifest.entries.every((entry) => entry.certified && entry.frozen && entry.publicIndexEligible), true); assert.equal(verification.valid, true); assert.equal(rendererAdapterFreezeCompatibility.readyForPublicIndex, true); assert.deepEqual(rendererAdapterFreezeDependencyContract.permittedProductionImports, ["./nexoraObjectDirectorRendererAdapterCertification"]); assert.deepEqual(rendererAdapterFreezeDependencyContract.prohibitedDirectLayers, ["NOL-5:1 Foundation", "NOL-5:2 Contracts", "NOL-5:3 Engine", "NOL-5:4 Integration", "NOL-5:5 Validation", "NOL-5:6 Platform", "NOL-4 Director Runtime"]); assert.equal(rendererAdapterFreezeDependencyContract.sequentialDependencyOnly, true); assert.equal(deeplyFrozen(manifest), true); });

  it("87-99. executes a full stable Freeze and preserves every blocked path", () => { const frozen = executeRendererAdapterFreeze(request()), disabled = executeRendererAdapterFreeze(request({ executeCertification: false })), partial = executeRendererAdapterFreeze(request({ certificationRequest: certificationRequest({ requestedLevels: ["structural"] }) })), behaviorDisabled = executeRendererAdapterFreeze(request({ certificationRequest: certificationRequest({ executeBehaviorChecks: false }) })); assert.equal(frozen.frozen, true); assert.equal(frozen.publicIndexReady, true); assert.equal(frozen.status, "frozen"); assert.equal(frozen.stability, "stable"); assert.ok(frozen.certificationAttestation); for (const blocked of [disabled, partial, behaviorDisabled]) { assert.equal(blocked.frozen, false); assert.equal(blocked.publicIndexReady, false); assert.equal(blocked.status, "blocked"); assert.equal(blocked.stability, "unstable"); assert.equal(blocked.certificationAttestation, null); } assert.equal(rendererAdapterFreezePolicy.freezeDoesNotRepair, true); });

  it("100-109. derives complete summaries while respecting finding and evidence visibility", () => { const complete = executeRendererAdapterFreeze(request()), omitted = executeRendererAdapterFreeze(request({ includeFindings: false, includeEvidence: false })); assert.equal(complete.summary.requirementCount, 28); assert.equal(complete.summary.passedRequirementCount, 28); assert.equal(complete.summary.failedRequirementCount, 0); assert.equal(complete.summary.capabilityCount, rendererAdapterFreezeCapabilities.length); assert.equal(complete.summary.consumerGuaranteeCount, rendererAdapterFreezeConsumerGuarantees.length); assert.equal(complete.summary.publicApiExportCount, rendererAdapterFreezePublicApiEntries.length); assert.equal(complete.summary.releaseBlockingFailureCount, 0); assert.equal(complete.findings.length, 28); assert.equal(complete.evidence.length, 28); assert.deepEqual(omitted.findings, []); assert.deepEqual(omitted.evidence, []); assert.equal(omitted.summary.findingCount, 28); });

  it("110-115. reports readiness, determinism, and exact result predicates", () => { const readiness = assessRendererAdapterFreezeReadiness(), original = request(), cloned = freeze({ ...original, certificationRequest: freeze({ ...original.certificationRequest, requestedLevels: freeze([...original.certificationRequest.requestedLevels]) }) }), determinism = verifyRendererAdapterFreezeDeterminism(original, cloned), frozen = executeRendererAdapterFreeze(original), blocked = executeRendererAdapterFreeze(request({ executeCertification: false })); assert.equal(readiness.ready && readiness.publicIndexTransitionReady, true); assert.equal(determinism.deterministic, true); assert.equal(isRendererAdapterFrozen(frozen), true); assert.equal(isRendererAdapterPublicIndexReady(frozen), true); assert.equal(isRendererAdapterFreezeBlocked(blocked), true); });

  it("116-127. preserves certified truth and deeply freezes every release surface", () => { const result = executeRendererAdapterFreeze(request()), certificationBefore = JSON.stringify(result.certificationResult); assert.equal(JSON.stringify(result.certificationResult), certificationBefore); for (const value of [result, result.identity, result.release, result.certificationAttestation, result.capabilities, result.consumerGuarantees, result.publicApiManifest, result.findings, result.evidence, result.summary]) assert.equal(deeplyFrozen(value), true); assert.equal(rendererAdapterFreezePolicy.freezeDoesNotMutate, true); assert.equal(rendererAdapterFreezePolicy.runtimeExecutionForbidden, true); });

  it("128-145. verifies Public Index transition and excludes prohibited capabilities", () => { const report = verifyRendererAdapterFreeze(); assert.equal(report.valid, true); assert.equal(report.publicIndexTransitionValid, true); assert.equal(report.publicSurfacesFrozen, true); assert.equal(deeplyFrozen(report), true); assert.equal(rendererAdapterFreezePolicy.publicIndexIsOnlyNextConsumer, true); assert.doesNotMatch(source, /from\s+["'][^"']*(?:Platform|Validation|Integration|Engine|Contracts|Foundation|nexoraObjectDirectorRuntime|react|next|three|webgl|canvas|svg|dom)/i); assert.doesNotMatch(source, /\b(?:async|await|Promise|setTimeout|setInterval|fetch|localStorage|sessionStorage|window|document|globalThis|Math\.random|Date\b|Worker|process|filesystem)\b|new\s+(?:Mesh|Scene|Camera|Renderer)|console\./); assert.equal(executeRendererAdapterFreeze(request()).publicIndexReady, true); });
});
