/** NOL-5:6 — validated operational Platform for immutable renderer-ready data. */
import {
  assessRendererAdapterValidationReadiness,
  executeRendererAdapterCollectionValidation,
  executeRendererAdapterValidation,
  freezeRendererObject,
  rendererAdapterValidationPolicy,
  validateRendererAdapterCollectionValidationRequest,
  validateRendererAdapterValidationRequest,
  validationId,
  validationVersion,
  verifyRendererAdapterValidation,
  verifyRendererValueFrozen,
  type NexoraObjectDirectorRendererAdapterCollectionValidationRequest,
  type NexoraObjectDirectorRendererAdapterCollectionValidationResult,
  type NexoraObjectDirectorRendererAdapterValidationFinding,
  type NexoraObjectDirectorRendererAdapterValidationRequest,
  type NexoraObjectDirectorRendererAdapterValidationResult,
  type RendererAdapterValidationEvidence,
  type RendererAdapterValidationSummary,
} from "./nexoraObjectDirectorRendererAdapterValidation.ts";

// NOL-5:6 exposes canonical immutability primitives to Certification.
export { freezeRendererObject, verifyRendererValueFrozen };

export const platformId = "NOL-5:6/NexoraObjectDirectorRendererAdapterPlatform" as const;
export const platformVersion = "5.6.0" as const;
export const platformNamespace = "nexora.nol.renderer.adapter.platform" as const;
export const platformStatus = "Platform" as const;
export const platformLock = "NOL-5-6-DIRECTOR-RENDERER-ADAPTER-PLATFORM-LOCKED" as const;

export type RendererAdapterPlatformMode = "strict" | "compatible";
export type RendererAdapterPlatformOperation = "single" | "collection" | "inspect";
export type RendererAdapterPlatformStatus = "ready" | "degraded" | "blocked";
export type RendererObject = NonNullable<NonNullable<NexoraObjectDirectorRendererAdapterValidationResult["integrationResult"]>["rendererObject"]>;

export interface NexoraObjectDirectorRendererAdapterPlatformConfiguration { readonly mode: RendererAdapterPlatformMode; readonly validationEnabled: true; readonly failOnWarning: boolean; readonly includeFindings: boolean; readonly includeEvidence: boolean; readonly includeSummary: boolean; readonly includeTrace: boolean; readonly preserveCollectionOrder: true; }
export interface NexoraObjectDirectorRendererAdapterPlatformRequest { readonly platformRequestId: string; readonly consumerId: string; readonly operation: "single"; readonly runtimeObject: unknown; readonly sourceRuntimeId: string; readonly configuration: NexoraObjectDirectorRendererAdapterPlatformConfiguration; }
export interface NexoraObjectDirectorRendererAdapterCollectionPlatformRequest { readonly platformRequestId: string; readonly consumerId: string; readonly operation: "collection"; readonly runtimeObjects: readonly unknown[]; readonly sourceRuntimeIds: readonly string[]; readonly configuration: NexoraObjectDirectorRendererAdapterPlatformConfiguration; readonly preserveOrder: true; }
export interface NexoraObjectDirectorRendererAdapterPlatformInspectionRequest { readonly platformRequestId: string; readonly consumerId: string; readonly operation: "inspect"; readonly includeCapabilities: boolean; readonly includeHealth: boolean; readonly includeReadiness: boolean; }
export type NexoraObjectDirectorRendererAdapterPlatformRequestUnion = NexoraObjectDirectorRendererAdapterPlatformRequest | NexoraObjectDirectorRendererAdapterCollectionPlatformRequest | NexoraObjectDirectorRendererAdapterPlatformInspectionRequest;
export interface RendererAdapterPlatformRequestValidationResult { readonly valid: boolean; readonly platformRequestIdValid: boolean; readonly consumerIdValid: boolean; readonly operationValid: boolean; readonly configurationValid: boolean; readonly payloadValid: boolean; readonly validationDependencyCompatible: boolean; readonly violations: readonly string[]; }
export interface RendererAdapterPlatformResultMetadata { readonly platformIdentity: string; readonly platformVersion: string; readonly platformRequestId: string; readonly consumerId: string; readonly operation: RendererAdapterPlatformOperation; readonly mode: RendererAdapterPlatformMode | null; readonly status: RendererAdapterPlatformStatus; readonly validated: boolean; readonly deterministic: true; readonly deeplyFrozen: true; }
export interface NexoraObjectDirectorRendererAdapterPlatformResult { readonly metadata: RendererAdapterPlatformResultMetadata; readonly accepted: boolean; readonly valid: boolean; readonly rendererObject: RendererObject | null; readonly validationResult: NexoraObjectDirectorRendererAdapterValidationResult | null; readonly findings: readonly NexoraObjectDirectorRendererAdapterValidationFinding[]; readonly evidence: readonly RendererAdapterValidationEvidence[]; readonly summary: RendererAdapterValidationSummary | null; readonly warnings: readonly string[]; readonly errors: readonly string[]; readonly guarantees: NexoraObjectDirectorRendererAdapterPlatformGuarantees; }
export interface NexoraObjectDirectorRendererAdapterCollectionPlatformItemResult { readonly index: number; readonly sourceRuntimeId: string; readonly accepted: boolean; readonly valid: boolean; readonly rendererObject: RendererObject | null; readonly warningCount: number; readonly errorCount: number; readonly findings: readonly NexoraObjectDirectorRendererAdapterValidationFinding[]; readonly deeplyFrozen: true; }
export interface NexoraObjectDirectorRendererAdapterCollectionPlatformResult { readonly metadata: RendererAdapterPlatformResultMetadata; readonly accepted: boolean; readonly valid: boolean; readonly rendererObjects: readonly RendererObject[]; readonly itemResults: readonly NexoraObjectDirectorRendererAdapterCollectionPlatformItemResult[]; readonly validationResult: NexoraObjectDirectorRendererAdapterCollectionValidationResult | null; readonly findings: readonly NexoraObjectDirectorRendererAdapterValidationFinding[]; readonly evidence: readonly RendererAdapterValidationEvidence[]; readonly summary: RendererAdapterValidationSummary | null; readonly sourceCount: number; readonly outputCount: number; readonly failedItemCount: number; readonly orderPreserved: true; readonly partial: boolean; readonly warnings: readonly string[]; readonly errors: readonly string[]; readonly guarantees: NexoraObjectDirectorRendererAdapterPlatformGuarantees; }
export interface NexoraObjectDirectorRendererAdapterPlatformInspectionResult { readonly metadata: RendererAdapterPlatformResultMetadata; readonly ready: boolean; readonly capabilities: readonly RendererAdapterPlatformCapability[]; readonly health: RendererAdapterPlatformHealthReport | null; readonly readiness: RendererAdapterPlatformReadinessReport | null; readonly warnings: readonly string[]; readonly errors: readonly string[]; readonly guarantees: NexoraObjectDirectorRendererAdapterPlatformGuarantees; }
export type NexoraObjectDirectorRendererAdapterPlatformResultUnion = NexoraObjectDirectorRendererAdapterPlatformResult | NexoraObjectDirectorRendererAdapterCollectionPlatformResult | NexoraObjectDirectorRendererAdapterPlatformInspectionResult;
export interface RendererAdapterPlatformCapability { readonly id: string; readonly order: number; readonly name: string; readonly supported: true; readonly description: string; }
export interface NexoraObjectDirectorRendererAdapterPlatformGuarantees { readonly validationMandatory: true; readonly validationOnlyDependency: true; readonly synchronous: true; readonly deterministic: true; readonly sideEffectFree: true; readonly rendererExecutionForbidden: true; readonly runtimeMutationForbidden: true; readonly validationRepairForbidden: true; readonly strictModeSupported: true; readonly compatibleModeSupported: true; readonly singleProcessingSupported: true; readonly collectionProcessingSupported: true; readonly inspectionSupported: true; readonly collectionOrderPreserved: true; readonly partialCompatibleResultsSupported: true; readonly deeplyFrozenOutputs: true; readonly rendererFrameworkAgnostic: true; }
export interface NexoraObjectDirectorRendererAdapterPlatformCompatibility { readonly platformIdentity: string; readonly validationIdentity: string; readonly compatibleValidationVersion: string; readonly validationOnlyDependency: true; readonly strictModeCompatible: boolean; readonly compatibleModeCompatible: boolean; readonly singleProcessingCompatible: boolean; readonly collectionProcessingCompatible: boolean; readonly inspectionCompatible: boolean; readonly rendererFrameworkAgnostic: true; }
export interface RendererAdapterPlatformHealthReport { readonly healthy: boolean; readonly identityHealthy: boolean; readonly validationHealthy: boolean; readonly configurationHealthy: boolean; readonly capabilityRegistryHealthy: boolean; readonly pipelineHealthy: boolean; readonly compatibilityHealthy: boolean; readonly determinismHealthy: boolean; readonly immutabilityHealthy: boolean; readonly prohibitedCapabilitiesAbsent: boolean; readonly status: RendererAdapterPlatformStatus; readonly violations: readonly string[]; }
export interface RendererAdapterPlatformReadinessReport { readonly ready: boolean; readonly identityReady: boolean; readonly dependencyReady: boolean; readonly validationReady: boolean; readonly configurationReady: boolean; readonly capabilitiesReady: boolean; readonly pipelineReady: boolean; readonly compatibilityReady: boolean; readonly healthReady: boolean; readonly deterministicExecutionReady: boolean; readonly publicSurfacesFrozen: boolean; readonly violations: readonly string[]; }
export interface RendererAdapterPlatformDeterminismReport { readonly deterministic: boolean; readonly requestEquivalent: boolean; readonly validationEquivalent: boolean; readonly rendererOutputEquivalent: boolean; readonly findingsEquivalent: boolean; readonly evidenceEquivalent: boolean; readonly summaryEquivalent: boolean; readonly warningsEquivalent: boolean; readonly errorsEquivalent: boolean; readonly metadataEquivalent: boolean; readonly violations: readonly string[]; }
export interface NexoraObjectDirectorRendererAdapterPlatformVerificationReport { readonly valid: boolean; readonly identityValid: boolean; readonly namespaceValid: boolean; readonly versionValid: boolean; readonly statusValid: boolean; readonly lockValid: boolean; readonly dependencyValid: boolean; readonly validationCompatible: boolean; readonly modesValid: boolean; readonly operationsValid: boolean; readonly configurationValid: boolean; readonly capabilitiesValid: boolean; readonly pipelineValid: boolean; readonly registryValid: boolean; readonly guaranteesValid: boolean; readonly healthValid: boolean; readonly readinessValid: boolean; readonly deterministicExecutionValid: boolean; readonly publicSurfacesFrozen: boolean; readonly prohibitedCapabilitiesAbsent: boolean; readonly violations: readonly string[]; }

export const rendererAdapterPlatformModes = freezeRendererObject(["strict", "compatible"] as const satisfies readonly RendererAdapterPlatformMode[]);
export const rendererAdapterPlatformModeCount = rendererAdapterPlatformModes.length;
export const rendererAdapterPlatformOperations = freezeRendererObject(["single", "collection", "inspect"] as const satisfies readonly RendererAdapterPlatformOperation[]);
export const rendererAdapterPlatformOperationCount = rendererAdapterPlatformOperations.length;
export const rendererAdapterPlatformStatuses = freezeRendererObject(["ready", "degraded", "blocked"] as const satisfies readonly RendererAdapterPlatformStatus[]);
export const rendererAdapterPlatformStatusCount = rendererAdapterPlatformStatuses.length;
export const rendererAdapterPlatformDefaultConfiguration: NexoraObjectDirectorRendererAdapterPlatformConfiguration = freezeRendererObject({ mode: "strict", validationEnabled: true, failOnWarning: false, includeFindings: true, includeEvidence: false, includeSummary: true, includeTrace: false, preserveCollectionOrder: true } as const);

const capabilityNames = ["Platform Request Validation", "Strict Single Processing", "Compatible Single Processing", "Strict Collection Processing", "Compatible Collection Processing", "Partial Collection Results", "Collection Order Preservation", "Validation Findings", "Validation Evidence", "Validation Summaries", "Platform Inspection", "Health Assessment", "Readiness Assessment", "Compatibility Verification", "Structural Determinism", "Deep Immutability", "Consumer Guarantees", "Platform Verification"] as const;
export const rendererAdapterPlatformCapabilities: readonly RendererAdapterPlatformCapability[] = freezeRendererObject(capabilityNames.map((name, index) => ({ id: `platform-capability-${String(index + 1).padStart(2, "0")}`, order: index + 1, name, supported: true as const, description: `${name} is supported by the immutable NOL-5:6 Platform.` })));
export const rendererAdapterPlatformCapabilityCount = rendererAdapterPlatformCapabilities.length;
export const rendererAdapterPlatformPipeline = freezeRendererObject([
  { id: "validate-platform-request", order: 1, name: "Validate Platform Request", required: true },
  { id: "resolve-platform-operation", order: 2, name: "Resolve Platform Operation", required: true },
  { id: "resolve-platform-configuration", order: 3, name: "Resolve Platform Configuration", required: true },
  { id: "build-validation-request", order: 4, name: "Build Validation Request", required: true },
  { id: "execute-validation", order: 5, name: "Execute Validation", required: true },
  { id: "normalize-validation-result", order: 6, name: "Normalize Validation Result", required: true },
  { id: "resolve-platform-status", order: 7, name: "Resolve Platform Status", required: true },
  { id: "build-platform-metadata", order: 8, name: "Build Platform Metadata", required: true },
  { id: "attach-platform-guarantees", order: 9, name: "Attach Platform Guarantees", required: true },
  { id: "freeze-platform-result", order: 10, name: "Freeze Platform Result", required: true },
] as const);
export const rendererAdapterPlatformPipelineStepCount = rendererAdapterPlatformPipeline.length;
export const rendererAdapterPlatformGuarantees: NexoraObjectDirectorRendererAdapterPlatformGuarantees = freezeRendererObject({ validationMandatory: true, validationOnlyDependency: true, synchronous: true, deterministic: true, sideEffectFree: true, rendererExecutionForbidden: true, runtimeMutationForbidden: true, validationRepairForbidden: true, strictModeSupported: true, compatibleModeSupported: true, singleProcessingSupported: true, collectionProcessingSupported: true, inspectionSupported: true, collectionOrderPreserved: true, partialCompatibleResultsSupported: true, deeplyFrozenOutputs: true, rendererFrameworkAgnostic: true } as const);
export const rendererAdapterPlatformCompatibility: NexoraObjectDirectorRendererAdapterPlatformCompatibility = freezeRendererObject({ platformIdentity: platformId, validationIdentity: validationId, compatibleValidationVersion: validationVersion, validationOnlyDependency: true, strictModeCompatible: true, compatibleModeCompatible: true, singleProcessingCompatible: true, collectionProcessingCompatible: true, inspectionCompatible: true, rendererFrameworkAgnostic: true } as const);
export const rendererAdapterPlatformRegistry = freezeRendererObject(["Identity", "Configuration", "Request Validation", "Single Processing", "Collection Processing", "Inspection", "Result Normalization", "Status Resolution", "Capabilities", "Guarantees", "Health", "Readiness", "Compatibility", "Determinism", "Verification"] as const);
export const rendererAdapterPlatformRegistryCount = rendererAdapterPlatformRegistry.length;
export const rendererAdapterPlatformPublicApiSurface = freezeRendererObject(["createRendererAdapterPlatformConfiguration", "validateRendererAdapterPlatformRequest", "createRendererAdapterPlatformValidationRequest", "createRendererAdapterCollectionPlatformValidationRequest", "executeRendererAdapterPlatform", "executeRendererAdapterCollectionPlatform", "inspectRendererAdapterPlatform", "resolveRendererAdapterPlatformStatus", "normalizeRendererAdapterPlatformResult", "normalizeRendererAdapterCollectionPlatformResult", "createRendererAdapterPlatformMetadata", "assessRendererAdapterPlatformHealth", "assessRendererAdapterPlatformReadiness", "verifyRendererAdapterPlatformDeterminism", "isRendererAdapterPlatformReadyResult", "isRendererAdapterPlatformDegradedResult", "isRendererAdapterPlatformBlockedResult", "verifyRendererAdapterPlatform"] as const);
export const rendererAdapterPlatformPublicApiCount = rendererAdapterPlatformPublicApiSurface.length;

type IntegrationRequest = NexoraObjectDirectorRendererAdapterValidationRequest["integrationRequest"];
type CollectionIntegrationRequest = NexoraObjectDirectorRendererAdapterCollectionValidationRequest["integrationRequest"];
type InputContract = IntegrationRequest["engineRequest"]["input"];

function record(value: unknown): value is Record<string, unknown> { return value !== null && typeof value === "object" && !Array.isArray(value); }
function equivalent(left: unknown, right: unknown): boolean { if (Object.is(left, right)) return true; if (Array.isArray(left) || Array.isArray(right)) return Array.isArray(left) && Array.isArray(right) && left.length === right.length && left.every((value, index) => equivalent(value, right[index])); if (!record(left) || !record(right)) return false; const a = Object.keys(left).sort(), b = Object.keys(right).sort(); return a.length === b.length && a.every((key, index) => key === b[index] && equivalent(left[key], right[key])); }
function uniqueMessages(values: readonly string[]): readonly string[] { const result: string[] = [], seen = new Set<string>(); for (const value of values) { const normalized = value.trim(); if (normalized && !seen.has(normalized)) { seen.add(normalized); result.push(normalized); } } return freezeRendererObject(result); }

export function createRendererAdapterPlatformConfiguration(options: Partial<NexoraObjectDirectorRendererAdapterPlatformConfiguration> = {}): NexoraObjectDirectorRendererAdapterPlatformConfiguration {
  const configuration = { ...rendererAdapterPlatformDefaultConfiguration, ...options };
  if (!rendererAdapterPlatformModes.includes(configuration.mode) || configuration.validationEnabled !== true || configuration.preserveCollectionOrder !== true || ![configuration.failOnWarning, configuration.includeFindings, configuration.includeEvidence, configuration.includeSummary, configuration.includeTrace].every((value) => typeof value === "boolean")) throw new TypeError("Platform configuration must preserve mandatory validation, order, and supported options");
  return freezeRendererObject(configuration);
}

function configurationValid(value: unknown): value is NexoraObjectDirectorRendererAdapterPlatformConfiguration { return record(value) && rendererAdapterPlatformModes.includes(value.mode as RendererAdapterPlatformMode) && value.validationEnabled === true && value.preserveCollectionOrder === true && [value.failOnWarning, value.includeFindings, value.includeEvidence, value.includeSummary, value.includeTrace].every((setting) => typeof setting === "boolean") && verifyRendererValueFrozen(value); }

export function validateRendererAdapterPlatformRequest(request: NexoraObjectDirectorRendererAdapterPlatformRequestUnion): RendererAdapterPlatformRequestValidationResult {
  const value: Record<string, unknown> = record(request) ? request : {}, platformRequestIdValid = typeof value.platformRequestId === "string" && value.platformRequestId.trim().length > 0, consumerIdValid = typeof value.consumerId === "string" && value.consumerId.trim().length > 0, operationValid = rendererAdapterPlatformOperations.includes(value.operation as RendererAdapterPlatformOperation), validationDependencyCompatible = verifyRendererAdapterValidation().valid;
  let configValid = value.operation === "inspect", payloadValid = false;
  if (value.operation === "single") { configValid = configurationValid(value.configuration); payloadValid = record(value.runtimeObject) && verifyRendererValueFrozen(value.runtimeObject) && typeof value.sourceRuntimeId === "string" && value.sourceRuntimeId.trim().length > 0; }
  else if (value.operation === "collection") { configValid = configurationValid(value.configuration); payloadValid = Array.isArray(value.runtimeObjects) && Array.isArray(value.sourceRuntimeIds) && value.runtimeObjects.length === value.sourceRuntimeIds.length && value.runtimeObjects.every((item) => record(item) && verifyRendererValueFrozen(item)) && value.sourceRuntimeIds.every((id) => typeof id === "string" && id.trim().length > 0) && value.preserveOrder === true; }
  else if (value.operation === "inspect") payloadValid = [value.includeCapabilities, value.includeHealth, value.includeReadiness].every((setting) => typeof setting === "boolean");
  const violations: string[] = [];
  if (!platformRequestIdValid) violations.push("platformRequestId is required"); if (!consumerIdValid) violations.push("consumerId is required"); if (!operationValid) violations.push("Platform operation is unsupported"); if (!configValid) violations.push("Platform configuration is invalid"); if (!payloadValid) violations.push("Platform request payload is invalid"); if (!validationDependencyCompatible) violations.push("NOL-5:5 Validation is incompatible");
  return freezeRendererObject({ valid: platformRequestIdValid && consumerIdValid && operationValid && configValid && payloadValid && validationDependencyCompatible, platformRequestIdValid, consumerIdValid, operationValid, configurationValid: configValid, payloadValid, validationDependencyCompatible, violations: uniqueMessages(violations) });
}

export function createRendererAdapterPlatformValidationRequest(request: NexoraObjectDirectorRendererAdapterPlatformRequest): NexoraObjectDirectorRendererAdapterValidationRequest {
  if (!validateRendererAdapterPlatformRequest(request).valid) throw new TypeError("A valid single Platform request is required");
  const input: InputContract = freezeRendererObject({ runtimeObject: request.runtimeObject, sourceRuntimeId: request.sourceRuntimeId, preserveRuntimeMetadata: true });
  const integrationRequest: IntegrationRequest = freezeRendererObject({ integrationId: request.platformRequestId, consumerId: request.consumerId, mode: request.configuration.mode, includeTrace: request.configuration.includeTrace, includeSummary: request.configuration.includeSummary, engineRequest: freezeRendererObject({ requestId: request.platformRequestId, input, strict: request.configuration.mode === "strict", includeWarnings: true }) });
  const translated: NexoraObjectDirectorRendererAdapterValidationRequest = freezeRendererObject({ validationId: request.platformRequestId, integrationRequest, executeIntegration: true, includeFindings: request.configuration.includeFindings, includeEvidence: request.configuration.includeEvidence, failOnWarning: request.configuration.failOnWarning });
  if (!validateRendererAdapterValidationRequest(translated).valid) throw new TypeError("Translated single Validation request is invalid");
  return translated;
}

export function createRendererAdapterCollectionPlatformValidationRequest(request: NexoraObjectDirectorRendererAdapterCollectionPlatformRequest): NexoraObjectDirectorRendererAdapterCollectionValidationRequest {
  if (!validateRendererAdapterPlatformRequest(request).valid) throw new TypeError("A valid collection Platform request is required");
  const inputs = freezeRendererObject(request.runtimeObjects.map((runtimeObject, index): InputContract => freezeRendererObject({ runtimeObject, sourceRuntimeId: request.sourceRuntimeIds[index], preserveRuntimeMetadata: true })));
  const integrationRequest: CollectionIntegrationRequest = freezeRendererObject({ integrationId: request.platformRequestId, consumerId: request.consumerId, mode: request.configuration.mode, includeTrace: request.configuration.includeTrace, includeSummary: request.configuration.includeSummary, preserveOrder: true, engineRequest: freezeRendererObject({ requestId: request.platformRequestId, inputs, strict: request.configuration.mode === "strict", includeWarnings: true, preserveOrder: true }) });
  const translated: NexoraObjectDirectorRendererAdapterCollectionValidationRequest = freezeRendererObject({ validationId: request.platformRequestId, integrationRequest, executeIntegration: true, includeFindings: request.configuration.includeFindings, includeEvidence: request.configuration.includeEvidence, failOnWarning: request.configuration.failOnWarning, preserveOrder: true });
  if (!validateRendererAdapterCollectionValidationRequest(translated).valid) throw new TypeError("Translated collection Validation request is invalid");
  return translated;
}

export function createRendererAdapterPlatformMetadata(platformRequestId: string, consumerId: string, operation: RendererAdapterPlatformOperation, mode: RendererAdapterPlatformMode | null, status: RendererAdapterPlatformStatus, validated: boolean): RendererAdapterPlatformResultMetadata {
  if (!platformRequestId.trim() || !consumerId.trim() || !rendererAdapterPlatformOperations.includes(operation) || !rendererAdapterPlatformStatuses.includes(status) || (mode !== null && !rendererAdapterPlatformModes.includes(mode))) throw new TypeError("Platform metadata values are invalid");
  return freezeRendererObject({ platformIdentity: platformId, platformVersion, platformRequestId, consumerId, operation, mode, status, validated, deterministic: true, deeplyFrozen: true });
}

export function resolveRendererAdapterPlatformStatus(requestValid: boolean, operation: RendererAdapterPlatformOperation, validationResult: NexoraObjectDirectorRendererAdapterValidationResult | NexoraObjectDirectorRendererAdapterCollectionValidationResult | null, mode: RendererAdapterPlatformMode | null, inspectionReady = false): RendererAdapterPlatformStatus {
  if (!requestValid) return "blocked";
  if (operation === "inspect") return inspectionReady ? "ready" : "blocked";
  if (!validationResult || !validationResult.valid || !validationResult.accepted) return "blocked";
  const partial = "itemResults" in validationResult && validationResult.failedItemCount > 0 && validationResult.outputCount > 0;
  if ((mode === "compatible" && validationResult.warnings.length > 0) || partial || validationResult.warnings.length > 0) return "degraded";
  return "ready";
}

export function normalizeRendererAdapterPlatformResult(request: NexoraObjectDirectorRendererAdapterPlatformRequest, validationResult: NexoraObjectDirectorRendererAdapterValidationResult): NexoraObjectDirectorRendererAdapterPlatformResult {
  const status = resolveRendererAdapterPlatformStatus(true, "single", validationResult, request.configuration.mode), rendererObject = validationResult.valid && validationResult.accepted ? validationResult.integrationResult?.rendererObject ?? null : null;
  return freezeRendererObject({ metadata: createRendererAdapterPlatformMetadata(request.platformRequestId, request.consumerId, "single", request.configuration.mode, status, true), accepted: validationResult.accepted, valid: validationResult.valid, rendererObject, validationResult, findings: validationResult.findings, evidence: validationResult.evidence, summary: request.configuration.includeSummary ? validationResult.summary : null, warnings: validationResult.warnings, errors: validationResult.errors, guarantees: rendererAdapterPlatformGuarantees });
}

export function normalizeRendererAdapterCollectionPlatformResult(request: NexoraObjectDirectorRendererAdapterCollectionPlatformRequest, validationResult: NexoraObjectDirectorRendererAdapterCollectionValidationResult, extraWarnings: readonly string[] = []): NexoraObjectDirectorRendererAdapterCollectionPlatformResult {
  const integrationItems = validationResult.integrationResult?.itemResults ?? [], rendererObjects = validationResult.valid && validationResult.accepted ? validationResult.integrationResult?.rendererObjects ?? [] : [], itemResults = freezeRendererObject(request.sourceRuntimeIds.map((sourceRuntimeId, index): NexoraObjectDirectorRendererAdapterCollectionPlatformItemResult => { const validatedItem = validationResult.itemResults[index], integratedItem = integrationItems[index]; return freezeRendererObject({ index, sourceRuntimeId, accepted: integratedItem?.accepted ?? false, valid: validatedItem?.valid ?? false, rendererObject: integratedItem?.rendererObject ?? null, warningCount: validatedItem?.warningCount ?? integratedItem?.warnings.length ?? 0, errorCount: validatedItem?.errorCount ?? integratedItem?.errors.length ?? 0, findings: validatedItem?.findings ?? freezeRendererObject([]), deeplyFrozen: true }); }));
  const partial = itemResults.some((item) => item.accepted) && itemResults.some((item) => !item.accepted), warnings = uniqueMessages([...validationResult.warnings, ...extraWarnings]), status = resolveRendererAdapterPlatformStatus(true, "collection", freezeRendererObject({ ...validationResult, warnings }), request.configuration.mode);
  return freezeRendererObject({ metadata: createRendererAdapterPlatformMetadata(request.platformRequestId, request.consumerId, "collection", request.configuration.mode, status, true), accepted: validationResult.accepted, valid: validationResult.valid, rendererObjects, itemResults, validationResult, findings: validationResult.findings, evidence: validationResult.evidence, summary: request.configuration.includeSummary ? validationResult.summary : null, sourceCount: validationResult.sourceCount, outputCount: validationResult.outputCount, failedItemCount: validationResult.failedItemCount, orderPreserved: true, partial, warnings, errors: validationResult.errors, guarantees: rendererAdapterPlatformGuarantees });
}

function blockedSingle(request: NexoraObjectDirectorRendererAdapterPlatformRequest, violations: readonly string[]): NexoraObjectDirectorRendererAdapterPlatformResult { return freezeRendererObject({ metadata: createRendererAdapterPlatformMetadata(typeof request.platformRequestId === "string" && request.platformRequestId ? request.platformRequestId : "invalid-platform-request", typeof request.consumerId === "string" && request.consumerId ? request.consumerId : "invalid-consumer", "single", record(request.configuration) && rendererAdapterPlatformModes.includes(request.configuration.mode as RendererAdapterPlatformMode) ? request.configuration.mode as RendererAdapterPlatformMode : null, "blocked", false), accepted: false, valid: false, rendererObject: null, validationResult: null, findings: freezeRendererObject([]), evidence: freezeRendererObject([]), summary: null, warnings: freezeRendererObject([]), errors: uniqueMessages(violations), guarantees: rendererAdapterPlatformGuarantees }); }
function blockedCollection(request: NexoraObjectDirectorRendererAdapterCollectionPlatformRequest, violations: readonly string[]): NexoraObjectDirectorRendererAdapterCollectionPlatformResult { return freezeRendererObject({ metadata: createRendererAdapterPlatformMetadata(typeof request.platformRequestId === "string" && request.platformRequestId ? request.platformRequestId : "invalid-platform-request", typeof request.consumerId === "string" && request.consumerId ? request.consumerId : "invalid-consumer", "collection", record(request.configuration) && rendererAdapterPlatformModes.includes(request.configuration.mode as RendererAdapterPlatformMode) ? request.configuration.mode as RendererAdapterPlatformMode : null, "blocked", false), accepted: false, valid: false, rendererObjects: freezeRendererObject([]), itemResults: freezeRendererObject([]), validationResult: null, findings: freezeRendererObject([]), evidence: freezeRendererObject([]), summary: null, sourceCount: 0, outputCount: 0, failedItemCount: 0, orderPreserved: true, partial: false, warnings: freezeRendererObject([]), errors: uniqueMessages(violations), guarantees: rendererAdapterPlatformGuarantees }); }

export function executeRendererAdapterPlatform(request: NexoraObjectDirectorRendererAdapterPlatformRequest): NexoraObjectDirectorRendererAdapterPlatformResult { const validation = validateRendererAdapterPlatformRequest(request); if (!validation.valid) return blockedSingle(request, validation.violations); return normalizeRendererAdapterPlatformResult(request, executeRendererAdapterValidation(createRendererAdapterPlatformValidationRequest(request))); }
export function executeRendererAdapterCollectionPlatform(request: NexoraObjectDirectorRendererAdapterCollectionPlatformRequest): NexoraObjectDirectorRendererAdapterCollectionPlatformResult { const validation = validateRendererAdapterPlatformRequest(request); if (!validation.valid) return blockedCollection(request, validation.violations); const duplicates: string[] = [], seen = new Set<string>(); request.sourceRuntimeIds.forEach((id) => { if (seen.has(id)) duplicates.push(`Duplicate source runtime ID retained: ${id}`); else seen.add(id); }); return normalizeRendererAdapterCollectionPlatformResult(request, executeRendererAdapterCollectionValidation(createRendererAdapterCollectionPlatformValidationRequest(request)), duplicates); }

export function assessRendererAdapterPlatformHealth(): RendererAdapterPlatformHealthReport {
  const identityHealthy = platformId === "NOL-5:6/NexoraObjectDirectorRendererAdapterPlatform" && platformVersion === "5.6.0" && platformNamespace === "nexora.nol.renderer.adapter.platform" && platformStatus === "Platform" && platformLock === "NOL-5-6-DIRECTOR-RENDERER-ADAPTER-PLATFORM-LOCKED", validationHealthy = verifyRendererAdapterValidation().valid, configurationHealthy = configurationValid(rendererAdapterPlatformDefaultConfiguration), capabilityRegistryHealthy = rendererAdapterPlatformCapabilities.length === rendererAdapterPlatformCapabilityCount && rendererAdapterPlatformCapabilities.every((entry, index) => entry.order === index + 1 && entry.supported), pipelineHealthy = rendererAdapterPlatformPipeline.length === rendererAdapterPlatformPipelineStepCount && rendererAdapterPlatformPipeline.every((entry, index) => entry.order === index + 1 && entry.required), compatibilityHealthy = rendererAdapterPlatformCompatibility.validationIdentity === validationId && rendererAdapterPlatformCompatibility.compatibleValidationVersion === validationVersion, determinismHealthy = rendererAdapterPlatformGuarantees.deterministic, immutabilityHealthy = [rendererAdapterPlatformModes, rendererAdapterPlatformOperations, rendererAdapterPlatformStatuses, rendererAdapterPlatformDefaultConfiguration, rendererAdapterPlatformCapabilities, rendererAdapterPlatformPipeline, rendererAdapterPlatformGuarantees, rendererAdapterPlatformCompatibility, rendererAdapterPlatformRegistry, rendererAdapterPlatformPublicApiSurface].every(verifyRendererValueFrozen), prohibitedCapabilitiesAbsent = rendererAdapterPlatformGuarantees.rendererExecutionForbidden && rendererAdapterPlatformGuarantees.sideEffectFree, violations: string[] = [];
  if (!identityHealthy) violations.push("Platform identity is unhealthy"); if (!validationHealthy) violations.push("Validation dependency is unhealthy"); if (!configurationHealthy) violations.push("Platform configuration is unhealthy"); if (!capabilityRegistryHealthy) violations.push("Capability registry is unhealthy"); if (!pipelineHealthy) violations.push("Platform pipeline is unhealthy"); if (!compatibilityHealthy) violations.push("Platform compatibility is unhealthy"); if (!determinismHealthy) violations.push("Platform determinism is unhealthy"); if (!immutabilityHealthy) violations.push("Platform immutability is unhealthy"); if (!prohibitedCapabilitiesAbsent) violations.push("A prohibited capability is present");
  return freezeRendererObject({ healthy: violations.length === 0, identityHealthy, validationHealthy, configurationHealthy, capabilityRegistryHealthy, pipelineHealthy, compatibilityHealthy, determinismHealthy, immutabilityHealthy, prohibitedCapabilitiesAbsent, status: violations.length === 0 ? "ready" : "blocked", violations });
}

export function assessRendererAdapterPlatformReadiness(): RendererAdapterPlatformReadinessReport {
  const health = assessRendererAdapterPlatformHealth(), identityReady = health.identityHealthy, dependencyReady = rendererAdapterPlatformGuarantees.validationOnlyDependency, validationReady = assessRendererAdapterValidationReadiness().ready, configurationReady = health.configurationHealthy, capabilitiesReady = health.capabilityRegistryHealthy, pipelineReady = health.pipelineHealthy && rendererAdapterPlatformRegistry.length === rendererAdapterPlatformRegistryCount, compatibilityReady = health.compatibilityHealthy, healthReady = health.healthy, deterministicExecutionReady = health.determinismHealthy, publicSurfacesFrozen = health.immutabilityHealthy, violations: string[] = [];
  if (!identityReady) violations.push("Platform identity is not ready"); if (!dependencyReady) violations.push("Platform dependency is not ready"); if (!validationReady) violations.push("Validation is not ready"); if (!configurationReady) violations.push("Configuration is not ready"); if (!capabilitiesReady) violations.push("Capabilities are not ready"); if (!pipelineReady) violations.push("Pipeline or registry is not ready"); if (!compatibilityReady) violations.push("Compatibility is not ready"); if (!healthReady) violations.push("Platform health is not ready"); if (!deterministicExecutionReady) violations.push("Deterministic execution is not ready"); if (!publicSurfacesFrozen) violations.push("A Platform public surface is mutable");
  return freezeRendererObject({ ready: violations.length === 0, identityReady, dependencyReady, validationReady, configurationReady, capabilitiesReady, pipelineReady, compatibilityReady, healthReady, deterministicExecutionReady, publicSurfacesFrozen, violations });
}

export function inspectRendererAdapterPlatform(request: NexoraObjectDirectorRendererAdapterPlatformInspectionRequest): NexoraObjectDirectorRendererAdapterPlatformInspectionResult {
  const validation = validateRendererAdapterPlatformRequest(request), readiness = assessRendererAdapterPlatformReadiness(), health = assessRendererAdapterPlatformHealth(), ready = validation.valid && readiness.ready, status = resolveRendererAdapterPlatformStatus(validation.valid, "inspect", null, null, ready);
  return freezeRendererObject({ metadata: createRendererAdapterPlatformMetadata(typeof request.platformRequestId === "string" && request.platformRequestId ? request.platformRequestId : "invalid-platform-request", typeof request.consumerId === "string" && request.consumerId ? request.consumerId : "invalid-consumer", "inspect", null, status, validation.valid), ready, capabilities: validation.valid && request.includeCapabilities ? rendererAdapterPlatformCapabilities : freezeRendererObject([]), health: validation.valid && request.includeHealth ? health : null, readiness: validation.valid && request.includeReadiness ? readiness : null, warnings: freezeRendererObject([]), errors: validation.valid ? freezeRendererObject([]) : validation.violations, guarantees: rendererAdapterPlatformGuarantees });
}

function outputOf(result: NexoraObjectDirectorRendererAdapterPlatformResultUnion): unknown { if ("rendererObjects" in result) return result.rendererObjects; if ("rendererObject" in result) return result.rendererObject; return result.ready; }
function executePlatform(request: NexoraObjectDirectorRendererAdapterPlatformRequestUnion): NexoraObjectDirectorRendererAdapterPlatformResultUnion { if (request.operation === "single") return executeRendererAdapterPlatform(request); if (request.operation === "collection") return executeRendererAdapterCollectionPlatform(request); return inspectRendererAdapterPlatform(request); }
export function verifyRendererAdapterPlatformDeterminism(request: NexoraObjectDirectorRendererAdapterPlatformRequestUnion, equivalentRequest: NexoraObjectDirectorRendererAdapterPlatformRequestUnion = request): RendererAdapterPlatformDeterminismReport { const first = executePlatform(request), second = executePlatform(equivalentRequest), requestEquivalent = equivalent(request, equivalentRequest), validationEquivalent = equivalent("validationResult" in first ? first.validationResult : first.readiness, "validationResult" in second ? second.validationResult : second.readiness), rendererOutputEquivalent = equivalent(outputOf(first), outputOf(second)), findingsEquivalent = equivalent("findings" in first ? first.findings : [], "findings" in second ? second.findings : []), evidenceEquivalent = equivalent("evidence" in first ? first.evidence : [], "evidence" in second ? second.evidence : []), summaryEquivalent = equivalent("summary" in first ? first.summary : null, "summary" in second ? second.summary : null), warningsEquivalent = equivalent(first.warnings, second.warnings), errorsEquivalent = equivalent(first.errors, second.errors), metadataEquivalent = equivalent(first.metadata, second.metadata), violations: string[] = []; if (!requestEquivalent) violations.push("Platform requests are not equivalent"); if (!validationEquivalent) violations.push("Validation results are not equivalent"); if (!rendererOutputEquivalent) violations.push("Renderer outputs are not equivalent"); if (!findingsEquivalent) violations.push("Findings are not equivalent"); if (!evidenceEquivalent) violations.push("Evidence is not equivalent"); if (!summaryEquivalent) violations.push("Summaries are not equivalent"); if (!warningsEquivalent) violations.push("Warnings are not equivalent"); if (!errorsEquivalent) violations.push("Errors are not equivalent"); if (!metadataEquivalent) violations.push("Metadata is not equivalent"); return freezeRendererObject({ deterministic: violations.length === 0, requestEquivalent, validationEquivalent, rendererOutputEquivalent, findingsEquivalent, evidenceEquivalent, summaryEquivalent, warningsEquivalent, errorsEquivalent, metadataEquivalent, violations }); }

export function isRendererAdapterPlatformReadyResult(result: NexoraObjectDirectorRendererAdapterPlatformResultUnion): boolean { return result.metadata.status === "ready" && ("ready" in result ? result.ready : result.valid && result.accepted); }
export function isRendererAdapterPlatformDegradedResult(result: NexoraObjectDirectorRendererAdapterPlatformResultUnion): boolean { return result.metadata.status === "degraded"; }
export function isRendererAdapterPlatformBlockedResult(result: NexoraObjectDirectorRendererAdapterPlatformResultUnion): boolean { return result.metadata.status === "blocked"; }

export function verifyRendererAdapterPlatform(): NexoraObjectDirectorRendererAdapterPlatformVerificationReport {
  const identityValid = platformId === "NOL-5:6/NexoraObjectDirectorRendererAdapterPlatform", namespaceValid = platformNamespace === "nexora.nol.renderer.adapter.platform", versionValid = platformVersion === "5.6.0", statusValid = platformStatus === "Platform", lockValid = platformLock === "NOL-5-6-DIRECTOR-RENDERER-ADAPTER-PLATFORM-LOCKED", dependencyValid = rendererAdapterPlatformGuarantees.validationOnlyDependency, validationCompatible = verifyRendererAdapterValidation().valid && rendererAdapterPlatformCompatibility.validationIdentity === validationId, modesValid = rendererAdapterPlatformModes.join("|") === "strict|compatible", operationsValid = rendererAdapterPlatformOperations.join("|") === "single|collection|inspect", configurationValidValue = configurationValid(rendererAdapterPlatformDefaultConfiguration), capabilitiesValid = rendererAdapterPlatformCapabilities.length === rendererAdapterPlatformCapabilityCount && rendererAdapterPlatformCapabilities.every((entry, index) => entry.order === index + 1), pipelineValid = rendererAdapterPlatformPipeline.length === rendererAdapterPlatformPipelineStepCount && rendererAdapterPlatformPipeline.every((entry, index) => entry.order === index + 1), registryValid = rendererAdapterPlatformRegistry.length === rendererAdapterPlatformRegistryCount && rendererAdapterPlatformPublicApiSurface.length === rendererAdapterPlatformPublicApiCount, guaranteesValid = Object.values(rendererAdapterPlatformGuarantees).every((value) => value === true), healthValid = assessRendererAdapterPlatformHealth().healthy, readinessValid = assessRendererAdapterPlatformReadiness().ready;
  const probeRuntime = freezeRendererObject({ runtimeObjectId: "platform-probe-runtime", objectId: "platform-probe-object", sceneObjectId: "platform-probe-scene", sourceCommandIds: [], generation: 1, lifecycle: "Active", visible: true, interactive: true, focused: false, operating: false, attentionLevel: "None", renderingLevel: "Normal", cameraIntent: "None", relationshipMode: "Direct", labelMode: "Full", indicatorMode: "Essential", animationPending: false, lastExecutionState: "Completed", updatedAt: "platform-probe" });
  const probe = freezeRendererObject({ platformRequestId: "platform-probe", consumerId: "platform-verifier", operation: "single", runtimeObject: probeRuntime, sourceRuntimeId: "platform-probe-runtime", configuration: rendererAdapterPlatformDefaultConfiguration } as const satisfies NexoraObjectDirectorRendererAdapterPlatformRequest), deterministicExecutionValid = verifyRendererAdapterPlatformDeterminism(probe).deterministic, publicSurfacesFrozen = [rendererAdapterPlatformModes, rendererAdapterPlatformOperations, rendererAdapterPlatformStatuses, rendererAdapterPlatformDefaultConfiguration, rendererAdapterPlatformCapabilities, rendererAdapterPlatformPipeline, rendererAdapterPlatformGuarantees, rendererAdapterPlatformCompatibility, rendererAdapterPlatformRegistry, rendererAdapterPlatformPublicApiSurface].every(verifyRendererValueFrozen), prohibitedCapabilitiesAbsent = rendererAdapterPlatformGuarantees.rendererExecutionForbidden && rendererAdapterValidationPolicy.rendererExecutionForbidden, violations: string[] = [];
  if (!identityValid) violations.push("Platform identity is invalid"); if (!namespaceValid) violations.push("Platform namespace is invalid"); if (!versionValid) violations.push("Platform version is invalid"); if (!statusValid) violations.push("Platform status is invalid"); if (!lockValid) violations.push("Platform lock is invalid"); if (!dependencyValid) violations.push("Platform dependency is invalid"); if (!validationCompatible) violations.push("Validation compatibility is invalid"); if (!modesValid) violations.push("Platform modes are invalid"); if (!operationsValid) violations.push("Platform operations are invalid"); if (!configurationValidValue) violations.push("Default configuration is invalid"); if (!capabilitiesValid) violations.push("Platform capabilities are invalid"); if (!pipelineValid) violations.push("Platform pipeline is invalid"); if (!registryValid) violations.push("Platform registry is invalid"); if (!guaranteesValid) violations.push("Platform guarantees are invalid"); if (!healthValid) violations.push("Platform health is invalid"); if (!readinessValid) violations.push("Platform readiness is invalid"); if (!deterministicExecutionValid) violations.push("Platform execution is not deterministic"); if (!publicSurfacesFrozen) violations.push("A Platform public surface is mutable"); if (!prohibitedCapabilitiesAbsent) violations.push("A prohibited capability is present");
  return freezeRendererObject({ valid: violations.length === 0, identityValid, namespaceValid, versionValid, statusValid, lockValid, dependencyValid, validationCompatible, modesValid, operationsValid, configurationValid: configurationValidValue, capabilitiesValid, pipelineValid, registryValid, guaranteesValid, healthValid, readinessValid, deterministicExecutionValid, publicSurfacesFrozen, prohibitedCapabilitiesAbsent, violations });
}
