import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { describe, it } from "node:test";
import { type NexoraDirectorRuntimeObjectState } from "./nexoraObjectDirectorRendererAdapterFoundation.ts";
import { createRendererAdapterInputContract, type NexoraObjectDirectorRendererAdapterInputContract } from "./nexoraObjectDirectorRendererAdapterContracts.ts";
import { type NexoraObjectDirectorRendererAdapterEngineCollectionRequest, type NexoraObjectDirectorRendererAdapterEngineRequest } from "./nexoraObjectDirectorRendererAdapterEngine.ts";
import { integrateRendererAdapterObject, type NexoraObjectDirectorRendererAdapterCollectionIntegrationRequest, type NexoraObjectDirectorRendererAdapterIntegrationRequest, type NexoraObjectDirectorRendererAdapterIntegrationResult, type RendererAdapterIntegrationMode, type RendererObject } from "./nexoraObjectDirectorRendererAdapterIntegration.ts";
import {
  assessRendererAdapterValidationReadiness,
  collectRendererAdapterValidationEvidence,
  collectRendererAdapterValidationFindings,
  createRendererAdapterValidationFinding,
  createRendererAdapterValidationSummary,
  executeRendererAdapterCollectionValidation,
  executeRendererAdapterValidation,
  isRendererAdapterCollectionValidationSuccessful,
  isRendererAdapterValidationSuccessful,
  rendererAdapterValidationCompatibility,
  rendererAdapterValidationPipeline,
  rendererAdapterValidationPipelineStepCount,
  rendererAdapterValidationPolicy,
  rendererAdapterValidationPublicApiCount,
  rendererAdapterValidationPublicApiSurface,
  rendererAdapterValidationRegistry,
  rendererAdapterValidationRegistryCount,
  rendererAdapterValidationRuleCategories,
  rendererAdapterValidationRuleCategoryCount,
  rendererAdapterValidationRuleCount,
  rendererAdapterValidationRules,
  rendererAdapterValidationSeverities,
  rendererAdapterValidationSeverityCount,
  validateRendererAdapterCollectionIntegrationResult,
  validateRendererAdapterCollectionValidationRequest,
  validateRendererAdapterIntegrationResult,
  validateRendererAdapterIntegrationSummary,
  validateRendererAdapterIntegrationTrace,
  validateRendererAdapterRendererObject,
  validateRendererAdapterSeedColor,
  validateRendererAdapterValidationRequest,
  validationId,
  validationLock,
  validationNamespace,
  validationStatus,
  validationVersion,
  verifyRendererAdapterRuntimeImmutability,
  verifyRendererAdapterValidation,
  verifyRendererAdapterValidationDeterminism,
  type NexoraObjectDirectorRendererAdapterCollectionValidationRequest,
  type NexoraObjectDirectorRendererAdapterValidationRequest,
} from "./nexoraObjectDirectorRendererAdapterValidation.ts";

function freeze<T>(value: T, seen = new Set<object>()): T { if (value === null || typeof value !== "object" || seen.has(value as object)) return value; seen.add(value as object); Object.values(value as Record<string, unknown>).forEach((child) => freeze(child, seen)); return Object.freeze(value); }
function deeplyFrozen(value: unknown, seen = new Set<object>()): boolean { if (value === null || typeof value !== "object" || seen.has(value as object)) return true; if (!Object.isFrozen(value)) return false; seen.add(value as object); return Object.values(value as Record<string, unknown>).every((child) => deeplyFrozen(child, seen)); }
function runtime(id = "one", overrides: Readonly<Record<string, unknown>> = {}): NexoraDirectorRuntimeObjectState { return freeze({ runtimeObjectId: `runtime-${id}`, objectId: id, sceneObjectId: `scene-${id}`, sourceCommandIds: [], generation: 1, lifecycle: "Active", visible: true, interactive: true, focused: false, operating: false, attentionLevel: "None", renderingLevel: "Normal", cameraIntent: "None", relationshipMode: "Direct", labelMode: "Full", indicatorMode: "Essential", animationPending: false, lastExecutionState: "Completed", updatedAt: "2035-01-01T00:00:00.000Z", ...overrides } as NexoraDirectorRuntimeObjectState); }
function engineRequest(runtimeObject = runtime(), strict = true): NexoraObjectDirectorRendererAdapterEngineRequest { return freeze({ requestId: `engine-${runtimeObject.runtimeObjectId}`, input: createRendererAdapterInputContract(runtimeObject, runtimeObject.runtimeObjectId), strict, includeWarnings: true }); }
function integrationRequest(mode: RendererAdapterIntegrationMode = "strict", runtimeObject = runtime()): NexoraObjectDirectorRendererAdapterIntegrationRequest { return freeze({ integrationId: "integration-1", consumerId: "consumer-1", mode, includeTrace: true, includeSummary: true, engineRequest: engineRequest(runtimeObject, mode === "strict") }); }
function validationRequest(options: Partial<NexoraObjectDirectorRendererAdapterValidationRequest> = {}): NexoraObjectDirectorRendererAdapterValidationRequest { return freeze({ validationId: "validation-1", integrationRequest: integrationRequest(), executeIntegration: true, includeFindings: true, includeEvidence: true, failOnWarning: false, ...options }); }
function collectionIntegrationRequest(inputs: readonly NexoraObjectDirectorRendererAdapterInputContract[], mode: RendererAdapterIntegrationMode): NexoraObjectDirectorRendererAdapterCollectionIntegrationRequest { const engineRequest: NexoraObjectDirectorRendererAdapterEngineCollectionRequest = freeze({ requestId: "engine-collection", inputs, strict: mode === "strict", includeWarnings: true, preserveOrder: true }); return freeze({ integrationId: "integration-collection", consumerId: "consumer-1", mode, includeTrace: true, includeSummary: true, engineRequest, preserveOrder: true }); }
function collectionValidationRequest(inputs: readonly NexoraObjectDirectorRendererAdapterInputContract[], mode: RendererAdapterIntegrationMode): NexoraObjectDirectorRendererAdapterCollectionValidationRequest { return freeze({ validationId: "validation-collection", integrationRequest: collectionIntegrationRequest(inputs, mode), executeIntegration: true, includeFindings: true, includeEvidence: true, failOnWarning: false, preserveOrder: true }); }
const source = readFileSync(new URL("./nexoraObjectDirectorRendererAdapterValidation.ts", import.meta.url), "utf8");

describe("NOL-5:5 Director Renderer Adapter Validation", () => {
  it("1-10. exposes exact identity and an Integration-only production dependency", () => { assert.equal(validationId, "NOL-5:5/NexoraObjectDirectorRendererAdapterValidation"); assert.equal(validationVersion, "5.5.0"); assert.equal(validationNamespace, "nexora.nol.renderer.adapter.validation"); assert.equal(validationStatus, "Validation"); assert.equal(validationLock, "NOL-5-5-DIRECTOR-RENDERER-ADAPTER-VALIDATION-LOCKED"); const imports = [...source.matchAll(/from\s+["']([^"']+)["']/g)].map((match) => match[1]); assert.deepEqual(imports, ["./nexoraObjectDirectorRendererAdapterIntegration.ts"]); assert.doesNotMatch(imports.join(" "), /Engine|Contracts|Foundation|nexoraObjectDirectorRuntime/i); });

  it("11-31 and 100. exposes exact ordered, dynamically counted, frozen registries", () => { assert.deepEqual(rendererAdapterValidationSeverities, ["info", "warning", "error", "critical"]); assert.equal(rendererAdapterValidationSeverityCount, rendererAdapterValidationSeverities.length); assert.deepEqual(rendererAdapterValidationRuleCategories, ["identity", "dependency", "request", "integration", "renderer-output", "collection", "determinism", "immutability", "compatibility", "architecture"]); assert.equal(rendererAdapterValidationRuleCategoryCount, rendererAdapterValidationRuleCategories.length); assert.deepEqual(rendererAdapterValidationRules.map((entry) => entry.id), ["VAL-IDENTITY-001", "VAL-DEPENDENCY-001", "VAL-REQUEST-001", "VAL-REQUEST-002", "VAL-INTEGRATION-001", "VAL-INTEGRATION-002", "VAL-OUTPUT-001", "VAL-OUTPUT-002", "VAL-OUTPUT-003", "VAL-OUTPUT-004", "VAL-COLLECTION-001", "VAL-COLLECTION-002", "VAL-COLLECTION-003", "VAL-DETERMINISM-001", "VAL-IMMUTABILITY-001", "VAL-IMMUTABILITY-002", "VAL-COMPATIBILITY-001", "VAL-ARCHITECTURE-001", "VAL-ARCHITECTURE-002", "VAL-ARCHITECTURE-003"]); assert.deepEqual(rendererAdapterValidationRules.map((entry) => entry.order), Array.from({ length: 20 }, (_, index) => index + 1)); assert.equal(rendererAdapterValidationRuleCount, rendererAdapterValidationRules.length); assert.deepEqual(rendererAdapterValidationPipeline.map((entry) => entry.order), Array.from({ length: 11 }, (_, index) => index + 1)); assert.equal(rendererAdapterValidationPipelineStepCount, rendererAdapterValidationPipeline.length); assert.equal(rendererAdapterValidationRegistryCount, rendererAdapterValidationRegistry.length); assert.equal(rendererAdapterValidationPublicApiCount, rendererAdapterValidationPublicApiSurface.length); for (const value of [rendererAdapterValidationSeverities, rendererAdapterValidationRuleCategories, rendererAdapterValidationRules, rendererAdapterValidationPipeline, rendererAdapterValidationPolicy, rendererAdapterValidationCompatibility, rendererAdapterValidationRegistry, rendererAdapterValidationPublicApiSurface]) assert.equal(deeplyFrozen(value), true); });

  it("32-35. validates requests, rejects malformed structure, and supports inspection only", () => { assert.equal(validateRendererAdapterValidationRequest(validationRequest()).valid, true); assert.equal(validateRendererAdapterValidationRequest(validationRequest({ validationId: "" })).validationIdValid, false); assert.equal(validateRendererAdapterValidationRequest({ ...validationRequest(), integrationRequest: null } as unknown as NexoraObjectDirectorRendererAdapterValidationRequest).integrationRequestValid, false); const inspected = executeRendererAdapterValidation(validationRequest({ executeIntegration: false })); assert.equal(inspected.valid, true); assert.equal(inspected.accepted, false); assert.equal(inspected.integrationExecuted, false); assert.equal(inspected.integrationResult, null); });

  it("36-40. validates strict execution, strict rejection, and reported compatible fallback", () => { const strict = executeRendererAdapterValidation(validationRequest()), fallbackRequest = validationRequest({ integrationRequest: integrationRequest("compatible", runtime("fallback", { lifecycle: "Unmapped" })) }), fallback = executeRendererAdapterValidation(fallbackRequest), strictRejected = executeRendererAdapterValidation(validationRequest({ integrationRequest: integrationRequest("strict", runtime("failed", { lifecycle: "Unmapped" })) })); assert.equal(strict.valid && strict.accepted, true); assert.equal(fallback.valid && fallback.accepted, true); assert.ok(fallback.warnings.length > 0); assert.equal(strictRejected.accepted, false); assert.equal(strictRejected.integrationResult?.rendererObject, null); });

  it("41-50. detects missing output, invalid state, visibility, palette, mutable data, and executable handles", () => { const validResult = integrateRendererAdapterObject(integrationRequest()), object = validResult.rendererObject as RendererObject; assert.equal(validateRendererAdapterRendererObject(object).every((item) => item.valid), true); const missing = validateRendererAdapterRendererObject(null); assert.equal(missing.some((item) => item.ruleId === "VAL-OUTPUT-001" && !item.valid), true); const invalidState = freeze({ ...object, metadata: freeze({ ...object.metadata, rendererState: "immersive" }) }); assert.equal(validateRendererAdapterRendererObject(invalidState).some((item) => item.ruleId === "VAL-OUTPUT-002" && !item.valid), true); const invalidVisibility = freeze({ ...object, visibility: "ghosted" }); assert.equal(validateRendererAdapterRendererObject(invalidVisibility).some((item) => item.ruleId === "VAL-OUTPUT-003" && !item.valid), true); const invalidColor = freeze({ ...object, color: freeze({ ...object.color, base: "Purple" }) }); assert.equal(validateRendererAdapterSeedColor(invalidColor.color).some((item) => !item.valid), true); const mutable = { ...object, badges: [...object.badges], metadata: { ...object.metadata } }; assert.equal(validateRendererAdapterRendererObject(mutable).some((item) => item.ruleId === "VAL-IMMUTABILITY-001" && !item.valid), true); const executable = freeze({ ...object, metadata: freeze({ ...object.metadata, callback: () => true }) }); assert.equal(validateRendererAdapterRendererObject(executable).some((item) => item.ruleId === "VAL-ARCHITECTURE-001" && !item.valid), true); });

  it("39-40. rejects a compatible neutral fallback when its warning is suppressed", () => { const original = integrateRendererAdapterObject(integrationRequest("compatible", runtime("fallback", { lifecycle: "Unmapped" }))), tampered = freeze({ ...original, warnings: freeze([]), engineResult: freeze({ ...original.engineResult, warnings: freeze([]) }) }) as NexoraObjectDirectorRendererAdapterIntegrationResult; assert.equal(validateRendererAdapterIntegrationResult(tampered).some((item) => item.code === "FALLBACK_WARNING_MISSING" && !item.valid), true); });

  it("51-56. validates summaries and traces and detects count, stage, duplicate, and completion defects", () => { const result = integrateRendererAdapterObject(integrationRequest()); assert.equal(validateRendererAdapterIntegrationSummary(result.summary, result).every((item) => item.valid), true); const badSummary = freeze({ ...result.summary!, outputCount: 99 }); assert.equal(validateRendererAdapterIntegrationSummary(badSummary, result).some((item) => !item.valid), true); assert.equal(validateRendererAdapterIntegrationTrace(result.trace).every((item) => item.valid), true); const trace = result.trace!; for (const stages of [[...trace.stages, "unknown"], [trace.stages[0], trace.stages[0]], trace.stages.slice(0, 2)]) { const invalid = freeze({ ...trace, stages: freeze(stages), completed: true }) as unknown as typeof trace; assert.equal(validateRendererAdapterIntegrationTrace(invalid).some((item) => !item.valid), true); } });

  it("57-68. validates collection counts, order, alignment, strict rejection, and compatible partial truth", () => { const a = createRendererAdapterInputContract(runtime("a"), "runtime-a"), b = createRendererAdapterInputContract(runtime("b"), "runtime-b"), invalid = freeze({ runtimeObject: null, sourceRuntimeId: "runtime-invalid", preserveRuntimeMetadata: true }) as unknown as NexoraObjectDirectorRendererAdapterInputContract; assert.equal(validateRendererAdapterCollectionValidationRequest(collectionValidationRequest([a, b], "strict")).valid, true); const valid = executeRendererAdapterCollectionValidation(collectionValidationRequest([a, b], "strict")), strict = executeRendererAdapterCollectionValidation(collectionValidationRequest([a, invalid], "strict")), partial = executeRendererAdapterCollectionValidation(collectionValidationRequest([invalid, b], "compatible")); assert.equal(valid.valid && valid.accepted, true); assert.equal(valid.sourceCount, 2); assert.equal(valid.outputCount, 2); assert.equal(valid.failedItemCount, 0); assert.deepEqual(valid.itemResults.map((item) => [item.index, item.sourceRuntimeId]), [[0, "runtime-a"], [1, "runtime-b"]]); assert.equal(strict.accepted, false); assert.deepEqual(strict.integrationResult?.rendererObjects, []); assert.equal(partial.accepted, true); assert.equal(partial.failedItemCount, 1); assert.equal(partial.itemResults[0].accepted, false); assert.equal(partial.itemResults[1].accepted, true); assert.deepEqual(partial.integrationResult?.rendererObjects.map((object) => object.id), ["runtime-b"]); assert.equal(validateRendererAdapterCollectionIntegrationResult(partial.integrationResult!, partial.integrationResult ? collectionValidationRequest([invalid, b], "compatible").integrationRequest : undefined).every((item) => item.valid), true); });

  it("69-70. orders findings by rule and removes exact duplicates stably", () => { const state = createRendererAdapterValidationFinding({ ruleId: "VAL-OUTPUT-002", valid: false, code: "STATE", message: "Bad state.", path: "state", expected: "minimum", actual: "bad" }), identity = createRendererAdapterValidationFinding({ ruleId: "VAL-IDENTITY-001", valid: true, code: "IDENTITY", message: "Good identity.", path: "identity", expected: true, actual: true }), collected = collectRendererAdapterValidationFindings([state, identity], [state]); assert.deepEqual(collected.map((item) => item.ruleId), ["VAL-IDENTITY-001", "VAL-OUTPUT-002"]); assert.equal(collected.length, 2); assert.equal(deeplyFrozen(collected), true); });

  it("71-73. includes or omits evidence and rejects executable evidence", () => { const included = executeRendererAdapterValidation(validationRequest()), omitted = executeRendererAdapterValidation(validationRequest({ includeEvidence: false })); assert.ok(included.evidence.length > 0); assert.deepEqual(omitted.evidence, []); assert.equal(deeplyFrozen(included.evidence), true); assert.throws(() => collectRendererAdapterValidationEvidence([{ identity: "bad", source: "test", path: "value", value: () => true, frozen: false }]), /plain values/); });

  it("74-78. computes summary policy from internal findings even when public findings are omitted", () => { const warning = createRendererAdapterValidationFinding({ ruleId: "VAL-INTEGRATION-001", severity: "warning", valid: false, code: "WARN", message: "Warning failure.", path: "warning", expected: true, actual: false }), error = createRendererAdapterValidationFinding({ ruleId: "VAL-REQUEST-001", valid: false, code: "ERROR", message: "Error failure.", path: "request", expected: true, actual: false }), critical = createRendererAdapterValidationFinding({ ruleId: "VAL-IDENTITY-001", valid: false, code: "CRITICAL", message: "Critical failure.", path: "identity", expected: true, actual: false }); assert.equal(createRendererAdapterValidationSummary([warning], false).valid, true); assert.equal(createRendererAdapterValidationSummary([warning], true).valid, false); assert.equal(createRendererAdapterValidationSummary([error], false).valid, false); assert.equal(createRendererAdapterValidationSummary([critical], false).valid, false); const omitted = executeRendererAdapterValidation(validationRequest({ includeFindings: false })); assert.deepEqual(omitted.findings, []); assert.ok(omitted.summary.findingCount > 0); });

  it("79-85. preserves messages and inputs while freezing findings, evidence, and summaries", () => { const runtimeObject = runtime("immutable"), before = JSON.stringify(runtimeObject), result = executeRendererAdapterValidation(validationRequest({ integrationRequest: integrationRequest("compatible", runtimeObject) })); assert.equal(JSON.stringify(runtimeObject), before); assert.equal(deeplyFrozen(result), true); assert.equal(deeplyFrozen(result.findings), true); assert.equal(deeplyFrozen(result.evidence), true); assert.equal(deeplyFrozen(result.summary), true); assert.deepEqual(verifyRendererAdapterRuntimeImmutability(runtimeObject, runtimeObject), { immutable: true, structurallyEquivalent: true, referenceMutationDetected: false, violations: [] }); });

  it("86-90 and 99. proves repeated and cloned single and collection determinism and predicates", () => { const single = validationRequest(), collection = collectionValidationRequest([createRendererAdapterInputContract(runtime("a"), "runtime-a")], "compatible"); assert.deepEqual(executeRendererAdapterValidation(single), executeRendererAdapterValidation(single)); assert.deepEqual(executeRendererAdapterCollectionValidation(collection), executeRendererAdapterCollectionValidation(collection)); const cloned = freeze({ ...single, integrationRequest: freeze({ ...single.integrationRequest, engineRequest: freeze({ ...single.integrationRequest.engineRequest, input: freeze({ ...single.integrationRequest.engineRequest.input }) }) }) }); assert.equal(verifyRendererAdapterValidationDeterminism(single, cloned).deterministic, true); assert.equal(isRendererAdapterValidationSuccessful(executeRendererAdapterValidation(single)), true); assert.equal(isRendererAdapterCollectionValidationSuccessful(executeRendererAdapterCollectionValidation(collection)), true); });

  it("91-98. verifies readiness, compatibility, architecture, determinism, and no repair behavior", () => { assert.deepEqual(rendererAdapterValidationCompatibility, { validationIdentity: validationId, integrationIdentity: "NOL-5:4/NexoraObjectDirectorRendererAdapterIntegration", compatibleIntegrationVersion: "5.4.0", integrationOnlyDependency: true, singleValidationCompatible: true, collectionValidationCompatible: true, strictModeCompatible: true, compatibleModeCompatible: true, rendererFrameworkAgnostic: true }); assert.deepEqual(assessRendererAdapterValidationReadiness(), { ready: true, identityReady: true, dependencyReady: true, integrationReady: true, rulesReady: true, policyReady: true, compatibilityReady: true, deterministicValidationReady: true, publicSurfacesFrozen: true, violations: [] }); const report = verifyRendererAdapterValidation(); assert.equal(report.valid, true); assert.equal(deeplyFrozen(report), true); assert.doesNotMatch(source, /from\s+["'][^"']*(?:Engine|Contracts|Foundation|nexoraObjectDirectorRuntime|react|next|three|webgl|canvas|svg|dom)/i); assert.doesNotMatch(source, /\b(?:async|await|Promise|setTimeout|setInterval|fetch|localStorage|sessionStorage|window|document|globalThis|Math\.random|Date\b|Worker|process|filesystem)\b|new\s+(?:Mesh|Scene|Camera|Renderer)|console\./); assert.match(source, /validationDoesNotRepair:\s*true/); });
});
